### ISSUE TITLE
MacOS: Paste shortcut doesn't work

### ISSUE THREAD

**Issue by Kurdy34** [Eugeny/terminus#1002]
Terminus v1.0.79.1358
MacOS 10.14.5

Cmd+V doesn't works, we need to go through Edit/Paste to paste the clipboard
(Cmd+C works)

**Comment by IgnusG** [comment]
Does Cmd+Shift+V work?

**Comment by Kurdy34** [comment]
Nope

**Comment by IgnusG** [comment]
If you go to Settings ->Hotkeys and Re-Assign `Paste from keyboard` does it work?

**Comment by Kurdy34** [comment]
Yep! It works :)
I think it would be preferable to add this by default.

Anyway, I close this issue 👍
