### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by febridev** [Eugeny/terminus#101]
If i go to setting > terminal terminus application is blank 

note:
windows 7 Profesional x64 
![blank_page](https://user-images.githubusercontent.com/1490986/27958954-9d144428-634f-11e7-8e04-5cd287c561ea.jpg)

**Comment by equinox** [comment]
Are you running from source (if so, what commit)?

If prebuilt Terminus.Setup.1.0.0-alpha.*.exe from GitHub Releases, what version?

Are you able to reproduce it reliably? If so, try starting Terminus with --debug (i.e `terminus.exe --debug`) so it opens with the Chrome dev tools and you can see what the error is in the console.

**Comment by Eugeny** [comment]
Terminus shouldn't crash anymore due to plugin problems.
