### ISSUE TITLE
Some hotkeys are not working

### ISSUE THREAD

**Issue by laurenz-glueck** [Eugeny/terminus#1014]
Hey @Eugeny,

short question regarding the hotkeys. I'm just trying to switch from iTerm to Terminus and would like to use the `Toggle terminal window` hotkey as I had it with iTerm on `Ctrl-<`.

Unfortunately when I set it to `Ctrl-<`, it's not working... The default `Ctrl-Space` is working fine... I also tried some other combinations like `Ctrl-Y` - also not working 😕

I'm using Terminus 1.0.79 on macOS 10.14.5

Looking forward to your response ☺️
Laurenz

**Comment by Eugeny** [comment]
Could it be related to the keyboard layout? Both < and Y have different locations in the German layout.

**Comment by laurenz-glueck** [comment]
Thanks for your fast response! I changed my keyboard layout from German to US and updated the hotkey. Afterwords I switched back the layout and it's now working fine 👌🏼

**Comment by dfyx** [comment]
I'm seeing the same problem in Windows 10 where your workaround does not appear to work. No matter which keyboard layout I have set in Windows, the settings page interprets `Ctrl+<` as `Ctrl+\` (which should be alright as that's the same physical key in the respective layouts). Actually using the hotkey doesn't work though.

**Comment by z-impi** [comment]
I think i have the same issue. My custom shortcuts are not working. only the default ones.
I switched toggle tabby window from `strg+space` to `F12` and its not working.
Other combinations also don't work. Posted this because i think its related.
As stated the defaults are working.
