### ISSUE TITLE
Resizing window - Content does not redraw

### ISSUE THREAD

**Issue by jrock2004** [Eugeny/terminus#102]
Just started using this tool and I have noticed that when you resize the terminal, the content is not resizing to new height and width

![image](https://user-images.githubusercontent.com/655716/27960014-afbaf5c0-62f7-11e7-8481-dac4ad85e0e2.png)

Then I resize

![image](https://user-images.githubusercontent.com/655716/27960007-a5b70b22-62f7-11e7-9a46-e8b0a626c43b.png)

**Comment by Eugeny** [comment]
Please retry it with the latest alpha and also indicate on which platform and with which shell you're running Terminus

**Comment by Eugeny** [comment]
Closing due to the lack of activity. Please feel free to reopen if the issue is still relevant!

**Comment by mattias93** [comment]
I'm affected as well, W10 1809 - 17763.973, Terminus 1.0.102, no plugins.
