### ISSUE TITLE
Weird Syntax Background Color Issue

### ISSUE THREAD

**Issue by jstanley23** [Eugeny/terminus#1025]
Version: 1.0.78
Platform: win32 10.0.16299
Plugins: none

Have a weird issue where colors for syntax and background are getting all messed up. I have noticed it doing multiple different actions, but the one I am always able to replicate is when I am ssh'd to a system and edit a file using vim.

I can open a text file, search for a term, then scroll up and the whole screen turns yellow.

https://imgur.com/5SJE5LF

**Comment by IgnusG** [comment]
Does it go away if you click on the terminal with the mouse?

**Comment by jstanley23** [comment]
I uninstalled and re-installed and have not been able to duplicate
