### ISSUE TITLE
I can't open two or more apps

### ISSUE THREAD

**Issue by NDelt** [Eugeny/terminus#1031]
If there is an already opened Terminus application and try to open a new terminal, the existing one is killed. I can't open two or more Terminus apps at the same time.

It would be great if newly opened terminal is integrated into existing terminal as a tab.

I'm using Alpha 79.

**Comment by GeoBSI** [comment]
Same issue here, existing window getting kill if trying to open a new one. 
Can't use shell "Open Terminus here" if Terminus is already opened.
On Alpha 81

**Comment by zhanqiuzhang** [comment]
Same issue on Alpha 81.

**Comment by NDelt** [comment]
It occurs on Alpha 82. If I reopen terminal, everything is empty.
![Capture](https://user-images.githubusercontent.com/46282492/60393572-acc92e00-9b52-11e9-98f2-1ce7b412b6cf.PNG)
