### ISSUE TITLE
Error: Cannot find module 'npm' under Mac OS v1.0.79

### ISSUE THREAD

**Issue by CreativeBulma** [Eugeny/terminus#1038]
I just installed last version (1.0.79) and I get the following error message (NPM is well installed and npm command is working in termnial) when trying to install plugin.

<code>
Error: Cannot find module 'npm'
Require stack:
- /Applications/Terminus.app/Contents/Resources/app.asar/dist/index.html
</code>

**Comment by Novezeil** [comment]
Same - but on both Windows 10 and OSX.

**Comment by Eugeny** [comment]
Duplicate of #714
