### ISSUE TITLE
Invisible Text when connecting to SSH

### ISSUE THREAD

**Issue by KlotzJesse** [Eugeny/terminus#1039]
Version: 1.0.80
Platform: win32 10.0.17763
Plugins: none

Since the newest version I don't have any text (output) anymore and nothing else for a SSH connection with SSH Key. Just an empty window.

A bug like this should not contain a version which is not a test version...

**Comment by LambofanHD** [comment]
Same Issue :(

**Comment by dziban303** [comment]
Same. Crippling bug. Had to drop down to 1.0.79. Shell Selector plugin is also broken now.

**Comment by IgnusG** [comment]
Does your output look like the on in https://github.com/Eugeny/terminus/issues/1044?

**Comment by IgnusG** [comment]
Please open another issue for the shell selector plugin with as much details as you can provide

**Comment by Eugeny** [comment]
Duplicate of #1044
