### ISSUE TITLE
Set multiple fonts for font-fallback.

### ISSUE THREAD

**Issue by PMExtra** [Eugeny/terminus#1041]
I'm used to using `Droid Sans Mono for Powerline` font, but I usually work with asian characters such as Chinese or Japanese in my shell.

For now, the font-fallback is follow the systemlink, but it's a very outdated and complex way to set.
I think it looks awesome if I can set multiple fonts in Terminus.

Well known, Terminus is built with electron that is based web technique. So I have tried to use css `font` syntax to set multiple fonts, and finally it works with below:

```
Droid Sans Mono for Powerline Regular", "Microsoft Yahei", "Microsoft JhengHei
```

Note that there should be no quote character at start or end. Then it works right with shell windows but not shown correctly in the "preview" panel of settings.

It would be great if you can fix the "preview" panel and make a more sensible font setting UI.

**Comment by Eugeny** [comment]
Fixed - behaviour is now the same between preview and the actual terminal. Multiple fonts can be specified, separated with commas, with or without quotes.

I've also fixed the bundled last-resort fallback font to work with xterm.

**Comment by Eugeny** [comment]
@allcontributors add @PMExtra for bugs
