### ISSUE TITLE
Does not display terminal for SSH

### ISSUE THREAD

**Issue by bwpetty** [Eugeny/terminus#1044]
Version: 1.0.80
Platform: win32 10.0.17763
Plugins: altair, clickable-links, theme-hype, theme-windows10

When opening SSH to (previously working) Raspberry Pi connection, does not display terminal window. Can log into Pi from WSL using SSH. Some text is being sent if typing is done in blank SSH window, can echo in simultaneously logged-in SSH session from WSL terminal.

Tried removing all additional add-ons that were not installed prior to issue, restarting, reinstalling, etc.
![image](https://user-images.githubusercontent.com/21268273/59151829-d4235400-8a07-11e9-94c0-3a40e64b5004.png)

**Comment by ylhelloworld** [comment]
I have the same problem.

**Comment by Novezeil** [comment]
Same on OSX. Noticed the text are there (link detectable), just not being shown.

**Comment by 3rm4k0ff** [comment]
![image](https://user-images.githubusercontent.com/8244225/59156738-5451c400-8ab1-11e9-9b53-c5be00dd375c.png)
I have some problem on windows
This is debug.

**Comment by binford6000** [comment]
Same here. But i've encountered some blue frame from AVAST AV around the Terminus window. Since then this error occurs.

**Comment by IgnusG** [comment]
Avast keeps flagging new Terminus versions as potential malware after each release. Seems to usually pass  after a couple of days. Maybe avast is trying to run it in sandbox mode?
