### ISSUE TITLE
Missing options to cygwin bash

### ISSUE THREAD

**Issue by j-santander** [Eugeny/terminus#105]
Just tried Terminus 1.0.0 alpha 19 on Windows 10 with Cygwin bash.
What I've noticed is that the PATH is not properly set (e.g. /usr/bin/ is not included in the PATH).
Comparing to the cygwin.bat terminus just run `bash`, while the bat file runs `bash --login -i`

**Comment by koraktor** [comment]
As a workaround you may create a batch file alongside `bash.exe`:

```batch
@ECHO OFF

"%~dp0bash.exe" --login -i
```

You can modify `config.yaml` in `%APPDATA%\terminus` to use the batch instead of the exe.
