### ISSUE TITLE
"New Terminal with Profile" doesn't work when there's no opened tabs

### ISSUE THREAD

**Issue by peidaqi** [Eugeny/terminus#1053]
Cannot select any of the profiles if there's no opened tabs on "New terminal with profile" from upper left corner - on Termius 1.0.81 with Windows 10 1903.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by peidaqi** [comment]
There's no console error output....
It's just when you start the program with no tabs opened, by clicking on "open terminal with profile", none of the drop-down items can be selected.

**Comment by IgnusG** [comment]
Can confirm - if all tabs are closed and the welcome screen is shown you can open the drop-down but clicking on the individual profiles has no effect

**Comment by Eugeny** [comment]
Can you check whether this happens with a freshly created profile?

**Comment by IgnusG** [comment]
![GIF](https://user-images.githubusercontent.com/6438760/59533498-ea3f8180-8eeb-11e9-8ab9-6324554ae96c.gif)
