### ISSUE TITLE
Run Powershell on Terminus as Admin 

### ISSUE THREAD

**Issue by adamantinum** [Eugeny/terminus#1064]
Hi, I would like to know if there is a way to launch an admin powershell instance on Terminus. 
Thank you in advance.

**Comment by Eugeny** [comment]
You can do it from the right-click context menu.

**Comment by adamantinum** [comment]
I have only "normal" powershell, without admin rights...
![image](https://user-images.githubusercontent.com/50221095/59361407-157e7100-8d32-11e9-84bb-5c6a90237b69.png)

**Comment by Eugeny** [comment]
Enable ConPTY under Settings > Shell

**Comment by adamantinum** [comment]
In this way?
![image](https://user-images.githubusercontent.com/50221095/59363487-8f642980-8d35-11e9-9737-2c4b733a75b8.png)

**Comment by Eugeny** [comment]
Oh sorry - this option is only available on Windows 10 build 18309 and higher.

**Comment by adamantinum** [comment]
Thank you very much! I've just upgraded and now it works!

**Comment by lackovic** [comment]
I am also trying to find a way to run **PowerShell Core** _as Administrator_: right clicking on the window does not show any context menu.

Using terminus `v1.0.101` on Windows 10 version `1909`.

My config file:
```js
hotkeys:
  profile: {}
  shell: {}
terminal:
  environment:
    ConPTY: Enable
  profile: powershell-core
  rightClick: menu
ssh: {}
appearance: {}
enableWelcomeTab: false

```
