### ISSUE TITLE
Settings scroll doesn't work (Windows 10)

### ISSUE THREAD

**Issue by AlexanderZon** [Eugeny/terminus#1065]
Version: 1.0.81-c10-g3a0d3ca
Platform: win32 10.0.17134
Plugins: none

**Comment by IgnusG** [comment]
That's my fault. The applied CSS styles got lost - will submit a PR shortly

**Comment by palkerecsenyi** [comment]
I'm using version 1.0.89 on Windows 10 and it still doesn't work for me.
