### ISSUE TITLE
[Feature Request] Hotkey for SSH connections

### ISSUE THREAD

**Issue by plrnr** [Eugeny/terminus#1067]
Please add a Hotkey to pull up "SSH Connections" pop up.

**Comment by yfwz100** [comment]
It seems that shortcut for ssh connections is available in config file.

![image](https://user-images.githubusercontent.com/983211/59545616-45f12580-8f53-11e9-970e-7d1e5bde1f3e.png)

**Comment by plrnr** [comment]
Excellent! I actually didn't have hotkeys>ssh in my config file, but I added per your screenshot and it worked. Perhaps this can be added to Hotkeys settings tab?
