### ISSUE TITLE
clear command not working with git bash 

### ISSUE THREAD

**Issue by OmranAbazid** [Eugeny/terminus#108]
Version: 1.0.0-alpha.19
Platform: win32 10.0.15063

look at the picture when i hit clear the cursor go to the top but without clearing the screen:

![image](https://user-images.githubusercontent.com/9063094/27992499-bbb71b8a-649e-11e7-9a38-67d647d9eed4.png)

**Comment by Eugeny** [comment]
Duplicate of #28
