### ISSUE TITLE
Opened tabs at startup behavior

### ISSUE THREAD

**Issue by sibbngheid** [Eugeny/terminus#1089]
Firstly `Auto-open a terminal at app start` is enabled in my settings.

When I'm launching terminus normally it is came with a terminal as expected. But when I right click my desktop and select `Open Terminus here` it is came with two tabs. One is my desktop, and one is default. I found it a little annoying. I think it only launch with one tab at my desktop.

Also when you close Terminus while Settings tab is open, after relaunch Settings tab is back. I think this behavior is completely unnecessary.

**Comment by sibbngheid** [comment]
Also when you click Open Terminus here at desktop then close terminus while 2 tabs are open and launch terminus directly, terminus comes with 2 tabs; a blank tab with "Terminal" title, and my my default custom shell.

**Comment by NDelt** [comment]
@Eugeny This issue is still not resolved.
![Honeycam 2019-08-14 17-54-03](https://user-images.githubusercontent.com/46282492/63007957-9a197700-bebc-11e9-90f6-e702d4ec1d9f.gif)

**Comment by Eugeny** [comment]
@Ndelt this is the expected behaviour - tabs are initialized when first clicked. 
In the original issue, other tabs stayed blank permanently

**Comment by NDelt** [comment]
@Eugeny Then, how to I make terminal to only one tab is opened after launching it?

**Comment by Eugeny** [comment]
@NDelt you can't do that - Terminus remembers the tabs that were previously open and restores them on start.

**Comment by NDelt** [comment]
@Eugeny May I open a feature request to add an option make Terminus to not remember the tabs previously opened?

**Comment by Eugeny** [comment]
Certainly
