### ISSUE TITLE
[bug] Cannot create custom tab without launching default shell

### ISSUE THREAD

**Issue by dudeisbrendan03** [Eugeny/terminus#1095]
Attempting to create a new shell from the start menu will not work unless there is already a tab open.

For example, if I wanted to open an Ubuntu shell I would have to hit the `+` first to create a shell, then hit the selection button and click what I want.

If I do not create the empty tab first then none of the buttons function.

*The menu I'm talking about to avoid confusion*
![Menu](https://i.imgur.com/FBr6cOp.png)

Running Terminus v1.0.82

**Comment by Eugeny** [comment]
Duplicate of #1053
