### ISSUE TITLE
[bug] Unable to scroll in plugins area

### ISSUE THREAD

**Issue by dudeisbrendan03** [Eugeny/terminus#1096]
~~*Haven't attempted to recreate*~~

~~On my first launch I enable acrylic then went into the plugins area. I was unable to scroll to view all the plugins.~~

~~Edit: This happened again when installing some plugins. It only happens when acrylic is enabled and is sorted by enabling and disabling acrylic.~~

Edit2: Plugins area doesn't have a scroll bar when launching. I have to go to plugins, go to another option, then back to plugins to scroll. I've tested this a couple times and this is what's happening.

~~I resolved this by relaunching, disabling acrylic, enabling acrylic then going to plugins. I haven't attempted to recreate this and it only happened on the first launch.~~

**Comment by ChipwizBen** [comment]
This seems to apply to any page in Settings. I've got a lot of hosts (400+) and 16 groups and scrolling doesn't work without the trick detailed by @dudeisbrendan03:

"I have to go to plugins, go to another option, then back to plugins to scroll."

**Comment by Eugeny** [comment]
Fixed in the nightly build
