### ISSUE TITLE
[feature request] Emoji support!!!

### ISSUE THREAD

**Issue by dudeisbrendan03** [Eugeny/terminus#1097]
Title sums it all up. Manages to work alright in xterm (webgl) but when using xterm/webgl there is a black background (not following the theme). The blurred background works in xterm/hterm but not xterm (webgl). Sad.

🤞🤞🤞🤞🤞💕😁😁😂😂😂😂🤣🤣😊😊👍👍👍👍👍

**Comment by dudeisbrendan03** [comment]
I think it's a font issue?
Segoe UI has emoji support I think, how can I add fonts 🤔

**Comment by mehdisadeghi** [comment]
> can I add fonts

"Custom CSS" section perhaps?

**Comment by dudeisbrendan03** [comment]
Using hterm + a font w/ emoji support works.

Segoe UI doesn't really work, it leaves a massive gap between the text and the cursor.


I used hterm+DejaVu Sans and now I have those sweet emojis for my commits!
![image](https://user-images.githubusercontent.com/6009600/60292675-95513180-9915-11e9-9e58-c4677aa7794c.png)

**Comment by dudeisbrendan03** [comment]
It's still a bit dodgy, while placing emojis it randomly shows that emoji again at the bottom of the screen. 

You should avoid xterm as the emojis overlap.

**Comment by dudeisbrendan03** [comment]
Segoe UI (the emoji appears under the current line and the cursor is *way* off)
![image](https://user-images.githubusercontent.com/6009600/60292990-2de7b180-9916-11e9-9575-8a3dce42fcb8.png)

**Comment by mehdisadeghi** [comment]
Good to hear that you've made some progress! I installed Arch on my machine and put Windows in a VM and erased the problem alltogether.

**Comment by dudeisbrendan03** [comment]
🤔

**Comment by dudeisbrendan03** [comment]
I was desperate for emojis, not desperate enough to run a VM. Were you trying to run it on Arch?

**Comment by mehdisadeghi** [comment]
I'm using a qemu vm using gnome-boxes. However, I installed arch linux for other reasons but it solved this problem too.
