### ISSUE TITLE
Empty space at the top of the terminal

### ISSUE THREAD

**Issue by daramez** [Eugeny/terminus#11]
Every time I open a new terminal or a new tab I see an empty space at the top of the terminal. Is this the expected behavior?.

I'm using Linux Mint 18.1.
![terminus_003](https://user-images.githubusercontent.com/14096153/27743327-7937110a-5d70-11e7-88bc-99cb034c9d57.png)

**Comment by tborychowski** [comment]
same on latest macos

**Comment by lucasqueiroz** [comment]
Are there any updates on this?
