### ISSUE TITLE
Open Terminus with a Command

### ISSUE THREAD

**Issue by PandawanFr** [Eugeny/terminus#110]
Hey, since Windows's Context Menu can run commands to open Applications with parameters, it would be awesome if doing something like:
```
terminus .
```
(similar to `atom .`) would open the terminus with a tab already opened and `cd`'ed into the current directory. (With that, you could create a context menu to open the directory you right click into, something like 'Open with Terminus' though that can be custom-made, having the option to do parameters would be great).  

So doing something like:
```
terminus C:\Users\panda\Desktop
```
Would work with shortcuts, bash/shell/batch scripts... 

Now, the terminus part (using terminus instead of the full path to Terminus) is probably just an environment variable thing, but the arguments/parameters would be awesome.

Thanks!

**Comment by Eugeny** [comment]
The `terminus` part depends on your $PATH environment variable, and the rest is being tracked in #90
