### ISSUE TITLE
STUCK/BROKEN - after monitors removed/changed, or removed/added to dock (laptop)

### ISSUE THREAD

**Issue by lgordnier** [Eugeny/terminus#1108]
Version: 1.0.82
Platform: win32 10.0.17763
Plugins: none

When I'm working on my laptop on a dock, then remove the laptop from the dock and move elsewhere the entire program locks up. I'm left with a fully black "Terminus" screen that does not respond to resize/close commands - and as far as I can tell it does not function any longer either. Task manager must be used to force the program closed.  No issues after re-opening.

**Comment by wsinned** [comment]
I have seen the same issue with both Terminus and VSCode on Window 10 version 1803 Build 17134.706

There is a workaround. Pressing Alt-Space then selecting move from the menu that appears allows you to use the cursor keys to move the window back onto the current desktop/monitor.

**Comment by lgordnier** [comment]
this work around is not working for me. I get the arrows to move it, but the window will not move from that screen.
