### ISSUE TITLE
incorrect cursor position 

### ISSUE THREAD

**Issue by seoh** [Eugeny/terminus#112]
![image](https://user-images.githubusercontent.com/2159453/28010571-539685ac-659a-11e7-8ec8-16f3dfd36527.png)

Cursor seems to be 2-3 pixels left of where it should be. I searched in issue but i dont find same issue. If it is already submmited, just close :)

- environment
OS: Ubuntu Gnome 17.04
Shell: Zsh 5.2 (w/ zplug + sindresorhus/pure)

**Comment by koraktor** [comment]
It seems like this is also dependent on the font used. For me, the whole last character is covered by the cursor.

**Comment by MatayoshiMariano** [comment]
The same is happening to me!
![screenshot from 2017-07-10 10 25 29](https://user-images.githubusercontent.com/4236217/28020280-2444e932-655a-11e7-998b-d15f824c073c.png)

**Comment by seoh** [comment]
I use Fira Code 16pt.

**Comment by OvermindDL1** [comment]
Yep, same issue here as well (I typed `tes`):
![image](https://user-images.githubusercontent.com/401605/28024534-37303d78-654e-11e7-8a68-3f6b6ab70671.png)

For note, here is the text copy-pasted as text here:
```
╰─➤  tes
```

**Comment by leandrw** [comment]
I've found a solution, but I can't figure out where in the source code, could I put.

This line of style should fix the problem:

```css
.cursor-node {
    margin-left: .5em;
}
```

I don't know where in the project (in .scss or in style module definition of Angular component) should I put this. 

Can someone help me?

**Comment by OvermindDL1** [comment]
That fixes the alignment of the cursor so it matches the monotype width, however the text is still mis-aligned:
![image](https://user-images.githubusercontent.com/401605/28076932-65585f08-661d-11e7-8900-3487311c6b26.png)

I am using `Source Code Pro` as my font, which works fine in other terminals and does not mis-align text, however it seems text is getting misaligned here as you can see (I typed `test`).

**Comment by seoh** [comment]
I just fixed. replace /x-screen {/.cursor-node { margin-left: 3px; }\nx-screen {/ in`${TERMINUS}/resources/builtin-plugins/terminus-terminal/dist/index.js`(in my case, `/opt/Terminus`. I know, horrible solution but it works for now :p

**Comment by seoh** [comment]
And zeit/hyper also uses [hterm](https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm)(via [hterm-umdjs](https://github.com/dbkaplun/hterm-umdjs) too) but cursor is find. I have no idea why.

**Comment by OvermindDL1** [comment]
> I just fixed. replace /x-screen {/.cursor-node { margin-left: 3px; }\nx-screen {/ in${TERMINUS}/resources/builtin-plugins/terminus-terminal/dist/index.js(in my case, /opt/Terminus. I know, horrible solution but it works for now :p

Does not work here either, the cursor is both offset and the text is offset both.  It really looks like text is being displayed in non-monotype-cell's.

**Comment by leandrw** [comment]
```css
.cursor-node {
    margin-left: .5em;
}
```
Worked to me. 

Check: 
![peek 11-07-2017 13-56](https://user-images.githubusercontent.com/1456009/28080013-dc0e2362-6640-11e7-8524-b48fdf153bf1.gif)

**Comment by OvermindDL1** [comment]
Can you try changing your prompt to `╰─➤  ` and test?  Also what font are you using (`Source Code Pro` here).

**Comment by Eugeny** [comment]
This was due to the font not having a monospace glyph for the `➤` character. I'm not supplying a fallback font (`Meslo G for Powerline`), so that these characters can be rendered in a monospace manner.

**Comment by seoh** [comment]
@Eugeny Fira Code is not supported? :(

**Comment by Eugeny** [comment]
It is. The extra font is only for the characters missing in your chosen
font. I'm using Fira Code myself.

**Comment by seoh** [comment]
My bad. It works well in alpha21. Thx :)

**Comment by OvermindDL1** [comment]
Fixed here in alpha21 for "Source Code Pro" as well.  Thanks much!
