### ISSUE TITLE
Notifications on activity

### ISSUE THREAD

**Issue by Jaymzu** [Eugeny/terminus#1123]
Hey there, 
I think terminus is great. Definitely nice looking. I do miss one feature from iTerm2, though. notifications when there's activity in a terminal tab. Like something finishes compiling or something as simple as "something happened" when output is expected in more than a few seconds. 

Cheers,

**Comment by Eugeny** [comment]
Is this perhaps what you're looking for? 
![image](https://user-images.githubusercontent.com/161476/60019384-041c5980-968e-11e9-9c9c-2fa99c385031.png)

**Comment by Jaymzu** [comment]
ok, that works for when processes finish a longterm activity (just tested it now). 
how about adding support for any activity when the window is not focused? for stuff like tcpdump or tail? 
++ also show activity in the tab title besides system notifications (some people may keep system notification muted but have 10 terminal tabs open and it would be useful to see whenever a one of those tabs finishes something or has activity)

Cheers,

**Comment by Eugeny** [comment]
You should see blue highlight whenever a tab has new output: 
![image](https://user-images.githubusercontent.com/161476/60023331-e4892f00-9695-11e9-8e5b-9c7a6c841dd0.png)

Adding notifications for any kind of activity makes sense too - filed under enhancements
