### ISSUE TITLE
Empty tab is opened after relaunch the app

### ISSUE THREAD

**Issue by NDelt** [Eugeny/terminus#1147]
1. Enable `Auto-open a terminal on app start`
2. Open some tabs and go into `bash`
3. Close the terminal (Select 'Kill' to "bash.exe is still running. Close?")
3. Reopen the terminal

**Result:**

![capture](https://user-images.githubusercontent.com/46282492/60393726-bb184980-9b54-11e9-9557-d44143b1c8b7.png)

Version: Alpha 82
Unfortunately, this is not a constant issue so I tested it several times until it occurs again.

**Comment by yyynnn** [comment]
Yes, and if you open one tab then open settings and exit on app start only settings tab will be present.

**Comment by NDelt** [comment]
@yyynnn But those tabs freeze and no command works.
