### ISSUE TITLE
SSH connection timeout ?

### ISSUE THREAD

**Issue by JoseMariani** [Eugeny/terminus#1148]
Please, implement setting timeout to conection to the server... :( when i connect to server ... the console freezen! and i will close the console..  

and yeah, i configurate the SSH conf file to:

ClientAliveInterval 120
    ClientAliveCountMax 10

and restar shhd service!

**Comment by dsx12** [comment]
Same issue here. I encountered this after updating my terminus, did you ever fix this?

**Comment by highkay** [comment]
+1 connecting timeout

**Comment by GarbageYard** [comment]
Can you please fix the timeout issue? The screen freezes I guess in a minute or so. I am on v1.0.215
