### ISSUE TITLE
Cannot enter chars in terminal after using a shortcut

### ISSUE THREAD

**Issue by clerik** [Eugeny/terminus#115]
Version: 1.0.0-alpha.19 (since, at least, alpha 15)
Platform: win32 6.3.9600

All visual char keys (a to z, 0 to 9 and symbols) are not working anymore.
Enter, tab (and maybe some others) are working properly.

**Comment by Eugeny** [comment]
Which shortcut do you mean?

**Comment by clerik** [comment]
All of them.

Marko Savard

"Great spirits have always encountered violent opposition from mediocre
minds."
-- Albert Einstein

"Maverick: Someone who refuses to play by the rules. he/she isn't scared to
cross the line of conformity. but their unorthodox tactics get results!"
-- Urban Dictionary
<http://www.urbandictionary.com/define.php?term=Maverick&defid=361454>

**Comment by clerik** [comment]
Since the latest alpha (21) the problem is gone.
