### ISSUE TITLE
ctrl-r is unavailable

### ISSUE THREAD

**Issue by Chr1s-T** [Eugeny/terminus#1157]
When I ssh to a host and try to use ctrl-r to search the history, it failed to execute. Who can HELP me to solve this problem? I'm gona crazy!!!

**Comment by IgnusG** [comment]
Have a look at the keyboard bindings in settings and see if <kbd>ctrl</kbd><kbd>r</kbd> is not bound to something else

**Comment by Chr1s-T** [comment]
> Have a look at the keyboard bindings in settings and see if ctrlr is not bound to something else

Thank you, my keyboard bindings in settings is using in default, which do not contain any hotkey with "ctrl-r", what's the problem in here? By the way, when I use other terminal like the "cmd", the problem isn't exist, proving that the terminus "eating" my "ctrl-r" in some way. Don't you have such problem?

**Comment by Chr1s-T** [comment]
> Have a look at the keyboard bindings in settings and see if ctrlr is not bound to something else

I tried it again, actually, I found that when I ssh to a server, the ctrl-r is functional, but when I use the tmux , it turned out to be un-useable. What's the bug in here ?

**Comment by Chr1s-T** [comment]
> Have a look at the keyboard bindings in settings and see if ctrlr is not bound to something else
It looks like you're the only emancipator who can help me to solve the problem, give me a hand, plz, I really love this terminal, and don't want to try

**Comment by Chr1s-T** [comment]
Ok， I  know the the situation. It's because I use tmux to attach a session which is not supported to use ctrl-r hotkey.
