### ISSUE TITLE
Alt+F8 on git bash not clearing history

### ISSUE THREAD

**Issue by dejames** [Eugeny/terminus#116]
When using git-bash standalone, `Alt+F8` clears the terminal and clears the scrollback too. 
Terminus doesn't do this,  Instead it gives me a `~`

**Comment by Eugeny** [comment]
Alt-F8 is a hotkey from the mintty terminal emulator that Git-Bash uses: https://mintty.github.io/mintty.1.html
A universal shortcut to clear terminal would be Ctrl-L
