### ISSUE TITLE
Switching window black screen

### ISSUE THREAD

**Issue by swimmingchar** [Eugeny/terminus#1160]
Whenever I switch window 2 and return to window 1, the whole screen is black. When I press the Enter key, the font will be visible.

**Comment by wutz** [comment]
+1

**Comment by node-lux** [comment]
yep, and history log will be disappear

**Comment by IgnusG** [comment]
Seems like a duplicate of https://github.com/Eugeny/terminus/issues/729

**Comment by Eugeny** [comment]
Duplicate of #729
