### ISSUE TITLE
SSH connections do not open on 1.0.83

### ISSUE THREAD

**Issue by plrnr** [Eugeny/terminus#1161]
Version: 1.0.83
Platform: win32 10.0.17763
Plugins: scrollbar

Connections used to work fine on 1.0.82, app showed an 1.0.83 update is available. Updated and none of the connections open. The console just prints dots forever

**Comment by marcinbojko** [comment]
Nothing really works, no config window, no shell.

**Comment by zvshka** [comment]
+1

**Comment by zvshka** [comment]
![image](https://user-images.githubusercontent.com/39166475/60664177-e7d8a380-9e69-11e9-99c9-975c8d47ab06.png)

**Comment by zvshka** [comment]
nice

**Comment by peterbev** [comment]
Version 1.0.84
Windows	10.0.17134

Ditto

**Comment by kamkovvv** [comment]
Yes, it can't connect for both versions - 1.0.83 and 1.0.84.

**Comment by joseska** [comment]
+1

**Comment by dsx12** [comment]
Having the same issue here... I guess I'm just going to go with windows terminal.

**Comment by m1r0** [comment]
@Eugeny, JFYI, it seems that the problem still persists on v1.0.85, Windows 10.0.17763 x64.

**Comment by Eugeny** [comment]
Please download the updated A85 build here: https://github.com/Eugeny/terminus/releases/tag/v1.0.85

**Comment by binford6000** [comment]
> Please download the updated A85 build here: https://github.com/Eugeny/terminus/releases/tag/v1.0.85
> 
> > <img alt="" width="48" src="https://avatars3.githubusercontent.com/u/161476?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[Eugeny/terminus](https://github.com/Eugeny/terminus)**A terminal for a more modern age. Contribute to Eugeny/terminus development by creating an account on GitHub.

With this version ssh works again. Thx!
Sebastian

**Comment by zvshka** [comment]
++ thx!!
