### ISSUE TITLE
Appearance font family scrolling

### ISSUE THREAD

**Issue by ruslanguns** [Eugeny/terminus#1178]
When you are looking for the family font at Appearance Setting's Section the scrolling down is not fine. The only way to filter your font is filtering by text and you can only use the visible part not the displayed part in the lower part of the view.

**Comment by IgnusG** [comment]
Please attach a screenshot. Thanks!

**Comment by ruslanguns** [comment]
Better than that I think an animated gif will explain itself better :-) Thanks for responding.

![Font issue](https://user-images.githubusercontent.com/19806968/60753448-53398700-9fca-11e9-8513-c57cc52cafd8.gif)
