### ISSUE TITLE
Terminal opens but blank screen

### ISSUE THREAD

**Issue by vysecurity** [Eugeny/terminus#1179]
![image](https://user-images.githubusercontent.com/3596242/60659817-ea96c100-9e88-11e9-9038-bb6e33160454.png)
Any idea?

**Comment by vysecurity** [comment]
It's not the clickable-links bug. I don't even have the plugin, and even after installing latest version the issue still persists.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by vysecurity** [comment]
![image](https://user-images.githubusercontent.com/3596242/60660423-53cb0400-9e8a-11e9-8ff9-54d8cb0b7484.png)

**Comment by vysecurity** [comment]
![image](https://user-images.githubusercontent.com/3596242/60660513-837a0c00-9e8a-11e9-81e8-e02d0d52649a.png)

**Comment by Eugeny** [comment]
Which windows build are you on? Try disabling ConPTY in the Settings -> Shell

**Comment by vysecurity** [comment]
![image](https://user-images.githubusercontent.com/3596242/60660707-e9669380-9e8a-11e9-9497-372af79d7b48.png)


Where's ConPTY? On 10.0.18922 N/A Build 18922

**Comment by vysecurity** [comment]
Added:
  useConPTY: false

To the Config file. Same issue, didn't fix it.

**Comment by Liamdoult** [comment]
I am having the same issue when swapping between tabs:
![image](https://user-images.githubusercontent.com/12427907/61182331-55828d80-a629-11e9-8f68-e13e93f7a818.png)

Version: 1.0.85
Platform: win32 10.0.18362
Plugins: none

**Comment by Liamdoult** [comment]
I can confirm that this issue was resolved for me with ALPHA 86.

**Comment by fatkulnurk** [comment]
The same problem :-(
