### ISSUE TITLE
1.0.83 don't close the tabs and the terminal itself when clicking the cross

### ISSUE THREAD

**Issue by zvshka** [Eugeny/terminus#1180]
don't close the tabs and the terminal itself when clicking the cross

**Comment by IgnusG** [comment]
I have a similar problem. Seems like most controls on the top panel (new tab, close tab, settings ...) require several clicks in order to work. I usually works if I press hard enough :)

**Comment by bes-internal** [comment]
Like these problems are related to the shell - profile - cmd (clink). try to change it

**Comment by IgnusG** [comment]
I'm using a custom profile for WSL
