### ISSUE TITLE
Custom Shell for Anaconda enviroment

### ISSUE THREAD

**Issue by joseska** [Eugeny/terminus#1181]
I´m trying to create a new "Custom shell" for Anaconda env but no success.

I´m trying with: %windir%\system32\cmd.exe "/K" C:\Anaconda3\Scripts\activate.bat env_name, but not work

any idea?????

thanks......

**Comment by lookingz** [comment]
According to the script from the shortcut of "Anaconda Powershell Prompt",

`%windir%\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy ByPass -NoExit -Command "& 'D:\Anaconda3\shell\condabin\conda-hook.ps1' ; conda activate 'D:\Anaconda3' "`,

you can try custom shell settings like this.

![image](https://user-images.githubusercontent.com/9127424/60851441-becb6080-a225-11e9-9242-8f74c77746dd.png)

**Comment by lookingz** [comment]
You can try settings like this.

![image](https://user-images.githubusercontent.com/9127424/60851671-b0ca0f80-a226-11e9-8eda-fa2e3eb06912.png)

**Comment by joseska** [comment]
work... thanks...

only change the last command for:
& 'C:\Anaconda3\shell\condabin\conda-hook.ps1' ; conda activate env-name
