### ISSUE TITLE
Error: 'getProcessList' of undefined

### ISSUE THREAD

**Issue by zippy4** [Eugeny/terminus#1183]
I'm trying to connect to an ssh host I added in the settings and I saw I couldn't connect with the application idling trying to connect.
![application idling](https://i.imgur.com/gjcLjUg.png)
So I opened up the console and found I got this error when trying to make a connecting via ssh. I am able to connect via a terminal and not receive this error.
![error](https://i.imgur.com/Ezk3HjN.png)

Am I doing something wrong?

**Comment by Eugeny** [comment]
Fixed in the updated A85 build here: https://github.com/Eugeny/terminus/releases/tag/v1.0.85
