### ISSUE TITLE
Useless paddings when using tmux.

### ISSUE THREAD

**Issue by Chr1s-T** [Eugeny/terminus#1188]
As you can see, when I use tmux in a server, there are some useless paddings remaining in the terminus, how to fix this problem? I want to use it without any margin.
![TIM截图20190705124454](https://user-images.githubusercontent.com/23159278/60698627-de5f4200-9f22-11e9-904f-5f469d2a0c20.png)

**Comment by IgnusG** [comment]
Try the Relaxed theme. It doesn't have this padding.

**Comment by Chr1s-T** [comment]
> Try the Relaxed theme. It doesn't have this padding.

No use, still have some paddings arround.

**Comment by Chr1s-T** [comment]
> Try the Relaxed theme. It doesn't have this padding.

No use, still have some paddings arround.

**Comment by yfwz100** [comment]
Try "Custom CSS" in application setting:

```css
[_nghost-c8] > .content[_ngcontent-c8] { margin: 0 !important; }
```

**Comment by Chr1s-T** [comment]
> Try "Custom CSS" in application setting:
> 
> ```css
> [_nghost-c8] > .content[_ngcontent-c8] { margin: 0 !important; }
> ```
Very very great!! It works!! How did you find the solusion?

**Comment by yfwz100** [comment]
The whole UI is themed by CSS. You can open the dev-tool to inspect the element you want to change. But the class name may be changed in releases.
