### ISSUE TITLE
Quick Commands Error: "SafeValue must use..." takes up title bar

### ISSUE THREAD

**Issue by jackdw-concur** [Eugeny/terminus#1190]
Build: Terminus 1.0.85
OS: Windows 10

On updating from 1.0.77 (I believe), the title bar is consumed with the Quick Commands part taking up most of it.

The text in it is: 

```
safevalue must use [property]=binding: (see http://g.co/ng/security#xss)
```
A quick look through the config files and such does not show any clear way of fixing it.

**Comment by Eugeny** [comment]
I've posted a PR in the quick-cmds repo: https://github.com/Domain/terminus-quick-cmds/pull/11

**Comment by dogancelik** [comment]
Alpha 85
![safevalue](https://user-images.githubusercontent.com/486818/60767633-451b6180-a0c3-11e9-99d4-1d3177869985.png)

**Comment by Eugeny** [comment]
Please update the plugin

**Comment by dogancelik** [comment]
I deleted all user settings (in *AppData*) folder and did a fresh install.

I install Quick Cmds plugin again, the problem still exists in the latest version `2.0.0`.

**Comment by Eugeny** [comment]
My bad - they haven't merged my PR yet: https://github.com/Domain/terminus-quick-cmds/pull/11

Feel free to subscribe to the PR - I'll close this issue.
