### ISSUE TITLE
Still no support for ED25519 SSH keys with the built-in SSH agent

### ISSUE THREAD

**Issue by tchadelicard** [Eugeny/terminus#1191]
Hello,

I have recently installed terminus, I have seen that there were issues with ED25519 SSH keys. Apparently, the issues were fixed but I have found out that they still don't work. Furthermore, I've created this issue because the one that was previously created is closed.

Here are the errors I get while using either Putty format keys or  OpenSSH format keys:
![59699425-d77dc300-91f1-11e9-9968-b13faf5d8948](https://user-images.githubusercontent.com/22417050/60767095-d0402b80-a0b2-11e9-9f0b-3d5ef0a0096b.png)
![60346375-4958c800-99bb-11e9-923b-aea331c96979](https://user-images.githubusercontent.com/22417050/60767104-e4842880-a0b2-11e9-8a19-17ca2a6f6b63.png)

**Comment by peterbev** [comment]
I concur

![image](https://user-images.githubusercontent.com/26773831/60792336-6df03500-a15d-11e9-8f17-5147bcccc74e.png)

**Comment by hataos** [comment]
I have the same issue and am getting the "Cannot parse privateKey: Unsupported key format" message. Running v. 1.0.86.
