### ISSUE TITLE
Bash history not saved

### ISSUE THREAD

**Issue by bboehmke** [Eugeny/terminus#1198]
I tried terminus on a windows 10 (1709) with Cygwin and the bash from the git installation.
In both variation the history is not saved after the tab was closed.

I tried also the PowerShell but there it is working as expected.

**Comment by sburkett** [comment]
Sounds like a problem with your bash configuration. Or perhaps your hotkey mapping in Terminus? Dunno, but this search might be of help to you: https://www.google.com/search?q=bash+history+not+saving&oq=bash+history+not+saving&aqs=chrome.0.0l6.1774j0j7&sourceid=chrome&ie=UTF-8

**Comment by bboehmke** [comment]
If I open cygwin or the git bash directly the history is working fine.
Because the bash configuration is also almost default (only extended path variable and bigger history).
I also have not changed anything on the hotkey mapping.

The only bigger change is that I set the HOME environment variable inside windows to define a custom home directory which is working fine in native cygwin and git bash.

**Comment by sburkett** [comment]
What is the output of `history` in your `bash` shell? If you see a bunch of results, I'm guessing that for some reason your up/down arrow keys are not mapped properly in Terminus. Or, perhaps your `TERM` is not set up properly in the `bash` sh

**Comment by sburkett** [comment]
I don't use Cygwin, but it sounds like perhaps it isn't recognizing your custom `HOME` env variable. Does Cygwin require UNIX-like paths (e.g. /home/user), or does it require Win-like paths like c:\home\User?

**Comment by bboehmke** [comment]
The arrow key are working and I get even some history but only this entries that are already present in the .bash_history or done in the current session. Also history show this.

The home variable is set in my case to a path like "c:/path/home" which is handled well in cygwin.
This will be converted into something like "/c/path/home" inside the bash.

I will try it on a second windows system maybe this give us more information.

**Comment by sburkett** [comment]
Wait, you get "some" history, but not all of it? If a command was run in a different shell, you won't see it in the history of your current one.  Perhaps that is it?

**Comment by sburkett** [comment]
This has some helpful `bash` settings that may help you:

https://askubuntu.com/questions/885531/half-of-bash-history-is-missing

**Comment by bboehmke** [comment]
sorry with "some" I mean everything but none of the commands I used in a Terminus session

**Comment by bboehmke** [comment]
I also know the entry option `export PROMPT_COMMAND='history -a'` that will save the history on every command but I think this is mor like a wokr around.

**Comment by bboehmke** [comment]
I can also reproduce this on a second system here a short video: https://www.youtube.com/watch?v=fP_vdEYNe3E

**Comment by sburkett** [comment]
I see. That is strange. Doesn't happen for me on my system. Again, I'm not using Cygwin, so it may have something to do with that. Here is my output of `set | grep -i hist` ... maybe that will help:

```
BASHOPTS=checkwinsize:cmdhist:expand_aliases:extquote:force_fignore:histappend:hostcomplete:interactive_comments:login_shell:progcomp:promptvars:sourcepath
HISTCONTROL=ignoredups
HISTFILE=/root/.bash_history
HISTFILESIZE=1000
HISTSIZE=1000
SHELLOPTS=braceexpand:emacs:hashall:histexpand:history:interactive-comments:monitor
```

**Comment by bboehmke** [comment]
I think i found the issue. If the tab is closed in terminus, the bash will not be terminated:
![image](https://user-images.githubusercontent.com/9787279/61237687-4986f080-a73b-11e9-96aa-577bb99302b6.png)

**Comment by sburkett** [comment]
Ah, that could be it. You would need to add a signal trap in your .bashrc or something to catch that and exit gracefully. Or, just remember to log out instead of closing the tab.

**Comment by bboehmke** [comment]
I am not 100% but I think this should be handled inside terminus. 
The mintty that is used by cygwin can terminate the bash correctly and this should also be possible with terminus.

I would try to analize the code by my self but I can't work with TypeScript.

**Comment by sburkett** [comment]
I disagree. If you close a tab/session you have effectively lost control of the session. In the case of SSH connections, it has no idea what shell you are running in that session.

I have created an enhancement request that might help in this regard, though: #1241

If I have time, I might consider cobbling together a little plugin to do it, but let's see what @Eugeny says about my enhancement request first.

**Comment by bboehmke** [comment]
I can not imagine that it is intended that a closed tab is still running in background and can not be accessed anymore. At least the process should be terminated in my opinion.

For example a tab in a browser is also killed completely and a video must not be stopped manual before (maybe not the best comparison).

Btw I tested terminus on my linux system and there exist the same issue.

**Comment by sburkett** [comment]
But, the process is terminated, but not by Terminus. It is closed by the remote OS. Again, Terminus has no clue what you are connecting to. It could be any application that connects via SSH, not just a shell.

**Comment by bboehmke** [comment]
I think we're talking about different things. I do not use terminus to connect to a remote system via SSH.

I am using terminus as terminal emulator for local shells. In this case terminus will start this shell if a new tab is created and in this case terminus should also terminated it if the tab is closed.

Beside the issue that the history is not saved, I think it is bad if the application "allocate" ressources which are not released if they are not used anymore. In this case it is impossible to stop the shell after the tab is closed and only terminated if terminus is closed.

Normally I would assume that when closing a tabs a SIGTERM is sent to the shell. I think this is not the case at the moment (even if I not checked it). In this case also a trap inside the bash will have no efect because no signal was send (by default the bash should also exit if it receives a SIGTERM).

**Comment by sburkett** [comment]
Again, I don’t use Cygwin, but bash is bash... no matter if it is local or not.

**Comment by bboehmke** [comment]
But there is a different between remote and local.

In case of an remote connection the SSH server will spawn the bash and normally terminate it if connection is closed or lost.

In case of a local bash (cygwin, git bash, ...) terminus must start the bash and should also close it if it is not used anymore.

As far as I understand you use terminus mainly as SSH client without a local shell (bash) so you will not be affected by this issue because the SSH server handles the bash process (spawn and terminate).

**Comment by sburkett** [comment]
I’m not at home right now, so just have my phone, but according to the code it requests the host close the session:

   this.window.webContents.send('host:window-close-request')

**Comment by Eugeny** [comment]
The latest nightly should properly kill shell processes - please check!

**Comment by bboehmke** [comment]
I can confirm that the process is terminated now.

Sadly this does not solve the issue that the history is not saved.
Based on the change you made I may found something that can be the reason of this issue:
https://github.com/Eugeny/terminus/blob/4782a67fe024f00638b4f211b1768583c48aef32/terminus-terminal/src/services/sessions.service.ts#L251-L255
If I understand this correctly, this will kill the process like a unix SIGKILL on windows. This makes it impossible for bash to save the history.

**Comment by bboehmke** [comment]
@Eugeny 
Have you looked at this issue again?
