### ISSUE TITLE
Calling `terminus` from within Terminus causes it to crash

### ISSUE THREAD

**Issue by rhamzeh** [Eugeny/terminus#120]
Terminal: Terminus
Version: Alpha 20
OS: Ubuntu 16.04

> [raghd:~] $ terminus
Reading /opt/Terminus/resources/app.asar/node_modules/devtron/manifest.json failed.
Error: ENOENT, node_modules/devtron/manifest.json not found in /opt/Terminus/resources/app.asar
    at notFoundError (ELECTRON_ASAR.js:115:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:514:9)
    at getManifestFromPath (/opt/Terminus/resources/electron.asar/browser/chrome-extension.js:34:26)
    at App.<anonymous> (/opt/Terminus/resources/electron.asar/browser/chrome-extension.js:363:26)
    at Object.onceWrapper (events.js:290:19)
    at emitTwo (events.js:106:13)
    at App.emit (events.js:191:7)

**Comment by Eugeny** [comment]
Does it really crash, or does it hide the window? The default behaviour is to toggle the window visibility, so that you can bind the `terminus` command to a hotkey in case the builtin hotkey doesn't handle it.

**Comment by rhamzeh** [comment]
Just tried it with the Terminus version I have installed, and it is as you said, it was just being hidden.

If it is working as expected I guess this can be closed.

Some issues:
1) Commands like `terminus --version` and `terminus --help` are impossible to run. (How do I get the version number?)
2) When terminus is hidden using this method, there is no indicator that it is running in the background (notification icon, dock icon, etc..), and the user would never know until Terminus is run again.

You think these two warrant their own issues, or I let them be for now?

**Comment by Eugeny** [comment]
I think both are perfectly valid suggestions: #226, #227
