### ISSUE TITLE
Application name

### ISSUE THREAD

**Issue by jrock2004** [Eugeny/terminus#121]
The name of this application is the name of a business. I am not a lawyer or anything, but if this takes off, you could run into some problems

http://terminus.com/

**Comment by OvermindDL1** [comment]
They seem to be different domains, and if the domains are different then there is no trademark issue.

Also, their site is exceptionally bad, it does not load anything beyond the top bar and is causing my setup to throw a fit with invalid 3rd-party accesses...

**Comment by Eugeny** [comment]
I agree with @OvermindDL1
