### ISSUE TITLE
Feature Sugestion: Quake-like Terminal Option

### ISSUE THREAD

**Issue by Exorust** [Eugeny/terminus#1214]
Considering terminus is quite heavy, an alternative would be to have a quake mode, in which it would act like a drop down terminal. I believe this would allow more users to use it more frequently.

**Comment by Eugeny** [comment]
This is already possible - set the Docking mode to "top" and use the "Toggle window" hotkey to show and hide the terminal.

**Comment by kchen0x** [comment]
In contrast to Guake-like terminals, such as iTerm2, the behavior of Tabby when running in a similar configuration is notably dissimilar. 

Specifically, when a user pulls down the half-top window over a fullscreen application and subsequently retracts it, the cursor focus is expected to return to the original window. However, with Tabby, anomalous behavior is observed wherein the application reverts back to a non-fullscreen screen space and the cursor cannot be directed back to the original application.

**Comment by Saucistophe** [comment]
In a multiple-monitor setup, Guake also tracks on which monitor you are - at least it tries to.
