### ISSUE TITLE
Uncaught Exception: YAMLException: end of the stream or a document seperator is expected

### ISSUE THREAD

**Issue by jacobgasser** [Eugeny/terminus#1215]
![image](https://user-images.githubusercontent.com/43097555/61050974-34fecd00-a3b6-11e9-939f-6d6738032d22.png)

I get this error when i click the shortcut labeled "Terminus" and cannot open the terminal. 

I am on Windows 10, I just updated to the latest update. It worked just fine before the update.

**Comment by jacobgasser** [comment]
I tried reinstalling but I still get the same issue.

**Comment by CVJoint** [comment]
I had the same issue even after reinstalling. This fixed it for me - I uninstalled Terminus, went to my C:\Users\<user>\AppData folder and deleted the Terminus references from the Local and Roaming folders. Then when I reinstalled Terminus everything was working again.
