### ISSUE TITLE
Blur not effective in terminal

### ISSUE THREAD

**Issue by CafuChino** [Eugeny/terminus#1223]
Blur effect in terminal screen is gone with blur swith opened,while window frame displayed normaly.Maybe it only effect to software on win10 1903?
![image](https://user-images.githubusercontent.com/49181984/61183096-46bec980-a66f-11e9-8a34-dafbd34af5d3.png)
(just like this)

**Comment by Eugeny** [comment]
Are you using the xterm-webgl backend? It doesn't support transparency at this time.

**Comment by IgnusG** [comment]
Also check if in settings you have
![Annotation 2019-07-30 164007](https://user-images.githubusercontent.com/6438760/62138882-b75d1b80-b2e8-11e9-8ad7-4f3f6181b43d.png)

**Comment by ashtagged** [comment]
Same for me. Blur effect not working on shell even if i set same settings as above.

**Comment by Eugeny** [comment]
Fixed in A94 - release coming up!
