### ISSUE TITLE
Self Deinstallation after closing terminus

### ISSUE THREAD

**Issue by JannesStroehlein** [Eugeny/terminus#1224]
Yesterday I closed terminus via the X Symbole in the Titlebar and the deinstallation form poped up and deinstalled terminus completly. I wonder why terminus deinstalled itself without **any** userinput. It deleted its Programm Files (x86) directory. But the 

> paste path into terminus context menu entry

PS: Sorry for the worst english you ever saw (I'm german :D )

**Comment by JannesStroehlein** [comment]
Edit: It left over all its registry entrys.

**Comment by siccous** [comment]
I have very similiar issue with self deinstallation.

For me it happens every time when new version is available => new version icon in Terminus and after exit all files in Terminus folder are deleted. Only the empty Terminus folder remains. 

So my workaround is to install Terminus again (the new version) and it works again until new version is released :)

Platform: Windows 10 1903
