### ISSUE TITLE
PowerShell does not work on Windows

### ISSUE THREAD

**Issue by netxph** [Eugeny/terminus#123]
Version: 1.0.0-alpha.20
Platform: win32 6.1.7601

It has good user experience but my primary shell in windows is PowerShell. It's just showing me blank pane.

BTW. I'm using PowerShell 6 and Windows 7.

**Comment by princemaple** [comment]
BTW works quite well on Win10

**Comment by Eugeny** [comment]
Is the `powershell` command on your `%PATH%`?

**Comment by mikemaccana** [comment]
@Eugeny Powershell 6 is `pwsh` rather than `powershell`. You have to start it via a custom terminal. Hence https://github.com/Eugeny/terminus/issues/291

**Comment by mikemaccana** [comment]
TBH I expect this is the same issue as #291 but will let you decide!

**Comment by Eugeny** [comment]
@mikemaccana but there's still a `powershell` alias to it, isn't it? I'm going to close this, feel free to reopen if it still doesn't work after the #219 fix

**Comment by mikemaccana** [comment]
Hi @Eugeny! Nope, it's changed permanently and MS don't provide an alias. See https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-6  :

 > The binary name for PowerShell Core has been changed from powershell(.exe) to pwsh(.exe). This change provides a deterministic way for users to run PowerShell Core on machines to support side-by-side Windows PowerShell and PowerShell Core installations.

Ie binary name chooses Powershell Core vs Powershell 5


    which powershell
    C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe

    which pwsh
    C:\Program Files\PowerShell\6.0.0\pwsh.exe
