### ISSUE TITLE
Problem in interface

### ISSUE THREAD

**Issue by lyairmg** [Eugeny/terminus#1237]
Version: 1.0.85
Platform: win32 10.0.18362
Plugins: altair, clickable-links, quick-cmds, save-output, scrollbar, shell-selector, theme-windows10, title-control

The interface is not displayed correctly

![imagen](https://user-images.githubusercontent.com/5771046/61299739-4b39ce00-a7a6-11e9-94c9-ce7615f13289.png)

**Comment by Eugeny** [comment]
Tracked here: https://github.com/Domain/terminus-quick-cmds/pull/11
