### ISSUE TITLE
Ubuntu 16.04 Terminus Using Shell With Incorrect Environment Path

### ISSUE THREAD

**Issue by N0taN3rd** [Eugeny/terminus#124]
# Bug Report
The path variable in the shell used by Terminus **v1.0.0-alpha.20** is incorrect.
This occurs when the ```Shell``` option is set to ```Default shell``` and ```/bin/bash```

### What is the current behavior?
![terminuspath](https://user-images.githubusercontent.com/8648317/28132829-fe7b57f0-670b-11e7-9046-efd1d37629b3.png)

The output of echoing ```$PATH``` "prettified" with anotation from Terminus
```shell
echo $PATH 
/home/john/.rvm/gems/ruby-2.4.0/bin:/home/john/.rvm/gems/ruby-2.4.0@global/bin:/home/john/.rvm/rubies/ruby-2.4.0/bin:
/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:
.: <--- looks like bad substring manipulation??
/snap/bin:/home/john/.rvm/bin:/home/john/.rvm/bin
```

### What is the expected behavior?
The output of echoing ```$PATH```   "prettified" from gnome-terminal
```shell
echo $PATH 
/home/john/.rvm/gems/ruby-2.4.0/bin:/home/john/.rvm/gems/ruby-2.4.0@global/bin:/home/john/.rvm/rubies/ruby2.4.0/bin:
/opt/texbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/john/utilLibs/jdk/bin:
/home/john/utilLibs/scala/bin:/home/john/Desktop/testQT/qt5/qtbase/bin:/home/john/utilLibs/mvn/bin:/home/john/utilLibs/ant/bin:
/home/john/utilLibs/go/bin:/snap/bin:/home/john/.rvm/bin:/home/john/.rvm/bin
```
### What's your environment?
Ubuntu 16.04 LTS  

### Other information
I use both /etc/environment and ~/.bashrc to populate $PATH and global shell information which should be visible to ```process.env```  
Please consult this [gist](https://gist.github.com/N0taN3rd/f7ca67bc6c93fd98cd6114dfe562eac8) 
which shows the keys of  ```process.env```  when executed from Terminus and gnome-terminal 

I am able to get the expected behavior in terminus only after executing
```shell
source /etc/environment
```

Love this terminal keep up the good work :+1:

**Comment by Eugeny** [comment]
Could you please try following:

* Close Terminus
* Change the `shell` key in the `~/.config/terminus/config.yaml` file to `-bash`
* Restart Terminus

If this doesn't help, try changing it to `/bin/bash --login`

**Comment by N0taN3rd** [comment]
@Eugeny 

>  Change the shell key in the ~/.config/terminus/config.yaml file to -bash
- the actual shell ```sh``` not ```bash```
- setup order ```~/.bash_profiles``` -> ```~/.profile```  -> ```~/.bashrc```  when adding ```echo <filename>``` to each file  but path is still incorrect appears that only ```/etc/environment``` is added to shell 
- the output of dumping the keys of [```process.env```](https://gist.github.com/N0taN3rd/f7ca67bc6c93fd98cd6114dfe562eac8#file-terminusbashlogin-txt) 

>  If this doesn't help, try changing it to /bin/bash --login
- the actual shell ```sh``` not ```bash```
- setup order ```~/.bash_profiles``` -> ```~/.profile```  -> ```~/.bashrc```  when adding ```echo <filename>``` to each file  but path is still incorrect appears that only ```/etc/environment``` is added to shell 
- the output of dumping the keys of [```process.env```](https://gist.github.com/N0taN3rd/f7ca67bc6c93fd98cd6114dfe562eac8#file-terminusdashbash-txt) 
  

I have created an [Imgur album](http://imgur.com/a/MNkdi) documenting the output of these two commands
```shell
echo $PATH
echo $0
```
for reference when executed using terminus with the following ```shell``` keys set in ``` ~/.config/terminus/config.yaml```
1. ```-bash```
2. ```/bin/bash --login```
3. ```~default-shell~```
4. ``` /bin/bash```
5.  ```/bin/bash -i```
6.  ```/bin/bash -i -l```

**Comment by Eugeny** [comment]
Please retry with Alpha 22
