### ISSUE TITLE
No terminal opens at startup.

### ISSUE THREAD

**Issue by Mossop** [Eugeny/terminus#1240]
I have auto-open terminal at app start turned on but when I launch Terminus on OSX nothing happens. I have to click the dock icon a second time to get a window with a terminal to appear.

**Comment by Adrian-Grimm** [comment]
Same error here with Version 86 on MacOS - second click shows a white blank App:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/5657002/61396856-eaef7d00-a8c8-11e9-990e-a9ac3b9e49b6.png">

But the Windows Version ist working great!

**Comment by Zereao** [comment]
> Same error here with Version 86 on MacOS - second click shows a white blank App:
> <img alt="image" width="810" src="https://user-images.githubusercontent.com/5657002/61396856-eaef7d00-a8c8-11e9-990e-a9ac3b9e49b6.png">
> 
> But the Windows Version ist working great!

I got a same error~

**Comment by yyyreal** [comment]
Same problem. I've uninstalled terminal.app

**Comment by Adrian-Grimm** [comment]
> Same problem. I've uninstalled terminal.app

You don't have to... just install Version 85 again and everything is working...

**Comment by yyyreal** [comment]
@Adrian-Grimm I tried, but it doesn't work.  Thanks to version 86, Terminal.app works again.

**Comment by Adrian-Grimm** [comment]
The new Version ist working again - that bug could be closed.

**Comment by IgnusG** [comment]
Which version works?

**Comment by Adrian-Grimm** [comment]
> Which version works?

That one: "Alpha 87"

**Comment by Mossop** [comment]
I'm running Alpha 87 and this is still broken.
