### ISSUE TITLE
No menu to open a terminal or add plugins

### ISSUE THREAD

**Issue by Terraknor** [Eugeny/terminus#1248]
[Version:]1.0.86
Platform: linux 5.2.1
Plugins: altair, clickable-links, quick-cmds, relaxed-theme, save-output, scrollbar, shell-selector, theme-gruvbox, theme-hype, theme-windows10, title-control

When opening terminus 1.0.86 I don't get any menu options to open a terminal session or go to setting. Open settings with shortcut and don't have any customization code

**Comment by IgnusG** [comment]
Can you post an screenshot of how it looks like when you start the terminal?
