### ISSUE TITLE
GUI applications can not be launched from terminus 1.0.0-alpha.20 Ubuntu 16.04

### ISSUE THREAD

**Issue by N0taN3rd** [Eugeny/terminus#125]
# Bug Report

### What is the current behavior?
![terminusnoguilaunch](https://user-images.githubusercontent.com/8648317/28183075-1e421a3a-67dc-11e7-9563-601eceb4d330.png)

### What is the expected behavior?
![gnomeshellguilaunch](https://user-images.githubusercontent.com/8648317/28183079-22085026-67dc-11e7-8947-f269d7123180.png)

### What's your environment?
Ubuntu 16.04 LTS  

### Other information
see #124

**Comment by OvermindDL1** [comment]
Did you set your display variable first?  This is not a terminal thing but a shell thing, if using bash try:
```bash
DISPLAY=:0 gedit &
```
Or:
```bash
$ export DISPLAY=:0
$ gedit &
```

**Comment by N0taN3rd** [comment]
@OvermindDL1 I should not have to when using a properly configured terminal emulator per expected behavior.
And like you said it would be nice if terminus would be able to inherit the environment of the user's default shell.

If this a feature terminus will not be supporting I am more than happy to close this issue.

**Comment by OvermindDL1** [comment]
> And like you said it would be nice if terminus would be able to inherit the environment of the user's default or chosen shell.

I think it is a feature it should support, hence my implication that instead of this being a bug report issue, you should re-title and re-word it to be a feature request of using the current environment when loading a shell instead of the empty environment.  :-)

Would even be nice to be able to customize the environment passed in as well via Settings.

**Comment by panefem** [comment]
Same bug here
Linux Mint 18.2

**Comment by jamgregory** [comment]
This was working in Alpha 15, but now appears to be broken in Alpha 20. Setting `DISPLAY=:0` works (after a fashion) but Atom seems to run so much slower, so something seems to have been broken between those two releases...

**Comment by OvermindDL1** [comment]
> but Atom seems to run so much slower, so something seems to have been broken between those two releases...

I'm not seeing that after just testing it with `DISPLAY=:0 atom $PWD`, how do you reproduce it?

**Comment by jamgregory** [comment]
I could reproduce it on my machine (using alpha 20) but I've reverted back to alpha 15 for now. No idea particularly what's causing it... it just takes a lot longer to load when using Alpha 20...

**Comment by Eugeny** [comment]
Please retry with Alpha 22

**Comment by jamgregory** [comment]
That's fixed in alpha 22 - thanks @Eugeny :+1:
