### ISSUE TITLE
Terminus becomes unresponsive over time

### ISSUE THREAD

**Issue by dabrazhe** [Eugeny/terminus#1269]
After about a day or two Terminus becomes very slow in switching tabs and unresponsive to the degree I have to close the application are re-start it.

I am using about 8 tabs with ssh connection to cloud servers. 

Version: 1.0.77
Platform: win32 10.0.17134
Plugins: none

**Comment by Hammster** [comment]
Since you open/close a lot of tabs this should be resolved with #1263 :wink:
