### ISSUE TITLE
Special characters are not displayed correctly

### ISSUE THREAD

**Issue by pwittchen** [Eugeny/terminus#127]
Special characters are not displayed correctly. Please, see screenshot below, where I'm comparing Terminus with default system terminal.

![zrzut ekranu z 2017-07-15 11-37-21](https://user-images.githubusercontent.com/695319/28238356-40303b64-6952-11e7-913d-02c702d9d173.png)

My setup is exactly the same as in the issue #62 (Ubuntu 16.04 LTS, Zsh & Tmux).

Moreover, these characters were displayed correctly in one of the previous versions (as you can see on the screenshot in the issue #62).

**Comment by Eugeny** [comment]
Hi, please post the `locale` output inside Terminus

**Comment by pwittchen** [comment]
```
LANG=pl_PL.UTF-8
LANGUAGE=pl_PL
LC_CTYPE=pl_PL.UTF-8
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=
```

**Comment by Eugeny** [comment]
Could this possibly be font dependent? The terminals on the screenshot are using different fonts.

**Comment by pwittchen** [comment]
I'm not sure. In the previous Terminus version I was using `Liberation Mono` font as well, but special characters were displayed correctly.

**Comment by pwittchen** [comment]
Right now, I don't see Tmux bottom panel at all. I can see it in Tilix, so it's Terminus issue.
