### ISSUE TITLE
Additional tabs are opened when I launch the app

### ISSUE THREAD

**Issue by NDelt** [Eugeny/terminus#1272]
![Honeycam 2019-07-20 00-30-10](https://user-images.githubusercontent.com/46282492/61550676-0fe11d00-aa8e-11e9-811f-eb915f5ed296.gif)

Additional tabs are opened when I launch the app.
This issue occurs if `Settings | Terminal | Auto-open a terminal on app start` option is enabled.
I hope only 1 tab is opened when I opened terminal.

**Comment by Eugeny** [comment]
Duplicate of #1089
