### ISSUE TITLE
Keyboard Hotkeys override other applications Hot-Keys even if Terminus is not the application in focus

### ISSUE THREAD

**Issue by couchcamote** [Eugeny/terminus#1278]
Example:
Eclipse uses the CTRL-SPACE for most all of auto-completion and Intellisense  but instead of working, the app is now being minimized/restored back.  Found out after few hours of head scratching that it is Terminus doing this.

**Comment by Eugeny** [comment]
You can change or remove this hotkey ("toggle window") under Settings -> Hotkey
