### ISSUE TITLE
The first shell after opening terminus will use full-width characters

### ISSUE THREAD

**Issue by WhiteGreeny** [Eugeny/terminus#1281]
![terminusFullWidthCharacter](https://user-images.githubusercontent.com/19926964/61599422-49b34e80-ac5b-11e9-8302-ca853bc02452.jpg)

After that,the new shell will be normal.
version alpha 86
Windows 10 1903
OS locales is zh-cn

**Comment by zend** [comment]
It's a xterm bug, you can change Frontend to _hterm_ to avoid it. `Settings - Appearance - Frontend`

**Comment by WhiteGreeny** [comment]
> It's a xterm bug, you can change Frontend to _hterm_ to avoid it. `Settings - Appearance - Frontend`

It's work,thank you.
