### ISSUE TITLE
Feature request: logs to folder

### ISSUE THREAD

**Issue by woyczek** [Eugeny/terminus#1289]

**Comment by woyczek** [comment]
Have a way to permanently export whole output to a log folder, with a filename format such as Terminus-%Shell_PID-%d%m%y-%starting_timestamp.

A lot of terminal emulators does the log archiving, it seems to be the only and last feature to completely switch from SecureCRT, Putty, Terminator or ConEmu to Terminus.

**Comment by Eugeny** [comment]
This is now available as an option in the latest `save-output` plugin release
