### ISSUE TITLE
Terminus disappear when setting dock from off to bottom

### ISSUE THREAD

**Issue by huyvohcmc** [Eugeny/terminus#13]
I just downloaded the latest release and tried some settings (change dock from off to bottom) and then the app doesn't show up like it should be. Also reinstalled, no luck.

My issue is related to this #9, but on Ubuntu 17.04

**Comment by Eugeny** [comment]
Please see if the latest alpha resolves this issue.

**Comment by jdmartinbr** [comment]
I have the same problem with  v1.0.0-alpha.45

**Comment by tuannvm** [comment]
Try to delete `~/.config/terminus` and reinstall

**Comment by carthikvp** [comment]
still the issue is surfacing even in the version terminus-1.0.67-c10-gccc34ae

**Comment by 13sergy** [comment]
Delete all this directory. It will be create by default again.

> %AppData%/terminus

**Comment by richardoctoey** [comment]
> Delete all this directory. It will be create by default again.
> 
> > %AppData%/terminus

modify config.yaml
change to
`dock: off`

modify window.json
set X and Y to 0
` {
	"windowBoundaries": {
		...
		"x": 0,
		"y": 0,
		...
	},
}`
