### ISSUE TITLE
Fallback to username and password if SSH key does not match

### ISSUE THREAD

**Issue by n0ne117** [Eugeny/terminus#1312]
I really like Terminus and it's my go-to application on Windows - more recently I got a Mac and wanted to use Terminus there as well - but I'm stumbling over one issue:

I have an SSH key on macOS and Terminus want's to use it for every saved SSH host without failing back to username and password or interactive authentication.

This is the message I get - am I doing something wrong?

`Connecting to server.fq.dn
Using user's default private key: /Users/user/.ssh/id_rsa.
Loading private key from /Users/user/.ssh/id_rsa
Cannot parse privateKey: Encrypted private OpenSSH key detected, but no passphrase given`

Sorry, if I forgot something or if the formatting is not proper - this is my first issue :-)

Thank you all very much in advance!

**Comment by ChipwizBen** [comment]
This would be a useful feature. Putty handles the fallback to password correctly so it would be great if Terminus also did this.

**Comment by patriarch** [comment]
I have the same issue on my mac ....
Pearhaps have a button to not to connect with the private key

**Comment by n0ne117** [comment]
I just updated to 1.0.91 and everything works as expected - thank you!
(Terminus tries the key first and then falls back to password)
