### ISSUE TITLE
Add split screen commands to right click context menu

### ISSUE THREAD

**Issue by mikepanayotov** [Eugeny/terminus#1321]
Add split screen commands to right click context menu

**Comment by cgarst** [comment]
Agreed! Specifically, this should add at least three options:

1. Split Horizontally
2. Split Vertically
3. Close (Close the selected split pane)

**Comment by mishoboss** [comment]
@Eugeny , I thought this will land as part of #2054 but seems it's not there yet? Or I miss something?

**Comment by Eugeny** [comment]
@mishoboss no, this is a separate issue and hasn't been implemented yet
