### ISSUE TITLE
Session persistence (opened tabs and split screen configs)

### ISSUE THREAD

**Issue by mikepanayotov** [Eugeny/terminus#1322]
It would be great if the window size & position, tabs and split screen configs are preserved and then restored on Terminus reopen. Preserving the CWD of each tab & split screen and last commands of it, would make it awesome!

**Comment by mikepanayotov** [comment]
Personally for me the lack of that feature is becoming more and more an issue. I'll probably give it a try to implement if I find some time soon.

**Comment by Eugeny** [comment]
This has been implemented a while ago
