### ISSUE TITLE
Bug with paste

### ISSUE THREAD

**Issue by tanguyvda** [Eugeny/terminus#1325]
version  1.0.87

hotkey configuration: 
copy to clipboard : Ctrl-Shift-C
Paste from clipboard : Ctrl-V
Intelligent Ctrl-C : Ctrl-C

terminal configuration: 
Copy on select : ticked
right click : Paste

Hello there, 

since the update i'm having some troubles while trying to paste. 

when using ctrl-shift-c or ctrl-c it displays the little pop up telling me that the text is in the clipboard. But when trying to use ctrl-V or right click, there is nothing to paste (in terminus or anywhere else)

when just selecting text and using right click right away, it pastes the text. But if i write some text in terminus between the selection and the right click, I lose everything that was in the clipboard. 
If I do the same thing, but i write the text in a notepad, I keep the selected text inside the clipboard. So it is only when writing inside terminus that it flushes the clipboard.

**Comment by kachunkachunk** [comment]
Are you seeing this specifically when using less or vim, more specifically? I am trying to narrow down what specifically is causing this, but indeed, you can copy content to the clipboard just fine, but the moment you exit less or vim, clipboard contents are purged.

This may be some intelligent buffer stuff getting mixed up or passed to the system clipboard (I believe yanked text is supposed to be cleared upon exit?). That said, I'm testing that copying/highlighting text is not specifically "yanking" text and thus "putting" is pasting entirely different content.

I'm not sure yet what the deal is.

**Comment by tanguyvda** [comment]
nice catch :). Works fine using hterm.

just so you know, the behavior that i've reported is not limited to vim or less. It happens even when I'm not doing the copy/paste action through the SSH  connection.
