### ISSUE TITLE
Git-Bash python virtualenv not.

### ISSUE THREAD

**Issue by Hackxiaoya** [Eugeny/terminus#1326]
![image](https://user-images.githubusercontent.com/15765464/62170375-c4682200-b35d-11e9-9cf2-db3af7dd6273.png)

Git-Bash python virtualenv not venv

**Comment by IgnusG** [comment]
Can you please elaborate what the problem is? Which version are you running?

**Comment by Hackxiaoya** [comment]
@IgnusG I used git-ban mode to enter python's virtualenv, but after entering virtualenv, it does not show me currently in virtualenv.

**Comment by Eugeny** [comment]
@Hackxiaoya on the screenshot you posted, it's showing `(venv)`
