### ISSUE TITLE
[FEATURE REQUEST] SCP support

### ISSUE THREAD

**Issue by hardwareadictos** [Eugeny/terminus#1339]
Hi again guys :)

What do you think about implementing any plugin for supporting SCP/SFTP file transfer with a little simple file browser between connected machines. Maybe like in moba xterm or winsshterm? Its really useful when you are a Linux sysadmin, you can send backups or files easily between servers without the need of making scp invocations throw terminal everytime :)

Thanks in advance!

**Comment by huangxuanyuan8** [comment]
I also need this feature.

**Comment by Eugeny** [comment]
Duplicate of #296
