### ISSUE TITLE
Black screen software crash

### ISSUE THREAD

**Issue by yuhao-su** [Eugeny/terminus#1340]
- version 1.087
- platform windows 10 1903

I use VPN to connect to intranet servers, but sometimes when the VPN connection is cut down or my PC goes to sleep and restarts, the whole terminus shows black screen and has no response to any operation. In this case, I have to terminate the process in windows task manager.

**Comment by 1212gmartinez** [comment]
+1
Happens any time my computer goes to sleep.
- version 1.0.90
- Windows 10 1803
