### ISSUE TITLE
How to add Git Bash on Windows

### ISSUE THREAD

**Issue by Loreno10** [Eugeny/terminus#1345]
In Settings I see only cmd and Powershell. Git Bash for Windows is installed. I'm running Windows 7.

**Comment by yfwz100** [comment]
You can manually add profile under shell settings. 

For example:

![image](https://user-images.githubusercontent.com/983211/64060452-394da680-cbff-11e9-94f6-a750f0ea53c7.png)

**Comment by digeomel** [comment]
I'm sorry but this not very clear to me, the Add profile dialog now shows this (it asks me to select a profile and I selected `cmd(clink)`):

![image](https://user-images.githubusercontent.com/3295889/157712270-5cbce045-44c7-4f37-b537-e6307db599d4.png)

I'm assuming I have to change the command line field, but to what? `cmd.exe /k <path to bash.exe>`?

**Comment by Eugeny** [comment]
If you've installed Git-Bash via installer, it should be detected automatically. Otherwise, here are the default settings: 
<img width="379" alt="image" src="https://user-images.githubusercontent.com/161476/157719036-90cb33db-9f5a-442d-a69e-21e127395185.png">

**Comment by kesavanm** [comment]
This works with latest `tabby` with `PortableGit`
![image](https://user-images.githubusercontent.com/1879445/163858000-cf55e2ac-aaa4-4eb3-9029-14b7f21486bd.png)
