### ISSUE TITLE
UTF8 font support broken on OS10.13 High Sierra beta

### ISSUE THREAD

**Issue by jwintz** [Eugeny/terminus#135]
Any hints on how I could investigate and fill a PR ?

**Comment by Eugeny** [comment]
Which Terminus version are you using?

**Comment by jwintz** [comment]
Alpha 20, download a few days ago. I'd like to contribute, Terminus is awesome.

I also have so ideas on keyboard shortcuts (as a heaven user of emacs, CTRL-A emulate GNU screen is quite disturbing, also the CMD-Q only works when no more shell is opened).

**Comment by jwintz** [comment]
Just realize alpha 21 is out. I'll give it a try.

**Comment by Eugeny** [comment]
@jwintz any luck?

**Comment by jwintz** [comment]
Nope, I’m using Terminus on a daily basis now, both on a desktop and a laptop under MacOSX High Sierra Beta, and the support for glyphish fonts is gone.


Note that on the desktop (Mac Pro late 2010), the scrollbar is not shown as expected, but this bug happens with any Electron app, and is therefor not related to terminus.

  - ju

On 24 July 2017 at 09:57:10, Eugene Pankov (notifications@github.com) wrote:

@jwintz any luck?

**Comment by Eugeny** [comment]
Could you please post a screenshot with those broken chars?

**Comment by Eugeny** [comment]
The final 10.13 is now out and the Unicode chars work fine for me. Feel free to reopen if this is not the case in your setup!
