### ISSUE TITLE
Restart session in tab

### ISSUE THREAD

**Issue by ChipwizBen** [Eugeny/terminus#1350]
If a session dies, it would be good to be able to restart that session by restarting it and preserving the tab (including any text within it) and not having to reopen a new tab. Putty can do this with a right click and an option called "Restart Session".

**Comment by Eugeny** [comment]
Duplicate of #761

**Comment by Arichy** [comment]
> Duplicate of #761

How can I restart a normal session which is not ssh or telnet?
