### ISSUE TITLE
Ctrl + L shortcut makes WSL display strange

### ISSUE THREAD

**Issue by Hustcw** [Eugeny/terminus#1352]
Windows10 set the default shell in terminus as WLS/Ubuntu
When using ctrl+L, it does clear the screen while the cursor will jump far away. But if I use clear command, everything goes on well.

**Comment by mvineza** [comment]
@Hustcw I removed "CTRL+L" from hotkeys in settings menu and it worked for me. I'm using v1.0.77.

**Comment by Hustcw** [comment]
@mvineza Thanks for your reply. Actually I only find this strange display when I use terminus for wsl. I can run terminus well if I only use terminus for ssh. The most funny thing is I can use
```bash
clear
```
to make everything goes ok. So maybe there's some bugs in hot-key for wsl? I guess

**Comment by fanlushuai** [comment]
@mvineza  It works for me ,thanks very much!

**Comment by liushan150** [comment]
@mvineza  nice! It works. good job!

**Comment by Eugeny** [comment]
@mvineza great find! Terminus doesn't forward keys that are recognized as hotkeys to the shell, so while Ctrl-L would clear the TTY, the actual process isn't aware of this. I'll remove the default clear hotkey assignment on Windows and Linux.
