### ISSUE TITLE
Home and End keys do not work

### ISSUE THREAD

**Issue by ChipwizBen** [Eugeny/terminus#1359]
These do not seem to be configurable in settings either. Shift+Home and Shift+End do work, but it's counter intuitive to have to use this combo.

**Comment by HotBlack77** [comment]
Oh god, please yes. I thought I was going insane.

**Comment by Eugeny** [comment]
What about these? 
![image](https://user-images.githubusercontent.com/161476/62851964-39d1dc00-bce8-11e9-98cd-b502acfb4af4.png)

**Comment by ChipwizBen** [comment]
Those don't work. If you set Home and End correctly, it still requires that you press shift to operate them.

**Comment by Eugeny** [comment]
Oh which OS / shell?

**Comment by ChipwizBen** [comment]
Fedora 30, bash.

**Comment by HotBlack77** [comment]
Debain 9, bash 4.4

**Comment by jack1142** [comment]
I have the same problem when I ssh from my Windows computer to Ubuntu 18.04 server (bash shell)

**Comment by dogik** [comment]
Same here. ubuntu 18.04 server (zsh 5.4.2 - oh-my-zsh).

ps: @Eugeny thanks for your hard work on this project

**Comment by citycide** [comment]
Same for me on Windows using powershell core.

**Comment by darkiop** [comment]
some here, with terminus @ win10 and some connections to bash-shells.

workaround (bash):

strg + e = end of line
strg + a = beginning of the line

![image](https://user-images.githubusercontent.com/205119/63873010-12089680-c9bf-11e9-96ac-537f991ebc51.png)

**Comment by jaques-sam** [comment]
The begin & end buttons under Windows:
- WORK always on host
- WORK on the guest when ssh was entered in local terminal
- DO NOT WORK on the guest when connected through an ssh connection via "SSH Connections"

**Comment by jack1142** [comment]
Yeah, when ssh is entered in local terminal, you use something like OpenSSH but if you use Terminus's ssh connection you use SSH2 client that is written in JavaScript (https://www.npmjs.com/package/ssh2)

**Comment by MortezaRamezani** [comment]
On Windows 10, set hotkeys to Shift+right, Home and Shift+left, End, and now home and end are working but not shift+<left/right> which doesn't matter 😄

**Comment by MichalCz** [comment]
Same here, although removing the hotkeys (simply leaving those blank) work just fine for me in min-gw (git-bash), cmd (clink and legacy) and ssh connections.

**Comment by jaques-sam** [comment]
Waauw, thanks @MichalCz!! This works like a charm!

**Comment by jaques-sam** [comment]
Waauw, thanks @MichalCz!! This works like a charm!

**Comment by nipeone** [comment]
the  bug is still exist, 'Home' , 'End' and 'Ctrl-F' are not working on SSH

**Comment by jaques-sam** [comment]
> 
> 
> the bug is still exist, 'Home' , 'End' and 'Ctrl-F' are not working on SSH
Correct!

Btw, it's either: "still exists" or "is still exiting" 😉

**Comment by citycide** [comment]
> > the bug is still exist, 'Home' , 'End' and 'Ctrl-F' are not working on SSH
> > Correct!
> 
> Btw, it's either: "still exists" or "is still exiting"

> still exiting

https://en.wikipedia.org/wiki/Muphry%27s_law

:wink:

**Comment by jaques-sam** [comment]
It's just to help, not to criticize as one might think 😉

**Comment by ChipwizBen** [comment]
This is now working correctly.

**Comment by reynadan** [comment]
I had the same problem with Tabby 1.0.211
I fixed it by simply removing hotkeys for beggining and end of the line
![image](https://github.com/user-attachments/assets/204acc3e-93b2-457a-b3c2-aacbd070d5a3)

**Comment by elrosch** [comment]
> I had the same problem with Tabby 1.0.211 I fixed it by simply removing hotkeys for beggining and end of the line ![image](https://private-user-images.githubusercontent.com/9109378/370223222-204acc3e-93b2-457a-b3c2-aacbd070d5a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4MzYwNzAsIm5iZiI6MTczNjgzNTc3MCwicGF0aCI6Ii85MTA5Mzc4LzM3MDIyMzIyMi0yMDRhY2MzZS05M2IyLTQ1N2EtYjNjMi1hYWNiZDA3MGQ1YTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTRUMDYyMjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjk5MmU1ZjJhYzI3MGE1ZmIyOTFiNzRmOWFkOTUyZGRiOWU2MzcyYTdjMTdlZTRmODUzZjc3NTUxOWJjZDAzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.te-ofBil11-bvSkUYvV9LNEsFtX1RsRQ-HbMHDpUSU8)

Tabby 1.0.216: I can still confirm that removing the hotkeys fixes the issue
