### ISSUE TITLE
Terminus stuck on logo startup screen

### ISSUE THREAD

**Issue by jdenoy** [Eugeny/terminus#1361]
Hello,

Terminus stuck on logo screen, has never started.

OS : Arch Linux
Kernel : 5.1.15
Terminus version : 1.0.78-1 (installed via https://github.com/Eugeny/terminus#tag=v1.0.78)

Screenshot : 
![image](https://user-images.githubusercontent.com/246715/62619028-040eab00-b916-11e9-8840-a2628511e342.png)

**Comment by Hmerin** [comment]
I have the same problem/behavior

OS : Arch Linux
Kernel : 4.19.62
Terminus version: terminus-terminal-1.0.78-1 Installed via yay

**Comment by Fuzen-py** [comment]
Same problem 
OS: Arch
Kernel: 5.3.5-zen
Terminus version: 1.0.78-1 (Installed with AUR)
DE: i3

**Comment by Fuzen-py** [comment]
> Same problem
> OS: Arch
> Kernel: 5.3.5-zen
> Terminus version: 1.0.78-1 (Installed with AUR)
> DE: i3
Built from source, that seems to have fixed it

**Comment by jdenoy** [comment]
latest update works fine

**Comment by korr237i** [comment]
Hello,
I have this problem now. Terminus starts and stucks on logo.
OS: Manjaro
Kernel: 5.5.2-1
Terminus: 1.0.101-1, installed from AUR

**Comment by kev-cs** [comment]
I have the same problem too. Same behavior as described in the first post.

OS: Manjaro
Kernel: 5.4.24
Terminus: 1.0.104-1, installed from AUR

Running it from the tar.gz download works though. Still, I like to install my programs with a package manager.

**Comment by Eugeny** [comment]
@kev-cs please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by kev-cs** [comment]
@Eugeny unfortunately, it won't open. I also have to manually kill the process to close it.

**Comment by dragonito** [comment]
Same problem here on manjaro 21.1.3, i installed with aur package tabby 1.0.157-2

**Comment by Eugeny** [comment]
Could you please launch tabby with `--inspect` and then use Chrome to connect to the main process debugger? (see https://nodejs.org/en/docs/guides/debugging-getting-started/).
There should be _something_ in the console there.

**Comment by januridp** [comment]
➜  ~ tabby --debug
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[232653:0123/193323.861286:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
^C
➜  ~ tabby --inspect
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[251846:0123/193813.357302:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.

Hi, I got stuck on the logo screen.

**Comment by marwankous** [comment]
restarting the operation system solved the problem for me

**Comment by damianchoc** [comment]
~ tabby --debug
[3598:1101/163549.800443:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.

i've got the same problem as guys above, please fix it
