### ISSUE TITLE
Path Background Highlight Feature

### ISSUE THREAD

**Issue by syedsimanta03** [Eugeny/terminus#1366]
Hey, How can I set background color like the below image where it showing PATH background color and highlights the patch C://users/username

https://cdn-media-1.freecodecamp.org/images/1*7SLVI9-_IBwEcmZpGaDvmw.png

**Comment by Eugeny** [comment]
This is not terminal-related, but you could try oh-my-zsh with this theme: https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#agnoster

**Comment by syedsimanta03** [comment]
man I am a windows user. How to install powerline path highlight colors BG?

**Comment by Eugeny** [comment]
https://www.google.com/search?q=powershell+powerline
