### ISSUE TITLE
Shall we get powerline for terminus in future?

### ISSUE THREAD

**Issue by syedsimanta03** [Eugeny/terminus#1374]
Terminus is really awesome and good looking terminal. Shall we get powerline for terminus in future? Highlight for the path

**Comment by Eugeny** [comment]
Powerline fonts and themes are not terminal dependent. Consider installing oh-my-zsh with one of the powerline based themes

**Comment by syedsimanta03** [comment]
I am a windows user Saturday, 10 August 2019, 07:40p.m. +06:00 from Eugene  notifications@github.com :

**Comment by Eugeny** [comment]
Then just install the original powerline: https://github.com/Jaykul/PowerLine

**Comment by syedsimanta03** [comment]
Already installed it and it can only change the windows powershell. I am unable to to load it with terminus. Even I changed the terminus shell to powershell for new tab. Still not working. However I just need to show up powerline with my beauty terminus
--
Sent from Mail.Ru app for Android Saturday, 10 August 2019, 08:47p.m. +06:00 from Eugene  notifications@github.com :

**Comment by Eugeny** [comment]
Here's Powerline running in Terminus. Make sure you've added `Import-Module Powerline` to your `profile.ps1`

![image](https://user-images.githubusercontent.com/161476/62832208-3298c880-bc2b-11e9-8e2f-10713bba2299.png)

**Comment by syedsimanta03** [comment]
This looks awesome man. Can get step by step guide? I was able to install powerline using PowerShell windows os. But that don't persist when I reopen it I see no powerline on my powershell. 
How to save this look with powerline. What is profile­.ps1?
After that I will choose powershell for new tab on Terminus? I want to load that on terminus as well


--
Sent from Mail.Ru app for Android Sunday, 11 August 2019, 03:29p.m. +06:00 from Eugene  notifications@github.com :

**Comment by Eugeny** [comment]
You need to add `Import-Module Powerline` to your Powershell profile script. You can edit your profile script with `notepad $PROFILE`. 

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-6

**Comment by syedsimanta03** [comment]
Bro U are awesome. Itz fine. But not like yours. The colors looks different
on my powershell and Terminus. I am using cobalt 2 + Altier + Droid sans
mono powerline font for My terminus.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
