### ISSUE TITLE
Docked terminal is invisible - where can I delete the config

### ISSUE THREAD

**Issue by norandom** [Eugeny/terminus#138]
Hi,

I have Windows 8.1, dual screen setup. I clicked "Dock at bottom". Now Terminus is gone, persistently. Can someone tell me where I can delete the config? The AppData folder doesn't have it.

**Comment by Clanwarz** [comment]
So ... my first day using terminus and highly disappointed that the bottom dock completely ruins this app. The docker routine needs some work but we need a way to enter the program.

**Comment by vlur** [comment]
FYI, this is still broken.

Workaround:

The relevant configs are stored in `AppData\Roaming\Terminus`. Delete all files in this directory and restart Terminus. It should recreate them from defaults and Terminus will become visible again.

I did try first to edit the `config.yaml` file in Roaming and delete the line starting with `dock:`. Unfortunately, this changed nothing.
