### ISSUE TITLE
There is not any option to open mulitple SSH Connecitons

### ISSUE THREAD

**Issue by mehdiirh** [Eugeny/terminus#1388]
If I open a tab to use SSH Connection, then I just can open new windows cmd line, and can't open a new SSH Connection.

Version: 1.0.88
Platform: win32 10.0.17763
Plugins: altair, clickable-links

**Comment by Eugeny** [comment]
Press the "SSH" button in the windows titlebar to open a new SSH connection: 
![image](https://user-images.githubusercontent.com/161476/63005264-79313180-be7c-11e9-9ee9-c8cc10b73647.png)
