### ISSUE TITLE
Request for configuration to change lineHeight

### ISSUE THREAD

**Issue by Shriram-Balaji** [Eugeny/terminus#1390]
Hey, 

Thanks for creating this amazing terminal app. It's one of the best looking terminal interfaces that Ive found for Windows.

I was trying to find an option to increase the `lineHeight` but couldn't find any in the configuration. xterm seems to have an option set the `lineHeight`, as well https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/#lineheight

Is it possible to include that as part of the configuration? Unfortunately, I'm on WSL and it seems to be quite tough to set things up. so I'm not sure I can make a PR myself. Thanks!

**Comment by Eugeny** [comment]
Fixed in the nightly - `terminal.linePadding` now works with the xterm frontend too
