### ISSUE TITLE
Add an option make Terminus to not remember the tabs previously opened

### ISSUE THREAD

**Issue by NDelt** [Eugeny/terminus#1392]
Currently, the tabs I opened previously is accumulated every time launch the app. Please add a new option for disabling this behavior.

**Comment by ZaLiTHkA** [comment]
I was about to make the same request.. since I only ever launch it from my Explorer context menu (Windows), I end up having to close at least one tab every time I launch it.

**Comment by Eugeny** [comment]
Has been done a while ago
