### ISSUE TITLE
Hotkeys settings 'Search' Ctrl-F do not work for SSH connections

### ISSUE THREAD

**Issue by zhanghaobj** [Eugeny/terminus#1394]
Version: 1.0.88
Platform: win32 10.0.14393
Plugins: save-output, theme-gruvbox, theme-hype, theme-windows10

Hotkeys settings 'Search' in Settings->Hotkeys, Ctrl-F, Ctrl-Shift-F, do not work for SSH connections. These hotkeys only work for local shells now.

**Comment by chanlk** [comment]
+1

**Comment by xorbitnl** [comment]
jup same here on mac

**Comment by x1nas** [comment]
https://github.com/Eugeny/terminus/issues/1359#issuecomment-538642660
