### ISSUE TITLE
Can't use arrow keys to navigate in vi

### ISSUE THREAD

**Issue by rpelissi** [Eugeny/terminus#1397]
Hi,
I have Alpha 88 version and use a custom shell that point to the cygwin.bat script. I can use cygwin as a shell.
But everytime I open VI, I can't navigate in the file with the arrow keys. The cursor just don'T move and every attempt make just a beep...
Please help!

**Comment by sadlame** [comment]
Maybe [this](https://vim.fandom.com/wiki/Fix_arrow_keys_that_display_A_B_C_D_on_remote_shell)?
