### ISSUE TITLE
Github Sponsor Button Issue

### ISSUE THREAD

**Issue by TimoSta** [Eugeny/terminus#1398]
As I press the _Sponsor_ button on the repo, I see the following error:

![image](https://user-images.githubusercontent.com/5621996/63174269-9a765700-c00f-11e9-967b-a1d07607e664.png)

It looks like Github won't let me sponsor via the in-platform sponsor feature, as you're not enrolled, @Eugeny?

**Comment by Eugeny** [comment]
For some reason, I'm still not enrolled, although I signed up way before the official announcement :)

I wasn't aware that this error is visible to other users though.

**Comment by TimoSta** [comment]
Github sponsorships work for your account now, @Eugeny! 🎉

Closing the issue.
