### ISSUE TITLE
退出时自动卸载

### ISSUE THREAD

**Issue by tiantianliu2018** [Eugeny/terminus#1399]
Version: 1.0.87
Platform: win32 10.0.18362
Plugins: none
Automatically uninstall when exiting

**Comment by yfwz100** [comment]
如何自动卸载？

**Comment by tiantianliu2018** [comment]
退出后，软件就消失了，下一次点开还要重新安装

**Comment by yfwz100** [comment]
是重新初始化，还是重新安装？

**Comment by tiantianliu2018** [comment]
是重新安装

**Comment by yfwz100** [comment]
你是不是运行错程序了

**Comment by chanlk** [comment]
+1
it was happed 3 times when i turn off my pc;
It bothers me!

Version: 1.0.88
Platform: win64 10.0.18970.1005
Plugins: none

**Comment by Eugeny** [comment]
This should be fixed in the latest release.
