### ISSUE TITLE
Flexible line-height

### ISSUE THREAD

**Issue by JostCrow** [Eugeny/terminus#141]
It would be nice if the line-height could be flexible. Right now it is a bit close to the line above. It would be better to read if the spacing was a little bigger (but that is personal)

![screenshot from 2017-07-24 16-17-27](https://user-images.githubusercontent.com/390575/28527751-d00b745c-708b-11e7-9d36-bb8292a3d113.png)

**Comment by Eugeny** [comment]
This is now controlled by the `terminal.linePadding` config option

**Comment by JostCrow** [comment]
Oke nice. Thank you

**Comment by ibnuh** [comment]
@Eugeny `terminal.linePadding` doesn't seem to work anymore, how can I change the line-height?

**Comment by vivekragunathan** [comment]
This `terminal.linePadding` is an option visible in the settings UI? Or needs to be added in the Appearance > Custom CSS textbox?

**Comment by Eugeny** [comment]
It's not visible in UI, you need to add `linePadding: 5` to the `terminal:` section in Settings -> Config File.

**Comment by vivekragunathan** [comment]
> It's not visible in UI, you need to add `linePadding: 5` to the `terminal:` section in Settings -> Config File.
Yep, i tried that. https://github.com/Eugeny/tabby/issues/141#issuecomment-998283904

**Comment by Eugeny** [comment]
My bad, I didn't see the edit. You need to either use the built-in config editor (`Settings -> Config file`), or edit the config while Tabby isn't running - otherwise it's overwritten when the app quits.
