### ISSUE TITLE
New tab immediatly close

### ISSUE THREAD

**Issue by Thosquey** [Eugeny/terminus#1417]
Version: 1.0.88
Platform: win32 10.0.17134
Plugins: none

I can't open new tabs on terminus. It's closing in a second. Does not matter which one i'm using (powershell/cmd etc). Can't do a thing, and switching terminals in settings does not seems to change something. Can't use terminus.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs
