### ISSUE TITLE
Terminus just abruptly disappeared without a trace

### ISSUE THREAD

**Issue by josephrooks** [Eugeny/terminus#1418]
I've been using Terminus for a couple of months now without any issues. It was running 20 minutes ago in a session that's been going for a few weeks. I just shut down my computer to move some furniture around, and on restart the icon was blank in my taskbar, so I went looking for it -- and the entire folder in program files is completely empty. Wha? Any idea what could have happened? I don't have anything scanning for anything right now that could have mistakenly flagged it as malicious.

**Comment by Jany-M** [comment]
Same thing here.
Opened it after some time (1.0.85), then closed it and reopened it. It was completely gone from hdd.
On Win10 Pro 64x.

**Comment by ghostseven** [comment]
Same, it appears to be uninstalling itself by the looks of it.

**Comment by kachunkachunk** [comment]
For a few releases I've had issues with its updater, yep. It seems like it's uninstalling itself and not proceeding with the next step.

This has been on systems with UAC enabled and disabled. Trying to see if I can supply something more tangible (logs, etc) but so far I haven't found much.

**Comment by 1212gmartinez** [comment]
+1
