### ISSUE TITLE
Custom colorscheme

### ISSUE THREAD

**Issue by rapha8l** [Eugeny/terminus#142]
Hi,

It's not a bug, but I tried to add custom color schemes in /opt/Terminus/resources/builtin-plugins/terminus-community-color-schemes/schemes/ using the same syntax as other files.
Though they don't appear in the menu to select the color scheme
I checked permissions and syntax, and I don't see what I missed

thanks

**Comment by Eugeny** [comment]
Hi, those files are for reference only, the actual schemes are compiled into `/opt/Terminus/resources/builtin-plugins/terminus-community-color-schemes/dist`. Currently only schemes in Hyper format are auto-loaded, and also scheme plugins (like community-color-schemes)

**Comment by rapha8l** [comment]
ok thanks
