### ISSUE TITLE
Problem with korean language

### ISSUE THREAD

**Issue by winetree94** [Eugeny/terminus#1425]
![01](https://user-images.githubusercontent.com/51369962/63836973-91916800-c9b5-11e9-82df-a27e96143444.PNG)
![02](https://user-images.githubusercontent.com/51369962/63836975-91916800-c9b5-11e9-8445-e52c21ccacdb.PNG)
![03](https://user-images.githubusercontent.com/51369962/63836976-91916800-c9b5-11e9-8f02-7759f2d1dea7.PNG)
![04](https://user-images.githubusercontent.com/51369962/63836977-91916800-c9b5-11e9-9195-cd6a587b6180.PNG)

when i typed korean words into terminus
every word duplicated somewhere in terminal

i'm using on latest version
thanks for your app 👍 

if you need more information of this bug, i will do my best

**Comment by Eugeny** [comment]
Which frontend are you using? (xterm/hterm)
Does enabling/disabling ConPTY make any difference?

**Comment by winetree94** [comment]
![1](https://user-images.githubusercontent.com/51369962/63934941-65e6ae80-ca97-11e9-9025-6eb5c2fe1a4d.PNG)
![2](https://user-images.githubusercontent.com/51369962/63934942-65e6ae80-ca97-11e9-8a3c-e4f1fbe3ddf6.PNG)
![3](https://user-images.githubusercontent.com/51369962/63934943-65e6ae80-ca97-11e9-9194-f00a86a88ab3.PNG)

here's my all configuration
i changed nothing both of config file and plugins
even though i changed ConPTY setting, problem still happened

and i'm using on windows 10 18965.1005

**Comment by Eugeny** [comment]
Please change the frontend to xterm (which is now the default). 
hterm is known to have multiple issues with double-width characters

**Comment by winetree94** [comment]
![Capture](https://user-images.githubusercontent.com/51369962/63935571-bad6f480-ca98-11e9-8216-11fb767efc93.PNG)

if i change the frontend to xterm, every korean characters just typed "?"
i'm using korean included font

**Comment by winetree94** [comment]
On WSL, korean ime is work, maybe powershell problem,  i will try some of ways and i will report

**Comment by Eugeny** [comment]
Could you please upgrade to the latest nightly and provide a dump of your terminal state as described here? https://github.com/Eugeny/terminus/wiki/Posting-terminal-state

(with xterm)
