### ISSUE TITLE
Overlay text in the console

### ISSUE THREAD

**Issue by Paul75** [Eugeny/terminus#1435]
Hello,

As you can see on the attached photo, if I enter for example: nano my_doc.php, the file is displayed but the old text of the console remains behind and it is unreadable. I use Windows 10.

![Terminus_nano_superposition_text](https://user-images.githubusercontent.com/457062/64002743-104be980-cb0b-11e9-99cc-d81609f01a29.PNG)

Thanks

**Comment by cmonat** [comment]
I have something similar when I want to use a command line from the history, if I go "too far" (only two or three command before is enough) the commands are mixing and it's difficult to read it.
For example:
`[celmonat@hpc2 ~]$  ls $HOME/Wls $HOME/WheatOMICS/testhicProOutputs/rawdata_splited/`
