### ISSUE TITLE
Terminus is not opening the correct folder in the context menu Mint Linux 19.2

### ISSUE THREAD

**Issue by desenvolvedorfmais** [Eugeny/terminus#1436]
#English
I have problems using terminus on Mint Linux 19.2. When I try to open a folder using the context menu click as gif image below, terminus always points to the logged in User folder. 

I installed the version below and it is working normally, but in the latest version 1.0.89 does not work
[Terminus 1.0.0](wget https://github.com/Eugeny/terminus/releases/download/v1.0.0-alpha.18/terminus_1.0.0-alpha.18_amd64.deb)
How to solve this question?
Thank you
Instalei a versão abaixo e está funcionando normalmente, porém na última versão 1.0.89 não funciona
wget https://github.com/Eugeny/terminus/releases/download/v1.0.0-alpha.18/terminus_1.0.0-alpha.18_amd64.deb

#PT BR
Estou com problemas ao utilizar o terminus no Mint Linux 19.2. Quando tento abrir alguma pasta usando o click do menu context conforme imagem gif abaixo, o terminus sempre aponta para a pasta do Usuário logado. 
Instalei a versão abaixo e está funcionando normalmente, porém na última versão 1.0.89 não funciona
[Terminus 1.0.0](wget https://github.com/Eugeny/terminus/releases/download/v1.0.0-alpha.18/terminus_1.0.0-alpha.18_amd64.deb)

Como resolver essa questão? 
Obrigado

![terminus](https://user-images.githubusercontent.com/35231033/64027443-18aa2180-cb17-11e9-9e76-a39f3783566b.gif)

**Comment by tsdeveloper** [comment]
// ENGLISH
I am having the same problem, they have released version 1.0.90 but still the same problem. It also does not open folders when you right-click. It would also be interesting to have options to open by default in tabs, it's very annoying to open the terminal as a new instance.

//PT BR
Estou tendo o mesmo problema, eles lançaram a versão 1.0.90 mas continua o mesmo problema. Além também de não abrir as pastas quando clica com o button direito. Seria interessante também ter opções de abrir por default em abas, é muito chato abrir o terminal como nova instância
