### ISSUE TITLE
Can't scroll hotkeys list

### ISSUE THREAD

**Issue by mparry** [Eugeny/terminus#1437]
Version: 1.0.90
Platform: Windows 10 x64 (build 18970)

I almost reopened #1072 but that was reported against macOS, and since that was fixed I'm guessing that this may not be exactly the same issue. Anyway, I don't seem to be able to scroll the list of hotkeys. I can work around with searching for now, of course, but it does hamper discoverability quite a bit!

**Comment by mparry** [comment]
Also can't scroll the plugins list, I realised a bit later.

It _does_ work within shells and in the config display.

**Comment by GoodbyeNJN** [comment]
Same problem for me at same version and same platform.

**Comment by Eugeny** [comment]
Fixed in the nightly build
