### ISSUE TITLE
problems opening a specific directory using Mint 19 Linux

### ISSUE THREAD

**Issue by tsdeveloper** [Eugeny/terminus#1438]
Version: 1.0.90
Platform: linux 4.15.0-58-generic
Plugins: none

How do I open multiple tabbed directories in terminus for a specific profile?

![terminus](https://user-images.githubusercontent.com/5727326/64065390-6d1ad300-cbe3-11e9-93d3-4f656346a4da.png)

**Comment by Eugeny** [comment]
A profile can only contain one tab with one CWD.
If you're referring to CLI usage, you can open multiple tabs by running `terminus open <directory>` multiple times.
