### ISSUE TITLE
Can't Scroll Vertically in Settings pages.

### ISSUE THREAD

**Issue by tampiko** [Eugeny/terminus#1439]
Version: 1.0.90
Platform: win32 10.0.16299
Plugins: none

**Comment by entrptaher** [comment]
I just wanted to test this for first time out on my ubuntu 18.04 and saw I could not scroll vertically. I didn't expect this from a version 1.0.90 product. 

Hopefully this gets fixed, this looks nice.

**Comment by hdougie** [comment]
I believe I may have fixed this locally with some small CSS changes. I'm just testing a few more bits and then if it all seems good I'll submit a PR.
