### ISSUE TITLE
Build failure?

### ISSUE THREAD

**Issue by SolarAquarion** [Eugeny/terminus#144]
ERROR in ./src/index.ts
Module not found: Error: Can't resolve 'ngx-perfect-scrollbar' in '/home/solaraquarion/terminus/terminus-core/src'
 @ ./src/index.ts 17:32-64

ERROR in ./src/index.ts
Module not found: Error: Can't resolve 'perfect-scrollbar/dist/css/perfect-scrollbar.css' in '/home/solaraquarion/terminus/terminus-core/src'
 @ ./src/index.ts 40:0-59

ERROR in ../node_modules/css-loader!../node_modules/sass-loader/lib/loader.js!./src/theme.scss
Module build failed: 
@import '~bootstrap/scss/bootstrap.scss';
^
      File to import not found or unreadable: ~bootstrap/scss/bootstrap.scss.
Parent style sheet: stdin
      in /home/solaraquarion/terminus/terminus-core/src/theme.scss (line 76, column 1)
 @ ./src/theme.scss 2:21-130
 @ ./src/theme.ts
 @ ./src/index.ts

ERROR in [at-loader] ./terminus-core/src/components/appRoot.component.ts:17:15 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/components/appRoot.component.ts:18:14 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/components/renameTabModal.component.ts:6:15 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/components/startPage.component.ts:1:21 
    TS2307: Cannot find module 'os'.

ERROR in [at-loader] ./terminus-core/src/components/startPage.component.ts:8:15 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/components/startPage.component.ts:9:14 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/components/tabBody.component.ts:13:9 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/components/tabBody.component.ts:14:9 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/components/tabHeader.component.ts:8:15 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/components/tabHeader.component.ts:9:14 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/components/titleBar.component.ts:5:15 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/components/titleBar.component.ts:6:14 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/components/windowControls.component.ts:6:15 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/components/windowControls.component.ts:7:14 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/config.ts:6:27 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/config.ts:7:29 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/config.ts:8:27 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/config.ts:10:16 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/index.ts:6:40 
    TS2307: Cannot find module 'ngx-perfect-scrollbar'.

ERROR in [at-loader] ./terminus-core/src/services/config.service.ts:4:21 
    TS2307: Cannot find module 'fs'.

ERROR in [at-loader] ./terminus-core/src/services/config.service.ts:10:31 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/services/electron.service.ts:16:25 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/services/hostApp.service.ts:34:29 
    TS2304: Cannot find name 'require'.

ERROR in [at-loader] ./terminus-core/src/services/hotkeys.util.ts:5:3 
    TS2304: Cannot find name 'process'.

ERROR in [at-loader] ./terminus-core/src/services/hotkeys.util.ts:11:3 
    TS2304: Cannot find name 'process'.

ERROR in [at-loader] ./terminus-core/src/theme.ts:7:11 
    TS2304: Cannot find name 'require'.

**Comment by Eugeny** [comment]
Make sure you have installed the sub-dependencies using the `install-deps.js` script as per https://github.com/Eugeny/terminus/blob/master/HACKING.md

**Comment by SolarAquarion** [comment]
@Eugeny also .desktop would be good.  I'm making a PKGBUILD for this project

**Comment by Eugeny** [comment]
I'm currently using the .desktop file generated by `electron-builder`. You can extract it from the .deb or .rpm package.

**Comment by SolarAquarion** [comment]
@Eugeny I don't see the .desktop in the rpm directory when i unpack it

**Comment by Eugeny** [comment]
Strange. MC shows it for me: 
![image](https://user-images.githubusercontent.com/161476/28583426-658d35f0-7169-11e7-8248-c2d2ca37ab8f.png)

**Comment by Eugeny** [comment]
```
[Desktop Entry]
Name=Terminus
Comment=A terminal for a modern age
Exec="/opt/Terminus/terminus"
Terminal=false
Type=Application
Icon=terminus
Categories=Utilities;
```

**Comment by SolarAquarion** [comment]
Almost done the final touches of the PKGBUILD for the git version

**Comment by Eugeny** [comment]
Please post the install instructions for Arch when you're done and I'll add them to README!

**Comment by SolarAquarion** [comment]
https://aur.archlinux.org/packages/terminus-terminal I decided to use the deb for the stable ver.
