### ISSUE TITLE
Scrolling in settings issue

### ISSUE THREAD

**Issue by smamusa** [Eugeny/terminus#1453]
Scrolling using touchpad in the settings view is not working. I have to manually resize the window in order to see the controls ( buttons etc. ).

The graphical performance is a bit worrying since this is a terminal application and the printouts feel kinda laggy. What I mean is that letters render a bit slow, both while typing and while the command are listing output.

Sorry for putting two issues in one, I can open a second one for the graphics part.

Version: 1.0.90
Platform: win32 10.0.18362
Plugins: none

**Comment by hdougie** [comment]
I believe that this is a duplicate and already reported in #1439

**Comment by smamusa** [comment]
Sorry for the trouble. Closing it.
