### ISSUE TITLE
Can't call SublimeText from subl command

### ISSUE THREAD

**Issue by jaredchu** [Eugeny/terminus#146]
When enter `subl filename` or `subl .`
**Expected:**
SublimeText display and open the file or folder.
**Actual:**
Nothing happened.

**Comment by Eugeny** [comment]
Which Terminus version are you using>

**Comment by jaredchu** [comment]
v1.0.0-alpha.22 on Ubuntu 16.04

**Comment by Eugeny** [comment]
what does `echo $DISPLAY` in Terminus show?

**Comment by jaredchu** [comment]
```
echo $DISPLAY 
:0
```
But it works now.
