### ISSUE TITLE
我不知道为什么我的控制台什么都不能输入

### ISSUE THREAD

**Issue by ironmn** [Eugeny/terminus#1465]
Version: 1.0.90
Platform: win32 10.0.17763
Plugins: none

**Comment by Eugeny** [comment]
Please translate the ticket to English, thank you.

**Comment by PMExtra** [comment]
It means:
I don't know why I can't enter anything in my console.

I think it's a invalid issue because there is no any useful message. Please close it.

To author:
我建议关闭这个问题，因为您没有提供任何有效的信息。你可以重新发起一个新的问题，并详细描述问题的现象，如有必要可以配合截图/录屏，并说明触发该问题的条件和步骤。
