### ISSUE TITLE
Can't use when maximized since Alpha 90

### ISSUE THREAD

**Issue by scrossan-crown** [Eugeny/terminus#1467]
When I maximize the terminus window it becomes unusable but if not maximized it is fine. See the below screenshots

OS: Windows 10 

Maximized
![image](https://user-images.githubusercontent.com/30405149/64319800-23e8cb80-cfb5-11e9-94fb-7a50bc1238d7.png)

Unmaximized
![image](https://user-images.githubusercontent.com/30405149/64319910-585c8780-cfb5-11e9-9431-87a51375f9fe.png)

**Comment by Eugeny** [comment]
This should already be fixed in the [nightly build](https://ci.appveyor.com/project/Eugeny/terminus/build/artifacts) - please check.

**Comment by scrossan-crown** [comment]
It is definitely fixed in the nightly build
