### ISSUE TITLE
Cannot turn to transparency

### ISSUE THREAD

**Issue by Chr1s-T** [Eugeny/terminus#1468]
Cannot turn to transparency even though I turn on the option, as the picture describes. When I ssh to a server my terminal 's background is always so dark. How to fix the problem? I want the terminal's background is transparency too.
![image](https://user-images.githubusercontent.com/23159278/64331883-2f181780-d006-11e9-9549-aa1980570693.png)
![image](https://user-images.githubusercontent.com/23159278/64331902-363f2580-d006-11e9-9ac7-48f7fc465f4d.png)

**Comment by Chr1s-T** [comment]
![image](https://user-images.githubusercontent.com/23159278/64332011-61297980-d006-11e9-94b7-cc5460ba28d0.png)

**Comment by Eugeny** [comment]
xterm-webgl frontend doesn't support terminal transparency at this time.

**Comment by Chr1s-T** [comment]
> xterm-webgl frontend doesn't support terminal transparency at this time.

That's it, thank you. It works again when I switched to xterm mode.

**Comment by vprimin** [comment]
So as I understand there is no option to turn on transparency on MacOS ?
Maybe you have it on your roadmap?

**Comment by SaladinoGW** [comment]
Manjaro KDE :(
