### ISSUE TITLE
Do i need to compile the colorscheme thing seperately?

### ISSUE THREAD

**Issue by SolarAquarion** [Eugeny/terminus#148]

**Comment by Eugeny** [comment]
No, the plugins you see in this repo are auto-bundled inside the build

**Comment by SolarAquarion** [comment]
I don't see the color schemes where I go to terminal settings

**Comment by Eugeny** [comment]
Do you see it in the plugins list?

**Comment by SolarAquarion** [comment]
Yes. I press the colorscheme drop down and don't see anything

On Jul 27, 2017 6:00 AM, "Eugene Pankov" <notifications@github.com> wrote:

Do you see it in the plugins list?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Eugeny/terminus/issues/148#issuecomment-318317596>, or mute
the thread

**Comment by Eugeny** [comment]
Does the plugin get loaded? (see devtools / app log)
