### ISSUE TITLE
"Acrylic background" has no effect

### ISSUE THREAD

**Issue by Komposten** [Eugeny/terminus#1483]
The "Acrylic background" setting appears to have no effect for me. Doesn't matter if I set it to "Blur" or "Fluent"; the background remains sharp:

![image](https://user-images.githubusercontent.com/7335682/64526269-21fb7100-d303-11e9-8c64-67b5e2034dcf.png)

--
Terminus: Alpha 90
OS: Windows 10 1903 Build 18362.295

**Comment by Eugeny** [comment]
Do other UWP apps have acrylic backgrounds on your system?

**Comment by Komposten** [comment]
It works in both Windows Settings and Windows Terminal.

**Comment by mnpenner** [comment]
It works for me, but only after restarting the app, and Fluent is ridiculously laggy. Blur seems fine. On Windows 10.

**Comment by Komposten** [comment]
Update: It appears that it's the Gruvbox theme that breaks the acrylic background. If I use any of the default themes (standard, compact or paper) acrylic works perfectly fine.

**Comment by Eugeny** [comment]
@Komposten yeah, if the theme forces the background to be non-translucent, the window won't be transparent anymore.

@mnpenner see #949
