### ISSUE TITLE
Key 'Home' and 'End' are not working on CentOS

### ISSUE THREAD

**Issue by Songzr** [Eugeny/terminus#1490]
version 1.0.90
Key 'Home' and 'End' are not working when connect to CentOS using ssh -- the cursor doesn't move to the begining or the end of line.
They are worked fine on local terminal (at least on Windows 10 terminal).

**Comment by Songzr** [comment]
By the way, I'd like to help translating the UI into chinese, but I know nothing about TypeScrpit language... Could you tell me how can I help with internalization if you need?

**Comment by xell90** [comment]
Same issue here, this is mandatory for us! Please fix!
