### ISSUE TITLE
pasted content changes in ssh terminal

### ISSUE THREAD

**Issue by splintereddy** [Eugeny/terminus#1491]
version: 1.0.90 mac 
when i open a ssh connection and paste a command like `du -d 1 -h /home` , it becomes `0~du -d 1 -h /home1~`, making the command can't to be executed, it's so wired!! it's all ok when using iterm2 to open the ssh connection

**Comment by Eugeny** [comment]
It's likely that your shell doesn't support *bracketed paste* - you can disable it in Settings.
