### ISSUE TITLE
Terminal not starting when using normal cmd

### ISSUE THREAD

**Issue by vinguan** [Eugeny/terminus#1493]
Version: 1.0.90
Platform: win32 10.0.18362
Plugins: none

![Terminus_xi1EliCJRq](https://user-images.githubusercontent.com/6222878/64624814-972d7b80-d3c1-11e9-9ced-95886d7a85dd.png)

Administrator terminal works just fine.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by vinguan** [comment]
![image](https://user-images.githubusercontent.com/6222878/64707530-86483d00-d489-11e9-917d-e15cb8af659b.png)

**Comment by Eugeny** [comment]
Could you please check the $PATH value Terminus is using? Just type `process.env.PATH` in the debug console.

**Comment by vinguan** [comment]
![image](https://user-images.githubusercontent.com/6222878/65515041-e80a9d00-deb4-11e9-8de7-fb701e500c55.png)
It's using the user's PATH when executing a normal terminal. It's the expected behavior I think, but shouldn't it configure his required path variables prior executing? I installed via the exe on the releases.
