### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by selfsalty** [Eugeny/terminus#1495]
Version: 1.0.90
Platform: win32 10.0.18362
Plugins: none

The process is killed. Restart is still the old version.

**Comment by ZaLiTHkA** [comment]
I had the same experience trying to update from alpha 88; watching the list in Process Explorer, it seems like the setup process itself is also killed when the main Terminus process is closed.

**Comment by kachunkachunk** [comment]
Yep, I can confirm this has been going on for many versions now, including .90 to .91 today.

If you allow the installer to start the actual installation process (progress bars and all), quickly close the lingering Terminus console window yourself, the installer should finish; it will prompt if you want to relaunch Terminus - go ahead if you like, it should be updated fine this time.

Seems it all goes wrong if you leave the existing console window open and _both_ terminate without updating.

**Comment by ZaLiTHkA** [comment]
> Edit: Should mention this is for my installations set for All Users. I wonder if folks using the user profile (Only For Me) installation do not have this experience, since privileges are more relaxed there. I have yet to test that install scheme.

FWIW, I install mine with the "Just for me" option, so it's not affected by that part..

Also, Process Explorer shows a tree view of processes, with child processes listed in a collapsible section of it's parent process. From that I can tell that (in this scenario) the setup package is launched as a child process of the primary Terminus instance, after that I *suspect* the setup package is killing the target process *tree* (i.e.: target process and all it's children) when it closes Terminus.

Perhaps the solution here is to get the setup package to be launched as it's own top-level process instead? Then it wouldn't commit suicide when it closes the currently running Terminus instance.

**Comment by iomicifikko** [comment]
I can confirm that the problem appears in the "Just for me" installation also. Here's my situation:

Version: 1.0.104
Platform: win32 10.0.18363 (x64)
Plugins: none
Install folder: c:\users\username\AppData\Local\Programs\Terminus

- Program starts, after a few seconds gift icon appears
- Click on gift icon
- Click on "Update"
- Select "Just for me" and click on "Install"
- Click "Ok" on pop-up warning that program is still alive
- Both Terminus and Terminus Update Process exit after a few seconds.

End
