### ISSUE TITLE
Terminus hotkeys steal keypressed from tmux

### ISSUE THREAD

**Issue by dualmoon** [Eugeny/terminus#151]
Tmux is unusable due to hotkeys being passed to Terminus. My tmux prefix is Ctrl-A which conflicts with Terminus' hotkey. I tried removing all "Ctrl-A" based hotkeys but the keys still don't make it to tmux.

**Comment by valeryan** [comment]
Also, makes using gnu screen a little difficult as you can't detach screens using `Ctrl`+`A` commands.

**Comment by MeltedLux** [comment]
Sort of related, terminus also steals keys from other programs while it is not in focus.

e.g. minimizing the app and then using chrome, Ctrl+Shift+V will go to terminus.

**Comment by Eugeny** [comment]
@valeryan I can now confirm that removing all Ctrl-A shortcuts from terminus will foward Ctrl-A keypresses to the Screen inside.
