### ISSUE TITLE
Program wont appear in Windows 10

### ISSUE THREAD

**Issue by TaxaList** [Eugeny/terminus#1511]
In Windows 10 since a few updates ago the Terminus window won't appear though the process is running. Uninstalling and reinstalling Terminus did not fix issue.

Edit: I tried reinstalling again and it seems to work now.

**Comment by adidus** [comment]
The same problem

**Comment by madcpt** [comment]
I had the same issue after updating to v0.91
You should try falling back to v0.88

**Comment by kerwitz** [comment]
This seems to be happening for me after every update. I install Terminus, use it for a while, then the app disappears and the start menu shortcuts do not work any longer. Only reinstalling helps.

**Comment by trolhamonas** [comment]
I'm going to try downgrading to v0.88 since the problem is still there on newer versions and see, will report back.
