### ISSUE TITLE
Can't display Chinese directly.

### ISSUE THREAD

**Issue by danielduyixin** [Eugeny/terminus#1519]
Version: 1.0.91
Platform: win32 10.0.18362
Plugins: none
Can't display Chinese directly.
Maybe need to support utf-8 or GBK encoding
![image](https://user-images.githubusercontent.com/19722567/64864759-6623a400-d66a-11e9-9e8f-f6e707870e13.png)

**Comment by aqrun** [comment]
Version: 1.0.91
Platform: win64 10.0.17134
Plugins: none
Same to me, non English folder names are not correctly decoded to show

![image](https://user-images.githubusercontent.com/4224867/64935798-b75baf80-d885-11e9-9e9e-dc0c899a96df.png)

**Comment by darkevil1102** [comment]
i need UTF-8 encoding too

**Comment by Eugeny** [comment]
Please upgrade to the latest nightly and provide a dump of your terminal state as described here: https://github.com/Eugeny/terminus/wiki/Posting-terminal-state
