### ISSUE TITLE
Curly Brackets (Bash on Windows) Windows 10 - Spanish Keyboard

### ISSUE THREAD

**Issue by sntiagoma** [Eugeny/terminus#152]
I've installed terminus on Windows 10 and I use it with Linux Subsystem (Bash - Ubuntu), My keyboard distribution is Spanish (Spain) but I'm not able to write **{** or **}** in the shell. Instance it's writing other characters that are not the ones of the key that I'm typing; It's like if the program wasn't getting the characters that are been input in the system or has a problem with Spanish distribution because when I've tried with a English (US) keyboard it works properly.

**Comment by Eugeny** [comment]
Duplicate of #17
