### ISSUE TITLE
upgrade failed

### ISSUE THREAD

**Issue by seiry** [Eugeny/terminus#1520]
Version: 1.0.90 => 1.0.91
Platform: windows 10 1803 enterprise 
Plugins: none

the first install was failed, then the files in `C:\Users\Seiry\AppData\Local\Programs` was removed by the installer. reopen the installer, it will stuck at loading

![image](https://user-images.githubusercontent.com/4397354/64917241-7cdc0f00-d7c0-11e9-808a-043ed1eb259e.png)
![image](https://user-images.githubusercontent.com/4397354/64917243-82d1f000-d7c0-11e9-8e6a-29ccb4ef4a55.png)
![image](https://user-images.githubusercontent.com/4397354/64917244-8bc2c180-d7c0-11e9-87a4-02153c1b3aa3.png)

**Comment by seiry** [comment]
Manually delete registry `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\{d31d809c-e53c-572c-9d08-2a14932bd95e}` helps.
 I think a `clear reinstall` option is needed for windows platform maybe

**Comment by KabesaKubo** [comment]
Same to me. Thanks for the solution, but the dev need to fix this.

**Comment by tomshaw** [comment]
I'm stuck with a Terminus loading screen on update.
