### ISSUE TITLE
dont see what i type

### ISSUE THREAD

**Issue by eran10** [Eugeny/terminus#1521]
Version: 1.0.91
Platform: win32 10.0.18362
Plugins: theme-windows10, title-control

i dont see what i type, what can i do ? i try to close and re-open but still the same

![image](https://user-images.githubusercontent.com/5971236/64918305-13023c00-d7a5-11e9-848e-cb5f82071fa3.png)

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs
