### ISSUE TITLE
quick-cmds can not be used

### ISSUE THREAD

**Issue by SuperYogurt** [Eugeny/terminus#1529]
No response after sending the command

**Comment by mishoboss** [comment]
This issue is since a lot of time now. Seems the quick-cmds plugin doesn't get much love. @Eugeny , is it discontinued?

**Comment by Eugeny** [comment]
Looks like it. Unfortunately it's a third-party plugin

**Comment by mishoboss** [comment]
@Eugeny , how hard would be this feature to land as a part of the core app?

**Comment by sburkett** [comment]
I agree ... this would be a terrific addition to Terminus. It was nice to be able to fire off a bunch of commands to all of my open SSH windows.

**Comment by mishoboss** [comment]
Probably worth putting it as a feature request.

**Comment by Eugeny** [comment]
Fixed in `quick-cmds` 1.2.0
