### ISSUE TITLE
Copy paste longer than selected text

### ISSUE THREAD

**Issue by jaredchu** [Eugeny/terminus#153]
I only selected `jaredchu` from the first line but it copy longer than I needed.
This issue happen very frequently.
[![SCREEN SHOT](http://i.imgur.com/HhTiMJT.jpg)]()

**Comment by jamgregory** [comment]
I've been experiencing the same thing in alpha 27 - selecting some of the screen and pressing Ctrl+Shift+C (on Ubuntu 16.04 with 'screen' mode enabled) selects the whole line instead of the part selected.

**Comment by jaredchu** [comment]
Ya, this issue keep me using gnome terminal instead of terminus. It's
really usually happen.
