### ISSUE TITLE
中文显示乱码

### ISSUE THREAD

**Issue by SanZY05** [Eugeny/terminus#1532]
Version: 1.0.91
Platform: win64 10.0.18362
Plugins: none

**Comment by w2r** [comment]
大兄弟，你怎么解决乱码的

**Comment by allenjol** [comment]
@w2r 
I want to know how to solve the problem of garbled code

**Comment by hailin84** [comment]
When I use ls command from Git for Windows in tabby console, directories contains Chinese characters show  garbled code. Here is my solution:
execute this command first:
set LANG=zh_CN.UTF-8
Or you can just set user enviroment variable LANG=zh_CN.UTF-8
Everything is fine now.  It also works for windows command prompt, cmder etc.

Just FYI. @ayunwSky @w2r @ghost

**Comment by doglex** [comment]
参考这个 https://blog.csdn.net/ss0660ss/article/details/125213360
tabby的设置--配置文件里找到appearance那行，添加一行，注意开头是两个空格：

```
appearance:
  Character encoding: UTF-8
```

保存，重启tabby
