### ISSUE TITLE
Last line not visible 

### ISSUE THREAD

**Issue by gonwms** [Eugeny/terminus#1533]
Version: 1.0.91
Platform: win32 10.0.18362
Plugins: clickable-links

The scroll never reach the last line.

![Uploading Anotación 2019-09-18 234843.png…]()

**Comment by urzz** [comment]
I had the same problem.

When I set the window full screen, the last line not visible.

Version: 1.0.91
Platform: win10 x64 1903 18362.239

**Comment by cafeduke** [comment]
The last line was partially visible. I changed Settings > Application > Window Frame from "Full" to "Native". The last line is now visible. 

Version: 1.0.98
Platform: Ubuntu 19.10

**Comment by Eugeny** [comment]
Could you please grab the latest nightly and provide a dump of your terminal state as described here? https://github.com/Eugeny/terminus/wiki/Posting-terminal-state
