### ISSUE TITLE
SSH screen dont self clear

### ISSUE THREAD

**Issue by MstrTaffy** [Eugeny/terminus#1535]
Version: 1.0.91
Platform: win32 10.0.18362
Plugins: none

1) SSH into a server
![1](https://user-images.githubusercontent.com/30232425/65215876-71575380-daf2-11e9-9176-bb7f5319df7d.PNG)
2) screen -x into a Screen.
![2](https://user-images.githubusercontent.com/30232425/65215878-71efea00-daf2-11e9-8ac8-010db2b52e92.PNG)
3) Press CTRL A+D
![3](https://user-images.githubusercontent.com/30232425/65215879-71efea00-daf2-11e9-968a-091600c142e7.PNG)
4) Screen information stays, doesn't self clear
![4](https://user-images.githubusercontent.com/30232425/65215880-71efea00-daf2-11e9-94de-b5dad9afeba6.PNG)

**Comment by windzhu0514** [comment]
I also encountered this error.
