### ISSUE TITLE
when closing one tab, app should focus input on the next open tab

### ISSUE THREAD

**Issue by JeffMelton** [Eugeny/terminus#1537]
Version: 1.0.91
Platform: win32 10.0.17134
Plugins: clickable-links, scrollbar, title-control

What happens:
When closing a tab with Ctrl-D, input is not focused on the next open tab.

How to repeat:
Open two or more terminal tabs. Close one with Ctrl-D. Note that input is not focused on the remaining terminal.

Expected Behavior:
When closing a terminal tab with Ctrl-D, input focus should switch to the next open tab.

**Comment by abassanini** [comment]
Anyone knows a workaround?

**Comment by Eugeny** [comment]
Duplicate of #2525
