### ISSUE TITLE
Request for adding paste from clipboard

### ISSUE THREAD

**Issue by mariaquilac** [Eugeny/terminus#154]
Version: 1.0.0-alpha.23
Platform: win32 10.0.15063

I found terminus today and instantly became a big fan!
However, I have one problem that I couldn't paste code from clipboard...
It'll be great if that function be added.
I appreciate your decision in advance.

**Comment by Eugeny** [comment]
Paste is Cmd-V on Mac and Ctrl-Shift-V everywhere else.
