### ISSUE TITLE
Unable to select SSH private key using "browse" button

### ISSUE THREAD

**Issue by lpreiner** [Eugeny/terminus#1540]
When creating a new SSH connection and attempting to select a private key file, the filename is not populated after selecting a file.

1. Navigate to Settings > SSH
2. Click "+ New Connection"
3. Click the "folder" icon on the "Private key" input
4. Select a file
5. "Key file path" input is not populated

Version: 1.0.91
Platform: win32 10.0.17763
Plugins: none

**Comment by Eugeny** [comment]
Fixed in the latest nightly
