### ISSUE TITLE
Console Flashing seems to be not implemented

### ISSUE THREAD

**Issue by UweKeim** [Eugeny/terminus#1553]
Using Terminus on Windows, in our build scripts we are using a call to the [Platform SDK function `FlashWindowEx()`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-flashwindowex) to signal errors to the user, even when the console is minimized.

When our scripts run in the native CMD console, the task bar icon of the calling window is being correctly flashed (i.e. the background is periodically highlighted).

It seems to be _not_ implemented at all in Terminus. I.e. when running a program that flashes the window, nothing is visible in the task bar icon.

I've written a small program to illustrate the behaviour. See the attached files for both source code and a .NET compiled version:

> [console-flasher.zip](https://github.com/Eugeny/terminus/files/3656576/console-flasher.zip)

### My question/request

Please support the flashing of the window title and task bar icon of Terminus. Probably the tab that creates the flash should also be flashing.

**Comment by Eugeny** [comment]
Which HWND are you passing to `FlashWindowEx()`? Due to how Terminus is implemented, it's running a hidden conhost window (which likely would be "flashing") when ConPTY is disabled.
When ConPTY is enabled, I believe there's no way for client application to get a host's HWND, since it might not even have a window.

**Comment by UweKeim** [comment]
This is an excerpt of the code:

```csharp
var consoleWindowHandle = GetConsoleWindow();
var foregroundHandle = GetForegroundWindow();

if (consoleWindowHandle.Equals(foregroundHandle))
{
    // If already foreground window, flash a few times, then stop.

    var fInfo = new FLASHWINFO();
    fInfo.cbSize = Convert.ToUInt32(Marshal.SizeOf(fInfo));
    fInfo.hwnd = consoleWindowHandle;
    fInfo.dwFlags = FLASHW_ALL;
    fInfo.uCount = 4;
    fInfo.dwTimeout = 0;
    FlashWindowEx(ref fInfo);
}
else
{
    // If background window, flash until in foreground.

    var fInfo = new FLASHWINFO();
    fInfo.cbSize = Convert.ToUInt32(Marshal.SizeOf(fInfo));
    fInfo.hwnd = consoleWindowHandle;
    fInfo.dwFlags = FLASHW_ALL | FLASHW_TIMERNOFG;
    fInfo.uCount = 4;
    fInfo.dwTimeout = 0;
    FlashWindowEx(ref fInfo);
}
```

It uses the [Platform SDK function `GetConsoleWindow()`](https://docs.microsoft.com/en-us/windows/console/getconsolewindow) to get the handle.

**Comment by UweKeim** [comment]
Maybe you could [hook to the hidden conhost window and get notified if it is being flashed](https://stackoverflow.com/q/7785334/107625), thus forwarding the flash to your own window?

**Comment by UweKeim** [comment]
Or, maybe, I could travel up to the parent process of the window returned by `GetConsoleWindow()` and flash that window instead?
