### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by latinos-bub** [Eugeny/terminus#1562]
Version: 1.0.91
Platform: win32 10.0.17134
Plugins: none

i have set LNAG=zh_CN.GBK, GB2312, GB18030 so on ...
but not .
for example 

2019-09-29 00:00:01 [����: ERROR]  [����]:

**Comment by yfwz100** [comment]
Maybe `LANG=zh_CN.UTF-8` ？

**Comment by util-you-com** [comment]
nonono, that is even worse!!! I have tried it

**Comment by Eugeny** [comment]
Please upgrade to the latest nightly and provide a dump of your terminal state as described here: https://github.com/Eugeny/terminus/wiki/Posting-terminal-state
