### ISSUE TITLE
Screen blanking out issue

### ISSUE THREAD

**Issue by sburkett** [Eugeny/terminus#1564]
I've noticed this for a while, but thought I would finally report it. Not sure if anyone else has experienced this or not.

I had several terminal sessions open earlier today. I left home for a few hours, and came back after a few hours. The entire app was "all black", with no tabs at the top, etc. Alt-F4 wouldn't close it either. Had to kill via it task manager in Win10.

I've also seen this behavior occasionally when I have multiple tabs open, and I CTRL-W out of one of them.

This is with v1.0.91, but as I said, I've been experiencing it for several versions.

I will let you know if I can provide more data on this.

**Comment by nonbeing** [comment]
I have a repro too, on v1.0.91, on Win10 x64.

**Comment by sburkett** [comment]
Just a ping to keep this issue alive. Still experiencing this issue periodically.

**Comment by sburkett** [comment]
Here is another clue that may be of help. I went away this weekend and when I got back, I saw all of the terminal screens blank. Tried to close one, and got the same problem (and Terminus hung on me, had to kill with Task Manager). I saw from other apps that my Internet connection had gone down for a bit, then came back online). So perhaps the lack of connectivity played a role here. Of course, I would expect that the Terminus sessions would eventually close due to the lack of connection, but perhaps it isn't handling it gracefully or something?

**Comment by sburkett** [comment]
Any update on this? This issue makes it pretty difficult to work with, especially when you have a dozen tabs open and all of a sudden they go away. :(

**Comment by BlackGlory** [comment]
The same issue here https://github.com/Eugeny/terminus/issues/1340, still have no idea.

**Comment by Eugeny** [comment]
Unfortunately no progress on this yet - I could get a reliable repro yet and these are Electron renderer process crashes, which are not easy to debug either.

**Comment by roman-geraskin** [comment]
same issue, 1.0.117
