### ISSUE TITLE
[feature request] Quake style dropdown terminal

### ISSUE THREAD

**Issue by krokofant** [Eugeny/terminus#157]
This is supported in terminals like CMDer and iTerm. Would be great to se this terminal support this feauture.

**Comment by Eugeny** [comment]
This is actually possible. Set `Docking` to Top and use the `Toggle Window` hotkey.

**Comment by yeralin** [comment]
Additional question, is "smooth" drop-down implemented?

**Comment by Eugeny** [comment]
No, but feel free to open an issue for that
