### ISSUE TITLE
Cannot remove the default profiles

### ISSUE THREAD

**Issue by PurpleSci** [Eugeny/terminus#1570]
For example, I installed Arch Linux for Windows Subsystem for Linux some time ago, but now I have deleted it and currently use Ubuntu on WSL. After that, I decided to try this terminal emulator. I found Arch there without an option to remove it, as well as the other profiles already included in Terminus.
Also I didn't find an option to add icons to custom profiles (the ones that I created).
Could you, please, add these options, dear Eugene?

**Comment by Eugeny** [comment]
The undeletable entries are not profiles, but rather the shells that Terminus detects at each startup. This means that Arch is still present as a WSL environment

**Comment by PurpleSci** [comment]
But I honestly deleted everything Arch... strange. WIndows Terminal behaves exactly like so, BTW. (I mean that it shows Arch and I cannot completely remove it, only "hide")

**Comment by PurpleSci** [comment]
And there is the "Custom shell" that is simply CMD. But I remember not creating it.

**Comment by PurpleSci** [comment]
And I recommend you changing the name to something else, because there already is a font with that exact name (Terminus) and even a production company.

**Comment by PurpleSci** [comment]
Terminus behaves AWFULLY with Cygwin. Instead of launching .bat file, it launches /bin/bash.exe and doesn't understand anything. If only there was an option to chnage the directory and/or parameters of the included profiles...
![cygwin_in_terminus](https://user-images.githubusercontent.com/44437701/66131514-3aa63080-e5fc-11e9-80d5-a62de0c7453c.png)
