### ISSUE TITLE
What's with the monkeypatching of Terminal.scrollToBottom?

### ISSUE THREAD

**Issue by Tyriar** [Eugeny/terminus#1578]
I'm curious why you are doing this:

https://github.com/Eugeny/terminus/blob/86e1abd44f272e76aa0194af6daa305b4ad68363/terminus-terminal/src/frontends/xtermFrontend.ts#L84-L85

**Comment by Eugeny** [comment]
This is to prevent xterm from unconditionally scrolling to the bottom on user input (see #1824)

**Comment by Tyriar** [comment]
@Eugeny I still don't really understand the problem, if you're in tmux you're in the alt buffer which means you have no scrollback or scroll bar and scrollToBottom should essentially do nothing?

**Comment by Eugeny** [comment]
@Tyriar it's really not just related to #543 - some people want to avoid losing the scroll position by accidentally hitting a key

**Comment by Tyriar** [comment]
Makes sense 👍 opened https://github.com/xtermjs/xterm.js/issues/1824 up to PRs
