### ISSUE TITLE
No color for new tabs

### ISSUE THREAD

**Issue by Annolize** [Eugeny/terminus#158]
everytime creating new terminal, the color scheme isn't working. only work in first tab
i'm using elementary OS.

![image](https://user-images.githubusercontent.com/30700498/28975943-292fd34c-7966-11e7-8e6b-ec39fc0dc4c0.png)

it should be like this 

![image](https://user-images.githubusercontent.com/30700498/28975984-515b54ea-7966-11e7-8754-4be62899c39f.png)

**Comment by Eugeny** [comment]
Your first tab says "SSH session" while the second doesn't. Could this be the reason? Are both shells on the same machine?

**Comment by Eugeny** [comment]
Closing due to the lack of activity. Please feel free to reopen if the issue is still relevant!
