### ISSUE TITLE
Copy paste into vim does not work

### ISSUE THREAD

**Issue by franciskim** [Eugeny/terminus#1589]
Version: 1.0.91
Platform: darwin 18.7.0
Plugins: clickable-links

Copy pasting around 100 lines of code from macOS 10.14.6 into vim messes up the indentation and the code becomes invalid.

**Comment by seag-rvc** [comment]
I have the same issue with Windows 7

**Comment by franciskim** [comment]
@seag-rvc I'll give that a try

**Comment by verhyppo** [comment]
Hi, I've tried to reproduce the bug on MacOS Catalina. 
I tried the following:
* multiline, tabbed with spaces (CRLF) (I noticed that the \n is doubled in this case)
* multiline, tabbed with tabs (CRLF) (I noticed that the \n is doubled in this case)
* multiline, tabbed with spaces (LF)
* multiline, tabbed with tabs (LF)

I used this text changing line ending and tabs/spaces
```
test
	test
		test
	test
test
```

I cannot understand what does it mean "messed up" actually, can you provide a sample input?

Thanks.

**Comment by franciskim** [comment]
`:set paste` actually works.

I'm unable to explain this issue further at this stage as I'm no longer on a Mac.
