### ISSUE TITLE
[feature request] Allow running different shells at the same time on windows

### ISSUE THREAD

**Issue by neodyma** [Eugeny/terminus#16]
Adding support for multiple shells (e.g. PS + Bash) in parallel would be great. Different shells could be made visible by using different colors in the corresponding tab for example.

**Comment by V3XATI0N** [comment]
this would be awesome, especially if you just ignore the "on windows" part and implement it for all platforms.

**Comment by princemaple** [comment]
Would also be great if we are able to open admin tabs! (if not possible already)

**Comment by grdnrio** [comment]
Would be great to add custom hot keys to support this. Ctrl-N = new Powershell tab, Ctrl-b = news bash tab etc.

**Comment by OvermindDL1** [comment]
> Would be great to add custom hot keys to support this. Ctrl-N = new Powershell tab, Ctrl-b = news bash tab etc.

Just not by default, Ctrl+<something> is often used by programs on the shell, especially both Ctrl+n and Ctrl+b are often used ones in many setups.

**Comment by Eugeny** [comment]
Now possible using the shell-selector plugin.
