### ISSUE TITLE
mac catalina Unable to install

### ISSUE THREAD

**Issue by Alenx58** [Eugeny/terminus#1607]
mac catalina 10.15  Unable to install

**Comment by dabat** [comment]
same-ish. actually the install package cannot be opened. and the app in the zip will not run.
![image](https://user-images.githubusercontent.com/37282138/80964589-ca040400-8dd6-11ea-9b7a-538efcd56417.png)
:(

**Comment by Eugeny** [comment]
You can still install it by right-clicking and selecting `Open`. I'll check why the notarization didn't go throuh.

**Comment by Eugeny** [comment]
I've just uploaded Alpha 109 which is now properly notarized by Apple.
