### ISSUE TITLE
how to disable taskbar's scrollbar percentage with vim?

### ISSUE THREAD

**Issue by hsnks100** [Eugeny/terminus#1608]
![image](https://user-images.githubusercontent.com/3623889/66631390-03113700-ec41-11e9-8970-e019366e8377.png)

I want to disable taskbar's flash( a part of green area).

I try to find way what I want, but I can't find that. 

I think terminus detect scrollbar percentage of neovim/vim. Let me know that how to off taskbar's flash.

**Comment by yan42685** [comment]
The same for me.

**Comment by Eugeny** [comment]
You can now disable it with the `terminal.detectProgress: false` option
