### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by umarmughal** [Eugeny/terminus#162]
After i update the app it stops working on Win10 .. only the splash screen and that's it .. anyone else?

**Comment by Eugeny** [comment]
Try pressing `Ctrl-Shift-I` or `F12` - this should bring up the Devtools (or alternatively start `terminus.exe --debug`). 
Paste any logs from the Console tab.

**Comment by umarmughal** [comment]
Nothing working out, neither `Ctrl-Shift-I` , `F12` nor command.
