### ISSUE TITLE
Feature Request: Option to disable middle click paste

### ISSUE THREAD

**Issue by JoelECourtney** [Eugeny/terminus#1631]
When I middle click to paste, both Ubuntu and Terminus paste separate paste bins, making the middle click functionality unusable. Please add a settings option that lets me disable Terminus' middle click paste feature.

**Comment by iExalt** [comment]
+1, it's a real pain to not be able to use middle click in Terminus on Ubuntu

**Comment by damien-lloyd** [comment]
+1 This is very annoying! At least make Terminus smart enough to only paste once for Linuxers.
