### ISSUE TITLE
Powerlevel9k icons are not shown in zsh theme on WSL

### ISSUE THREAD

**Issue by starcevpro** [Eugeny/terminus#1639]
![image](https://user-images.githubusercontent.com/24702947/66929586-f96e4180-f03b-11e9-83db-b16888464e59.png)

OS: Windows
Font: DejaVu Sans Mono Nerd Font Complete

**Comment by Eugeny** [comment]
Please upgrade to the latest nightly and provide a dump of your terminal state as described here: https://github.com/Eugeny/terminus/wiki/Posting-terminal-state
