### ISSUE TITLE
I cannot see tmux bottom bar on Linux Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by pwittchen** [Eugeny/terminus#164]
I cannot see tmux bottom bar on Linux Ubuntu 16.04 LTS.

Please take a look at the screenshot below, where we can compare default system terminal and Terminus. 
I have the latest version of Terminus: https://github.com/Eugeny/terminus/releases/tag/v1.0.0-alpha.27.

![zrzut ekranu z 2017-08-06 19-25-42](https://user-images.githubusercontent.com/695319/29005520-3581b214-7add-11e7-887a-158fc4f140b7.png)

**Comment by Eugeny** [comment]
You can't start a tmux inside a tmux because Terminus uses Tmux internally to persist tabs when Terminus quits. You can disable this behaviour by setting "Session persistence" to "off" or "GNU screen" in Settings > Terminal

**Comment by pwittchen** [comment]
I changed it to "Off", but after restart, it's set to Tmux again. I cannot see any "Save" button, so I assume it should save this setting after selection. Moreover, I can use several tmux features like splitting the screen. I just cannot see the bottom bar.

**Comment by Eugeny** [comment]
Seems that that "off" doesn't work (#165). Try "Screen".

**Comment by pwittchen** [comment]
With "Screen" it works fine, but bottom bar is cut as I reported in #62.

**Comment by Eugeny** [comment]
Please post a screenshot there and I'll reopen it
