### ISSUE TITLE
Ubuntu: Using "toggle terminal window" add a new icon in status bar each time

### ISSUE THREAD

**Issue by ByScripts** [Eugeny/terminus#1642]
Hello.

I just installed Terminus on Ubuntu 19.10.

Each time I hide the window with the "toggle terminal window" shortcut, a new icon is added in status bar.

![terminus icon bug](https://user-images.githubusercontent.com/19408/67016560-ab6b4380-f0f8-11e9-9ad1-98c6222f0b3f.png)

**Comment by Eugeny** [comment]
Upstream issue: https://bugs.launchpad.net/ubuntu/+source/libappindicator/+bug/1395229

**Comment by Eugeny** [comment]
`libappindicator` makes it impossible to hide an icon once it's been shown - I'm disabling the tray icon on Linux until that's solved.
