### ISSUE TITLE
Deleted itself without reinstalling when auto updating

### ISSUE THREAD

**Issue by zhufengning** [Eugeny/terminus#1646]
This happened several times

**Comment by Talkarcabbage** [comment]
Myself and a friend also had this happen.

**Comment by timotejroiko** [comment]
same thing happened to me, for some reason the updater didnt run. You can find the updater and run it manually in appData/Local/terminus-updater

**Comment by jylescoad-ward** [comment]
I have had the same thing to me, starting to get quite annoying.

**Comment by beeb** [comment]
Can confirm this happening on my machine too.

**Comment by timotejroiko** [comment]
The problem can be avoided if you manually close Terminus before clicking next in the updater window

**Comment by Eugeny** [comment]
Fixed

**Comment by HammSoftware** [comment]
This is still happening regularly for me, I constantly need to reinstall Termius manually.

**Comment by Eugeny** [comment]
Termius is a different project (unless it's a typo)

**Comment by HammSoftware** [comment]
> Termius is a different project (unless it's a typo)

So sorry, my bad. Feel free to remove, of course.

**Comment by areuddin** [comment]
This still seems to be a problem

**Comment by Badetuch** [comment]
I know its a different project, however this issue has attracted a lot of people and I can say that in March 2024, this issue still persists. However, the solution by timotejroiko fixes it short-term.

**Comment by csskroubledev** [comment]
Happened to me today. Didn't reinstall after auto updating.

**Comment by dexedrine-01** [comment]
Deleted itself automatically.

**Comment by Anas-Qadil** [comment]
termius keeps deleting itself automatically.

**Comment by e0xify** [comment]
happens still to me all the time...

**Comment by heggland** [comment]
this is getting really annoying..

**Comment by CodesterDubs** [comment]
happens to me at least once a month, only thing stopping me from moving to another client is the UI on termius, might have to reconsider if it keeps happening.. I lose all of my logins every time it uninstalls itself.

**Comment by heggland** [comment]
it happened again.. I just had termius open. Closed it and opened it again and boom its gone
![image](https://github.com/user-attachments/assets/508aedcb-0c8c-4313-b3d9-760b713eecc9)

**Comment by Eugeny** [comment]
@heggland wrong app

**Comment by CodesterDubs** [comment]
> @heggland wrong app

whenever you search about termius uninstalling itself this github issue shows up as the first result 😭

**Comment by Micro0x00** [comment]
same issue here

**Comment by CarlosPerez-VV** [comment]
Just happened to me

**Comment by Duoquote** [comment]
My termius just deleted itself this morning?

**Comment by DevinMina1** [comment]
> same thing happened to me, for some reason the updater didnt run. You can find the updater and run it manually in `AppData/Local/terminus-updater`

Thank you! This brought my Termius back from the dead!

**Comment by markusd1984** [comment]
Wow I was like what happened, did my wife uninstall or did it delete itself? lol

**Comment by olimexsmart** [comment]
Since I last commented the same thing happened with VSCode, I think it might be related to some bug in the electron app updater

**Comment by heggland** [comment]
can we get a fix for this?
 A better flow would be to ask the user to update the app when the user opens the app. Bitwarden do it like this..

**Comment by codecustard** [comment]
> Wow I was like what happened, did my wife uninstall or did it delete itself? lol

thought I got hacked!

**Comment by gummifisch24** [comment]
Same here, happend many times to me too

**Comment by cristake007** [comment]
happened to me twice and did not even press update...on two separate machines

**Comment by diego-develops** [comment]
This keep happening to me, so annoying

**Comment by FriskyFennecFox** [comment]
It deleted itself on my Windows 11 machine as well! The .lnk file points to `%USERPROFILE%\AppData\Local\Programs\Tabby\Tabby.exe`, but, while the path exists, the `Tabby.exe` executable (or any other files in that directory) is simply absent.

**Comment by Taykun345** [comment]
I am furius with this app. Constant new versions AND constants automatic removals of the application on 2 different PCs!?! Maybe this is on purpose because I use starter version!? I dont know. First time in 20+ years that application is removing itself over and over again. And issue is closed... really? Must be on purpose then for those who use free version.

**Comment by kylerhenry** [comment]
This just happened to me too; should not be marked closed.
