### ISSUE TITLE
Settings seems to be stuck on US Keyboard 

### ISSUE THREAD

**Issue by m0ll3art** [Eugeny/terminus#1651]
I'm trying to define a **Hotkey** to toggle the main window on and off by inserting `§` as a character on Swiss-DE keyboard layout but _terminus_  translates it to `'`  (backtick actually) same for `^`translated to `=`. Otherwise, in the terminal swiss-DE layout is well supported including ALTGR keys e.g. ALTGR-`^` for `~`  

Is there something I missed ?

**Comment by m0ll3art** [comment]
In the settings panes, most on the inputs are using the user-defined keyboard, but HotKeys and control keystrokes i.e.  not  made in an editor or text-box or -area are bound to some kind of US Keyboard layout

**Comment by RibShark** [comment]
I am having a similar issue with a UK keyboard. I want to assign "toggle terminal" to CTRL+', but when I add the shortcut, despite it displaying as "CTRL+'", the toggle actually happens with CTRL+#. Setting the shortcut to "CTRL+#" then both displays and is activated by CTRL+\.

**Comment by mullerch** [comment]
Same problem for me, cannot bind the § key (that is the one for the quake-style terminal).
I added the hotkey in the config file directly but nothing happen when I hit the key.

**Comment by MrAdam** [comment]
Same issue here.. the default ctr+space is used in my IDE, so I'd really like to remap to something else, but this is hard when it's not working correctly on a danish keyboard..

**Comment by Eugeny** [comment]
Hotkey settings now correctly refer to the OS layout
