### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by okonomiyaki3000** [Eugeny/terminus#166]
It's great to see that Terminus is being so actively developed and updates are coming so rapidly but it can be difficult to keep up with the latest versions. How about using something like [hazel](https://github.com/zeit/hazel) or creating a package for [chocolatey](https://chocolatey.org/)?

**Comment by princemaple** [comment]
https://github.com/Eugeny/terminus/issues/99

**Comment by compuguy** [comment]
For mac there is always [homebrew cask](https://caskroom.github.io/).

**Comment by okonomiyaki3000** [comment]
@compuguy That's nice but OSX has iTerm2. I'm not likely to switch from that. On Windows the best terminal app is conEmu. I'm pretty satisfied with it but I could imagine going to Terminus if it keeps getting better. Which is why I want to keep up with the latest versions.
