### ISSUE TITLE
Split Panels cannot be resized

### ISSUE THREAD

**Issue by TimoSta** [Eugeny/terminus#1676]
With one of the last updates, I am no longer able to resize split panels:

![terminus-no-pane-resize](https://user-images.githubusercontent.com/5621996/67401698-83a73000-f57d-11e9-8b59-77aad567299e.gif)

I tried restarting/reinstalling the app, which didn't help.

I'm running **Terminus 1.0.92** on **Windows 10 version 1803**.

**Comment by atreidesend** [comment]
also having the same on 1.0.98 on Windows 10 version 19041
