### ISSUE TITLE
GDB Debugging not inverting text color

### ISSUE THREAD

**Issue by cburj** [Eugeny/terminus#1682]
When using GDB to debug a process, the text on the highlighted line is the same color as the highlighting itself. This means it's impossible to read what is currently being highlighted. I have tried many of the included themes, but they all fail to invert the color of the text when highlighted in GDB.

I have attached a screenshot to help clarify the issue.
![Capture](https://user-images.githubusercontent.com/32635895/67467259-596a7680-f640-11e9-8aff-2c317b4bf0f4.PNG)

**Comment by Eugeny** [comment]
Duplicate of #646
