### ISSUE TITLE
Feature Request: Open new tab/panel with current working directory

### ISSUE THREAD

**Issue by boxsnake** [Eugeny/terminus#1685]
Platform: Windows
OS Version: Win 10 v1803(17134.1069)
Terminus Version: Alpha 92

Request:

When I open a new tab or a panel, it starts with `C:\Users\{USERNAME}`, which is the "Home" of user on Windows. Is it able to start a tab/panel just from where you're working? For example, when I am now in `D:\workspace`, and then open a new tab or split a new panel, it start with `D:\workspace`.

**Comment by Eugeny** [comment]
See #1703
