### ISSUE TITLE
Feature Request: Restore window/tabs with previously working directories

### ISSUE THREAD

**Issue by boxsnake** [Eugeny/terminus#1686]
Platform: Windows
OS Version: Win 10 v1803(17134.1069)
Terminus Version: Alpha 92

Request:
When I close the Terminus and reopen it, all tabs and panels will be restored. This is convinience. However, the tabs/panels start with default shell starting path (if it is not set, it will be the home path of user), is it able to restore the tabs / panels with the working directories, not just the layouts?
Thank you.

**Comment by Eugeny** [comment]
This is actually implemented, but CWD detection on Windows is hard - see #1703
