### ISSUE TITLE
Special characters like @ don't get recognized when not using US keyboard layout

### ISSUE THREAD

**Issue by neodyma** [Eugeny/terminus#17]
special characters from the letter part of the keyboard (~, €, @) don't get recognized by the shell when using the German keyboard layout, though AltGr works for other special characters which are in the number row.

**Comment by Eugeny** [comment]
@neodyma, which OS are you using?

**Comment by neodyma** [comment]
@Eugeny I am using Windows 10 with anniversary update.

**Comment by th0th** [comment]
Is there any update on this issue? I can't use terminus due to this.

**Comment by th0th** [comment]
Is there any update on this issue? I can't use terminus due to this.
