### ISSUE TITLE
Slow on startup majority of the time, laggy when in use

### ISSUE THREAD

**Issue by mknepper** [Eugeny/terminus#172]
Suggesting overall optimization with the application - seems to run slowly. Start up can lag pretty hard and general use seems to be sluggish compared to other terminal applications (Terminator, Xfce4-Terminal, Gnome-Terminal, etc).

Was this made with Electron by chance?

Anyway, just a suggestion. Would like to see this amazing app adopted more an sped up/optimized.

**Comment by sylveon** [comment]
Startup times could be reduced by letting Terminus run in the tray, which is, IMO, an acceptable solution for the overhead that involves web technologies on desktop.
