### ISSUE TITLE
Alias support and shortcut to paste common command

### ISSUE THREAD

**Issue by 3cks82** [Eugeny/terminus#1731]
I have 2 questions.

1. Can you create aliases? Like I want to create a massive alias list that i can just type say "router1" but it is executing "ssh username@router1".

2. The other question I have is does it support shortcut to paste command. Example: if I do "Ctrl+Shift+S" I want it to type the following "copy run scp://username@hostname/filename

I am just not seeing about those to things specifically. But I am probably missing it. LOL

Other than that, really liking the application. Just need to get these few things sorted. :)

**Comment by Eugeny** [comment]
Aliases are a feature of your shell, not the terminal. The second one is provided by the quick-cmds plugin, which you can install from Settings

**Comment by 3cks82** [comment]
Thank you for getting back to me. So Terminus will recognize aliases?

**Comment by Eugeny** [comment]
Once you set up aliases in your shell, they will work in any terminal app.
