### ISSUE TITLE
Not able to open a new terminal tab

### ISSUE THREAD

**Issue by Vinno97** [Eugeny/terminus#174]
Version: `1.0.0-alpha.27`
Platform: `win32 6.1.7601`

Hi,

I just downloaded Terminus on my computer and I am not able to open a new terminal tab.
All the other buttons work, except the buttons that should open a new terminal (the plus sign at the top left and the big button in the middle). 

Restarting does not help and I've never had a problem with other electron apps.

My guess is that `Terminus` cannot access `cmd.exe` for some reason?

**Comment by Eugeny** [comment]
Please open Settings, then press the DevTools button and copy whatever error messages appear on the Console tab.

**Comment by Vinno97** [comment]
It says that it `Cannot read property 'value' of null`:
```
TypeError: Cannot read property 'value' of null
    at reg.get (C:\Users\BCM\AppData\Local\terminus\app-1.0.0-alpha27\resources\builtin-plugins\terminus-terminal\d…:21690)
    at C:\Users\BCM\AppData\Local\terminus\app-1.0.0-alpha27\resources\builtin-plugins\terminus-terminal\n…:664
    at CallbacksRegistry.apply (C:\Users\BCM\AppData\Local\terminus\app-1.0.0-alpha27\resources\electron.asar\common\api\callbacks-…:48)
    at EventEmitter.<anonymous> (C:\Users\BCM\AppData\Local\terminus\app-1.0.0-alpha27\resources\electron.asar\renderer\api\remote.js:299)
    at emitThree (events.js:116)
    at EventEmitter.emit (events.js:194)
```

**Comment by Vinno97** [comment]
I have found that I can replicate this error sometimes by going to the "Terminal" tab in the settings.

It appears that `reg.get('InstallPath, ...)'` does not always return an item in the following function, even though there isn't an error:
https://github.com/Eugeny/terminus/blob/6352f22c48fd2405310f6ec4e0cffabb00a98e5e/terminus-terminal/src/shells/gitBash.ts#L25-L34

When this happens, the list with shells stays empty.

The only other thing that I could find is that my registry does not have the key `HKEY_LOCAL_MACHINE\\Software\\Cygwin\\setup`. It appears that Terminus does not care about that, but it might be worth mentioning.

**Comment by Eugeny** [comment]
So apparently `item` returned from winreg isn't reliably non-null. Now fixed.

**Comment by Vinno97** [comment]
Thanks, I'm able to open tabs now. However, I don't think that this patch really fixes the complete problem, but treats the symptoms instead. 
When I go to select my Shell after this fix, I sometimes see:
```
CMD (clink)
CMD (stock)
Powershell
Git-Bash
```
And sometimes I see:
```
CMD (clink)
CMD (stock)
Powershell
```
Other times I get completely no results

I've also tried Terminus on another PC (Windows 10). Here I also occasionally get no results, but never only partial results. 

There are no errors or warnings logged in the DevTools, apart from a deprecation notice about the use of `<template>` instead of `ng-template>`
