### ISSUE TITLE
[Feature] Instant paste

### ISSUE THREAD

**Issue by thinking-aloud** [Eugeny/terminus#1741]
right now pasting things in the terminal has an animation, which is annoying especially with lots of text.
Please add an option to make it instant.

**Comment by TylerTemp** [comment]
... And this issue is closed, damn... please re-open it, I have the same issue. I need to paste long text for work

**Comment by Eugeny** [comment]
There is no "paste animation" unless the application receiving it has disabled echo and is slowly echoing back the input itself. Please open a separate issue with as much details as possible.

**Comment by TylerTemp** [comment]
> There is no "paste animation" unless the application receiving it has disabled echo and is slowly echoing back the input itself. Please open a separate issue with as much details as possible.

Sorry, after some tests I found it's because [zsh functions](https://apple.stackexchange.com/questions/312795/zsh-paste-from-the-clipboard-a-command-takes-a-few-second-to-be-write-in-the-ter). Not related to tabby
