### ISSUE TITLE
Display issue after unplugging external monitor

### ISSUE THREAD

**Issue by louisbizouerne** [Eugeny/terminus#1746]
Every time I unplug my external screen, sone of my tabs takes the following appearance:
<img width="753" alt="Screenshot 2019-11-07 at 12 46 38" src="https://user-images.githubusercontent.com/25149909/68390322-ee02c780-015c-11ea-9918-719a264bb853.png">

Version: 1.0.92
Platform: darwin 18.7.0
Plugins: relaxed-theme

**Comment by Eugeny** [comment]
This is caused by DPI change. There's currently a "workaround" of zooming in and out (`Cmd-+` and then `Cmd-0`)
