### ISSUE TITLE
Installed plugins and now stuck in opening

### ISSUE THREAD

**Issue by dewolfs** [Eugeny/terminus#175]
I have install the three available plugins but when I try to start Terminus now, it is stuck on the opening screen.
![screenshot](https://user-images.githubusercontent.com/13407615/29087430-34bfb0e8-7c76-11e7-9c35-f7dd79a9363d.png)

**Comment by Eugeny** [comment]
Please upgrade Terminus to the latest version. I'm planning to auto-disable crashing plugins, but for now you can remove them from the `Terminus/plugins/node_modules` folder inside `~/Library/Application Support` (macOS), `%APPDATA%` (Windows) or `~/.config` (Linux)

**Comment by Eugeny** [comment]
Plugins will not crash the whole app anymore now.
