### ISSUE TITLE
terminus-terminal on Arch Linux (AUR)

### ISSUE THREAD

**Issue by flaketill** [Eugeny/terminus#176]
terminus-terminal

https://aur.archlinux.org/packages/terminus-terminal/

Agregar en el PKGBUILD

makedepends=('git' 'npm' 'yarn' 'unp')

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=terminus-terminal

**Comment by SolarAquarion** [comment]
I updated it and removed unp

**Comment by SolarAquarion** [comment]
@Eugeny you can close this

**Comment by ShayBox** [comment]
This isn't being updated regularly, it should be updated for every tagged release

**Comment by volkflo** [comment]
Is there any progress on that also with the renaming? :)
Would be cool to have an updated AUR package on a regular base :)

**Comment by Eugeny** [comment]
@SolarAquarion is there anything I can do to allow AUR to update the package automatically? I'm not familiar with Arch.

**Comment by SolarAquarion** [comment]
I keep on getting sidetracked, and I plan to create a new package, and do a
rename.  I can add you as a co-maintainer once I do the rename
