### ISSUE TITLE
Weird rendering for lines with underscores in them

### ISSUE THREAD

**Issue by sburkett** [Eugeny/terminus#1765]
Running 1.0.92. See images below:

*** Frontend: hterm
![image](https://user-images.githubusercontent.com/2219483/68777385-90a8c380-05ff-11ea-8ea6-9719d4629431.png)

*** Frontend: xterm
![image](https://user-images.githubusercontent.com/2219483/68777650-01e87680-0600-11ea-89d7-f7748114f4c2.png)

Only seems to happen with colorized under `vim`. Using `vi` it looks fine.

**Comment by Eugeny** [comment]
Does xterm's rendering look OK to you? Hterm is known for lots of issues such as these, which is xterm is the default renderer in Terminus.
