### ISSUE TITLE
SSH password for private key file 

### ISSUE THREAD

**Issue by benediktschoeffmann** [Eugeny/terminus#1788]
Hi, when i add SSH connection and add my private (password-protected) Key-File, there is no option to enter a password for the key file.

So when i open this connection, i get 

Using user's default private key: H:\.ssh\id_rsa
Loading private key from H:\.ssh\id_rsa
Cannot parse privateKey: Encrypted private OpenSSH key detected, but no passphrase given

I like the Terminus but it's basically unusable for me if this does not work.

Kind regards, 
Ben

**Comment by Onepamopa** [comment]
Just tested - confirm there is no password prompt for password-protected private keys.
Also - it would be great if the password for keys can be saved and auto-added.
