### ISSUE TITLE
Terminate SSH session on tab close

### ISSUE THREAD

**Issue by Charburner** [Eugeny/terminus#1789]
When a SSH connection is closed by closing the tab, the actual SSH session won't be terminated on the server. I would prefer a PuTTY like behaviour: There is no difference between typing "exit" in the terminal or closing the window via the X button.

What do you think?

**Comment by Onepamopa** [comment]
I agree, closing SSH should close the session. There is no point in keeping an active SSH session if the tab is closed.

**Comment by Eugeny** [comment]
Duplicate of #1784
