### ISSUE TITLE
I can't select  shell -> profile, plz see my gif

### ISSUE THREAD

**Issue by RumRaisins** [Eugeny/terminus#1820]
Version: 1.0.95
Platform: win32 10.0.18362
Plugins: none

**Comment by RumRaisins** [comment]
![noexist](https://user-images.githubusercontent.com/23291220/69618299-a3e27700-1074-11ea-8ef5-2f31d7d6b71d.gif)

**Comment by Eugeny** [comment]
Duplicate of #1822
