### ISSUE TITLE
Change the color of the command line

### ISSUE THREAD

**Issue by LuhengStat** [Eugeny/terminus#1823]
Dear,
I found the terminus is a better replacement of powershell of windows. I am wondering 
does there exists some way to change the command line color. Such as the snipaste figure bleow.
Thanks. Best

![Snipaste_2019-11-26_23-23-53](https://user-images.githubusercontent.com/30485426/69647080-d6579880-10a3-11ea-8fb1-dad2a341a5c0.png)

**Comment by Eugeny** [comment]
This doesn't depend on a specific terminal app. There are lots of various PS prompt configs, one of the more popular is Powerline: https://github.com/Jaykul/PowerLine
