### ISSUE TITLE
[OSX] input of "ALT+key" special characters not possible

### ISSUE THREAD

**Issue by heinerlesaar** [Eugeny/terminus#183]
On 1.0.0-alpha.28.168, 

special characters based on ALT+key don´t work on the OSX version of Terminus.
This makes using "@" or all kinds of brackets on german (and presumably other) keyboard layouts impossible.

**Comment by ElephantRose** [comment]
Same issue on Windows7 + french keyboard.
Might be an issue with the default hotkeys to switch between tabs ?

**Comment by Eugeny** [comment]
@ElephantRose could you please retry it with the latest build (Alpha 29)? Thanks.

**Comment by Eugeny** [comment]
Ref #316
