### ISSUE TITLE
Terminus on Windows tries to unistall itself every time I close it

### ISSUE THREAD

**Issue by floatingpurr** [Eugeny/terminus#1831]
Hello. I'm using Terminus on Windows 10. Every time I close it, I'm asked by Windows' user account control if I want to allow the app to make changes to my system. If I press 'Yes', Terminus is removed. It happens all the times. How can I avoid this?

**Comment by Havoc85** [comment]
I think I had the same issue. Yesterday (or more: since around a month) it worked the whole time. Today, terminus is just gone. Empty link on my desktop...

**Comment by floatingpurr** [comment]
Same behavior here
