### ISSUE TITLE
Unable to start a SSH session with no password

### ISSUE THREAD

**Issue by oreaird** [Eugeny/terminus#1832]
I am a programmer for Crestron, and by default they set the SSH credentials with no password, it's not "anonymous" its simply blank. 

When I use PowerShell or other terminals it works, but if I try with terminus I get 
".........................................Timed out while waiting for handshake"

**Comment by Onepamopa** [comment]
Same... , also with "keyboard-interactive" login - unable to use the saved password, just outputs dots like crazy.

**Comment by mhh12121** [comment]
@oreaird @Onepamopa I also met the same problem! But it seems that the latest version support it. Just try press **Esc** when seeing the poping text for entering password, it works perfectly to me.
