### ISSUE TITLE
Transparency not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by jorgegarro** [Eugeny/terminus#1833]
The transparency is not working on a fresh installation of Ubuntu 18.04. I set the parameter restart Terminus, but nothing changes:

Linux chorch 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nitishingde** [comment]
I am also facing the same issue, any updates on this bug?

**Comment by Eugeny** [comment]
Duplicate of #832
