### ISSUE TITLE
Zooming with CTRL+Mouse wheel up/down zooms unintuitively

### ISSUE THREAD

**Issue by svenluijten** [Eugeny/terminus#184]
I expect the font size in _increase_ when I scroll _up_, but instead it _decreases_ (on Windows, using Git Bash). Related to #24?

**Comment by jaques-sam** [comment]
Not working for me on Windows10 😟

**Comment by CompeyDev** [comment]
Same here, doesn't seem to work on Windows 11 either... Any updates?

**Comment by juanpide** [comment]
You can configure it in the settings.
If you are using a non-English layout the defaults are not what we expect. Just change them.
