### ISSUE TITLE
垃圾小白问一句ssh自动断开应该怎么设置？

### ISSUE THREAD

**Issue by Anemone0** [Eugeny/terminus#1844]
如题如题
没有命令在运行的时候过一会就会断开

**Comment by CyrilTaylor** [comment]
set keep alive in advanced option of ssh.

**Comment by Anemone0** [comment]
能告诉我一下设置的路径吗？我找不到你说的那个

**Comment by CyrilTaylor** [comment]
选中一个ssh的配置，然后再高级设置里设置保活

![image](https://user-images.githubusercontent.com/12631466/71461746-df936c80-27eb-11ea-8ba9-4d357dabd56c.png)

**Comment by chk141** [comment]
Settings -> SSH Test -> ADVANCED -> Keep Alive Interval(Milllisenconds) = 0
