### ISSUE TITLE
Terminal hides permanently when using "toggle terminal window"

### ISSUE THREAD

**Issue by svenluijten** [Eugeny/terminus#185]
When I use <kbd>CTRL</kbd>+<kbd>space</kbd> to hide the terminal (when active), it hides the window as expected. However, using the same key combination again doesn't bring it back, even though the process is still active (as seen in my Task Manager).

On Windows 10, using Git Bash shell.

**Comment by Eugeny** [comment]
Is there any other app on your system that might be swallowing this combo? Please also try setting a different hotkey and see whether it makes a difference

**Comment by joting** [comment]
I have this issue too on Windows 10.  It seems not so much that there is a keystroke conflict, but that the application is still in the foreground when the window is hidden and the keystroke has no effect unless you bring another application into the foreground i.e. click on something else first.  Ideally on hide, the next application should be brought to the foreground; I believe this is how hyper.js works with it's summon extension.

**Comment by normallywho** [comment]
I have a similar issue on Windows 7. I press CTRL-Space and Terminus goes away (as I'd expect), but it also is removed from the taskbar. Pressing CTRL-Space does nothing. I don't see it in the ALT-Tab application selector and it does not show up in the Applications list in Windows Task Manager. However, in the Windows process list Terminus is still active. If I select Terminus in the process list and then press CTRL-Space again, the application comes back.

**Comment by thedonquixotic** [comment]
I'm also having this same problem. 

One weird wrinkle to add: If I hit alt-tab and cycle through the windows but land back on the app I was using (in this case Chrome) and then hit ctrl space, it opens, and I can then also close. BUT then it won't open again. 

Also I had trouble finding documentation for what the global hotkey was, and I also don't see anything in the settings for the hotkeys to change this hotkey. 

I'm on Win 10

**Comment by thedonquixotic** [comment]
Hey just wanted to add, after some experimentation I've realized that the hide and pull up hotkey works fine, as long as a window is in focus. If I pull up the terminal, and then hide it, nothing is in focus and hitting the hotkey again won't work. But if I pull it up, hide it, and then click on a window or something, putting that window in focus, it will work. No clue why that is.

**Comment by bramvbilsen** [comment]
This is actually a really annoying issue! I have Terminus open almost all the time when I am writting code in VS Code. Now, the shortcut for autocomplete suggestions for VS Code is `ctrl space`, but whenever Terminus is open, it overwrites the VS Code shortcut and shows the Terminus terminal instead.

**Comment by Eugeny** [comment]
Thanks @jcklpe - finally nailed it

**Comment by apurbajnu** [comment]
Is there any solution of @jcklpe  issue. I am also facing the same issue. I don't know even how to reinstall. Can't see on Control panel.

**Comment by AntonioRedondo** [comment]
Hello @Eugeny,

It seems your commit https://github.com/Eugeny/terminus/commit/dc864781e4b5627126e8b533c903710ea17f9a61 doesn't solve the problem. Tested on Windows 10 1809 and macOS 10.15 with Terminus 1.0.102, as described by @jcklpe, the toggle window terminal hotkey will only work if the window has been hidden with the hotkey but not if the window remains visible but in the background.

Do you think this can be addressed anytime soon? Terminus has become my favourite terminal. But this hotkey behaviour really annoys me as I use the toggle hotkey constantly to bring the window to the foreground.

**Comment by Eugeny** [comment]
Added a possible fix - please check!

**Comment by AntonioRedondo** [comment]
That was quick! Can you make a release so that I can check changes?

**Comment by Eugeny** [comment]
It will appear on the nightly builds page soon https://ci.appveyor.com/project/Eugeny/terminus/build/artifacts

**Comment by AntonioRedondo** [comment]
I downloaded the artifact build and the toggle functionality works always no mater the app has been already hidden with the hotkey or not. Great job! 👍👍👍
