### ISSUE TITLE
xterm (WebGL) tmux missing text in green status bar

### ISSUE THREAD

**Issue by fastest963** [Eugeny/terminus#1851]
I wasn't sure if this was an xterm.js bug or a terminus bug. When using tmux (in WSL) and xterm (WebGL) I don't see any text in the tmux status bar but if I switch back to normal xterm I do.

xterm:
![image](https://user-images.githubusercontent.com/112555/70080927-7ac26900-15d5-11ea-9179-1e7c3747ce5f.png)

xterm (WebGL):
![image](https://user-images.githubusercontent.com/112555/70080935-7f871d00-15d5-11ea-8325-4ea50041c6e1.png)

**Comment by Eugeny** [comment]
Is the text visible with the non-webgl xterm frontend?

**Comment by fastest963** [comment]
Yeah, the top screenshot in my bug is with non-webgl xterm and the bottom is the new webgl xterm. The top screenshot has the black text on top of the green bar but in the bottom screenshot there is no text.

**Comment by fastest963** [comment]
This is still happening even with Alpha 102. Is there anything I can provide to help debug or diagnose?

**Comment by Eugeny** [comment]
Tracking in #2210
