### ISSUE TITLE
zsh

### ISSUE THREAD

**Issue by Ampy** [Eugeny/terminus#1855]
v1.0.92
![image](https://user-images.githubusercontent.com/909538/70197029-8c2a8300-1745-11ea-9f51-e9f40a711290.png)

v1.0.97
![image](https://user-images.githubusercontent.com/909538/70197184-f8a58200-1745-11ea-8a3a-a394eab654a6.png)

it's a bug.
zsh

**Comment by ingvevs** [comment]
Same here. Zsh autosuggestions stopped working on 1.0.97.

**Comment by anthony-doutre-cko** [comment]
Same here the plugin [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions) stopped working in Terminus while running fime on iTerm.
In Terminus I only see the first letter of the suggestion just like the screenshot above.
It only displys the suggested character that is below the cursor.

**Comment by Eugeny** [comment]
Could you please use a light theme to confirm that it's not a case of dark text on dark bg? zsh-autosuggestions works for me.
