### ISSUE TITLE
Ctrl-A doesn't go to the head of line

### ISSUE THREAD

**Issue by tlyalex** [Eugeny/terminus#186]
Awesome product, just want to let you know.
One questions:
Does ctrl-a go to the head of line? ctrl-e works as expected to go to the end of line.

also in https://github.com/Eugeny/terminus/blob/2377a8c522e07ad0e31d7f29137cf0cea6c3f64e/clink/clink_inputrc_base#L12 
Looks like there is a short cut for go to the head of line. Not sure if this is something related.

Thanks.

**Comment by tlyalex** [comment]
ubuntu 16.04 with alpha 28 terminus

**Comment by Eugeny** [comment]
Ctrl-A is used as a part of multiple shortcuts. You can remove them under Settings > Hotkeys, and after that Ctrl-A should be passed to the shell.

**Comment by ponsfrilus** [comment]
@tlyalex <kbd>ctrl</kbd>+<kbd>a</kbd> is the default [GNU Screen](https://www.gnu.org/software/screen/) keybinding: e.g. <kbd>ctrl</kbd>+<kbd>a</kbd> <kbd>ctrl</kbd>+<kbd>a</kbd> will "Toggle to the window displayed previously. If this window does no longer exist, `other` has the same effect as `next`" – see full explanation on https://www.gnu.org/software/screen/manual/html_node/Default-Key-Bindings.html.

If you want to use the emacs key binding (i.e. <kbd>ctrl</kbd>+<kbd>e</kbd> end-of-line) you can also edit your `~/.screenrc` (https://apple.stackexchange.com/questions/12444/how-do-i-change-gnu-screens-meta-key-to-cmd-a) as long as your are in a screen session (check with `echo $TERM`).

Hope this helps.

**Comment by Eugeny** [comment]
@ponsfrilus worth noting that this only applies if he's running another Screen inside Terminus. In any case, it wouldn't have anything to do with terminal directly.

**Comment by Eugeny** [comment]
Confirmed that removing the Ctrl-A hotkeys from settings leads to Ctrl-A being forwarded to the shell.
