### ISSUE TITLE
multiple windows on MacOS

### ISSUE THREAD

**Issue by davidedelvento** [Eugeny/terminus#1870]
I just switched to MacOS from Linux and I was extremely surprised to find the default terminal so lacking compared to Linux options. So please be patient with me because I am a MacOS and terminus newbie. In fact, I tried a few terminal alternatives, and the only one that satisfies me is terminus ;-)

Yet, in terminus I cannot figure out a way to open a second (or third, fourth, n-th) window on MacOS. I need this desperately for various reasons, e.g. multiple desktops which I use for separate projects. From various github issues, it seems that CTRL-SHIFT-N should do that, but it does nothing on Mac. Thinking a CTRL-vs-CMD swap as with many other things (e.g. copy-paste) I tried also CMD-SHIFT-N but that does nothing either. The menus do not have any mention of "new window" (but menus do not have any mention of "new tab" either, yet new tab is supported with the "+" symbol next to the list of existing tabs, so there may be a button hiding somewhere in plain sight). I did not find anything that seemed relevant in the settings either.

Such a long introduction for the actual issue: are the multiple windows a feature supported on MacOS, and if so how? If not, will it be soon? I am running v1.0.97

**Comment by Eugeny** [comment]
On macOS, it's ⌘-N, as seen here:

![image](https://user-images.githubusercontent.com/161476/70461979-35f96f00-1aba-11ea-86f7-15d5541ad1a9.png)

**Comment by davidedelvento** [comment]
@Eugeny thanks for the super fast answer, however you closed the issue too soon.

On my machine, a MacOS v10.14.6 the ⌘-N (aka CMD-N) shortcut opens a new tab. I tried with and without SHIFT, since N might mean uppercase, i.e. with shift. Without SHIFT it opens a new tab. With it it does nothing. I also checked in the hotkey menu to make sure it did inadvertently got changed, and it is not. It's identical to your screenshot. Note that this is a fresh install of terminus with vanilla defaults (I'm still learning about it).

**Comment by Eugeny** [comment]
Just to be clear - you were trying this while a terminal was focused? Because hotkeys are disabled when any input elements are focused other than the terminal itself - e.g. the search field in Hotkeys

**Comment by davidedelvento** [comment]
@Eugeny thanks for reopening this. Yes, the terminal is focused, if I type it writes to the shell. In fact the hotkeys are enabled since a new TAB get created (instead of a new WINDOW). 

Just to make sure there wasn't other trivial things interfering with it, I asked another person to test this on their machine, and they got the very same result. Both of us dug into the hotkeys for new TAB and in fact both CMD-T and CMD-N are listed. Removing the latter from the hotkeys for new TAB (and double checking it stays there for new-window) makes the CMD-N hotkey work for me (hooray for new window!), but do nothing (and actually hang the app) for him. So I guess the bug here is to remove the double hotkey for new-tab, while we investigate if the hang was coincidental or reproducible (and what version of terminus and MacOS he's running) and report back to you on that regard.

Thanks!

**Comment by davidedelvento** [comment]
We have not been able to reproduce that crash, and the new-window is working for the other person too, albeit it is fairly slow to appear. So I guess this turned out simpler than I though. I am fine manually removing that hotkey for myself, but I suppose you want to do it globally for everybody in the next release.

**Comment by hangingman** [comment]
⌘-N (aka CMD-N) shortcut is working fine on Tabby v1.0.168

**Comment by roberthoegerl** [comment]
⌘-N (aka CMD-N) works fine to OPEN a new window. But how does one close a window (not the entire application)?

It appears that after the last tab inside a window is closed (and the tabby home screen is shown), ⌘-W stops having any effect. At the same time ⌘-Q closes ALL windows belonging to tabby, hence, also not producing the desired outcome either.

Is there a way to close a window using a shortcut? It appears the optimal behaviour would be: while tabs are open, ⌘-W should close tabs _(already does)_, and once the last tab inside a window is closed, ⌘-W should then close the window _(currently not the case)_.
