### ISSUE TITLE
Shell doesn't accept any keyboard inputs.

### ISSUE THREAD

**Issue by ajayr97** [Eugeny/terminus#1878]
Version: 1.0.97
Platform: win32 10.0.17134
Plugins: none

Nothing I key in gets entered in the shell.

**Comment by ajayr97** [comment]
Issue resolved after defaulting settings.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs
