### ISSUE TITLE
Screen breaks terminal colors

### ISSUE THREAD

**Issue by Maathias** [Eugeny/terminus#1887]
When switching to a screen session, colors break in all tabs until restart

Version: 1.0.75
Platform: win32 10.0.18363
Plugins: none

**Comment by Eugeny** [comment]
Please upgrade to the latest nightly and provide a dump of your terminal state as described here: https://github.com/Eugeny/terminus/wiki/Posting-terminal-state

**Comment by Eugeny** [comment]
A screenshot would help too
