### ISSUE TITLE
Useless padding

### ISSUE THREAD

**Issue by edouard-lopez** [Eugeny/terminus#189]
Hi, thanks for the project it's really nice and feel super fast.

Whatever theme I use (_tomorrow_, _base16_) I got a padding all around my content. You can see it top and left of my prompt `❯`:

![selection_086](https://user-images.githubusercontent.com/1212392/29962548-e725c7e6-8f03-11e7-8423-0ab057fac5cf.png)

Is there a way to remove it?

**Comment by Eugeny** [comment]
It's coming from the theme. But you can override the padding with the following CSS:

```css
terminaltab > div { margin: 0 !important; }
```

Just paste that under `Custom CSS` in the settings.

**Comment by Chr1s-T** [comment]
> It's coming from the app theme. But you can override the padding with the following CSS:
> 
> ```css
> terminaltab > div { margin: 0 !important; }
> ```
> 
> Just paste that under `Custom CSS` in the settings.
By doing like this? It looks like doesn't work.

![TIM截图20190703091437](https://user-images.githubusercontent.com/23159278/60556252-00b25d80-9d73-11e9-8313-3110ed3ad413.png)

**Comment by Nyxtorm** [comment]
Hello,

In case it's still useful, I've removed these margins as follows in the last version:

```css
tab-body div.content {
    margin: 0 !important;
}
```
