### ISSUE TITLE
Terminus Continues To Overlay When Clicked Off

### ISSUE THREAD

**Issue by seivad** [Eugeny/terminus#1894]
Version: 1.0.92
Platform: win32 10.0.18362
Plugins: none

Hey guys the Terminus window will stay above all other windows when I click off. I have a setup where I press Alt + Space to open it which takes up the upper portion of my screen. Then when I click off to say Chrome or Sublime it still stays on top which is quite annoying. Only way to hide it again is to press Alt + Space. Also when it is setup like this, Terminus doesn't show in the Windows Dock as an open app, it looks like it is closed so when you click the icon in the dock, it opens another session of the app.

**Comment by pdc4444** [comment]
Version: 1.0.99-nightly.0
Platform: Windows 10 Version 1903
Plugins: None

This is a problem for me too. No matter what I do, the terminus window is always on top of my other windows and does not behave like any other window! I tried switching the Window frame to Native and that did not change it's behavior.
