### ISSUE TITLE
How to use my tmux.conf?

### ISSUE THREAD

**Issue by edouard-lopez** [Eugeny/terminus#190]
Again thanks for the tools, pretty neat!

### Tmux config

Prior to using `terminus`, I was using `konsole`/`yakuake` with my [tmux configuration](https://github.com/edouard-lopez/dotfiles/blob/master/.tmux.conf).

Now, I'm using the session persistence feature with tmux. However, neither the default shortcuts nor mine seems to work and my configuration seem to be totally ignored.

I'm used to work in split mode (2 vertical panes) and `tmux` tabs.

### Tmux session

On `konsole`/`yakuake`/`gnome terminal`/`TTY` I can see my tmux session

    ❯ tmux ls
    0: 1 windows (created Fri Sep  1 10:01:46 2017) [237x69] (attached)

But when in `terminus` I don't see it but something completely different

    ❯ tmux ls
    1504253032460: 1 windows (created Fri Sep  1 10:03:52 2017) [262x72] (attached)
    control: 1 windows (created Fri Sep  1 10:01:45 2017) [80x24] (attached)

### Question

How do I take my config into account?

**Comment by Eugeny** [comment]
Terminus doesn't expect you to manipulate the "persistence" TMux directly. If you want to use your own tmux, I suggest switching the persistence to Screen or even switching it off completely, since your own Tmux is taking care of that already.

**Comment by edouard-lopez** [comment]
Config is read, but shortcuts still not available, I guess they are swallowed by terminus and never reach tmux.

**Comment by Eugeny** [comment]
Since your config uses Ctrl-A, you need to first unbind it in Terminus' own keyboard settings, otherwise it'll get swallowed :)
