### ISSUE TITLE
Colors in midnight commander fix request 

### ISSUE THREAD

**Issue by jonyrock-back** [Eugeny/terminus#1909]
Hey, this is how I see colors when I am trying to copy:

![image](https://user-images.githubusercontent.com/58978975/71217379-ada37700-22ce-11ea-8358-658eb8571f99.png)

I believe that there should be a different color for text in the blue inputs

**Comment by jonyrock-back** [comment]
I am using `mc` command on wsl/ubuntu

**Comment by Eugeny** [comment]
Please provide a dump of your terminal state as described here: https://github.com/Eugeny/terminus/wiki/Posting-terminal-state

**Comment by Eugeny** [comment]
Tracking in #2210
