### ISSUE TITLE
Each time when create new ssh connection RAM usage rise up

### ISSUE THREAD

**Issue by WaskiWaski** [Eugeny/terminus#1910]
Hi,
I realised that, each time when i close SSH connection and open it again, RAM usage rise up.
At first run it is aproximately 950MB RAM, which in my opinion is really hugh value. 
But after couple times of close/open connection ram usage rise even to 2600MB RAM (pic rel, it could be higher, i guess) 
![Screenshot - 12_20_2019 , 12_51_01 AM](https://user-images.githubusercontent.com/15268965/71218865-7085b780-22c3-11ea-8969-d3c956ff613d.png)

After few minutes of idle it down to 1400MB, but later rise one more time to 2400MB.
In my config i use compact theme with fluent background.
Extra addons: clicable links and scrollbar.
My system is Windows Version 10.0.18362 Build 18362
Terminus 1.0.97

**Comment by Eugeny** [comment]
This should be fixed in the nightly build now.
