### ISSUE TITLE
Can't select Shell in settings

### ISSUE THREAD

**Issue by avrittrohwer** [Eugeny/terminus#192]
On windows, I cannot select the default shell in the settings.  I can get around this using the shell-selector plugin, however.

**Comment by Eugeny** [comment]
What happens if you select an item? Does it jump back to previous selection?
Please also grab the logs from Settings > Dev tools > Console.

**Comment by avrittrohwer** [comment]
It doesn't present any options to select. 

Here's the log: 
[log.txt](https://github.com/Eugeny/terminus/files/1273277/log.txt)

**Comment by Eugeny** [comment]
please try removing the \Users\avritt\.hyper_plugins\node_modules\.bin folder. It shouldn't affect your Hyper plugins.

**Comment by avrittrohwer** [comment]
That worked.  Thank you.
