### ISSUE TITLE
dash symbol => "-" does not appear when you use powershell

### ISSUE THREAD

**Issue by lxwulf** [Eugeny/terminus#1925]
i think the problem is theme related or maybe how terminus shows powershell because dash is a parameter or a command in powershell itself 
when i typing "ls -h" as example i doesn't see "-h"

![Untitled](https://user-images.githubusercontent.com/44492381/71514180-c4813500-289d-11ea-8177-705b13891cba.png)
![Untitledw](https://user-images.githubusercontent.com/44492381/71514181-c519cb80-289d-11ea-9390-7dfbe95a0dc0.png)

**Comment by Eugeny** [comment]
Looks like your Powershell theme uses black color for flag highlighting.

**Comment by lxwulf** [comment]
Nice, thank you @Eugeny ! i changed my theme in terminus! now i see my dashes again

sry for the trouble =D
