### ISSUE TITLE
Application hangs after opening new terminal/sending command

### ISSUE THREAD

**Issue by mtaanquist** [Eugeny/terminus#193]
Version: 1.0.0-alpha.29
Platform: win32 10.0.16278

When opening a new terminal, or after sending a command, the application hangs for several seconds where the window becomes non-responsive. Clicking any part of the interface does not work. If inputting commands in the terminal window, it will "catch up" afterwards, printing what you typed.

I made a brief video of the issue, with an on-screen keyboard showing me typing, which can be seen here: https://gfycat.com/OffbeatInsistentDotterel

This is happening regardless of the type of terminal I open, both on my desktop PC and my laptop.

**Comment by mtaanquist** [comment]
Turns out this was an issue with the clickable-links plug-in. Once I disabled the plug-in, I have not problems with the application hanging since.

Close this issue if necessary.

**Comment by equinox** [comment]
Related: https://github.com/Eugeny/terminus/issues/83

**Comment by VOMAkSh** [comment]
This is a major problem. It gets freezed and has to be killed via command prompt, then only after restart it works.
