### ISSUE TITLE
Is there anyway to hide/remove the PORT buttom in the latest update?

### ISSUE THREAD

**Issue by zhouyan** [Eugeny/terminus#1932]
I understand some people may need it for port forwarding. But having it in the as port of the main terminal screen is not only an eye sore, but also affect real work. For instance, it overlaps with my Vim status line. The terminal screen shall be clean without any obstructions.

**Comment by guangmuzhu** [comment]
It's NOT an `Enhancement', it's just a bug.

There are only certain users who need this feature and no one wants it to be the button that ALWAYS stays on top.

Hey guys, look at here! My feature, my code, what a wonderful thing! Do you like it? Oh you must like it, or...Emmm, do you have any choice? ;)
