### ISSUE TITLE
System hotkey to invoke

### ISSUE THREAD

**Issue by ak1dd** [Eugeny/terminus#1944]
I'm a Guake/Tilix user and just found terminus on my Windows 10 computer.   With Guake you can quickly invoke the terminal by hitting F12 (or whatever you set) and hide it again by hitting the same.  Perhaps this is already possible but I'm not seeing it?   It would also be great if the terminal could hide itself if it loses focus.

**Comment by Eugeny** [comment]
You can open/close terminus guake-style with the "toggle window" hotkey (ctrl-space by default), but it doesn't close itself on unfocus yet
