### ISSUE TITLE
some issues in terminus 1.0.98(alpha 98)

### ISSUE THREAD

**Issue by lain-github** [Eugeny/terminus#1948]
1. When using telnet, the cursor moves to the left without showing the exact cursor position in real time .
2. After closing terminus, opening it again will keep the number of previous tabs, and open a new tab. Can this be set, only one tab is opened each time terminus is opened.
3. Can the tab management panel set transparency? Full transparency is inconvenient.

**Comment by CyrilTaylor** [comment]
- issue 2: Settings->Terminal->Restore terminal tabs on app start->off
- issue 3: Settings->Application
    - Acrylic background->on
    - Background type->blur
    - Transparency->minimum
