### ISSUE TITLE
SSH to some servers no longer working after installing Terminus 1.0.98

### ISSUE THREAD

**Issue by Beatle777** [Eugeny/terminus#1957]
I installed the latest Terminus release and some SSH connections I previously had are no longer working throwing a handshake error :

Connecting to fsehlp04.sabre.com..
SHA256 fingerprint: 061262413f6bbd41eac460fe88816cb42d00ff2be56666d26cf04527adcbf0e6
Handshake failed: signature verification failed

Please help. I don't want to go back to using Putty.
Thanks

**Comment by CyrilTaylor** [comment]
You can try to delete `~/.ssh/known_hosts` in your guest computer, and reconnect it again.

**Comment by lxwulf** [comment]
for me the normal way is working also with the new version but not when i use key file then it says everytime every authentication method is failed 
```
Connecting to 192.168.1.101
Loading private key from C:\Users\LxWulf\Desktop\id_ed25519
SHA256 fingerprint: 2d4e45a8f06efb7ce6fc71aeb1407ef8e1999f0b8aba40562db83407cc1e65e6
All configured authentication methods failed
```
without keyfile i can login with a normal user

**Comment by CyrilTaylor** [comment]
Did you copy your public key `id_ed25519.pub` to your host `/home/${USER}/.ssh/authorized_keys`, and enable PubkeyAuthentication?

Uncommented follow options in `/etc/ssh/sshd_config`

```ssh_config
PubkeyAuthentication yes
AuthorizedKeysFile     .ssh/authorized_keys .ssh/authorized_keys2
```

**Comment by lxwulf** [comment]
yes `PubkeyAuthentication yes` is uncommented
yes i uncomment `AuthorizedKeysFile     .ssh/authorized_keys .ssh/authorized_keys2`

and yes i forgot to copy over the key to `authorized_keys` file 🙈🙊
i seat the whole day on this problem and with the time you forgot what you already did and which not 😅

anyway thank you very much for help =D looking forward to manage this with terminus

**Comment by Beatle777** [comment]
> You can try to delete `~/.ssh/known_hosts` in your guest computer, and reconnect it again.

Thanks for your response. I'm running Terminus on Windows 10. Do you know where is it caching the Known Hosts ?

**Comment by CyrilTaylor** [comment]
> > You can try to delete `~/.ssh/known_hosts` in your guest computer, and reconnect it again.
> 
> Thanks for your response. I'm running Terminus on Windows 10. Do you know where is it caching the Known Hosts ?

For windows, `win + R` to open run and input `%USERPROFILE%/.ssh`
