### ISSUE TITLE
Sometimes I can't see the text anymore

### ISSUE THREAD

**Issue by is-sam** [Eugeny/terminus#1958]
Version: 1.0.98
Platform: win32 10.0.18362
Plugins: none

Hello,

Sometimes when I leave the app running on background and open it I can't see any text and I have to spam Enter until I see it again.

**Comment by LordBoBCUP** [comment]
Version: 1.0.98
Platform: Windows 1903
Plugins: None

Confirm I have the same issue. Long standing windows turn to blank and for me even spamming enter doesn't bring it back however you can sometimes see the cursor flicker further down the screen.

**Comment by is-sam** [comment]
![image](https://user-images.githubusercontent.com/15368990/72679608-230e8d00-3ab1-11ea-8f53-ed1c1dfc4a30.png)
