### ISSUE TITLE
Can not install on win32 platform

### ISSUE THREAD

**Issue by lurdan** [Eugeny/terminus#196]
I'm trying to install on 32 bit windows 2-in-1 tablet, but
released alpha installers fail with complaining that "this binary (Terminus.exe) is not for this platform".

I guess windows installer is meant for 64 bit only, doesn't it?
I'm glad if it detects the platform or you add another one dedicated for win32 platform.

**Comment by Eugeny** [comment]
Altough Terminus can be built for 32-bit Windows, I'm not making 32-bit builds.
For those interested, it can be bulit by setting up the environment (https://github.com/Eugeny/terminus/blob/master/HACKING.md) and running `node scripts\build-windows.js`
