### ISSUE TITLE
Settings sync

### ISSUE THREAD

**Issue by opensorceror** [Eugeny/terminus#1972]
I'm wondering if there is a way to periodically, automatically sync the Terminus settings file to, say, GitHub. I'd like to try to ensure that all my saved SSH connections, as well as custom Terminus settings, are always automatically backed up.

VSCode has a [plugin](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) to do this; I'm wondering if Terminus does too.

**Comment by Eugeny** [comment]
Terminus doesn't have an existing plugin for it, but the config file is just a plain YAML and one could come up with a simple script to push it around :)
