### ISSUE TITLE
Ctrl-Space closes Terminus in any shell (ssh, cmd, etc.) on Windows 10

### ISSUE THREAD

**Issue by rfie16** [Eugeny/terminus#1976]
When using emacs or jed Ctrl-Space is used to mark the beginning of a text block. It's also a good way to kill Terminus on Windows 10 without a "do you want to close" dialogue. The auto-save feature of emacs or jed makes this a little less painful.

How to reproduce: Open Terminus on Windows 10, open a shell (cmd is enough), press Ctrl-space

**Comment by Eugeny** [comment]
It doesn't close it, it's the default "toggle window" shortcut, change it under settings.
