### ISSUE TITLE
home and end key does not work

### ISSUE THREAD

**Issue by yqcy** [Eugeny/terminus#1988]
Version: 1.0.98
Platform: win32 10.0.18362
Plugins: none

I create a ssh connection by **[Settings]->[SSH]**, when i open it through **[Quick connect]**,  "home" and "end" key cannot work, when i open a new tab through **[New terminal]**, it work correctly.

**Comment by lxwulf** [comment]
can approve that it also not work when you are in saved ssh connection you click on one of your save connection and ex. starting vim and do things **page up** and **down** works but not **home** or **end**

**Comment by hcharbonnier** [comment]
Same here.

**Comment by chemnic** [comment]
Same her in version 1.0.101.
I use HOME and END a lot so this is a very annoying for me.

**Comment by joaoreis13** [comment]
Same here, version 1.0.101 on Windows.

**Comment by hcharbonnier** [comment]
FYI, as a temporary workaround, in a linux shell you cant use CTRL+A and CTRL+E.
In Vim you can press to times ^ or $ key.

**Comment by justinvson-pd** [comment]
This still doesn't work for me
