### ISSUE TITLE
Not plugins - Not Working

### ISSUE THREAD

**Issue by guillermoarb** [Eugeny/terminus#1990]
Version: 1.0.98
Platform: win32 10.0.17763
Plugins: none

So if you disable all pugins, it stops working. Now I can not access to config to use it again :(

**Comment by Eugeny** [comment]
As a workaround, you can clear the plugin blacklist directly in the config file: https://github.com/Eugeny/terminus/wiki/Config-file

**Comment by guillermoarb** [comment]
Yes, I did that. Thank you
