### ISSUE TITLE
The password was strangely retained if remove the connection

### ISSUE THREAD

**Issue by gaoming714** [Eugeny/terminus#1999]
Steps:
1.  store a key password for a connection
2.  delete the connection (do not delete the saved password)
3.  create the same connection without the password.
4.  unfortunately, the password shows for this connection if I reopen the connection.

the password is stored in a wrong place, and I need to delete it manually.

Version: 1.0.98
Platform: win32 10.0.17763
Plugins: none

**Comment by Eugeny** [comment]
Terminus stores SSH passwords in the OS keychain, but doesn't automatically remove them when the connection is removed
