### ISSUE TITLE
Function keys are all wrong.

### ISSUE THREAD

**Issue by V3XATI0N** [Eugeny/terminus#20]
For example -- in a byobu shell, F2/F3/F4 etc. do not work as expected (or at all, really). Is this a bug or a keyboard mapping issue?

**Comment by Eugeny** [comment]
The F-key behaviour you describe is specific to Byobu. The F-keys are forwarded to the apps by default in Terminus. You can, however, map them in the same way under Settings>Hotkeys.

**Comment by superm1** [comment]
I'm a little confused; I encounter the same behavior in terminus 1.0.71 on Windows 10.
I use F2/F3 in `byobu` in `wsl` with `cmder` no problem, but in Terminus they just print `~`.  I double checked and nothing is set for those keys in settings->hotkeys
