### ISSUE TITLE
Feature request. Move a tab to another location

### ISSUE THREAD

**Issue by larssb** [Eugeny/terminus#2007]
I would love it to be possible to move a tab in **Terminus** to another location in the tab bar. 

TRIED:
- searched settings, couldn't find any
- searched the issues here on GitHub, did not find any matching

Is this forthcoming or already possible and I just didn't see it.

Thank you.

**Comment by Eugeny** [comment]
You can drag tabs around by their index indicators.

**Comment by larssb** [comment]
Dang! That was easy. I tried dragging and whatnot all over a tab. Except by their index indicator. Love it. Thank you a million.
