### ISSUE TITLE
Nothing to work

### ISSUE THREAD

**Issue by JasonSubMara** [Eugeny/terminus#2008]
[
![WeChat截圖_20200116094448](https://user-images.githubusercontent.com/30927318/72486237-3ddcc980-3845-11ea-940e-cf671cb80115.png)
](url)

**Comment by tommymcgahee** [comment]
Getting this as well with every shell.

**Comment by wtiandong** [comment]
nothing work...

**Comment by wtiandong** [comment]
hi @JasonSubMara,  I tried v1.0.98 and it worked...

**Comment by volkflo** [comment]
Same for me

**Comment by Eugeny** [comment]
Fixed in the nightly build
