### ISSUE TITLE
Make RMB behaviour configurable

### ISSUE THREAD

**Issue by Simsch** [Eugeny/terminus#201]
Would it be possible to copy-paste via right mouse click instead of having this little popup windows (right click?). In other consoles it works with selecting some text and right click it in order to paste it to the cursors position.

**Comment by princemaple** [comment]
I think this popup is better. It allows more possibilities.

**Comment by Simsch** [comment]
The problem with the popup is that (at least on my windows 10 machine) it is never near the mouse cursor. The possibilities are rather rare. You can only open another terminal (in addition) which I can do with a shortcut or pressing the plus sign on top in the tab bar. Anyway, most of the time someone wants to copy text which was selected so the one click more into the popup is just not neccessary. The way most of the unix shells I worked with is the way I described above.

**Comment by princemaple** [comment]
Not only talking about copy and paste here. This could be extended to allow plugins to perform actions on the selected text. Plus, you could always just Ctrl+shift+c and Ctrl+shift+v.

**Comment by Razva** [comment]
I think that "copy on highlight" and "paste on right click" are *a must* as they are the norm in Windows: PowerShell, Putty etc. This is one of the biggest reason for me not using Terminus (on Windows).
