### ISSUE TITLE
cant open new terminal 1.0.99

### ISSUE THREAD

**Issue by windzhu0514** [Eugeny/terminus#2011]
[terminal] Starting profile Git-Bash {name: "Git-Bash", icon: "<svg aria-hidden="true" focusable="false" data-pre…ss stroke="none" stroke-width="1px"></path></svg>", sessionOptions: {…}, isBuiltin: true}
log.service.ts:56 [terminal] Using session options: {command: "C:\Program Files\Git\bin\bash.exe", args: Array(2), env: {…}, pauseAfterExit: undefined, cwd: undefined}
/D:/MyConfiguration/ljc43026/AppData/Local/Programs/Terminus/resources/app.asar/dist/[object%20Module]:1 GET file:///D:/MyConfiguration/ljc43026/AppData/Local/Programs/Terminus/resources/app.asar/dist/[object%20Module] net::ERR_FILE_NOT_FOUND
D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:1993 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:1993
customScheduleGlobal @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1883
ZoneDelegate.scheduleTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:410
onScheduleTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:301
ZoneDelegate.scheduleTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:404
Zone.scheduleTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:238
Zone.scheduleEventTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:264
(anonymous) @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:2054
t.addDisposableDomListener @ xterm.js:1
t.bindMouse @ xterm.js:1
t.open @ xterm.js:1
e.open @ xterm.js:1
attach @ xtermFrontend.ts:122
eval @ baseTerminalTab.component.ts:184
ZoneDelegate.invokeTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423
onInvokeTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334
ZoneDelegate.invokeTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:422
Zone.runTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:195
ZoneTask.invokeTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:498
ZoneTask.invoke @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:487
timer @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:2281
processImmediate @ internal/timers.js:439
D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:1993 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:1993
customScheduleGlobal @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1883
ZoneDelegate.scheduleTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:410
onScheduleTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:301
ZoneDelegate.scheduleTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:404
Zone.scheduleTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:238
Zone.scheduleEventTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:264
(anonymous) @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:2054
t.addDisposableDomListener @ xterm.js:1
t.bindMouse @ xterm.js:1
t.open @ xterm.js:1
e.open @ xterm.js:1
attach @ xtermFrontend.ts:122
eval @ baseTerminalTab.component.ts:184
ZoneDelegate.invokeTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423
onInvokeTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334
ZoneDelegate.invokeTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:422
Zone.runTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:195
ZoneTask.invokeTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:498
ZoneTask.invoke @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:487
timer @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:2281
processImmediate @ internal/timers.js:439
D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:1993 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:1993
customScheduleGlobal @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1883
ZoneDelegate.scheduleTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:410
onScheduleTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:301
ZoneDelegate.scheduleTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:404
Zone.scheduleTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:238
Zone.scheduleEventTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:264
(anonymous) @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:2054
t.addDisposableDomListener @ xterm.js:1
t.bindMouse @ xterm.js:1
t.open @ xterm.js:1
e.open @ xterm.js:1
attach @ xtermFrontend.ts:122
eval @ baseTerminalTab.component.ts:184
ZoneDelegate.invokeTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423
onInvokeTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334
ZoneDelegate.invokeTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:422
Zone.runTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:195
ZoneTask.invokeTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:498
ZoneTask.invoke @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:487
timer @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:2281
processImmediate @ internal/timers.js:439
log.service.ts:56 [terminalTab] Resizing to 235x51
D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:1993 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:1993
customScheduleGlobal @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1883
ZoneDelegate.scheduleTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:410
onScheduleTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:301
ZoneDelegate.scheduleTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:404
Zone.scheduleTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:238
Zone.scheduleEventTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:264
(anonymous) @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:2054
attach @ xtermFrontend.ts:143
eval @ baseTerminalTab.component.ts:184
ZoneDelegate.invokeTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423
onInvokeTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334
ZoneDelegate.invokeTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:422
Zone.runTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:195
ZoneTask.invokeTask @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:498
ZoneTask.invoke @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:487
timer @ D:\MyConfiguration\ljc43026\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:2281
processImmediate @ internal/timers.js:439
2buffer.js:459 Uncaught TypeError [ERR_INVALID_ARG_TYPE]: The "list[1]" argument must be one of type Array, Buffer, or Uint8Array. Received type string
    at Function.concat (buffer.js:459)
    at Socket.eval (bufferizedPTY.js:41)
    at Socket.emit (events.js:208)
    at addChunk (_stream_readable.js:295)
    at readableAddChunk (_stream_readable.js:272)
    at Socket.Readable.push (_stream_readable.js:210)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166)
NodeError @ internal/errors.js:194
concat @ buffer.js:459
eval @ bufferizedPTY.js:41
emit @ events.js:208
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:272
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166

**Comment by MattBianco** [comment]
Version: 1.0.99
Platform: win32 10.0.18363
Plugins: none

I've not used terminus before, so it is a fresh install. SSH connections work fine, but I can't manage to get anything in a local terminal. Just the cursor. I tried with all choices of shells in the default profiles.

**Comment by Eugeny** [comment]
Fixed in the nightly build
