### ISSUE TITLE
[Feature Request] Default path for new console

### ISSUE THREAD

**Issue by Simsch** [Eugeny/terminus#202]
It would be nice to have to have some kind of default path (folder) which will open if you open a new console (overrite the default console behavior).

**Comment by Eugeny** [comment]
Done.

**Comment by tnguyen14** [comment]
I have alpha 35 (latest version right now). Is this included in that version?

**Comment by Eugeny** [comment]
No, it's coming in the Alpha 36.

**Comment by tnguyen14** [comment]
I see it now - what should I set the value so that it would be my home folder (`/home/tri`) instead of `/mnt/c/Users/tri`? Setting it to either `~` or `/home/tri` causes the new tab to be hung.

**Comment by Eugeny** [comment]
This is set from the windows side when launching the shell - try setting it to the windows-mapped path of your home dir

**Comment by Eugeny** [comment]
E.g. C:\Users\Mark\AppData\Local\lxss\home\mark

**Comment by Simsch** [comment]
First of all - Thanks a lot for this feature!
Currently there is a bug where the path is not taken into account when a new shell is opened via the shell-selector plugin. But I am not shure to whom the bug belongs (plugin dev or main application).

**Comment by tnguyen14** [comment]
@Eugeny thanks that makes sense.

I tried the path you suggested, and it took me to a home folder of an Ubuntu I had installed before (but then subsequently uninstalled). I have since then installed the Ubuntu version on the Windows Store.

Do you know where the new home directory might be?

**Comment by tnguyen14** [comment]
According to this post https://askubuntu.com/questions/759880/where-is-the-ubuntu-file-system-root-directory-in-windows-nt-subsystem-and-vice, it would be in something like 
```C:\Users\<username>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs```

However, the permission on that for me show `000` and owned by `root`.

**Comment by tnguyen14** [comment]
Interestingly, if I set that path as above, a new tab will take me to the root directory (.i.e `/`). However, appending `\home` or `\home\<username>` does not actually take me to the home directory.
