### ISSUE TITLE
Problem with emojis and double width chars (in spaceship-prompt for example)

### ISSUE THREAD

**Issue by FlorentLM** [Eugeny/terminus#2022]
Version: 1.0.98
Platform: win32 10.0.18363
Plugins: none

Hi,
The UTF-8 characters such as emoji are fucked up (there is a question mark showing in front of them), could there be a better support for this in Terminus?
Second problem, some double width characters are also acting funny, which is exactly the problem listed [here ](https://denysdovhan.com/spaceship-prompt/docs/Troubleshooting.html#some-section-icons-overlap-each-other)on their troubleshooting page. Can the width be adjusted somehow in Terminus?

Thanks

**Comment by Eugeny** [comment]
Could you please grab the latest nightly and provide a dump of your terminal state as described here? https://github.com/Eugeny/terminus/wiki/Posting-terminal-state

**Comment by FlorentLM** [comment]
```"\r\n\u001b[93;1mflorent\u001b[97m in \u001b[96m~\u001b[97m at \u001b[92mOmicron\u001b[97m \u001b[0m\r\n\u001b[92;1m➜ \u001b[32;22mtouch\u001b[0m Dockerfile\r\n\r\n\u001b[93;1mflorent\u001b[97m in \u001b[96m~\u001b[97m at \u001b[92mOmicron\u001b[97m on \u001b[96m�🐳\u001b[1C v19.03\u001b[97m.\u001b[0m5\r\n\u001b[92;1m➜ \u001b[0m"```

**Comment by Eugeny** [comment]
Thanks. Could you check this against v1.0.102?

**Comment by FlorentLM** [comment]
Sorry for the delay, it's exactly the same :(

```"\r\n\u001b[93;1mflorent\u001b[97m in \u001b[96m~\u001b[97m at \u001b[38;2;215;0;95mOmicron\u001b[97m on \u001b[96m�🐳\u001b[1C v19.03\u001b[97m.\u001b[0m6\r\n\u001b[92;1m➜ \u001b[0m"```
