### ISSUE TITLE
Terminal too narrow after tab restore

### ISSUE THREAD

**Issue by CyrilTaylor** [Eugeny/terminus#2025]
Version: 1.0.100
Platform: win32 10.0.18363
Plugins: none

![image](https://user-images.githubusercontent.com/12631466/72703890-dbabfd80-3b91-11ea-85c0-5de0609be144.png)

**Comment by ChipwizBen** [comment]
I too have this issue after I downgraded from A100 to A98. I haven't found a work around for it.
