### ISSUE TITLE
Tab name changes when already set in ssh connection

### ISSUE THREAD

**Issue by lxwulf** [Eugeny/terminus#2027]
Wouldnt be nice to have  the name on tab which i already set in the ssh connection settings?

![grafik](https://user-images.githubusercontent.com/44492381/72709027-4c3c2580-3b64-11ea-94ff-c96c59c0da24.png)

![grafik](https://user-images.githubusercontent.com/44492381/72708998-36c6fb80-3b64-11ea-9185-1b8bd2909ea7.png)

**Comment by CyrilTaylor** [comment]
double-click the title of tab to set the name of tab.

**Comment by lxwulf** [comment]
no i know that already, but it would be nicer when this is automatically setup

**Comment by CyrilTaylor** [comment]
But in the case of that multi-tabs for the same server, the tab name will be hazy even though index them. You can color them in advanced settings of ssh.

![image](https://user-images.githubusercontent.com/12631466/73061179-81ce6f00-3ed4-11ea-84f9-a81d581d69d8.png)

**Comment by lxwulf** [comment]
ah i completly didnt saw that ^^' thank you i think that is not a bad "workaround"
