### ISSUE TITLE
Alt key combination doesn't work in alpha 32

### ISSUE THREAD

**Issue by superwg** [Eugeny/terminus#203]
Affecting version: terminus_1.0.0-alpha.32.2_amd64.deb

alt+b alt+f doesn't work.

It was working fine in alpha.27

**Comment by hateonion** [comment]
Almost same issue:
Version: Alpha 33
System Version: Ubuntu 17.10

Keybinding meta or alt won't work.

**Comment by scrossan-crown** [comment]
Version: Alpha 35
System: Windows 10

I'm having the a similar issue when trying to use alt+g for go to line in nano. It did work in an older version can't remember which but I've noticed in the last couple of versions it's not been working.

**Comment by SC7639** [comment]
Version: Alpha 35
System: Windows 10

I'm having the a similar issue when trying to use alt+g for go to line in nano. It did work in an older version can't remember which but I've noticed in the last couple of versions it's not been working.

**Comment by cezarsl** [comment]
Version: Alpha 44
System: Windows 10

Alt key does not work as a modifier, only to input special characters, i.e. ALT+1234 produces ╥
I tried sshing into an Ubunut Machine, where I installed ncurses-examples and ran /usr/lib/ncurses/examples/demo_altkeys, which produced nothing when I pressed ALT. However, the windows key looks like it behaves like the ALT/ESC key

**Comment by Eugeny** [comment]
Let's track this in #316
