### ISSUE TITLE
Lag and high RAM memory usage

### ISSUE THREAD

**Issue by hardwareadictos** [Eugeny/terminus#2031]
Hi friends.

Just noticed that app is taking too much RAM memory from system, just with two tabs opened. Once you start working with more tabs and more consoles it gets laggy, even more when outputing lots of text. Other console managers like winsshterm or putty are taking lot less memory (like 20-30MB). 

Happening on both Linux (Fedora 31) and Windows 10. Tested on two laptops, and a Surface.
What could be the issue?

Thanks in advance :)

Greetings.

<img width="488" alt="terminus" src="https://user-images.githubusercontent.com/20403906/72712439-501f7600-3b6b-11ea-89bc-ea5cbc79fa03.PNG">

**Comment by pdc4444** [comment]
I left Terminus open over the weekend with no active sessions, came back to see it consumed over a gig of memory. What was it doing?

(Windows 10 Pro)

![image](https://user-images.githubusercontent.com/47576692/72732317-6b868300-3b63-11ea-99a8-2aa8493a0f15.png)

**Comment by hardwareadictos** [comment]
Hope we can get some feedback about this soon :(

**Comment by mattias93** [comment]
Terminus is based on the Electron framework, which is very heavy on the RAM. Visual Studio Code, also based on Electron but heavily tuned by Microsoft, also uses almost the same amount of ram with no projects open. That's my best guess
