### ISSUE TITLE
unable to write

### ISSUE THREAD

**Issue by Zandary** [Eugeny/terminus#2032]
Version: 1.0.100
Platform: win32 10.0.18363
Plugins: none
I can't write anything on the shell!

**Comment by Zandary** [comment]
I can't write anything on the shell!

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by Zandary** [comment]
I've reinstalled it and it worked properly, thank you
