### ISSUE TITLE
Cant save ssh profiles on linux

### ISSUE THREAD

**Issue by lxwulf** [Eugeny/terminus#2035]
Im on Fedora 31 with KDE Plasma desktop and wayland engine (kwayland)

When i want to save a new ssh profile its crashing the save process terminus itself is still here but the setring window of ssh is crashing and nothing saved when i click save

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by lxwulf** [comment]
nvm? it worked now....maybe my keyring wasnt unlocked because i noticed that it should ask when i typing the password init however we can close this one but next time i give you from the first post the logs ;)
