### ISSUE TITLE
Add some sort of feedback to the settings tab.

### ISSUE THREAD

**Issue by tabarra** [Eugeny/terminus#204]
There is absolutely no response from the settings tab after a click a button, so I don't know if it was registered/saved.

**Comment by valeryan** [comment]
On the latest release (32.2) the settings that are button based are not saving and are not showing feedback for the current settings. I had to drop back to alpha 29 to find a version where the settings buttons are working properly.

**Comment by borekb** [comment]
> On the latest release (32.2) the settings that are button based are not saving

Same here, I'm on Windows 10 x64 1703.
