### ISSUE TITLE
USB level portability

### ISSUE THREAD

**Issue by PipeItToDevNull** [Eugeny/terminus#2048]
Is this able to use configs located in a configurable or relative location? I do not see a way to contain this onto a USB for portability.

**Comment by Eugeny** [comment]
The latest portable exe creates a data folder for configuration in the same location as the binary

**Comment by PipeItToDevNull** [comment]
I do not see this behavior in 1.0.100 or 1.0.101-nightly that was downloaded a few minutes ago. I removed my appdata directory, ran the executable and the appdata folder was re-created.

**Comment by Eugeny** [comment]
Just looking back at https://github.com/Eugeny/terminus/commit/8201e0b9ef07bf13c98da0f084e86160f20f3918 - can you try creating a `data` directory next to the binary and see if it will start using it?

**Comment by PipeItToDevNull** [comment]
It did indeed start using the `data` folder to hold:

`.updaterID`
`config.yaml`
`log.txt`

It still created the appdata directory to hold a bunch of things (I assume none of that is config data though)

**Comment by Eugeny** [comment]
Folder should be created automatically now
