### ISSUE TITLE
Feature Request: Horizontal Scrolling using the mouse.

### ISSUE THREAD

**Issue by cburj** [Eugeny/terminus#2049]
Not necessarily related to Terminus itself, but it would be nice to add support for horizontal scrolling - which would basically just map to the left and right arrow keys. 😁

**Comment by Eugeny** [comment]
Do you mean scrolling in a specific app (e.g. vim)?
Terminus is not a PTY type terminal (as opposed to conhost) and doesn't include horizontal scrolling at all.

**Comment by cburj** [comment]
I mean anywhere in terminus, not specifically vim or other text editors. I think it would be super useful to be able to use horizontal scroll to move the cursor left and right on the screen. :)

**Comment by Eugeny** [comment]
There are no escape sequences I could send to the shell to notify it of horizontal scroll, but it could be an idea for a plugin that converts it to the ANSI arrow key sequences :)

**Comment by cburj** [comment]
While i can reproduce this with an Autohotkey script, I think it would be pretty cool to have this built in to Terminus. Thanks for the quick replies by the way! :)
