### ISSUE TITLE
text formatting different than Powershell

### ISSUE THREAD

**Issue by ak1dd** [Eugeny/terminus#2051]
Love Terminus.   I'm new, so may be missing something.  I use Ubuntu on Windows 10, WSL - zsh.   I also use PowerLevel10K installed as described here: https://github.com/romkatv/powerlevel10k

Everything seems to work with Terminus but the text formatting is very different.  Fonts with background highlights aren't vertically centered, some of the  characters from Meslo Nerd Fonts are incorrect.

In the attached screenshot you see Powershell running behind Terminus.  

![2020-01-23 12_14_20-~](https://user-images.githubusercontent.com/38289720/73020224-0c7e7380-3dda-11ea-95d2-5e8e187ca0cf.png)

Version: 1.0.98
Platform: win32 10.0.18363
Plugins: none

**Comment by Eugeny** [comment]
Could you please grab the latest nightly and provide a dump of your terminal state as described here? https://github.com/Eugeny/terminus/wiki/Posting-terminal-state
