### ISSUE TITLE
New Shell Tab Displays "undefined" Instead of Blank Icon

### ISSUE THREAD

**Issue by ensafi** [Eugeny/terminus#2052]
When a custom or standard shell such as WSL does not have an associated icon, the text "undefined" is displayed in the new shell tab's pop-up menu.  This did not happen in version 1.0.93.  I started to notice it after 1.0.97, and it continues to manifest itself in 1.0.100.

![menu](https://user-images.githubusercontent.com/1656720/73045703-ce0da680-3e23-11ea-99e5-78435e88d14a.png)

**Comment by Eugeny** [comment]
Could you please double-check your version? I've already fixed this just a few versions back

**Comment by ensafi** [comment]
Yes, here is a screenshot.  I also tried to delete config.yaml to start with fresh settings, and th eproblem persisted.  Could there be any other conflicting files or settings from a previous version?
![window](https://user-images.githubusercontent.com/1656720/73109251-7de02400-3eb7-11ea-8249-43192fdd057b.png)

**Comment by elvisoliveira** [comment]
It would be nice to add an option to disable this icons

**Comment by Eugeny** [comment]
Fixed in the nightly build
