### ISSUE TITLE
Problem with SSH private key file since 1.0.99

### ISSUE THREAD

**Issue by K3UL** [Eugeny/terminus#2053]
Similar to #2006 I generated a key with putty-keygen (I think, it was so long ago) and it stopped working to connect by SSH in 1.0.99 (and 1.0.100) with the following message:
`Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR`

Here is the header of my key file:
```
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-128-CBC,6AAC7A25BD3CC1C457B424C247C20CEB
```

It used to work fine until 1.0.98. Is this a regression or is it some format that will not be supported anymore ?

**Comment by CyrilTaylor** [comment]
FYI

https://github.com/liximomo/vscode-sftp/issues/594#issuecomment-511221368

**Comment by K3UL** [comment]
Thank you ! But as stated by someone in that thread, converting to PEM does not seem like a great solution

**Comment by dylanh724** [comment]
Why is this closed? @Eugeny - converting to PEM is a workaround; not a solution.

**Comment by K3UL** [comment]
@dylanh724 I think it is because #2018 has been reopened since, it has more history on the problem

**Comment by Eugeny** [comment]
Guys, it's been closed with a fix. Apparently it doesn't work in all cases though, so reopening.

**Comment by Eugeny** [comment]
Added a potential fix, please test this nightly once it's ready: https://ci.appveyor.com/project/Eugeny/terminus/builds/35791534
