### ISSUE TITLE
Privacy concerns

### ISSUE THREAD

**Issue by Onepamopa** [Eugeny/terminus#2057]
Hello,

Can you explain for what purpose Terminus tries to connect to the following hosts?

37.188.42.15 - RU kursk telecom - no DNS query (direct IP connection)

github-production-release-asset-2e65be.s3.amazonaws.com
A
    CNAME: s3-1-w.amazonaws.com. (ttl=2400)
    A: 52.216.89.196 (ttl=0)

github-production-release-asset-2e65be.s3.amazonaws.com
A

    CNAME: s3-1-w.amazonaws.com. (ttl=2113)
    A: 52.216.26.220 (ttl=3)

www.npmjs.com
A
    A: 104.16.93.83 (ttl=300) - Cloudflare
    A: 104.16.92.83 (ttl=300) - Cloudflare

**Comment by Eugeny** [comment]
The first one is likely the Mixpanel analytics endpoint (enabled after the first start prompt only)

GitHub is used for update checking

NPM is queried for available plugins

**Comment by Onepamopa** [comment]
I have the "analytics" disabled, this is not a "first start" - it connects to that IP on each run.

**Comment by Onepamopa** [comment]
Upon further checking it seems this IP does not respond on port 443 (I wanted to see if there's anything in the certificate to indicate the purpose of that connection), even though I can clearly see in/out traffic on firewall. Port-knocking ?

**Comment by Onepamopa** [comment]
So, is this analytics connection or?
I tried to search for 37.188.42.15 in the source - couldn't find it:

terminus # find . -type f -name "*" |xargs grep "37.188.42.15" 2> /dev/null |wc -l
       0

**Comment by Eugeny** [comment]
What OS are you on? With the Linux build, i'm only getting one `connect()` under strace and that's to Github.

**Comment by Onepamopa** [comment]
@Eugeny I'm using the Windows version.

It won't be a bad idea to check how it behaves:
1. Block + Log all traffic for the Terminus process (I'm using Kaspersky's firewall, it's great).
2. Check the extended log and see where it (tries) to send traffic.

**Comment by Eugeny** [comment]
Terminus is completely open source, including the **build process**, and I fully review each contribution individually. The only way is that one of the dependencies could contain malicious code. There are no active known CVEs against them and I'm actively monitoring for security updates using Dependabot.

Having said that, I'm still unable to reproduce any of this on Windows either:
![image](https://user-images.githubusercontent.com/161476/73169813-f2140500-410d-11ea-9465-49c0a0728982.png)

I suggest that you check whether any of your shell startup scripts contain anything that might be making outside contact.

**Comment by Onepamopa** [comment]
I'm running DEFAULT installation of Terminus:
- Analytics disabled.
- No additional plugins.

Here is what Kaspersky firewall logs when I start Terminus without any tabs open, and as I mentioned above - no custom plugins, no custom themes, analytics disabled:

![Terminus-Connections](https://user-images.githubusercontent.com/3053279/73175205-4de08d00-4112-11ea-839d-5c387f533c6f.png)

Now, you tell me again ?

**Comment by Onepamopa** [comment]
The IP is actually 35.188.42.15 (GCP) not 37.188.42.15. Weird. I'll recheck the firewall logs again.

**Comment by PipeItToDevNull** [comment]
I only show 2 connections, one to aws and one to github when terminus is opened. They are terminated after a period of time. 

You software of choice for security is also not recommend or highly recommend based on your geographic location lending to the idea that it is faulty or your system is compromised.

**Comment by Onepamopa** [comment]
@PipeItToDevNull What are you referring to?

**Comment by Onepamopa** [comment]
By the way I'm closing the issue. Seems like I mistyped the IP, somehow...
I can't see it in the fw logs going 1 week back.

In any case I'll keep the Terminus outbound comms restricted to IPs I need to connect with.

**Comment by scaleoutsean** [comment]
Here's where my /opt/Tabby/tabby (I have the sha256sum from that time -  b65b240550ef1dcef50d0bb5cbb042d4008ae11c58c4fd898a71c3c0f5ea5103 - now I have v1.0.169 but I don't know what version I had last month) connected when it was running in January:

```raw
104.16.92.83                                                                                                                                                                                                                                                                                       1     0.0 kB     0.0 kB
com.amazonaws.compute.ap-northeast-1.ec2-13-230-158-120                                                                                                                                                                                                                                            6     0.0 kB     0.0 kB
com.amazonaws.compute.ap-northeast-1.ec2-18-179-245-253                                                                                                                                                                                                                                           13     0.0 kB     0.0 kB
com.amazonaws.compute.ap-northeast-1.ec2-52-69-239-207                                                                                                                                                                                                                                             5     0.0 kB     0.0 kB
```

It was all outgoing tcp/443, with 0kb transferred, could be just a "ping" of sorts. 
It'd happen twice a day, 15 min before noon and 15 min before midnight.

```raw
/opt/Tabby/tabby --type=utility --utility-sub-type=network.mojom.NetworkService --field-trial-handle=xxxxxxxxxxxxxxxxxxx,xxxxxx --disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --lang=en-US ...
```

My analytics setting is now off and I don't recall changing any settings for a while. 

I can't say with certainty that I wasn't downloading from within Tabby (wget and such) - maybe it was me, but I'll just share this here in the case it helps someone save time.

**Comment by Eugeny** [comment]
These are GitHub's IPs, have you disabled automatic update checks?

**Comment by scaleoutsean** [comment]
Good to know.

I've been using the default settings.

Maybe that's what some other folks saw as well.
