### ISSUE TITLE
Scroll back not working (Linux)

### ISSUE THREAD

**Issue by TeroBlaZe** [Eugeny/terminus#206]
Can't scroll with the mouse wheel but I can scroll in Hyper or native Terminal
for example if I type `ls -la` then `cat .zshrc` in Hyper or Terminal I can scroll back content of .zshrc but in Terminus it cuts the top of zshrc and shows end of `ls -la`
[Example image](https://i.imgur.com/bwT9Fq6.png)

Disabling session persistence solves this issue, but maybe there is other way to do.

**Comment by nik0diamond** [comment]
It's looking as the same. Can't scroll back with the mouse on long out's (logs for examples) and in editors scroll down (vi or vim). 
What about session persistence disabling? Where can I do it? 
Sorry, a am not very smart.

**Comment by dogcalas** [comment]
This is happening to me too!!! Please help!
I am using  oh my zsh!.
