### ISSUE TITLE
Proposal: brief introduction to styling

### ISSUE THREAD

**Issue by Marahin** [Eugeny/terminus#207]
Hello!

First of all I want to say **THANK YOU!**, all maintainers and contributors, as you are bringing me the terminal emulator I needed, that is usable, unlike most of the Electron based projects that came up lately in the open source world. :) Good job and keep it up!

I come here today to suggest adding a wiki page that would briefly introduce users to styling. Today I felt like I want to add a background image to the editor, and I couldn't find an option anywhere. I knew that there is a CSS-override box in the settings though, so I headed there. 

I needed to open the dev tools to find the selector I needed, and I managed to do so.

I think a brief introduction with basic selectors list would be very handy, alongside with basic examples (like adding a background image).

**Comment by Marahin** [comment]
(actually the tab selector is `tab-body.active`? So, yeah, this proves a point I think :D)

**Comment by Eugeny** [comment]
Great idea! The class names & layout are still subject to change until the final version, but I'll see what I can do.

BTW, here's a shorter way to add a background:
```css
x-screen {
    background: url(http://i.imgur.com/lo6Td1n.jpg);
    background-size: cover;
}
```

**Comment by Slider-Override** [comment]
Can please someone create a short tutorial for how to change the background image or the console ?

**Comment by RobBravo** [comment]
Can please someone create a short tutorial for how to change the background image or the console ?

**Comment by ecspresso** [comment]
Open developer tools under settings to bring up the console and view the DOM tree. Using this, you can see determine the selector needed to create a custom CSS with a image you want.
