### ISSUE TITLE
REQ: Dark Windows Title Bar 

### ISSUE THREAD

**Issue by KZNcode** [Eugeny/terminus#2071]
Can we get a dark theme windows title bar?

![screenshot_20200128-214341_This_PC](https://user-images.githubusercontent.com/10285627/73331001-42c35500-4217-11ea-9714-8e711022a456.png)

**Comment by Eugeny** [comment]
Non-AppX apps can't follow the system theme (like Explorer).

You can switch "Window Frame" to "Thin" or "Full" to get an emulated title bar, like VSCode does:
![image](https://user-images.githubusercontent.com/161476/73840395-2764d500-4829-11ea-8441-7e96015c081d.png)
