### ISSUE TITLE
Screen Tearing and Rendering Issues.

### ISSUE THREAD

**Issue by adwaraki** [Eugeny/terminus#2074]
Version: 1.0.100
Platform: win32 10.0.18363
Plugins: altair, clickable-links, quick-cmds, relaxed-theme, save-output, scrollbar, shell-selector, theme-gruvbox, theme-hype, theme-windows10, title-control

I am noticing weird screen tearing and rendering issues on Terminus on Windows 10. I am not quite sure how to diagnose this further or even troubleshoot it. The problem is that it is occurring only with two applications on Windows 10, one is Terminus and the other is Notion Desktop (which is an all-in-one note-taking app), 

The rendering issues start when the Terminus window is visible in the foreground, but the mouse focus is not on that window. Then you notice an initial rendering issue. It is exacerbated when mouse pointer is continually moved in another window without bringing the focus back to Terminus. It gets worse if there are highlightable items in other windows. For example, if I overlay Terminus on my Outlook main window and then move the mouse pointer continuously over my inbox items that get highlighted as the pointer moves over them, the tearing/rendering gets worse on the Terminus screen.

The issue goes away when you bring focus back to Terminus by clicking on it, and the above scenario rinses and repeats.

I am not quite sure how to troubleshoot this. I have tried changing the settings by turning off the background transparency, and changing the effect from fluent to blur and such. It does not help. In some cases, it just makes it worse.

![Terminus-Screen-Tearing](https://user-images.githubusercontent.com/3513434/73462966-2c65e800-4342-11ea-9850-ebcc2fb04bc6.jpg)

**Comment by adwaraki** [comment]
This is what happens if I leave Terminus in the foreground unattended for some time.

![Terminus-Screen-Tearing](https://user-images.githubusercontent.com/3513434/73466004-dcd5eb00-4346-11ea-9bd8-0d5b8f2c1fce.jpg)

**Comment by Eugeny** [comment]
This definitely looks like a GPU rendering issue. Notion seems to be an Electron based app as well.
What's your GPU and the driver version? (this might actually be the one case where updating the drivers could help)

**Comment by adwaraki** [comment]
I am currently running the nVidia GeForce 441.87 drivers on an RTX 2080 Ti. The GPU drivers are kept up to date via the GeForce Experience app. All the drivers and Windows itself are up to date.

**Comment by adwaraki** [comment]
I just checked on the nVidia site and the 441.87 seems to be the latest release version out there.

**Comment by Eugeny** [comment]
I've added an experimental Electron 8 build (downloads will appear soon) - https://ci.appveyor.com/project/Eugeny/terminus/builds/30464163
Please see if that fixes your issue

**Comment by adwaraki** [comment]
Thank you so much. Let me check if that fixes it. I will update you after checking it.

**Comment by adwaraki** [comment]
Eugene, I just wanted to check if the download will appear at a beta download. I was looking at the commits and changes and seems like you made them on a separate branch. The changes you made on the master seem to have been built and downloads available. I am not quite sure how it works for a different branch.

**Comment by Eugeny** [comment]
On the Appveyor page I linked above, go to the Artifacts tab and the downloads will be there

**Comment by adwaraki** [comment]
My apologies. I was not aware that was where I was supposed to look. Appreciate the help. :)

**Comment by adwaraki** [comment]
@Eugeny Eugene, I just checked and the issue still exists. I am attaching a screenshot. I am not quite sure if you can see it, but the version in the settings shows 1.0.102nightly.

![Terminus-Screen-Tearing](https://user-images.githubusercontent.com/3513434/73486539-f9841a00-436a-11ea-9123-2a6ced16e03a.jpg)

**Comment by Eugeny** [comment]
Does disabling "acrylic background" chance anything?

**Comment by adwaraki** [comment]
Not that I can see. :(

![Terminus-Screen-Tearing](https://user-images.githubusercontent.com/3513434/73487281-49171580-436c-11ea-9dba-5332cc3639d1.jpg)

**Comment by adwaraki** [comment]
Hi @Eugeny , actually it has improved a lot. I posted the screenshot as soon as I installed the build and maybe for some reason, it took time to take effect. It is not completely gone, but definitely improved a lot. I can at least use the app now. We can investigate further if would like to, if not, I can close the bug and you can roll in the changes to master, if you think it is something people can live with for now.

**Comment by Eugeny** [comment]
Electron 8 is now in master. If you any other useful correlations - feel free to comment and I'll reopen this. Thanks!

**Comment by lapis-kasen** [comment]
Hi @adwaraki , I recently had a similar problem with another Electron application. While playing with Geforce's driver settings, the problem was resolved. I think it was resolved when the Image Sharpening function was disabled. Sorry for the inaccurate information, but FYI.

**Comment by ayucapal** [comment]
> Hi @adwaraki , I recently had a similar problem with another Electron application. While playing with Geforce's driver settings, the problem was resolved. I think it was resolved when the Image Sharpening function was disabled. Sorry for the inaccurate information, but FYI.

Thank you ! This worked for me, the same problem !!!
