### ISSUE TITLE
Feature Request: How about the SSH Dynamic Port Forwarding?

### ISSUE THREAD

**Issue by lxwulf** [Eugeny/terminus#2077]
The local/remote portforwarding options in terminus are very very nice but what is when i want to portforwading the connection dynamically? then i need to do it in a normal terminal a third option for dynamic pf would be nice 

to be clear i mean the ssh option -D like => ssh -D 8080 lxwulf@myserver

**Comment by eugenov** [comment]
Very handy! I use it every day - no vpn needed with this socks5 tunnel.

**Comment by johnalanyoung** [comment]
This would indeed be a great feature to have.

**Comment by zend** [comment]
The project [ssh2](https://github.com/mscdex/ssh2) supports dynamic port forwarding using the api `forwardOut`.

See example:
https://github.com/mscdex/ssh2/blob/v0.8.x/README.md#dynamic-11-port-forwarding-using-a-socksv5-proxy-using-socksv5

**Comment by ykgw-liuxin** [comment]
+1
I like port forwarding in termius<https://termius.com/>

**Comment by Eugeny** [comment]
Now available in the nightlies
