### ISSUE TITLE
ability to edit preconfigured profiles like saved profiles

### ISSUE THREAD

**Issue by laundmo** [Eugeny/terminus#2078]
currently i can only create a new profile which is a duplicate of a preconfigred one to edit some settigns such as:
- arguments
- command
- name
- run as adminstrator
- tab color

these settings should be made avaliable for all profiles, not just saved ones. that way i dont need duplicate profiles just to access these settings.

fo this i think the best way would be to rename "Saved Profiles" to simply "Profiles" and allow editing of all default profiles there, while keeping the ability to create a new profile from the unedited default profiles.

this would also allow us to delete default profiles from the new tab selection, but allow to add them back by creating a new profile from the unedited default profiles.

the ability to hide all default profiles from the new tab selection + adding them to saved profiles would accomplish the same

**Comment by mjklemm** [comment]
It would also be great to be able to define the working directory  for each of the default profiles. For instance, Cygwin wants to start in C:\cygwin\home\username, while WSL prefers to start in the native home folder somewhere in AppData on Windows.

**Comment by Eugeny** [comment]
Would you guys be interested in having an option to just hide all the default profiles from the profile menus? This way, you'll be able to create new profiles using the existing ones as templates and change any options on them. As a bonus, you'll only have the profiles you actually use.

**Comment by mjklemm** [comment]
That would certainly work for me. This is a one-time setup effort and it would reduce the number of shown profiles.  So, +1 from me.
