### ISSUE TITLE
High Network Usage when Opening Despite Analytics and Auto Update Disabled

### ISSUE THREAD

**Issue by Talkarcabbage** [Eugeny/terminus#2088]
Version: 1.0.98
Platform: win32 10.0.18363
Plugins: none

Opening Terminus sometimes results in several minutes of high network download usage even though both auto-update and analytics are off (they were off prior to opening). Whether or not a network connection is available also seems to dramatically affect startup times (including if auto update is disabled, and where having no internet access causes a longer delay, of 10 seconds or more), which I assume may be related. Observed with no terminals open beyond opening the settings menu to gather the screenshots below. 

![image](https://user-images.githubusercontent.com/3232043/73805099-5af12200-478b-11ea-92e4-69f6ed1d810c.png)
![image](https://user-images.githubusercontent.com/3232043/73805108-62183000-478b-11ea-9f99-757ec602adb0.png)

**Comment by Eugeny** [comment]
Looks like the updater module would still try to download the update, but just won't install it if disabled. Fix incoming
