### ISSUE TITLE
Heavy "Unhandled exception" Output on DevTool Console

### ISSUE THREAD

**Issue by lapis-kasen** [Eugeny/terminus#2095]
Version: 1.0.101
Platform: win32 6.3.9600
Plugins: none (Only Buildin Plugins activated)

The DevTool has a lot of fast output like the one below (Increase by about 50 ~ 100 per second). What is this? However, the application itself appears to work fine on the surface. Don't I have to worry about it?

![image](https://user-images.githubusercontent.com/43636453/73911576-a0316300-48f5-11ea-97cf-5751dc74e644.png)

**Comment by Eugeny** [comment]
Could you please start Terminus itself from CLI? There should be more details error messages there.

**Comment by lapis-kasen** [comment]
Hi @Eugeny , Thank you for your reply. Unfortunately, Terminus could not be launched from the CLI due to a problem with the company environment. (You have followed the instructions on this [note](https://github.com/Eugeny/terminus/blob/master/HACKING.md). If not, I would appreciate it if you could tell me the procedure.)

In addition, when I started Terminus alpha v101 from my PC at home, it started normally, and there was no abnormal log like the one mentioned above. That's why I think it's a problem that only happens in the company environment. The difference is with or without a proxy. If you are inside the company, connect to the external network through a proxy. I will try a little more and let you know if there is any change. Are you sure you want to close it? (Or please close it.)
