### ISSUE TITLE
A show bug when opened terminal newly

### ISSUE THREAD

**Issue by ou-taku14** [Eugeny/terminus#2098]
![image](https://user-images.githubusercontent.com/46275394/74081574-7c078a80-4a8b-11ea-810d-8dfa90873f64.png)

**Comment by tortuo** [comment]
Running macOS Catalina 10.15.3, Terminus Alpha 101

**Comment by Eugeny** [comment]
That's a Powerline prompt. Are you using a Powerline enabled font?

**Comment by tortuo** [comment]
Oh, I use Monaco font~
