### ISSUE TITLE
Rendering artifacts in hterm profile with WSL

### ISSUE THREAD

**Issue by sriharshachilakapati** [Eugeny/terminus#2099]
![image](https://user-images.githubusercontent.com/4593204/74090289-792e8900-4acf-11ea-8326-1a2159657c95.png)

I'm searching for the perfect terminal on Windows, and this is far better than any existing ones. It took me some time to get the colors come right, but there are some artifacts. See the line 33 from below? It is showing some unwanted text in the indent area.

I tried xterm, but it is not allowing me to send Alt key to terminal so I'm stuck with hterm. Any idea on what could have gone wrong?

I didn't find the location of config files to attach. I can attach them for you.

**Comment by Eugeny** [comment]
Hterm has tons of rendering issues and isn't being updated anymore, that's why we default to xterm.

You can enable the Alt key under Settings -> Terminal.
Config file is available under Settings -> Config file

**Comment by sriharshachilakapati** [comment]
I tried shifting to xterm. It is painfully slow, and alt is still not working for me. Am attaching the file here:

~~~yaml
hotkeys:
  profile:
    wsl-default-distro: []
  shell: {}
  ctrl-c: []
  toggle-window: []
  toggle-fullscreen:
    - - Alt-Enter
  rename-tab: []
  close-tab: []
  next-tab:
    - - Ctrl-Tab
  previous-tab:
    - - Ctrl-Shift-Tab
  split-right: []
  split-bottom: []
  pane-maximize: []
  pane-nav-up: []
  pane-nav-down: []
  pane-nav-left: []
  pane-nav-right: []
terminal:
  colorScheme:
    name: ayu
    foreground: '#e6e1cf'
    background: '#0f1419'
    cursor: '#f29718'
    colors:
      - '#000000'
      - '#ff3333'
      - '#b8cc52'
      - '#e7c547'
      - '#36a3d9'
      - '#f07178'
      - '#95e6cb'
      - '#ffffff'
      - '#323232'
      - '#ff6565'
      - '#eafe84'
      - '#fff779'
      - '#68d5ff'
      - '#ffa3aa'
      - '#c7fffd'
      - '#ffffff'
  font: Fira Code Retina Regular
  frontend: xterm
  background: colorScheme
  fallbackFont: Consolas Regular
  environment: {}
  profile: wsl-default-distro
  bell: audible
  autoOpen: true
  altIsMeta: true
  fontSize: 14
  ligatures: true
  useConPTY: true
ssh: {}
appearance:
  theme: Compact
  vibrancy: true
  vibrancyType: fluent
  opacity: 1
  frame: thin
  dock: 'off'
enableAnalytics: false
enableWelcomeTab: false
~~~

Rendering is very slow, and something is wrong. I've tried experimenting with the useConPTY parameter too, and colors are proper only when this is set to true. Otherwise it's fast, but colors inside Neovim aren't reported.
