### ISSUE TITLE
Output performance slow compared to gnome-terminal

### ISSUE THREAD

**Issue by jbreitbart** [Eugeny/terminus#21]
I have been playing around with terminus and noticed that cat <file> is relatively slow for large files. 

With terminus:
```
$ cat /var/log/vbox-install.log |wc -l
6516

$ time cat /var/log/vbox-install.log
...
real    0m12.963s
user    0m0.000s
sys     0m0.052s
```
With gnome-terminal
```
$ time cat /var/log/vbox-install.log
...
real	0m0.681s
user	0m0.000s
sys	0m0.032s
```

**Comment by Positive07** [comment]
Are you comparing a native C++ application with a hybrid app made with web technologies? Real question

**Comment by jbreitbart** [comment]
Yes, sure. Both serve the same purpose and whereas I did expect terminus to be slower, I did not expect a slowdown by a factor of ~18.

**Comment by Positive07** [comment]
Yeah, similarly to how Chrome is probably 100 times slower than a curl request...

**Comment by OvermindDL1** [comment]
> Rendering is what is taking time

What about rendering being done async so that actual printing to the screen runs at full speed to a buffer?

The speed that the terminal can receive the text (not necessarily display it, but 'receive' it) can often cause a difference in running speed of programs that flush output routinely.

**Comment by sylveon** [comment]
At least terminus is better than hyper. When running `journalctl --no-pager`, hyper will completely freeze for a while. Terminus will slowdown, but completely render the thing.
