### ISSUE TITLE
Display error when using SSH for Windows in PowerShell

### ISSUE THREAD

**Issue by Blealtan** [Eugeny/terminus#210]
Reproduce steps:

1. Open a tab running Windows PowerShell
1. ssh onto any host
1. Run `htop`, and quit
1. Now the console is messed up, with closed `htop` content still remains in the terminal

**Comment by princemaple** [comment]
seems to work for me.

![screenshot](https://user-images.githubusercontent.com/1329716/31152219-e7c088c4-a8e6-11e7-9de5-01b75d025055.gif)

**Comment by Blealtan** [comment]
That's quite embarrassing... Did you log into this host with ssh for Windows from Windows PowerShell?

**Comment by princemaple** [comment]
![image](https://user-images.githubusercontent.com/1329716/31175289-7fd19bb2-a95a-11e7-9f8a-b18cbe17f00d.png)
And yes I'm using powershell. However, I'm not quite sure about the ssh part. Does powershell come with a special ssh? I'm using ssh from docker. And I have another one from open ssh, both work fine.

**Comment by Blealtan** [comment]
Oh I've missed that part, it's the one ssh client goes with Git for Windows. Seems that's the one to be blamed? I'll check for other implements of ssh on Windows later XD

**Comment by Eugeny** [comment]
I've tried with both WSL and Git-Bash SSH clients - works fine for me. 
@Blealtan can you provide any details to narrow this down?

**Comment by Blealtan** [comment]
Sorry but I was too busy these days to cover this.
I'm using the `ssh.exe` under `<path-to-git4win>\usr\bin`, and the version of my Git for Windows is v2.10.2 according to its release note.
Also, with the same environment, ConEmu and VSCode terminal (hence xterm.js) both works fine, so do the default terminal of PowerShell for Windows.
If any other information might be left out, please let me know. Thank you.
