### ISSUE TITLE
vi/vim/nano randomly push characters to left of screen

### ISSUE THREAD

**Issue by superhawk610** [Eugeny/terminus#211]
I've had this issue occur while using vi, vim, and nano, across multiple Linux devices. After typing a few characters on a line, the first character in that line will get pushed to the left of the screen, as shown below:

![terminus-formatting](https://user-images.githubusercontent.com/18172185/31292381-2f576890-aaa1-11e7-992c-0a9d0f2c6296.png)

This strange formatting applies to display only - when the file is saved, the formatting is correct.

The issue seems to only occur in files full of indents (namely, code and config files).

**Comment by tnguyen14** [comment]
@Eugeny can this be kept from going stale?

**Comment by Eugeny** [comment]
@tnguyen14 sure - your comment will already prevent it from being closed. I still wasn't able to reproduce it though

**Comment by superhawk610** [comment]
I'll pull the latest version and see if I can get steps to reproduce. @tnugyen14 if you have any suggestions they would be appreciated.
