### ISSUE TITLE
No right click context menu showing anymore

### ISSUE THREAD

**Issue by mishoboss** [Eugeny/terminus#2111]
I just updated to latest v102 and right click context menu is not showing anymore. It is enabled in Settings. MacOS Mojave.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by mishoboss** [comment]
There's no error in the console. Seems the right click event is not captured at all (I use MacBook's touchpad).

**Comment by Eugeny** [comment]
Can you check whether the event is triggered at `baseTerminalTab.component.ts:378`?
![image](https://user-images.githubusercontent.com/161476/74423736-06b40500-4e51-11ea-9040-0d311da3527e.png)

**Comment by mishoboss** [comment]
Debugged. `event.which` value is `1`.

**Comment by mishoboss** [comment]
So, I got what happens. I use Control + Click on the trackpad to trigger right click. Apparently that's handled as left button click for some reason. It works fine if I use a mouse or I change the trackpad setting to trigger right click in the bottom right corner. Here is an old article, but good enough to describe the issue: https://stackoverflow.com/questions/14725824/any-way-to-detect-ctrl-click-in-javascript-for-osx-browsers-no-jquery
