### ISSUE TITLE
[Windows 10] Open Previous Sessions Directory not working properly with all shells

### ISSUE THREAD

**Issue by debopamgupta** [Eugeny/terminus#2120]
In the release 🗳 Alpha 102, a new terminal opens up in the previous session's directory only while using powershell and cmd and not Git Bash On Windows 10 v1903. 

Is there a way to fix this? 🔧 

BTW when I saw this happening to me on windows , I was genuinely surprised!! Thanks!! ✨  

Just can we work this out with git bash as well in some way? It will be really helpful 👍

**Comment by Eugeny** [comment]
Please see https://github.com/Eugeny/terminus/issues/1703 - "true" CWD detection on Windows is impossible and I rely on parsing it out of the shell. However, you can add a hidden escape sequence to your prompt to notify Terminus of the current dir.

**Comment by debopamgupta** [comment]
The [above fix](https://github.com/Eugeny/terminus/wiki/CWD-reporting) is not working for me on git bash. Any help?

**Comment by debopamgupta** [comment]
This is my bashrc: -   
```sh 
#Python alias
alias python='winpty python.exe'
alias python3='winpty python.exe'
#Aliases
alias clear='reset'
alias c='code'

alias open='explorer' # for windows explorer
# Git aliases
alias ga='git add .'
alias gaa='git add .'
alias gcm='git commit -m '
alias gd='git diff'
alias gi='git init'
alias gpull='git pull'
alias gpush='git push'
alias gs='git status'
alias gss='git status -s'

bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

txtred='\e[0;31m' # Red
txtgrn='\e[0;32m' # Green
bldgrn='\e[1;32m' # Bold Green
bldpur='\e[1;35m' # Bold Purple
txtrst='\e[1;32m'    # Text Reset
txtcyan='\e[1;36m'

print_before_the_prompt () {
    dir=$PWD
    home=$HOME
    dir=${dir/"$HOME"/"~"}
    printf "$txtred%s $bldpur%s $txtcyan%s\n$txtrst" "dg" "$dir" "$(__git_ps1 "[git: %s]")"
}

mkcd() {
  mkdir $1 && cd $1
}

PROMPT_COMMAND=print_before_the_prompt
PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
export PS1="> "
export PS2='=>'
export PS1="$PS1\e]1337;CurrentDir=\w\a"

```
