### ISSUE TITLE
Need option to suppress motd with SSH connections

### ISSUE THREAD

**Issue by ShawnRahlTR** [Eugeny/terminus#2121]
When connecting via SSH, I need/want to suppress issue/motd in SSH connections as I don't want/need to see all the ancillary text in my terminal. 

Ideally, this functionality should be implemented as a checkbox (to disable motd) in each SSH connection configuration.

OS: MacOS 10.15.3
Current version: 1.0.102

**Comment by ShawnRahlTR** [comment]
Thank you! 
Do you have any ETA on a build for MacOS that will contain this fix?

**Comment by Eugeny** [comment]
Done: https://github.com/Eugeny/terminus/releases/tag/v1.0.103

**Comment by ShawnRahlTR** [comment]
With MacOS build 1.0.103, I'm unable to login with shared RSA keys.
- tried without changing any settings.
- tried after removing pointer to SSH key and readding.

I'm getting the following error:
` X  Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR`
