### ISSUE TITLE
It is so slow on my Ubuntu why?

### ISSUE THREAD

**Issue by MatiasDevop** [Eugeny/terminus#2128]
Version: 1.0.0-alpha.47
Platform: linux 5.3.0-28-generic

**Comment by KZNcode** [comment]
Try disabling 3rd party extensions.

Same issue on Windows 10. Came to a crawl after a while. 

(Had tabs and log extensions running... Disabling seems to have fixed the issue; but not totally sure, since only used it for a couple hours after.
