### ISSUE TITLE
Settings button does not work in ubuntu 17.10 

### ISSUE THREAD

**Issue by zhillb** [Eugeny/terminus#213]
Clicking the settings button does nothing in Ubuntu 17.10 beta at 1.0.0 alpha 33 (when installed via the deb file)

**Comment by Eugeny** [comment]
I've just released Alpha 34 - please try it. If it still doesn't work, try pressing `Ctrl-Shift-I` or `F12` to bring up the debug console.

**Comment by zhillb** [comment]
Alpha 34 is having the same results. Ctrl-Shift-I & F12 don't work either. Thanks for the quick reply!

**Comment by leandroaps** [comment]
You need to purge the old installation and install it again, this should fix, but the release 35 lost the autocomplete when you press tab. Roll-backing to the 34 release for now.
