### ISSUE TITLE
Nothing happens up when I try to open a new terminal on Windows 10

### ISSUE THREAD

**Issue by Usmanovsky** [Eugeny/terminus#2130]
When i click the button to open a new terminal, I get nothing. I understand it's supposed to give me a list of distros to select from, How can I fix this?
![image](https://user-images.githubusercontent.com/36796008/74590574-a30b1280-4fdd-11ea-8101-935cf4c61d12.png)

**Comment by jraller** [comment]
Can you access Settings and "Open DevTools" and then check the console log when you try to open a new terminal? There was an issue with a few recent versions for Windows where it was trying to get an icon for WSL that caused it to not open terminals. Which version are you using?

**Comment by Usmanovsky** [comment]
There's no "Open DevTools" option in my settings. I'm using version 1.0.102
![image](https://user-images.githubusercontent.com/36796008/74591044-5e35aa80-4fe2-11ea-8894-135ed26c3460.png)

**Comment by jraller** [comment]
In the screenshot you shared look to the right of the Debugging item under Settings->Application

**Comment by Usmanovsky** [comment]
Oh yeah, found it. This is what it says under console
![image](https://user-images.githubusercontent.com/36796008/74591231-1f085900-4fe4-11ea-899a-204c783a6f1f.png)

**Comment by Eugeny** [comment]
Can you grab the red lines from higher above?

**Comment by Usmanovsky** [comment]
Red lines
![image](https://user-images.githubusercontent.com/36796008/74597056-644d7a80-5026-11ea-9f29-1031bc685fc4.png)

**Comment by Eugeny** [comment]
Thanks. Could you please export and post your 	`HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss` registry key?

**Comment by RaFi32** [comment]
I have the same issue since I updated Terminus to the last release.
Here the export of my Lxss registry key: 

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss]
"DefaultDistribution"="{66c84b68-3222-4bc7-be26-51871871f9cd}"

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{be18a5f5-f116-4706-a0c3-ccc3637ac8b4}]
"State"=dword:00000001
"DistributionName"="Ubuntu-18.04"
"Version"=dword:00000001
"BasePath"="C:\\Users\\rbie\\AppData\\Local\\Packages\\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\\LocalState"
"PackageFamilyName"="CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc"
"KernelCommandLine"="BOOT_IMAGE=/kernel init=/init"
"DefaultUid"=dword:000003e8
"Flags"=dword:00000007
"DefaultEnvironment"=hex(7):48,00,4f,00,53,00,54,00,54,00,59,00,50,00,45,00,3d,\
  00,78,00,38,00,36,00,5f,00,36,00,34,00,00,00,4c,00,41,00,4e,00,47,00,3d,00,\
  65,00,6e,00,5f,00,55,00,53,00,2e,00,55,00,54,00,46,00,2d,00,38,00,00,00,50,\
  00,41,00,54,00,48,00,3d,00,2f,00,75,00,73,00,72,00,2f,00,6c,00,6f,00,63,00,\
  61,00,6c,00,2f,00,73,00,62,00,69,00,6e,00,3a,00,2f,00,75,00,73,00,72,00,2f,\
  00,6c,00,6f,00,63,00,61,00,6c,00,2f,00,62,00,69,00,6e,00,3a,00,2f,00,75,00,\
  73,00,72,00,2f,00,73,00,62,00,69,00,6e,00,3a,00,2f,00,75,00,73,00,72,00,2f,\
  00,62,00,69,00,6e,00,3a,00,2f,00,73,00,62,00,69,00,6e,00,3a,00,2f,00,62,00,\
  69,00,6e,00,3a,00,2f,00,75,00,73,00,72,00,2f,00,67,00,61,00,6d,00,65,00,73,\
  00,3a,00,2f,00,75,00,73,00,72,00,2f,00,6c,00,6f,00,63,00,61,00,6c,00,2f,00,\
  67,00,61,00,6d,00,65,00,73,00,00,00,54,00,45,00,52,00,4d,00,3d,00,78,00,74,\
  00,65,00,72,00,6d,00,2d,00,32,00,35,00,36,00,63,00,6f,00,6c,00,6f,00,72,00,\
  00,00,00,00

```

**Comment by Usmanovsky** [comment]
Here is my registry key @Eugeny 

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss]
"DefaultDistribution"="{49250c15-3aaf-44e7-9275-75d03ee42177}"

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{09e4b911-ad7a-4803-8fa0-3af4c2fb9d01}]
"State"=dword:00000001
"DistributionName"="Ubuntu-18.04"
"Version"=dword:00000001
"BasePath"="C:\\Users\\usman\\AppData\\Local\\Packages\\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\\LocalState"
"PackageFamilyName"="CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc"
"KernelCommandLine"="BOOT_IMAGE=/kernel init=/init"
"DefaultUid"=dword:000003e8
"Flags"=dword:00000007
"DefaultEnvironment"=hex(7):48,00,4f,00,53,00,54,00,54,00,59,00,50,00,45,00,3d,\
  00,78,00,38,00,36,00,5f,00,36,00,34,00,00,00,4c,00,41,00,4e,00,47,00,3d,00,\
  65,00,6e,00,5f,00,55,00,53,00,2e,00,55,00,54,00,46,00,2d,00,38,00,00,00,50,\
  00,41,00,54,00,48,00,3d,00,2f,00,75,00,73,00,72,00,2f,00,6c,00,6f,00,63,00,\
  61,00,6c,00,2f,00,73,00,62,00,69,00,6e,00,3a,00,2f,00,75,00,73,00,72,00,2f,\
  00,6c,00,6f,00,63,00,61,00,6c,00,2f,00,62,00,69,00,6e,00,3a,00,2f,00,75,00,\
  73,00,72,00,2f,00,73,00,62,00,69,00,6e,00,3a,00,2f,00,75,00,73,00,72,00,2f,\
  00,62,00,69,00,6e,00,3a,00,2f,00,73,00,62,00,69,00,6e,00,3a,00,2f,00,62,00,\
  69,00,6e,00,3a,00,2f,00,75,00,73,00,72,00,2f,00,67,00,61,00,6d,00,65,00,73,\
  00,3a,00,2f,00,75,00,73,00,72,00,2f,00,6c,00,6f,00,63,00,61,00,6c,00,2f,00,\
  67,00,61,00,6d,00,65,00,73,00,00,00,54,00,45,00,52,00,4d,00,3d,00,78,00,74,\
  00,65,00,72,00,6d,00,2d,00,32,00,35,00,36,00,63,00,6f,00,6c,00,6f,00,72,00,\
  00,00,00,00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{7f97211f-80a1-4be1-b911-19919abb03ce}]
"State"=dword:00000001
"DistributionName"="Ubuntu"
"Version"=dword:00000001
"BasePath"="C:\\Users\\usman\\AppData\\Local\\Packages\\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\\LocalState"
"PackageFamilyName"="CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc"
"KernelCommandLine"="BOOT_IMAGE=/kernel init=/init"
"DefaultUid"=dword:000003e8
"Flags"=dword:00000007
"DefaultEnvironment"=hex(7):48,00,4f,00,53,00,54,00,54,00,59,00,50,00,45,00,3d,\
  00,78,00,38,00,36,00,5f,00,36,00,34,00,00,00,4c,00,41,00,4e,00,47,00,3d,00,\
  65,00,6e,00,5f,00,55,00,53,00,2e,00,55,00,54,00,46,00,2d,00,38,00,00,00,50,\
  00,41,00,54,00,48,00,3d,00,2f,00,75,00,73,00,72,00,2f,00,6c,00,6f,00,63,00,\
  61,00,6c,00,2f,00,73,00,62,00,69,00,6e,00,3a,00,2f,00,75,00,73,00,72,00,2f,\
  00,6c,00,6f,00,63,00,61,00,6c,00,2f,00,62,00,69,00,6e,00,3a,00,2f,00,75,00,\
  73,00,72,00,2f,00,73,00,62,00,69,00,6e,00,3a,00,2f,00,75,00,73,00,72,00,2f,\
  00,62,00,69,00,6e,00,3a,00,2f,00,73,00,62,00,69,00,6e,00,3a,00,2f,00,62,00,\
  69,00,6e,00,3a,00,2f,00,75,00,73,00,72,00,2f,00,67,00,61,00,6d,00,65,00,73,\
  00,3a,00,2f,00,75,00,73,00,72,00,2f,00,6c,00,6f,00,63,00,61,00,6c,00,2f,00,\
  67,00,61,00,6d,00,65,00,73,00,00,00,54,00,45,00,52,00,4d,00,3d,00,78,00,74,\
  00,65,00,72,00,6d,00,2d,00,32,00,35,00,36,00,63,00,6f,00,6c,00,6f,00,72,00,\
  00,00,00,00

**Comment by Eugeny** [comment]
Thanks guys - is it possible that you have deleted a WSL distro that was previously the default one?

**Comment by RaFi32** [comment]
I don't think so. I installed again the previous version of Terminus that I had (terminus-1.0.90-setup) and it works.

**Comment by Eugeny** [comment]
That's still possible - v90 didn't try to read default distribution info, and recent versions do (to show the appropriate icon).

The nightly build should be ready in a bit

**Comment by Usmanovsky** [comment]
It works now, thanks!!!!! @Eugeny
