### ISSUE TITLE
Maximized terminus with multi screen creates a 'shadow'

### ISSUE THREAD

**Issue by willianba** [Eugeny/terminus#2149]
Version: 1.0.103
Platform: Windows 10

I have two screens on my computer. When I open terminus maximized in one screen, the other screen remains with a little shadow.

See in the image below.

![shadow](https://user-images.githubusercontent.com/26071084/74852424-4b411400-531b-11ea-9486-1dddb13ebbe2.png)

**Comment by mattias93** [comment]
Confirm, even though all the maximized windows in Windows produce the same effect when they are main. I have 3 screens, Terminus is in the middle, windows explorer on the left and firefox on the right, they all produce a shadow ON the others when active, but the one that Terminus produces is the largest and brightest.
