### ISSUE TITLE
Error while signing data with privateKey

### ISSUE THREAD

**Issue by Xen00x** [Eugeny/terminus#2151]
Version: 1.0.103
Platform: win32 10.0.18362
Plugins: altair, relaxed-theme, scrollbar, theme-gruvbox, theme-hype, theme-windows10

On new version I receive error during the connection with private key: Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR

Same key worked fine with old version and no problems when using TermiNus

**Comment by Novezeil** [comment]
+1

**Comment by litaxc** [comment]
+1

**Comment by ShawnRahlTR** [comment]
+1
Platform: MacOS 10.15.3
