### ISSUE TITLE
1.03 cannot parse private key

### ISSUE THREAD

**Issue by amurad** [Eugeny/terminus#2154]
It was working fine until 1.02. With 1.03 I get error:
```
Loading private key from  ###\.ssh\id_ed25519 
 X  Cannot parse privateKey: Unsupported key format
```
Reinstalled 1.02 and it works fine

**Comment by ShawnRahlTR** [comment]
+1
Platform: MacOS 10.15.3

**Comment by E1oz** [comment]
same here, Windows 10 1909 18363.657

**Comment by r00tbox** [comment]
Same here.

**Comment by r00tbox** [comment]
@Eugeny what do you mean with "use ssh-keygen to convert keys", from what to what? i only use ssh-keygen to create keys, why do i need to convert it?

**Comment by Eugeny** [comment]
It's a pull request name. Terminus will now use ssh-keygen internally to convert the key internally from the new OpenSSH format to PKCS.1 which `node-ssh2` understands.
