### ISSUE TITLE
SSH Port Forward: EADDRINUSE: address already in use

### ISSUE THREAD

**Issue by wassimsabra** [Eugeny/terminus#2181]
SSH   X  Failed to forward port (local) 127.0.0.1:18080 → (remote) 23.45.67.89:8080: Error: listen EADDRINUSE: address already in use 127.0.0.1:18080

The added port forwarding does not show after restarting the application.
If I try to re-added I get the error above, however, the port forwarding is not working.

**Comment by Eugeny** [comment]
Duplicate of #2143
