### ISSUE TITLE
SSH Plugin attempts to use private key when a password is set

### ISSUE THREAD

**Issue by viertaxa** [Eugeny/terminus#2183]
When authenticating to a server using the SSH plugin, and a login password is saved, Terminus prompts for the default SSH key credentials and attempts to use that before trying the saved password. 

What should happen: Terminus sees that there is a saved password and attempts to use that first.

**Comment by Metal-Mighty** [comment]
Bumping as it is happening to me too.
Additional info:
- OS: Windows 10
- Terminus 1.0.108
- Doesn't work whether I input a password or not, a username or not, and the private key field is empty (including in the configuration file)
- Errors in dev console: First one when clicking on the connection, second one after the timeout
![image](https://user-images.githubusercontent.com/5247527/80922355-d52a4600-8d7c-11ea-960e-43dd55777ee4.png)

**Comment by Eugeny** [comment]
Fixed
