### ISSUE TITLE
Mouse support

### ISSUE THREAD

**Issue by Calinou** [Eugeny/terminus#22]
**OS:** Windows 10 Creators Update
**Terminus version:** Alpha 15

From my testing with [micro](https://micro-editor.github.io/) and [htop](http://hisham.hm/htop/), it looks like Terminus does not support mouse input, both in a Bash on Windows session and a SSH session inside Bash on Windows (Windows CMD and PowerShell don't feature the concept of mouse input, to my knowledge).

Are there any plans to support it? This would be really appreciated to make text editing much more convenient, especially over SSH (where GUI editors may not be an option).

**Comment by OvermindDL1** [comment]
Confirming the same, I just hit this myself.

**Comment by Calinou** [comment]
Mouse input seems to be working in micro with the new xterm back-end on Linux, but I haven't tested it on Windows yet.

**Comment by hungsu** [comment]
I'd love to see mouse support too!

**Comment by ignacvucko** [comment]
Still broken on latest version.

**Comment by Eugeny** [comment]
Duplicate of #290
