### ISSUE TITLE
SSH Password secure? [ENCRYPT?]

### ISSUE THREAD

**Issue by xJoeyv** [Eugeny/terminus#2200]
Dear,

Due security I would like to know how and where the SSH Connection credentials are stored. If this is a file I would like to encrypt it myself or if it is encrypted how secure is it?

Can I get more clearance about this topic.

**Comment by Eugeny** [comment]
SSH passwords are stored in your OS keychain (Windows Credentials Store / Keychain / Gnome-keyring)
