### ISSUE TITLE
Can't connect host using pem file

### ISSUE THREAD

**Issue by akavato** [Eugeny/terminus#2209]
Version: 1.0.104
Platform: win32 10.0.18363
Plugins: clickable-links

WARNING: UNPROTECTED PRIVATE KEY FILE!
Changing file permissions doesn't make sense, as it creates key file in temp dir/

**Comment by Eugeny** [comment]
Please try the latest nightly build.

**Comment by akavato** [comment]
> Please try the latest nightly build.

Works on terminus-1.0.105-nightly.0. Thank you!
