### ISSUE TITLE
Short Path name and current branch name

### ISSUE THREAD

**Issue by barbarosalp** [Eugeny/terminus#2213]
Is it possible to have the current branch name and a short version of the current path in the terminal? I have checked the plugins and settings but couldn't see any.

**Comment by Eugeny** [comment]
This is provided by the shell, not the terminal. Check out oh-my-zsh: https://github.com/ohmyzsh/ohmyzsh

**Comment by barbarosalp** [comment]
Oh, I hadn't mentioned that the question was about Windows. Do you have any recommendations for Windows? I currently use posh-git.

**Comment by Eugeny** [comment]
Haven't tried it myself, but posh-git does indeed seem to be the go-to option for this.
