### ISSUE TITLE
[BUG] Session restore doesn't work properly

### ISSUE THREAD

**Issue by Onepamopa** [Eugeny/terminus#2214]
Session restore is not working as it should.

Say I have 10 tabs and I close Terminus.
When I start it - most of the time I get 1 tab, sometimes I get 3-4 tabs.

So far the only time I've seen a whole session properly restored is when Windows crashes and I open terminus after BSOD reboot....

**Comment by DanRibbens** [comment]
I don't know if this is considered the same issue, I have never had my tabs reopen to the same path as where I left them. In my experience I typically have 1 - 3 tabs going and after a normal closing of the app, upon reopen, the same number of tabs come up but they are all at "~".

**Comment by Eugeny** [comment]
@DanRibbens if you're on Windows, please see #1703

**Comment by DanRibbens** [comment]
That may be what is going on for me. I am on windows, using bash.
