### ISSUE TITLE
cannot conect SSH

### ISSUE THREAD

**Issue by geldarr** [Eugeny/terminus#2218]
Command failed: C:\Program Files\Terminus\resources\extras\ssh-keygen\ssh-keygen.exe -p -P  -N  -m PEM -f C:\Users\I_GAYN~2\AppData\Local\Temp\f-202025-18292-1r8jquh.indz
                                                                                                                                                                              @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'C:\\Users\\I_GAYN~2\\AppData\\Local\\Temp\\f-202025-18292-1r8jquh.indz' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Failed to load key C:\\Users\\I_GAYN~2\\AppData\\Local\\Temp\\f-202025-18292-1r8jquh.indz: bad permissions

**Comment by Eugeny** [comment]
Please try the latest nightly build

**Comment by geldarr** [comment]
i use last version 1.0.104

**Comment by Eugeny** [comment]
The nightly build is available at https://ci.appveyor.com/project/Eugeny/terminus/builds/31255160/artifacts
