### ISSUE TITLE
Hotkey binding to Win+<

### ISSUE THREAD

**Issue by Thokas** [Eugeny/terminus#2223]
Hi, it seems, that i run in the same problem as **dfyx** in issue #1014.
I've tried to set it manually in the config file, but it doesn't recognize the shortcut `Win-<`, `Win+<` or any other combination.
If i set through the interface, it tries to set `Win-\` and doesn't work at all. If i then set my keyboard to US-Layout it opens with just the click on `<`

_I use a Keyboard with German-Layout._

**Comment by kbromwich** [comment]
Hi, I'm also running into this problem.
I'd like to bind toggle-window to `` Win-` ``, but I have the same problem as Thokas, where the `` ` `` key on it's own will then trigger the toggle-window. I am just using a typical US keyboard layout.
I've settled for using ``Alt-` `` in the meantime, but it'd be great to have support for the "win" key!

**Comment by pm-energid** [comment]
I can't even bind to `Alt+``
