### ISSUE TITLE
Start from a defined working directory

### ISSUE THREAD

**Issue by motss** [Eugeny/terminus#223]
The ability to start from a user-defined working directory is highly desirable.

**Comment by Eugeny** [comment]
You can do that by passing the directory to a shell. I.e., select a `Custom` shell in the Terminal settings and use `/bin/zsh /working/dir` as the command.

**Comment by motss** [comment]
Couldn't get it working for Bash for Windows.

**Comment by Eugeny** [comment]
Now added as a separate option
