### ISSUE TITLE
I found there is no a way to cancel the hotkey of ssh (alt+s) in terminus because i need it in emacs

### ISSUE THREAD

**Issue by abrance** [Eugeny/terminus#2238]
As title, I found there is no a way to cancel the hotkey of ssh (alt+s) in terminus because i need it in emacs.I use terminus 1.0.73.Option Hotkey can find the hotkey sothat i can't undo it.I love this software so much, and I really don't want to abandon it because of it.

**Comment by Eugeny** [comment]
You can remove it from Settings -> Hotkeys: 
![image](https://user-images.githubusercontent.com/161476/76429121-e2dfd280-63ae-11ea-9d18-db26e4f98522.png)
