### ISSUE TITLE
Feature request - When using saved SSH session the name of the tab is the "name" field

### ISSUE THREAD

**Issue by sylock** [Eugeny/terminus#2240]
The behavior of Terminus is to name the tab according to the user@host. From my point of view it is the expected behavior when you did not registered the host previously.

When you registered an SSH connection (from settings/SSH) you setup a "name". Generally, you define something there that has a meaning for you in your daily work (when you need to deal with hundreds of servers). In that case, it would be really useful that the tab name is set according to the "name" field of the registered SSH connection.

**Comment by Eugeny** [comment]
Terminus will use connection name for the tab unless the remote shell overrides it. The "user@host" string is the window title reported by the shell on the other side. As a workaround, you can disable/replace automatic title update code in your shell config.

For example, on stock Ubuntu there's a following snippet in your `.bashrc`:

```bash
# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac
```

**Comment by zhangchenkai** [comment]
Why not add an option to use the ssh name that saved in the "ssh connections"?

**Comment by cvster** [comment]
I need this feature too, because config on many servers is not convenient at all. And other ssh tools like xshell, mremoteNG, they all have this feature.
