### ISSUE TITLE
how to change selection, highlighting and search colors?

### ISSUE THREAD

**Issue by shyhsheng** [Eugeny/terminus#2249]
Version: 1.0.104
Platform: win32 10.0.18363
Plugins: none

Hello,

as title , how to change selection, highlighting and search colors?

Thnanks

**Comment by Eugeny** [comment]
Selection and search use the same color - which can now be customized via the `terminal.colorScheme.selection` setting. What do you mean by a _highlighting_ color

**Comment by shyhsheng** [comment]
Hi Engeny,

terminal.colorScheme.selection <== this is what I want.

thank you.

**Comment by ydcool** [comment]
but this setting can only be customized by editing the config file, no UI in `color scheme` tab ?
