### ISSUE TITLE
Missing builds for alpha.35?

### ISSUE THREAD

**Issue by princemaple** [Eugeny/terminus#225]
![image](https://user-images.githubusercontent.com/1329716/31867386-5c1b1e1c-b7da-11e7-8dc4-1800bb2efd3a.png)

**Comment by Positive07** [comment]
You can search them in the CI artifacts on [AppVeyor](https://ci.appveyor.com/project/Eugeny/terminus/build/216/artifacts)

I have no clue about Travis though so for Mac OSX builds you are on your own.

I don't know what happen that they couldn't upload all the builds, hope they do soon!

**Comment by princemaple** [comment]
@Positive07 thanks!
Windows build is what I wanted. Thank you. :)

**Comment by Positive07** [comment]
No prob! 👍

**Comment by Eugeny** [comment]
Whoops, now fixed!
