### ISSUE TITLE
enhancement: compatibility with Fedora 32 Beta

### ISSUE THREAD

**Issue by stefangweichinger** [Eugeny/terminus#2279]
terminus seems to depend on gnome-python2-gnomekeyring, which seems not to be there in Fedora 32 beta (yet?)

I open this issue as a reminder .. maybe this has to be solved in Fedora, I don't know yet.

**Comment by ybaumy** [comment]
Isnt the problem that it depends on python2 and fedora is pretty much python3 now. I dont see why this should be fixed in fedora?

**Comment by Doctor-Who** [comment]
Same on openSUSE where Python 2 is not supported anymore on modern distribution,
Terminus should find alternative that don't need some old python2 lib as gnome-python2-gnomekeyring
