### ISSUE TITLE
WSL work directory

### ISSUE THREAD

**Issue by erpadmin** [Eugeny/terminus#2287]
setting work directory to WSL long path home doesn't actually navigate to it when creating new sessions, it insists on opening to /mnt/c/Users/<username>

example WSL path for Ubuntu is C:\Users\<username>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\<wsl username>

**Comment by Eugeny** [comment]
Duplicate of #271
