### ISSUE TITLE
Do not enforce multi-line paste warning dialog

### ISSUE THREAD

**Issue by capsali** [Eugeny/terminus#2309]
Hey, in latest version 1.0.105, multi-line paste issues a warning everytime.

I get that some people need this warning, but it is getting frustrating to always get this warning.
Since it is baked in the code and no way of disabling this warning, can we have a new option on enabling/disabling multi-line paste warning in settings?

Thanks.

**Comment by Eugeny** [comment]
Sure! Out of curiosity, in what situations do you paste multiple lines regularly? It already disables itself in fullscreens editors that use alternate buffer, like vi and nano

**Comment by capsali** [comment]
Mostly bash multi-line commands that are not oneliners (&&). Mostly when copying lines from somewhere and pasting them in terminal. :)
It is not a deal-breaker but it gets annoying eventually.
Thanks for the quick reply!

**Comment by khoxsey** [comment]
I'd like to add my desire for the ability to turn off the warning. I upgraded yesterday and the dialog is annoying me to tears already. I routinely generate a block of actions and then paste them into the shell.

Is there an easy way to downgrade my version?
