### ISSUE TITLE
Serial button no response

### ISSUE THREAD

**Issue by steelywing** [Eugeny/terminus#2345]
At this Line

https://github.com/Eugeny/terminus/blob/master/terminus-serial/src/services/serial.service.ts#L70

`window.localStorage.lastSerialConnection` return `undefined` at first time use, so `JSON.parse(window.localStorage.lastSerialConnection)` throw a `Unexpected token u in JSON` error, may be add a default value like `window.localStorage.lastSerialConnection || null`?

**Comment by Eugeny** [comment]
This is already fixed in the nightly build - please try it.
