### ISSUE TITLE
Git Log super laggy

### ISSUE THREAD

**Issue by SarcasmAppreciated** [Eugeny/terminus#235]
In Windows 10 Powershell, after running git log, terminal hangs (for a long time) before you can enter in a command to quit etc.

**Comment by princemaple** [comment]
Try turning off clickable links
https://github.com/Eugeny/terminus/issues/83#issuecomment-314857049

**Comment by SarcasmAppreciated** [comment]
@princemaple that worked for windows - let me try bash now
