### ISSUE TITLE
zmodem/rz not working

### ISSUE THREAD

**Issue by imlizi** [Eugeny/terminus#2352]
Version: 1.0.105
Platform: darwin 19.3.0
Plugins: none

![image](https://user-images.githubusercontent.com/30803070/78563709-fd8e5580-784d-11ea-9281-ad5dd75a3d77.png)

After i chose the file to upload , it print 'Offered',  nothing  happen?

what can i do?

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by imlizi** [comment]
ths for your  reply so rapid，the console log.
![image](https://user-images.githubusercontent.com/30803070/78564554-30851900-784f-11ea-8aaf-9e6d3a73a2c3.png)

**Comment by Eugeny** [comment]
Is this happening locally or over an SSH connection? Please post your `lrzsz` version and environment vars.

**Comment by donglee-afar** [comment]
I meet the same question when connect my server over SSH conection.
`lrzsz` version is 0.12.21-8.
![Annotation 2020-04-14 214519](https://user-images.githubusercontent.com/26436796/79232564-3f487d00-7e9a-11ea-993f-9c0bdfda1894.jpg)

**Comment by Eugeny** [comment]
Can you please check if restarting Terminus and having just one tab open allows `rz` to work?

**Comment by donglee-afar** [comment]
It is not work :(
![Annotation 2020-04-14 221220](https://user-images.githubusercontent.com/26436796/79234670-3016fe80-7e9d-11ea-9cc7-4d4c1d6c30c6.jpg)

**Comment by imlizi** [comment]
> Can you please check if restarting Terminus and having just one tab open allows `rz` to work?

just one table , rz not working, also got Offered.
![image](https://user-images.githubusercontent.com/30803070/79426055-2ef8e500-7ff5-11ea-941e-552b0c956e16.png)
