### ISSUE TITLE
safevalue must use [property]=binding in terminus taskbar

### ISSUE THREAD

**Issue by Deathtech-00** [Eugeny/terminus#2369]
Version: 1.0.106-nightly.0
Platform: win32 10.0.18363
Plugins: altair, clickable-links, quick-cmds, relaxed-theme, save-output, scrollbar, theme-gruvbox, theme-hype, theme-windows10, title-control

I had seen the previous issue with bug #1769 that was closed due to the shell-selector plugin becoming deprecated. I have the most recent nightly, and do not have the aforementioned plugin installed, yet the issue seems to persist.

**Comment by Eugeny** [comment]
The `quick-cmds` has the same problem, and its author hasn't updated it in a while.
