### ISSUE TITLE
Open different Shells

### ISSUE THREAD

**Issue by alexifranco** [Eugeny/terminus#237]
Would it be possible to add a feature which would allow a user to create a new tab/shell which is different from the primary one selected in the settings? e.g. I have "Bash for Windows" selected in the settings though at times I need to launch PowerShell or the cmd prompt. Currently, you would have to go into the settings and change your default shell to "Powershell" then create the tab, then switch the default option back to "Bash".

**Comment by Eugeny** [comment]
The "shell selector" plugin can do this

**Comment by alexifranco** [comment]
Sweet, thank you for the tip. The screenshot for the plugin only showed Unix shells and there was no documentation so I assumed incorrectly.

**Comment by Eugeny** [comment]
I've updated the README to make it more clear :)

**Comment by myaesubi** [comment]
after installing the "shell-selector" and restart, shell-selector does not pop up.
