### ISSUE TITLE
Terminal does not start

### ISSUE THREAD

**Issue by jos3s** [Eugeny/terminus#2381]
Version: 1.0.106
Platform: win32 10.0.19592
Plugins: clickable-links, relaxed-theme, theme-hype, theme-windows10

The terminal is charged and never starts, in any of the modes
![image](https://user-images.githubusercontent.com/50359547/79081085-898dfa80-7cf0-11ea-880d-7450ae1c436a.png)

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by jos3s** [comment]
Critical error log
[logs.txt](https://github.com/Eugeny/terminus/files/4469485/-1586780987426.txt)
