### ISSUE TITLE
First Terminal has delimiter issue

### ISSUE THREAD

**Issue by SarcasmAppreciated** [Eugeny/terminus#239]
On Windows 10, the first terminal you open or auto-open, the delimiter will stick between words:

For instance, if you type "git push", the delimiter will stick somewhere around 's' like "git pus|h"

**Comment by Eugeny** [comment]
Could you please add a screenshot?

**Comment by SarcasmAppreciated** [comment]
https://drive.corp.amazon.com/documents/bensoli%40/Delimter.JPG

**Comment by Eugeny** [comment]
`drive.corp.amazon.com` doesn't resolve

**Comment by SarcasmAppreciated** [comment]
https://orig00.deviantart.net/4d88/f/2017/321/d/d/delimter_by_bli08-dbu10zg.jpg

**Comment by Eugeny** [comment]
Can you please post your complete config file?

**Comment by SarcasmAppreciated** [comment]
terminal:
  shell: powershell
  colorScheme: &ref_0
    name: Bright Lights
    foreground: '#b3c9d7'
    background: '#323f56'
    cursor: '#f34b00'
    colors:
      - '#FFF'
      - '#ff355b'
      - '#7a9b4d'
      - '#ffc251'
      - '#76d4ff'
      - '#ba76e7'
      - '#6cbfb5'
      - '#c2c8d7'
      - '#FFF'
      - '#ff355b'
      - '#9cc663'
      - '#ffc251'
      - '#76d5ff'
      - '#ba76e7'
      - '#6cbfb5'
      - '#c2c8d7'
  cursor: beam
  customColorSchemes:
    - *ref_0
  autoOpen: true
  background: colorScheme
  cursorBlink: false
  font: Inconsolata
hotkeys:
  copy:
    - - Ctrl-Shift-C
appearance:
  theme: Standard

**Comment by SarcasmAppreciated** [comment]
Found the solution after got fed-up with having to open second tab: it's the Inconsolata font (or maybe lack of)
