### ISSUE TITLE
Uninstalled on Update

### ISSUE THREAD

**Issue by izshreyansh** [Eugeny/terminus#2393]
Every time it auto updates, It automatically uninstalls itself without even notifying.
When i close terminus, It asks for elevated permission, Which i think would be inorder to update itself.
But as i restart my machine next day. Terminus shortcut is gone, And i cant find the program anywhere on my machine.

I'm using Avast antivirus. I don't know if that could be causing it? But i haven't seen avast do that with any other program.

**Comment by sduduzog** [comment]
I've gotten this three times already, every since I've started using terminus

**Comment by MrPistachios** [comment]
This happened to me again yesterday evening, now I have to come download it again
