### ISSUE TITLE
[Feature Request] Persistent port forwarding

### ISSUE THREAD

**Issue by jewfro-cuban** [Eugeny/terminus#2395]
Would be nice to be able to save port forwardings per ssh connection without needing to re-type every time the app is restarted.

**Comment by LoveDuckie** [comment]
Yes please!

Having port forwarding rules saved as part of SSH connection configurations would be very useful, especially when combined with something [like RMate and Visual Studio Code.](https://marketplace.visualstudio.com/items?itemName=rafaelmaiolla.remote-vscode)

**Comment by ahbrajev** [comment]
That'd be awesome.

**Comment by ykgw-liuxin** [comment]
+1
I like port forwarding in termius<https://termius.com/>

**Comment by Volnovik** [comment]
Just having a list of preset rules under each connection options (to save time copypasting address and port every time) would be enough.
