### ISSUE TITLE
Settings won't open after upgrading from a previous version

### ISSUE THREAD

**Issue by xpboy7** [Eugeny/terminus#240]
Version: 1.0.0-alpha.35
Platform: win32 10.0.15063

**Comment by Eugeny** [comment]
Could you please paste the log from `%APPDATA%\Terminus` here?

**Comment by eviltak** [comment]
Can confirm this problem on Arch Linux. I just installed the [AUR package](https://aur.archlinux.org/packages/terminus-terminal/) and was asked to upgrade the core and settings from Alpha 24 to 35 by the app. Post the upgrade the settings will not open.

**Comment by Eugeny** [comment]
I see. The built-in plugins shouldn't actually be upgradeable. Please remove the updated version from ~/.config/terminus/plugins ( %APPDATA%/terminus/plugins) and install the latest version of the app itself

**Comment by eviltak** [comment]
The `terminus-settings` and `terminus-terminal` directories in the `node_modules` directory? I assumed the app was at the latest version (it says so on the AUR as well as the `.deb` used as part of installation).

**Comment by Eugeny** [comment]
If the app is at the last version, just drop those two and restart it

**Comment by xpboy7** [comment]
It solved the issue, Thanks.

**Comment by eviltak** [comment]
Just a suggestion, if the built-in plugins aren't meant to be upgradable, why show upgrades in the first place?

**Comment by Eugeny** [comment]
@eviltak it was just a mistake - I've now unpublished them from the NPM and you shouldn't see the "upgrades" anymore
