### ISSUE TITLE
Broken arrow keys on profiled terminals

### ISSUE THREAD

**Issue by Chrominskyy** [Eugeny/terminus#2421]
Version: 1.0.106
Platform: win32 10.0.18363
Plugins: none

Arrow keys to bring back last used command works fine inside regular terminal window.
For Profiled ones it is broken.

[https://i.imgur.com/rcLfLxg.mp4](url)
![BrokenArrowKeysTerminus](https://user-images.githubusercontent.com/7253046/79450270-05d05880-7fe5-11ea-9c37-800072beda3a.gif)

**Comment by rjl9** [comment]
I too was able to recreate this problem with any profiled terminals

**Comment by illuzian** [comment]
Identical issue for me also.
![Terminus_i4yt6LGmPc](https://user-images.githubusercontent.com/6283729/81031628-728d9300-8ebf-11ea-8822-24aacbfd0b18.png)

State
```"[ADMIN]: PS C:\\Users\\username> [A[A[A[A"```

Output
```"\u001b[2J\u001b[?25l\u001b[m\u001b[H\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\u001b[H\u001b]0;C:\\Users\\username\\AppData\\Local\\Programs\\Terminus\\resources\\extras\\UAC.exe\u0007\u001b[?25h\u001b[?25l\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\u001b[H\u001b[?25h\u001b[?25l\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\u001b[H\u001b[?25h\u001b[?25l[ADMIN]: PS C:\\Users\\username> \u001b[282X\u001b[282C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\r\n\u001b[317X\u001b[317C\u001b[1;36H\u001b]0;Administrator: C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\u0007\u001b[?25h\u001b[?25l\u001b[?25h\u001b[?25l[A\u001b[?25h\u001b[?25l\u001b[?25h\u001b[?25l\u001b[1;36H[A[A\u001b[?25h\u001b[?25l\u001b[?25h\u001b[?25l\u001b[1;36H[A[A[A\u001b[?25h\u001b[?25l\u001b[?25h\u001b[?25l\u001b[1;36H[A[A[A[A\u001b[?25h"```

**Comment by alex-hempel** [comment]
I have the same issue.

**Comment by brc-dd** [comment]
I also have the same issue. Terminus is passing the ASCII escape sequences instead of key events to shell (elevated privileges, in my case) making the shell unable to interpret the signal. It is not only with the arrow keys, but also with the modifier keys (CTRL, ALT, SHIFT, SUPER).

**Comment by Eugeny** [comment]
Duplicate of #691
