### ISSUE TITLE
[FEATURE-REQ] Quck Commands

### ISSUE THREAD

**Issue by mishoboss** [Eugeny/terminus#2423]
Having a list of predefined commands users can choose from to execute. CRUD page in Settings, the same way we have for SSH (with Groups).

There was a quick-cmds plugin that is no longer supported, but it was extremely useful. IMHO such a feature deserves first citizen love & support.

**Comment by sburkett** [comment]
I second this! A lot of times I open several connections to the same server, and want to issue a command to cd to a certain location, run a script there, etc. So handy ... really miss the ability to issue commands to multiple sessions! In fact, I have sessions open to usually 3 or 4 servers, several tabs for each. Would be awesome to be able to send commands to ALL sessions, or just ones to a certain server, or even server groups. +1 +1 +1

**Comment by AlphaS-code** [comment]
Quick commands has in plugins, but didnt work well. (You can add command, but cant use)

**Comment by Eugeny** [comment]
Fixed in `quick-cmds` 1.2.0
