### ISSUE TITLE
Automatic updater closing terminus AND installer

### ISSUE THREAD

**Issue by norweeg** [Eugeny/terminus#2436]
When running an update from the automatic updater, selecting to close terminus while a terminus window is open also closes the installer, aborting the upgrade process, however, if you begin the upgrade process but close the terminus window before clicking OK to close terminus, the installer completes the upgrade successfully

**Comment by Nuclearfossil** [comment]
Yeah, this is really annoying. Any way to fix this soon?

**Comment by barbados-clemens** [comment]
Just wanting to say same thing here. But I don't notice this behavior on MacOS. I have the same plugins and version as windows, platform is MacOS Catalina 10.15.4.

Here the Win info as well.
Version: 1.0.112
Platform: win32 10.0.18363
Plugins: clickable-links, scrollbar
