### ISSUE TITLE
Stuck on Loading

### ISSUE THREAD

**Issue by vikas5914** [Eugeny/terminus#244]
![screenshot_2](https://user-images.githubusercontent.com/7912297/33206446-43af4e2e-d130-11e7-85cb-76c2d15c762d.png)

had the same problem with prebuild windows binary. (alpha 36)  

OS: Windows 10 17046 x64 

Console log: 

Running in debug mode
(anonymous) @ bundle.js:1426
plugins.ts:112 Plugin terminus-community-color-schemes already exists, overriding
plugins.ts:112 Plugin terminus-core already exists, overriding
plugins.ts:112 Plugin terminus-settings already exists, overriding
plugins.ts:112 Plugin terminus-community-color-schemes already exists, overriding
plugins.ts:112 Plugin terminus-core already exists, overriding
plugins.ts:112 Plugin terminus-plugin-manager already exists, overriding
plugins.ts:112 Plugin terminus-settings already exists, overriding
plugins.ts:112 Plugin terminus-terminal already exists, overriding
entry.ts:37 Starting with plugins: [Object, Object, Object, Object, Object, Object, Object, Object, Object]
plugins.ts:147 Loading clickable-links: C:\Users\vikas\AppData\Roaming\terminus\plugins\node_modules\terminus-clickable-links\dist\index.js
plugins.ts:147 Loading shell-selector: C:\Users\vikas\AppData\Roaming\terminus\plugins\node_modules\terminus-shell-selector\dist\index.js
plugins.ts:147 Loading theme-hype: C:\Users\vikas\AppData\Roaming\terminus\plugins\node_modules\terminus-theme-hype\dist\index.js
plugins.ts:147 Loading theme-windows10: C:\Users\vikas\AppData\Roaming\terminus\plugins\node_modules\terminus-theme-windows10\dist\index.js
plugins.ts:147 Loading community-color-schemes: C:\Users\vikas\Desktop\terminus\terminus-community-color-schemes\dist\index.js
plugins.ts:147 Loading core: C:\Users\vikas\Desktop\terminus\terminus-core\dist\index.js
plugins.ts:147 Loading plugin-manager: C:\Users\vikas\Desktop\terminus\terminus-plugin-manager\dist\index.js
plugins.ts:147 Loading settings: C:\Users\vikas\Desktop\terminus\terminus-settings\dist\index.js
plugins.ts:147 Loading terminal: C:\Users\vikas\Desktop\terminus\terminus-terminal\dist\index.js
C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:2965 Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("            <ng-template #scrollablePlaceholder></ng-template>
        </perfect-scrollbar>
        [WARNING ->]<template #nonScrollablePlaceholder [ngIf]="!scrollable"></template>
    "): ng:///AppModule/TabBodyComponent.html@4:8
Console.warn @ C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:2965
TemplateParser.parse @ C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\compiler\bundles\compiler.umd.js:12842
JitCompiler._compileTemplate @ C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\compiler\bundles\compiler.umd.js:26998
(anonymous) @ C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\compiler\bundles\compiler.umd.js:26918
JitCompiler._compileComponents @ C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\compiler\bundles\compiler.umd.js:26918
(anonymous) @ C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\compiler\bundles\compiler.umd.js:26805
then @ C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\compiler\bundles\compiler.umd.js:1714
JitCompiler._compileModuleAndComponents @ C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\compiler\bundles\compiler.umd.js:26804
JitCompiler.compileModuleAsync @ C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\compiler\bundles\compiler.umd.js:26733
PlatformRef_._bootstrapModuleWithZone @ C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:4567
PlatformRef_.bootstrapModule @ C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:4553
(anonymous) @ entry.ts:33
fulfilled @ bundle.js:1405
ZoneDelegate.invoke @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:391
Zone.run @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:141
(anonymous) @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:818
ZoneDelegate.invokeTask @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:424
Zone.runTask @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:191
drainMicroTaskQueue @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:584
ZoneTask.invoke @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:490
timer @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:1540
entry.ts:41 Angular bootstrapping error: Error: No provider for LogService!
    at injectionError (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:1201)
    at noProviderError (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:1239)
    at ReflectiveInjector_._throwOrNull (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:2681)
    at ReflectiveInjector_._getByKeyDefault (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:2720)
    at ReflectiveInjector_._getByKey (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:2652)
    at ReflectiveInjector_.get (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:2521)
    at resolveNgModuleDep (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:9505)
    at _callFactory (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:9580)
    at _createProviderInstance$1 (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:9519)
    at initNgModule (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:9470)
(anonymous) @ entry.ts:41
rejected @ bundle.js:1406
ZoneDelegate.invoke @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:391
Zone.run @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:141
(anonymous) @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:818
ZoneDelegate.invokeTask @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:424
Zone.runTask @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:191
drainMicroTaskQueue @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:584
ZoneTask.invoke @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:490
timer @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:1540
entry.ts:42 Trying safe mode
(anonymous) @ entry.ts:42
rejected @ bundle.js:1406
ZoneDelegate.invoke @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:391
Zone.run @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:141
(anonymous) @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:818
ZoneDelegate.invokeTask @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:424
Zone.runTask @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:191
drainMicroTaskQueue @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:584
ZoneTask.invoke @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:490
timer @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:1540
plugins.ts:147 Loading community-color-schemes: C:\Users\vikas\Desktop\terminus\terminus-community-color-schemes\dist\index.js
plugins.ts:147 Loading core: C:\Users\vikas\Desktop\terminus\terminus-core\dist\index.js
plugins.ts:147 Loading plugin-manager: C:\Users\vikas\Desktop\terminus\terminus-plugin-manager\dist\index.js
plugins.ts:147 Loading settings: C:\Users\vikas\Desktop\terminus\terminus-settings\dist\index.js
plugins.ts:147 Loading terminal: C:\Users\vikas\Desktop\terminus\terminus-terminal\dist\index.js
entry.ts:47 Bootstrap failed: Error: No provider for LogService!
    at injectionError (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:1201)
    at noProviderError (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:1239)
    at ReflectiveInjector_._throwOrNull (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:2681)
    at ReflectiveInjector_._getByKeyDefault (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:2720)
    at ReflectiveInjector_._getByKey (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:2652)
    at ReflectiveInjector_.get (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:2521)
    at resolveNgModuleDep (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:9505)
    at _callFactory (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:9580)
    at _createProviderInstance$1 (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:9519)
    at initNgModule (C:\Users\vikas\Desktop\terminus\app\node_modules\@angular\core\bundles\core.umd.js:9470)
(anonymous) @ entry.ts:47
rejected @ bundle.js:1406
ZoneDelegate.invoke @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:391
Zone.run @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:141
(anonymous) @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:818
ZoneDelegate.invokeTask @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:424
Zone.runTask @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:191
drainMicroTaskQueue @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:584
ZoneTask.invoke @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:490
timer @ C:\Users\vikas\Desktop\terminus\app\node_modules\zone.js\dist\zone.js:1540

**Comment by Eugeny** [comment]
Could you please capture the traceback with the prebuilt binary?

**Comment by diegopego** [comment]
I have this error too. How can I capture the traceback?
windows 7 sp1 x64
I'm a software developer, but I don't know much about JS. Coming from Delphi and xBase.
But I can help a lot if you tell me what to do. (no need for teaching)

**Comment by Eugeny** [comment]
If you press F12 or Ctrl-Shift-I during startup, it will open the devtools pane (seen in the screenshot above). From there, you can copy the console output.

**Comment by diegopego** [comment]
It freezes and those keys do not bring the dev panel.

Em sex, 4 de mai de 2018 10:30, Eugene Pankov <notifications@github.com>
escreveu:

**Comment by diegopego** [comment]
It freezes and those keys do not bring the dev panel. still happening as of today.

**Comment by QWp6t** [comment]
I'm experiencing [a similar issue](https://github.com/Eugeny/terminus/issues/530) that's possibly related, but I'm only having problems with the latest version of Terminus. Previous versions until now have worked fine leading me to believe that despite similar symptoms, my issue is likely the result of something different.

**Comment by shacal** [comment]
Just updated, same issue.
Windows 10

**Comment by lawrencehlee** [comment]
I'm getting the same issue on Windows 7 SP1, Terminus 1.0.69. It started happening after I added a new account-level environment variable called "DEV" - once I removed that environment variable, Terminus loaded properly again.

**Comment by Eugeny** [comment]
@lawrencehlee a very good catch! The `DEV` envvar switches Terminus into 'run from a source checkout mode'. I'll change the name to something unique

**Comment by Eugeny** [comment]
@lawrencehlee this should be fixed now
