### ISSUE TITLE
Colored Tab Not working

### ISSUE THREAD

**Issue by yelled1** [Eugeny/terminus#2448]
I have set the colors below, but it's not showing up on the tab. Not a biggie, but if forgot to set something up or need to get plugin then pls tell me.

![image](https://user-images.githubusercontent.com/2314710/79876940-a645c480-83b9-11ea-970f-45e517b06527.png)

![image](https://user-images.githubusercontent.com/2314710/79877024-bd84b200-83b9-11ea-91f1-5f4baa9a7df6.png)

I have following Plugin's installed, but willing to let go of them if it gives me color tabs.
![image](https://user-images.githubusercontent.com/2314710/79877587-67643e80-83ba-11ea-9c26-756f7dc60cc7.png)
Thanks,

**Comment by Binbinfx** [comment]
Same issue for me. 
Version 1.0.108. (Windows) 
I tried installed and portable version. 
The tab color works if we set manually by right click on it. 

Thank you.
