### ISSUE TITLE
stuck on start after upgrading to alpha37

### ISSUE THREAD

**Issue by princemaple** [Eugeny/terminus#247]
Stuck on this:
![image](https://user-images.githubusercontent.com/1329716/33289017-3597dac4-d412-11e7-92e1-4a1e5d97278c.png)

Win10

I've tried removing all terminus files and re-install. Same.

Got back to alpha36 for now.

**Comment by Eugeny** [comment]
Please grab the log from %APPDATA%/Terminus

**Comment by princemaple** [comment]
Hi @Eugeny thanks for the quick reply. I see no logs being written out.

This is with a clean install
![image](https://user-images.githubusercontent.com/1329716/33289916-2c83da0c-d415-11e7-84e1-c88ec03a7276.png)

When upgrading from alpha36 to a37, I do see the log file, but the only content in it is alpha36 related.

**Comment by princemaple** [comment]
What does the lockfile do? It's 0KB and goes away when I terminate the terminus process.

**Comment by danielfparker** [comment]
I have the same issue on Ubuntu.. Where can I find the log?

**Comment by princemaple** [comment]
https://github.com/Eugeny/terminus/commit/d9e337aa460b619f87cf4b30f403f173348f98cb does seem to fix it. I've got the installer from https://ci.appveyor.com/project/Eugeny/terminus/build/233/artifacts and it works for me. I don't know about linux builds though. https://github.com/Eugeny/terminus/releases nothing is there for the re-tagged a.37

**Comment by Eugeny** [comment]
I've re-published Alpha 37 here with the newer builds. Thanks for testing!
