### ISSUE TITLE
Scroll bar plugin doesnt seem to work

### ISSUE THREAD

**Issue by Atul28** [Eugeny/terminus#2472]
Version: 1.0.108
Platform: linux 5.4.0-26-generic
Plugins: relaxed-theme, theme-hype

I have installed the plugin using below command and done seem to see the scroll bar on the terminus 
root@ubuntu-box:~# npm i terminus-scrollbar
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

+ terminus-scrollbar@0.2.1
added 1 package from 1 contributor and audited 1 package in 1.829s
found 0 vulnerabilities

root@ubuntu-box:~# npm list | grep -i term
`-- terminus-scrollbar@0.2.1

**Comment by Eugeny** [comment]
Plugins should be installed via Terminus itself, through Settings -> Plugins.

**Comment by Atul28** [comment]
Hi @Eugeny , Thank you for the prompt response. I had tried the click path mentioned too, i updated the version to 109 today and still not able to add the scroll bar. 

Any way i can send you some logs for debugging ?

**Comment by Eugeny** [comment]
Is your frontend set to xterm? (Settings -> Appearance)

**Comment by Atul28** [comment]
That did the trick! I had it set to hterm, stay safe and thank you so much!!

**Comment by Eugeny** [comment]
Anytime. hterm is the old and deprecated frontend.
