### ISSUE TITLE
ssh not picking up my private key

### ISSUE THREAD

**Issue by princemaple** [Eugeny/terminus#248]
It asks me to enter password

Am I missing something?
What's the use case / expected behavior?

Thanks for the new functionality! ❤️ 

Win10 Terminus a.37

**Comment by Eugeny** [comment]
Have you selected the key in the connection properties? If not, is it your default PuTTY / Cygwin SSH / Git SSH key? Where is it located?

**Comment by princemaple** [comment]
It only asked me to select a folder. I couldn't select a file. That would be the problem, wouldn't it?

**Comment by Eugeny** [comment]
Should be fixed in this build: https://ci.appveyor.com/project/Eugeny/terminus/build/234/artifacts

**Comment by princemaple** [comment]
Yes it's fixed in the linked build. :)
