### ISSUE TITLE
How does Terminus's Windows taskbar integration work?

### ISSUE THREAD

**Issue by Nevrage** [Eugeny/terminus#2482]
Hello,

Sorry to drop an issue for something that isn't really one, but I couldn't find any information about it.

I was wondering how Terminus gets the progress to be displayed as a green fill in the Windows taskbar.
Is this baked in and based on the terminal output? Could an application make sure to be a compliant for this to be picked up?
Is it specific to Terminus or is it a standard?

Thanks!

**Comment by Eugeny** [comment]
Hi, this is a Terminus-specific hack. It's listening for percentages in the terminal output that match `​/​(​^​|​[​^​\d​]​)(​\d​+​(​\.​\d​+​)​?​)%(​[​^​\d​]​|​$​)​/​` and as long as an app is writing a string like this within every stdout/stderr flush, the progress bar will stay on
