### ISSUE TITLE
Unable to get files using rz command

### ISSUE THREAD

**Issue by xiaojinxin3** [Eugeny/terminus#2485]
Version: 1.0.106
Platform: win32 6.3.9600
Plugins: none

When I used "rz" command to get files, I got nothing.

**Comment by Eugeny** [comment]
Please upgrade to the latest release.

**Comment by xiaojinxin3** [comment]
Yeah,ok. I'll try later. Thanks a lot




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eugene"<notifications@github.com&gt;; 
发送时间: 2020年4月28日(星期二) 下午2:58
收件人: "Eugeny/terminus"<terminus@noreply.github.com&gt;; 
抄送: "◎闪电风暴☆"<499856090@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Eugeny/terminus] Unable to get files using rz command (#2485)





 
Please upgrade to the latest release.
