### ISSUE TITLE
xterm-256color support

### ISSUE THREAD

**Issue by timvisee** [Eugeny/terminus#249]
I'm using terminals with rendering mode `xterm-256color` enabled (`export TERM=xterm-256color`) for proper color support with themes in my configuration. I've configured tools like [Vim](https://github.com/vim/vim) and [tmux](https://github.com/tmux/tmux) to use these color types to nicely theme my terminal. On some other terminal emulators I've installed the `base16-tomorrow-night` color scheme as my preferred scheme. I'm usually SSH'ing into other machines that have this configuration set.

Terminus does not seem to support this color mode at this time. Instead, colors are rendered weirdly, even when selecting the built-in `Tomorrow Night` theme (as I think this is the exact same scheme). Backgrounds appear weird, colors are inconsistent, and so on. I'll post some screenshots below to better explain the color problems.

I could not find anything about `xterm-256color` with a quick search, and I didn't find any similar issue on GitHub. Therefore I'm posting this issue.

## Screenshots
Here are some screenshots of a random project in Vim, to show the issues I'm having regarding terminal colors.

This is what the colors should look like, in iTerm 2 on macOS (and there are quite a few other terminal emulators on Linux and macOS that render these colors perfectly fine):  
![Colors in iTerm 2](https://uploads.timvisee.com/public/terminus-colors-iterm.png)

This is what it currently looks like in terminus, with the `Tomorrow Night` theme enabled:  
![Colors in terminus](https://uploads.timvisee.com/public/terminus-colors-terminus.png)

This is what terminus settings I've used for the above screenshot:  
![Used terminus settings](https://uploads.timvisee.com/public/terminus-colors-settings.png)

## xterm-256color
So, as far as I can see, this is an issue with `xterm-256color` support in terminus.

Will this color mode be supported at any later stage? And/or is there a known bug causing these rendering issues?

Note: changing 'Terminal Background' from 'From Theme' to 'From Colors' does only slightly improve background rendering.

## Dotfiles
The dotfiles I'm using on my systems are located [here](https://github.com/timvisee/dotfiles), this might be useful to to see what color modes and configurations I'm using for Vim and tmux.

**Comment by tnguyen14** [comment]
@timvisee Please update to the latest version (Alpha 54) and try again. This should be fixed by 8aff33d59c3d75a12321425388a27041af7d55a9

**Comment by timvisee** [comment]
> @timvisee Please update to the latest version (Alpha 54) and try again. This should be fixed by [8aff33d](https://github.com/Eugeny/terminus/commit/8aff33d59c3d75a12321425388a27041af7d55a9)

Sorry for taking so long to respond.

Rendering `xterm-256color` colors is indeed much better now. Thanks a lot for this! I'll close this issue now.

**Comment by AxelRHD** [comment]
How can I enable the xterm-256?
