### ISSUE TITLE
Is it possible to add user-defined baud rate function

### ISSUE THREAD

**Issue by xwliu** [Eugeny/terminus#2490]
Is it possible to add user-defined baud rate function

**Comment by Eugeny** [comment]
You can change a connection's baud rate in the config file

**Comment by tionebrr** [comment]
It would be nice to have a way to set an arbitrary baudrate during the connection instanciation... Could this issue be reopened?

**Comment by shikaiguo** [comment]
Yes, I'm also looking forward to being able to customize baudrate in connection config, and whether Is it possible to refer to xshell

**Comment by tionebrr** [comment]
Hello @Eugeny . Closed because implemented (for a future release) or not a priority/don't want right now?

**Comment by Eugeny** [comment]
I've implemented it. See the linked commit.

**Comment by tionebrr** [comment]
Thank you so much. I can say goodby to putty now :)
