### ISSUE TITLE
How to Copy Text from Terminus

### ISSUE THREAD

**Issue by valeryan** [Eugeny/terminus#25]
You can paste text into terminus using `Shift+Ins` but How do you copy text from terminus? I thing the traditional hot key is `Ctrl+Ins` to copy but when I hit Ctrl and the Insert button terminus shows the characters `~5` at the prompt instead of coping the highlighted text. Is there some way to copy text in terminus?

Environment: Windows 10, Bash for Windows. Alpha 15

P.S. Terminus is awesome keep of the amazing work.

**Comment by Eugeny** [comment]
On Windows & Linux, use `Ctrl-Shift-C` to copy and `Ctrl-Shift-V` to paste.

**Comment by sunshineYPH** [comment]
Auto copy selected text :
Settings - Terminal menu on left - enable "Copy on select "

**Comment by mariusa** [comment]
Doesn't work when sshed on a remote server, only locally.

**Comment by chheiss** [comment]
# open evcc at http://evcc.local:7070
network:
  schema: http
  host: evcc.local # .local suffix announces the hostname on MDNS
  port: 7070

log: debug
levels:
  cache: error

# unique installation id
plant: xxxxxxxxxxxxxxxxxxxxxxxxxx

interval: 30s # control cycle interval

meters:
- type: template
  template: sma-home-manager 
  usage: grid  
  host: 192.168.1.234  
  interface: eth0  
  name: grid1
- type: template
  template: sma-inverter-modbus 
  id: 3  
  host: 192.168.1.18  
  port: 502  
  usage: pv  
  modbus: tcpip  
  name: pv2
- type: template
  template: sma-inverter-modbus 
  id: 3  
  host: 192.168.1.180  
  port: 502  
  usage: pv  
  modbus: tcpip  
  name: pv3
- type: template
  template: sma-inverter-modbus 
  id: 3  
  host: 192.168.1.215  
  port: 502  
  usage: pv  
  modbus: tcpip  
  name: pv4
- type: template
  template: sma-sbs-modbus 
  id: 3  
  host: 192.168.1.221  
  port: 502  
  usage: battery  
  modbus: tcpip  
  capacity: 21  
  watchdog: 60s  
  chargepower: 4200  
  name: battery5

chargers:
- type: template
  template: tinkerforge-warp3 
  host: 192.168.1.194  
  port: 1883  
  topic: warp2/Wz6  
  timeout: 30s  
  name: wallbox6

loadpoints:
- title: Garage Warp
  charger: wallbox6
  mode: minpv

site:
  title: Home Garage
  meters:
    grid: grid1
    pv:
    - pv2
    - pv3
    - pv4
    battery:
    - battery5

hems:
  type: sma
  AllowControl: true 

tariffs:
  currency: EUR
  grid:
    type: fixed
    price: 0.28
  feedin:
    type: fixed
    price: 0.20  
  solar:
    - type: template
      template: forecast-solar
      lat: 48.1   #1527
      lon: 11.6   #6313
      dec: 12 # 0 = horizontal, 90 = vertikal
      kwp: 6
      az: -90
      #horizon: '30,0,70,0'
      dm: 0.5
      de: 0

    - type: template
      template: forecast-solare
      lat: 48.1
      lon: 11.6
      dec: 40 # 0 = horizontal, 90 = vertikal
      kwp: 6
      az: 0 # -180 = Norden, -90 = Osten, 0 = Süden, 90 = Westen, 180 = Norden
      #horizon: '0,0,20,0'
      dm: 0
      de: 0.5


  co2:
    type: template
    template: grünstromindex # example GrünstromIndex (Germany only)
    zip: 81927
