### ISSUE TITLE
Icon Is Missing

### ISSUE THREAD

**Issue by Naolador** [Eugeny/terminus#2502]
Version: 1.0.108
Platform: linux 5.3.0-51-generic
Plugins: none

Installed the latest Terminus on Ubuntu 19.10. After I launched Terminus, the app icon is a blank one on the tray.

See the screenshot below. After clicking on the app, a separate demon was launched with a blank icon.
![2020-05-19_15-14](https://user-images.githubusercontent.com/11061451/82280666-7fdc6e80-99e3-11ea-9e2d-669aeefe9f9d.png)

**Comment by Eugeny** [comment]
Should be already fixed

**Comment by gersonmdesouza** [comment]
Version: 1.0.136
Platform: elementary OS 5.1.7 Hera - Built on Ubuntu 18.04.4 LTS - Linux 5.4.0-71-generic - GTK 3.22.30)
Plugins: none

![Screenshot from 2021-04-14 01-02-06](https://user-images.githubusercontent.com/10407690/114652967-60b29380-9cbd-11eb-8086-bb34e67512d2.png)

Any idea on how to fix it?
