### ISSUE TITLE
Remote rejected opening a shell channel: Error: Unable to request a pseudo-terminal

### ISSUE THREAD

**Issue by StriveSt** [Eugeny/terminus#2508]
Version: 1.0.108
Platform: darwin 19.4.0
Plugins: none
Hello, I'm using the MAC system. When using SSH connections to connect to jumpserver, I reported this error，However, I can log in Using “ssh username @ jumpserver -p”，Where is the problem? Thank you for your reply

**Comment by StriveSt** [comment]
SSH connections is OK on Windows

**Comment by Eugeny** [comment]
This should be fixed by now - feel free to reopen if it's not - Terminus shouldn't request PTY from jump hosts anymore.
