### ISSUE TITLE
SSH Warn on close

### ISSUE THREAD

**Issue by Metal-Mighty** [Eugeny/terminus#2512]
Hi all !

I started using Terminus a lot since a few days (love it !) and one thing that annoys me is the lack of warning when closing a tab. I have unintentionnaly clicked on the tab close button so many times (including while extracting a 25GB tar file...) and it's getting a bit annoying.

I feel like adding a warn on close (maybe as an option?) might save some frustration amongst users !

**Comment by urbels** [comment]
Thank you for this! I did this accidentally by myself few times.
