### ISSUE TITLE
Switching tabs loses focus in the terminal

### ISSUE THREAD

**Issue by haydos-amber** [Eugeny/terminus#2525]
Version: 1.0.109
Platform: linux 5.3.0-51-generic
Plugins: none

After creating two tabs, switching between them will result in the focus being moved from the terminal to the navigation tab bar. Additionally closing one of the tabs will focus on the navigation bar instead of the remaining terminal.

How to reproduce:
1. Press `Ctrl`+`Shift`+`T` twice
2. Press `Alt`+`1` to navigate back to the first tab
3. Note that the terminal window does not have focus
4. Press `Tab` 4-5 times. Note that the "+" button is highlighted indicating that the focus is on the top bar

Additional scenarios
1. Press `Ctrl`+`Shift`+`T` twice
2. Press `Ctrl` + `D`
3. Note that the remaining terminal window does not have focus
4. Press `Tab` 2-3 times. Note that the "+" button is highlighted indicating that the focus is on the top bar

**Comment by pkmandke** [comment]
Facing the same issue..

**Comment by VJvaLbhYbfr** [comment]
Same problem here.

Additionally (although might not be related) upon restoring focus, ctrl+left/right doesn't jump words anymore, Ctrl+C doesn't pass sigterm to shell anymore etc.

**Comment by abassanini** [comment]
Same problem here as mentioned by @VJvaLbhYbfr 
Those keyboard combinations don't work till the focus is back with a mouse click in the terminal
