### ISSUE TITLE
for multi-instance, short cut  `ctrl`+`space`  conflits

### ISSUE THREAD

**Issue by dreamer2q** [Eugeny/terminus#2534]
When I opened another instance by mistake, the previous one hidden by short cut `ctrl`+`space` could not be triggered out any longer by this short cut. As a consequence, I had to terminate the previous one and lost all the `env`s I had set.

A suggestion is that providing an option to allow only one instance running since multi-tabs is supported.

**Comment by Eugeny** [comment]
This is fixed in the latest release.
