### ISSUE TITLE
Keyboard layout ignored for hotkeys

### ISSUE THREAD

**Issue by thenephie** [Eugeny/terminus#2544]
Version: 1.0.111
Platform: win32 10.0.18363
Plugins: clickable-links, quick-cmds, relaxed-theme, scrollbar, theme-windows10

When setting and using hotkeys the windows keyboard layout seems to be ignored.
If a hotkey is set to Alt-A, i cannot use it with Alt-A ... I have to use Alt-Q. If i set the hotkey in de settings windows it also sets it to Alt-Q when i press Alt-A and vice-versa

It seems like it always act as if the keyboard layout i qwerty, while my windows keyboard layout is azerty. In other Terminus windows it works fine.

**Comment by PINPAL** [comment]
Can confirm, also experiencing this issue. It's very infuriating with Dvorak as the keys are in very different places to Qwerty.

**Comment by Eugeny** [comment]
I'm not familiar with how shortcuts are used in other Latin based languages - when pressing Ctrl-Z, are you using the physical Z key or the one where it is supposed to be on a US keyboard?

**Comment by Arro** [comment]
People who use Dvorak (like myself) press keys that are different that the letter printed on the keyboard.  For example, the key for "T" is actually the "K" button on the keyboard.  It seems that Terminus thinks that the "K" button on a keyboard is always for the letter K, but that's not true.  Anyway, launching the preferences and remapping was very weird for dvorak.... had to remap everything.  Would suggest Terminus use the letter the OS gives you, instead of the "key code" hard coded to that key.

**Comment by Eugeny** [comment]
@Arro just using the characters that the OS reports will prevent non-Latin keyboard users from using shortcuts at all. For my understanding - when using Dvorak, do you use the US-layout "C" for "Ctrl-C", or do you use the Dvorak-layout "C"?

**Comment by Arro** [comment]
@Eugeny 

So, sticking with my example of the hotkey for new tab.  

1. I want the hotkey "⌘T" to make new tab. 
2. I'm using Dvorak layout, so the "K" button on my keyboard is how I type "T" to my computer.
3. I remapped it and it looks like the screenshot below.  
4. I **sometimes** switch back to Qwerty.  
5. During those times, I would **expect** the hotkey the physical key "T" to make a new tab.  
6. However, it wouldn't be the case, it would stick with the physical key "K"
7. I feel hotkeys should be bound to the (changeable) keyboard layout, not the physical keys.
 
![Screen Shot 2021-01-21 at 2 22 49 PM](https://user-images.githubusercontent.com/180387/105293757-25d81c80-5bf4-11eb-96c0-28cfbb5ecaa4.png)

**Comment by aldopareja** [comment]
confirmed, is there some solution for now?
