### ISSUE TITLE
Background color is stuck as blue no matter what my color scheme has set

### ISSUE THREAD

**Issue by nathan-fiscaletti** [Eugeny/terminus#2555]
Version: 1.0.111
Platform: win32 10.0.18363
Plugins: none

![image](https://user-images.githubusercontent.com/1699763/81607865-986cd900-9392-11ea-82bd-23da2e8aa206.png)

![image](https://user-images.githubusercontent.com/1699763/81607888-a1f64100-9392-11ea-88f7-0a03102229cd.png)

I don't understand why i'm stuck with this dark blue color? I want it to be black.

**Comment by Eugeny** [comment]
Set "Terminal background" to "From color scheme" in the Appearance settings.
