### ISSUE TITLE
No reaction when i click 

### ISSUE THREAD

**Issue by FlameMida** [Eugeny/terminus#2580]
There is no reaction when I click something in the interface except new terminal

**Comment by Doctor-Who** [comment]
Version: 1.0.108
Platform: linux 5.4.39-1-MANJARO
Plugins: clickable-links, quick-cmds, scrollbar

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by FlameMida** [comment]
![image](https://user-images.githubusercontent.com/33086993/81935727-b00ec080-9623-11ea-8e23-dd8d8d4f6ae7.png)
this is the error when i click the github logo

**Comment by FlameMida** [comment]
![image](https://user-images.githubusercontent.com/33086993/81935977-067bff00-9624-11ea-926c-162f0f2cb61c.png)
the version is empty 
OS：MacOS 10.15.4
version: alpha111

**Comment by Doctor-Who** [comment]
alpha112 work like a charm, closed from a side
