### ISSUE TITLE
Feature: Copy full text of current buffer to clipboard

### ISSUE THREAD

**Issue by xropi** [Eugeny/terminus#2585]
It'd nice to see this feature with a configurable shortcut in a terminal program.
It is sometimes needed to paste the full text from terminal to an editor for further processing. (find / find and replace / etc)

**Comment by rocketnateynate** [comment]
I have an issue that may be related... If not I will open another issue..

When copying text from Termius on Mac, it seems to only copy the *visible* text.  (ie. if I run a command that scrolls a lot of text off the screen, and then try to copy that text, it appears to work however when pasting it only pastes what was visible on the Termius screen.

Is there a way to configure this?  Maddening when working with router configs / etc.  To the point of making me switch to another application to replace Termius.

**Comment by Eugeny** [comment]
Wrong repo
