### ISSUE TITLE
Context menu option does not open new tab

### ISSUE THREAD

**Issue by kirinnee** [Eugeny/terminus#2588]
With `Shell integration` enabled, the right-click context menus' `Open Terminus Here` does not open a new tab when Terminus is already open.

**Comment by daika7ana** [comment]
I'm having the same issue. One you hit `Open Terminus Here` the focus changes back to Terminus yet no tab opens. The Dev console also gives no errors. 

Version: 1.0.119
Platform: win32 10.0.19041
Plugins: clickable-links

**Comment by ColinEspinas** [comment]
Same issue here, kind of an important feature at that, can't really use terminus without that as the loss in productivity is big.

**Comment by Eugeny** [comment]
Fixed.
