### ISSUE TITLE
XSS Error in Ubuntu 20.04

### ISSUE THREAD

**Issue by anidotnet** [Eugeny/terminus#2589]
Version: 1.0.111
Platform: linux 5.4.0-29-generic
Plugins: altair, clickable-links, quick-cmds, relaxed-theme, scrollbar, theme-hype

XSS error message is always there in the title bar no matter what. It's kinda annoying, otherwise a wonderful product. :+1: 

![image](https://user-images.githubusercontent.com/696662/82151666-2c9adc80-987a-11ea-8e7e-48b995d6bd75.png)

**Comment by Eugeny** [comment]
Cause by the quick-cmds plugin
