### ISSUE TITLE
Shell Tab Title

### ISSUE THREAD

**Issue by cdhunt** [Eugeny/terminus#259]
Currently (alpha-36) I see no title text for Shell tabs. SSH tabs include the host address. It would be nice if the Shell tabs showed $PWD as the tab title, but just the Shell name would be helpful.

OS: Windows 10.0.15063
Shell: PowerShell 5.1.15063.674

_Mockup from editing the HTML in dev tools_
![Mockup](https://user-images.githubusercontent.com/114173/33909923-23d372d6-df5b-11e7-84c6-12bf14bc2ff6.png)

**Comment by cdhunt** [comment]
I don't know what the issue was yesterday, but Tab Titles are working as expected for me now.

**Comment by terryaney** [comment]
@cdhunt  Setting $PWD will update the tab name?  Would like to control via profile.sh1 powershell script or simply have it display the name of a tab I put in the Saved Profiles of the Shell settings.

**Comment by cdhunt** [comment]
It's been working as expected for me since 2017.

**Comment by terryaney** [comment]
Actually I misunderstood PWD.  I simply want the profile name to be the tab name.

![image](https://user-images.githubusercontent.com/6237247/54224990-b443c900-44c8-11e9-8291-29bed55f5af9.png)

That appears as:

![image](https://user-images.githubusercontent.com/6237247/54225025-c9b8f300-44c8-11e9-89c9-4d1449776d2e.png)

Where the path is C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe

Any idea why it simply doesn't show 'ESS Sites'?

**Comment by cdhunt** [comment]
I set the Title using https://github.com/Jaykul/PowerLine in my profile and it just works. I don't know how it's all wired up.
