### ISSUE TITLE
Right-click to close the session by mistake

### ISSUE THREAD

**Issue by ntsyanslovesky** [Eugeny/terminus#2599]
Version: 1.0.111
Platform: win32 10.0.19041
Plugins: none

Maybe my situation is only individual, but I think maybe other people have the same experience. When I right-click the session title bar, the right-click menu is displayed, but the first menu is closed. I accidentally closed the session many times. I hope there can be a way to avoid this situation.

**Comment by Lockszmith** [comment]
+1, until this is resolved, I can suggest what I did: I moved bars to the bottom. Close is now farthest away.
