### ISSUE TITLE
how to settings defaut width and height?

### ISSUE THREAD

**Issue by bsed** [Eugeny/terminus#26]

**Comment by Eugeny** [comment]
Terminus remembers its location, width & height after a restart.

**Comment by bsed** [comment]
![image](https://user-images.githubusercontent.com/10845087/27768492-975a78c4-5f47-11e7-9519-56ee567f06c7.png)

**Comment by bsed** [comment]
how to hidden dot ?

**Comment by Eugeny** [comment]
Looks like you have another terminal that's connected to this GNU Screen session.

**Comment by bsed** [comment]
i must need chsh -i /usr/local/bin/terminus ?

**Comment by OvermindDL1** [comment]
Wrong way, the issue is that you are using something like `screen` or `tmux` inside your shell (which is inside Terminus) and it is 'that' which is drawing the dots, not Terminus.

**Comment by bsed** [comment]
oh, thank you, this problem solve.
