### ISSUE TITLE
ZModem protocol only supported at SSH terminal window

### ISSUE THREAD

**Issue by zmapleshine** [Eugeny/terminus#2609]
Version: 1.0.111
Platform: win32 10.0.18363
Plugins: none

ZModem protocol only supported at SSH terminal window

when i open a new terminal and use ssh xxx command enter a remote host, use rz can't open a file transfer window . 

![image](https://user-images.githubusercontent.com/12667610/82523187-fac99480-9b5d-11ea-83ed-a557571982c3.png)

**Comment by Spinestars** [comment]
![image](https://user-images.githubusercontent.com/7272900/82772548-07a5fb00-9e72-11ea-8871-dfdb079e2e6e.png)
