### ISSUE TITLE
Issue with the windows bar

### ISSUE THREAD

**Issue by skibum1869** [Eugeny/terminus#2612]
Currently running Windows 10 and the portable version of the terminus terminal. after loading and enabling the three options the terminal reloaded to load the SSH manager and the bar went to the bottom.  It corrects its self when using the terminal but goes back to the bottom at the home page.

![terminus issue](https://user-images.githubusercontent.com/15605269/82624766-03938800-9ba9-11ea-8828-45e6f060b5b8.png)

![terminus terminal](https://user-images.githubusercontent.com/15605269/82624915-6ab13c80-9ba9-11ea-8398-f79c21d683d2.png)

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by skibum1869** [comment]
Closed as I could not duplicate the problem
