### ISSUE TITLE
Where can i locate my custom theme?

### ISSUE THREAD

**Issue by wormeyman** [Eugeny/terminus#263]
I am working on a ruby blue theme for terminus and when it is ready where can I find the file to contribute it. Also is there more documentation on what each of the numbered colors does?

![image](https://user-images.githubusercontent.com/1795016/34018995-718e63b4-e0e1-11e7-94b9-faefda6b6117.png)

**Comment by Eugeny** [comment]
The schemes are saved into `customColorSchemes` array in the config file (https://github.com/Eugeny/terminus/wiki/Config-file). 
The bundled color schemes are currently in the Xresources format, but I'm working on bundling some schemes in Terminus' own scheme format (the one your config file uses).
Numbered colors are the standard ANSI terminal 16-color palette - see http://tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html
