### ISSUE TITLE
Clicking on other tabs terminus doesnt hide

### ISSUE THREAD

**Issue by Haneefh** [Eugeny/terminus#2634]
Version: 1.0.111
Platform: win32 10.0.18362
Plugins: none

With terminus app running , when I click on the other apps terminus app doesnt hide. I have to minimise the terminus and open other
For ex in the image attached , with terminus app open if I click on the excel it opens in the background with terminus app in the foreground

![image](https://user-images.githubusercontent.com/31154779/82984190-402f0b80-a00f-11ea-9938-4399a68ac672.png)

**Comment by Eugeny** [comment]
You've set your window behaviour to "Dock". This makes it always-on-top and sets a specific size. Disable it if you want the "normal" behaviour.

**Comment by Haneefh** [comment]
thank You!
