### ISSUE TITLE
macOS window moves when tab is dragged

### ISSUE THREAD

**Issue by phuein** [Eugeny/terminus#2649]
Hi,

Every time I click to change tabs I get a bit of drag that moves the whole window - very noticeable when it's stretched over the screen (Windows style maximized.) This also doesn't let me move tabs around with the mouse, as other standard terminals do.

Thanks

EDIT: Seeing there are a lot of open issues and no response here, I'll help investigate this issue. Maybe it's related to how macOS handles the window with its current minimal config:
https://github.com/Eugeny/terminus/blob/master/app/lib/window.ts#L60

**Comment by Eugeny** [comment]
On macOS, tabs can only be dragged by their "number" area. This is a limitation of Electron itself.

**Comment by phuein** [comment]
> On macOS, tabs can only be dragged by their "number" area. This is a limitation of Electron itself.

Oh wow, that'd be a shame. Then how come VS Code on macOS can move tabs around without moving the window? It's Electron based, too.

**Comment by Eugeny** [comment]
VS Code has a separate "title bar" area whereas Terminus puts tabs in there.
