### ISSUE TITLE
Control + A doesnt go to start of line

### ISSUE THREAD

**Issue by cptx032** [Eugeny/terminus#266]
I try use the Ctrl + A to go to start of line (this doesn't works). Instead the cursor starts to blink in a weird way:
![asd](https://s13.postimg.org/cgvr7kjp3/GIFrecord_2017-12-20_145659.gif)

I dont install any plugin/package. I'm using Ubuntu 16.04 LTS x64

**Comment by csrgxtu** [comment]
to go to the start of the line use follow key:
```bash
ctrl+shift+a
```

**Comment by Eugeny** [comment]
Ctrl-A is used in multiple default shortcuts - have you removed those first?

**Comment by cptx032** [comment]
After I removed all default hotkeys, Ctrl+A goes to start of line. Thanks!
(anyway the weird blinking is...odd)
