### ISSUE TITLE
Missing reconnect option

### ISSUE THREAD

**Issue by jaques-sam** [Eugeny/terminus#2662]
When an SSH connection stopped and the tab is not closed, there is no option to click reconnect and continue working from the same tab. A new shell session should start without loosing the previous shell content.

**Comment by lpadula** [comment]
This is very necessary!

**Comment by jaques-sam** [comment]
What? Why is this closed without explanation? Is there an alternative? I'd like to know!

**Comment by Eugeny** [comment]
It's been closed because a fix has been committed. The reconnect button is now permanently enabled. You can give it a try with a nightly build.
