### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by Mystic8b** [Eugeny/terminus#2672]
Friends, tell me please, is it possible to make a bright theme with the effect of transparency? I, as many others are sure, use a light windows theme and the black terminal does not look at all stylish.

**Comment by Eugeny** [comment]
There's a light theme included with Terminus (Paper).

**Comment by Mystic8b** [comment]
No, I mean the white theme, so that acrylic transparency looks like in the system itself.

**Comment by sayomelu** [comment]
we just want a pure white theme

**Comment by Mystic8b** [comment]
Just use WinTerminal
