### ISSUE TITLE
How do I redirect www to https?

### ISSUE THREAD

**Issue by agplacid** [Eugeny/terminus#268]
Hi Eugeny, thank you for the unbelievable work you have done to bring us this brilliant piece of software. 
I have set up a website with ssl certificate and its working fine, my only problem is that when I try to access it by typing www.mydomain.com I get this "We can’t connect to the server at www.mydomain.com"
I tried to configure the site to redirect automatically to https when someone types www with the following code which I inserted into the advanced - custom configuration through the gui

server {
  listen       80;
  listen  [::]:80;
  server_name  www.mydomain.com;
  return       301 https://mydomain.com$request_uri;
}

But I still get the same message. Is there anyway you can point me in the right direction?
Thanks

**Comment by wormeyman** [comment]
Try asking your webhost.

**Comment by Eugeny** [comment]
I think you meant to ask this in the https://github.com/ajenti/ajenti repo.

**Comment by keiko233** [comment]
![image](https://github.com/Eugeny/tabby/assets/76520798/fb329a21-090e-45a6-841d-b87259fff882)

Reaplace your Authorization callback URL to `http://yourdomain.com/api/1/auth/social/complete/github/`.
Don't use https。
