### ISSUE TITLE
Significant lag on window dragging after Windows May 2020 Creators Update 

### ISSUE THREAD

**Issue by taupehat** [Eugeny/terminus#2687]
Unsure what happened but immediately after installing the CU I am experiencing significant delay in window repositioning - if I drag a Terminus window randomly around for a while and then release the mouse button I will see two mouse pointers: one still attached to the Terminus window (which is slowly moving around in whatever random order I dragged it) and the other the actual functional mouse pointer.

**Comment by taupehat** [comment]
Yep, the clip in #2693 is exactly like what I'm seeing.

**Comment by Eugeny** [comment]
Duplicate of #949
