### ISSUE TITLE
Connection manager BUG

### ISSUE THREAD

**Issue by UAnton** [Eugeny/terminus#270]
I have saved connections in Connection manager.
If I connect via Connection manager to server1 and try connect from server1 to server2 via ssh - session hungs and don't connect. Connections without Connection manager works fine!

P.S. Windows ver.

**Comment by zenanswer** [comment]
Reproduced on version 1.0.221, macos.

Steps:
1. loggin to ubuntu server A with tabby (imported from ssh config)
2. in this console, run ssh command for loging another ubuntu server B

Expect:
could got "debug2: KEX algorithms:" and "debug2: host key algorithms:" in ssh log.
should login ubuntu server B success

Actual result:
no "KEX algorithms" in ssh log (ssh -vvv xxx@yyy)
ssh command hung

SSH and SSHD version info
Server A:
SSHD: OpenSSH_8.9p1 Ubuntu-3ubuntu0.11, OpenSSL 3.0.2 15 Mar 2022
SSH: OpenSSH_8.9p1 Ubuntu-3ubuntu0.11, OpenSSL 3.0.2 15 Mar 2022
Server B:
SSHD: OpenSSH_8.2p1 Ubuntu-4ubuntu0.12, OpenSSL 1.1.1f  31 Mar 2020

If login server A with running ssh command in iTerm, and login server B in that console, no such issue.

**Comment by zenanswer** [comment]
> Reproduced on version 1.0.221, macos.
> 
> Steps:
> 
>     1. loggin to ubuntu server A with tabby (imported from ssh config)
> 
>     2. in this console, run ssh command for loging another ubuntu server B
> 
> 
> Expect: could got "debug2: KEX algorithms:" and "debug2: host key algorithms:" in ssh log. should login ubuntu server B success
> 
> Actual result: no "KEX algorithms" in ssh log (ssh -vvv xxx@yyy) ssh command hung
> 
> SSH and SSHD version info Server A: SSHD: OpenSSH_8.9p1 Ubuntu-3ubuntu0.11, OpenSSL 3.0.2 15 Mar 2022 SSH: OpenSSH_8.9p1 Ubuntu-3ubuntu0.11, OpenSSL 3.0.2 15 Mar 2022 Server B: SSHD: OpenSSH_8.2p1 Ubuntu-4ubuntu0.12, OpenSSL 1.1.1f 31 Mar 2020
> 
> If login server A with running ssh command in iTerm, and login server B in that console, no such issue.

I am not sure is that a bug or not. But I found a workaround for this issue, just recorded here, hoping it can help others.

workaround:
disable the ForwardAgent of server B in ~/.ssh/config file on the client PC.

`
Host x.x.x.x
  HostName xxx
  User xcwang
  ForwardAgent no
`
