### ISSUE TITLE
How to set home directory for Windows Subsystem for Linux (WSL)?

### ISSUE THREAD

**Issue by abalter** [Eugeny/terminus#271]
Version: 1.0.0-alpha.38
Platform: win32 10.0.16299

In the settings, I've tried the following options for Terminal>Bash on Window>Working Directory:

- `~`
- `/home/balter`

In both cases, the terminal does not open properly. If I leave that setting blank, then the terminal opens properly but drops me into `/mnt/c/Users/ariel` (my Windows home directory).

Note: "Bash on Window" should probably be (WSL) or at least make Window plural.

**Comment by abalter** [comment]
Well, there is an infinite number of workarounds in Linux. But WSL is going to be a huge use case for Terminus. MobaXTerm knows how to default to the WSL directory. It would be good if Terminus could too.

**Comment by Jule-** [comment]
FTR, this is problematic when you have some binaries present in the Windows environnement that can be reached in the WSL environnement.

For example take `yarn`. I have `yarn` installed with `scoop` on Windows and with `apt` on WSL:
In PowerShell
```powershell
C:\Users\jule> yarn global bin
C:\Users\jule\scoop\apps\yarn\current\bin
```
In Terminus
```bash
jule@Jule-PC:/mnt/c/Users/jule$ yarn global bin
/mnt/c/Users/jule/C:\Users\jule\scoop\apps\yarn\current/bin

jule@Jule-ZB:/mnt/c/Users/jule/dev$ cd ~

jule@Jule-ZB:~$ yarn global bin
/home/jule/.yarn/bin
```

And when you modify your `.bashrc` in order to have `yarn` binaries in the path like this:
```bash
export PATH="$(yarn global bin):$PATH"
```
Then when your `.bashrc` is executed in your Windows home directory you will have in your WSL path the first wrong scoop form (`/mnt/c/Users/jule/C:\Users\jule\scoop\apps\yarn\current/bin`) instead of the second one (`/home/jule/.yarn/bin`).

Indeed adding `cd ~` at the beginning of your `.bashrc` do the trick like @pinyin said. But it is not natural and putting `/home/jule` in Terminus working directory setting **breaks** the terminal. It is still **not desirable**.

**Comment by Eugeny** [comment]
The recent Terminus versions will let you pick a working directory inside WSL rootfs if you're using the "browse" button near the input field. Sorry for not responding in this ticket

**Comment by Jule-** [comment]
Ok I can confirm that whatever I put in working directory setting that is under `lxss` folder I end up with `/` as working directory.

**Comment by Jule-** [comment]
And I don't know if it is normal but I have installed last alpha.65 version from github and I still have:

![image](https://user-images.githubusercontent.com/9716736/50091501-dac8cf80-020b-11e9-9a00-1dd995770236.png)

**Comment by Eugeny** [comment]
On my Windows, WSL distros have their FS in `%HOME%\AppData\Local\Packages\[distro]\LocalState\rootfs`, and the user's home folder is located inside.

Please try following:
1. Install an additional WSL distro to see if it gets set up with a "proper" FS layout
2. Alternatively, try creating an empty home folder at `C:\Users\jule\AppData\Local\lxss\rootfs\home\jule` and see if setting it as CWD tricks WSL into doing the right thing.

**Comment by Eugeny** [comment]
@Jule- also, until we find the reason, the WSL folks suggest a workaround by invoking `wsl.exe ~` or `wsl.exe ~ -d <distro-name>` - which you can set up as a Profile in Terminus.

**Comment by Eugeny** [comment]
Ref: https://github.com/Microsoft/WSL/issues/1346

**Comment by IgnusG** [comment]
This started happening for me after the latest Alpha 78 release. Can't trace what is causing it though

**Comment by ruslanguns** [comment]
> wsl.exe ~

That work, however it breaks the right click opt for open folder, it forward you right to your ~ directory.

**Comment by floatingpurr** [comment]
> @Jule- also, until we find the reason, the WSL folks suggest a workaround by invoking `wsl.exe ~` or `wsl.exe ~ -d <distro-name>` - which you can set up as a Profile in Terminus.

Excuse me for the naive question: how can I set a custom profile this way?

**Comment by miyunda** [comment]
> > @Jule- also, until we find the reason, the WSL folks suggest a workaround by invoking `wsl.exe ~` or `wsl.exe ~ -d <distro-name>` - which you can set up as a Profile in Terminus.
> 
> Excuse me for the naive question: how can I set a custom profile this way?

![Jietu20191220-090029](https://user-images.githubusercontent.com/27171256/71221331-3dfdae00-2307-11ea-85a6-ca70a69e9ee4.jpg)
just add an argument.

**Comment by VVVVictorJ** [comment]
@Eugeny 
That works.But I found it's has another problem.I set the ubuntu 18.04 as default launching.
And I open a new terminal for ubuntu. It shown the ```/mnt/c/users/victor```.And I set the ubuntu as default launching. It turn back normal. It seems like the profile setting only works for the default launching.

**Comment by Eugeny** [comment]
Good news - WSL2 now supports setting any CWD when starting a shell.

- Make sure you're using a fresh nightly build that includes this fix
- If using a profile, add a `shell: wsl-Ubuntu` or similar to its config entry, or just recreate it.
- Set the working directory as `\\wsl$\Ubuntu\home\...`

**Comment by equiman** [comment]
> Good news - WSL2 now supports setting any CWD when starting a shell.

I'm just adding picture details, How to config that.

1. Get the path from file explorer
![image](https://user-images.githubusercontent.com/933393/222649578-c619af21-0d18-4b7d-92a2-62947a8842e0.png)

Copy from address bar
![image](https://user-images.githubusercontent.com/933393/222650073-e1734f67-caab-4a36-a630-743bac660e6c.png)

2. Setting the env variables and working directory
![image](https://user-images.githubusercontent.com/933393/222649959-faad2798-f02e-4404-822d-59b4345b8852.png)
