### ISSUE TITLE
Terminal closing automatically when I try to open it

### ISSUE THREAD

**Issue by sebajuffar** [Eugeny/terminus#2719]
I've updated Windows and now I can't get the terminal working. It was working fine before the update. I'm not able to see what it says but any time I hit "New Terminal" I see in the screen something like "Error:..." and the terminal closes really fast.

Version: 1.0.112
Platform: win32 10.0.19042
Plugins: none

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by sebajuffar** [comment]
It seems there was an issue with WSL2 itself, not Terminus.
If it helps anyone, I ran this and it worked again:
`$processes = Get-Process -Id (Get-NetUDPEndpoint -LocalPort 53).OwningProcess | Select-Object -ExpandProperty Id

ForEach ($process in $processes) {
    Stop-Process -ID $process -Force
}`

Source: https://github.com/microsoft/WSL/issues/4929#issuecomment-616383430
