### ISSUE TITLE
win10 open a "New admin tab" error codes, System language is Chinese

### ISSUE THREAD

**Issue by Xiaoxiao1990** [Eugeny/terminus#2733]
![微信图片_20200624091443](https://user-images.githubusercontent.com/13549234/85485560-933eb300-b5fb-11ea-9ccb-045058d61e13.png)

**Comment by THX1188** [comment]
Hi !
The Error-Message , on the screen was caused by entering some invalid PowerShell command. Could you try to start Windows Powershell directly (enter 'Windows Powershell' in serach tab and start) and retry the input, is the output the same (some chineese message), currently it looks not like an app issue.

I must admit the error-message on my PS is definitely longer.
but maybe chineese is much more compact :)

> PS C:\Users\QXXXXXX> ssssssssssssssssssssssssssssssssssss
> ssssssssssssssssssssssssssssssssssss : The term 'ssssssssssssssssssssssssssssssssssss' is not recognized as the name of a cmdlet,
> function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
> try again.
> At line:1 char:1
> + ssssssssssssssssssssssssssssssssssss
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (ssssssssssssssssssssssssssssssssssss:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>

**Comment by Xiaoxiao1990** [comment]
Thanks a lot for your response. May be I'm not describe the question details enough. I have do test again with your advice.
1. Open Windows Power Shell directly and compare with it open by "New admin tab", then execute "ls".

![1](https://user-images.githubusercontent.com/13549234/86204607-86d9cd80-bb9a-11ea-809e-13dd91c6278a.jpg)

2. The question are occured by open a tab with "New admin tab", either PS or cmd and git-bash.  If open tab with general user, it works fine.

![2](https://user-images.githubusercontent.com/13549234/86205548-bbe71f80-bb9c-11ea-9e4c-cd0c08c20c6e.jpg)

Here are my terminus version:
Version: 1.0.112
Platform: win32 10.0.18362
Plugins: none

**Comment by THX1188** [comment]
Now when I open a New Admin window a Non-Modal Dialog pops up to approve to enable the System Privileges
- The question now is, do you have system/admin privs as logged user? maybe that is the root cause, as this is the only 
difference to open a user - window.

**Comment by Xiaoxiao1990** [comment]
Yes, that's the problem. My logged user have no admin privs. When I start terminus by administrator, it's works fine. Thanks!
