### ISSUE TITLE
How can the terminal be uninstalled?

### ISSUE THREAD

**Issue by pranav-cs** [Eugeny/terminus#274]
I am unable to find it in the Program Files. 
OS : Windows 10

**Comment by Eugeny** [comment]
It's installed in the user's profile (APPDATA), but you can quickly remove it via the normal Windows Settings > Installed Apps

**Comment by mokeyjay** [comment]
@Eugeny Hello, when i uninstall Terminus from Installed Apps, the right click menu still exists
![](https://i.loli.net/2019/02/11/5c619690e3835.jpg)  
if i click it  
![](https://i.loli.net/2019/02/11/5c619690e6075.jpg)
means **can't find the program**  
how can i remove it ?

**Comment by mokeyjay** [comment]
I found it.
![image](https://user-images.githubusercontent.com/6757507/52644844-92cbdd80-2f1a-11e9-8d2d-9c74527cd817.png)

**Comment by nod0n** [comment]
Also see workaround from #1344
