### ISSUE TITLE
How to export SSH list

### ISSUE THREAD

**Issue by Kakoum** [Eugeny/terminus#2749]
Hello,

I don't know if this is the right place to ask. But is it possible to export SSH config ? (for another Terminus installation).

Thank you in advance.

**Comment by Eugeny** [comment]
You can copy your complete configuration from Settings -> Config file.

**Comment by Kakoum** [comment]
Perfect, tanks.

**Comment by yogithesymbian** [comment]
> Hello,
> 
> I don't know if this is the right place to ask. But is it possible to export SSH config ? (for another Terminus installation).
> 
> Thank you in advance.

its a premium or how ? i didnt see `settings -> config file`
devices:  mbpm1
