### ISSUE TITLE
Windows 10 - downlaod from tdoay - does show intro-Screen ...

### ISSUE THREAD

**Issue by THX1188** [Eugeny/terminus#2754]
and then nothing,  I am on the search for a new terminal app. maybe this is hte one.
specially the font rendering from putty and others is horrible
cheers
Thsx1188

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by THX1188** [comment]
It works with 1.0.112! I had downloaded some image like 1.0.113.nigh.0;
Very nice so far! Great handling!
Thanks!

**Comment by THX1188** [comment]
The right versions fixed it!
