### ISSUE TITLE
This software contains a malware, according to avast

### ISSUE THREAD

**Issue by elieobeid7** [Eugeny/terminus#277]
Windows 10: Avast latest  free version detected a virus related to a plugin used by this application. I'm going to uninstall it since you seem a busy man. When you remove the malware or when you reply to this issue by explaining the malware, I'll reinstall it, since it's an awesome terminal but I don't keep infected software on my PC.

![photo_2018-01-18_00-48-09](https://user-images.githubusercontent.com/660142/35071466-69f743b4-fbe9-11e7-95c8-ad48eb742522.jpg)

**Comment by Eugeny** [comment]
This is a heuristics false positive.

Report for this file: https://www.virustotal.com/#/file/81e2794607855f7851dd8c12376d60315b2e9db4ed537d8136401067785f3927/detection

Report for the 64 bit build from the same source: https://www.virustotal.com/#/file/cd2ea0c045de77252da1d413ce0c6c8614ec9d79493fb67fec5e8be4aa83b727/detection

Compare the file hash (SHA-256: `81e2794607855f7851dd8c12376d60315b2e9db4ed537d8136401067785f3927`) to make sure your file is identical to the official build.

**Comment by Eugeny** [comment]
This is likely related to this library being used to read and write credentials from/to the Windows Credential Store by the `terminus-ssh` plugin.

**Comment by princemaple** [comment]
It's not very nice to quickly assume that the author is attaching malware in the distribution. At least verify it first before you make such a "threat".

**Comment by elieobeid7** [comment]
I did not assume anything i just said Avast and avg  and apparently a third company According to virus total say it's malware.


@Eugeny im using 64 build and got the malware, don't know why avast shows a different result on virus total
