### ISSUE TITLE
[Feature request] Support multiple instances

### ISSUE THREAD

**Issue by hakbra** [Eugeny/terminus#278]
I see that multiple instancus is currently not possible, but it is the only feature I am missing from Terminus at the moment. Are there any technical reasons it is not possible now?

**Comment by metastableB** [comment]
+1 

It seems you can have multiple windows by `Ctrl + shift + n` , but all of them seem to map to the same instance. Closing one, closes all.

**Comment by Eugeny** [comment]
Duplicate of #170
