### ISSUE TITLE
command line option to start and connect to a host

### ISSUE THREAD

**Issue by russellliss** [Eugeny/terminus#2785]
The one feature I feel this is missing is the ability to call it from the command line with a username, host, password and port.  I use KeePass to store my passwords, and so having it launch terminus with those details would be very useful.

For example: terminus.exe ssh user@host:port password

**Comment by rabauss** [comment]
Is there any workaround with the "run" command? 
I cannot start any command with the cli run 👎 

I could also live with the format: terminus.exe run "ssh user:password@host:port"

**Comment by Eugeny** [comment]
The new commands are:
```
  terminus connect-ssh [connectionName]     open a tab for a saved SSH
                                            connection
  terminus connect-serial [connectionName]  open a tab for a saved serial
                                            connection
```
