### ISSUE TITLE
Terminus doesnt open terminal tab

### ISSUE THREAD

**Issue by ssalguero** [Eugeny/terminus#279]
Version: 1.0.0-alpha.38
Platform: win32 6.1.7600

Its no resoponding when I click on new terminal, aditionally, when click on Terminal on the Settings Menú, Shows while 1 second and then dissapear all and shows like that:

![image](https://user-images.githubusercontent.com/15388664/35168972-cf6df202-fd28-11e7-83cf-40cf96c5b10c.png)

I love this terminal, but.. :(

**Comment by bigkahuna1uk** [comment]
I see a different behaviour. 

- Terminus opens you get the settings tab
- If I hit Cmd-N then I get a new terminal tab
- I would expect if I hit Cmd-N again I would get a new terminal but none opens. 
- I have to go back to settings tab and then Cmd-N works again and opens another tab. 

I installed terminus from brew: 

- version 1.0.0-alpha.23 (1.0.0-alpha.23.137)
- Mac OS X High Sierra 10.13.3 (17D102)

This needs to be fixed as it's counter to what you expect to opening new tabs compared to say iTerm.  For me this is a blocker for usage and I'll go back to another terminal until this is fixed. 

Cheers.
