### ISSUE TITLE
No terminal available. "New Terminal" or "New Terminal with Profile" buttons does nothing

### ISSUE THREAD

**Issue by TheDatadrainer** [Eugeny/terminus#2795]
Version: 1.0.112
Platform: win32 10.0.18363
Plugins: none

The program starts with no terminal opened and it is impossible to create one using "New Terminal" or "New Terminal with Profile". The others buttons works.
I tried to debug and an error occurs several times => "TypeError: Cannot read property 'value' of undefined" in the file core.umd.js at line 4302| console.error.apply(console, __spread(values));

Then there is a lot of warnings telling "DevTools failed to parse SourceMap" on different .js.map files. That can be not related to the problem.

Maybe the program has a compatibility issue with something installed on my system as it works correctly on an older Windows 7 machine. But maybe it is a compatibility issue with my version of Windows 10 64-bit (1909 version 10.0.18363.959). I hope you will be able to do something about that and help me to make it work.

Thank you.

Regards.

**Comment by Eugeny** [comment]
Please try the latest nightly build - this has likely been already fixed.

**Comment by TheDatadrainer** [comment]
> 
> 
> Please try the latest nightly build - this has likely been already fixed.

Ok, Indeed with version 0.113 all is in order. Thank you for your fast answer and for making this software ;)
