### ISSUE TITLE
In splash screen it says SafeValue must use

### ISSUE THREAD

**Issue by ghgymo** [Eugeny/terminus#2797]
Version: 1.0.113
Platform: darwin 19.5.0
Plugins: altair, quick-cmds, relaxed-theme, save-output, theme-hype, title-control

I've attached a screen shot of what I'm seeing.  Don't know why this started to appear.  I was using it for a couple of months and it started to appear.

![image](https://user-images.githubusercontent.com/30731478/87859284-fb826b00-c901-11ea-8726-981f139fa6ac.png)

**Comment by CLUB777ONE** [comment]
same problem

**Comment by Eugeny** [comment]
The plugin has been abandoned by its author and wasn't updated in a while.
