### ISSUE TITLE
SSH Warn on close - make optional setting (global or per ssh entry)

### ISSUE THREAD

**Issue by ThomasHeliase** [Eugeny/terminus#2801]
Relates to [https://github.com/Eugeny/terminus/issues/2512](https://github.com/Eugeny/terminus/issues/2512)

Now that we are warned and need to confirm every disconnect, it is laborious to close multiple warning prompts (personally, I roll through most of my working tabs with Ctrl-D once I've finished a bunch of sessions for the day..., found it smoother before this feature)

I agree it's necessary feature - and ideally I'd like to be able to set `"Warn on disconnect"` per SSH entry - but for now, allowing a global `"Warn on disconnect: true/false"` in the terminal or ssh config would be great.

**Comment by Novezeil** [comment]
+1

**Comment by Lockszmith** [comment]
Both suggestion would be awesome.
1. A global prompt
2. A configuration per connection - with the default begin inherited from a global 'default config'

**Comment by Eugeny** [comment]
Added a UI option to SSH settings. You can also override it (`warnOnClose`) for individual connections through the config file.
