### ISSUE TITLE
Support PPK SSH Keys with Passphrase

### ISSUE THREAD

**Issue by Simsch** [Eugeny/terminus#281]
Hello,

currently I can not use SSH Keys with passphrases. There is no way to enter the passphrase in the connections manager or in a separate popup for a saved connection.

None the less awsome project!

**Comment by Eugeny** [comment]
@Simsch the app should ask you for the passphrase during connection, isn't this the case?

**Comment by Simsch** [comment]
@Eugeny sorry for the late answer. I got the problem right now. I have selected the ppk Key which is not working. Selecting the id_rsa file is working fine and I am asked for the key.

So this bug is not a bug anymore. Thanks!

**Comment by kamkovvv** [comment]
Sorry, just reviewed the thread, and converted ppk to rsa. Now it's ok.

**Comment by Eugeny** [comment]
Let's add PPK support, shall we?
