### ISSUE TITLE
Font Colors All The FG Color

### ISSUE THREAD

**Issue by Mynameisreily** [Eugeny/terminus#2818]
I just downloaded this and for some reason, all the font colors are the same as the FG color. I have tried multiple fonts, reinstalling and looking through settings. Maybe I'm missing something really obvious since I'm new?

<img width="1080" alt="Screen Shot 2020-07-24 at 11 06 18 PM" src="https://user-images.githubusercontent.com/26028598/88447560-841d7180-ce02-11ea-8e09-810620a32749.png">
<img width="1080" alt="Screen Shot 2020-07-24 at 11 06 07 PM" src="https://user-images.githubusercontent.com/26028598/88447562-85e73500-ce02-11ea-90ae-a46253d080ac.png">

**Comment by Eugeny** [comment]
This means your `ls` isn't printing in color. Try `ls --color`.
