### ISSUE TITLE
Could not connect: Error: Timed out while waiting for handshake

### ISSUE THREAD

**Issue by Novezeil** [Eugeny/terminus#282]
**Environment:** Windows 10 Enterprise 1709 16299.125
**Version:** 1.0.0-alpha.39

**Issue Description:**
* SSH connection could not established with message:
`Could not connect: Error: Timed out while waiting for handshake`.
* SSH server is configured to a custom port (acknowledged the feature was introduced in `1.0.0-alpha.39`) and set to login-by-key only.
* Key is in default .ppk format generated by putty.
* SSH connection can be established by putty with exact same key file.
* Debug console only shows `loaded private key from [path]` with no more information.
* For testing connection without key, password prompt will show up. Enter random password will also cause the error message.

**Comment by VaultVulp** [comment]
Hi.
This probably could be fixed by merging https://github.com/Eugeny/terminus/pull/285
Anyway, you can fix this problem manually.

- Open the configuration file: `c:\Users\<USER>\AppData\Roaming\terminus\config.yaml`
- Go to `ssh/connections` block 
- Set the valid value for `port` key

**Comment by Eugeny** [comment]
@Novezeil could you please try out @VaultVulp 's manual fix?

**Comment by Novezeil** [comment]
@Eugeny Yes that works.

**Comment by Eugeny** [comment]
Thanks. Meanwhile Alpha 40 fixes the issue for good.
