### ISSUE TITLE
Update is not working on Windows

### ISSUE THREAD

**Issue by gaston-senac** [Eugeny/terminus#2835]
Version: 1.0.112
Platform: win32 10.0.17134
Plugins: none

**Comment by jraller** [comment]
Version 113 also fails to complete an upgrade. It shows the present icon in cyan in the toolbar, and when clicked that shows the dialog that says "Installing the update will close all tabs and restart Terminus" with an "Update" button, but when pressed the dialog goes away and nothing happens. Downloading a more recent installer and running it does allow for an upgrade.

My copy is installed only for a single user.

**Comment by plinkpaste** [comment]
I started to notice this too, and then I ran Terminus with elevated privileges. Clicked "Update" on the dialog and nothing happened, but then around 2-3 minutes later the setup window appeared.
