### ISSUE TITLE
Can't open settings

### ISSUE THREAD

**Issue by compliment** [Eugeny/terminus#286]
Version: 1.0.0-alpha.39
Platform: win32 10.0.16299

All settings buttons are unresponsive

**Comment by Eugeny** [comment]
Please post the log from the Devtools Console

**Comment by compliment** [comment]
> Devtools Console

Can't access that too, maybe it's just me.

**Comment by Eugeny** [comment]
Try pressing Ctrl-Shift-I or starting Terminus with a `--debug` flag
