### ISSUE TITLE
Don't open Settings page by default?

### ISSUE THREAD

**Issue by FinlayDaG33k** [Eugeny/terminus#287]
Hii there,

I'm using Terminus as my go-to terminal emulator on Linux, however, I tend to be annoyed by the fact that it automatically opens the `settings` tab in the background on startup.
Is there a way I could disable this?

Cheers

**Comment by Eugeny** [comment]
Hi, the Settings tab should only open if it was open the last time you closed the terminal.

**Comment by FinlayDaG33k** [comment]
Ah I see, it sometimes doesn't work as intended, but it might be that it doesn't play nice with i3wm.
Though it would be nice to have a little toggle for it in the settings (oh the irony) to circumvent issues like these.

**Comment by Eugeny** [comment]
Basically, the terminal remembers the last pages open (although actual terminal tabs are remembered only if one of the persistence engines is enabled), and tries to recover them when started again. Likely, you just have a settings tab open at the time of closure.
