### ISSUE TITLE
Strange but, git commands like pull/push stop working since 115

### ISSUE THREAD

**Issue by leocreo** [Eugeny/terminus#2872]
Version: 1.0.116
Platform: win32 10.0.19042
Plugins: relaxed-theme

**Comment by Sendoo** [comment]
I have the same thing, rolled back to version 114

**Comment by leocreo** [comment]
Yes i did the same, but Terminus updates automatically in background and then comes 116 again!

**Comment by Sendoo** [comment]
> Yes i did the same, but Terminus updates automatically in background and then comes 116 again!

In the settings, you can turn off automatic updates.

**Comment by leocreo** [comment]
You are right, nice tip!! Thanks!! 
I will wait for a full solution to the issue then.

**Comment by Eugeny** [comment]
Duplicate of #2868
