### ISSUE TITLE
Dragging Terminus Window is Delayed

### ISSUE THREAD

**Issue by darthsiderius** [Eugeny/terminus#2883]
Version: 1.0.116
Platform: win32 10.0.19041
Plugins: none

Just download terminus on my new machine, using ubuntu wsl with windows. When I try to drag the terminus window, it is delayed to go to the new position, it moves at a slower pace than the mouse.

**Comment by kachunkachunk** [comment]
This is a Windows issue, unfortunately. See issue #949

**Comment by Eugeny** [comment]
Duplicate of #949
