### ISSUE TITLE
ssh connetct to jump server

### ISSUE THREAD

**Issue by windzhu0514** [Eugeny/terminus#2884]
Version: 1.0.116
Platform: win32 6.1.7601
Plugins: none

```
 SSH  Connecting to ssh2.17usoft.com
Using user's default private key
Loading private key from  D:\MyConfiguration\ljc43026\.ssh\id_rsa 
  Host key fingerprint:
   SHA256  c5cafe82d7d8d5c53ed6d3542bf5aebeded7be77dc56f648002a74bb23c3ecc3 
 X  All configured authentication methods failed

 SSH   X  Remote rejected opening a shell channel: Error: Not connected

 SSH  ssh2.17usoft.com: session closed
```
Develop Tools error
```
GET file:///C:/Program%20Files/Terminus/resources/app.asar/dist/[object%20Module] net::ERR_FILE_NOT_FOUND
C:\Program Files\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:7574 [ssh] Using user's default private key
C:\Program Files\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:7574 [ssh] Loading private key from [47m[90m D:\MyConfiguration\ljc43026\.ssh\id_rsa [39m[49m
C:\Program Files\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:7574 [ssh] [47m [49m Host key fingerprint:
C:\Program Files\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:7574 [ssh] [47m [49m [30m[47m SHA256 [49m[39m[100m c5cafe82d7d8d5c53ed6d3542bf5aebeded7be77dc56f648002a74bb23c3ecc3 [49m
C:\Program Files\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:7574 [ssh] Server does not support auth method hostbased
C:\Program Files\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:7574 [ssh-ssh2.17usoft.com-22] [41m[30m X [39m[49m Remote rejected opening a shell channel: Error: Not connected
```

occur this error when i ssh connect to a jump server user password

**Comment by windzhu0514** [comment]
Now it can be used normally

**Comment by allenjol** [comment]
I only have a server with normal user's key privileges as a jump-on, log in and run sudo su -, then run SSH to connect to other machines. So I wonder how tabby needs to be configured？
any one can tell me,thanks!

**Comment by Eugeny** [comment]
@allenjol  if you don't have to input a password for the 2nd connection, that means the key for it is stored on the jump server in `/root/.ssh/id_*`. You can copy this key over to your local machine and use it in your Tabby profile for the 2nd connection.

**Comment by allenjol** [comment]
Hello @Eugeny ! I can't do this because only the machine I'm jumping to has an extranet IP that I can connect to using Tabby as a secret key. The other machines only have intranets. In Tabby version 1.0.172, I wanted to execute `sudo su -`  by setting up a login script to capture # and SSH remore_ip, but I found that Tabby only executed `sudo su -` after capturing $. The second command was not executed. I wonder if there is something wrong with my Settings?

**Comment by allenjol** [comment]
The screenshot below：
<img width="536" alt="image" src="https://user-images.githubusercontent.com/28972707/159154599-927ee201-9e85-4c4c-80a0-4f19e9419b3b.png">

**Comment by Eugeny** [comment]
@allenjol sorry for the delay. My suggestion still stands - you only need to retrieve the SSH key from your jump host, and then set up the jump chain directly inside Tabby without any login scripts:

`<jump host> (with your current key) -> <target host> (with the key you copied)`
