### ISSUE TITLE
Can't maximize Terminus window

### ISSUE THREAD

**Issue by adenijiayocharles** [Eugeny/terminus#289]
Since installation, I have not been able to maximise the Terminus Window on my Windows 10 PC. I can't even use it.

**Comment by ahmetcadirci25** [comment]
Click Start or go to the **Windows 10** Search charm, type **%appdata%**, and select the Roaming file.

Open the **terminus** folder.

Open the **windows.js** file and change the coordinates. Restart the program will fix the problem.

```
{
	"windowBoundaries": {
		"x": 0,
		"y": 0,
		"width": 800,
		"height": 400
	}
}
```

**Comment by adenijiayocharles** [comment]
Thanks.  It's working now
