### ISSUE TITLE
[Feature Request] Restart SSH session

### ISSUE THREAD

**Issue by Onepamopa** [Eugeny/terminus#2891]
I'd love to see a "restart" functionality for SSH - when the session times out for some reason (or if bad password is entered) the only way to reopen is to close the tab and open a new one.

Putty has this by simply pressing "Enter" on the session window - it reconnects.

**Comment by Jacamexx** [comment]
I just login here to look for the same.

**Comment by rjroot** [comment]
Would love such a feature.

**Comment by louis-lau** [comment]
If you go to the top right and hover over the 3 dots, there's a reconnect button.

**Comment by Onepamopa** [comment]
Oh, I totally forgot about that, seems like I'm used to the "putty way" ;)
