### ISSUE TITLE
SSH sessions don't get local sessions background image

### ISSUE THREAD

**Issue by hm72747** [Eugeny/terminus#2898]
If a background image is set using custom CSS:

![Clipboard02](https://user-images.githubusercontent.com/69722291/90314046-d3753000-dede-11ea-99c2-4f0030255362.jpg)

It is shown in local sessions:

![Clipboard01](https://user-images.githubusercontent.com/69722291/90314042-cfe1a900-dede-11ea-9c0e-6e737b4b052c.jpg)

But not in SSH sessions:

![Clipboard03](https://user-images.githubusercontent.com/69722291/90314049-d53ef380-dede-11ea-99a6-0f4bd44ea2c8.jpg)

**Comment by Eugeny** [comment]
SSH tabs have a different tag name (`ssh-tab` instead of `terminaltab`)

**Comment by hm72747** [comment]
It works! Thaks so much

![Clipboard02](https://user-images.githubusercontent.com/69722291/90316943-cf074200-def3-11ea-9993-43598359c5a3.jpg)

![Clipboard03](https://user-images.githubusercontent.com/69722291/90316946-d0d10580-def3-11ea-9c6a-0f0040ddb4ca.jpg)
