### ISSUE TITLE
Scrollbars

### ISSUE THREAD

**Issue by naeemkhan12** [Eugeny/terminus#29]
It would be good to have scrollbars so that user can scroll up and down easily.

**Comment by artvandelay440** [comment]
I'm able to scroll on Windows without issue. Do you have anything in your $PSProfile that would affect console behavior/shell size?

**Comment by Eugeny** [comment]
@naeemkhan12 which shell are you using?

**Comment by compliment** [comment]
I'm able to scroll with mouse but not with trackpad.

**Comment by naeemkhan12** [comment]
i am using git bash

**Comment by datreic** [comment]
Are you able to scroll with your mouse or are you concerned with the lack of a scroll bar on the side?

**Comment by naeemkhan12** [comment]
As it is difficult to scroll with touch-pad of laptop so scroll bar is what i am concerned with 😸 .

**Comment by arpit1997** [comment]
Scrollbars would be a great idea as some of the many users faces the issues with touch pad in linux. BTW +1 for the terminus its awesome.

**Comment by kbjr** [comment]
Looks like manipulating the scroll position inside of hterm is actually pretty easy. You can get a handle on the frame, and then the screen component.

```javascript
frame.contentDocument.querySelector('x-screen').scrollTo(0, 0);
```

^ Seems to work exactly as expected, which means building a scrollbar component that interacts with hterm screen should be fairly straightforward. I'll take a crack at it and see if I can get something working.

**Comment by kbjr** [comment]
Okay, I've got basic functionality working for a scrollbar

![image](https://user-images.githubusercontent.com/195127/42139108-6d4d5876-7d3c-11e8-82de-dd3e35745409.png)

**Comment by kbjr** [comment]
https://github.com/kbjr/terminus-scrollbar

**Comment by Eugeny** [comment]
xterm frontend will be the default in the future and has a built-in scrollbar, and hterm scrollbar plugin is availabile, so I'm closing this for now.
