### ISSUE TITLE
[Bug] Terminus using project folder name in the execution

### ISSUE THREAD

**Issue by gajrajgchouhan** [Eugeny/terminus#2906]
So I have a python file (not in my project folder) which loads contents of a json file and prints it.
It runs correct when I use default python build system. (I am using python 3.8.2)
However when using terminus build system (given below), I am getting FileNotFoundError when I run the program.

I have tried debugging this issue and found that terminus is using `$file_path = my-project-path` for the build whereas python build system would use `$file_path = file-path` in the sublime-build file.

So the path of the JSON file will be relative to my project path (~/Documents/folder/) , instead of actual file path (which is ~/Downloads/)

```json
{
    "target": "terminus_open",
    "auto_close": false,
    "timeit": true,
    
    "cmd": ["python3", "-u", "$file"],
    "file_regex": "^[ ]File \"(...?)\", line ([0-9]*)",
    "selector": "source.python"
}
```

I am using Ubuntu 20.04.1 LTS with Sublime Text 3.2.2, Build 3211

**Comment by Eugeny** [comment]
You're looking for https://github.com/randy3k/Terminus
