### ISSUE TITLE
Click and drag tabs to reorder

### ISSUE THREAD

**Issue by ankush981** [Eugeny/terminus#2908]
Hello, I've searched through the issues list (closed as well as open), so I'm pretty sure it's not been covered before. But if so, please feel free to close this issue.

A very common feature in terminals is reordering of tabs by clicking, dragging and dropping. This is very useful when you have several tabs open and they're related to say, the three current projects you're running. In such cases, it's a great convenience to drag and drop related tabs together.

Can this feature be added? Or maybe there's already some tab grouping mechanism and I haven't been able to discover it?

Thanks for the great work, folks! Terminus is the best terminal I ever came across. 😄

**Comment by Eugeny** [comment]
You can reorder tabs by dragging them (Windows / Linux) or dragging them by their numbers (macOS).

**Comment by ankush981** [comment]
Ah, I see, I see. Yes, I'm on Mac and was trying to drag them by the tab. I now spotted that if I hover over the tab number, a small hand icon appears and I can grab and move the tab. Very nice! But, I think this should be more discoverable on Mac. Anyway, thanks again!
