### ISSUE TITLE
Keyboard switching on MacOS level change focus to terminus

### ISSUE THREAD

**Issue by kucherenko** [Eugeny/terminus#2911]
I have strange situation with switching keyboard layout, every time when I switch layout with control+space keys the focus changed to Terminus window. 

Version: 1.0.117
Platform: darwin 19.5.0
Plugins: clickable-links, scrollbar, title-control

**Comment by Eugeny** [comment]
Ctrl-space is the default spawn hotkey for Terminus - you can disable or change it under Settings -> Hotkeys.

**Comment by kucherenko** [comment]
Excellent! Thank you
