### ISSUE TITLE
Duplicate Tab not working

### ISSUE THREAD

**Issue by omipenguin** [Eugeny/terminus#2913]
Version: 1.0.117
Platform: win32 10.0.18363
Plugins: altair, quick-cmds, save-output, scrollbar, title-control

When i open the ssh session with any server , And when i right click on any tab to duplicate tab it don't show me menu which have active ssh connection. But it shows the menu on an inactive tab

**Comment by Eugeny** [comment]
This is fixed in the nightly build.

**Comment by omipenguin** [comment]
I'm using 1.0.117, When i change the tab of color e.g to red other than default , it doesn't show menu, But when i revert it back to default it shows menu

**Comment by Eugeny** [comment]
Yes - it's fixed in the nightly build, which you can get here: https://ci.appveyor.com/project/Eugeny/terminus/build/artifacts
