### ISSUE TITLE
Is it possible to Integrate WinSCP with Terminus

### ISSUE THREAD

**Issue by omipenguin** [Eugeny/terminus#2917]
Not an issue but looking for solution. I was looking a way to transfer file from Terminus but couldn't find any builtin tool for this purpose.  Soin Mobaxterm it is possible to download or upload a file , so is it possible to integrate External Tool like WinSCP with Terminus.

**Comment by Eugeny** [comment]
Duplicate of #296. As a quick way to grab/send a file, you can also use Zmodem
