### ISSUE TITLE
Terminus not working for elixir/erlang shell

### ISSUE THREAD

**Issue by gustavobertolino** [Eugeny/terminus#2920]
I'm using Sublime to code Elixir and have already installed **Elixir + Erlang** in my machine, but when I try using Elixir shell, which is **iex**, it doesn't work in my Terminus panel. 

Below you can see my **iex** version installed as I call it in my Linux terminal
![Screenshot from 2020-08-20 18-43-28](https://user-images.githubusercontent.com/25723294/90830435-0cb30300-e318-11ea-9813-3eefff351dab.jpg)

And here I trying calling **iex shell** on a Terminus session
![Screenshot from 2020-08-20 18-43-57](https://user-images.githubusercontent.com/25723294/90830415-00c74100-e318-11ea-88e5-844d5473574d.jpg)

Does anyone have idea about what could be the root-cause for this apparent fail in Terminus?

**Comment by Eugeny** [comment]
This isn't the project you're looking for.
