### ISSUE TITLE
Weird formatting

### ISSUE THREAD

**Issue by c0fe** [Eugeny/terminus#293]
I am getting some weird formatting with terminus, specifically extra space between lines that isn't in the original file nor is it occurring in other terminal/ssh/putty.

I am using nano editor on the Linux machine and Windows as to write out the configuration.

**Original (using Atom text editor):**

https://i.imgur.com/lW3kNXA.png

**Terminus (using Nano text editor):**

https://i.imgur.com/U1GhZP6.png

**Mobaxterm (using Nano text editor):**

https://i.imgur.com/5xtTslM.png

I am simply using regular copy/paste method.

Mobaxterm does not add in the extra space between lines. If this matters at all I am using Ubuntu 16.04.

**Comment by Eugeny** [comment]
Does the file you copy from use CR, LF or CRLF?

**Comment by c0fe** [comment]
@Eugeny i am not sure what you mean

**Comment by StevenKGER** [comment]
@Eugeny I figured out, how to reproduce this - I tried to copy on my linux laptop, and it worked without additional line breaks. So I booted Windows and selected LF in notepad++, which works without additional lines - using CRLF does add an additional line after any linebreak (effect as described in those two issues). Using CR does produce the same (normal effect) as using LF.

**Comment by Eugeny** [comment]
Nice - I think I know what to do then!

**Comment by sinnlosername** [comment]
I did a small collection of what happens when copying using different line-breaks. Hope it helps.

https://imgur.com/a/EPaUm

**Comment by sinnlosername** [comment]
It's not solved yet. Only MacOS line-breaks (CR) work fine, while CR+LF and LF results in the following.

Original: https://sc.florian.pw/gN4t.png
Result: https://sc.florian.pw/7c4N.png

**Comment by StevenKGER** [comment]
In addition there could be made a test using
```
line 1
line 2
line 3
another fancy line
```
this will end in 

```
line 1 line 2 line 3
another fancy line
```
when using LF (and CRLF due to fix).
Using CR will show the original when copying in to terminus.

However, copying
```
location /  {
          test test1;
          test test2;
}
```
will keep in terminus when copying when using LF (and CRLF due to fix).

**Conclusion** LF sometimes worked - CR always worked in my tests. I did not expect this bug using LF, but also think, that @sinnlosername can approve it.
