### ISSUE TITLE
Cannot start remote ssh session since build 118

### ISSUE THREAD

**Issue by spanyukov** [Eugeny/terminus#2937]
Every time I'm trying to init ssh connection I got this error
`Remote rejected opening a shell channel: TypeError: Cannot read property 'shell' of undefined`
and some windows errors marked red.

After degrading to build 114 everything is good again.
OS: Windows 10 Home Insider Preview Single Language 2004 build 20190.1000

**Comment by Eugeny** [comment]
Should be fixed in build 119.

**Comment by spanyukov** [comment]
> Should be fixed in build 119.

I got this error in 119 either.

**Comment by Eugeny** [comment]
Could you post a full screenshot?

**Comment by seanhogge** [comment]
![terminuserror](https://user-images.githubusercontent.com/11177804/91456507-fbeb1b80-e848-11ea-8c52-6583a0210eb1.png)

Getting something similar or the same: I'm using the same key that I used in 117, which I had to convert from a putty .ppk file back on 114 (or earlier?).

**Comment by spanyukov** [comment]
@Eugeny terminus-1.0.119-setup.exe
![image](https://user-images.githubusercontent.com/7642845/91457538-1fd05080-e88d-11ea-9577-ee62512aa519.png)

**Comment by Eugeny** [comment]
Fixed in Alpha 120
