### ISSUE TITLE
WinSCP integration - right click

### ISSUE THREAD

**Issue by siccous** [Eugeny/terminus#2938]
Hello Eugeny,

I've tried the newly added WinSCP integration and it works great. Only small issue for me is that I'm using the right click as paste (not for context menu). Will it be possible to insert the WinSCP menu also in tab header context menu?

**Comment by hm72747** [comment]
You can configure paste on middle click either

![image](https://user-images.githubusercontent.com/69722291/91307383-df34e200-e77b-11ea-8e84-37d0b0682b8b.png)

**Comment by dhiman-ghosh** [comment]
Hi,

Is there any plan on this enhancement? I agree configuring paste on middle click is another option to get things work but if somebody prefers paste on right click then it is a problem. Tab header context menu would be great as @siccous mentioned, or atleast ability to open the context menu on Ctrl+Right Click or similar (when paste is configured on Right Click), or a configurable hotkey for WinSCP might also do the job. Everything else is great.
