### ISSUE TITLE
Issue: Pageant is not running

### ISSUE THREAD

**Issue by hm72747** [Eugeny/terminus#2939]
I'm running latest version and I cannot connect to a SSH session. It gets stucked at connecting:

" _SSH  Connecting to F8S00314

Private key auth selected, but no key is loaded

  Host key fingerprint:
   SHA256  539aa7ce30d7ad78e9c28f646c960a4700af78cfdc66778d045b450999be6e9f 
 X  Pageant is not running
Trying saved password
■ Connecting_"

![image](https://user-images.githubusercontent.com/69722291/91314334-73a34280-e784-11ea-93a7-7d56aaeee379.png)

![image](https://user-images.githubusercontent.com/69722291/91314365-7b62e700-e784-11ea-8eb6-e1473e821953.png)

**Comment by Eugeny** [comment]
Fixed in Alpha 120

**Comment by Eugeny** [comment]
Fixed in Alpha 120

**Comment by hm72747** [comment]
Good work!
