### ISSUE TITLE
Pageant is not running

### ISSUE THREAD

**Issue by Mirulmaar** [Eugeny/terminus#2941]
Version: 1.0.119
Platform: win32 10.0.18363
Plugins: none

Hello!
I have problems after update 119. If I try to use a new SSH connection, I get a "Pageant is not running" message and the connection fails. Also, if you return to the main menu, the buttons there are inaccessible for pressing and blink.

![Screenshot_6](https://user-images.githubusercontent.com/49832462/91419992-bb959880-e85c-11ea-879e-519f9624908a.png)

![ezgif-6-cefd218a5228](https://user-images.githubusercontent.com/49832462/91421086-27c4cc00-e85e-11ea-87c4-d2e1c45e3cbf.gif)

**Comment by DoctorLai** [comment]
same here.

**Comment by Eugeny** [comment]
Fixed in Alpha 120
