### ISSUE TITLE
font rendering issue with Terminus Font

### ISSUE THREAD

**Issue by andrewboie** [Eugeny/terminus#2943]
My preferred monospaced font is Terminus Font, which you can find here: https://files.ax86.net/terminus-ttf/

I have my font in Terminus Terminal set to "Terminus (TTF) for Windows Medium" size 12.

It seems to be trying to apply some boldface algorithm which is making text very fuzzy-looking:

![incorrect](https://user-images.githubusercontent.com/3387369/91480333-a9652b80-e857-11ea-8c6e-2d0fe1d17675.PNG)

Another example, here it is doing it for only some of the color text. Seems to be a specifically a boldface thing.

![terminus font](https://user-images.githubusercontent.com/3387369/91480408-c8fc5400-e857-11ea-928f-0f6e5dde0352.PNG)

On every other terminal I've used (the new Windows Terminal, PuTTY, VS Code, etc) it doesn't do this. Same deal with every Linux terminal app I've ever used. Here's a screenshot from Windows Terminal:

![correct](https://user-images.githubusercontent.com/3387369/91480698-37411680-e858-11ea-950e-da9fe24e2ac1.PNG)

Would expect Terminus Terminal to behave the same way with this font, or at least a configuration toggle for this.

I don't know if this is reproducible on OSes other than Windows 10.

**Comment by Eugeny** [comment]
The bold text is coming from `ls` itself - looks like the Windows terminal is just ignoring it.

The font works fine for me - have you installed all four TTF files (including bold)? If it can't find the "native" bold variation, it will be artificially generated.

![image](https://user-images.githubusercontent.com/161476/91532679-eccea100-e90e-11ea-90ee-cda9a17146cb.png)

**Comment by omipenguin** [comment]
> The bold text is coming from `ls` itself - looks like the Windows terminal is just ignoring it.
> 
> The font works fine for me - have you installed all four TTF files (including bold)? If it can't find the "native" bold variation, it will be artificially generated.
> 
> ![image](https://user-images.githubusercontent.com/161476/91532679-eccea100-e90e-11ea-90ee-cda9a17146cb.png)

@Eugeny please tell me which font is this in your screenshot above , i have trying to find it but dont know the name of it

**Comment by andrewboie** [comment]
OK I found the problem.

The font picker is a text box. When I started typing "Terminus" it autocompleted to "Terminus (TTF) for Windows Medium".

If I instead changed it to just "Terminus (TTF) for Windows" it looks exactly like I would expect. This was not something that the auto-complete logic offered.

Perhaps the auto-complete logic needs to be less specific.

**Comment by jpwilksch** [comment]
I had the same problem with the Cascadia Code PL font - I had "Cascadia Code PL Medium" selected from the suggestions and bold characters were fuzzy.

Confirmed the work-around - thanks andrewboie!

**Comment by Eugeny** [comment]
A137 now automatically suggests correct font names

**Comment by happycod3r** [comment]
Im experiencing this currently as well. Not sure what to do but making sure I have the necessary TTF files sounds like my next course of action. Any help would be cool if anyone figured out how to positively deal with this. Thanks everyone in advance. 
![image](https://user-images.githubusercontent.com/127797659/231538939-10810aee-3e86-4e17-9bb3-551c6148bd53.png)
