### ISSUE TITLE
Throws weird error every time I try to connect to any SSH session

### ISSUE THREAD

**Issue by aidenmitchell** [Eugeny/terminus#2944]
```
X  Command failed: icacls C:\Users\AIDENM~1\AppData\Local\Temp\f-2020727-20396-jzys60.hkb3h /grant:r battlestation-t\aiden:(R,W)
battlestation-t\aiden: No mapping between account names and security IDs was done.
SSH   X  Remote rejected opening a shell channel: TypeError: Cannot read property 'shell' of undefined
```

I've tried reinstalling but that doesn't help. Not sure what's going on here. Any help would be appreciated.

**Comment by Clemens-E** [comment]
I'm getting the same error, happened after updating to the latest version (now 1.0.120)

**Comment by lyroazo** [comment]
I also got this error when using version 1.0.120.

I tried icacls command in powershell, and found that the problem may be the space of username.
`my-computer/my name` will be trimmed to `my-computer/my`, so icacls fails.

After some investigation, I found #2824 makes this error.
I can connect properly after I revert the changes.

Here is a quick workaround to revert the changes:
1. Edit _terminus-1.0.120-portable\resources\builtin-plugins\terminus-ssh\dist\index.js_ (line 2614 ~ 2616)
```javascript
// let sid = yield (0,child_process.execFile)('whoami', ['/user', '/nh']);
// sid = sid[0].split(' ')[0];
// yield (0,child_process.execFile)('icacls', [temp.path, '/grant:r', `${sid}:(R,W)`]);
yield (0,child_process.execFile)('icacls', [temp.path, '/grant:r', `${process.env.USERNAME}:(R,W)`]);
```
2. Restart Terminus
3. Now Terminus should establish SSH connection properly

**Comment by Eugeny** [comment]
Please post the output of `whoami /user/ nh` on your PC.

**Comment by lyroazo** [comment]
> Please post the output of `whoami /user/ nh` on your PC.

```powershell
PS C:\Users\Ray Cheng> whoami /user /nh
desktop-jrlk2q1\ray cheng S-1-5-21-4163148248-353001864-4251232444-1001
```

**Comment by Eugeny** [comment]
Should be fixed now in the nightly build - thanks!
