### ISSUE TITLE
Text remaining after exiting editor

### ISSUE THREAD

**Issue by c0fe** [Eugeny/terminus#295]
**Problem:**

When you exit a text editor, the cursor will jump upwards and land in between other text rather than return to its original place, below, on the last line.

**Environment:**

- Windows 10 (where Terminus runs)
- Ubuntu 16.04 (remote SSH)
- Nano (text editor)

**Video:**

http://www.screencast.com/t/LTDAGu0RxfPi

**Comment by stu177** [comment]
Have exactly the same issue running Terminus on Ubuntu 17.10. Also occurs when SSH'd into boxes running various versions of Ubuntu and CentOS.

**Comment by c0fe** [comment]
@Eugeny can you please flag this as a bug?

**Comment by Black-J88** [comment]
I am also facing this bug. I am using WSL Ubuntu 18.04.
