### ISSUE TITLE
Opening a terminal on start results in too much space between letters

### ISSUE THREAD

**Issue by BenBait** [Eugeny/terminus#2955]
Version: 1.0.120
Platform: win32 10.0.18363
Plugins: defaults

I recently downloaded terminus and when I open it with either the "auto-open terminal" or "restore terminal tabs" on app start options, there are spaces between all of the letters. If I open a new terminal after opening the app, though, this does not happen (only if a terminal opens on app startup). Anyone know what to do about this?

**Comment by vs1998** [comment]
+1 same for me.
Quick fix: <kbd>RightMouseClick</kbd> -> Split -> Right and close right screen after.
Does not resolve the issue though.

**Comment by vs1998** [comment]
Already mentioned in #2861

**Comment by Eugeny** [comment]
Duplicate of #1850
