### ISSUE TITLE
SFTP Transfer Capabilities

### ISSUE THREAD

**Issue by c0fe** [Eugeny/terminus#296]
I personally really dislike having to deal with nano, vi, vim, emacs whatever and rather just to be able to transfer the file I need out and make the edits I need and transfer it back in. Nothing crazy but a simple file transfer (sftp protocol) would be appreciated.

**Comment by sinnlosername** [comment]
You could use scp for that. Or filezilla.

**Comment by c0fe** [comment]
@sinnlosername you could but I rather not have to switch around programs if I can help it. MobaXterm allows for file transfer capabilities but it isn't as nice looking as Terminus.

**Comment by c0fe** [comment]
@Eugeny any updates on this?

**Comment by Eugeny** [comment]
@c0fe not yet

**Comment by Domain** [comment]
xterm has a zmodem addon, which can be used to transfer files.

**Comment by XianwuLin** [comment]
It's import for me to add this function. Sometimes I can't use stfp transfor files to my pc, because those servers can't be connected directly to my computer.

**Comment by Ansen** [comment]
I have hundreds of servers, I don't want to manage more than one configuration, so I need the sftp function to let me transfer files quickly on the current session.

I don't believe in closed-source fee-based software.

Thank you for your contribution, it makes the world a better place.

**Comment by xugaoxiang** [comment]
+1

**Comment by Schemiii** [comment]
+1

**Comment by BMRX** [comment]
+1 Would love SFTP support.

**Comment by EggsBlue** [comment]
+1

**Comment by EggsBlue** [comment]
@Eugeny +1111

**Comment by lfkdev** [comment]
would really be awesome to have this integrated! +1

**Comment by helloxz** [comment]
+1，Hope to consider adding SFTP support

**Comment by lihe6666** [comment]
+1

**Comment by aiustcer** [comment]
+1

**Comment by Dynan7** [comment]
+1

**Comment by xuanyuanaosheng** [comment]
@Eugeny  Any update?

**Comment by Eugeny** [comment]
@xuanyuanaosheng no updates yet. It's a gigantic chunk of work that I have no time to approach yet.

**Comment by xuanyuanaosheng** [comment]
@Eugeny Looking forward to SFTP function. Thanks

**Comment by aiustcer** [comment]
> @xuanyuanaosheng no updates yet. It's a gigantic chunk of work that I have no time to approach yet.

https://github.com/electerm/electerm  can you use this project's sftp code? contact with the author it may help.

**Comment by omipenguin** [comment]
Even Kitty have option to call external File transfer program, like WinSCP, just uncomment 1 line in kitty configuration file. I hope we can have such support in Terminus.

**Comment by mqhe2007** [comment]
+1

**Comment by dallaslu** [comment]
+1

**Comment by IrwenXYZ** [comment]
+1 I would really love for SFTP functions to be integrated into Terminus

**Comment by howar31** [comment]
still need this in 2021

**Comment by FrederickTF** [comment]
+1 It is the only missing feature that i need to jump from mobaxterm to terminus

**Comment by Eugeny** [comment]
I've added an experimental implementation to the nightly (accessible via the connection toolbar) - currently it can only upload and download single files - more to come 
![image](https://user-images.githubusercontent.com/161476/121756950-40b41a80-cb1c-11eb-8728-2204f17596fc.png)

**Comment by IrwenXYZ** [comment]
@Eugeny sorry for the ping, but where can I report issues for this feature, or nightlies in general?

**Comment by Eugeny** [comment]
@IrwenXYZ right here on the issue tracker - just create new issues.

**Comment by Alejandro-Sosa** [comment]
I'm about to lose it, currently on latest nightly build and I have scavenged the entire program for this feature. Could you give more specific steps on how to access SFTP?

**Comment by Eugeny** [comment]
@Alejandro-Sosa hover on the "..." in the top right corner to reveal the toolbar, or access SFTP from the context menu

**Comment by lfkdev** [comment]
![image](https://user-images.githubusercontent.com/49819192/122678531-9a38db00-d1e7-11eb-8457-9b9e4bde1dcc.png)

**Comment by Alejandro-Sosa** [comment]
Nothing shows up, I don't see any three dots button anywhere either. Am I missing something important?

**Comment by IrwenXYZ** [comment]
@Alejandro-Sosa you need to be connected to a remote server via SSH first. once you're connected, you can see the "..." button at the top right of the screen

**Comment by Eugeny** [comment]
![image](https://user-images.githubusercontent.com/161476/122679396-f3563e00-d1ea-11eb-92a5-bf6c6ccfe8aa.png)

**Comment by alansenairj** [comment]
Is it possible to put download function in SFTP on remote host? It only has upload and delete function.

**Comment by Eugeny** [comment]
@alansenairj click a file to download it.

**Comment by alansenairj** [comment]
Thank you! But in my case I need to download folders. Are there some way to do that? 

> @alansenairj click a file to download it.

**Comment by Eugeny** [comment]
Not yet - here's a tracking issue: #4946

**Comment by c0fe** [comment]
@Eugeny the one I have to add is that if you are using something like LXC, the SFTP function doesn't follow.

**Comment by Eugeny** [comment]
@c0fe could you elaborate? Do you mean you're connecting to a remote host and then to a container on the remote host? If you're just running `ssh` on the remote side, a terminal wouldn't know about that, but you can set up an SSH profile in Tabby using the container host as an SSH jump host and then connecting to the container.

**Comment by c0fe** [comment]
@Eugeny correct, you connect to the remote host and then through that go into the container. yeah you can setup openssh on the container and then run it directly in it but I thought perhaps there has been some kind of an update to address this.

**Comment by Eugeny** [comment]
Well, SFTP can't follow you into a container if the container has no SFTP server in it.

**Comment by c0fe** [comment]
@Eugeny but it does

**Comment by alansenairj** [comment]
Guys, it does based on authentication of ssh server. Just copy to container using ssh-copy-id to better results. 

"To access your sftp from other hosts, please make sure following is installed and configured properly.

Installed OpenSSH servers
Configured sshd_config
PubkeyAuthentication yes
Subsystem sftp internal-sftp
Added your public key to ~/.ssh/authorized_keys

Start the ssh server with port 22/TCP open # /etc/init.d/sshd start

# iptables -I INPUT -j ACCEPT -p tcp --dport 22
Finally, test $ sftp <login>@<hostname>"

https://unix.stackexchange.com/questions/209770/ssh-console-login-working-but-sftp-does-not-why
