### ISSUE TITLE
Password changed...

### ISSUE THREAD

**Issue by ernest33** [Eugeny/terminus#297]
Terminus should be able to : 
* Ask for the password if the first try to connect doesn't succeed.
or 
* Add an option to be able to change the recorded password of the SSH session.

Actually if the account password used to login is changed by the "admin", you cannot connect.

**Comment by Eugeny** [comment]
Currently, the stored password should be auto-deleted if the connection fails. Is this not the case?

**Comment by ernest33** [comment]
Seems not.
Could be useful to be able to change manualy the password in the ssh session settings(_when you already know the password has changed_)
