### ISSUE TITLE
Pass the vttest

### ISSUE THREAD

**Issue by RedHatter** [Eugeny/terminus#299]
The standard test of full vt100 terminal emulation is [vttest](https://invisible-island.net/vttest/). Terminus currently fails several of the screens.

Vttest is included in the Ubuntu repositories.

    $ sudo apt install vttest
    $ vttest

**Comment by c0fe** [comment]
This is actually a good idea, Terminus looks neat but I have run into a number of annoying issues that makes working with it a problem.

@Eugeny please take into consideration of this, might just help out in ironing Terminus out to be less problematic overall when you have the time.

**Comment by Eugeny** [comment]
As much as I'd like it to pass, I have to reply on hterm.js to do the terminal emulation, and it's far from perfect. The only other viable option is xterm.js, but it doesn't provide satisfactory results either
