### ISSUE TITLE
Windows doesn't show BASH option

### ISSUE THREAD

**Issue by andrewbanchich** [Eugeny/terminus#3]
Fantastic terminal so far! However, on Windows 8 I go to Settings > Terminal > Shell and I only see CMD and Powershell. No BASH.

**Comment by Eugeny** [comment]
Hi Andrew, could you check if _Bash on Windows_ is fully installed, i.e. whether typing in `bash` in the default command prompt takes you directly to Bash?

**Comment by andrewbanchich** [comment]
Ah, I see. No, it isn't recognizing it as a command. I don't believe it is installed. I figured it had something like Git Bash, which is installed on my computer.

**Comment by Eugeny** [comment]
No, it's literally the "Bash on Windows", by Microsoft :)
See: https://msdn.microsoft.com/en-us/commandline/wsl/install_guide?f=255&MSPPError=-2147217396
