### ISSUE TITLE
[FEATURE] auto-reconnect

### ISSUE THREAD

**Issue by oligu** [Eugeny/terminus#3010]
It would be useful to have the option that a disconnected tab automatically tries to reconnect after some timeout.
Like this, we don't have to try to reconnect multiple times for example when the connected device is rebooted.
As en extra bonus, the timeout could increase after every few unsuccessful attempts to connect in a row.

**Comment by alhassanv** [comment]
I like this feature because when I'm working with multiple servers it becomes really annoying..

**Comment by ldavis2020** [comment]
Oh yes please, this feature would be amazing! Even just the option to right-click on a tab that has a dead connect and hit reconnect would be a fabulous start.

**Comment by alhassanv** [comment]
I mean why does terminus even terminate the session?

**Comment by ldavis2020** [comment]
The session terminates because my laptop goes into sleep mode (eg I close the lid). Putty and Termius (SSH clients I've used previously) have had options to reconnect a session if it terminates. Automatic reconnection would be fantastic, but a right-click option would also work.

**Comment by ldavis2020** [comment]
I'd still like the auto reconnect feature, but for those that don't know (and I've been using Terminus for well over a year now and only just noticed) the three dots in the top right hand corner of the window will reconnect a dead SSH session.

**Comment by Muadiv** [comment]
No updates yet in this feature ?
