### ISSUE TITLE
Can not store passwds?

### ISSUE THREAD

**Issue by SarshesJ** [Eugeny/terminus#302]
I have installed terminus on my gnome DE for fedora workstation. It is simple and beautiful, very nice.

But when I tried ssh client, I can't find options for storing the passwords. 

But I found this #297 . Terminus can store passwords, right? how can I do that?

**Comment by Eugeny** [comment]
Terminus will ask for password if the key auth doesn't succeed. Successfully authenticated passwords are stored in the system keychain.

**Comment by SarshesJ** [comment]
emmmm..... But the terminus always asks me for the password no matter what I did, even if the former connection was opened and closed successfully.

So I tested the following code with root and normal user on my machine, and the output is "Password is null"
```
[root@me terminus-ssh]# ls node_modules/
asn1  semver  ssh2  ssh2-streams  streamsearch  xkeychain
[root@me terminus-ssh]# cat xkeychain.js 
var keychain = require('xkeychain');
keychain.setPassword({ account: 'foo', service: 'FooBar', password: 'baz' }, function(err) {
  keychain.getPassword({ account: 'foo', service: 'FooBar' }, function(err, pass) {
    console.log('Password is', pass);
    // Prints: Password is baz 
  });
});
[root@me terminus-ssh]# node xkeychain.js 
Password is null
```

It seems that xkeychain not working correctly. Should I install some additional packages?

**Comment by Eugeny** [comment]
Could you also check if `setPassword` returned an `err`?

**Comment by SarshesJ** [comment]
Seems `setPassword` failed. `console.log(err)` gives the output.
```
Error: Security returned a non-successful error code: 1
    at ChildProcess.<anonymous> (/opt/Terminus/resources/builtin-plugins/terminus-ssh/node_modules/xkeychain/platforms/linux.js:168:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

**Comment by Eugeny** [comment]
Interesting, can you set passwords using this tool from xkeyring? https://github.com/mvhaen/node-xkeychain/blob/master/platforms/gkeyring.py

**Comment by SarshesJ** [comment]
I need to install the gnome-keyring python binding.
```
[root@me platforms]# dnf remove gnome-python2-gnomekeyring
```
or the python script will fail.
```
[root@me platforms]# python gkeyring.py --help
Traceback (most recent call last):
  File "gkeyring.py", line 13, in <module>
    import gnomekeyring as gk
ImportError: No module named gnomekeyring
```

**Comment by SarshesJ** [comment]
Yes, now it works fine.

**Comment by Eugeny** [comment]
Thank you for debugging! I've added the RPM dependency

**Comment by laundry-96** [comment]
Hello @Eugeny, the RPM in question (gnome-python2-gnomekeyring) is not available on Fedora 33. Are you aware of any alternatives we can use?
