### ISSUE TITLE
Dynamic port forwarding configuration

### ISSUE THREAD

**Issue by thgesteves** [Eugeny/terminus#3020]
Hello guys, 

I am trying to create a dynamic port forwarding config on Terminus, but I can't put an * to specify the remote port while configuring it. Is there a way to do it? I am trying to create a local SOCKS proxy to access my company web servers that are behind a firewall. I've already done it with putty but I really want to use just terminus and not use putty just to do just it. 

Regards. 

Thiago

**Comment by eugenov** [comment]
https://github.com/Eugeny/terminus/issues/2077
