### ISSUE TITLE
ssh keys not working from 

### ISSUE THREAD

**Issue by saviodesign** [Eugeny/terminus#3028]
Version: 1.0.120
Platform: win32 10.0.19041
Plugins: altair

Receiving the following error at login:
 SSH  Connecting to 192.168.0.XX
Loading private key from  C:\Users\XXX\Documents\XXXX\sshkey\id_rsa.ppk 
 
X  Failed to parse (unnamed) as a valid auto format key: key is not a private key
 SSH   X  **Remote rejected opening a shell channel: TypeError: Cannot read property 'shell' of undefined**

**Comment by PhilippLoewen** [comment]
I'm prettty sure you're using the wrong key format. That's a puttygen format. Terminus requires the OpenSSH format.
Check here on how to convert with PuttyGen: https://www.tbs-certificates.co.uk/FAQ/en/putty-ppk-vers-openssl-openssh.html

**Comment by saviodesign** [comment]
Receiving a similar error post key conversion.

**SSH  Connecting to 192.168.X.XXXX
Loading private key from  C:\Users\Savio Design\XXXXX\XXXXXXX\terminus.ppk 
 X  Command failed: icacls C:\Users\SAVIOD~1\AppData\Local\Temp\f-202095-11380-y9lulb.lx1te /grant:r xxxxxxxxxxxxx\savio:(R,W)
 xxxxxxxxxxxxx\savio: No mapping between account names and security IDs was done.
SSH   X  Remote rejected opening a shell channel: TypeError: Cannot read property 'shell' of undefined**

Even after granting correct permissions R/W to applications folder (**%appdata%**) the error is still there.

This issue is **client specific** as I have tested these keys, and they do work with some other clients including **PuTTY** and  **MOBA**, as well as mobile clients like **Juice SSH**.
Please take a diligent look into this is issue rather than redirect me to information I can obtain through a general google search.
These are security keys, and thus a major issue for those of us that would prefer to not expose simple SHH tunneling to "Bad Actors" by enter keystrokes.

**Note**: I am not the only person experiencing this issue as there are others with the same problem posted under a different topic header ( found after the original posting ).  The associate BOT closed the issue before it could be properly addressed.

#786  
#3034 
#3028
#3030
#2952 
#2944 
And many more ( 15+ pages of this error to search through) 

Again, please take a good look at this issue, it is not one single person issue, these are all related, and rathe than slap a band-aid on it, how about we address the problem at its' core and resolve MANY issues in one felled swoop. Rather than trying to save time by invalidly closing out unverified issues.

**Comment by saviodesign** [comment]
I've since updated to version 1.0.122, and this appears to have been resolved.
