### ISSUE TITLE
New terminal starts with blank lines

### ISSUE THREAD

**Issue by lucasqueiroz** [Eugeny/terminus#303]
First, thank you for creating such a great terminal! In my home computer, I use it with Ubuntu 17.10 and it works really well.
But in my work's machine, a macOS, when it starts a new terminal, it leaves some blank lines behind:
<img width="1277" alt="screen shot 2018-03-13 at 11 36 01" src="https://user-images.githubusercontent.com/29466590/37348408-bd9777ac-26b2-11e8-841b-3d27ded3974d.png">

**Comment by Eugeny** [comment]
Duplicate of #11
