### ISSUE TITLE
Where does Terminus look for npm? (OSX)

### ISSUE THREAD

**Issue by wnpaul** [Eugeny/terminus#305]
Clicking the "Plugins" item in Settings told me I needed to install npm, so I did that. It installed in /usr/local/bin.
Terminus still tells me npm is not available.  What gives?

**Comment by Eugeny** [comment]
It's looking for in the `$PATH`, so likely /usr/local/bin isn't on it.

**Comment by dklima** [comment]
I can confirm, it don't look for $PATH

![screen shot 2018-03-16 at 15 04 27](https://user-images.githubusercontent.com/52062/37537118-598a7c48-292b-11e8-95a3-969c087e9a5e.png)

![screen shot 2018-03-16 at 15 04 01](https://user-images.githubusercontent.com/52062/37537127-5ea290bc-292b-11e8-85fb-52a57b956442.png)

**Comment by Eugeny** [comment]
If your $PATH is set by .bashrc, .zshrc or similar, it doesn't apply to any applications except shells.

**Comment by Eugeny** [comment]
Here's one way: https://apple.stackexchange.com/a/243946
