### ISSUE TITLE
Dragging the window

### ISSUE THREAD

**Issue by 18gatenmaker** [Eugeny/terminus#3066]
Version: 1.0.120
Platform: win32 10.0.19041
Plugins: relaxed-theme

Steps:
1. Open terminus
2. Drag the window around

Unexpected behaviour:
- It duplicates my cursor
- It moves at a constant rate in the direction i was dragging it into
- It doesn't stop until I get my cursor at the same position of the fake pointer.

**Comment by Eugeny** [comment]
Duplicate of #949
