### ISSUE TITLE
Feature: Intelligent copy/paste shortcuts

### ISSUE THREAD

**Issue by sinnlosername** [Eugeny/terminus#307]
Hi!

I'm using the latest release of terminus (Alpha 42). Currently you cannot copy with ctrl+c without removing the "interrupt" shortcut from most shells. So you can either copy text or close programs, but not both. The same problem is for paste.

It would be nice if you could add a kind of "intelligent" copy/paste mode like:
Click ctrl + c while text is marked: Copy the text
Click ctrl + c while no text is marked: Input will be sent to shell

I know there's also a different key combination, but it's not so fast and handy. Also, you could add a config option, so people can choose the current if they (for whatever reason) want so.

**Comment by Eugeny** [comment]
This is a fantastic idea! Will certainly implement
