### ISSUE TITLE
Broken responsive design on edge cases

### ISSUE THREAD

**Issue by crumbleRhubarbe** [Eugeny/terminus#308]
Hello! First of all I'm not used to issue design problems and I would like to apologize if this issue is not well crafted.

I'm using Terminus on Windows 10 docked on the right side of my screen. When moving the `Docked terminal size` slide bar to the left, to reduce the terminal size, the responsive design breaks past a point.

![reference_point](https://user-images.githubusercontent.com/621850/37713188-615ed8ee-2d16-11e8-9960-d24f0ca6bbab.png)

You can observe that the top button is slightly cropped on the right, and that there is still room left to decrease the size again.

It is especially obnoxious with the bottom and right docking. Both with minimum set makes the app unusable, pushing the UI off the screen. To return to a good enough state you need to know how to resize a window by yourself and set the slide bar back to a reasonable value.

![right_broken](https://user-images.githubusercontent.com/621850/37713304-c64cdf9e-2d16-11e8-80f7-4a511a08003a.png)

![bottom_broken](https://user-images.githubusercontent.com/621850/37713336-e91ed590-2d16-11e8-83df-a4809f8d473c.png)

With the left docking the UI get squished but doesn't present this off-screen behavior. With the top docking the left end of the slide bar is ignored.

Sadly I don't have the time to dive into a codebase and a language I don't know so I can't fix it myself.

**Comment by Eugeny** [comment]
Thank you for your report! Great screenshots.
The reason for this is that the app positions itself along the right edge for the small expected width, but then can't squish itself beyond the minimum width.
