### ISSUE TITLE
Feature Request: when using saved SSH session the name of the tab is the "name" field, propose again.

### ISSUE THREAD

**Issue by cvster** [Eugeny/terminus#3085]
I saw many issues requesting for this feature, like #2240 #2027 #621 #65
Many other ssh tools like xshell and mremoteNG defaultly behaves like this, because it's quite useful and convenient.
Thank you.

**Comment by Eugeny** [comment]
In the connection settings: 
![image](https://user-images.githubusercontent.com/161476/96412247-1fe43100-11ea-11eb-98a0-fa0a0362195d.png)

**Comment by cvster** [comment]
That's great, thank you!
