### ISSUE TITLE
"Hide dock on blur" setting is hidden, but still active, if docked mode is switched to "Off"

### ISSUE THREAD

**Issue by x6herbius** [Eugeny/terminus#3096]
I was getting extremely confused that whenever I clicked away from my Terminus window, the entire application would hide. I worked out that this was because I'd previously enabled "Hide dock on blur" when I had started off using the terminal in docked mode. When I switched docked mode to "Off", the option to hide on blur was hidden from the settings menu, but still caused the terminal to hide itself upon loss of focus. It took me _many_ passes over the settings pane in order to work out where the setting was and to disable it.

I would suggest either not allowing the application to hide itself in this way if it's not docked, or moving the "hide on blur" setting so that it is always available in the settings pane.

My Terminus version: 1.0.120

**Comment by x6herbius** [comment]
Does this have visibility from any maintainers?

**Comment by Eugeny** [comment]
Yes, in fact it was fixed a month ago, but the ticket wasn't closed for some reason.
