### ISSUE TITLE
Proposal for serial features

### ISSUE THREAD

**Issue by MikeMihailov** [Eugeny/terminus#3099]
Hello!
I use serial part of Terminus every day. It's very useful to have  PowerShaell and Serial in the same program.  So I think it will be great to add the next features for serial connection:
1. Monitoring port status - if I reboot or reconnect my USB to serial device, there is no reaction in the tab.
2. Auto reconnection to the port. If port of the tab re-created, it will be cool to reconnect.
3. Input line. The serial tab sends only one char from the keyboard and I don't see what I type without echo in my device. It will be nice to have an opportunity to write a command and send full string after Enter, like in the common command line.

**Comment by Eugeny** [comment]
All done ✅
