### ISSUE TITLE
in mac os x utf-8 not working

### ISSUE THREAD

**Issue by Ox16** [Eugeny/terminus#31]
I get ??????w not żółw. default sh, 
i use mc and not working too. 
many hot keys is this same as Polish chars (Right alt+ zascnlo...)
terminal is not usefull

$ set | grep TERM
TERM=xterm-color
TERMCAP=$'SC|xterm-color|VT 100/ANSI X3.64 virtual terminal:\\\n\t:DO=\\E[%dB:LE=\\E[%dD:RI=\\E[%dC:UP=\\E[%dA:bs:bt=\\E[Z:\\\n\t:cd=\\E[J:ce=\\E[K:cl=\\E[H\\E[J:cm=\\E[%i%d;%dH:ct=\\E[3g:\\\n\t:do=^J:nd=\\E[C:pt:rc=\\E8:rs=\\Ec:sc=\\E7:st=\\EH:up=\\EM:\\\n\t:le=^H:bl=^G:cr=^M:it#8:ho=\\E[H:nw=\\EE:ta=^I:is=\\E)0:\\\n\t:li#24:co#80:am:xn:xv:LP:sr=\\EM:al=\\E[L:AL=\\E[%dL:\\\n\t:cs=\\E[%i%d;%dr:dl=\\E[M:DL=\\E[%dM:dc=\\E[P:DC=\\E[%dP:\\\n\t:im=\\E[4h:ei=\\E[4l:mi:IC=\\E[%d@:ks=\\E[?1h\\E=:\\\n\t:ke=\\E[?1l\\E>:vi=\\E[?25l:ve=\\E[34h\\E[?25h:vs=\\E[34l:\\\n\t:ti=\\E[?1049h:te=\\E[?1049l:k0=\\E[10~:k1=\\EOP:k2=\\EOQ:\\\n\t:k3=\\EOR:k4=\\EOS:k5=\\E[15~:k6=\\E[17~:k7=\\E[18~:\\\n\t:k8=\\E[19~:k9=\\E[20~:k;=\\E[21~:F1=\\E[23~:F2=\\E[24~:\\\n\t:kh=\\E[1~:@1=\\E[1~:kH=\\E[4~:@7=\\E[4~:kN=\\E[6~:kP=\\E[5~:\\\n\t:kI=\\E[2~:kD=\\E[3~:ku=\\EOA:kd=\\EOB:kr=\\EOC:kl=\\EOD:'
TERMINUS_PLUGINS=

anybody can help me?

**Comment by Eugeny** [comment]
Could you please elaborate? Which exact hotkeys are in conflict? Which OS are you on? A screenshot of broken Unicode would be appreciated.

**Comment by smalllixin** [comment]
I encounter the same problem. All the chinese named file show "?????".
MacOS sierra Version 10.12.5
<img width="524" alt="screen shot 2017-07-05 at 9 48 49 am" src="https://user-images.githubusercontent.com/787881/27846095-5cf59908-6167-11e7-9594-fdc34dcb39d9.png">

**Comment by taohex** [comment]
![image](https://user-images.githubusercontent.com/1678003/27847262-37ed49c8-616f-11e7-8db1-2f47c2ce5e84.png)
On macOS 10.12.5
I encounter the same problem. The powerline fonts are broken, too.

**Comment by a-sk** [comment]
Same here, powerline symbols, russian symbols all are not rendered correctly.

**Comment by StrangeNoises** [comment]
For my part, finding the symbols used by bash-git-prompt do not work, am seeing only question marks.

Compare: 
<img width="224" alt="screen shot 2017-07-05 at 14 44 18" src="https://user-images.githubusercontent.com/1295001/27867055-74a70892-6190-11e7-8b2b-24f076e2a19d.png">

vs: same in Terminal.app: 
<img width="229" alt="screen shot 2017-07-05 at 14 44 45" src="https://user-images.githubusercontent.com/1295001/27867070-852e6c0a-6190-11e7-83ec-bac5ebb43288.png">

On macOS High Sierra beta 1, terminus alpha 16. Font here is Consolas 14pt in both cases, but is just the same in Menlo.

**Comment by Eugeny** [comment]
Please retry with alpha 17

**Comment by a-sk** [comment]
I tried with alpha 18, with no success :(

**Comment by mikesprague** [comment]
Same issue here on Sierra with v1.0.0-alpha.18. 

FWIW, this is specific only to Terminus. All other terminal emulators on my system built with web technologies ([Hyper](https://hyper.is/), [Upterm](https://github.com/railsware/upterm), [TermBar](http://termbar.com/)) render all characters in all fonts, including powerline, without issue.

**Comment by Eugeny** [comment]
I've added another potential fix in Alpha 19

**Comment by mikesprague** [comment]
Thanks @Eugeny, that seemed to do the trick with the font display!

**Comment by nililia** [comment]
Upterm is can unicode
