### ISSUE TITLE
soft-breaks in copy

### ISSUE THREAD

**Issue by sinnlosername** [Eugeny/terminus#310]
Hi!

If a text is longer than the whole line, terminus will automatically add a soft-break (Here's a screenshot of it https://sc.florian.pw/rIu7.png). 

The problem is: It will also copy those soft-breaks, but it shouldn't do so, as they don't really exist in the program output.

**Comment by kbjr** [comment]
I don't know that there's going to be any easy path to fixing this.

Terminus seems to use `hterm.copySelectionToClipboard()` to handle the actual copy. \[[source](https://github.com/Eugeny/terminus/blob/master/terminus-terminal/src/components/terminalTab.component.ts#L98)]

Looking into that, it looks like they just use `document.execCommand('copy')` \[[source](https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm/js/hterm.js#168)]

Which bring this all down to a matter of how that `execCommand('copy')` is implemented.

https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

At best, it's an hterm issue, at worst, it would be considered a webkit "issue". Ultimately, I doubt either would do anything about it (especially the latter).

**Comment by rootshellz** [comment]
Was these ever a fix for this?  Still annoying.
