### ISSUE TITLE
Terminus asking for private key passphrase though it isn't selected

### ISSUE THREAD

**Issue by Proxymiity** [Eugeny/terminus#3102]
When I log to a ssh server, Terminus keeps asking me to enter my `$home/.ssh/id_rsa` passphrase even though I didn't select a private key to be used, but a password.
This renders the app unusable as I can't even login to servers using a normal 'password' auth.

Host config:
![image](https://i.iya.at/Terminus_dkLAHj.png)

Term output:
![image](https://i.iya.at/Terminus_7u8BS0.png)

**Comment by DeviantUK** [comment]
I can confirm this problem.

**Comment by Eugeny** [comment]
Duplicate of #2968

**Comment by rbukovansky** [comment]
Problem solved with the latest AppVeyor build! 🍾
