### ISSUE TITLE
SSH connection failed when using saved password

### ISSUE THREAD

**Issue by SovietSword** [Eugeny/terminus#3110]
**I am using Terminus on Windows 10 for SSH connection. The "Authencation" option is set as "password".** 

![terminus1](https://user-images.githubusercontent.com/47520284/97427570-b681c200-194f-11eb-8566-55e0200ec072.png)

**But when I try to connect, Terminus tries to use private key and causes an error.**

![terminus2](https://user-images.githubusercontent.com/47520284/97427573-b7b2ef00-194f-11eb-87e8-f1547ac97f8b.png)

**And if I delete ~/.ssh/id_rsa and ~/.ssh/id_rsa.pub, Termius works right then.**

![terminus3](https://user-images.githubusercontent.com/47520284/97427575-b84b8580-194f-11eb-910d-d8a4814c3b37.png)

**I am quite confused. Is there something wrong with my environment, or are there bugs with Terminus's authencation logic?**

**Comment by isdqwq** [comment]
![Uploading image.png…]()

**Comment by rbukovansky** [comment]
Yeah, I have already reported this issue in #2968 😊

Unfortunately, it seems like another great and awesome open source project dead in the water... 😢 Or am I mistaken, @Eugeny? 🤷

**Comment by Eugeny** [comment]
Duplicate of #2968

**Comment by rbukovansky** [comment]
Problem solved with the latest AppVeyor build! 🍾
