### ISSUE TITLE
neovim view bug

### ISSUE THREAD

**Issue by peach-lasagna** [Eugeny/terminus#3112]
![изображение](https://user-images.githubusercontent.com/59787538/97696135-2ca03900-1ab6-11eb-947d-0dba7760f1b6.png)

1. terminal theme conflicts with neovim theme
2. terminal on pressing esc then enter creates a new line with input for commands

**Comment by peach-lasagna** [comment]
![изображение](https://user-images.githubusercontent.com/59787538/97696922-5a39b200-1ab7-11eb-8687-8adf8ccc0fac.png)

**Comment by peach-lasagna** [comment]
and vim lays in this terminal

**Comment by Chameleon-fzb** [comment]
I have the same problem as you.
