### ISSUE TITLE
GET file:///C:/Users/Administrator/AppData/Local/Programs/Terminus/resources/app.asar/dist/[object%20Module] net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by copysunday** [Eugeny/terminus#3124]
GET file:///C:/Users/Administrator/AppData/Local/Programs/Terminus/resources/app.asar/dist/[object%20Module] net::ERR_FILE_NOT_FOUND

Version: 1.0.120
Platform: win32 10.0.18362
Plugins: none

**Comment by Heartlessguy** [comment]
Looks like it's the same issue i've created here #3217
