### ISSUE TITLE
Copying text with CTRL+C instead of send cancel

### ISSUE THREAD

**Issue by StevenKGER** [Eugeny/terminus#314]
Hello,

I am using Terminus 1.0.0-alpha.44.
When I am pressing CTRL+C to cancel an operation, it sometimes copies a string from my terminal.
Actually, my hotkey for copying is "CTRL+SHIFT+C" and not "CTRL+C" - I also turned the function "Copy on select" on, so it already copies.

This behaviour is not good for me. For instance, I want to cancel an operation and got a string marked from an operation before - if I want to cancel this with CTRL+C, I have to demark the string and press CTRL+C again, however this is not my copy shortcut.

**Comment by sinnlosername** [comment]
I'd add a config option to disable this "intelligent copy" feature if people want so.

**Comment by Eugeny** [comment]
The smart Ctrl-C hotkey can now be removed from the settings tab.

**Comment by rianquinn** [comment]
This new feature is a game changer. Switched to this instead of HyperTerm specifically because of this feature.

**Comment by thedonquixotic** [comment]
The only thing I really feel is lacking functionality wise is the "open Terminus here" right click context menu functionality. And from what little I know about windows registry stuff, that's pretty easy to do.

**Comment by Eugeny** [comment]
@thedonquixotic wrong issue?

**Comment by thedonquixotic** [comment]
@Eugeny yes, sorry. Had too many tabs open. Great work on the project I'm impressed!
