### ISSUE TITLE
Allow switching between OS and shell handling of Alt-keys

### ISSUE THREAD

**Issue by Eugeny** [Eugeny/terminus#316]
German and Spanish users rely on the OS to process Alt-letter combos to input accented characters, but some applications (nano etc.) expect the Alt-letter keystrokes to be forwarded to shell unprocessed.

We should expose this setting to the user.

**Comment by apra93** [comment]
This is listed as an enhancement, but it renders terminal applications that use the meta (alt) key for basic operations unusable. Emacs is where I noticed this issue, but I'm sure there are others.

**Comment by Eugeny** [comment]
It's listed as an enhancement because currently, only the first option (OS handles Alt key) is available

**Comment by Eugeny** [comment]
Both modes should now be accessible:

macOS:
* With "Alt key is Meta key": Alt sends Meta as well
* Without "Alt key is Meta key": Alt is processed by the OS, Cmd key is Meta in the shell

Windows and Linux
* With "Alt key is Meta key": Alt sends Meta
* Without "Alt key is Meta key": Alt is processed by the OS
