### ISSUE TITLE
Sometimes, some characters wont show up

### ISSUE THREAD

**Issue by lucasqueiroz** [Eugeny/terminus#317]
Hi. I'm having a weird problem: When the PS1 is at the bottom of the screen, the first character of the second row does not show up.

Examples:

![screenshot from 2018-04-02 10-37-51](https://user-images.githubusercontent.com/29466590/38198223-41e0b302-3662-11e8-9470-97462a7dffe9.png)

:point_up: This shows the problem, when I'm at the bottom of the screen

![screenshot from 2018-04-02 10-38-05](https://user-images.githubusercontent.com/29466590/38198256-672e8f8a-3662-11e8-8546-b45ad08497f5.png)

:point_up: This is after I run `clear`

**Comment by Eugeny** [comment]
could you please upload your dotfiles/shell config?

**Comment by lucasqueiroz** [comment]
You mean the file that creates the PS1? It is a theme I built myself using Ruby, and it works perfectly in all the other terminals (iTerm 2, Hyper, Terminator...). If you want to check the code you can see it at https://github.com/lucasqueiroz/powerline-pills-zsh

**Comment by dougmaitelli** [comment]
I am facing problems with powerline in Terminus as well, but for me, the problem is that the prompt on the right side does not appear, and instead is displayed on the left side, overlapping the other characters.
