### ISSUE TITLE
add "always on top" for windowing

### ISSUE THREAD

**Issue by finomxf** [Eugeny/terminus#3187]
add "always on top" for windowing, along with Max, Min, 
this is handy when let the terminal app on top of a IDE (VS code for example), 
the terminal app can use the empty space usually on the right side of the IDE window, at the same time, keep IDE window use the whole screen. 

thanks, 
BR fino

**Comment by Eugeny** [comment]
This is basically what the Dock mode does (Settings -> Application -> Dock the terminal)

**Comment by SaiNikhileshReddy** [comment]
@Eugeny It would give flexibility for people who don't want to dock it permanently. It would be great if you add an option in settings for it.
