### ISSUE TITLE
move config file to follow the xdg-user-dirs spec

### ISSUE THREAD

**Issue by xenoterracide** [Eugeny/terminus#3188]
link to spec https://www.freedesktop.org/wiki/Software/xdg-user-dirs/ the default should put the file in `~/.config` (probably `~/.config/terminus`. If just straight up changing isn't an option, maybe allow it to be an install time option. My motivation for this is I want to use https://yadm.io to store the config, and move it across OS's, so having it in the same place on all of them makes things easier. Note: starting this on Mac OS, but I also have a Linux box, and a Windows Box.

**Comment by Eugeny** [comment]
Terminus already places its config in `~/.config/terminus` on Linux, but that's not a standardised config location for macOS (even if some Brew builds use it). See https://github.com/Eugeny/terminus/wiki/Config-file for config paths for all platforms.

**Comment by xenoterracide** [comment]
I understand it not being the default, but if it's not in the same place on all operating systems I can't (currently/easily) share the config between them. I'm just wondering if we could add an option to move it in the installer, to whatever directory.
