### ISSUE TITLE
Buttons are off the bottom of the window when window frame is set to thin or full and tab location is set to left or right

### ISSUE THREAD

**Issue by DeviantUK** [Eugeny/terminus#3191]
In 1.0.121 and 1.0.122, some buttons are off the bottom of the window when the window frame is set to thin or full, and tab location is set to left or right. There is no problem when window frame is set to native.
Possibly related to #3186?

![Terminus_aTp7iW9BQG](https://user-images.githubusercontent.com/16081842/101611738-c76b2c00-3a01-11eb-904a-56f4062fa68f.png)
![Terminus_XV3ZfjTObA](https://user-images.githubusercontent.com/16081842/101611745-c934ef80-3a01-11eb-8df8-55bfdce2805d.png)

**Comment by ZehuanZhang** [comment]
same issue here, the button overflows its container
![image](https://user-images.githubusercontent.com/20352723/102161378-30e7b080-3ec2-11eb-9605-055c6436e999.png)

**Comment by NJAldwin** [comment]
I am experiencing this when tab location is `Bottom`, but only for `Full` frame mode:

### Full
![image](https://user-images.githubusercontent.com/145036/103488431-7c62ef80-4dda-11eb-9b18-b45781fdc2b3.png)

(note none of the content in the tabs/buttons on the bottom are visible; the small spaces are still clickable if you know where things should be)

### Thin
![image](https://user-images.githubusercontent.com/145036/103488447-90a6ec80-4dda-11eb-8668-be7dfdae2e95.png)

### Native
![image](https://user-images.githubusercontent.com/145036/103488459-9dc3db80-4dda-11eb-8735-c3656dda5c42.png)
