### ISSUE TITLE
Drag tabs to arrange order

### ISSUE THREAD

**Issue by SergioSuarezDev** [Eugeny/terminus#3192]
"Drag tabs to arrange order"

It is possible add this functionality?

Thanks

![Kapture 2020-12-09 at 10 59 45](https://user-images.githubusercontent.com/3636232/101614820-b1fbff00-3a0d-11eb-85fe-8265f45bcf57.gif)

**Comment by Eugeny** [comment]
You can drag the tabs around by their numbers.

**Comment by RangerRick** [comment]
I ended up searching this because I was trying to figure out if it was a feature of Tabby yet. It didn't occur to me that only the number would grab, so I never happened to grab that part of the tab.

Is the a reason the entire tab (other than the `X`) isn't grabbable?

**Comment by Eugeny** [comment]
Yes (it's used to drag the window itself)

**Comment by alphahot1** [comment]
Unfortunately, for me this has the side effect that if you click on the tab just to focus it (not to move the window), you end up always moving the window a few pixels... and if your window is maximized, it's annoing.
Any chance you could do something about it?

Thanks
