### ISSUE TITLE
In this version, When toggle terminal window, app creating new icon as i attached.

### ISSUE THREAD

**Issue by msaistaken** [Eugeny/terminus#3195]
![image](https://user-images.githubusercontent.com/62212589/101636124-edadbd80-3a3b-11eb-8593-0d2f2186d3d7.png)

**Comment by masa0612** [comment]
I encountered the same problem with the following environment.

Version: 1.0.122
Platform: linux 4.15.0-128-generic
Plugins: none

**Comment by Eugeny** [comment]
Duplicate of #1642
