### ISSUE TITLE
Terminus does not run zsh on start

### ISSUE THREAD

**Issue by pwittchen** [Eugeny/terminus#32]
In settings, I've tried to choose `/usr/bin/zsh` and also `bin/zsh`. In the new terminal tab, zsh wasn't set as the default shell. After restarting the app it also didn't work. Default terminal application available in the system works fine.

My setup:
- Ubuntu 16.04 LTS
- Zsh

**Comment by Eugeny** [comment]
Which shell gets opened instead of zsh?

**Comment by pwittchen** [comment]
```
echo $0
```

prints 

```
sh
```

so I suppose it's `sh`. In default terminal, the same command prints `-zsh`.

**Comment by zaphbbrox** [comment]
Hey,
I have a similiar problem. In the Terminus settings the selected shell is `bash`, but every new terminal opens a `sh`-shell.
I'm using the binary file from the latest release on Antergos.

**Comment by cornerot** [comment]
You need to install "screen"

**Comment by pwittchen** [comment]
@cornerot You're right. After installing `screen`, it works fine. 

I think it should be added to some kind of FAQ, requirements/dependencies section or installation file.

**Comment by Eugeny** [comment]
@pwittchen did you install Terminus from a DEB package? It should have `screeen` as a dependency

**Comment by pwittchen** [comment]
@Eugeny I downloaded `*.deb` package and installed it with: `sudo dpkg -i *.deb` command.

**Comment by zaphbbrox** [comment]
@cornerot It works for me, too. thanks!

**Comment by cornerot** [comment]
@pwittchen, @zaphbbrox welcome!
