### ISSUE TITLE
Toggle terminal windows lose focus when full screen

### ISSUE THREAD

**Issue by PePoDev** [Eugeny/terminus#3214]
Version: 1.0.122
OS: Windows 10

After Toggle Terminus It will focus on "New terminal" button. Happen only in full-screen mode.

**Comment by nnkken** [comment]
Same issue here. Seems that in my case it is focused on the close button, after hitting Ctrl+Space to toggle the terminal, pressing space results in closing the first tab.

Version: both 1.0.123 and 1.0.125 have the same issue
OS: Windows 10

Seems previous version does not have the same issue, but I forgot which one. This appears after a certain version upgrade.

**Comment by nnkken** [comment]
Tried downgrading and seems the problem starts from 1.0.122

**Comment by PePoDev** [comment]
Upgrading to 1.0.134 solved
