### ISSUE TITLE
Probable conflict with another package

### ISSUE THREAD

**Issue by moreorem** [Eugeny/terminus#3225]
**OS**: OpenSuse Tumbleweed
**DE**: KDE Plasma

**Install method**: rpm package

**Description**:
After installing, software update is initiated with error. Probable conflict of similar named package https://software.opensuse.org/package/terminus

![Screenshot_20201223_120547](https://user-images.githubusercontent.com/34963131/102985092-4474c600-4517-11eb-8a1f-19db038e7ae9.png)

**Comment by DeanR97** [comment]
Have the Same issue under Ubunut 20.10.

**Comment by widewind2015** [comment]
same with Ubuntu 21.04.

**Comment by Eugeny** [comment]
The package has been renamed in the nightly builds.
