### ISSUE TITLE
With session persistence off, mouse events in byobu/tmux aren't handled correctly

### ISSUE THREAD

**Issue by fj** [Eugeny/terminus#323]
When you use the mouse in Terminus while inside `byobu` (and with session persistence off), mouse events aren't handled correctly.

Works:

* open `xfce4-terminal`
* `byobu`
* type `ls -la` in a directory with a large number of files
* use mouse scroll wheel to see beginning of list
* works! :smile: 

Doesn't work:

* open Terminus
* disable session persistence; restart
* type `ls -la` in a directory with a large number of files
* use mouse scroll wheel to see beginning of list
* doesn't work; renders control characters to screen or produces other unusual effects :cry:

**Comment by fj** [comment]
Commenting to refresh issue as per stalebot's request, since this is still outstanding.

**Comment by fj** [comment]
Commenting to refresh issue as per stalebot's request, since this is still outstanding.

**Comment by Eugeny** [comment]
Is there any custom configuration involved? Byobu doesn't react to mouse wheel in stock xfce4-terminal for me

**Comment by fj** [comment]
Are you using `tmux` or `screen` for your byobu backend? This is
tmux-specific.

**Comment by Eugeny** [comment]
Closing as tmux/screen persistence isn't used anymore
