### ISSUE TITLE
Feature Requests.

### ISSUE THREAD

**Issue by Hypnoes** [Eugeny/terminus#324]
1.  Set multiple fonts for font-fallback.
1.  Support ansi escape code `\33[5m blink(slow)` `\33[6m blink(fast)`

**Comment by NDelt** [comment]
Fallback font option is definitely needed for configuring CJK fonts separately.

**Comment by Eugeny** [comment]
Blinking text attribute will not be implemented in xterm, which I'm using for terminal rendering: https://github.com/xtermjs/xterm.js/issues/944
