### ISSUE TITLE
Toggle-Window causes a terminus stacking on notify bar

### ISSUE THREAD

**Issue by lucaomartins** [Eugeny/terminus#3258]
Version: 1.0.122
Platform: linux 5.4.0-58-generic
Plugins: none

When i press the toggle window key terminus stack on notify bar

![image](https://user-images.githubusercontent.com/51249341/103178573-b411ea80-4862-11eb-889c-2f85cb32e39c.png)

**Comment by onlyjsmith** [comment]
The same thing happens when 'Hide dock on blur' is set and I click out of terminal.

Version: 1.0.127
Platform: linux-5.8.0-40-generic / Ubuntu 20.10

**Comment by ralleal** [comment]
The same thing happens with me.

Version: 1.0.136
Platform: 5.11.0-14-generic / Ubuntu 21.04

**Comment by lucaomartins** [comment]
Duplicate of #1642
