### ISSUE TITLE
MacOS 10.12.6 is not available

### ISSUE THREAD

**Issue by wenbingzhang** [Eugeny/terminus#3259]
/Applications/Terminus.app/Contents/MacOS/Terminus
(node:62968) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:62974) Electron: Loading non-context-aware native module in renderer: '/var/folders/xd/g0bw6b953mndsj0_f24w0xkh0000gn/T/.org.terminus.2GS6gY'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:62974) Electron: Loading non-context-aware native module in renderer: '/var/folders/xd/g0bw6b953mndsj0_f24w0xkh0000gn/T/.org.terminus.CER3gW'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:62974) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1228/094948.978571:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7fff5954c000, 0x2000): (os/kern) invalid address (1)
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: index.js:6333:30

**Comment by wenbingzhang** [comment]
https://github.com/Eugeny/terminus/issues/3261

**Comment by Eugeny** [comment]
Tracking in #3261
