### ISSUE TITLE
Alpha 123 crash / blank window

### ISSUE THREAD

**Issue by coLATin** [Eugeny/terminus#3261]
OS: MacOS bigsur 11.1
Terminus version Alpha 122 -> Alpha 123
Try update and re-install ways, no help.
Crash in the loading process, have to force quit each time.
for Alpha 122 or even elder versions, everything is ok.
looking forward to fix asap, really a perfect app.

https://user-images.githubusercontent.com/749762/103192685-808f9880-4914-11eb-861b-fe95b09d43f9.mov

**Comment by coLATin** [comment]
Seems to find the reason, crash when load local machine (folder), but in 122, it's OK.
BTW:
copy (text or content) not work sometimes, have to right click mouse to use copy.

**Comment by FlameMida** [comment]
I also got this problem

**Comment by coLATin** [comment]
sadly I lost all my nodes config, because the auto login as last time, and last time I opened local tab, so dead end.....

**Comment by KhushrajRathod** [comment]
same problem, downgrading fixes it temporarily.
Here's the error in the window console:
```
GET file:///Applications/Terminus.app/Contents/Resources/app.asar/dist/[object%20Module] net::ERR_FILE_NOT_FOUND
```

**Comment by SergioSuarezDev** [comment]
I have fixed it doing this: 
**Disable auto-updates and install Terminus version Alpha 122**

**Comment by KhushrajRathod** [comment]
How do you disable auto updates?

**Comment by KhushrajRathod** [comment]
Ah nvm, I found it in the general preferences. Somehow I couldn't find it earlier

**Comment by Eugeny** [comment]
Please post the crash report (it's found under Console.app -> Crash Reports).

**Comment by crstauf** [comment]
> Please post the crash report (it's found under Console.app -> Crash Reports).

There is no crash report listed for Terminus.

**Comment by matias-miranda** [comment]
In `system.log` of Console.app I see this:

```
Dec 30 21:23:39 Matiass-MacBook-Pro-2 Terminus Helper (GPU)[8402]: getattrlist failed for /System/Library/Extensions/AppleIntelKBLGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsGLDriver: #2: No such file or directory
Dec 30 21:23:39 Matiass-MacBook-Pro-2 Terminus Helper (GPU)[8402]: getattrlist failed for /Library/GPUBundles/AMDRadeonX6000GLDriver.bundle/Contents/MacOS/ATIRadeonX6000SCLib.dylib: #2: No such file or directory
Dec 30 21:23:39 Matiass-MacBook-Pro-2 Terminus Helper (GPU)[8402]: getattrlist failed for /System/Library/Extensions/AMDRadeonX6000GLDriver.bundle/Contents/MacOS/ATIRadeonX6000SCLib.dylib: #2: No such file or directory
Dec 30 21:23:39 Matiass-MacBook-Pro-2 Terminus Helper (GPU)[8402]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
```
I have graphics AMD Radeon Pro 5500M 4 GB, if that helps..

**Comment by Eugeny** [comment]
Fixed in Alpha 124

**Comment by BxDev** [comment]
Today, after updates i have the same bug. Latest version KDE Neon.

![Image](https://github.com/user-attachments/assets/7aed3177-5302-487a-9cf6-191f266b2430)
