### ISSUE TITLE
Can't install plugins

### ISSUE THREAD

**Issue by manjotsc** [Eugeny/terminus#3264]
Hi,

When I try to install any plugin, I am getting the following error.

```
Error in quick-cmds:
TypeError: must call as: npm.load(callback)
Thanks,

```
Windows 10 Pro Latest Build
Version: 1.0.123

**Comment by dogancelik** [comment]
I confirm.

![plugin install error](https://user-images.githubusercontent.com/486818/103254158-50d4a500-4995-11eb-83fa-284333ef760e.png)

Same OS, same Terminus version.
