### ISSUE TITLE
Terminal  brash/blank (white window) when open a new tab

### ISSUE THREAD

**Issue by SergioSuarezDev** [Eugeny/terminus#3265]
From this week when i open a new terminal, app crashes and show a white window:

<img width="804" alt="Captura de pantalla 2020-12-28 a las 22 53 33" src="https://user-images.githubusercontent.com/3636232/103245178-a3936a00-495f-11eb-8c7a-82f3b4c871c5.png">

**Comment by SergioSuarezDev** [comment]
I have fixed it doing this: 
**Disable auto-updates and install Terminus version Alpha 122**

**Comment by huangjian80s** [comment]
me too,but i am mac + Alpha 123
just reboot mac ,only work

**Comment by kentond18** [comment]
I experienced the same issue @SergioSuarezDev and did the temp fix as you stated prior.

Any updates from @Eugeny or devs if this is something you are all aware of?

**Comment by xingshanghe** [comment]
the same question.
mac + 1.0.123

**Comment by tedvdb** [comment]
I'm seeing the same in version 1.0.123 on MacOS 11.1.

Attached the [developer tools log](https://github.com/Eugeny/terminus/files/5750271/-1609235127301.log).

I think the main error is this one:
```
/Applications/Terminus.app/Contents/Resources/app.asar/dist/[object%20Module]:1 GET file:///Applications/Terminus.app/Contents/Resources/app.asar/dist/[object%20Module] net::ERR_FILE_NOT_FOUND
```

**Comment by fighterhit** [comment]
> I have fixed it temporary doing this:
> **Disable auto-updates and install Terminus version Alpha 122**

How to `Disable auto-updates` ?

**Comment by SergioSuarezDev** [comment]
In settings

**Comment by Eugeny** [comment]
Duplicate of #3261
