### ISSUE TITLE
SSH Blank screen on Windows

### ISSUE THREAD

**Issue by rajsardhara** [Eugeny/terminus#3268]
Hello,

This issue just started on windows with Version 1.0.123, everything works just fine but when I try to do ssh during cipher match screen just goes completely blank and just hangs there, here is the screenshot.

![image](https://user-images.githubusercontent.com/25749762/103290421-1ed03c80-49af-11eb-9e03-a2d7f164387e.png)
![image](https://user-images.githubusercontent.com/25749762/103290702-c483ab80-49af-11eb-88a9-7fc32f41aa93.png)

**Comment by fighterhit** [comment]
I met this in Ubuntu.

**Comment by tanconghui** [comment]
I also met this when I try to establish an SSH connection on Windows 10, Version 1.0.123.

**Comment by SixBytesUnder** [comment]
Same here on Windows 10, Version 10.0.19042 Build 19042
Started with Terminus 1.0.123

**Comment by Eugeny** [comment]
Duplicate of #3261
