### ISSUE TITLE
Cannot input anything after ssh reconnection

### ISSUE THREAD

**Issue by lf-openthos** [Eugeny/terminus#3276]
If the ssh connection is broken or terminated by the server and use "reconnect" at the dead terminal, the connection will be restored correctly but non input is accepted any more. The only solution is to close the tab and create a new one.

Affected OS: windows 10, macOS Catalina and Big Sur (Other OS may be affected also but not confirmed)
Affected plugin: SSH

**Comment by Eugeny** [comment]
Which version are you on?

**Comment by lf-openthos** [comment]
1.0.122 and 1.0.123, this won't happed every time but most the time.

**Comment by snehbansal** [comment]
This looks to be similar to https://github.com/Eugeny/terminus/issues/3074

@Eugeny, were you able to look at the console logs I shared in that ticket?
