### ISSUE TITLE
SSH errror: Unable to request agent forwarding

### ISSUE THREAD

**Issue by lafriks** [Eugeny/terminus#328]
It is currently not possible to connect to ssh servers that has option `AllowAgentForwarding no` set.

When connecting to such server terminus shows error: `Could not connect: Error: Unable to request agent forwarding`

**Comment by lafriks** [comment]
Problem is still actual, it is not possible to connect to servers with `AllowAgentForwarding no` set

**Comment by bramPintelon** [comment]
I have the same problem. A solution would be nice, with other ssh managers (royal ts putty, solar putty, ...)  I can connect to the same server without any problem.

**Comment by Novezeil** [comment]
Same here with alpha 62 & 63 (was okay with .62 for a period of time though).

**Comment by Novezeil** [comment]
Update: the issue was narrowed down to my own incorrect config on `ssh_config`, which should not be confused with `sshd_config`. Running commands such as `ssh -l ` or `ssh -- l` would likely to show the faulty part in `ssh_config`.

**Comment by Eugeny** [comment]
Now fixed together with #496
