### ISSUE TITLE
Alpha 124 Blank screen

### ISSUE THREAD

**Issue by dsheedes** [Eugeny/terminus#3283]
When trying to open a new SSH connection I only get a blank screen
![image](https://user-images.githubusercontent.com/7893622/103485215-13d53c00-4df5-11eb-8b40-03b5282d70ef.png)

Going back to 122 fixes the issue

**Comment by Alexs-12** [comment]
same problem except when doing it manually

**Comment by Eugeny** [comment]
Fixed in a125

**Comment by rbukovansky** [comment]
> Fixed in a125

I can confirm. Thanks, @Eugeny!
