### ISSUE TITLE
SSH exit problem 

### ISSUE THREAD

**Issue by Alexs-12** [Eugeny/terminus#3285]
Version: 1.0.125
Platform: win32 10.0.19042
Plugins: none

![SSH](https://user-images.githubusercontent.com/39067512/103487830-7dab1100-4e08-11eb-8b6c-34564b254421.png)

**Comment by aidenmitchell** [comment]
What exactly is the issue? I don't see any problems here.

**Comment by Alexs-12** [comment]
the problem is that when you execute the command exit the screen does not close and remains stationary with the written session closed
