### ISSUE TITLE
Prompt not showing

### ISSUE THREAD

**Issue by akilegaspi** [Eugeny/terminus#329]
![aa](https://user-images.githubusercontent.com/6070608/38973568-14760776-43d9-11e8-8330-c9e0ba14f7d7.PNG)

The Prompt (e.g ">", "$") isn't showing when I start Terminus itself

**Comment by thyberg** [comment]
This happened to me also on windows 10 (surface pro) after a reboot of the machine.
No matter what shell I choose in the shell settings not shell appears in the window.
Terminus seems to fork something according to the activity manager:
![image](https://user-images.githubusercontent.com/141589/41473651-3574b824-70ba-11e8-9ef2-07a8c2e225eb.png)
No restart or reboot seems to help
