### ISSUE TITLE
Terminus slows Windows down to a crawl

### ISSUE THREAD

**Issue by agilly** [Eugeny/terminus#3292]
Happy to see the terminus project continually improving!

I would like to report an issue that I did not experience the last time I tried Terminus. I am running it on a dual GPU config:

0. Intel UHD Graphics 630
1. Nvidia Quadro P2000

When I start up Terminus, using Windows becomes very slow. All apps are slowed down noticeably. The task manager shows that "Desktop Window Manager" has extremely high GPU usage (>90%). It is set to use GPU 0. 

I saw some other issues that suggested Terminus might do better on another GPU. I forced Windows to use GPU 1 for Terminus.exe, but that doesn't help the issue above. The Desktop Windows Manager still uses GPU 0, and the computer is still quite slow.

Specs:

Intel Core i9 8950HK
32Gb RAM
64-bit Windows 10 2004

**Comment by agilly** [comment]
This is directly tied to the acrylic background. When that is disabled, GPU usage goes down. Is it expected that the blurry background would almost saturate a GPU like that?

**Comment by Eugeny** [comment]
Acrylic background in Win32 apps is still pretty glitchy in Windows (and remains undocumented). If it doesn't perform on your machine, definitely disable is or switch to the simple blur in the settings.
