### ISSUE TITLE
Glasstron debian10 issue

### ISSUE THREAD

**Issue by dysondi** [Eugeny/terminus#3293]
I have the error when i trying start terminus.
please help me resolve that.
Here i need do "npm install glasstron" ?

```
Glasstron.init() is deprecated! Please use the Glasstron.BrowserWindow export
Directly injecting into Electron.BrowserWindow is not recommended! Please use the Glasstron.BrowserWindow export instead.
Delaying the 'ready' event via the Glasstron Hacks class is not recommended! Please take care of it yourself!

```

**Comment by masa0612** [comment]
I encountered the same problem with the following environment.

Version: 1.0.125(I have confirmed that version 1.0.124 also has this bug. And And it doesn't happen in version 1.0.123 )
Platform: Ubuntu 18.04(4.15.0-128-generic)
Plugins: none

**Comment by Eugeny** [comment]
This should now be fixed in Alpha 127. Let me know if you still experience problems and I'll reopen.
