### ISSUE TITLE
meta (alt)+ key  not work

### ISSUE THREAD

**Issue by lainredsonic** [Eugeny/terminus#330]
shortcut not work:
meta (alt) + f   : move forward by words
meta (alt) + b   : move backward by words
meta (alt) + d   : delete forward by words

It's looks like meta(alt) key no effect.

keycode when press meta (alt):
press any key (program terminates 10s after last keypress)...
keycode  28 release
keycode  56 press
keycode  56 release
keycode  56 press
keycode  56 release
keycode  56 press
keycode  56 release
keycode  56 press
keycode  56 release
keycode  56 press
keycode  56 release
keycode  56 press
keycode  56 release
keycode  56 press
keycode  56 release
keycode  56 press
keycode  56 release
keycode  56 press
keycode  56 release
keycode  56 press
keycode  56 release
keycode  29 press
^Ccaught signal 2, cleaning up...

ENV:
OS:opensuse 13.X   , opensuse 42.X
TERM:screen-256color

**Comment by apra93** [comment]
I have a feeling this will be closed in favor of #316, so I'd add your comment there

**Comment by Eugeny** [comment]
Now fixed in #316
