### ISSUE TITLE
"SafeValue Must Use" Message on Titlebar

### ISSUE THREAD

**Issue by anidotnet** [Eugeny/terminus#3305]
Version: 1.0.125
Platform: linux 5.4.0-59-generic
Plugins: altair, clickable-links, quick-cmds, relaxed-theme, save-output, scrollbar, theme-gruvbox, theme-hype

The title bar is having this annoying text as below

![image](https://user-images.githubusercontent.com/696662/103768577-c6510d00-5048-11eb-9d41-fea5ab2e72b7.png)

**Comment by Eugeny** [comment]
Please file the issue with the offending plugin's author.

**Comment by anidotnet** [comment]
Can you tell me which plugin is causing this issue?

**Comment by Eugeny** [comment]
Judging by the icon seems to be "quick-cmds"
