### ISSUE TITLE
Feature request: Open WinSCP in current Terminus console path

### ISSUE THREAD

**Issue by hm72747** [Eugeny/terminus#3306]
When I launch WinSCP from shell menu it opens a session to that same SSH server session previously opened in Terminus, however this new WinSCP session it is opened in the default path. There should be an option so the SFTP session follows the same path as the SSH session.

**Comment by Eugeny** [comment]
Unfortunately the remote shell doesn't notify terminal of its current CWD, so this wouldn't be possible
