### ISSUE TITLE
Not working on MacOS 10.13.4

### ISSUE THREAD

**Issue by UAnton** [Eugeny/terminus#331]
Hello,
Last biuld not working on MacOS 10.13.4.

The application “Terminus” can’t be opened.

**Comment by Eugeny** [comment]
If you're seeing this dialog,

![](https://www.technipages.com/wp-content/uploads/2017/01/MacOS-Gateway-Warning.png)

you need to allow the app under macOS' Preferences -> Security

**Comment by UAnton** [comment]
I know about this. I have another dialog.
![untitled](https://user-images.githubusercontent.com/1290580/39044331-82cd555c-4498-11e8-880c-29837ba71427.png)

**Comment by Eugeny** [comment]
Have you already tried all the usual things (re-downloading, deleting the old version first etc)? I've just tried it on my 10.13.4 and it works.

**Comment by davistran86** [comment]
@UAnton try this, you should enable Anywhere: http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/
