### ISSUE TITLE
Terminus Uninstalled Itself

### ISSUE THREAD

**Issue by shidarin** [Eugeny/terminus#3312]
I realize how crazy this sounds, but last night when I clicked the 'X' to close Terminus, Terminus asked for admin permissions (which I granted, thinking it was auto-updating) and uninstalled itself. It did not end up upgrading the install- I had to download a new installer this morning.

I'm not sure what version of Terminus I was on- 1.0.113 or newer.

Windows 10.

I'm sorry for how little information I can provide, I wasn't paying that much attention to it.

**Comment by Eugeny** [comment]
No problem - older versions have sometimes had this issue when auto-updating.
