### ISSUE TITLE
It's stuck to drag the window

### ISSUE THREAD

**Issue by evalexp** [Eugeny/terminus#3318]
Version: 1.0.126
Platform: win32 10.0.18363
Plugins: none

Look this gif.
![2](https://user-images.githubusercontent.com/72970177/104124939-a6924f80-538e-11eb-92b5-1fd75c923451.gif)

**Comment by Bloopps** [comment]
Same issue

Version: 1.0.126
Platform: win64 10.0.19041
Plugins: none

**Comment by evalexp** [comment]
This problem has been solved in Version 1.0.127
