### ISSUE TITLE
serial tab crash in macos

### ISSUE THREAD

**Issue by CyrilTaylor** [Eugeny/terminus#3325]
version: 1.0.126

https://user-images.githubusercontent.com/12631466/104208969-14f90f80-546c-11eb-9af7-9a312984968d.mp4

Serial Tab crash in Macos, and terminus dead, so can't get debug log.

**Comment by ryanrdetzel** [comment]
I'm seeing this too.

**Comment by Eugeny** [comment]
This should now be fixed in Alpha 127. Let me know if you still experience problems and I'll reopen.
