### ISSUE TITLE
Splitting into 4 panels and right clicking no longer shows context menu

### ISSUE THREAD

**Issue by princemaple** [Eugeny/terminus#3328]
Version: 1.0.126
Platform: win32 10.0.19042
Plugins: clickable-links

It also doesn't split any further beyond 4, which I don't mind, but it shouldn't block context menu from showing.

**Comment by Eugeny** [comment]
Please see if there's anything in the debug console.

**Comment by princemaple** [comment]
![image](https://user-images.githubusercontent.com/1329716/104300061-17b23e00-551a-11eb-82f8-7820996a9bdd.png)

Also I found out that it's not only when splitting into panels. I can only have 4 sessions running. If I create 4 tabs I am not able to create another one. My action to create more seems to be queued somehow, when I close 1 of the 4, a new one pops up.

**Comment by fitzg2** [comment]
Side request. Can the close tab hotkey close the active split and not the entire tab?

**Comment by Eugeny** [comment]
@fitzg2 you can rebind your `close-tab` hotkey to `close-pane` and use that - closing the last pane closes the tab.

**Comment by Eugeny** [comment]
Fixed in nightly.

**Comment by princemaple** [comment]
FYI 132 seems to be working as expected. 133 doesn't open. Stuck on startup.

Platform: win32 10.0.19042
Plugins: clickable-links
