### ISSUE TITLE
Custom shell opening in new window

### ISSUE THREAD

**Issue by Sean-Pickering** [Eugeny/terminus#3332]
Version: 1.0.125
Platform: win32 10.0.14393
Plugins: none

I downloaded the git for git-sdk-64 from https://github.com/git-for-windows/git-sdk-64. I tried to use git-bash.exe as custom shell in Terminus but it keeps opening a new window as seen in the pictures.
![NeedsFixed](https://user-images.githubusercontent.com/77068587/104498949-fdbc3e00-55a1-11eb-8176-e2a95b66fd6a.PNG)
![NeedsFixed2](https://user-images.githubusercontent.com/77068587/104498970-03b21f00-55a2-11eb-8616-44bdc98d8cf6.PNG)

**Comment by Eugeny** [comment]
Don't quote me on this, but IIRC you can run git-sdk's bash as `git-cmd.exe --command=usr/bin/bash.exe -l -i`

**Comment by Sean-Pickering** [comment]
It is working now! however, there is always an extra space in between lines (with a %) as shown. Is there a way to fix this? 
![image](https://user-images.githubusercontent.com/77068587/104505873-2fd19e00-55aa-11eb-8c4f-359549f0d00c.png)

**Comment by Eugeny** [comment]
This looks like what zsh is printing when the last command's output didn't end with a new line

**Comment by Sean-Pickering** [comment]
I did PROMPT_EOL_MARK='' and that seemed to fix it!
