### ISSUE TITLE
Unsupported key exchange algorithm: curve25519-sha256@libssh.org

### ISSUE THREAD

**Issue by baermathias** [Eugeny/terminus#3335]
I have configured an SSH connection with a key file in `/home/user/.ssh/id_rsa_myproject` and iIt worked yesterday in v126, but doesn't work today in v127. I get the following error:

```
 SSH  Connecting to ip_address
Loading private key from  /home/user/.ssh/id_rsa_myproject
 X  Unsupported key exchange algorithm: curve25519-sha256@libssh.org
 SSH   X  Remote rejected opening a shell channel: Error: Not connected
```

**Comment by Lockszmith** [comment]
Same here. workede earlier today before upgrade.

Running on Windows 10, connecting (or more precisley failing connect) to Ubuntu 20.04 LTS, freshly installed today.

**Comment by ErdeFB** [comment]
Updated from 1.2.5 to 1.2.7 and I got the same issue. Reverting back to 1.2.5 fixed the issue.
Client is on latest stable Win10 and server is Ubuntu 20.4.

**Comment by Poulpinounette** [comment]
> Updated from 1.2.5 to 1.2.7 and I got the same issue. Reverting back to 1.2.5 fixed the issue.
> Client is on latest stable Win10 and server is Ubuntu 20.4.

Work for me.

**Comment by Poulpinounette** [comment]
> Updated from 1.2.5 to 1.2.7 and I got the same issue. Reverting back to 1.2.5 fixed the issue.
> Client is on latest stable Win10 and server is Ubuntu 20.4.

Reverting back, work for me. Thanks.

**Comment by Eugeny** [comment]
This was due to me having to downgrade Electron because of the native crashes in the new version, and the older Node doesn't have support for c25519 exchanges. Please try this nightly build: https://nightly.link/Eugeny/terminus/workflows/windows/master/Installer (win) / https://nightly.link/Eugeny/terminus/workflows/macos/master/macOS%20.pkg%20(x86_64).zip (mac)

**Comment by Poulpinounette** [comment]
I have try with the news version, i think the bug was resolve. Good jobs
