### ISSUE TITLE
Tabs hit invisible barrier on Thin theme

### ISSUE THREAD

**Issue by ChaosZero112** [Eugeny/terminus#334]
On the sixth Tab, Terminus starts shrinking them, creating a lot of wasted space on the top bar. Only appears to be affecting the Thin theme.

![2018-04-26_16-43-14](https://user-images.githubusercontent.com/22225233/39330922-135f67c2-4971-11e8-87af-d50d0f57798c.png)

![terminus_2018-04-26_16-46-33](https://user-images.githubusercontent.com/22225233/39331028-6743252c-4971-11e8-882c-62216ae9dc19.png)

This is on Windows 10 build 1703, Terminus alpha 45.

**Comment by Eugeny** [comment]
The area in the middle is for dragging the window around (similar to Microsoft Edge). Unfortunately Electron  doesn't support dragging the window by clickable areas yet.

**Comment by ChaosZero112** [comment]
I had a feeling that might be the case... In that case, not a bug, but an ehancement request to shrink the space.

I feel like this
![applicationframehost_2018-04-26_17-06-33](https://user-images.githubusercontent.com/22225233/39332063-5c723ee6-4974-11e8-858d-7ff5fd05c636.png)

Is a much better use of space than this
![terminus_2018-04-26_17-06-46](https://user-images.githubusercontent.com/22225233/39332084-6a901a84-4974-11e8-85d6-f740591f7f8c.png)
