### ISSUE TITLE
Close tab and close app not responding

### ISSUE THREAD

**Issue by Bootta11** [Eugeny/terminus#3342]
I'm using Windows 10 and installed ssh(not using Terminus ssh). I open few tabs that are ssh on different hosts. After there are multiple ssh active connections Terminus close tab and close app stop responding?

This happen if terminus stay open for longer time(I keep it open for 8+ hours). If ssh opened in tabs and I try to close that tabs sooon after tab-terminus opened it will prompt me message "ssh.exe" is still running. Close?". But if ssh tabs stay open for some time and I try to close them there is not this message.

**Comment by Arro** [comment]
I'm experiencing this as well on the arm64 Mac build, on versions `1.0.126` and `1.0.127` both.

**Comment by Roobyx** [comment]
Happens to me as well. 
But it has nothing to do with SSH for me. I am using 4 tabs, for light nginx and nodejs. 
Cannot close either a tab or the whole app and I have to kill it from task manager.

**Comment by matias-miranda** [comment]
Similar issue on Mac, versions 1.0.126 and 1.0.127 the tab and app closes but terribly slow, same to open a new tab, it seems stuck

**Comment by matias-miranda** [comment]
I saw on dev console that the whole app is re-draw many times,
I also noticed that the Vibrance has no effect, and I added custom css and I saw a lot of redrawing on the <style> tag. maybe related to https://github.com/Eugeny/terminus/issues/3292

I'm not sure if those are related, just trying to provide some clue, the issue seems to be related to performance

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by Bootta11** [comment]
After update(version 1.0.132) problem no more exists.
