### ISSUE TITLE
Some characters make rows higher than normal

### ISSUE THREAD

**Issue by iolaizola** [Eugeny/terminus#335]
Hi,
Im running the alpha 45 version. I cannot see the text when it reaches the bottom as it get's cut. It seems to be a kind of padding issue, any suggestions?

**Comment by leandroaps** [comment]
The same applies to the top, I'm running the 46 build on the new Ubuntu 18. Try to fix using CSS, doesn't work.

**Comment by elton2048** [comment]
I believe it is font problem when oh-my-zsh(or only zsh? I use both so I don't know the core) is used. By default the font used is Liberation Mono which seems have bad support in Ubuntu 18.04(I just try on it). Try `ls -al` and there is no padding between each item.

To solve the problem AVOID to use the following font.

- FreeMono
- Liberation Mono
- MathJax_Vector (\-Bold)
- Noto Mono (Only letter 'g' is problematic)
- Ubuntu Mono

Also I guess some Linux distros(or desktop? I don't know how the font is associated in Linux) miss some font in the list as some item shows no difference in terminal tab. Maybe it is better to set a common font for Linux version to ensure the default display is good?

**Comment by iolaizola** [comment]
Thanks! As you say there is a strange behaviour where some fonts fit well while others some others don`t.

I changed to `cousine` and now it works perfeclty.

**Comment by iolaizola** [comment]
I tried to fix it by using the debugger. I saw that changing the <x-screen> tag "overflow" attribute from "hidden" to "visible" fixes the issue, but I don't know how to specify it in the CSS

**Comment by Eugeny** [comment]
Please disregard the above - overflow: visible breaks scrolling. 
Could you guys post some screenshots?

**Comment by iolaizola** [comment]
Hi Eugene,

I send you two screenshots. The first one is created by using "cousine"
font while the second one uses "Ubuntu Mono".
you can see that now the effect is mainly that the characters that go
downwards are cut ("g", "q", "p").

With a little gap with the frame or making it transparent should be enough.

Thank you

Igor

**Comment by Eugeny** [comment]
@iolaizola you'll have to attach them directly on Github since mail attachments won't work.

**Comment by iolaizola** [comment]
Now they should be properly updated. Thanks again!

![screenshot from 2018-07-22 21-47-59](https://user-images.githubusercontent.com/8578574/43049901-1ae565c2-8e00-11e8-90e9-2fe24927e0ce.png)
![screenshot from 2018-07-22 21-44-02](https://user-images.githubusercontent.com/8578574/43049903-1b00d6cc-8e00-11e8-94f3-5058d8385b0a.png)

**Comment by Eugeny** [comment]
Can you check if using a simple prompt (e.g. from `sh`) alleviates the issue?

**Comment by iolaizola** [comment]
Yes, with sh it works perfeclty

**Comment by Eugeny** [comment]
Then I can confirm that it's emoji and special characters (lamba in your case) that can push the lines to be higher than they should be - I'll see what I can do about this!
