### ISSUE TITLE
is it possible to write plugin to show images/pdf?

### ISSUE THREAD

**Issue by diegopego** [Eugeny/terminus#336]
sorry if I posted in the wrong place.
If this is possible, I would like to help in any way I can, including with donation.
Any documentation / guidance would help!
Thank you.

**Comment by Eugeny** [comment]
Hi, this is totally possible - start with the https://github.com/Eugeny/terminus/blob/master/HACKING.md document!
You're looking to extend `BaseTabComponent` to create a new tab that contains an embedded PDF viewer.
The only question is how the user would reach that tab.
