### ISSUE TITLE
Can't interact with user interface

### ISSUE THREAD

**Issue by manjotsc** [Eugeny/terminus#3369]
Hi,

When every it launches it I can't do anything with user interface, it only display blurred overlay.

Thanks,

https://user-images.githubusercontent.com/51430971/105795775-666cc880-5f5b-11eb-9bbd-4bfc67f17f31.mp4

**Comment by larssb** [comment]
I have the same thing on:

- MacOS Big Sur
- on Terminus v128

**Comment by wjiuxing** [comment]
Same here v128. I'm afraid of clicking on the gift on the right-top corner.

**Comment by larssb** [comment]
Seems that v129 is okay. Let's see if it continues throughout the day.

**Comment by manjotsc** [comment]
I updated to 129, now it can't load my configs.


https://user-images.githubusercontent.com/51430971/106103219-95776b80-610e-11eb-8e69-cf9f5c52da32.mp4

**Comment by Eugeny** [comment]
Fixed in 1.0.130
