### ISSUE TITLE
version 128 in macOS bigsur crash again

### ISSUE THREAD

**Issue by FlameMida** [Eugeny/terminus#3371]
ps:16 inch intel mac

**Comment by SergioSuarezDev** [comment]
+1 crash like version 122

**Comment by monoxane** [comment]
Same on HS, crashes with `/Applications/Terminus.app/Contents/Resources/app.asar/dist/[object%20Module]:1 GET file:///Applications/Terminus.app/Contents/Resources/app.asar/dist/[object%20Module] net::ERR_FILE_NOT_FOUND`

**Comment by Eugeny** [comment]
Fixed in v129

**Comment by FlameMida** [comment]
> Fixed in v129

Thank you
