### ISSUE TITLE
Cant SSH. Fresh install, Get error "TypeError: Cannot read property 'getRegistryKey' of undefined

### ISSUE THREAD

**Issue by lynxus** [Eugeny/terminus#3373]
Version: 1.0.129
Platform: win32 10.0.18363
Plugins: none

Cant SSH. Fresh install, Get error "TypeError: Cannot read property 'getRegistryKey' of undefined

That's pretty much it.
I created a session. Tried to open it and then get a red popup at the bottom saying the above.

**Comment by elixdreamer** [comment]
Same issue in 1.0.129

**Comment by ZehuanZhang** [comment]
same issue in 1.0.129 (windows platform)

**Comment by LaChimere** [comment]
Same issue in terminus 1.0.129 [windows]

**Comment by Eugeny** [comment]
Fixed in 1.0.130
