### ISSUE TITLE
Can't open a terminal after update

### ISSUE THREAD

**Issue by EDEN786** [Eugeny/terminus#3385]
Version: 1.0.129
Platform: win32 10.0.19041
Plugins: altair, clickable-links, quick-cmds, relaxed-theme, save-output, scrollbar, theme-hype, theme-windows10, title-control

![image](https://user-images.githubusercontent.com/23419505/106312356-65d77900-625e-11eb-923e-bbd8095e6012.png)
Empty home page (previously loaded up my default terminal WSL-Ubuntu)

![image](https://user-images.githubusercontent.com/23419505/106312175-2c067280-625e-11eb-8ef4-529df4e7ae18.png)
Profile loads empty list with no options.

![image](https://user-images.githubusercontent.com/23419505/106312224-404a6f80-625e-11eb-8a14-a1c6c772f6c2.png)
Top corner New-Default-Terminal and New-Terminal-Menu press -  but perform no action

Running as Admin did not change the behaviour

- CMD,
- PowerShell
- WSL (Ubuntu)
- Git-Bash
are all running fine on my system though normal windows terminal

**Comment by Eugeny** [comment]
Fixed in v1.0.130

**Comment by EDEN786** [comment]
oh, I wonder why did didn't give me a update notification ??

I was about to post the output of the console log,  but yea v1.0.130 seams to be back to normal
