### ISSUE TITLE
Can't start a terminal

### ISSUE THREAD

**Issue by cuhlman** [Eugeny/terminus#3388]
Version: 1.0.129
Platform: win32 10.0.18363
Plugins: none

After installing, I can't open any terminal sessions at all. Neither the "+ New terminal" button from the home screen, or the buttons in the top bar will do anything. The view in the main window does not change. I can get to the settings, but I didn't find anything that helps.

If there is debug output I can collect from somewhere, I'd be happy to share it.

**Comment by Martijn-Faber** [comment]
same problem

**Comment by binchick-in** [comment]
Just upgraded to the mentioned version and I'm seeing the same issue :(

**Comment by Eugeny** [comment]
Fixed in 1.0.130

**Comment by 1369521908** [comment]
i have the same problem please help
