### ISSUE TITLE
Screenshot theme

### ISSUE THREAD

**Issue by k33k00** [Eugeny/terminus#34]
Im running on windows the latest release [Alpha 15]. It's likely something simple but how the hell do I get the terminal looking like this ![example screenshot](https://github.com/Eugeny/terminus/raw/master/docs/linux.png) in particular the fancy path & git repo stuff.

I've tried installing hype theme but still nothing. Hopefully a simple tweak. As I really want it to look like the screenshot.

**Comment by Eugeny** [comment]
This is actually oh-my-zsh (https://github.com/robbyrussell/oh-my-zsh) which is a ZSH extension pack (thus, UNIX only unless you get it to run under Cygwin or Bash on Windows) with the `powerlevel9k` theme.

**Comment by k33k00** [comment]
thanks, much appreciated!
