### ISSUE TITLE
Not getting input : (

### ISSUE THREAD

**Issue by techvineyy** [Eugeny/terminus#3403]
Version: 1.0.130
Platform: win32 10.0.10240
Plugins: none

Unable to get text input

**Comment by clarkwang** [comment]
`1.0.130` is also not usable for me on macOS Catalina (`10.15.7`). This is the first time I try it on macos though `1.0.127` works quite well on Windows 10 (x64). Not sure if it's macos specific or some regression issue after `1.0.127`.

**Comment by clarkwang** [comment]
Issue #3399 says it stops working after 1.0.127 on Windows. I downloaded 1.0.127 on macos but it's also unusable for me. It can start but it's very very slow.

**Comment by Eugeny** [comment]
@clarkwang can you post your dev console output on macOS? 

@techvineyy it's a duplicate of #3397

**Comment by techvineyy** [comment]
#3397 worked for me thanks
