### ISSUE TITLE
Move Tabs to LEFT does not work properly

### ISSUE THREAD

**Issue by Tushar987** [Eugeny/terminus#3410]
Version: 1.0.131-nightly.0
Platform: win32 10.0.19042
Plugins: clickable-links

Moving Tabs to Left or right creates a small height panel that is not very friendly and can display only one tab at a time. It involves lots of scrolling to go to the right tab if you have multiple tabs open. The height of panels created while switching tab to left/right needs to be addressed.

**Comment by Eugeny** [comment]
Could you post a screenshot? All tabs are supposed to be visible at the same time: 
![image](https://user-images.githubusercontent.com/161476/106958291-6fb71b80-6739-11eb-8feb-50b749781077.png)

**Comment by Tushar987** [comment]
Attaching screenshots for reference...

[Tab Location: TOP]

![image](https://user-images.githubusercontent.com/14112700/107047308-b0706c80-67ed-11eb-9a71-1d7804d5c459.png)

[Tab Location: LEFT]

![image](https://user-images.githubusercontent.com/14112700/107047576-faf1e900-67ed-11eb-8a3f-00b7dd0f8282.png)

Only one tab is visible when tabs are aligned to left side. A small slider is visible though. I was able to access other tabs using this slider.

**Comment by Eugeny** [comment]
Fixed in nightly.
