### ISSUE TITLE
Can I manually set terminal type ($TERM)?

### ISSUE THREAD

**Issue by clarkwang** [Eugeny/terminus#3431]
By default `TERM=xterm-256color` which does not work quite well on some systems. Can we add an option to customize the `$TERM` type?

**Comment by eugenov** [comment]
Will `export TERM=xterm` as Login script fit you?

**Comment by clarkwang** [comment]
> Will `export TERM=xterm` as Login script fit you?

You mean in files like `.bashrc`? Yes that's what I'm doing for the workaround now. Not sure if this will cause any side effects. `Terminus` thinks it's `xterm-color256` but the remote programs think it's, e.g., `linux`. Possible trouble?

**Comment by eugenov** [comment]
No, I mean open Terminus -> Settings -> SSH -> choose your connection where you want set TERM to xterm -> LOGIN SCRIPTS -> New Item -> String to be sent -> insert there `export TERM=xterm`

**Comment by clarkwang** [comment]
> No, I mean open Terminus -> Settings -> SSH -> choose your connection where you want set TERM to xterm -> LOGIN SCRIPTS -> New Item -> String to be sent -> insert there `export TERM=xterm`

This has the same effect as changing `TERM` in `.bashrc`. Not sure if this causes any side effects.

**Comment by eugenov** [comment]
The only side effect is that you change $TERM to xterm, but you wanted it, did you? Changing with `export` changes TERM for running session, with `.bashrc` - for every session of specific user, it's obvious.

**Comment by Eugeny** [comment]
Just to confirm, setting $TERM via .bashrc, login scripts and shell env vars all have the same effect and will correctly override Terminus' own $TERM :+1:
