### ISSUE TITLE
"lable name of connection" instead the root@

### ISSUE THREAD

**Issue by KonsentoX** [Eugeny/terminus#3432]
Version: 1.0.128
Platform: win32 10.0.19042
Plugins: none

hello fellas, 
My suggestion is to show here (see the pic) the "lable name of connection" instead the root@blabla, sometimes i mistaken how tab i am using and send command to worng machine : )
thank you so much community : )

![name-x](https://user-images.githubusercontent.com/12088248/107553983-137a4e80-6bb4-11eb-995f-2b9faf17803e.png)

**Comment by Eugeny** [comment]
You can enable this on the Advanced tab of your connection's setting
