### ISSUE TITLE
Broken disconnection handling since 1.0.132 in Linux

### ISSUE THREAD

**Issue by mullerch** [Eugeny/terminus#3442]
Before 1.0.132, when the remote SSH got disconnected, Terminus would show it and a press on Enter (or clicking "Reconnect" in the top right '...' menu) would reconnect the session.

Now, disconnection is not detected. The session window does not respond (but it's not frozen, the cursor is still blinking). The '...' menu toolbar does not who when hovering the button as it was. The '...' button disappears on hovering.

The same problem occurs when connection is not successful, there is no way to reconnect. The tab must be closed and opened new again.

**Comment by fitzg2** [comment]
Happens in windows too

Version: 1.0.128-nightly.0
Platform: win32 6.3.9600
