### ISSUE TITLE
Serial console weird behaviour

### ISSUE THREAD

**Issue by eugenov** [Eugeny/terminus#3445]
Version: 1.0.132
Platform: win32 10.0.19042
Plugins: save-output

When I connect to serial console, I can't send some keys: "o", and some else. Output is broken: I see strange symbols (rhombus with question mark) in place of some standart symbols.
If i connect to COM port with WSL and minicom everything is fine.

**Comment by Eugeny** [comment]
Please double-check your baud rate and data/stop bits settings.

**Comment by eugenov** [comment]
I have only these settings:
![image](https://user-images.githubusercontent.com/61651148/107915740-1b503f00-6f76-11eb-88b1-b2b8eb69c9b7.png)
I don't see stop bits, flow control and such... Where can I find serial port settings like minicom's?
![image](https://user-images.githubusercontent.com/61651148/107915859-5b172680-6f76-11eb-88ab-43b82e0d45ad.png)

**Comment by Eugeny** [comment]
You can check them in the config file (Settings -> Config File)

**Comment by eugenov** [comment]
Got it. Strange thing: with 1.0.134 I didn't manage to reproduce. Meanwhile I definitly had this bug before (it was somewhere around 1.0.120 build).

**Comment by Eugeny** [comment]
No problem - thanks for letting me know :+1:
