### ISSUE TITLE
Fix Cygwin plugin

### ISSUE THREAD

**Issue by DRSDavidSoft** [Eugeny/terminus#345]
### Description of the issue

With Cygwin installation, windows paths are "mounted" on a virtual path, often called `/cygdrive`.
This behavior is defined in `<cygwin_root>/etc/fstab` as follows:

```
# This is default anyway:
none /cygdrive cygdrive acl,binary,posix=0,user 0 0
```

However, It's a common misunderstanding that Cygwin paths _always_ start with `/cygdrive`. In fact, you can change the "mounting" point by changing the `/cygdrive`. For example on my machine I use this:
`none /mntcygdrive acl,binary,posix=0,user 0 0`

To use the aptly named `/mnt/c/` instead of the ugly looking `/cygrive/c/`.

### What makes the problem

Currently, the `normalizePath` solution in the Terminus codebase uses a custom made function to handle the directory conversion.

https://github.com/Eugeny/terminus/blob/2bea4b9d6c919af190e6dcf32c6c523024952054/app/src/plugins.ts#L8-L15

This **isn't needed**. Cygwin provides a simple tool to use here: [`cygpath`](https://cygwin.com/cygwin-ug-net/cygpath.html). It works like this:

```
cygpath -u C:\Path\to\some\file.exe
REM this returns ==> /mnt/c/Path/to/some/file.exe
```

### Proposal on how to fix it

Terminus should either:
a) invoke `cygpath` pn each call of conversion
b) read and parse the `fstab` file to get the correct "mounting" point.

I'm personally against option _b_, so I suggest using open **a** to use the native Cygwin conversion tool.

**Comment by Eugeny** [comment]
Thanks for the in-depth investigation, but I don't quite get why this is relevant for plugin loading? It's happening outside of the Cygwin environment anyway.

**Comment by DRSDavidSoft** [comment]
@Eugeny If the `normalizePath()` function is called outside Cygwin just to get Windows-styled path from static calls, that's true and this may not be relevant.

But if the path is from the _user machine_, it needs to be parsed with `cygpath -w` like so:
`cygpath -w /cygdrive/c/some/path` → `C:\some\path`

Although I should've first asked why such a conversion is required. Does Electron pass cygwin-stlye paths to Terminus, or is there another reason you need to replace the `path` string manually?
