### ISSUE TITLE
Stop at startup screen

### ISSUE THREAD

**Issue by ZehuanZhang** [Eugeny/terminus#3455]
Version 1.0.133 (windows)
![Snipaste_2021-02-14_19-58-44](https://user-images.githubusercontent.com/20352723/107876143-2c119e00-6eff-11eb-804e-b6ca97ffd8f6.png)

**Comment by GanapathyRaman** [comment]
Yup. Same here. It stops at the start screen.

**Comment by DarkSeabass** [comment]
Same here, can't open the console either

**Comment by Eugeny** [comment]
Fixed in the new build.
