### ISSUE TITLE
RFE: Tab title enhancement

### ISSUE THREAD

**Issue by clarkwang** [Eugeny/terminus#3464]
See the following screenshot (Hide Tab Index: OFF, Hide Tab Close Button: ON).

1. Would look better if a SPACE is added to the right side of the title. (In the attachment, focus is on Tab 3. As we can see the tab separator is too close to the Tab title.)
1. Would be more COMPACT if the Tab Index occupies less space.

![image](https://user-images.githubusercontent.com/157076/107962812-60aa5600-6fe2-11eb-96b1-88b32e6c41ed.png)

**Comment by Eugeny** [comment]
Fixed the spacing. The tab index width can be customized via CSS, e.g.: `tab-header .index { width: 5px !important; }`
