### ISSUE TITLE
Add Cmder to the shells on windows

### ISSUE THREAD

**Issue by DRSDavidSoft** [Eugeny/terminus#347]
### Cmder shell

[Cmder](https://github.com/cmderdev/cmder) is a terminal package in windows combining some useful features (aliases, user-profiles, Clink, and git integregtion) with a beautiful shell prompt. Here's a screenshot:

<img width="445" alt="terminus-cmder" src="https://user-images.githubusercontent.com/4673812/40274013-b3c5929a-5be1-11e8-8d83-3926b9d45ae8.png">

### Request description

In here:

https://github.com/Eugeny/terminus/blob/7a005132cca25abee78afe8e9fbd025b9603b762/terminus-terminal/src/shells/windowsStock.ts#L20

Could you please add Cmder as a shell if `%CMDER_ROOT%` variable is detected and set?
```
            {
                id: 'cmder',
                name: 'Cmder',
                command: 'cmd.exe',
                args: [
                    '/k',
                    '%CMDER_ROOT%/vendor/init.bat'
                ]
            },
```

Currently, I'm using the _custom shell_ method to load Cmder into Terminus. This is because the Clink configuration that Cmder uses is more eye pleasing and feature rich on Windows.

**Comment by DRSDavidSoft** [comment]
@Eugeny I guess not then?

**Comment by Eugeny** [comment]
I've just added it in 5d605a485352be619514faffd6daf4490017e165 :)

**Comment by DRSDavidSoft** [comment]
@Eugeny That's amazing, thanks for the quick implementation!
