### ISSUE TITLE
RFE: Add an option to disable dynamic progress% detection on Windows' Taskbar

### ISSUE THREAD

**Issue by clarkwang** [Eugeny/terminus#3472]
See the following screenshot. When I was viewing a file with `less /some/file.txt` it'll *smartly* detect the progress% on the terminal and show a dynamic updating progress bar on the Windows (win10)'s Taskbar. Could we add an option to disable this behavior?

![image](https://user-images.githubusercontent.com/157076/108351082-fda60280-721f-11eb-913a-436f7ad2acb9.png)

**Comment by clarkwang** [comment]
Just noticed the Tab title area will also be updated. See Tab 4 in the screenshot. There's also a progress bar.

**Comment by clarkwang** [comment]
Not that annoying. Can get used to it.

**Comment by Eugeny** [comment]
No worries - this is still a valid request

**Comment by Eugeny** [comment]
Added the `terminal.detectProgress` config option (on by default)
