### ISSUE TITLE
Background transparency

### ISSUE THREAD

**Issue by py-alpha-wolf** [Eugeny/terminus#3490]
Hey, I am on my LinuxPC ( Ubuntu ) not possible to use the "blur" for the background. The opacity slider has no effect no matter how I move it. How can I change this?

**Comment by Mohammed-Taher** [comment]
I have the same problem. The opacity slider has no effect on linux.

**Comment by Eugeny** [comment]
Duplicate of #832

**Comment by TheAalCh3m1st** [comment]
This is still an issue in Nov/2024.

**Comment by Eugeny** [comment]
I know what date it is today, why don't you consider helping solve the issue instead?

**Comment by TheAalCh3m1st** [comment]
Chief, I didn't 'mean to be rude I was just letting the community know the issue still exist today. I'm new to helping on community projects and would love to contribute in any fashion that I can. My apologies!

**Comment by boutmos** [comment]
Same on Linux Mint 22
