### ISSUE TITLE
SSH Reconnecting loop

### ISSUE THREAD

**Issue by Onepamopa** [Eugeny/terminus#3492]
Hello,

While trying to connect to a server using SSH-key but placing a wrong password at the first attempt (after starting terminus and session is restored), the connection fails as it should, but then trying to "Reconnect" and place the correct ssh key password - this happens:

![reconnectng_loop](https://user-images.githubusercontent.com/3053279/108694927-5a4b3b00-7508-11eb-99fb-29ada9f8cf5e.png)

If I press enter, I can see the command prompt, but I cannot do anything but watch "Connecting" until I completely close the session and open a new one (Reconnect doesn't work).

Terminus version 1.0.134 @ Windows x64
Target server: FreeBSD 12.2-RELEASE

**Comment by amajauskas** [comment]
At this point you might be connected but theres some buy with the "connecting" status. Ive noticed when this happens to me i can still run commands and they work fine.

Seems like "connecting" is constantly replacing $PS1 or the current line, not sure.

**Comment by Eugeny** [comment]
Fixed
