### ISSUE TITLE
No UTF-8 support

### ISSUE THREAD

**Issue by hailwood** [Eugeny/terminus#35]
Trying to display UTF-8 symbols such as 💨 (https://emojipedia.org/dash-symbol/) results in � being displayed.

I'm running Kubuntu 16.10 currently.
The same symbol with the same font is displaying fine in qterminal.

I'll give this a go in Ubuntu (Gnome-Shell) latest this evening and update here, but I believe this isn't an issue with ubuntu as this seems to be the same issue as #31 but given the contents of that issue I've created a new one.

**Comment by acarl005** [comment]
+1. My emojis are gone :(

**Comment by Hammster** [comment]
Same on Windows, reading a file that contains emojis and writing them in the terminal do differ for me though.

![unbenannt](https://user-images.githubusercontent.com/1093709/27800154-731aeec2-6018-11e7-8e5f-c56a4aa0dec0.png)

![unbenannasdt](https://user-images.githubusercontent.com/1093709/27800155-731b0f38-6018-11e7-834c-ba772eded993.jpg)

**Comment by Nek-** [comment]
@Eugeny afaik it's not fixed. 

![image](https://user-images.githubusercontent.com/972456/34690645-39ff9958-f4ba-11e7-98ac-cde9540f3335.png)
