### ISSUE TITLE
RFE: Add hotkey support for Tab 11~20

### ISSUE THREAD

**Issue by clarkwang** [Eugeny/terminus#3500]
It's not uncommon to open 10+ Tabs. For now only Tab 1\~10 can have hotkeys. Could we add hotkey support for Tab 11\~20 at least? Then we can use hotkeys like this:

* Ctrl 1\~9 for Tab 1\~9
* Ctrl 0 for Tab 10
* Alt 1\~9 for Tab 11\~19
* Alt 0 for Tab 20

**Comment by clarkwang** [comment]
Managed to make hotkeys work for Tab 11\~20. The code change only involves `terminus-core/src/hotkeys.ts` and `terminus-core/src/configDefaults.<OS>.yaml`. `terminus-core/src/components/appRoot.component.ts`'s current logic works fine with it. 

Is it possible to add the support on `master`? 

![image](https://user-images.githubusercontent.com/157076/109621582-1e524e80-7b76-11eb-85dc-8d36f3aea22f.png)

**Comment by Eugeny** [comment]
Feel free to add a pull request - I'll merge it!
