### ISSUE TITLE
RFE: Use profile names as Tab titles for cygwin, powershell, ...

### ISSUE THREAD

**Issue by clarkwang** [Eugeny/terminus#3501]
See the following screenshot. Would look better if we don't use the long full pathname of cygwin/powershell/... We can just use the Profile names.

![image](https://user-images.githubusercontent.com/157076/108944401-9e1f7b00-7695-11eb-9a75-1acf82ba1b46.png)

**Comment by Eugeny** [comment]
Disabling "use dynamic tab title" in profile settings will show the profile name in the tab title instead
