### ISSUE TITLE
zmodem/rz  error

### ISSUE THREAD

**Issue by wenbingzhang** [Eugeny/terminus#3509]
<img width="1302" alt="iShot     2021-02-25 上午09 48 04" src="https://user-images.githubusercontent.com/13162606/109090899-c0290400-774e-11eb-841c-5fe86ecaef90.png">

**Comment by wenbingzhang** [comment]
file size 80M

**Comment by wenbingzhang** [comment]
https://github.com/tsl0922/ttyd/issues/278

https://github.com/FGasper/zmodemjs/issues/11

**Comment by zxdong262** [comment]
Will be fixed in next release https://github.com/electerm/electerm/commit/5bc80f9a79ecd994d0714f68e3dfa4ebf093ace1
