### ISSUE TITLE
[feature] ability to apply some change to console title

### ISSUE THREAD

**Issue by kbjr** [Eugeny/terminus#351]
The tabs are so short, that generally all of my tabs say exactly the same thing. "Administrator: posh-git..." and the rest of the actually useful title that I want see is cut off. Having some way to modify the title of the tabs automatically (for example, to remove the "Administrator" prefix) would be very helpful.

Cmder, for example, provides a whole templating and filtering system for tab titles that might be worth looking at for ideas.

**Comment by kbjr** [comment]
I ended up writing my own https://github.com/kbjr/terminus-title-control

Would love any feedback you have, this was my first attempt at TypeScript or Angular 4 :p

**Comment by Eugeny** [comment]
Really neat! You can also publish it to NPM with a `terminus-plugin` keyword, so that it will pop up in the plugin manager 👍

**Comment by kbjr** [comment]
Huh, it does have the keyword.. https://github.com/kbjr/terminus-title-control/blob/master/package.json#L5-L7

Not sure why it won't show up, I didn't even check..

**Comment by kbjr** [comment]
Weird, I have the keyword on the package

![image](https://user-images.githubusercontent.com/195127/42129574-66ce708a-7c7d-11e8-84e7-8b8cf086f5cf.png)

But clicking on that link to search by keyword doesn't show it

![image](https://user-images.githubusercontent.com/195127/42129576-79ad4eec-7c7d-11e8-9dd3-423ee513fd0a.png)

Maybe just an issue with npm caching the search results?

**Comment by Eugeny** [comment]
Seems like npmjs is caching things too aggressively, I'll switch to npms.io
