### ISSUE TITLE
Please add switching tabs with Ctrl+Page up/down

### ISSUE THREAD

**Issue by mariusa** [Eugeny/terminus#3519]
First of all, thanks for terminus, it's great to open with all tabs & folders as they were!

Swiching from gnome terminal, I miss switching tabs with Ctrl+Page up/down. I've read about Ctrl+Tab (+Shift) and Alt+n (which is very useful). 
Could Ctrl+Page up/down be added too by default? I've just added them in Settings and they work, just asking if this could be included by default.

**Comment by fitzg2** [comment]
You can't ask to change defaults for everyone because you like it.

**Comment by mariusa** [comment]
sure, closing
