### ISSUE TITLE
Console apps with Alt+Key bindings

### ISSUE THREAD

**Issue by glutaminefree** [Eugeny/terminus#356]
Version of Terminus: 1.0.0_alpha.47
OS: Fedora 28 x86_64

Ranger (console file manager) have key bindings for Alt+num for switching tabs. I removed Alt+num bindings in Terminus itself settings (and restart it after), but it not helped. Switching tabs with Alt+num inside Ranger still not working :(

**Comment by Eugeny** [comment]
Please see the "Alt/Meta key" setting at the end of the Terminal settings page. It controls whether Alt is handled by OS or passed to the shell/app as Meta.

**Comment by glutaminefree** [comment]
@Eugeny Thanks! Works great. But "Use Alt key as Meta Key" hint not obvious for me in this situation.
Anyway Terminus is great app. Thanks!

**Comment by MaiLunJiye** [comment]
[Please see the "Alt/Meta key" setting at the end of the Terminal settings page. It controls whether Alt is handled by OS or passed to the shell/app as Meta.]

I hope "ALT" can be set as "ESC+" , as well as iterm2.
And we can use ALT+<keys> in ssh, vim, tmux, etc.

![image](https://user-images.githubusercontent.com/20548127/189252961-8104c0f3-732a-4f79-8548-63276f611021.png)
