### ISSUE TITLE
when add connection，save butten do not work

### ISSUE THREAD

**Issue by syapollo** [Eugeny/terminus#3589]
Version: 1.0.134
Platform: linux 5.9.16-1-MANJARO
Plugins: none
when add connection，save butten do not work

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by shootdot** [comment]
Even I have the same Problem
![image](https://user-images.githubusercontent.com/55920587/112143382-3b1bf800-8bf1-11eb-9844-5d1786c94817.png)

**Comment by Pamalosebi** [comment]
Hey, I think I found the issue. Terminus needs a place to save the passwords / keys. (org.freedesktop.secrets)
So there basically is a dependency for "gnome-keyring". You can install it via "pamac install gnome-keyring". Or you use another AUR wrapper like yay --> "yay -Sy gnome-keyring".

**Comment by amajauskas** [comment]
> Hey, I think I found the issue. Terminus needs a place to save the passwords / keys. (org.freedesktop.secrets)
> So there basically is a dependency for "gnome-keyring". You can install it via "pamac install gnome-keyring". Or you use another AUR wrapper like yay --> "yay -Sy gnome-keyring".

Is it an AUR version thing? Might need to update the dependency list on that, installing gnome-keyring fixed it for me as well.

**Comment by Eugeny** [comment]
The upcoming release will include official pacman packages which will depend on libsecret.
