### ISSUE TITLE
Bug: After setting "dock" to be "right", the window disappears

### ISSUE THREAD

**Issue by VladislavZavadskyy** [Eugeny/terminus#363]
It's still there, somewhere, judging by the preview (on hover above the icon on taskbar), but it's beyond the boundary of the screen, and can't be brought back. 
A solution I've found is to delete all contents of `%appdata%/Terminus` as merely changing `config.yaml` didn't help.

**Comment by jamesrom** [comment]
See [my comment](https://github.com/Eugeny/terminus/issues/364#issuecomment-412391494) on #364:

> I found killing Terminus and deleting %appdata%\Terminus\window.json fixes the issue.
> 
> The bug appears to be something related to windowBoundaries having nonsense large (or negative) numbers.

**Comment by jamesrom** [comment]
This really isn't stale and should be a simple fix. `windowBoundaries` should be min'd with the desktop boundaries.
