### ISSUE TITLE
Tab names get cleared when reloading the app

### ISSUE THREAD

**Issue by AdamSalma** [Eugeny/terminus#3630]
Version: 1.0.135
Platform: win32 10.0.18363
Plugins: none

When I save a tab by name and reload the app, the tab's name initially gets preserved, however when the shell/profile loads, the tab name gets replaced with the directory name (`~`, in my case).

If I reload the app a second time, the `~` now becomes the default name. Its somehow overridden the custom name.

Perhaps related to https://github.com/Eugeny/terminus/issues/3629

**Comment by AdamSalma** [comment]
Powershell tabs seem to not be affected. Using this as a temp solution

**Comment by Eugeny** [comment]
Starting 1.0.135 there's an option in the profile settings to disable dynamic tab titles completely.
