### ISSUE TITLE
Docking causes the window to appear off-screen

### ISSUE THREAD

**Issue by devmoses** [Eugeny/terminus#364]
As mentioned by @VladislavZavadskyy (Issue #363) , the same problem is posed, when the "**dock's location**" is set to "**Left**". Deleting "**config.yaml**" file and restarting the application doesn't show any effect. On **Windows**, changing the screen orientation to landscape and reverting the changes helped.

**Comment by jamesrom** [comment]
I found killing Terminus and deleting %appdata%\Terminus\window.json fixes the issue.

The bug appears to be something related to windowBoundaries having nonsense large (or negative) numbers.

**Comment by Renondedju** [comment]
The same problem happens here.
The app was working perfectly when I had my additionals screens connected to my pc. But when I use only one screen, the app still appears on one of those screens! So in this case, there is no way to bring it back to the main screen.

I realized it when clicking on the icon in the taskbar, the opening windows animation goes to the right as if another screen was connected.

**Comment by sahilbabbar** [comment]
Same issue. But unable to resolve it using the workaround mentioned above, because there is not `.yaml` or `.json` file present in `/AppData/Local/Terminus`.

**Comment by Eugeny** [comment]
Thank you all for your feedback. It looks like there are multiple ways in which docking can cause the window to go off-screen. The current workaround is:

1) Disable docking in the [config file](https://github.com/Eugeny/terminus/wiki/Config-file)

2) Clear the saved window position by removing the `window.json` file in the same directory where the config file is

**Comment by LeoEatle** [comment]
Same problem here. Use `dock left` will make the app width infinite large and the appearance is weird.

**Comment by Eugeny** [comment]
fixed via #1145
