### ISSUE TITLE
Terminal prints a single char and deletes it

### ISSUE THREAD

**Issue by iAbadia** [Eugeny/terminus#3651]
Version: 1.0.135
Platform: win32 10.0.19042
Plugins: none

I'm trying to use Terminus and I get the prompt but when I try to write, a single character is printed and then instantly deleted.

This happens on:
- CMD (clink)
- CMD (stock)
- Git Bash
- WSL

Powershell is fine, if I open wsl from Powershell the issue persists.

Any ideas?

**Comment by iAbadia** [comment]
Can anyone please acknowledge this issue? After updating to the last version 137 I still have the same problem.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by iAbadia** [comment]
OH MY GOD

Thank you, looking at the logs I saw that every time I wrote something the terminal logged "Matched hotkey delete-previous-word". And indeed, the delete-previous-word was set to something (it seemed like an emtpy box), I removed the shortcut and it works fine now.

I don't recall modifying any shortcuts but maybe I did so accidentally.

**Comment by Eugeny** [comment]
No problem - glad you sorted it out
