### ISSUE TITLE
Need ability to remove Shell integration?

### ISSUE THREAD

**Issue by xaragen** [Eugeny/terminus#3657]
This is regarding the setting added in #362.

Once the registry is modified, there is no option in Settings to remove the integration, and upon uninstall the integration is also not removed.
The issue was closed as resolved but as of today (30th March 2021) This is still a problem.

**Comment by Eugeny** [comment]
You can uncheck the "Shell integration" checkbox under Settings -> Application. This removes the context menu entries completely.
