### ISSUE TITLE
[Feature Request] SSH port forwarding in Connections settings

### ISSUE THREAD

**Issue by leonardonormando** [Eugeny/terminus#367]
Hello!
I think `Terminus `has great potential and I would be great to have the ability to forward ports on the SSH connections tab; more or like this functionality of [bitvise](https://www.bitvise.com/port-forwarding). Specially the client-to-server port forward function; like this:

![like this](https://user-images.githubusercontent.com/798716/41852724-4d311444-7862-11e8-8fd4-d0da6eb14ea9.PNG).

**Comment by dabrazhe** [comment]
I would love to have SSH forwarding as well. Unless it's already implemented and I've missed it.)

**Comment by Scarsz** [comment]
Just an update for this issue, port forwarding is implemented now https://github.com/Eugeny/terminus/releases/tag/v1.0.98

**Comment by padrino121** [comment]
Reaching out on this old item, I have some connections that always need an active port forward, at this time I need to manually create it each time after I connect, that is a very useful capability however is there anyway to make them persistent and automatic each time that connection is opened...
