### ISSUE TITLE
Setting UI sidebar not stretching vertically

### ISSUE THREAD

**Issue by princemaple** [Eugeny/terminus#368]
Version: a48
Platform: Windows10
![image](https://user-images.githubusercontent.com/1329716/42196715-c217d232-7ec2-11e8-9868-266ddb62aed0.png)

**Comment by princemaple** [comment]
![image](https://user-images.githubusercontent.com/1329716/42219161-3c7cd0ae-7f0e-11e8-905d-df4bb7bfabf6.png)
the part in the red square is darker than above, too.
it goes away when commands are entered when the history grow.

**Comment by Eugeny** [comment]
Now fixed
