### ISSUE TITLE
Alpha 48 completely unusable on Ubuntu

### ISSUE THREAD

**Issue by jakob-fuchs** [Eugeny/terminus#369]
I've upgraded to the latest version, the program starts normally but there is no command prompt, just an empty window. 

Clicking the 'X' button to close a tab does nothing.

I've tried typing commands that will open external programs (subl . etc.), that doesn't work either so it's not just an issue with hidden text.

https://paste.laravel.io/b549323c-845c-4e0b-a632-76663db5d380

**Comment by drsm79** [comment]
I've the same problem on windows 10

**Comment by danfloyd111** [comment]
Here on my Ubuntu 18.04 (Linux 4.15.0-24-generic x86_64) works fine after the update.

**Comment by Eugeny** [comment]
This is caused by the clickable-links plugin. A fixed version (0.0.14) will soon pop up on the plugins page.

**Comment by jakob-fuchs** [comment]
Updating the clickable-links plugin worked. Thanks.
