### ISSUE TITLE
p10k stopped displaying properly after upgrade to latest release, but only for Terminal

### ISSUE THREAD

**Issue by jeffr1975** [Eugeny/terminus#3690]
Version: 1.0.136
Platform: linux 5.4.99-12983-g8b7876ab9f5e
Plugins: none
p10k stopped displaying properly after upgrade to latest release

I upgraded today.  I use zsh p10k in local Chromebook terminus install.  That worked with the release right before the most recent.  The same zsh p10k config still works on two remote ssh ubuntu hosts.  When I run the p10k configure on the local terminal, I get less options, so I know something is up.  Upgrading terminus was the only change.  But it only effected the local terminal.  I am going to try to save my config and go back to the previous version.

**Comment by jeffr1975** [comment]
I went back to terminus-1.0.135-linux.deb and my local terminal is displaying properly again.

**Comment by Eugeny** [comment]
Fixed in the nightly
