### ISSUE TITLE
Terminal have limitation

### ISSUE THREAD

**Issue by wakkings** [Eugeny/terminus#3695]
Version: 1.0.136
Platform: linux 5.8.0-48-generic
Plugins: altair, elastic-quick-commands, relaxed-theme, save-output, sync-config, theme-gruvbox, theme-hype, theme-windows10, title-control

I'm facing limitation in the screen when I run "top" or any command that output will be long

![top](https://user-images.githubusercontent.com/28263980/114503271-9f196580-9c5f-11eb-8727-7907f1d52f51.png)

**Comment by Jerrywang959** [comment]
Same issue

**Comment by wakkings** [comment]
Looks like after upgrade issue appears. 

> Same issue

**Comment by Skips75** [comment]
I've the same problem on a Window10 20H2 machine. 
Terminus version is 1.0.135.
Very very difficult to move around the text of a long file, chuncks of text appear before the previous ones,
the prompt disappears. Weird behaviours.

**Comment by Skips75** [comment]
I correct myself: in the previous comment I said that the problem is on v1.0.135.
I was wrong: version 1.0.135 does not present the problem, v1.0.136 is the faulty version.

**Comment by wakkings** [comment]
> I correct myself: in the previous comment I said that the problem is on v1.0.135.
> I was wrong: version 1.0.135 does not present the problem, v1.0.136 is the faulty version.

Yes.. Version 136 having issue

**Comment by Drogmor** [comment]
> I correct myself: in the previous comment I said that the problem is on v1.0.135.
> I was wrong: version 1.0.135 does not present the problem, v1.0.136 is the faulty version.

Same issue here, on Windows 10 20H2.
When Terminus is split, the leftmost panel does not render every line when the file or output is long.

**Comment by wakkings** [comment]
Issue has been fixed by using version 137
