### ISSUE TITLE
When the screen is full, enter a command or execute a command, the content will appear in the middle of the screen and conflict with the original content 

### ISSUE THREAD

**Issue by bingoYB** [Eugeny/terminus#3697]
![image](https://user-images.githubusercontent.com/24823972/114540774-84a7b200-9c88-11eb-8514-296b464bf517.png)

**Comment by stauvel** [comment]
Revert to 1.0.135 fixes the problem for me.
I'm using Windows and the problem was under wsl's terminal.

**Comment by jeffr1975** [comment]
This is similar what I reported in: [3690](https://github.com/Eugeny/terminus/issues/3690)

**Comment by bingoYB** [comment]
> Revert to 1.0.135 fixes the problem for me.
> I'm using Windows and the problem was under wsl's terminal.

Thank you very much, I reinstalled version 135 and it did solve the problem
