### ISSUE TITLE
reset command not clear the data in terminal - debian version

### ISSUE THREAD

**Issue by asnidhin** [Eugeny/terminus#37]
In debian based versions the reset command not clear already existing data and there is some blank space is created on the terminal.

**Comment by Eugeny** [comment]
Works for me - please include your distro and shell info.

**Comment by OvermindDL1** [comment]
Works for me on kubuntu 16.04.

**Comment by Eugeny** [comment]
Closing due to the lack of activity. Please feel free to reopen if the bug is still relevant!
