### ISSUE TITLE
Blank terminal screen after alpha48 upgrade

### ISSUE THREAD

**Issue by munikarmanish** [Eugeny/terminus#370]
OS: Windows 10
Terminus version: 1.0.0-alpha.48

When I start a new terminal (doesn't matter whichever shell I choose), I only get this:

![Blank terminal](https://i.imgur.com/AnQQMuU.png)

Reinstalling doesn't help. Any help would be appreciated.

**Comment by Eugeny** [comment]
Duplicate of #369
