### ISSUE TITLE
zmodem rz bug

### ISSUE THREAD

**Issue by garywu520** [Eugeny/terminus#3701]
After the upload of rz is completed, the feedback is not completed, and it has been stuck in this state. 

Terminus version:1.0.136
![1618448755682](https://user-images.githubusercontent.com/26731482/114799443-2edb2300-9dca-11eb-8357-6917e4c75a86.jpg)
![1618448792812](https://user-images.githubusercontent.com/26731482/114799454-35699a80-9dca-11eb-8820-19a9b65809d0.jpg)

**Comment by shihaonan369** [comment]
Is there a way around this?SFTP also provides no feedback, despite the fact that the file has been completely uploaded.
