### ISSUE TITLE
Text output overlapping from different commands

### ISSUE THREAD

**Issue by JacobPease** [Eugeny/terminus#3711]
Version: 1.0.136
Platform: win32 10.0.19041
Plugins: theme-gruvbox

![image](https://user-images.githubusercontent.com/24443400/115085748-a85d3900-9ed0-11eb-8392-c1b8fdce7a81.png)

I type 'git' then I typed 'ls'. The output from 'ls' appears before the command. It's gotten even more jumbled than this before too.

**Comment by Eugeny** [comment]
Fixed in a137
