### ISSUE TITLE
ssh connection with key

### ISSUE THREAD

**Issue by Railline** [Eugeny/terminus#3714]
Version: 1.0.137
Platform: win32 10.0.19042
Plugins: clickable-ips, clickable-links, scrollbar

hi i have a problem i can't connect to my ssh shell with my private key
![image](https://user-images.githubusercontent.com/57727650/115159013-5dd6ea80-a091-11eb-8acc-ad54c1edf6f9.png)

**Comment by theoricher** [comment]
Hello,

I have a similar problem, I can't initialise the connection with an SSH key :

![image](https://user-images.githubusercontent.com/12476264/115231219-96b8a300-a115-11eb-940c-e636724b8db2.png)

**Comment by Railline** [comment]
> Bonjour,
> 
> J'ai un problème similaire, je ne peux pas initialiser la connexion avec une clé SSH:
> 
> ![image](https://user-images.githubusercontent.com/12476264/115231219-96b8a300-a115-11eb-940c-e636724b8db2.png)

do you use keys OpenSSH ?

**Comment by theoricher** [comment]
> > Bonjour,
> > J'ai un problème similaire, je ne peux pas initialiser la connexion avec une clé SSH:
> > ![image](https://user-images.githubusercontent.com/12476264/115231219-96b8a300-a115-11eb-940c-e636724b8db2.png)
> 
> do you use keys OpenSSH ?

Hello,
This SSH key is generate with putty-gen.

**Comment by Railline** [comment]
> > > Bonjour, 
> > > J'ai un problème similaire, je ne peux pas initialiser la connexion avec une clé SSH:
> > > ![image](https://user-images.githubusercontent.com/12476264/115231219-96b8a300-a115-11eb-940c-e636724b8db2.png)
> > 
> > 
> > utilisez-vous des clés OpenSSH?
> 
> Bonjour,
> Cette clé SSH est générée avec putty-gen.

use the conversion option and select OPENSSH for convert putty key on OPENSSH

**Comment by theoricher** [comment]
> > > > Bonjour,
> > > > J'ai un problème similaire, je ne peux pas initialiser la connexion avec une clé SSH:
> > > 
> > > utilisez-vous des clés OpenSSH?
> > 
> > 
> > Bonjour,
> > Cette clé SSH est générée avec putty-gen.
> 
> use the conversion option and select OPENSSH for convert putty key on OPENSSH

![image](https://user-images.githubusercontent.com/12476264/115389128-ffb71e00-a1dc-11eb-9207-e59f7e30baec.png)

It works, but it keeps getting stuck on "Connecting" after I enter the key.

**Comment by Railline** [comment]
> > > > > Bonjour, 
> > > > > J'ai un problème similaire, je ne peux pas initialiser la connexion avec une clé SSH:
> > > > 
> > > > 
> > > > utilisez-vous des clés OpenSSH?
> > > 
> > > 
> > > Bonjour, 
> > > Cette clé SSH est vérifié avec putty-gen.
> > 
> > 
> > utilisez l'option de conversion et sélectionnez OPENSSH pour convertir la clé de mastic sur OPENSSH
> 
> ![image](https://user-images.githubusercontent.com/12476264/115389128-ffb71e00-a1dc-11eb-9207-e59f7e30baec.png)
> 
> Cela fonctionne, mais il reste bloqué sur "Connexion" après avoir entré la clé.

i have this problem sometime and after i get  error

**Comment by gaelthas** [comment]
It happens when using ppk file. I converted ppk to pem, it's fine.

**Comment by Railline** [comment]
> Cela se produit lors de l'utilisation du fichier ppk. J'ai converti ppk en pem, c'est bien.

how to do ?

**Comment by Railline** [comment]
> Cela se produit lors de l'utilisation du fichier ppk. J'ai converti ppk en pem, c'est bien.
i have try it and that didn't work
![image](https://user-images.githubusercontent.com/57727650/115547259-5fc5c700-a2a6-11eb-8bf5-82975a401b94.png)

**Comment by gaelthas** [comment]
![image](https://user-images.githubusercontent.com/11371061/115654842-8e09dc00-a364-11eb-8908-54c889c445d5.png)
@Railline

**Comment by Railline** [comment]
> ![image](https://user-images.githubusercontent.com/11371061/115654842-8e09dc00-a364-11eb-8908-54c889c445d5.png)
> @Chemin de fer

i have try this and i still get this error

**Comment by jobinli** [comment]
i have the same problem. i use Git-bash to run `ssh-keygen -t rsa` command and generate the id_ras.pub into User folder/.ssh. it can successfully to login remote server by ssh in Git-bash tab, but can't work well by ssh plugin.

![image](https://user-images.githubusercontent.com/59111601/116497382-c9af2380-a8d9-11eb-9f46-50872797ae08.png)

**Comment by theoricher** [comment]
Hello @Eugeny 

Have you ever had a similar problem in the past ?

**Comment by Eugeny** [comment]
Could you please test it against the today's build? Direct link: https://nightly.link/Eugeny/terminus/workflows/windows/master

**Comment by bliteknight** [comment]
> Could you please test it against the today's build? Direct link: https://nightly.link/Eugeny/terminus/workflows/windows/master
> 
> > **[nightly.link | Repository Eugeny/terminus | Workflow windows.yml | Branch master](https://nightly.link/Eugeny/terminus/workflows/windows/master)**

Just tried this version and I can login with my putty generated keys.

**Comment by Eugeny** [comment]
Thanks!
