### ISSUE TITLE
Opening ssh profile breaks layout

### ISSUE THREAD

**Issue by mullerch** [Eugeny/terminus#3715]
Since the last upgrade from 135 to 137, when I open an existing ssh preset, the layout is screwed (content was intentionally blurred):

![Selection_001](https://user-images.githubusercontent.com/1092115/115261315-cd9db180-a133-11eb-858f-64efb7cfc286.png)

The view splits in two panes, one empty and not usable (left) and one with the previously opened tab (right).

The tabs and toolbar button are not correctly aligned anymore.

**Comment by LForgit** [comment]
same problem

**Comment by firefoxzheng** [comment]
136 has the same problem too, easy to reproduce when opening by shotcuts.

**Comment by FravashY** [comment]
Same here. 135 works fine, but 136 and 137 not.

**Comment by boxsnake** [comment]
same here for version 137

OS: Windows 10 20H2

**Comment by boxsnake** [comment]
> 136 has the same problem too, easy to reproduce when opening by shotcuts.

I thout it may be caused by the experimental PTY change in Alpha 136.

**Comment by darkiop** [comment]
v136: same here, but only by using a shortcut like STRG+T - i dont have this issue with the SSH Connection Button.
