### ISSUE TITLE
Color scheme not changing directory colors etc

### ISSUE THREAD

**Issue by dustinm94** [Eugeny/terminus#3717]
Hey everyone, just wondering if someone else also ran into this issue. I am using the color scheme "Cobalt Neon" and my directories are not being colored as they should be. I cant find anything specific in the settings that would be turning this off any ideas on this? (Mac Book Pro, Bash)

**Comment by Woterw** [comment]
# Current folder color
$echo $LS_COLORS

# Modify the file
vim /etc/profile

export LS_COLORS=${LS_COLORS}'di=01;36':


source /etc/profile

**Comment by Eugeny** [comment]
See https://apple.stackexchange.com/questions/33677/how-can-i-configure-mac-terminal-to-have-color-ls-output
