### ISSUE TITLE
Built in plugins don't seem to update

### ISSUE THREAD

**Issue by kbjr** [Eugeny/terminus#376]
I recently updated from alpha.36 to alpha.48

While that update by itself seems to have worked, all of the built-in plugins are still version alpha.36, and there doesn't seem to be anyway to update them

**Comment by Eugeny** [comment]
I'm not publishing updates to the built-in plugins at the time of the alpha, and the version numbers on them are not correct. I'll tweak the build system to automatically tag them with the version they're packaged with.

**Comment by Eugeny** [comment]
Plugin versions should now correspond to the app version starting with the next release
