### ISSUE TITLE
Problem building on Windows

### ISSUE THREAD

**Issue by Esgariot** [Eugeny/terminus#379]
Hello there, 

I've tried to do something about #185, but I can't run the project on Windows. 
Could you double-check Windows part of `HACKING.md`? running second script (`build-native.js`) completes with errors, running `npm start` results in error being thrown in chromium debug console 

```
Error: Cannot find module 'font-manager'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (D:\Development\terminus\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at q (D:\Development\terminus\terminus-terminal\dist\index.js:1:600)
    at Object.<anonymous> (D:\Development\terminus\terminus-terminal\dist\index.js:1:1754)
    at Object.<anonymous> (D:\Development\terminus\terminus-terminal\dist\index.js:500:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
```

**Comment by Eugeny** [comment]
This is likely because npm failed to build the module for the first time, but still marked it as "installed". Nuke the `terminus-terminal\node_modules` folder and rerun `node scripts\install-deps.js`

**Comment by Esgariot** [comment]
I've tried multiple times and every time I deleted all `node_modules` in directory tree along with  all `package-lock.json`. I'll try to spin up a clean windows vm, check there and will report back.

**Comment by Domain** [comment]
I cannot build the project with node.js 10.8 in windows 10.
Too many errors. Some of them:

c:\git\terminus\terminus-terminal\node_modules\node-pty-tmp\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: ��ForceSet��: ���ǡ�v8::Object���ĳ�Ա (����Դ�ļ� ..\src\win\pty.cc) [C:\Git\terminus\terminus-terminal\node_modules\node-pty-tmp\build\pty.vcxproj]

c:\\program files (x86)\\windows kits\\10\\include\\10.0.17134.0\\um\\wincred.h(56): error C3646: ��dwLower��: δ֪��д˵���� (����Դ�ļ� ..\\platforms\\windows.cc) [C:\\Git\\terminus\\terminus-ssh\\node_modules\\xkeychain\\build\\windows.vcxproj]
c:\\program files (x86)\\windows kits\\10\\include\\10.0.17134.0\\um\\wincred.h(56): error C4430: ȱ������˵���� - �ٶ�Ϊ int��ע��: C++ ��֧��Ĭ�� int (����Դ�ļ� ..\\platforms\\windows.cc) [C:\\Git\\terminus\\terminus-ssh\\node_modules\\xkeychain\\build\\windows.vcxproj]
c:\\program files (x86)\\windows kits\\10\\include\\10.0.17134.0\\um\\wincred.h(57): error C3646: ��dwUpper��: δ֪��д˵���� (����Դ�ļ� ..\\platforms\\windows.cc) [C:\\Git\\terminus\\terminus-ssh\\node_modules\\xkeychain\\build\\windows.vcxproj]
c:\\program files (x86)\\windows kits\\10\\include\\10.0.17134.0\\um\\wincred.h(57): error C4430: ȱ������˵���� - �ٶ�Ϊ int��ע��: C++ ��֧��Ĭ�� int (����Դ�ļ� ..\\platforms\\windows.cc) [C:\\Git\\terminus\\terminus-ssh\\node_modules\\xkeychain\\build\\windows.vcxproj]
c:\\program files (x86)\\windows kits\\10\\include\\10.0.17134.0\\um\\wincred.h(76): error C3646: ��dwLowDateTime��: δ֪��д˵���� (����Դ�ļ� ..\\platforms\\windows.cc) [C:\\Git\\terminus\\terminus-ssh\\node_modules\\xkeychain\\build\\windows.vcxproj]
c:\\program files (x86)\\windows kits\\10\\include\\10.0.17134.0\\um\\wincred.h(76): error C4430: ȱ������˵���� - �ٶ�Ϊ int��ע��: C++ ��֧��Ĭ�� int (����Դ�ļ� ..\\platforms\\windows.cc) [C:\\Git\\terminus\\terminus-ssh\\node_modules\\xkeychain\\build\\windows.vcxproj]
c:\\program files (x86)\\windows kits\\10\\include\\10.0.17134.0\\um\\wincred.h(77): error C3646: ��dwHighDateTime��: δ֪��д˵���� (����Դ�ļ� ..\\platforms\\windows.cc) [C:\\Git\\terminus\\terminus-ssh\\node_modules\\xkeychain\\build\\windows.vcxproj]
c:\\program files (x86)\\windows kits\\10\\include\\10.0.17134.0\\um\\wincred.h(77): error C4430: ȱ������˵���� - �ٶ�Ϊ int��ע��: C++ ��֧��Ĭ�� int (����Դ�ļ� ..\\platforms\\windows.cc) [C:\\Git\\terminus\\terminus-ssh\\node_modules\\xkeychain\\build\\windows.vcxproj]

……

**Comment by Eugeny** [comment]
I've bumped the NAN version - please reinstall the deps in `terminus-terminal/` and try again
