### ISSUE TITLE
Add a Preferences menu item to the macOS menu

### ISSUE THREAD

**Issue by acarl005** [Eugeny/terminus#38]
I have custom fonts installed and I'd like to be able to use my preferred font.

**Comment by acarl005** [comment]
Nevermind. I found the options menu. I had trouble finding it before because I was expecting to find it in the menu bar or for cmd+comma (a standard hotkey in MacOS) to open it.

**Comment by Eugeny** [comment]
Done in f4eb03fee0f38c9b9148cdd35144f05dd4778a65
