### ISSUE TITLE
For the first attempt for establishing SSH session fails while next attempt passes

### ISSUE THREAD

**Issue by sandeepkota** [Eugeny/terminus#380]
Version: 1.0.0-alpha.48
Platform: win32 6.1.7601

Can be reproducible on demand.
When I initiate an SSH session for the first time for a host, SSH connection is not establishing the error says 'Could not connect Error while handshake'. Whereas when I attempt next time for the same host, the connection is establishing.

**Comment by soylens** [comment]
I have been experiencing this issue also.
I use Terminus to connect to my 2 Hyper-V Linux VMs via SSH. One of which is running Fedora workstation 27 and another Arch Linux.
Interestingly, this problem occurs only for the Fedora and not for the other, so I suppose it be relevant to not only Terminus(client) but also to the server side.
(PS All packages are up-to-date at the time of this comment)

**Comment by 40four** [comment]
I have also been experiencing this when connecting to a VirtualBox, Ubuntu 16.04 VM. Haven't been able to notice a reproducible pattern, seems to be intermittent, sometimes it connects fine on first attempt but often the first one times-out on handshake. Are there some logs somewhere I could pull?

Terminus 1.0.0-alpha.61
Windows 10 Enterprise
Version: 1709
Build: 16299.125

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by 40four** [comment]
Ok, thanks for the tip, good to know. I haven't been experiencing this lately, maybe it cleared up in newer builds? I'll keep an eye out though, and post the logs if I see it.
