### ISSUE TITLE
execute same command on splitted screen

### ISSUE THREAD

**Issue by lepapareil** [Eugeny/terminus#3802]
Hi,

It would be great if we could execute same command on splitted section of a tab, actually, i have to copy my command and switch over my splitted section to paste and execute it sequentially.

This is the only feature I'm missing to switch from terminator to terminus on win10 pc.

thks !

**Comment by Eugeny** [comment]
Pressing the "focus all panes" hotkey lets you type into all splits simultaneously.

**Comment by lepapareil** [comment]
In fact the focus does not work for all things. For example I make several spans, in which thanks to the focus all I launch an `htop` command, then I want to kill the process with `ctrl+c`keyboard shortcut and then, only one of the spans is affected, but the focus remains on all the spans...

![6span](https://user-images.githubusercontent.com/15672496/120900061-37661200-c633-11eb-93ac-d359112b0d12.gif)
