### ISSUE TITLE
Default Hotkey Scheme incompatible with Emacs-style navigation Shortcuts

### ISSUE THREAD

**Issue by soylens** [Eugeny/terminus#384]
`C-a` conflicts with tab control commands.
  this can be solved by deleting all shortcuts beginning with Ctrl-A
`M-d` does not work for some reasons without conflicting shortcuts

Platform: Win 10 x64
Version:1.0.0-alpha.48

**Comment by Eugeny** [comment]
Meta key combinations are affected by the "Use Alt key as Meta key" setting (Terminal tab).

**Comment by soylens** [comment]
Dup #7
