### ISSUE TITLE
macOS cannot verify the developer of “terminus-1.0.139-macos-x86_64.pkg”

### ISSUE THREAD

**Issue by bmweller** [Eugeny/terminus#3849]
Version: 1.0.137
Platform: darwin 20.4.0
Plugins: clickable-links, save-output

Getting the following when trying to install latest beta on BigSur 11.3.1 (20E241)

macOS cannot verify the developer of “terminus-1.0.139-macos-x86_64.pkg”. Are you sure you want to open it?

**Comment by Eugeny** [comment]
Fixed, release updated
