### ISSUE TITLE
How to use terminus as shell in vscode or pycharm terminal ？

### ISSUE THREAD

**Issue by AngusWG** [Eugeny/terminus#3851]
Version: 1.0.139
Platform: win10
Plugins: none

For cmder, I use "cmd.exe / k" D:\ Program Files\ cmder\ vendor\ init.bat " to replace the terminal style of pycharm with the style of cmder.

How to do it for terminus ?

![image](https://user-images.githubusercontent.com/26385612/118354366-50802380-b59d-11eb-9416-12074aa371c9.png)

**Comment by Eugeny** [comment]
Terminus is not a shell. If you're referring to the default shell that Terminus uses on Windows, that's https://chrisant996.github.io/clink/
