### ISSUE TITLE
[Windows 10] Alpha 49 not working at all

### ISSUE THREAD

**Issue by danfloyd111** [Eugeny/terminus#386]
I've tried to install the latest release a couple of times, but after the installation procedure when starting the program I can see the logo in the application bar but no windows shows up.

![image](https://user-images.githubusercontent.com/12446689/43932003-f30491f4-9c41-11e8-9e6e-bf93bcb7e14e.png)

Do I have to do a deep clean before a new installation? How?
How can I provide more useful debug info?

Thank you!

**Comment by Eugeny** [comment]
Hi, can you start it with the --debug flag or alternatively collect the log file from %appdata%/terminus?

**Comment by larp-welt** [comment]
Same to me!

The first strange thing is, Terminus installs to: C:\ProgramData\el\terminus\app-1.0.0-alpha49

When I start Terminus with --debug, only the debug console opens:

![image](https://user-images.githubusercontent.com/392672/43944095-0ce51e4a-9c7e-11e8-997e-e9af66e7c813.png)

I can see 3 Terminus.exe-processes in the task manager.

I'm still using Windows 7.

**Comment by filippobuletto** [comment]
Same here, console export with `--debug`:

```
data:text/html,chro…:1 Not allowed to load local resource: file:///C:/Users/OMITTED_FOR_PRIVACY/resources/app.asar/dist/index.html
```

Seems Electron related?

Windows 10 v1803 (build 17134.137)

Installed with [scoop](https://github.com/lukesampson/scoop) updating from alpha 48.

**Comment by larp-welt** [comment]
Exact the same for me:

`Not allowed to load local resource: file:///C:/ProgramData/el/terminus/app-1.0.0-alpha49/resources/app.asar/dist/index.html`

**Comment by Eugeny** [comment]
fixed in 0b56259a368ec9bf8810f4be16bfcc12b28a6e89, new build coming in a couple of minutes

**Comment by Eugeny** [comment]
The build is live

**Comment by danfloyd111** [comment]
Now works as expected, thanks! I'll test soon this release also on my Linux box.

p.s. The Vibrancy feature is very very cool!
