### ISSUE TITLE
Paste shortcut is ctrl + V on macOS

### ISSUE THREAD

**Issue by haoyang324** [Eugeny/terminus#3861]
In the Menu bar the shortcut is cmd + V but cmd + V is just does NOT works. 
Settings -> keyboard -> shortcut -> app shortcut does NOT works.
I am using macOS Big Sur. M1 Chip Mac mini.

**Comment by neoswallow** [comment]
Which build are you running?
I am running 1.0.139 and I don't ever seem to remember having this problem and I do paste a lot.
I'm also running Big Sur on M1 Mini.

**Comment by haoyang324** [comment]
Oh Sorry, I copied the config from another machine. 
Been troubled by this stupid mistake for a long time
