### ISSUE TITLE
a50 not reacting to win+arrow keys

### ISSUE THREAD

**Issue by princemaple** [Eugeny/terminus#388]
the windows "native docking"

**Comment by scrossan-crown** [comment]
I'm having the same issue. It's also not snapping to the sides of the screen either

**Comment by Eugeny** [comment]
This is likely caused by the custom window borders - the window manager won't attempt to dock such windows. What we could do is emulate this behaviour by hooking Win-L/Win-R (if this is even possible)

**Comment by Eugeny** [comment]
By the way, switching to the "native" window style should function as a workaround

**Comment by princemaple** [comment]
how was it possible before a49?

**Comment by Eugeny** [comment]
I think I've found it

**Comment by princemaple** [comment]
Interesting.. how transparency affects window management
Can't wait for the new builds. :)

**Comment by princemaple** [comment]
confirm it works now
