### ISSUE TITLE
Non-Latin characters broken when occur in the output over 1024 byte boundary

### ISSUE THREAD

**Issue by koterpillar** [Eugeny/terminus#3883]
I've been seeing occurrences of `��` in the output here and there and I've managed to come up with a reproducible example:

```
$ python -c 'print("a" + "ф" * 512)'
aфффф<snip>ффффффффф��
```

The letter ф has two bytes in the UTF-8 encoding, so the string is just over 1024 bytes, with the boundary _in the middle_ of the last ф.

I suspect this is the same as #3882, #3093, #2043.

Keywords: unicode replacement character, displayed incorrectly

**Comment by Eugeny** [comment]
Thanks for investigating this :+1:

**Comment by leonpenn** [comment]
@Eugeny Is there a plan to fix this problem?
