### ISSUE TITLE
[Ubuntu 18.04] Alpha 50 not starting

### ISSUE THREAD

**Issue by danfloyd111** [Eugeny/terminus#389]
Hi, sorry to bother you again, I've tested the Alpha 50 on my Linux box and I got this:

![photo_2018-08-10_13-59-36](https://user-images.githubusercontent.com/12446689/43957112-f5ab2c00-9ca6-11e8-8a42-77679b82e13a.jpg)

Thank you!

**Comment by larp-welt** [comment]
Hi!

Same for me! Using Ubuntu 18.04.

**Comment by iolaizola** [comment]
Same for me in ubuntu 18.04

**Comment by Eugeny** [comment]
Please try this release: https://github.com/Eugeny/terminus/releases/tag/v1.0.0-alpha.51

**Comment by iolaizola** [comment]
It works perfectly! great job!

thanks
