### ISSUE TITLE
Split screen function

### ISSUE THREAD

**Issue by Reverse7** [Eugeny/terminus#390]
Hi, can we please get ability to split screen vertical/horizontal? (preferable in the right click context menu). 
the program 'screen' does not work inside of Terminus

**Comment by Eugeny** [comment]
Duplicate of #49.

Also, `screen` works inside Terminus. If you mean Ctrl-A not being sent to screen, you need to remove all Ctrl-A hotkeys from the Hotkeys tab in the settings first.
