### ISSUE TITLE
Broadcast a command to multiple (split) terminals

### ISSUE THREAD

**Issue by mnmami** [Eugeny/terminus#3919]
Most probably this has already been asked before and that this issue will be promptly closed for good, but I'm maybe just not able to find the correct keywords to search. I don't see how one can broadcast a command to multiple terminals, more specifically for the split-terminal mode. If that's not possible, it'd be the most wanted feature from my side.

**Comment by Eugeny** [comment]
The shortcut you're looking for is "focus all panes"

**Comment by mnmami** [comment]
Thanks :)

**Comment by mnmami** [comment]
Thanks. At least, this issue will serve as a reference for users who come from other terminal software where the "broadcast" term is primarily used. 

To complete the story: to disable the all-panes focus and focus on a specific pane, the shortcut is (as of now at least) is Ctrl+Alt+{Up/Down/Left/Right} depending on which pan you want to focus on. 

Maybe it would be good, when the all-planes focus is enabled, to add "Focus on this" to the right-click menu to switch back to a spefic pane and run commands there, which might, too, have already been discussed in another issue :)

**Comment by Eugeny** [comment]
You can also just click into another pane, and that will cancel the global focus :)

**Comment by mnmami** [comment]
Alright, I did click the left pane but it did nothing, but clicking another pane as you said indeed disabled the global focus.

Thanks again!

**Comment by Eugeny** [comment]
:+1: I've just made clicking the same pane cancel broadcast as well

**Comment by mnmami** [comment]
Very active you :). I'm yet to try that out, but it just got me thinking, what happens when one wants to copy the typed command and select it to paste it later somewhere else, will that cancel the broadcast?

**Comment by Eugeny** [comment]
Yes - but they you can just re-enable broadcast again

**Comment by nproctor-dev** [comment]
For anyone finding this older thread: Tabby's native “focus all panes” feature is still the built-in way to broadcast input across panes.

If you're looking for a workflow where broadcast stays enabled while you move between panes, I ended up building a plugin called tabby-multiexec.

It keeps MultiExec active while switching pane focus and lets individual panes be dynamically excluded from the broadcast without disabling MultiExec for the others. It also adds toolbar controls for MultiExec, tiling, returning sessions to tabs, and full-terminal clipboard copy.

Docs/screenshots:
[https://github.com/nproctor-dev/tabby-multiexec-support](https://github.com/nproctor-dev/tabby-multiexec-support?utm_source=chatgpt.com)

Currently validated with Tabby 1.0.235–1.0.236 on Linux/Kubuntu.

Disclosure: I'm the plugin author.
