### ISSUE TITLE
How do I unify the path of the SSH private key in the Windows and Mac versions ?

### ISSUE THREAD

**Issue by zjwon** [Eugeny/terminus#3921]
Because of the SSH private key file path in the configuration file, I had to split the configuration file to synchronize the Windows version and the Mac version, which was a headache.
So, How do I unify the path of the SSH private key in the Windows and Mac versions ?

**Comment by Eugeny** [comment]
There's no built-in way to go around this unfortunately - only absolute paths are allowed in the `privateKey` field. I'll try to either add support for home-relative (~) paths or modify the sync plugin to not overwrite key paths

**Comment by zjwon** [comment]
Set two SSH private key fields(eg. `winPrivateKey` and `linuxPrivateKey`) for Windows and MacOS/Linux, and determine which field to use during SSH connection according to the OS type. Such a set of configuration files can be used across platforms~
How about this solution?

**Comment by zjwon** [comment]
> Set two SSH private key fields(eg. `winPrivateKey` and `linuxPrivateKey`) for Windows and MacOS/Linux, and determine which field to use during SSH connection according to the OS type. Such a set of configuration files can be used across platforms~
> How about this solution?

@Eugeny 
Add a few lines of code to the following two files to achieve the requirements I mentioned above. After I compile it locally, I can use it. Can it be implemented in the next version?
- terminus-ssh/src/api.ts

```
export interface SSHConnection {
    ......
    winPrivateKey?: string
    linuxPrivateKey?: string
    ......
)

```

- terminus-ssh/src/services/ssh.service.ts

```
async loadPrivateKeyForSession (session: SSHSession): Promise<string|null> {
    let privateKey: string|null = null
    let privateKeyPath = session.connection.privateKey
    let winPrivateKeyPath = session.connection.winPrivateKey
    let linuxPrivateKeyPath = session.connection.linuxPrivateKey

    if (this.hostApp.platform === Platform.Windows && winPrivateKeyPath) {
        privateKeyPath = winPrivateKeyPath
    } else if (this.hostApp.platform === Platform.macOS && linuxPrivateKeyPath) {
        privateKeyPath = linuxPrivateKeyPath
    }
    ......
}
```

**Comment by Eugeny** [comment]
I've replaced `privateKey` with a `privateKeys` path array - the first existing key will be used.
