### ISSUE TITLE
Terminal bell doesn't work in screen session

### ISSUE THREAD

**Issue by max1c** [Eugeny/terminus#3932]
The terminal bell is now working in the 1.0.139 release. However, it does not work when starting a screen session. This is not critical but thought I'd report it.

**Comment by Eugeny** [comment]
Might be a stupid question, but is bell enabled in Screen itself? https://superuser.com/questions/488817/enable-audible-bell-in-gnu-screen-current-window

**Comment by max1c** [comment]
Ah, thanks! It actually was not. Sorry for the confusion.
