### ISSUE TITLE
Console problems when using Git Bash to ssh into IBM PASE Environment

### ISSUE THREAD

**Issue by amacgillivray** [Eugeny/terminus#3946]
SSH-ing into the [PASE environment on an IBM i Series](https://www.ibm.com/docs/en/i/7.3?topic=programming-pase-i) creates several unusual problems. 

Most significantly, attempting to use the `backspace` key to correct a typographical error seems to perform a destructive backspace, but the previously-typed text is not removed from view. Instead, another character is appended to the line: 

![image](https://user-images.githubusercontent.com/40438470/120815074-1effd580-c515-11eb-879c-b5666f8aaedc.png)

The last two commands show the result of entering three and one backspaces, respectively. The terminal is working correctly in that "executing" the 2nd-from-last command ( ` $ ls ⌂⌂⌂` ) has no effect (all three characters, `ls `, have been erased). 

There are problems related to the terminal type (cygwin) when using `vi`: 

![image](https://user-images.githubusercontent.com/40438470/120816164-1f4ca080-c516-11eb-9f7d-9ff891fed3b7.png)

None of these errors occur if I ssh in using the Git Bash program on its own (instead of Git Bash inside of Terminus). 

---

Terminus Version: 1.0.139 (Windows, 64 bit)

Steps to reproduce: 

 * Open a new tab in the git bash profile 
 * ssh into an IBM PASE environment
 * Note problems with entering commands on the console

System information: 

Windows 10 (19041.985)
Git Bash (launched outside of Terminus) is using mintty 2.9.1 (x86_64-pc-msys)

**Comment by Eugeny** [comment]
Thanks for the detailed report. Can you compare the behaviour with the Terminus' own SSH client?

**Comment by amacgillivray** [comment]
Using Terminus's own SSH client creates different (undesired) behavior.
Backspaces no longer show a character, but do? seem to have an effect. See the last command where I typed `ls` and then several backspaces, and the result was ` not found`.

![image](https://user-images.githubusercontent.com/40438470/120819822-8fa8f100-c519-11eb-8322-4b8278bcbf12.png)

**Comment by amacgillivray** [comment]
Okay, I think I've figured it out. PASE is defaulting to bourne shell, and wants `ctrl+h` for backspaces. 

The following stackoverflow thread (discussing AIX, which is very similar to PASE) explained the fix: https://unix.stackexchange.com/questions/16700/what-is-the-default-shell-for-sh-in-aix

Running `ssty sane; tset -Q` and then `stty erase '^?'` fixed problems with backspaces in the Terminus Git Bash profile. However, it does not fix backspaces in a session created in Terminus's SSH client.

**Comment by amacgillivray** [comment]
`Vi` is opening vi in `open mode`, which is intended for terminals that display one active line at a time. `vim` launches vim properly in a fullscreen view. Since the problems didn't actually have anything to do with Terminus, I'm closing the issue.
