### ISSUE TITLE
Focus all pan does not work for all action

### ISSUE THREAD

**Issue by lepapareil** [Eugeny/terminus#3961]
Focus all pan does not work for all action. For example I make several spans, in which thanks to the focus all I launch an `htop` command, then I want to kill the process with `ctrl+c` keyboard shortcut and then, only one of the spans is affected, but the focus remains on all the spans...

![6span](https://user-images.githubusercontent.com/15672496/120983864-65a23980-c77a-11eb-9ac0-92cc3881ce08.gif)

**Comment by lepapareil** [comment]
👌

**Comment by icmono** [comment]
Hello,

This is still an issue for pasting. It pastes to the last focused pane before focusing all.
I'm on Windows10 right now. I'll try it on linux later today.
