### ISSUE TITLE
Terminus 0.51 hangs on startup screen on Windows 10 (1709)

### ISSUE THREAD

**Issue by corelon** [Eugeny/terminus#397]
I tried installing both from the installer and Scoop.
In both cases Terminus hangs on the transparent startup screen.
Any help on that would be greatly appreciated.

**Comment by Eugeny** [comment]
Please start it with the --debug flag - that should show the debug console immediately

**Comment by vtintillier** [comment]
It does not start for me either, but because it is blocked by McAfee. I guess signing the Windows binary would help.

**Comment by corelon** [comment]
I started it with --debug. Anything that I should be looking for?
Still getting the splash screen and chrome dev tools.

**Comment by Eugeny** [comment]
Check DevTools console tab for errors/warnings

**Comment by corelon** [comment]
That is the issue. There are no problems showing.

**Comment by corelon** [comment]
Seems to be fixed in alpha 52.

**Comment by corelon** [comment]
Closing for now.
