### ISSUE TITLE
Advance: Can give a way to set the color of edge of split windows?

### ISSUE THREAD

**Issue by qfs1998** [Eugeny/terminus#3991]
It is hard to find out the windows when I split it to 4. The color between windows is not very obvious.

**Comment by Eugeny** [comment]
Sure - see https://github.com/Eugeny/terminus/issues/2602

**Comment by qfs1998** [comment]
thx a lot!

**Comment by qfs1998** [comment]
> Sure - see #2602

thx a lot!
