### ISSUE TITLE
does not detect npm as installed by homebrew - macOS

### ISSUE THREAD

**Issue by StrangeNoises** [Eugeny/terminus#4]
As per subject. npm is installed on my system using homebrew, but the Settings->Plugins tab does not recognise it. I suspect that might be because it's not in a login shell itself (see my other issue) and thus homebrew's path is not in $PATH.

**Comment by gotama** [comment]
Ive installed npm via pkg and homebrew and can confirm neither pick up

**Comment by DAlperin** [comment]
I do not know if this is the correct place for this, however I realized that I have npm installed via nvm and yet it is informing me in the plugins tab that: "NPM not installed"

```which npm``` returns  ```/Users/dovalperin/.nvm/versions/node/v6.9.0/bin/npm```
```npm --version``` returns ```3.10.8```

**Comment by Eugeny** [comment]
@DAlperin @gotama, please retry with the current alpha, which is now runs a login shell and thus should pick up your custom $PATH automatically

**Comment by Eugeny** [comment]
Otherwise closed via #10

**Comment by StrangeNoises** [comment]
Not working for me in alpha 15 (apparently the latest though says 4 days old?)

npm is in `/usr/local/bin/npm` as installed by homebrew. This is in $PATH, being defined in `/etc/paths` and thus read by `/usr/libexec/path_helper` during the running of `/etc/profile`. In other respects, default login shell is working for me, which implies reading all that stuff.

Does the Settings dialogue run in a default login shell?

**Comment by pdelre** [comment]
Same issues in alpha 18: `Version 1.0.0-alpha.18 (1.0.0-alpha.18.96)`.

```
$ which npm
/usr/local/bin/npm

$ echo $PATH
/Users/pdelre/Library/Python/2.7/bin:/Users/pdelre/bin:/usr/local/opt/php70/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin

$ npm -v; echo $?
5.0.3
0
```

**Comment by compuguy** [comment]
Same issue in alphas 21 and 22.

**Comment by compuguy** [comment]
Still valid with alpha 28.

**Comment by karlokolar** [comment]
Still valid for alpha 31
