### ISSUE TITLE
vim renders all wrong

### ISSUE THREAD

**Issue by acarl005** [Eugeny/terminus#40]
How it looks in terminus:
<img width="1440" alt="screen shot 2017-07-03 at 1 07 44 am" src="https://user-images.githubusercontent.com/8334252/27783701-26e4b538-5f8c-11e7-9fb7-ddc5f7f35b49.png">

How it looks in other terminal emulators:
<img width="1440" alt="screen shot 2017-07-03 at 1 09 51 am" src="https://user-images.githubusercontent.com/8334252/27783772-5c43b350-5f8c-11e7-9b8a-846ff79cf0a6.png">

I'm on MacOS 10.11.6, Vim 8.0 with [this color theme](https://github.com/NLKNguyen/papercolor-theme).

**Comment by Eugeny** [comment]
Just from looking at those corners and characters, are you sure you're not using the Powerline fonts in iTerm? If so, you need to choose the same font in Terminus.

**Comment by acarl005** [comment]
Yep, quite sure. I'm using "Inconsolata for powerline" just as I do for other emulators. To my understanding, I believe UTF8 support is still required to get the more obscure looking characters to show up, even with the right font selected.

<img width="645" alt="screen shot 2017-07-03 at 10 55 05 am" src="https://user-images.githubusercontent.com/8334252/27803407-241eef60-5fde-11e7-99e4-09089bed6ad6.png">

**Comment by Eugeny** [comment]
Weird - as I'm using Powerline myself. Could you please upload the complete vim configuration so that I can try to reproduce this?

**Comment by acarl005** [comment]
[https://github.com/acarl005/bash-osx/blob/master/.vimrc](https://github.com/acarl005/bash-osx/blob/master/.vimrc)

**Comment by Eugeny** [comment]
![image](https://user-images.githubusercontent.com/161476/27856183-94525afc-616d-11e7-8555-ffb107f284f0.png)
Works for me... can you also try other fonts from the Powerline family?

**Comment by Eugeny** [comment]
I've added another potential fix in Alpha 19
