### ISSUE TITLE
[a52/win10] Right click does not work in xterm

### ISSUE THREAD

**Issue by princemaple** [Eugeny/terminus#400]
Although I never really right click, reporting it anyway...

**Comment by princemaple** [comment]
Actually fixed in a54

**Comment by princemaple** [comment]
So xterm doesn't work with right click or copy on select, but has a scrollbar
hterm works with right click, can copy on select, but does not have a scrollbar

**Comment by Eugeny** [comment]
@princemaple hterm doesn't have its own embedded scrollbar, but you can use the Scrollbar plugin for it. I've reopened this to fix the right click in xterm.
