### ISSUE TITLE
[SFTP] Issues with drag & drop upload feature

### ISSUE THREAD

**Issue by IrwenXYZ** [Eugeny/terminus#4000]
1. drag & drop upload does not allow uploading of multiple files
2. after uploading a file via drag & drop, the file list does not refresh. would be good for it to automatically refresh, or add a refresh button (or using the F5 button) for us to manually refresh the file list

**Comment by Eugeny** [comment]
Fixed. Thanks for testing the nightlies by the way, I appreciate it!

**Comment by IrwenXYZ** [comment]
happy to test! thanks for all the work!
