### ISSUE TITLE
problem under linux with every colorschemes

### ISSUE THREAD

**Issue by Tyr4El** [Eugeny/terminus#4014]
Hi, I wanted to try your piece of software and the color scheme doesn't seem to be applied on the username and hostname. They stay in gray for fedora 33/34. For ubuntu 20.04+, the whole thing takes the color from the username.

**Comment by Eugeny** [comment]
This means your shell doesn't colorize the prompt. Check this out: https://askubuntu.com/questions/123268/changing-colors-for-user-host-directory-information-in-terminal-command-prompt
