### ISSUE TITLE
Error: Can't resolve all parameters for URLHandler: (?).

### ISSUE THREAD

**Issue by kumardeepakxyz** [Eugeny/terminus#4015]
Version: 1.0.140
Platform: darwin 20.5.0
Plugins: terminus-clickable-links

**Comment by Eugeny** [comment]
Fixed in clickable-links v3.0.0

**Comment by kumardeepakxyz** [comment]
It's working fine with clickable-links v3.0.1

**Comment by boistordu** [comment]
Same problem with clickable ip plugin with terminus 141 can you make an update for this specific plugin?

**Comment by Eugeny** [comment]
I've submitted a PR but the plugin author hasn't reacted. The latest update to the official `clickable-links` plugin now includes support for IPs.
