### ISSUE TITLE
Unrecognized pageant

### ISSUE THREAD

**Issue by huai168an** [Eugeny/terminus#4023]
1.0.140  Unrecognized pageant
1.0.139 Normal

pageant 0.75

**Comment by OffalGood** [comment]
1.0.141 still doesn't recognize pagent 0.75 (Putty Agent)  Windows 10

**Comment by OffalGood** [comment]
Rolled back to 1.0.139, and integration with Putty agent works.

**Comment by Eugeny** [comment]
Fixed in the nightly.
