### ISSUE TITLE
[Error] Terminus

### ISSUE THREAD

**Issue by XIroot** [Eugeny/terminus#4033]
Hello !

It has restarted and the plugins are uninstalled automatically.
But each time you start Terminus, it displays repetitively:
"Terminus could not start with your plugins, so all third party plugins have been disabled in this session. The error was:"

How do I get rid of this error or what can I fix with your help?

Best regards. 
XIroot

Version: 1.0.140
Platform: win32 10.0.19043
Plugins: none

**Comment by Eugeny** [comment]
Please upgrade to v141 and then upgrade any outdated plugins.
