### ISSUE TITLE
no available window in macOS12 Monterey

### ISSUE THREAD

**Issue by fuuulstack** [Eugeny/terminus#4037]
simple, open with terminal, stuck at 
'''
MBInstance: setting bounds for user menubar on display 0x2B280D53 (main) with bounds o=[0.000000, 0.000000], s=[1920.000000, 24.000000]
'''

**Comment by Eugeny** [comment]
Fixed in v141

**Comment by fuuulstack** [comment]
> Fixed in v141

damn efficient! XD
