### ISSUE TITLE
Terminus hangs while opening

### ISSUE THREAD

**Issue by pradeep-anantha** [Eugeny/terminus#4038]
Version: 1.0.139
Platform: darwin 20.5.0
Plugins: clickable-ips, clickable-links, elastic-quick-cmds, elastic-quick-commands, quick-cmds, save-output, scrollbar, theme-windows10, title-control

Terminus does not open after reopening the application . It freezes with the terminus icon with progress bar loaded. 
Not sure if it a known issue . Every time I need to open I have to reinstall using brew..

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by fusionneur** [comment]
hangs for me too on latest version on windows 10

**Comment by Codex-** [comment]
I'm having this too on macos arm64, had to rollback to 138.

Console does not show anything, the session seems to die before I can connect to it with devtools.

**Comment by Eugeny** [comment]
Fixed in the nightly.
