### ISSUE TITLE
"select shell" icon broken

### ISSUE THREAD

**Issue by kbjr** [Eugeny/terminus#404]
![image](https://user-images.githubusercontent.com/195127/44819734-d1572100-aba2-11e8-98cf-c377a7d9c2d6.png)

![image](https://user-images.githubusercontent.com/195127/44819741-d74d0200-aba2-11e8-9a83-0073c424e692.png)

Both places where the icon is supposed to show, instead just say `th-large`

**Comment by citycide** [comment]
Updated the `shell-selector` plugin fixed this for me.

**Comment by Eugeny** [comment]
Yup - this is fixed in the updated plugin
