### ISSUE TITLE
won't install in MacOS 11.2.3 M1

### ISSUE THREAD

**Issue by lf-openthos** [Eugeny/terminus#4044]
arm64.pkg is not properly signed. So such error will display while install
"Cannot open ****.pkg because apple cannot determine if it is safe."
Version 1.0.141
MacOS version 11.2.3

and btw, at this environment, both 1.0.140 and 1.0.141 run with a grey windows without any content and cannot quit. Maybe I should clear all the data from previous version?

**Comment by lf-openthos** [comment]
While select "toggle developer tools", and "reload", the application will reload with the same grey blank window at the left with blank dev window at the right and show  "DevTools was disconnected from the page".

**Comment by lf-openthos** [comment]
meanwhile  the x64.pkg runs smoothly.
MacBook Pro M1, 16G+512G, 2020 model.

**Comment by Eugeny** [comment]
Fixed in the nightly.
