### ISSUE TITLE
UI crash resulting on a white screen

### ISSUE THREAD

**Issue by emanuelzh** [Eugeny/terminus#405]
Version: 1.0.0-alpha.54 (since 53)
Platform: win32 10.0.17134

Since the introduction of re-arranging tabs the UI started to crash constantly resulting on a complete white screen and all terminal connections loss.

**Comment by Eugeny** [comment]
Potentially fixed 18c0a585a2fe24be6dcba30df4c963f6f1802e90

**Comment by Eugeny** [comment]
@juanpazup have you by any chance enabled vibrancy in the settings? It could cause problems with Windows 7

**Comment by juanpazup** [comment]
Version: 1.0.0-alpha.55
Platform: win32 6.1.7601

@Eugeny No, vibrancy is not enable. And it always crash when I try to open the "Terminal" settings.
