### ISSUE TITLE
Alpha 141 seems have some bugs in arm macos

### ISSUE THREAD

**Issue by afukada-mkh** [Eugeny/terminus#4052]
Hi, 

I download version Alph 141 and installed in arm macOS.

But I can't start the app.

The App look like below and I can't terminate it (only use force to close it).

Someone have any idea about this issue?

<img width="830" alt="截圖 2021-06-25 15 02 09" src="https://user-images.githubusercontent.com/84664750/123383981-6b937980-d5c6-11eb-88f6-6db3b3599a23.png">

**Comment by florianflad** [comment]
Hi, I have the same behavior with the versions 139 and 140 on Apple M1.
It freezes directly after the start

**Comment by Eugeny** [comment]
Fixed in the nightly.
