### ISSUE TITLE
Many scrolling related issues

### ISSUE THREAD

**Issue by Msouza91** [Eugeny/terminus#4056]
Terminal scrolling isn't working for me and clearing the screen with the shortcut only works visually, but the cursor stays in the same place. Using the clear command works, but I can't scroll up to look at history after that.

I tried messing with the number of lines and other settings, but it is all broken for me...

![image](https://user-images.githubusercontent.com/19522556/123432829-2dd02a00-d5a1-11eb-8df9-78ebd093a7bd.png)

**Comment by Eugeny** [comment]
You're looking for Termius.
