### ISSUE TITLE
Unable to use gpg-agent in ssh plugin after update rencently version on mac

### ISSUE THREAD

**Issue by 81pla** [Eugeny/terminus#4062]
Hello, I'm using gpg-agent on mac, which allows using my GPG keys to authenticate SSH connections. However, after a recent update, i can't use it in SSH plugin, just notice me enter password,not forward to gpg-agent. But in command line use `ssh root@xxx` works, just not work when using ssh plugin in gui. its work well before update.

my ~/.zshrc 

```
export GPG_TTY=$(tty)
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpg-connect-agent updatestartuptty /bye > /dev/null
```

**Comment by Eugeny** [comment]
Should be fixed in the nightly.
