### ISSUE TITLE
Can not use clickable-ips plugins after updating the new version 1.0.139

### ISSUE THREAD

**Issue by ntctuyen** [Eugeny/terminus#4063]
Version: 1.0.142
Platform: linux 5.11.0-22-generic
Plugins: clickable-ips, clickable-links

After updating the new version, it always shows this error message when opening Terminus.
![image](https://user-images.githubusercontent.com/27688125/123514824-00799e00-d6bf-11eb-91bc-8963666e96e9.png)

**Comment by Eugeny** [comment]
Please upgrade to v142 and upgrade the plugin as well

**Comment by ntctuyen** [comment]
> Please upgrade to v142 and upgrade the plugin as well

Hi @Eugeny, the issue happened on v142 as well.

**Comment by Eugeny** [comment]
Sorry, I've misread it as "clickable-links". I've posted a pull request with a fix for that plugin, but the plugin's author hasn't merged it yet.
