### ISSUE TITLE
Third party plugins disabled at startup

### ISSUE THREAD

**Issue by parampreetss** [Eugeny/terminus#4066]
Version: 1.0.142
Platform: linux 5.11.0-22-generic
Plugins: altair, clickable-ips, clickable-links, quick-cmds, relaxed-theme, save-output, scrollbar, theme-gruvbox, theme-hype, theme-windows10, title-control

Getting this error message on startup:

Terminus could not start with your plugins, so all third party plugins have been disabled in this session. The error was:
Error: Can't resolve all parameters for URLHandler: (?).
![Screenshot_20210627_131435](https://user-images.githubusercontent.com/20267899/123536727-b7baf700-d749-11eb-9996-5e745ff91b83.png)

**Comment by Eugeny** [comment]
This is caused by the clickable-ips plugin. I've submitted a PR but the author hasn't reacted yet. You can update the clickable-links plugin instead - I've just pushed an update that adds support for highlighting raw IPs

**Comment by parampreetss** [comment]
I updated clickable-links plugin as you suggested. Removed the clickable-ips plugin. The error is gone. Thanks!
