### ISSUE TITLE
Toggle full-screen broken!

### ISSUE THREAD

**Issue by bantya** [Eugeny/terminus#407]
After updating to Terminus v1.0.0-alpha.54, the toggle full-screen functionality seems to be broken. It can only enter the full-screen and simply can not exit the full-screen

**Comment by bantya** [comment]
64bit Windows 10 (Version 1803)

**Comment by bantya** [comment]
Issue still persists after installing **Alpha 56** version. Once hitting <kbd>F11</kbd>, Terminus goes into full-screen then hitting <kbd>F11</kbd> again, it does't come back to its original state!

**Comment by ipctec** [comment]
same issue here 64bit Windows 10 Pro (Version 1809)
