### ISSUE TITLE
"Auto-open a terminal on app start" opens two terminal tabs on start

### ISSUE THREAD

**Issue by parampreetss** [Eugeny/terminus#4073]
Version: 1.0.142
Platform: linux 5.11.0-22-generic
Plugins: altair, clickable-links, quick-cmds, relaxed-theme, save-output, scrollbar, theme-gruvbox, theme-hype, theme-windows10, title-control

When "Auto-open a terminal on app start" is enabled, it opens two terminal tabs on start. This happens even when "Restore terminal tabs on start" is disabled.

Expected behavior (in my view): This option, when enabled, should launch a single terminal tab on start.

**Comment by Eugeny** [comment]
Should be already fixed in the nightly
