### ISSUE TITLE
Ssh-agent not working anymore

### ISSUE THREAD

**Issue by Vincent-HD** [Eugeny/terminus#4074]
Since I updated to the last version 1.0.142.

I can't get the the ssh-agent working, I selected agent on the authentication method and I get rejected.

Nothing is wrong on my side (I believe) even thought when I launch and regular cmd, and I type `ssh <user>@<host>` I can login without any problem, no errors in the console except this which is normal because it gets rejected:
`X  Remote rejected opening a shell channel: Error: Not connected`

Any Idea ? I think I will rollback to an older version for now

**Comment by Eugeny** [comment]
This should be fixed in the nightly build

**Comment by Vincent-HD** [comment]
Well thanks you for the quick answer, I should've check the nightly before, it works now, it even solved another problem with this error : 
`Unsupported key exchange algorithm: diffie-hellman-group15-sha512`
👍 🔥
