### ISSUE TITLE
Warn the user that the bell can't be disabled on WSL

### ISSUE THREAD

**Issue by pcause** [Eugeny/terminus#413]
running on win10.  in terminal settings I have the bell off.  AT the prompt if i enter ls and then hit backspace 3-4 times I hear a bell.

**Comment by aminland** [comment]
still happening with alpha 57 with wsl shell.

**Comment by Eugeny** [comment]
@pcause are you on WSL?

**Comment by pcause** [comment]
I am on Windows and bringing up a bash shell on WSL.  Thanks for the info.

**Comment by neodyma** [comment]
see [453](https://github.com/Eugeny/terminus/issues/453#issuecomment-427877098) for workaround
