### ISSUE TITLE
blank screen when opening new tab after a delay

### ISSUE THREAD

**Issue by MagicDuck** [Eugeny/terminus#420]
Version: 1.0.0-alpha.55
Platform: win32 10.0.16299

Hi, first, thanks for your work! We really need a decent terminal emulator especially on windoze. Love terminus so far!
The issue I am encountering has started happening in the last month or so. What happens is that I launch terminus and work for a while (1-2min) in the one tab. Then, when I try to open a new tab I get a blank screen. No matter how much I toggle back and forth, nothing will appear...
![image](https://user-images.githubusercontent.com/95201/45508688-4a7d7900-b74a-11e8-9242-9ff125eac44a.png)

If I open the dev tools, I see the following errors:
![image](https://user-images.githubusercontent.com/95201/45510215-65ea8300-b74e-11e8-9396-5475279f5827.png)

**Comment by MagicDuck** [comment]
Hmm, removing the "clickable link" plugin got rid of the first error above, but not the second...

**Comment by MagicDuck** [comment]
I wonder if the winpty issue is related to this: https://github.com/rprichard/winpty/issues/142

**Comment by rprichard** [comment]
@MagicDuck Do you have any third-party antivirus software running, and if so, can you try (temporarily) disabling it or adding the `winpty.dll` / `winpty-agent.exe` binaries as exceptions, for testing purposes?

**Comment by MagicDuck** [comment]
@rprichard yeah, it looks like some mcaffee rule is interfering with it :(. Funny enough, in the log, the action says "would block" but according to it, it doesn't actually block it. May still be doing something weird though....
Unfortunately I am on a corporate network and don't have permission to disable that stuff. I'll follow up with IT on my side. 
One thing I am confused about is why it works immediately after starting up terminus. I can open up as many tabs as I like... 
Thanks for trying to help!

**Comment by MagicDuck** [comment]
Just wanted to given an update. IT updated some stuff on my machine and the problem seems to have gone away. I still see the rule saying "would block" in the log, but it now works, so it seems like it was never truly blocking it but maybe something else was screwing things up???...
I didn't get to try @rprichard 's suggestion but I'll keep that in the back pocket in case the problem pops up again.

**Comment by Rodce** [comment]
Version: 1.0.73
Platform: linux 4.15.0-46-generic
Plugins: none

![image](https://user-images.githubusercontent.com/16733881/55132678-df1a5800-512b-11e9-92fb-872dab2579c7.png)
