### ISSUE TITLE
Cursor dispears when moving fast

### ISSUE THREAD

**Issue by lclalalalala** [Eugeny/terminus#422]
Version: 1.0.0-alpha.55
Platform: win32 10.0.16299

I ssh on my VPS, used byobu, when keeping pressing down left key to move cursor fast to somewhere in the shell, the cursor disappears. I have to stop to let it show up to find out where it is.
This is annoying.

**Comment by neodyma** [comment]
A workaround would be setting cursor blinking to off.

@Eugeny 
You could fix it by flipping the default state of the cursor. Currently, after you move the cursor, it will be invisible on the first tick, and then appear on the second one. If you set it to appear -> disappear -> .. instead, the cursor will be visible while moving it.
