### ISSUE TITLE
Terminus 55 hangs on startup (Ubuntu 18.04)

### ISSUE THREAD

**Issue by iolaizola** [Eugeny/terminus#425]
Hi,
I'm getting the following error when launching terminus 55.
```shell
(terminus:30333): Gtk-WARNING **: 11:49:58.030: Theme parsing error: gtk-main.css:73:38: 
Failed to import: Error opening file /usr/share/themes/Radiance/gtk-3.20/apps/gnome-builder.css:
 No such file or directory

```
I think it is the same problem that happened in a previous version.

**Comment by c0fe** [comment]
Honestly, I have found Ubuntu 18.04 to be quite buggy, numerous problems, not including the cloud-init issue.

**Comment by iolaizola** [comment]
Seems that after rebooting it works. Might be due to previous running instance of terminus.
