### ISSUE TITLE
Alpha 55 doesn't appear to close correctly

### ISSUE THREAD

**Issue by jamgregory** [Eugeny/terminus#426]
Not sure if it makes a difference, but I'm running Alpha 55 on Ubuntu 16.04.

When I close all tabs (returning to the Terminus home screen) and then click 'X', Terminus doesn't appear to be terminating (although it doesn't appear as a window in Unity).

Additionally, it appears Terminus is creating an extra(?) application icon, which means the primary application icon isn't used in Unity and instead a icon with the shell name in is present in the Unity dock - not sure if the two are related...

**Comment by Eugeny** [comment]
I can confirm the window closing issue, but the extra app icon seems to be a Unity problem. At least gnome-shell is properly grouping windows in its dock in 18.04

**Comment by jamgregory** [comment]
Great, thanks @Eugeny :+1:
