### ISSUE TITLE
Terminus goes out of screen when dock option is set up within the software

### ISSUE THREAD

**Issue by Rexcrazy804** [Eugeny/terminus#427]
i had to delete everything terminus to get the software start working again

**Comment by iceMatcha** [comment]
i had the same issue！！！

**Comment by Juneuly** [comment]
i had the same issue, too!!!!!!

**Comment by WuChouRao** [comment]
same problem

**Comment by osimbarhew** [comment]
Also same issue but you don't need to reinstall the app, just remove the "dock" line from the config.yaml file.

On Windows you can find it at `C:\Users\<user>\AppData\Roaming\Terminus\config.yaml`

**Comment by lpreiner** [comment]
I had this problem as well, and was able to fix it by modifying both the config.yaml file mentioned by @osimbarhew as well as window.json.

**Comment by Rexcrazy804** [comment]
Yeah better try not to change the dock setting in future

**Comment by glen-84** [comment]
Duplicate of #364?

**Comment by Eugeny** [comment]
Duplicate of #364

**Comment by Rexcrazy804** [comment]
Sorry haven't seen #364 thank you for closing this pull request.
