### ISSUE TITLE
Copy, paste function doesn't work on windows 10

### ISSUE THREAD

**Issue by compliment** [Eugeny/terminus#43]

**Comment by rfay** [comment]
I ran into this right away too, I assume it's something I just don't know about. I assumed that I'd be able to drag-select and ctrl-c or something, but couldn't figure it out.

**Comment by jmdf** [comment]
CTRL + SHIFT + C / V works for me to copy/paste. I'm running Bash on Windows on Windows 10.

Have you tried that?

**Comment by valeryan** [comment]
@Eugeny answered this here #25.

**Comment by Eugeny** [comment]
@compliment and which shortcut were you attempting to use?

**Comment by valeryan** [comment]
Adding these shortcuts to your README may help to avoid the confusion for most windows users. #44

**Comment by Killertjuh** [comment]
Already read the readme but i`ll like ctr+ ins and shift+ins.

**Comment by compliment** [comment]
@Eugeny CTRL + SHIFT + C / V works on all except clink, actually it freezes the app for sometime for unknown reason. I guess that's my PC though.

**Comment by andydude** [comment]
I'm experiencing the same issue with macos.

**Comment by k0t3n** [comment]
@andydude for MacOS use ⇧⌥⌘V
