### ISSUE TITLE
Use Powershell by default on Windows

### ISSUE THREAD

**Issue by mikemaccana** [Eugeny/terminus#431]
Windows 10 has made powershell the default terminal for some time now - run Win X and 'Powershell' and 'Powershell Admin' have replaced 'Command Prompt' which no longer appears in the list. Additionally the people responsible for maintaining `cmd` at Microsoft state that cmd is no longer being worked on and will receive minimal bug fixes in future. Currently Terminus starts `cmd` by default - I only worked this out after starting a terminal then wondering why `ls` etc suddenly didn't work and my `$profile` wasn't loaded. 

Since Powershell is default for the OS, it would be better for Terminus to use Powershell as the default too.

Even better: detect if PSCore is installed (since installing PSCore provides a good indication you want to use PSCore) then make that default, otherwise falls back to Powershell 5.

**Comment by mikemaccana** [comment]
Eugene thanks for your work on Terminus! I've started using 0.56 as a daily
driver since yesterday and I'm really happy with it.  I've updated
https://github.com/mikemaccana/powershell-profile/ to recommend it as the
best Windows Terminal emulator, over ConEmu, Hyper, Alacritty and
everything else 😃✨

**Comment by Eugeny** [comment]
Thanks Mike, it's the user feedback that keeps me going 🍻
