### ISSUE TITLE
New Terminal button doesn't work

### ISSUE THREAD

**Issue by xmoroccan** [Eugeny/terminus#438]
Version: 1.0.0-alpha.57
Platform: win32 10.0.17134
Plugins:

**Comment by DSlatkin** [comment]
Same here for version 1.0.0-alpha.57, platform win32 10.0.17134.

Screenshot of console error messages after bring up the app settings (these were already present - clicking new tab did not push anything to console):

![screenshot](https://user-images.githubusercontent.com/9263640/46252959-cf90af80-c425-11e8-8274-ae2ff66d2a3f.png)
