### ISSUE TITLE
Native scrollbars on Windows?

### ISSUE THREAD

**Issue by DRSDavidSoft** [Eugeny/terminus#440]
### Terminus is displaying "native" scrollbars on Windows
If you look to the right, you can see that the scrollbars are native-styled.
<img width="548" alt="terminus-sb" src="https://user-images.githubusercontent.com/4673812/46289210-3ed8e180-c595-11e8-80bd-0f06bbdb13bf.png">

Could you replace these scrollbars with something like [OverlayScrollbars](https://kingsora.github.io/OverlayScrollbars/#!overview) instead?

**Comment by Calinou** [comment]
I can reproduce this on https://github.com/Eugeny/terminus/commit/dff55558dd05c7d5cc743cdbf0d2e7dad5d11dd4.

![terminus_native_scrollbar](https://user-images.githubusercontent.com/180032/49297101-3e3bc900-f4ba-11e8-9ecb-6a8a60db72ce.png)
