### ISSUE TITLE
WSL Shell Missing

### ISSUE THREAD

**Issue by ChaosZero112** [Eugeny/terminus#441]
Updating to Alpha 57 removed my WSL/Bash option from Shell selection

![image](https://user-images.githubusercontent.com/22225233/46312955-9b87cc80-c594-11e8-8e1e-5601e423dfa5.png)

Rolling back to 56 it appears again.

![image](https://user-images.githubusercontent.com/22225233/46313167-1a7d0500-c595-11e8-9812-adb2d7b0a7a5.png)

**Comment by Eugeny** [comment]
Fixed in #443
