### ISSUE TITLE
pasting doesn't work

### ISSUE THREAD

**Issue by Woozyman** [Eugeny/terminus#445]
Version: 1.0.0-alpha.58
Platform: win32 6.1.7601
Plugins: shell-selector

when copying the text for eksample 'Pro' and right-clicking in terminal and clicking on paste nothing happens. changing right-click function to paste or pasting with Ctrl+Shift+V adds "200~" in front of what is pasted and "201~" after. Witch gives in this case "200~Pro201~"

**Comment by Eugeny** [comment]
This means your shell doesn't support bracketed paste - disable it in the Terminal settings
