### ISSUE TITLE
RPM misses metadata

### ISSUE THREAD

**Issue by rochacbruno** [Eugeny/terminus#45]
Screenshot can be added

![screenshot_2017-07-03_16-18-08](https://user-images.githubusercontent.com/458654/27805475-49b377f0-600b-11e7-824d-e868678da88f.png)

Ir says license is proprietary
![screenshot_2017-07-03_16-17-57](https://user-images.githubusercontent.com/458654/27805480-4e57322e-600b-11e7-8463-30b341def4e4.png)

**Comment by Eugeny** [comment]
Which package installer is this? Please note that in such software (e.g. gnome-software or Ubuntu app store), screenshots are a part of the official repository, not the RPM/DEB files.

**Comment by Eugeny** [comment]
Closing due to the lack of activity. Please feel free to reopen if the bug is still relevant!
