### ISSUE TITLE
Plugins search API broken

### ISSUE THREAD

**Issue by Domain** [Eugeny/terminus#451]
[https://api.npms.io/v2/search?q=terminus-plugin+quick-commands](https://api.npms.io/v2/search?q=terminus-plugin+quick-commands)
[http://registry.npmjs.org/-/v1/search?text=keywords:terminus-plugin+quick-commands](http://registry.npmjs.org/-/v1/search?text=keywords:terminus-plugin+quick-commands)

The first one return version 1.0.1, while the second one return 1.1.0

I know this is an issue of npm, but they has no reponse now, maybe we should change to the second API.

[https://npm.community/t/v2-search-api-broken/2509](https://npm.community/t/v2-search-api-broken/2509)
[https://npm.community/t/npm-search-api-returns-incorrect-version-date-fields/484/7](https://npm.community/t/npm-search-api-returns-incorrect-version-date-fields/484/7)

**Comment by Eugeny** [comment]
Strangely enough, I've changed from npmjs.org to npms.io because npmjs.org registry used to have the same problem (showing outdated package info). Reverted now in c2f4c34
