### ISSUE TITLE
Suggest CSS fixes for tabs to expand and use available space

### ISSUE THREAD

**Issue by mikemaccana** [Eugeny/terminus#458]
Right now, Terminus's tabs won't expand to fill available space properly (like eg, Firefox or iTerm  
etc)

Current CSS with two tabs:

![image](https://user-images.githubusercontent.com/172594/46666352-6136b480-cbbe-11e8-9902-7f432ac98c78.png)

Current CSS with 6 tabs:

![image](https://user-images.githubusercontent.com/172594/46666372-70b5fd80-cbbe-11e8-8e43-5f49a8dfa8ab.png)

Making the following CSS changes:

 - Adding `justify-content: space-between;` to `tab-bar`
 - Moving `btn-tab-bar` as the last item of `.tabs`
 - Wrapping `.btn-group` and `window-controls` into their own new `div` (let's call it `.controls`)  with `display: flex` on the new div
 - Moving `.drag-space` to be the first item of `.controls`

Updated CSS with two tabs

![image](https://user-images.githubusercontent.com/172594/46666131-c4741700-cbbd-11e8-8e2b-16ed7f1f8053.png)

Updated CSS with 6 tabs (and Settings)

![image](https://user-images.githubusercontent.com/172594/46666746-62b4ac80-cbbf-11e8-857e-e0064622d1da.png)

**Comment by mikemaccana** [comment]
For drag space there's a few options:

 - You could move drag space into the new div, to keep the drag space and the expandability
 - You could position the drag space to the left of the tabs and add an icon, like vscode does:

![image](https://user-images.githubusercontent.com/172594/46666869-cdfe7e80-cbbf-11e8-8c94-78071144ad3e.png)

**Comment by Eugeny** [comment]
Is there a visual difference between the 1st and 3rd images?

The reason the tabs don't take all the width is the drag space. I followed the MS Edge's approach on this one.
However, deleting this div, hiding it via user CSS or minimizing its width gives me the same layout as on your last screenshot.

Might be that I'm overseeing something though?

**Comment by mikemaccana** [comment]
Edge's approach would work too - maintainly a roughly '2 squares' width for the drag area. 

![image](https://user-images.githubusercontent.com/172594/46685923-94913780-cbee-11e8-8c07-536f3815ed6f.png)

It's just that currently the tabs don't expand as much as Edge's do.

But vscode looks great too:

![image](https://user-images.githubusercontent.com/172594/46685969-b4286000-cbee-11e8-8396-dca5dbd2d976.png)

**Comment by Eugeny** [comment]
Ahh got it. Feel free to reduce the drag zone min-width to two squares then!

And I'm totally fine with having the VSCode style as an option (another `appearance.frame` config value) if you can build it - for the icon div, set `.terminus-logo` class and specific width and height - that should do the trick.

**Comment by CrashLaker** [comment]
Hi @Eugeny,
could you help me on how can I increase the tabs sidebar width?
as in this example.
![image](https://user-images.githubusercontent.com/4432491/118051166-eb3af100-b356-11eb-8d28-1b4346c036a0.png)

**Comment by Eugeny** [comment]
@CrashLaker try 

```css
.tab-bar > .tabs {
	width: 400px;
}
```

**Comment by CrashLaker** [comment]
hi @Eugeny 
thank you for your reply.
you mean like this?
![image](https://user-images.githubusercontent.com/4432491/118145949-85954600-b3e4-11eb-8e85-00d2d7d8da41.png)

![image](https://user-images.githubusercontent.com/4432491/118146008-904fdb00-b3e4-11eb-8b54-7982305248e5.png)

i did not work :(

**Comment by CrashLaker** [comment]
got it to work.
needed to also style the wrapper div
```css
.tab-bar {
	width: 400px !important;
}
.tab-bar > .tabs {
	width: 400px !important;
}
```
thank you @Eugeny

**Comment by rodalpho** [comment]
For anyone reading several years later, the CSS changed. Here's how I shrunk the drag space to 20px in mid-2024.

```
.tab-bar > .btn-space {
  min-width: 20px !important;
  flex: 0 0 20px !important;
  width: 20px !important;
}

.tab-bar > .btn-space.persistent {
  min-width: 20px !important;
}

.tab-bar > .window-controls-spacer {
  min-width: 138px !important; 
}
```
