### ISSUE TITLE
The colors of the letters are not shown

### ISSUE THREAD

**Issue by fredmanre** [Eugeny/terminus#46]
The colors inside the terminal for files, and directories do not change

**Comment by Eugeny** [comment]
Could you be more specific?

**Comment by fredmanre** [comment]
In my so opensuse tumbleweed(gnu/linux) when try change the color letter's,
nothing's happend, the color letters don't change. Also i can't install
plugings; I don't know if is a problem of my operative system.

**Comment by Eugeny** [comment]
What exactly are you doing to change the colors? Does your shell show colors in other terminals?

**Comment by fredmanre** [comment]
Yes, the shell can change the color in others terminals, the app works
perfectly in debian and derivatives but in opensuse tumbleweed work fine
but the color of the letters don't change

**Comment by Eugeny** [comment]
Closing due to the lack of activity. Please feel free to reopen if the issue is still relevant!
