### ISSUE TITLE
Slight tweak to Windows icon

### ISSUE THREAD

**Issue by mikemaccana** [Eugeny/terminus#461]
Just to fit in more with the Windows 10 style - single color with gradients rather than multiple colors.

![image](https://user-images.githubusercontent.com/172594/46687614-3155d400-cbf3-11e8-9dcf-9bacd1019ed9.png)

I have in SVG and packed ico, let me know if you like it and I'll send a PR.

**Comment by Eugeny** [comment]
Nice - if the ICO is high-res, you can replace the one under `build/windows` too.

**Comment by DRSDavidSoft** [comment]
@mikemaccana I like this new icon, thanks for tweaking it!

**Comment by mikemaccana** [comment]
Thanks @DRSDavidSoft!
