### ISSUE TITLE
Terminal doesn't work

### ISSUE THREAD

**Issue by NixNotCastey** [Eugeny/terminus#463]
Version: 1.0.0-alpha.60
Platform: win32 10.0.16299
Plugins:  Only standard one

After update to alpha 60, terminal stop working and list of shells is empty.

**Comment by Eugeny** [comment]
Is your Windows locale different from English?

**Comment by NixNotCastey** [comment]
Yes, I've Polish locale on Windows.

**Comment by Eugeny** [comment]
Please try https://github.com/Eugeny/terminus/releases/tag/v1.0.0-alpha.61
