### ISSUE TITLE
Terminus breaks when switching between terminus settings

### ISSUE THREAD

**Issue by jithinlal** [Eugeny/terminus#464]
Happens when switching between settings tabs

**Comment by Eugeny** [comment]
What does "breaks" mean?

**Comment by jithinlal** [comment]
Terminus freezes and not responsive

**Comment by Xedecimal** [comment]
What OS? What version? I'm switching between settings pages here (hopefully you mean the left side pages of the settings tab) on Windows 10 version Alpha 61. Unless you have multiple settings tabs open at the same time which I couldn't replicate.

**Comment by jithinlal** [comment]
My OS is ubuntu 18.04 and my terminus version is Alpha 61.
I don't have multiple settings tab.
Only one, and i get this bug when the settings page is open at the first time.
That means, once the bug appears, I force quit the app and then reopens and settings will work with no problem
