### ISSUE TITLE
Release a 1.0?

### ISSUE THREAD

**Issue by mikemaccana** [Eugeny/terminus#465]
Terminus is already usable as a daily driver and, at least on Windows, is already far better than ConEmu, Hyper, Alacritty, the inbuilt Windows console, etc. Releasing a 1.0 might get more contributors.

**Comment by Xedecimal** [comment]
Heck no, there are still very breaking issues. For example, I ctrl+clicked on something thinking I could navigate to links (without that plugin installed) and some weird black box showed up on my secondary monitor. I had to close it with the start bar icon. Vibrancy issues and CPU consumption are pain points for users right now. If a stable version was released with an application this unstable all it would do is flood the issues page with a lot of angry users expecting more.

Take your time and make it right the first time. Popularity isn't important, once people are flooding in, your issue lists, forks, and feature requests will be through the roof and overwhelming. Even if you have a load of people submitting pull requests that are just more things for you to weed through slowing down your active development.

I say keep it alpha for a while longer. I'm using it fine in alpha and so are a lot of other people. A good product will gain popularity all by itself. A smaller group of contributors outweighs a much larger group of feature requesters any day!
