### ISSUE TITLE
Suggestion: make Terminus appear under 'T' rather than 'E' in Windows start menu

### ISSUE THREAD

**Issue by mikemaccana** [Eugeny/terminus#466]
Since Terminus is installed to a folder named after you, it appears under 'E' in the start menu. Not a big deal, most users would keep it on the taskbar or use search, but if you were looking for it, you'd expect it to be under 'T'.

![image](https://user-images.githubusercontent.com/172594/47011350-a6686280-d139-11e8-9edf-229e20a674e5.png)

**Comment by Eugeny** [comment]
Uhh - never noticed that 😅 it's apparently Squirrel's defaults
