### ISSUE TITLE
Black Screen 

### ISSUE THREAD

**Issue by LuisAdrianAzka** [Eugeny/terminus#467]
Version: 1.0.0-alpha.61
Platform: win32 6.1.7601
Plugins: None?

It's the first time that I use terminus, but when I push +Terminal it doesn't open.
I tried to see Configuration -> Terminal and the application crashes... It turns to black screen...

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs
