### ISSUE TITLE
npm is not installed

### ISSUE THREAD

**Issue by tnguyen14** [Eugeny/terminus#47]
Hi,

I just downloaded Terminus for the first time tonight on my Windows machine (with WSL), and I'm really impressed. It got a lot of nice things right.

I was also impressed with the long list of themes available right out of the box.  Well done!

I have a few simple questions that I was hoping you could help with:
- Can a new theme be added? I was pleasantly surprised when I saw the Tomorrow Night themes. Those have now been superseded by Base16 themes (see https://github.com/chriskempson/base16), which is a very popular project. Could support for that be added?
- On the plugins page, it says that NPM is not installed, even though I do have npm installed on WSL. But it's probably not where terminus is looking for it. Where should I have node and npm installed for it to pick up?
- Is there a way I could set the default path for a new terminal WSL windows? Right now, it is set to ` /mnt/c/Users/tri/AppData/Local/terminus/app-1.0.0-alpha15`. I wonder if that could be changed to home (`~`).

Thank you very much for the amazing work put into this so far. Please let me know if there's anything I could help with.

**Comment by tnguyen14** [comment]
I'm also aware that these are 3 questions combined into a single issue. I thought I'd do that to avoid spamming the repo. If you'd prefer they be split into their own issues, I'm more than happy to do that.

**Comment by Eugeny** [comment]
1. Currently it has to be either built as a plugin, or installed as a Hyper theme. I'm working to add an ability to automatically pick up themes from other sources on the system
2. `npm` should be available on `$PATH` for the detection to work. This works with e.g. the official NodeJS installer (linked directly inside Terminus).
3. Please open this as a separate bug and I'll take a look!

**Comment by tnguyen14** [comment]
I've opened #60 for 3.

For 2, I have node and npm available on `$PATH` inside WSL. It could be that Terminus looks for it in Windows system path somewhere? I'll try installing Node directly on Windows and report back.

**Comment by Eugeny** [comment]
Yes, it needs the Node to be installed in Windows itself, because it will then use npm to install packages into its own directory, which is outside of WSL.
