### ISSUE TITLE
It seems like it doesn't support emojis.

### ISSUE THREAD

**Issue by ShivanshuKantPrasad** [Eugeny/terminus#471]
In the below screenshot emojis are not rendered properly.
[emoj](https://www.npmjs.com/package/emoj) is a machine learning node module.

![annotation](https://user-images.githubusercontent.com/17960975/47150776-47e7e380-d2f5-11e8-99c8-a57eac6564e7.png)

**Comment by Eugeny** [comment]
Which OS/shell?

**Comment by ShivanshuKantPrasad** [comment]
OS: Windows 10
Shell: WSL (zsh with spacehip)

**Comment by ShivanshuKantPrasad** [comment]
What font are you using. I tried several fonts none of them work.

**Comment by Eugeny** [comment]
![image](https://user-images.githubusercontent.com/161476/47603310-b100e280-d9ea-11e8-8b1a-73f8c3cc5724.png)

Default (Consolas)

**Comment by ShivanshuKantPrasad** [comment]
What build of windows 10 are you using.
It seems from the [windows console repo](https://github.com/Microsoft/console/issues/190) and [wsl repo] that it doesn't support unicode characters and it is working on it. Maybe they have launched it in a insider release or something.
 To check windows build Run `winver` in run prompt(Win + R).

**Comment by Eugeny** [comment]
Build 1803

You could also try switching between the hterm and xterm frontends

**Comment by ShivanshuKantPrasad** [comment]
i tried switching

**Comment by SRGOM** [comment]
It works, lets stop this discussion here. And free the dev for making more awesome stuff.

**Comment by Eugeny** [comment]
@SRGOM this is not the kind of attitude that I appreciate here.

**Comment by SRGOM** [comment]
You're kind, ill leave. But don't spend too much time on people asking without trying.

**Comment by ShivanshuKantPrasad** [comment]
well I was not able to solve it and now I am using Linux instead of windows, so you may close it. Maybe my install was corrupted.

**Comment by ebissonn** [comment]
I have this rendering with 1.0.87 and Windows 1809 / Build 17763.615

![image](https://user-images.githubusercontent.com/51915159/61981919-19f0a780-afc9-11e9-9eee-d869680a2185.png)

but I should see this instead

![image](https://user-images.githubusercontent.com/51915159/61981969-41e00b00-afc9-11e9-97ba-586af1b6c026.png)

**Comment by Ray-Eldath** [comment]
@ebissonn same on my device
![image](https://user-images.githubusercontent.com/7938763/82756547-756c0b80-9e0d-11ea-8ed8-c109c7dfa40c.png)

Windows 10 1909. tried switching between fonts and hterm/xterm... non of them works. still investigating... 🤒
