### ISSUE TITLE
New terminal button does not open any terminal

### ISSUE THREAD

**Issue by kapiladhanvi** [Eugeny/terminus#472]
Version: 1.0.0-alpha.57
Platform: win32 10.0.17134
Plugins: altair

I've set my terminal to gitbash. Clicking on the "New Terminal" button does not do anything -- does not open anything at all. Also when I check under settings for terminals, I dont see anything there - 
![image](https://user-images.githubusercontent.com/6342961/47249245-286cbb80-d3c6-11e8-8467-70fb958e2ac0.png)

**Comment by Eugeny** [comment]
Please upgrade to the latest alpha
