### ISSUE TITLE
Paste problems

### ISSUE THREAD

**Issue by hiddehs** [Eugeny/terminus#473]
When I try to paste text into a sublevel of the console (WSL in my case), for example mysql> or nano, the pasted text will be surrounded with 0~ and 1~
`mysql> 0~SELECT longqueryyoumaywanttopaste1~`

Windows consoles are also doing some fun stuff:
CLink : `00~  -  ~01~`
Stock : `[200~  -  [201~`

Running win10 & alpha-61

**Comment by Eugeny** [comment]
This means your shell does not support bracketed paste - disable it under Settings > Terminal > Behaviour
