### ISSUE TITLE
The text generated by the Chinese input method cannot be displayed on the screen 

### ISSUE THREAD

**Issue by JiangBoy** [Eugeny/terminus#4740]
Version: 1.0.158
Platform: Windows x64 10.0.17763
Plugins: none
Frontend: xterm
![issue](https://user-images.githubusercontent.com/12654896/136879239-6f9c069a-6389-4541-b9f2-f6c04d7d3717.gif)

**Comment by psyuhen** [comment]
![image](https://user-images.githubusercontent.com/6522440/136906091-628b9ecd-eeee-4713-9691-1c05b388ae9f.png)

Windows的也OK哟

**Comment by Starrry** [comment]
老铁，我也可以

**Comment by Eugeny** [comment]
@JiangBoy let me know if upgrading to v159 helps.

**Comment by JiangBoy** [comment]
> ![image](https://user-images.githubusercontent.com/6522440/136906091-628b9ecd-eeee-4713-9691-1c05b388ae9f.png)
> 
> Windows的也OK哟

Please tell me what input method you are using
