### ISSUE TITLE
Duo Multi-factor Authentication prompt should not be truncated

### ISSUE THREAD

**Issue by junctionapps** [Eugeny/terminus#475]
Using DUO for multi-factor authentication on a ssh server. When doing so, on connection it presents a prompt with multiple lines asking if a push, text or phone call is desired. Other clients will display it as a multi line prompt; Terminus opens a dialog box, but displays a prompt with a form with the truncated prompt (ellipses char around position 65) as the label, and response expected in the form input. Clicking on the label makes the text bigger and appears in the form input area; hovering does not reveal the full prompt text.

This is not a huge issue; if you know which option is desired, entering that value allows one to proceed.

The setup for DUO is outlined at:
https://duo.com/docs/duounix

Terminus Prompt:
![image](https://user-images.githubusercontent.com/8778630/47363012-28153e80-d6ac-11e8-90c4-08fc4166e815.png)

Sample from Putty:
![image](https://user-images.githubusercontent.com/8778630/47362874-d4a2f080-d6ab-11e8-8d0c-3cc21d3d930c.png)

**Comment by Eugeny** [comment]
Hey, judging by the screenshot, you might be looking for http://support.termius.com/
