### ISSUE TITLE
Windowed fullscreen not available for Mac OS

### ISSUE THREAD

**Issue by Hugo-Duarte** [Eugeny/terminus#4754]
Version: 1.0.159
Platform: macOS x64 20.6.0
Plugins: none
Frontend: xterm

First of all thanks, I think this is more a suggestion than an issue.

Currently, we are only able to have the fullscreen option or windowed. Is it possible to add "windowed fullscreen" similar to other applications (e.g chrome) which when we double-click the window on the top bar just sets the maximum height and width for that screen and attach it to the top while still showing the Mac OS default top bar?

**Comment by psyuhen** [comment]
brother, try change mac os to windows ?
