### ISSUE TITLE
Error open

### ISSUE THREAD

**Issue by Darwinrv94** [Eugeny/terminus#476]
![imagen](https://user-images.githubusercontent.com/15697929/47489322-557cfc00-d814-11e8-8969-c6a258e52d92.png)

**Comment by Eugeny** [comment]
This means your config file is corrupted. You can find it at https://github.com/Eugeny/terminus/wiki/Config-file

**Comment by Darwinrv94** [comment]
Thank you!

**Comment by Darwinrv94** [comment]
Uninstall the program, delete the temporary files and change the configuration file and the error persists
