### ISSUE TITLE
CMD(stock) can't read environment variables.

### ISSUE THREAD

**Issue by suyanhanx** [Eugeny/terminus#481]
Is this cmd the same with Windows' system cmd?
It can't read system's environment variables.

OS: Windows 10
Shell: CMD(stock)

**Comment by DRSDavidSoft** [comment]
@suyanhanx It's the same `cmd.exe` of Windows.
Run `SET` in both of **Terminus** and stock **Command Line** windows and compare the environment variables.

**Comment by DRSDavidSoft** [comment]
@suyanhanx Can you post a screenshot of both `SET` commands?

**Comment by suyanhanx** [comment]
Oh I know. It can find the user's environment variables but can't find system's.
This is the problem

**Comment by DRSDavidSoft** [comment]
@Eugeny This is odd – should this be happening?

**Comment by suyanhanx** [comment]
In my option, this command is pretty common on terminal softwares.

Why not to add it ?

**Comment by Eugeny** [comment]
@suyanhanx I already did - you can start an admin shell from the context menu

**Comment by suyanhanx** [comment]
@Eugeny Oh, thank you.

It didn't notice me to update. I have found this command after updated.

issue close
