### ISSUE TITLE
display error while open from Windows 10 context menu

### ISSUE THREAD

**Issue by 4332weizi** [Eugeny/terminus#483]
Version: 1.0.0-alpha.62
Platform: win32 10.0.17763
Plugins: 

In Windows 10 folder，open from context menu “open terminus here”。2 tabs opened，the first tab has a display error

![qq 20181029155834](https://user-images.githubusercontent.com/5563945/47643774-62e50e00-dba7-11e8-9759-0acea40c7a3c.png)

**Comment by Eugeny** [comment]
This should be fixed in the latest nightly.
