### ISSUE TITLE
Small suggestion: use 'transparency' rather than 'vibrancy'

### ISSUE THREAD

**Issue by mikemaccana** [Eugeny/terminus#485]
Replace 'vibrant' with 'transparent' and 'vibrancy' with 'transparency' in both the README and the settings screen. 

 - Vibrant means having energy. It's not clear what 'vibrant' means in terms of a terminal

 - Currently 'vibrancy' needs to be explained - using the term 'transparent'. Which probably means transparent is a better name.

![image](https://user-images.githubusercontent.com/172594/47655524-15f04000-db85-11e8-8886-5aaf828d5cf3.png)

**Comment by Eugeny** [comment]
This actually refers to a specific term: https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/translucency/

On Windows, MS's latest implementation is called "Acrylic background" (https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic), but it's supported on Insider Builds only so far. 

The background style used on the latest stable is the same as Windows Aero, but MS has deprecated this name AFAIK.

**Comment by mikemaccana** [comment]
So does Terminus do this:

> They also use vibrancy, a subtle effect that dynamically blends the foreground and background colors using a careful balance of lightening and darkening techniques. 

I wonder if 'Acryllic' could be better on Windows, and 'Translucency' on Mac, per those links.

**Comment by Eugeny** [comment]
I'd argue that macOS users are generally aware of vibrancy as a "brand name", but dynamically renaming it to Acrylic on Windows would probably be nice.
