### ISSUE TITLE
Underscore Cursor Missing in Terminal

### ISSUE THREAD

**Issue by Dannyftm** [Eugeny/terminus#486]
I had my cursor set as the underscore cursor shape and it does not show up in the terminal while using it.

**Comment by echang24** [comment]
I have the same issue - using build 63 - tried all kinds of combinations of themes, backgrounds, etc... 

![image](https://user-images.githubusercontent.com/8852155/48996113-bcd1e880-f0ff-11e8-9209-9cbe7f9ebdc8.png)

**Comment by Elderry** [comment]
I have beam shape, also missing, build 63.

**Comment by lpulley** [comment]
@NuSkooler I get this issue but only when there are certain special Unicode characters in my prompt. For example, when using the Agnoster theme in Zsh, when I am not in a git folder it looks fine, but when I am in a git folder, my prompt looks ![like this](https://user-images.githubusercontent.com/7193187/51929572-2bf8e100-23be-11e9-83b3-0e3841469801.png) and that special "branch" icon appears to be offsetting the cursor position.

**Comment by NuSkooler** [comment]
@lpulley this may be my issue as well. I have Fish shell installed. Here is a SS while I cd (note the cursor position):

![image](https://user-images.githubusercontent.com/1509339/51930522-0cf75080-23b8-11e9-9feb-6880ebbc8fec.png)

**Comment by Eugeny** [comment]
Guys, could you please see if switching the frontend to xterm helps?

**Comment by Eugeny** [comment]
xterm is now the default frontend and underscore cursor works in ti
