### ISSUE TITLE
Split panes support

### ISSUE THREAD

**Issue by csrgxtu** [Eugeny/terminus#49]
could terminus support split screen

**Comment by faraazahmad** [comment]
Yes please! this is a much needed and appreciated feature for productivity

**Comment by marcelosuzumura** [comment]
I use terminator a lot on Ubuntu because of the split panels, but if I could split panes with Terminus, I'd surely switch over. Terminator is crashing a lot lately.

**Comment by rianquinn** [comment]
Split panes, and multiple windows are really needed to make this a more complete terminal emulator.

**Comment by renatn** [comment]
You can use Screen =) but i agree embedded feature much better

**Comment by youurayy** [comment]
Killer feature, e.g. when 
- managing multiple servers simultaneously and need to observe all at once
- compiling in one view, observing reload script in another, having git in yet another, etc.
ConsoleZ has it, and very easy to create vertical splits by cmd+shift+E and horizontal splits by cmd+shift+O without limits.
Then it's possible to move between the splits in arrow-like nature: <some modifiers> + arrow (will focus the next split up/down/left/right -- this is tricky if the splits aren't completely aligned, e.g. you have 1 vertical split with 3 horizontal splits on the left and 4 vertical splits on the right -- but let's say that the cursor will be moved to the split sharing the most _border_ area with the current split, as the user can always adjust with multiple movements. (that kind of navigation would be even better than what ConsoleZ currently has)

**Comment by jderus** [comment]
Yeah, I am gonna +1 on this request.
Right now I am swapping between a couple of different OSS terminal solutions:
1) ConEmu (via Cmder)
2) Hyper 
3) Terminus

I like how your approach/choices are pushing towards ng2x+. That makes me feel like I could dig in and contribute one day if I really needed to. But at the same time, some of the other approaches currently have quite a bit more features I find handy - especially splitting a tab.

I am hoping that Terminus will get there one day, especially if we pipe up and voice a desire for the feature :) In the meantime, perhaps you can draw inspiration from those other tools...

**Comment by wolf99** [comment]
Just discovered Terminus and really like it; it is a serious contender for taking over my puritanical sticking to windows console for WSL and CMD. *But* only because it looks nice and it installs easy on Windows... because I can't view things side by side, and I can't open more than one instance to instead arrange the instance as panes, this is actually worse in this regard than plain old console.exe >.< - mega +1 on this request

**Comment by youurayy** [comment]
In ConsoleZ, I can quickly build up the screen I like by pressing CTRL+Shift+O (new horizontal split) and CTRL+Shift+E (new vertical split).  Then I've setup CTRL+arrows to move between the created windows.

Of course ConzoleZ (and others) depend on cmd.exe/WSH, so they are nasty drain on the OS resources.

**Comment by taylorjdawson** [comment]
> You can use Screen =) but i agree embedded feature much better

@renatn 
What is Screen?

**Comment by jwhipp** [comment]
I actually came here to comment on screen not being a replacement but, turns out it has that functionality.  Here's a good blog on the subject:

https://tomlee.co/2011/10/gnu-screen-splitting/

Still, +1 for this being a built-in feature.

**Comment by taylorjdawson** [comment]
@jwhipp you were able to get screen splitting to work with `Screen`. What is your setup? I am using WSL and can't get it to work

**Comment by jwhipp** [comment]
@taylorjdawson  I haven't used it personally, I tend to use terminator with the WSL.  For a while Tilix was working but it's not now.   

The article I linked goes over how to run it for the most part.

**Comment by Mezner** [comment]
I'd be interested in contributing this feature potentially. Any thoughts on how you'd like to go about doing it?

**Comment by Eugeny** [comment]
It should be possible to implement splitting itself by displaying "tab sets" in tabs instead of a single `BaseTabComponent`. There are however problems with rearranging the splits/panels as using any kind of looping (ngFor) or component nesting means that components will get recreated, destroying the current terminal state. This can be theoretically avoided by directly attaching the components via Angular `ViewRef`s

**Comment by dawin09** [comment]
I'm waiting for this feature so I can switch to terminus.

**Comment by dirtypants** [comment]
+1 for screen spliting. tmux/screen are great but it's incredibly convenient to have it built in the client.

**Comment by Eugeny** [comment]
@bastiao this ticket isn't closed - and it's definitely on the roadmap!

**Comment by ScripterSugar** [comment]
+1 for this feature too. Really need it and very disappointed this is not yet implemented

**Comment by Hans941** [comment]
Yeah, this feature is really useful. Hoping ... +1.

**Comment by codeship-iai** [comment]
mouse support for tmux would be sufficient for me.

**Comment by mquinnv** [comment]
mouse support for tmux would be sufficient for me

**Comment by bastiao** [comment]
@Eugeny you did it great! Thank you! 
That's really change the way that we use terminus. I'm using nighly builds already.

**Comment by Eugeny** [comment]
@bastiao glad you liked it!

**Comment by ScripterSugar** [comment]
@Eugeny Also using nightly builds here. Totally satisfied with new feature. Great job.

**Comment by dirtypants** [comment]
@Eugeny Another sincere thank you for split panes! It's very well done and lets me use terminus as my daily console driver.

**Comment by Eraldoe** [comment]
@Eugeny I think there is a bug with this feature. On Windows 10 running Terminus Alpha 73 when you click the divider bar to change the size of a split pane, it will deselect the bar (and thus stop moving the divider) if your cursor moves outside the bar. The effect is that you must drag the bar extremely slowly. Check out this gifv to explain what I mean. If I move quickly, the bar stops dragging.

![Op9tu61PF4](https://user-images.githubusercontent.com/16160354/54207617-db8e9c00-44b0-11e9-9db2-b5b4ae6a487c.gif) (image mirrored at  https://i.imgur.com/mchGDGG.gifv)

**Comment by hardwareadictos** [comment]
Hi all! ¿Is it possible to implement split mode as it is on MobaXTerm, just splitting the terminal into two or more tabs instead of attatching one terminal into a tab via hotkeys as its being done now? Its the only thing left for me and my team to use it at work, its nice software what you are making Eugeny :)

**Comment by Wazbat** [comment]
For anyone finding this on google, the default keybinds don't work for me on Ubuntu. In the settings menu change "Split to the right" and "Split to the bottom" to something else. I'm using the numpad arrows with the same modifier as before

**Comment by jonesmith518** [comment]
nice feature!

**Comment by JamieCorkhill** [comment]
Is it possible to have different terminals/profiles in each pane? I.e, could I have Powershell top left, Bash top right, and normal Windows CMD on the bottom, for example?

Thank.

**Comment by mnmami** [comment]
For those landing here and wondering how the feature can be used, go to Settings then Hotkeys, then search for "split". In Windows, the default values should be Ctrl-Shift-E and Ctrl-Shift-D for 'split to the right' and 'split to the bottom, respectively.

**Comment by Jimmy-Newtron** [comment]
> For those landing here and wondering how the feature can be used, go to Settings then Hotkeys, then search for "split". In Windows, the default values should be Ctrl-Shift-E and Ctrl-Shift-D for 'split to the right' and 'split to the bottom, respectively.
> 
> UPDATE: a more intuitive way that I didn't immediately spot was simply to right-click any terminal then select "Split".

Even more intuitive would be an icon button that can fit visually on the menu bar (close to the new tab button)

**Comment by j-autuick** [comment]
great feature, works pretty good. I was curious, since I cannot find it, but is it possible to close a split window?

**Comment by Eugeny** [comment]
@j-autuick you can either exit the shell inside, or use the "close focused pane" shortcut

**Comment by efrenmarin45** [comment]
Is there a way to set up all new tabs be split by default?

**Comment by Eugeny** [comment]
Yes, and profile can be the default profile, including one based on a split tab (Tab context menu -> save profile)
