### ISSUE TITLE
Change "Update Available" button to releases page instead of specific release

### ISSUE THREAD

**Issue by Tr4il** [Eugeny/terminus#491]
I hadn't updated in a while, and when I clicked the update button it directed me to a specific alpha release, installed that, and then had to update again. Instead link to the github releases page so that people always get the latest version would be my suggestion.

**Comment by Tr4il** [comment]
I am still learning github, sorry thank you.

**Comment by Eugeny** [comment]
It's likely that I released a new version just shortly after - the update button always points to the latest available release

**Comment by Tr4il** [comment]
I assume so yes. Thanks for the hard work on terminus, apologies for bothering 😁
