### ISSUE TITLE
Clear Quick Connect History

### ISSUE THREAD

**Issue by SnackMix** [Eugeny/terminus#493]
Version: 1.0.0-alpha.62
Platform: win32 6.3.9600
Plugins: Default

Is there a way to clear quick connect history?
If not, it would be great to have because I accidentally pasted a server password into the quick connect and I can't find a way to clear the quick connect history.

**Comment by Eugeny** [comment]
Quick connect only remembers one last entry - typing any nonsense into the quick connect box and pressing Enter will instantly overwrite it

**Comment by SnackMix** [comment]
@Eugeny Thanks for the delete button in Alpha 63! :smiley:
