### ISSUE TITLE
session is freeze when run [git push] or [git pull]

### ISSUE THREAD

**Issue by kxk120** [Eugeny/terminus#496]
Version: 1.0.0-alpha.61
Platform: win32 6.1.7601
Plugins: 
SSH

**Comment by kxk120** [comment]
Login SSH terminal, and as soon as do git push or git pull, terminal will be freeze.(Ctrl+C can not also interrupt that status)

**Comment by qgy18** [comment]
Login SSH terminal, and connect another ssh server, for example, execute `ssh git@github.com`, terminal will be freeze, too. 

Version: 1.0.0-alpha.62
Platform: win32 10.0.17134
Plugins: shell-selector, title-control

**Comment by xRoR** [comment]
Some crazy shit happens here between ssh2 nodejs lib (who use own copy of pag{e}ant) and and great  Electron Framework on which this greatest terminal app of all time build)). On certain circumstances ssh2 go not to own folder, but for root folder which is C:/, and can't find any bit own pagent. 

So workaround for those who desperately need "git push" is - to put that file where it want. This file https://github.com/mscdex/ssh2/blob/master/util/pagent.exe to that place C:\util\pagent.exe
