### ISSUE TITLE
Terminus in my Electron App

### ISSUE THREAD

**Issue by prashantjeetsingh** [Eugeny/terminus#498]
Hi,
I want to use terminus in my electron app.

So basically I want to create a link and upon clicking on that link I want terminus to open so I can execute commands

**Comment by Eugeny** [comment]
You can start commands directly via CLI interface - see `terminus --help`

**Comment by prashantjeetsingh** [comment]
HI,
Sorry if you don't mind, can you explain in details?
Actually, I am new so not getting

My requirement is to create an index.html page which will have a link and upon clicking on that link I can get Terminus to use terminal

So basically I want to merge terminus in my app

**Comment by Eugeny** [comment]
If you're looking to just add a live terminal to your app, it's much easier to combine xtermjs (https://xtermjs.org/) and node-pty (https://github.com/Microsoft/node-pty) directly.
