### ISSUE TITLE
[Feature-request] Add the transparency bar

### ISSUE THREAD

**Issue by VladimirDev93** [Eugeny/terminus#5]
Hey!

I really like your repository and I've spread the news on social platforms. But my question is, can you add the transparency slider for the terminal? Like the one that Ubuntu has?

**Comment by Eugeny** [comment]
At this moment, Chrome has killed transparency while GPU acceleration is enabled - https://github.com/electron/electron/issues/8532#issuecomment-300715940

**Comment by VladimirDev93** [comment]
Ok
