### ISSUE TITLE
Tabs not restored after closing the window normally

### ISSUE THREAD

**Issue by gaui** [Eugeny/terminus#501]
I'm on Windows 10 running Terminus alpha 62 and everytime I close Terminus, all tabs are closed and not restored when running Terminus again.

"Auto-open a terminal on app start" opens a brand new terminal, and is not what I want.

Is this possible? This is the killer feature in Cmder that I love and cannot be without.

**Comment by amoerie** [comment]
ConEmu offers this too, very useful if you work in a lot of repos/environments. Just starting the shells with their last known directory would be a tremendous help!

**Comment by gaui** [comment]
I just tried 1.0.66 and it didn't work. I opened 3 tabs, went to specific directories and then closed Terminus manually. Then I opened Terminus again and it just opened a single tab with the default directory.

Any idea @Eugeny ?

**Comment by gaui** [comment]
Please reopen, this is not fixed.

**Comment by Eugeny** [comment]
Could you please retest it with the latest nightly?

**Comment by glen-84** [comment]
Still not working in `1.0.72`. 😞

**Comment by glen-84** [comment]
It restores the tabs and panes in a different order, and defaults to the user directory.
