### ISSUE TITLE
Windows run in administrator mode: CreateProcess failed

### ISSUE THREAD

**Issue by ingvevs** [Eugeny/terminus#505]
I have powershell as default shell.
Ran terminus as Administrator. I then got the following error from dev tools:

ERROR Error: Uncaught (in promise): Error: Unable to start terminal process: CreateProcess failed
Error: Unable to start terminal process: CreateProcess failed
at new WindowsPtyAgent terminus\app-1.0.0-alpha62\resources\builtin-plugins\terminus-terminal\node_modules\node-pty-tmp\lib\windowsPtyAgent.js:25:24
at new WindowsTerminal terminus\app-1.0.0-alpha62\resources\builtin-plugins\terminus-terminal\node_modules\node-pty-tmp\lib\windowsTerminal.js:45:24)

**Comment by mariusmu** [comment]
I have the same problem. This is the preventing me from using the terminal

**Comment by Eugeny** [comment]
Terminus now includes an option to start administrator shells in tabs without running the whole app as administrator - please use this instead.

**Comment by Eugeny** [comment]
It's available from the terminal context menu, and you can also set any Profile to be run as administrator.

**Comment by mariusmu** [comment]
I cannot find it in on my Windows 10 64bit setup. Is this only available on other platforms?

**Comment by Eugeny** [comment]
It's available _only_ on Windows, starting with Alpha 67
