### ISSUE TITLE
[Feature Request] Word selection on double-click

### ISSUE THREAD

**Issue by kjdms** [Eugeny/terminus#508]
I would like to be able to control word selection when double-clicking, also called word-by-word selection behavior. Currently it seems to end the selection at whitespace or control characters. For example, when I double-click the text "foo@bar" it selects the entire string. I would like to be able to configure Terminus to stop the selection at user-defined symbols, so if I double-clicked the "foo" in "foo@bar" only "foo" would be selected.

**Comment by kjdms** [comment]
:( This is still an issue.

**Comment by kachunkachunk** [comment]
Sublime Text has a nice reference/example you can consider. Here's the word separator list, in case it provides a head-start on this:

```
    // Characters that are considered to separate words
    "word_separators": "./\\()\"'-:,.;<>~!@#$%^&*|+=[]{}`~?",
```

**Comment by Eugeny** [comment]
Ref https://github.com/xtermjs/xterm.js/issues/2091

**Comment by ArsumPB** [comment]
> 
> 
> Ref [xtermjs/xterm.js#2091](https://github.com/xtermjs/xterm.js/issues/2091)

They added this option as of june, can you please follow through?
