### ISSUE TITLE
Feature Request - Support for font ligatures

### ISSUE THREAD

**Issue by duanemck** [Eugeny/terminus#51]
I use FiraCode font which has some nice ligatures. Would be great if they worked in Terminus.

**Comment by shaneneuerburg** [comment]
Allowing use of any font installed on the system would be fantastic

**Comment by Eugeny** [comment]
This is now controlled by the `terminal.ligatures` option in `config.yaml`! https://github.com/Eugeny/terminus/wiki/Config-file
