### ISSUE TITLE
Windows: Powershell input becomes invisible

### ISSUE THREAD

**Issue by kinl99** [Eugeny/terminus#510]
Version: 1.0.0-alpha.62
Platform: win32 10.0.17763
Plugins: altair, clickable-links, shell-selector, theme-hype, theme-windows10, title-control

As soon as one is trying to enter a parameter in powershelll shell to a cmdlet using the "-"-key the inpust becomes invisible

**Comment by oohtj** [comment]
same here.

**Comment by Eugeny** [comment]
This is caused by PSReadline - its default color for parameters is black.

You can change it with e.g.

```
Set-PSReadLineOption -Colors @{
    "Parameter" = [ConsoleColor]::DarkBlue
}
```
