### ISSUE TITLE
[Feature Request] Start new shell as admin

### ISSUE THREAD

**Issue by RobCannon** [Eugeny/terminus#511]
I would like to see the ability to start Terminus as a normal process, but I could start a shell "as admin" to elevate just that shell process.  Ideally this would be integrated with #495 so I could add a shell entry that is a normal process and another version that is the admin version.

**Comment by Eugeny** [comment]
NB: this requires a recent Windows Insider build with ConPTY support

**Comment by Mythos** [comment]
Hey there, I'm not sure where to post this, but on Windows 10 (1809) my windows freezes when trying to create new shell as admin.
According to your note (@Eugeny) you need an insider build of Windows (meaning no released version yet).
So it would be good if there could be some check included to show the menu item only, if Windows version is greater or equal the required one. (maybe using the build number)
Unfortunately I don't know if or how this is doable.

**Comment by Eugeny** [comment]
The check is, in fact, already in place (it checks for Windows build >=17692).

Please check the debug console for any errors.

**Comment by Mythos** [comment]
Thanks for the quick reply!
I'm getting normal logs, no errors (but there'll be a but):
```
[terminal] Using session options: {command: "C:\Users\user\AppData\Local\terminus\app-1.0.68\resources\extras\UAC.exe", args: Array(2), env: {…}, runAsAdministrator: true}
C:\Users\user\AppData\Local\terminus\app-1.0.68\resources\builtin-plugins\terminus-terminal\dist\index.js:8242 hterm resize
C:\Users\user\AppData\Local\terminus\app-1.0.68\resources\builtin-plugins\terminus-terminal\dist\index.js:3102 Resizing to 99x31
C:\Users\user\AppData\Local\terminus\app-1.0.68\resources\builtin-plugins\terminus-terminal\dist\index.js:8242 hterm resize
C:\Users\user\AppData\Local\terminus\app-1.0.68\resources\builtin-plugins\terminus-terminal\dist\index.js:3102 Resizing to 99x31
C:\Users\user\AppData\Local\terminus\app-1.0.68\resources\builtin-plugins\terminus-terminal\dist\index.js:8242 hterm resize
C:\Users\user\AppData\Local\terminus\app-1.0.68\resources\builtin-plugins\terminus-terminal\dist\index.js:3102 Resizing to 99x31
C:\Users\user\AppData\Local\terminus\app-1.0.68\resources\builtin-plugins\terminus-terminal\dist\index.js:8242 hterm resize
C:\Users\user\AppData\Local\terminus\app-1.0.68\resources\builtin-plugins\terminus-terminal\dist\index.js:3102 Resizing to 99x31
C:\Users\user\AppData\Local\terminus\app-1.0.68\resources\builtin-plugins\terminus-terminal\dist\index.js:8242 hterm resize
C:\Users\user\AppData\Local\terminus\app-1.0.68\resources\builtin-plugins\terminus-terminal\dist\index.js:3102 Resizing to 99x31
C:\Users\user\AppData\Local\terminus\app-1.0.68\resources\builtin-plugins\terminus-terminal\dist\index.js:3780 session exit
```

Now the BUT: The render process somehow dies, leading to a lost connection (between Terminus <--> Chrome Dev Tools) and rendering the process unusable, only to be killed via task manager.

But2: I'm seeing that it's calling the UAC of Windows, which I disabled, so I don't get a prompt for every admin action.
But3: Sometimes it just closes the tab, not rendering the process unusable.

**Comment by Mythos** [comment]
Appendix: I'm currently running Windows 10 Pro (1809, Build 17763.253)

**Comment by Eugeny** [comment]
Try disabling ConPTY in Settings -> Shell

**Comment by Mythos** [comment]
Unfortunately disabling it doesn't help too much. I had more auto-closes, but was still able to cause this issue.
