### ISSUE TITLE
Hotkey settings broken with Ubuntu 18.04 WSL distro installed

### ISSUE THREAD

**Issue by cternes** [Eugeny/terminus#517]
I'm running the version 1.0.0-alpha.62 on Windows 10 and I'm not able to add a new hotkey or change an existing one.

Click on "Add..." does nothing. How can I solve this?

**Comment by Eugeny** [comment]
Please see if you're getting any error messages in the console: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by cternes** [comment]
Yes, lots of errors:
`C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:12355 ERROR TypeError: Cannot read property '04' of undefined
    at SettingsTabComponent.getHotkey (C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\builtin-plugins\terminus-settings\dist\index.js:1051)
    at Object.eval [as updateDirectives] (SettingsTabComponent.ngfactory.js:1220)
    at Object.updateDirectives (C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:19901)
    at checkAndUpdateView (C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:19554)
    at callViewAction (C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:19795)
    at execEmbeddedViewsAction (C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:19758)
    at checkAndUpdateView (C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:19555)
    at callViewAction (C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:19795)
    at execEmbeddedViewsAction (C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:19758)
    at checkAndUpdateView (C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:19555)
defaultErrorLogger @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:12355
ErrorHandler.handleError @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:12401
(anonymous) @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:14638
ZoneDelegate.invoke @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\zone.js\dist\zone.js:388
Zone.run @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\zone.js\dist\zone.js:138
NgZone.runOutsideAngular @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:13864
ApplicationRef.tick @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:14638
(anonymous) @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:14522
ZoneDelegate.invoke @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\zone.js\dist\zone.js:388
onInvoke @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:13905
ZoneDelegate.invoke @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\zone.js\dist\zone.js:387
Zone.run @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\zone.js\dist\zone.js:138
NgZone.run @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:13819
next @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:14522
schedulerFn @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:9950
SafeSubscriber.__tryOrUnsub @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:209
SafeSubscriber.next @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:147
Subscriber._next @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:90
Subscriber.next @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:67
Subject.next @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\rxjs\internal\Subject.js:60
EventEmitter.emit @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:9934
checkStable @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:13874
onLeave @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:13941
onInvokeTask @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:13899
ZoneDelegate.invokeTask @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\zone.js\dist\zone.js:420
Zone.runTask @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\zone.js\dist\zone.js:188
ZoneTask.invokeTask @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\zone.js\dist\zone.js:496
invokeTask @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\zone.js\dist\zone.js:1540
globalZoneAwareCallback @ C:\Users\cternes\AppData\Local\terminus\app-1.0.0-alpha62\resources\app.asar\node_modules\zone.js\dist\zone.js:1566`

**Comment by Eugeny** [comment]
Can you also post your config file? https://github.com/Eugeny/terminus/wiki/Config-file

**Comment by cternes** [comment]
ssh: {}
hotkeys:
  shell: {}
  zoom-in:
    - - Ctrl-Shift-+
  copy:
    - []
    - []
    - []
terminal:
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  environment: {}
  shell: git-bash
  autoOpen: true
  rightClick: paste
  copyOnSelect: true
appearance:
  theme: Standard
  vibrancy: true
  vibrancyType: blur
  opacity: 1
  frame: thin
enableAnalytics: false
pluginBlacklist: []

**Comment by davidone** [comment]
I have more or less the same issue, if I click on 'Add...' and then I swith to another panel (Plugins/SSH/Appearance) the 'Add...' popup appears but without doing anything.

**Comment by henris42** [comment]
Yes same issue here. I deleted hotkey and cannot get it back.

Is there a way to edit hotkeys by editing some file etc? I'd like to have Alt-C/V/X copypaste, like in Mac.

**Comment by Eugeny** [comment]
Fixed - after updating, you might need to re-select your preferred shell.

**Comment by minidron** [comment]
Same issue. Profile name "WSL / Ubuntu-18.04".

DevTools - ERROR TypeError: Cannot read property '04' of undefined

Version: 1.0.106
Platform: win32 10.0.18363

![2020-04-20_14-06-33](https://user-images.githubusercontent.com/4964138/79745393-dab17600-8310-11ea-8df3-7b2b6ed3d109.png)
