### ISSUE TITLE
Bell is always audible on Windows 10 using PowerShell

### ISSUE THREAD

**Issue by petertiedemann** [Eugeny/terminus#518]
Regardless of my settings, when using PowerShell as shell i get the annoying bell. If i use cmd or git bash then the bell is gone as per the settings.

What additional information would be helpful?
-----

Version: 1.0.0-alpha.62
Platform: win32 10.0.17134
Plugins:

**Comment by petertiedemann** [comment]
Just wanted to mention that this is still an issue in 1.0.65, but i managed to work around it by stopping the windows "beep" service entirely.

**Comment by skt041959** [comment]
I'm also facing this issue. But I need the windows "beep" service to be enabled.

**Comment by skt041959** [comment]
OK, I have found the answer in #453
