### ISSUE TITLE
how to disable wrapping at the right edge

### ISSUE THREAD

**Issue by cybernetics** [Eugeny/terminus#521]
I'm using cmd (clink). output on the console is wrapping at the right edge of window. I can not find any setting that can help me change this behaviour. I do not want wrapping. I'm Ok with horizontal scrollbar to see the long text.

**Comment by Eugeny** [comment]
I'm not aware of any other terminals that do this.

**Comment by Eugeny** [comment]
Wrapping is more or less a natural behaviour since terminals always have a defined size.

**Comment by cybernetics** [comment]
I use windows 7 cmd.exe that gives me horizontal scrollbar and I doesn't wrap long lines.

**Comment by cybernetics** [comment]
not sure when the last time you use win cmd.exe

**Comment by cybernetics** [comment]
you're correct. but my point is: if it's possible with win cmd.exe to display horizontal scrollbar and not to wrap long lines at the edge. Then it should also be possible with your so called: "A terminal for a more modern age".

**Comment by Eugeny** [comment]
At this time, it's not a feature that I'm interested in implementing.

**Comment by cybernetics** [comment]
fare enough
