### ISSUE TITLE
v1.0.0-alpha.62 does not work on ubuntu 16.04

### ISSUE THREAD

**Issue by raudinm** [Eugeny/terminus#522]
I tried to install terminus in my ubuntu 16.04 but I'm not successful in the attempt, I get the same error with the .deb package and the .snap package the last version I used was v1.0.0-alpha.61 and everything worked correctly

![screenshot from 2018-11-20 14-31-50](https://user-images.githubusercontent.com/18465404/48794766-441ef680-ecd1-11e8-8ce1-d1c33a40d012.png)
![screenshot from 2018-11-20 14-04-14](https://user-images.githubusercontent.com/18465404/48793548-ad046f80-eccd-11e8-86ce-97225d477e84.png)
![screenshot from 2018-11-20 14-07-27](https://user-images.githubusercontent.com/18465404/48793549-ae359c80-eccd-11e8-9769-4179ec0b77bf.png)

**Comment by Eugeny** [comment]
Could you please retry it with the Alpha 63 (just released)? 

https://github.com/Eugeny/terminus/releases/tag/v1.0.0-alpha.63

**Comment by Eugeny** [comment]
Thanks for checking!
