### ISSUE TITLE
Long text copied with line breaks

### ISSUE THREAD

**Issue by gaui** [Eugeny/terminus#524]
When pasting long text into Terminus, there is no problem. It's correct. But when copying that long text in Terminus and pasting again, it adds line breaks and everything is executed as seperate commands.

See GIF:

![](https://i.imgur.com/U5em45x.gif)

**Comment by NixNotCastey** [comment]
Yeah, it's really annoying when you have long "single line" command string. It will be fixed?

**Comment by Eugeny** [comment]
There's unfortunately no solution to this since Windows performs line wrapping internally and hides it from the terminal (both in winpty and conpty).

**Comment by CasteyDaSilva** [comment]
In Termius and ConEmu they manage to fix that.

**Comment by itskenny0** [comment]
This problem has returned for me.

**Comment by jayunit100** [comment]
me to ?

**Comment by lawweiliang** [comment]
The solution for this is 

1. Go to setting
2. Select Terminal 
3. Uncheck "copy with formatting"

![image](https://github.com/Eugeny/tabby/assets/34936929/1bc7fcb7-f2ad-4608-b0f7-df2fb81068a7)

**Comment by Jvk1166z** [comment]
this is still a problem for me, even when 'copy with formatting' is turned off. it makes copying things like ssh keys a lot more annoying, because i have to remove the new lines from it in a text editor before i can paste it into something like proxmox's web interface.
