### ISSUE TITLE
Cursor doesn't blink

### ISSUE THREAD

**Issue by echang24** [Eugeny/terminus#527]
Not sure if anyone has seen this issue but I turned on `Blink cursor` and it definitely is not blinking

**Comment by nickjj** [comment]
It's not blinking for me either on Windows 10 Pro stable using Alpha 64 build.

I tried setting it to blinking, not blinking and back to blinking, etc..

**Comment by fanfan54** [comment]
Same, sometimes it's not blinking, sometimes it is (on Fedora 28 x64)
