### ISSUE TITLE
Symantec detects ffmpeg.dll and libegl.dll as infected

### ISSUE THREAD

**Issue by silo** [Eugeny/terminus#53]
![shot 07042017-09-06](https://user-images.githubusercontent.com/112174/27818928-33fce468-6098-11e7-997b-b8908de04daa.png)

**Comment by silo** [comment]
![shot 07042017-09-15](https://user-images.githubusercontent.com/112174/27819204-6cecc77e-6099-11e7-9f0f-ba355cbac9d3.png)

**Comment by iDaN5x** [comment]
It seems that those DLLs are bundled with Electron:
https://github.com/electron/electron/blob/master/docs/tutorial/windows-store-guide.md

Meaning this is most likely a false positive, as Electron is maintained by GitHub.

**Comment by silo** [comment]
That's weird. I use other electron bundled apps like franz(meetfranz), hyper, visual studio code(i think), without any warnings. But let's hope i am the only one with this issue :)

**Comment by Eugeny** [comment]
WS.Reputation is a weird Symantic heuristic system. Just upload the files to https://www.virustotal.com/ to be sure.
