### ISSUE TITLE
Latest version doesn't load for me on Windows 10

### ISSUE THREAD

**Issue by QWp6t** [Eugeny/terminus#530]
OS: Windows 10
Windows Version: 1803 (Build 17134.407)
Terminus: 1.0.1

Terminus begins to load and shows the initial loading screen. Then it abruptly goes blank without any error prompts and it remains blank indefinitely. I've let it sit for about 10 minutes just to see if maybe it was just slowly doing something, but it never does anything after the initial blank screen, and I have to manually close it from the task bar.

It's worth mentioning I also tried pressing `F12` / `ctrl`+`shift`+`i` to open Developer Tools, but nothing happens.

Let me know if there is any other information I can provide to help diagnose this issue. Or if nobody else has this problem, then feel free to close this issue and I can rollback to a previous version.

![Screen recording of me opening Terminus](https://user-images.githubusercontent.com/30584261/49250443-b085ae00-f3d3-11e8-8d8e-62a10c3b9885.gif)
(Note: On first glance it might look like Terminus is crashing, but it doesn't crash. The gif is just looping. And the number in the bottom right is an overlay by NVidia that shows up during HWA to tell me the FPS; it's dumb but I didn't immediately see how to disable it. lol)

**Comment by michaeldtaylor** [comment]
Happens on Windows 7 too.

**Comment by shacal** [comment]
OS: Windows 10
Windows Version: 1803 (Build 17134.441)
Terminus: 1.0.1

Same output

**Comment by srend42** [comment]
OS: Windows 10
Windows version: 1809 (build 17763.134)
Terminus: 1.0.1

Running Terminus from command line gives
```
←[32minfo←[39m: Window ID: 1
which: no screen in (
```
... lists contents PATH ...
`)`

**Comment by Eugeny** [comment]
Could you please try this build? https://ci.appveyor.com/project/Eugeny/terminus/build/artifacts

**Comment by QWp6t** [comment]
@Eugeny I just tested that build, and I'm still experiencing the same issue.

Are there any debugging options or flags I can set on my end to help figure out what's going on? Or do you already have an idea of what might be happening under the hood? If you want to direct me to the part of the code where the issue is, I can try to fix it myself and report back any findings.

In the meantime, I'll try to get a build environment set up so I can compile it myself and run some tests.

**Comment by shacal** [comment]
> Could you please try this build? https://ci.appveyor.com/project/Eugeny/terminus/build/artifacts

No change

**Comment by pbering** [comment]
same problem, but `terminus-1.0.1-17-gdbadef1-portable.exe` works!

**Comment by QWp6t** [comment]
@Eugeny the latest build works for me too, so I'll close this for now. Thanks for the fix!
