### ISSUE TITLE
Installer icon uses generic application icon

### ISSUE THREAD

**Issue by patHyatt** [Eugeny/terminus#531]
**Issue:**
Windows installation tray icon does not show the terminus icon and uses a generic Windows Form icon. See attached. 
![term_install](https://user-images.githubusercontent.com/296125/49260982-01b29380-f40e-11e8-964d-85fd09b97cae.PNG)

**Solution**
Unsure here. I've scanned the Windows Squirrel documents and was not able to scour up how to change the tray icon executable.

**Comment by mikemaccana** [comment]
Also since that new taskbar icon is **hot** the installer should use it too.

**Comment by Eugeny** [comment]
It seems that Squirrel doesn't support changing the window icon :(
