### ISSUE TITLE
Bug command git

### ISSUE THREAD

**Issue by rodrigofr91** [Eugeny/terminus#532]
Hi, 

For me, there is a bug when I run a git pull or push command on the ssh terminal. It is stopped and it is not possible to execute more commands, nor have ctrl + c to cancel. What can it be?

The: windows 10
Terminus version: 1.0.1

![capturar](https://user-images.githubusercontent.com/12415176/49445147-57918d80-f7b8-11e8-8276-115954af04bb.PNG)

**Comment by smcyr** [comment]
I have exactly the same problem on Windows 10 Terminus 1.0.65.

**Comment by Eugeny** [comment]
Duplicate of #496
