### ISSUE TITLE
terminus self-built doesn't start because of odd squirrel handling

### ISSUE THREAD

**Issue by Drachenkaetzchen** [Eugeny/terminus#534]
Prerequisites:
- Build from source, no errors

Symptom:
- Run `npm start`
- Observe the following message: `Angular bootstrapping error: Error: Could not call remote function 'checkForUpdates'. Check that the function signature is correct. Underlying error: Can not find Squirrel`

The electron autoupdater API unfortunately doesn't expose if Squirrel is available or not, so we need to rely on catching the error. Due to my limited TypeScript/Electron knowledge, I'm not sure if that's the best way, but I'll submit in a PR in a few minutes anyways.

**Comment by Drachenkaetzchen** [comment]
Also I noticed that there's a try/catch around `setFeedURL()`, and I'm not sure why that's there. `setFeedURL()` doesn't actually check if the URL is there.

**Comment by Eugeny** [comment]
Right-o, I totally forgot about `checkForUpdates`. `setFeedURL` fails without Squirrel as well

**Comment by Eugeny** [comment]
Fixed in 9fd69f668a48ad1d02ad338a4ac45c900234d64f
