### ISSUE TITLE
Does not open window / UI (cannot pin point an exact scenario )

### ISSUE THREAD

**Issue by VivekRagunathan** [Eugeny/terminus#538]
I am on Mac (Mojave). Unfortunately, Terminus is not bringing up the window at all. The app lauches and I can see app menu bar but no app window (with terminal). Nor anyway to launch one.

I can't figure when and why that no window situation happens. I can say with 50% confidence that it happens when the settings window is open (or the only window when closing).

I have had success earlier uninstalling and reinstalling, and i am gonna try the same later tonight. But is there a way to reset the app?

**Comment by dgiagio** [comment]
Same here, Windows 10. Terminus launches but only shows a window with a solid color. Had to kill the process manually.

**Comment by Thom-x** [comment]
I got this on W10 with the portable edition :

![bug](https://user-images.githubusercontent.com/6797195/49761349-21c43b80-fcc7-11e8-83b4-d39897fb2354.png)

And the UI looks like this : 

![screen](https://user-images.githubusercontent.com/6797195/49761430-5c2dd880-fcc7-11e8-9c84-b28a3ed9063b.png)

**Comment by Eugeny** [comment]
@Thom-x this should be fixed starting with Alpha 65
