### ISSUE TITLE
Extend the Transparency slider

### ISSUE THREAD

**Issue by mrmeszaros** [Eugeny/terminus#539]
The transparency - even when on max value (I guess it controls window opacity) - is too transparent.

This makes some color themes hardly readable (eg. `MaterialDark`) when the underlying window is bright.
<img width="209" alt="terminus-too-transparent" src="https://user-images.githubusercontent.com/15245298/49588598-71250780-f967-11e8-9d98-b75e129245de.png">
In comparison, here is a dark bg:
<img width="209" alt="terminus-too-transparent-dark-bg" src="https://user-images.githubusercontent.com/15245298/49588712-c7924600-f967-11e8-87e8-79bf53d2768a.png">

**Comment by mrmeszaros** [comment]
This works in the settings pane fine, however, somehow it applies it twice on the console windows.
It is highly visible in the 'border':
<img width="120" alt="weird-bg-transparency" src="https://user-images.githubusercontent.com/15245298/49590743-e6dfa200-f96c-11e8-9ef7-111051ac9916.png">

**Comment by Eugeny** [comment]
If you're using hterm as the frontend, it might apply to hterm's body as well. You can narrow it down to `body.vibrant`

**Comment by mrmeszaros** [comment]
Thanks!

**Comment by wtdcode** [comment]
@Eugeny So how about another slider for the background opacity?

**Comment by douglasmiranda** [comment]
I'm not able to use transparency.

My settings:

- Terminus Alpha 73
- Ubuntu 18.04.2
- Gnome 3.28.2
- Nvidia GeForce GTX 1050 Ti/PCIe/SSE2
  - Driver nvidia-driver-418 (open source)
