### ISSUE TITLE
HACKING.md setup issue

### ISSUE THREAD

**Issue by gotama** [Eugeny/terminus#54]
Hi Guys,

So following the instructions to try build this project I did -
>1. git clone https://github.com/Eugeny/terminus.git
>2. npm i ./scripts/install-deps.js

Which then resulted in an error : 

>npm i ./scripts/install-deps.js
>npm ERR! code ENOLOCAL
>npm ERR! Could not install "scripts/install-deps.js" as it is not a directory and is not a file with a >name ending in .tgz, .tar.gz or .tar

>npm ERR! A complete log of this run can be found in:
>npm ERR!     /Users/***/.npm/_logs/2017-07-04T07_03_12_674Z-debug.log

and the log out put :

>0 info it worked if it ends with ok
>1 verbose cli [ '/usr/local/bin/node',
>1 verbose cli   '/usr/local/bin/npm',
>1 verbose cli   'i',
>1 verbose cli   './scripts/install-deps.js' ]
>2 info using npm@5.0.3
>3 info using node@v8.1.3
>4 verbose npm-session 58cf237e10be56a3
>5 silly install loadCurrentTree
>6 silly install readLocalPackageData
>7 silly fetchPackageMetaData error for file:scripts/install-deps.js Could not install "scripts/install-deps.js" as it is not a directory and is not a f
ile with a name ending in .tgz, .tar.gz or .tar
>8 verbose stack Error: ENOTDIR: not a directory, open '/Users/***/Documents/Projects/terminus/scripts/install-deps.js/package.json'
>9 verbose cwd /Users/***/Documents/Projects/terminus
>10 verbose Darwin 16.6.0
>11 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "./scripts/install-deps.js"
>12 verbose node v8.1.3
>13 verbose npm  v5.0.3
>14 error code ENOLOCAL
>15 error Could not install "scripts/install-deps.js" as it is not a directory and is not a file with a name ending in .tgz, .tar.gz or .tar
>16 verbose exit [ 1, true ]

Im still googling so im not at ends here but thought id post my issue any way to streamline the setup with future devs wanting to get onto the project.

Some more info :
>npm version
>{ npm: '5.0.3',
>  ares: '1.10.1-DEV',
>  cldr: '31.0.1',
> http_parser: '2.7.0',
> icu: '59.1',
>  modules: '57',
>  node: '8.1.3',
>  openssl: '1.0.2l',
>  tz: '2017b',
> unicode: '9.0',
>  uv: '1.12.0',
>  v8: '5.8.283.41',
>  zlib: '1.2.11' }

Regards,

**Comment by iDaN5x** [comment]
You're not running the correct commands:
git clone https://github.com/Eugeny/terminus.git
```
npm i
node ./scripts/install-deps.js
node ./build-native.js
npm run build
```

Please note you need to have Gyp and windows-build-tools installed to build the electron app.

I recommend you use Yarn instead of NPM, as this is what the project actually uses.
After installing yarn, replace all occurrences of `npm` in the commands above with `yarn`

**Comment by gotama** [comment]
Ok will get hold of yarn and give that a run

Just tried npm i and threw errors

`npm i
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN prefer global npm@5.0.4 should be installed with -g

> node-sass@4.5.3 install /Users/***/Documents/Projects/terminus/node_modules/node-sass
> node scripts/install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'tough-cookie'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/***/Documents/Projects/terminus/node_modules/request/lib/cookies.js:3:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm WARN pug-loader@2.3.0 requires a peer of pug@>=2.0.0-beta3 <3 but none was installed.
npm WARN sass-loader@6.0.3 requires a peer of webpack@^2.0.0 but none was installed.
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm WARN term@ No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/***/.npm/_logs/2017-07-04T07_52_10_178Z-debug.log
`

**Comment by gotama** [comment]
Ok we can close this issue, Yarn was the way to go maybe update the HACKING.md  before closing this issue.

**Comment by Eugeny** [comment]
Updated `HACKING.md`!
