### ISSUE TITLE
Make it easier to disable the global Ctrl+Space hotkey

### ISSUE THREAD

**Issue by jhorv-bvb** [Eugeny/terminus#540]
I found [this closed issue](https://github.com/Eugeny/terminus/issues/139) and hunted everywhere in the settings for a button, finally realizing it should be listed the Config file | Defaults.  It was.  For anyone interested, you can disable this by adding the line

    toggle-window: null

under the `hotkeys:` section.

**Comment by Eugeny** [comment]
It's actually right there on the Hotkeys page. You can disable or reassign it from there.

**Comment by jhorv-bvb** [comment]
Huh!  Two things to report:

1. When I manually added the toggle-window: null line like I mention above, it did what I wanted while I was in Terminus, but the next time I closed/re-opened Terminus, it hung on the "splash screen" with the progress bar full, never fully starting.

2. There is a bug where it isn't actually visible in the Hotkeys tab.

![blankentries](https://user-images.githubusercontent.com/42846583/49610056-653b4480-f96b-11e8-870f-c22ed2a1e635.png)

But if I type "toggle" in the Hotkeys search bar, they are shown, and they are shown after that as well:

![nowshowing](https://user-images.githubusercontent.com/42846583/49610129-a895b300-f96b-11e8-8b10-ca2f0d0bca50.png)

Version info:

Version: 1.0.1
Platform: win32 10.0.17763
Plugins:

**Comment by Eugeny** [comment]
What are all these empty lines in the table? Could you please post your complete config file?

**Comment by jhorv-bvb** [comment]
I assume the empty lines are valid settings that aren't displaying properly.  Config attached.

[config.yaml.txt](https://github.com/Eugeny/terminus/files/2657532/config.yaml.txt)

**Comment by jhorv-bvb** [comment]
I haven't seen this bug - empty lines in the Hotkeys table - in the past month of using Terminus.

**Comment by Eugeny** [comment]
Thanks - let me know if you ever see it again and I'll reopen this.

**Comment by h4sohail** [comment]
Encountering this again on clean install of Windows 11.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs
