### ISSUE TITLE
Can't copy text with tmux (but there's no hotkey conflict)

### ISSUE THREAD

**Issue by nickjj** [Eugeny/terminus#543]
I'm using Terminus Alpha 64 along with tmux 2.9 and the latest stable Windows 10 Pro release with WSL.

Since Terminus doesn't support splitting windows, I've gone back to using tmux.

To copy text with tmux you would typically press `LEADER + [`, following by pressing space, selecting your text with the arrow keys and hitting enter to copy it.

But with Terminus, when you press space, it doesn't let you enter select mode. Instead, it jumps you to the bottom of the tmux window.

This is a really big problem because it makes it impossible to copy text with tmux, unless you're only copying a few lines of text that happens to fit in 1 screen (in which case you can use the mouse).

I've scanned through the list of hotkeys in the Terminus settings and nothing is bound directly to space. I've also rebound the tmux related selection keybinds and it still doesn't work, so I don't think it's a hotkey conflict.

Also as a side topic, mouse mode is also is broken with tmux. None of the events are being passed through, so selecting with the mouse (instead of using space + enter) is also not possible.

**Comment by Eugeny** [comment]
Scroll-on-input can now be disabled with the hterm frontend. On xterm, it's blocked by https://github.com/xtermjs/xterm.js/issues/1824

Mouse support is a known problem on Windows, tracked in https://github.com/Eugeny/terminus/issues/290 and blocked by https://github.com/Microsoft/node-pty/issues/216
