### ISSUE TITLE
Clink ALT based shortcut keys don't seem to work

### ISSUE THREAD

**Issue by keithn** [Eugeny/terminus#546]
Version: 1.0.1
Platform: win32 10.0.17763
Plugins: 

Just installed terminus for the first time, opened a shell, saw it was using Clink so tried ALt-H  and other ALT based shortcuts, but none of them seem to work,  other Ctrl oriented commands do seem to wrok

**Comment by Eugeny** [comment]
You can switch the Alt/Meta key behaviour in the preferences. It's handled by the OS by default instead of being forwarded to the shell.
