### ISSUE TITLE
Blur is gone

### ISSUE THREAD

**Issue by hummal** [Eugeny/terminus#556]
![image](https://user-images.githubusercontent.com/633711/49864473-d9aa3380-fe02-11e8-8fe9-be9cedae5647.png)

With activated blur options the window has no blur anymore. Since switching from 1.0.63 to 1.0.65. Also Fluent doesn't trigger any blurred background anymore. 

Windows 10 x64

**Comment by aharpervc** [comment]
I am also seeing this, same setup. I believe it was working okay v64 as well.

**Comment by christofjans** [comment]
I'm also seeing this: no more blur. Also Windows 10 x64.

**Comment by spencerwooo** [comment]
Same here, tried the `exe` one downloaded straight from Terminus' release page and the `nupkg` one scoop installed. Both didn't trigger vibrancy effect.

**Comment by fanfan54** [comment]
No blur too on Fedora 28 x64
