### ISSUE TITLE
Cannot bring window into view - Windows 10

### ISSUE THREAD

**Issue by dsbert** [Eugeny/terminus#561]
When I launch Terminus, I see the application start but the window does not come into view. I can use ctrl + space, and see the application hiding / showing in the taskbar. I can also see the initial start up screen in the taskbar peak.

My first thought is that this could be due to the window being off screen. I typically switch between a multi monitor dock and my laptop monitor when away from my desk. However, when this happens, the simple fix is to either shift + right click the application in task bar and select move, or use the cascade windows option to rearrange all windows. With terminus, neither of these options are working. Cascade windows does not cause terminus to appear, and the shift + right click menu does not exist (this appears to be an electron issue https://github.com/electron/electron/issues/12134).

Is there any other way to force the Terminus window position to reset?

**Comment by jcifang** [comment]
I have met this problem this morning ,I changed one option which I don't remember.then the window of this app is disappear ,I still can see it in the time line ,my os is windows10 1803.

**Comment by dsbert** [comment]
After doing another cold boot and plugging my laptop back into the docking station, Terminus came up on my second monitor.

**Comment by jcifang** [comment]
well,i do not have any  second monitor,still want to know how to reset it .but I cannot find the config file. #

**Comment by jcifang** [comment]
yeah，i have tried to plugging my laptop into another screen .It do come up.

**Comment by mbinette** [comment]
If on Windows, under AppData\Roaming\Terminus is a Windows.json file. Simply delete it and restart Terminus. Then under Settings, make sure you don't dock the window to any side. I also edited the dock setting in the config.yaml file but don't think that actually mattered.

**Comment by 1212gmartinez** [comment]
Having the same issue after a completely fresh install with no external monitors plugged in. Editing the config file solved the problem.
