### ISSUE TITLE
No scroll bar in the latest version

### ISSUE THREAD

**Issue by BenoitPoulet** [Eugeny/terminus#562]
Hello,

The scroll bar in the terminal is not present in the latest version

Version: 1.0.65
Platform: win32 10.0.17134
Plugins: none

**Comment by Eugeny** [comment]
For the `hterm` frontend, scrollbar is provided by this plugin: https://github.com/kbjr/terminus-scrollbar

**Comment by BenoitPoulet** [comment]
Ok thanks.
Perhaps it must be installed by default with hterm, because the scrollbar is a need.

**Comment by EliabHdez** [comment]
How I can hidden or disable the scrollbar in terminus? I dont like it to look
