### ISSUE TITLE
Shell list is empty. Bourne shell is the only one that works.

### ISSUE THREAD

**Issue by jaraddowning** [Eugeny/terminus#564]
Opening a terminal puts me in the Bourne shell and I can't change into any other shell. Also, any command not in /bin returns 'command not found'.

    sh-3.2$ chsh -s /usr/local/bin/zsh
    sh: chsh: command not found

    sh-3.2$ /usr/bin/chsh -s /usr/local/bin/bash
    Changing shell for jarad.
    Password for jarad: 
    sh-3.2$ echo $0
    sh
    sh-3.2$ 

List of shells in Settings > Shell is empty.
See https://gist.github.com/jaraddowning/bfcd90065a22facbb92db3489daeabae for log

terminus 1.0.65
MacOS 10.14.1
node 11.4.0

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by jaraddowning** [comment]
See the gist linked in my OP.

**Comment by Eugeny** [comment]
Is the `dscl` command really not available on your Mac?

**Comment by jaraddowning** [comment]
It is:

    helium:~ jarad$ dscl
    Entering interactive mode... (type "help" for commands)
    > quit
    Goodbye
    helium:~ jarad$ which dscl
    /usr/bin/dscl

This looks like it is due to the path issue I noticed above.

**Comment by jaraddowning** [comment]
I rebooted my machine and it is working now. Sorry for the bother. Not very used to needing to restart for things to work. :(

**Comment by Eugeny** [comment]
Weird - I've added the full path to dscl just in case.
