### ISSUE TITLE
[Minor Feature Request] Selection style is ambiguous, not sure which one is selected.

### ISSUE THREAD

**Issue by VivekRagunathan** [Eugeny/terminus#565]
![image](https://user-images.githubusercontent.com/292160/49961051-84375a80-fec6-11e8-9953-5a5e06195e7a.png)

Difficult to know without squinting if tabs _On the top_ or _At the bottom_ is selected. Same is the case with other selectable options. Would be nice if the selected is highlighted and contrasted with those that not selected.

**Comment by Eugeny** [comment]
Active buttons now have distinct hover styles.
