### ISSUE TITLE
Use two theme plug-ins at the same time

### ISSUE THREAD

**Issue by RGaius** [Eugeny/terminus#566]
Version: 1.0.65
Platform: win32 6.1.7601
Plugins: altair, theme-hype

**Comment by RGaius** [comment]
After using these two plugins, the application will not be able to use

**Comment by RGaius** [comment]
> What is the question here?

After using these two plugins, the application will not be able to use

**Comment by Eugeny** [comment]
I still can't understand what the problem is. Are you getting errors/crashes when both plugins are installed?

**Comment by RGaius** [comment]
> I still can't understand what the problem is. Are you getting errors/crashes when both plugins are installed?

No,nothing happened
When both plugins are installed and restart,the following interface appears
![image](https://user-images.githubusercontent.com/19511826/50152174-e694be80-02fd-11e9-8810-b32d08a48cdc.png)

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by RGaius** [comment]
I can not open the DevTools, use F12/Ctrl-Shift-I not response.
but,remove the Terminus config files and reinstall，the application is ok

**Comment by RGaius** [comment]
> Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

I can not open the DevTools, use F12/Ctrl-Shift-I not response.
but,remove the Terminus config files and reinstall，the application is ok

**Comment by Eugeny** [comment]
So that was config related then. Do you still have the old config file?

**Comment by RGaius** [comment]
No.
But,maybe i can repeat it

**Comment by RGaius** [comment]
> So that was config related then. Do you still have the old config file?

No.
But,maybe i can repeat it
