### ISSUE TITLE
[Feature] Able to display .PNG/.GIF/etc files in terminal

### ISSUE THREAD

**Issue by Kri-Ol** [Eugeny/terminus#569]
I believe Electron can do this and this feature is used widely in VS Code and its plugins. Would be nice doing something along the line

$ cat aaa.pmg
...image shown here...
$

**Comment by ChungZH** [comment]
I also need this feature, too.

**Comment by Kri-Ol** [comment]
One approach might be similar to what iTerm2 is doing: https://www.iterm2.com/documentation-images.html

**Comment by zhanxw** [comment]
Tabby looks great. It will be nice to support this feature. 
Will this information be helpful: https://chromium.googlesource.com/apps/libapps/+/HEAD/nassh/doc/FAQ.md#How-do-I-view-images Hterm.js supports images now.
