### ISSUE TITLE
Theme not displaying

### ISSUE THREAD

**Issue by gotama** [Eugeny/terminus#57]
Hi guys,

so theme im expecting to see :

![screen shot 2017-07-04 at 10 22 15 am](https://user-images.githubusercontent.com/9005135/27821730-a0a391ce-60a3-11e7-9fcb-3aa2c9b20d60.png)

And what im currently seeing :

![screen shot 2017-07-04 at 10 22 21 am](https://user-images.githubusercontent.com/9005135/27821748-abe7ea30-60a3-11e7-89bf-3202b369be90.png)

this is happening for all themes

Info
>im using /bin/bash
>on the latest alpha-15 build
>mac os sierra

**Comment by Tazeg** [comment]
Same issue on Ubuntu 16.04. I tried to change the Shell from "Default" to "/bin/bash" in settings, but nothing change. I have no colors. Moreover, i can confirm the ~/.bashrc is not read, because my alias are unknown.

**Comment by Eugeny** [comment]
Can you confirm that your shell is colorful in other terminals? Otherwise, try: `ls --color`

**Comment by gotama** [comment]
Directories on my standard mac terminal is not colored for ls :
![screen shot 2017-07-04 at 12 49 12 pm](https://user-images.githubusercontent.com/9005135/27827414-727ca7ae-60b7-11e7-894a-704e41686ffd.png)

Interesting though, when i ssh into my hosted server the directory colors show up :
![screen shot 2017-07-04 at 12 50 06 pm](https://user-images.githubusercontent.com/9005135/27827433-89fd2958-60b7-11e7-94d6-dced7ac057e1.png)

I wonder if its because of zsh

**Comment by Eugeny** [comment]
On macOS, it's `ls -G`.
Colorfulness is a choice of the program running inside the terminal, not the terminal itself. Many Bash and ZSH configs alias `ls` to `ls --color` on Linux, that's why you see the colors when on a remote server.  Try https://github.com/robbyrussell/oh-my-zsh for an easy way to spice up your shell.
