### ISSUE TITLE
[Feature Requests]: 'Open terminus here.'

### ISSUE THREAD

**Issue by ChungZH** [Eugeny/terminus#570]
Right-click the mouse in the folder. There is an option like this: 'Open terminus here'. Like `Hyper` and `Fluent Termimal`.

![Like this](https://i.loli.net/2018/12/16/5c1605b6e9df2.png)

*English is not my mother tongue. Please forgive some mistakes. Thank you.* 😘

**Comment by Saafo** [comment]
So here comes the problem: feature of "Open terminus here" had came true, now I have problem deleting it..Neither do I find any options in the settings nor I can delete it using my right context menu managers... Do you have any methods deleting it?
![image](https://user-images.githubusercontent.com/46736350/53012580-50f0e900-347e-11e9-8d51-101aab9bbcc5.png)
(image:my right context menu managers...)

**Comment by Qiming-Liu** [comment]
> So here comes the problem: feature of "Open terminus here" had came true, now I have problem deleting it..Neither do I find any options in the settings nor I can delete it using my right context menu managers... Do you have any methods deleting it? ![image](https://user-images.githubusercontent.com/46736350/53012580-50f0e900-347e-11e9-8d51-101aab9bbcc5.png) (image:my right context menu managers...)

Huorong works fine with it.

**Comment by Eugeny** [comment]
@Saafo you can disable it in Settings -> Application -> Shell integration (same place where you enable it).
