### ISSUE TITLE
App becomes low resolution when idling for about 15 seconds

### ISSUE THREAD

**Issue by naorunaoru** [Eugeny/terminus#573]
Hi. 

There's a problem with rendering on hi-dpi devices in Windows (at least, don't have similarly high dpi OS X/Linux device on hand right now).

![image](https://user-images.githubusercontent.com/3761149/50057929-8594ab80-0182-11e9-9a23-6dc6f57888dc.png)

This is what I see with 250% scaling. 

On devices with 100% scaling the app seems to work fine.

Is it Electron's bug or something that can be fixed in Terminus directly?

**Comment by fanfan54** [comment]
Hi @naorunaoru
The only thing I know is that, since I enabled some setting in the Intel Graphics control panel on my Windows PC, I have this exact same issue on many Electron apps (such as Discord), only when I'm idling for 1 minute or less. 
So it might not be because of Terminus

**Comment by naorunaoru** [comment]
@fanfan54 Thanks for your input, we might be onto something here, but:

> Intel Graphics
Mine has Nvidia graphics card.

> I have this exact same issue on many Electron apps (such as Discord)
No issues whatsoever on other Electron apps. Hyper (another terminal emulator) works fine. Discord too. 

Do you have two monitors with different DPI by any chance?

**Comment by fanfan54** [comment]
@naorunaoru No, it's on an old laptop with 100% DPI, 1600x900, without any screen attached to it
So it might be another issue

**Comment by Eugeny** [comment]
Could be https://github.com/electron/electron/issues/13646
