### ISSUE TITLE
Terminal misalignment on display scaling/DPI change

### ISSUE THREAD

**Issue by d1vanloon** [Eugeny/terminus#576]
Version: 1.0.1
Platform: win32 10.0.17134
Plugins: clickable-links

## Overview

If Terminus is running when a display change occurs, such as a remote desktop session from a device with a different display size or DPI, any open terminals may be vertically misaligned. The active prompt, if at the last line of the terminal, could be below or significantly above the lower border of the Terminus window.

Here's an example going from a high-DPI display back to a normal display. Note the gap between the bottom of the terminal and the bottom of the Terminus window:

![image](https://user-images.githubusercontent.com/9598082/50166487-cc7ec000-02ac-11e9-9df8-55581a66b9f8.png)

Normal for comparison:

![image](https://user-images.githubusercontent.com/9598082/50166194-28951480-02ac-11e9-9e75-a73b5cf4a1d9.png)

Here's an example going from normal display to high-DPI display. Note that the last line of the terminal is mostly below the border of the Terminus window:

![image](https://user-images.githubusercontent.com/9598082/50166326-73af2780-02ac-11e9-9e50-771828c2dc88.png)

Opening a new tab or restarting Terminus fixes the alignment issue.

## Steps to reproduce:

1. Open Terminus
2. Press Enter to fill the terminal with prompts
3. Change the scale of the display on which Terminus is positioned

![image](https://user-images.githubusercontent.com/9598082/50166748-46af4480-02ad-11e9-9f1d-f2bbc22a6f28.png)

4. Note the change in vertical alignment (up if scaling decreased, down if scaling increased)

**Comment by Eugeny** [comment]
Does slightly (+/- just a few pixels) resizing the window also fix the alignment?

**Comment by d1vanloon** [comment]
No, a resize doesn't seem to affect the alignment.

![terminus_resize](https://user-images.githubusercontent.com/9598082/50168310-b7a42b80-02b0-11e9-9388-6d02a64f89f5.gif)

**Comment by d1vanloon** [comment]
Thanks for following up on this.

I tested with the latest nightly build. The behavior remains as previously described with one new change. If, after the DPI change, I move the window, the proper alignment is restored after a brief delay.

Could you hook into the `screen.display-metrics-changed` event to react to DPI changes without needing window movement?

**Comment by d1vanloon** [comment]
@Eugeny The scenario in which I initially noted this issue involves a logical screen DPI change.

I use the application on my work PC with standard (78 PPI) DPI displays. I often use Remote Desktop to connect to my work PC from my home PC, which has high-DPI displays (e.g. 260 PPI). This results in an apparent display DPI change to running applications, which need to re-scale. The application window never moves, but the display DPI changed.

While the fix you've applied would allow me to force the application to re-configure by moving the window, some situations, e.g. when the window is maximized, make this workaround not apparent to the user.

**Comment by renierdbruyn** [comment]
> 
> 
> @Eugeny The scenario in which I initially noted this issue involves a logical screen DPI change.
> 
> I use the application on my work PC with standard (78 PPI) DPI displays. I often use Remote Desktop to connect to my work PC from my home PC, which has high-DPI displays (e.g. 260 PPI). This results in an apparent display DPI change to running applications, which need to re-scale. The application window never moves, but the display DPI changed.
> 
> While the fix you've applied would allow me to force the application to re-configure by moving the window, some situations, e.g. when the window is maximized, make this workaround not apparent to the user.

Is there a potential fix for this behavior?
