### ISSUE TITLE
Duplicate Tab

### ISSUE THREAD

**Issue by rockerest** [Eugeny/terminus#577]
This is a feature request.

One thing I miss literally every time I use Terminus is the ability to duplicate a tab.

Perhaps I'm just missing how to do it, but I can't see any way to open a new tab _at the same location_ as another tab. For now, I try to estimate how many tabs I'll need in one location and then use the quick command plugin to send the same `cd` command to all of them. This is obviously untenable long term.

Were #49 created, it would be great to have a "Split Up/Down/Left/Right" that simultaneously duplicates the current working directory into the new pane.

Without splitting, however, it would still be nice to be able to create a new tab at the same location as an existing tab.

**Comment by Eugeny** [comment]
@rockerest, which platform you're on? Opening a new tab on macOS and Linux should inherit current tab's CWD.

**Comment by rockerest** [comment]
Windows (10).

I have my shell working directory set, but the same behavior happens with it "unset" (defaulting to the home directory).

![cwd](https://user-images.githubusercontent.com/277023/50186065-f220bf00-02d6-11e9-8d49-8e80822a330a.gif)

**Comment by Eugeny** [comment]
Unfortunately keeping the CWD is still unavailable on Windows, since I wasn't able to find a surefire way to detect the running shell's CWD without requiring administrator rights. As soon as we figure this out, this will work, along with the tab recovery on Windows.
