### ISSUE TITLE
vim hotkeys dosen't work for wsl

### ISSUE THREAD

**Issue by 500646** [Eugeny/terminus#578]
I'm use terminus 1.0.65,use VIM with WSL.the ctrl+a don't work
i want use the ctrl-a to current number +1, but nothing happen.
here is my config:
hotkeys:
  shell: {}
  paste:
    - - Ctrl-Shift-V
    - - Shift-Insert
  home:
    - - Home
ssh: {}
terminal:
  colorScheme:
    name: ayu
    foreground: '#e6e1cf'
    background: '#0f1419'
    cursor: '#f29718'
    colors:
      - '#000000'
      - '#ff3333'
      - '#b8cc52'
      - '#e7c547'
      - '#36a3d9'
      - '#f07178'
      - '#95e6cb'
      - '#ffffff'
      - '#323232'
      - '#ff6565'
      - '#eafe84'
      - '#fff779'
      - '#68d5ff'
      - '#ffa3aa'
      - '#c7fffd'
      - '#ffffff'
  frontend: hterm
  background: theme
  autoOpen: true
  environment: {}
  shell: clink
  rightClick: paste
  copyOnSelect: false
  fontSize: 15
  ligatures: true
appearance:
  theme: Standard
  frame: thin
  vibrancy: false
  opacity: 0.96
  dock: 'off'
enableAnalytics: false

**Comment by klauern** [comment]
Same.  Since vim is such an integral part of my workflow, I'm just not able to use this tool.  I haven't tried it yet, but if this breaks Vim, I imagine TMux/Screen and other window managers might have a similar problem.
