### ISSUE TITLE
"Nightly" Windows Squirrel Install is broken

### ISSUE THREAD

**Issue by drub0y** [Eugeny/terminus#579]
The "nightly" build of the squirrel has been broken for around a week or more now. Specifically if you download and run it you'll get:

![image](https://user-images.githubusercontent.com/284152/50305737-9f671480-0448-11e9-9cea-3da819076b79.png)

Also, the binary size is only 209kb vs the portable binary which is 65MB. So something must have happened to the packaging of the squirrel build? 🤔

**Comment by Stanzilla** [comment]
CI did not produce artifacts for that commit

**Comment by Eugeny** [comment]
Now fixed
