### ISSUE TITLE
Hardcoded path in new ssh connection

### ISSUE THREAD

**Issue by jontwo** [Eugeny/terminus#580]
Version: 1.0.65
Platform: win32 10.0.17134
Plugins: none

I've set up an ssh connection, but when I click on it, I get a popup that says "Could not connect: Error: spawn C:\util\pagent.exe ENOENT".

I don't have a c:\util folder, hence the ENOENT. Is the path hardcoded somewhere?

**Comment by Eugeny** [comment]
Duplicate of #328
