### ISSUE TITLE
Reconnect SSH tabs

### ISSUE THREAD

**Issue by ecpMasterHunterGTX** [Eugeny/terminus#583]
I really like your application but I would like to report an improvement that I think could be very important.
Could you implement the reconnection of tabs of both ssh and local terminals? (as in chrome the anchored pages for example)
It can be very useful when you have always fixed connections and others that you use periodically that are not so important.

**Comment by Eugeny** [comment]
The latest release should remember opened terminal tabs (not the SSH connections though)

**Comment by ecpMasterHunterGTX** [comment]
> The latest release should remember opened terminal tabs (not the SSH connections though)

It could be a good idea to remember everything you have open, so when you open it again or when you turn off the PC you have it all again
