### ISSUE TITLE
How to install plugins?

### ISSUE THREAD

**Issue by Cifer-Y** [Eugeny/terminus#584]
Sorry, in my settings, I cannot find how to install plugins
I think I need help
macOS High Sierra Version 10.13.6
Terminus Version 1.0.66 

<img width="697" alt="18-12-24_23-41-58" src="https://user-images.githubusercontent.com/4470516/50402944-902ff000-07d5-11e9-85b6-bb09cb398cb0.png">

**Comment by HadesJK** [comment]
i have same question

**Comment by Eugeny** [comment]
Installing plugins requires NPM being available on system $PATH. You can install the official NodeJS distribution.

**Comment by Cifer-Y** [comment]
@Eugeny Yes, I have already installed npm, but in UI representation, I can not find how to install new plugins, such as clickable-links, but the plugins panel in the settings, just show the installed plugins.

I'm trying to find a plugins market or something like that, but I failed.

So I'm very confused....

**Comment by Eugeny** [comment]
Could you please check if you see any errors in the devtools console?

https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by Cifer-Y** [comment]
@Eugeny Ah, I saw an error, cause I'm using the fish shell, not bash

<img width="975" alt="18-12-29_20-56-37" src="https://user-images.githubusercontent.com/4470516/50538580-8e3aa800-0bac-11e9-8617-daae41e7a037.png">

**Comment by robot110011** [comment]
same with zsh. have npm last version but go this
http://snpy.in/dqmgg0

**Comment by Eugeny** [comment]
@robot110011 is `npm` immediately executable from the stock terminal? What is the location of the npm binary?

**Comment by robot110011** [comment]
@Eugeny what do you mean stock terminal? I can install any package using npm directly from terminal.

**Comment by Eugeny** [comment]
That answers the question, thanks. What about the npm installation path?

**Comment by robot110011** [comment]
npm@6.5.0 /usr/local/lib/node_modules/npm

**Comment by Eugeny** [comment]
But where is the actual npm launch script? What does `where npm` output?

**Comment by robot110011** [comment]
/usr/local/bin/npm

**Comment by digeomel** [comment]
Even assuming npm is correctly installed, how are we then supposed to install plugins?

**Comment by Eugeny** [comment]
@digeomel when npm is found, the Plugin pages includes a list of available plugins

**Comment by digeomel** [comment]
What I see is the following:

![image](https://user-images.githubusercontent.com/3295889/51692847-0bb3d580-1ffe-11e9-8e73-20a0a7a2103c.png)

Is this what's expected? I don't see any available plugins, only installed.
