### ISSUE TITLE
[Windows] Closing a window closes the app

### ISSUE THREAD

**Issue by thochra** [Eugeny/terminus#585]
Hello, 

I'm using version 1.0.66 of Terminus.
I noticed when we have multiple windows opened and we choose to close one from the close button all the app actually closes. (I'm using the thin window decoration btw, not the native one)

In order to fix this I did comment the app lock acquirement from the `index.ts` app file.
```
// if (!app.requestSingleInstanceLock()) {
//     app.quit()
//     process.exit(0)
// }
```

This solves my use case: virtual desktops with different opened terminals with multiple tabs.
Might also solve the #509 use case unless the lock is necessary for some reason...

Unfortunately I was unable to build the app for Windows (it stay stuck at loading screen) so I have to run it from `yarn prod`.

Do you think removing the lock could be a good option?

**Comment by Eugeny** [comment]
This is not a good idea actually, since it wastes memory by running multiple copies of the app and prevents controlling it from CLI. I should just fix the close button handler instead.
