### ISSUE TITLE
With ConPTY support enabled, Home/End keys don't work

### ISSUE THREAD

**Issue by Kri-Ol** [Eugeny/terminus#587]
Terminus 1.0.67, Win10 1809, x64, hterm.

With ConPTY support enables, Home/End didn't work. Disable ConPTY and they are working again

**Comment by JanRK** [comment]
Disabling ConPTY solves it for me also. (Settings - Shell - Use ConPTY).

**Comment by glen-84** [comment]
ConPTY also seems to break `Ctrl+L`.

(Windows Build 17763)

**Comment by simmessa** [comment]
Yep, also for me, ConPTY definitely breaks the Home and End keys, unfortunately I happen to use them a lot, so I'm back to not using ConPTY :(

**Comment by Eugeny** [comment]
Workaround: remove the `Beginning of the line`/`End of the line` mappings from Settings > Hotkeys

**Comment by simmessa** [comment]
I can confirm the fix suggested by @Eugeny worked for me! Many thanks! Great job as usual.
