### ISSUE TITLE
Suggestion - option to increase line/scroll cache

### ISSUE THREAD

**Issue by audioeptesicus** [Eugeny/terminus#589]
I'm using Terminus on Windows and would like to have more than 1000 lines for the scroll cache. Is there anyway to increase this to say, 5000 lines? If not, I'd love for the option to edit as it's a feature in many other terminal emulators.

**Comment by Eugeny** [comment]
Are you using the hterm or xterm frontend?

**Comment by audioeptesicus** [comment]
> Are you using the hterm or xterm frontend?

Looks like I'm using xterm. Should I be using hterm?

**Comment by Eugeny** [comment]
It must be xterm specific then - good to know

**Comment by audioeptesicus** [comment]
> It must be xterm specific then - good to know

I did switch to hterm, and the scroll buffer is much much longer... I'll stick with hterm for now unless I experience issues.
