### ISSUE TITLE
New tab fails every second times

### ISSUE THREAD

**Issue by princemaple** [Eugeny/terminus#591]
Version: 1.0.67
Platform: win32 10.0.17763
Plugins: clickable-links, scrollbar

![screenshot](https://user-images.githubusercontent.com/1329716/50577770-85372880-0e83-11e9-8464-a7b15662da20.gif)

**Comment by Nidnogg** [comment]
Seeing this as well on Win10 17134.472. It started a while after I configured my initial settings.

**Comment by Eugeny** [comment]
Duplicate of #586
