### ISSUE TITLE
With ConPTY enabled exiting a cmd clink terminal crashes whole application

### ISSUE THREAD

**Issue by mdsitton** [Eugeny/terminus#594]
Its not constantly reproducible, but i've been getting lots of cases where opening a bunch of different terminal windows then exiting a cmd clink shell causes the entire application to crash and turn into a black box and i have to manually kill the application and all of the background orphaned wsl and conhost processes.

**Comment by mdsitton** [comment]
I've just had it happen with a wsl window as well

**Comment by joshporter1** [comment]
Having the same issue as well. When typing "exit" with more than one tab open the entire app locks up and I have to manually kill it. Didn't even notice the orphaned WSL processes until you just mentioned it - have about 5-6 of everything I was running!

**Comment by norweeg** [comment]
I also have this problem.  Very frustrating because typing exit to close a terminal is a tough habit to break, but I lose work every time I trigger this bug

**Comment by Eugeny** [comment]
Could you please retest this against the latest nightly, which includes updated conpty integration in node-pty?

**Comment by norweeg** [comment]
@Eugeny for me, if I have only WSL tabs, or only CMD (clink) tabs open and type exit it's fine again, however, if I have some combination of WSL and CMD (clink) tabs open and type exit in either of them, the application locks up and gets blacked-out.

**Comment by joshporter1** [comment]
In addition to this happening with WSL, I had the same thing happen on MacOS using SSH - typed "exit" in the SSH session and the app locked up.

**Comment by norweeg** [comment]
so I just tried various combinations of shells.  the bug only happens if you have a wsl tab as your first tab, and a cmd(clink) tab as your second tab, then type exit in the wsl tab.  If your first tab is anything but wsl, the tab closes and cmd(clink) moves from second to first tab, but if it's wsl, the application locks.  if you have wsl and cmd(clink) in any other position tab, the bug does not happen when you exit either, whether they're right or left, regardless of what other shells are open.

**Comment by superm1** [comment]
It's happened to me with two WSL tabs and caused the crash by typing exit in my "second" WSL tab.

Version: 1.0.69
Platform: win32 10.0.17763

I'll try nightly as well.

**Comment by superm1** [comment]
With tonight's nightly (1.0.69-c16-g6f99e6c) it does behave "better".  The whole window froze, but did recover.

**Comment by mdsitton** [comment]
For me with the latest v1.0.69 I still just get a black screen forever with crashing upon exiting things. This time i was ssh'd out to another machine exited from that shell and it crashed. So it's not likely wsl specific

**Comment by Eugeny** [comment]
Apparently ConPTY is still not stable enough in Windows builds before 18309, so I'll be adding a corresponding warning to the settings UI.
