### ISSUE TITLE
Ctrl+c close the tab

### ISSUE THREAD

**Issue by BenoitValdes** [Eugeny/terminus#596]
Hello,

First of all I love the terminal, it's simple and perfect. The only thing that irritate me is when I want to cancel an operation or a program and that close my tab,

I don't know if it's something on my side or not: I am on Windows 10 and I use Git-Bash as shelf and everything else is set to default.

I hope that someone could help me because I can't use the software like that and I really want to.

Thank you for you work

Version: 1.0.68
Platform: win32 10.0.17134
Plugins: none

**Comment by Eugeny** [comment]
> First of all I love the terminal, it's simple and perfect. The only thing that irritate me is when I want to cancel an operation or a program and that close my tab,

I think something might have gone missing here :)

If Ctrl-C kills the shell for you, please check if disabling ConPTY (Settings -> Shell) fixes it

**Comment by BenoitValdes** [comment]
![image](https://user-images.githubusercontent.com/12208428/50643263-d4598800-0f6d-11e9-8744-9c4c0789c01e.png)
I don't find a way to disable ConPTY (this is a screenshot of the shell settings)

**Comment by Eugeny** [comment]
Could you please post the exact steps that lead to Ctrl-C closing the tab?

**Comment by BenoitValdes** [comment]
Hi,
I launch a software, I want to kill it co I hit CTRL + C and the tab is closed. If I do that in any other shell than git-bah the issue doesn't happen. If I open git bash itself (not through Terminus) the issue doesn't happen.

**Comment by aihuasxy** [comment]
this is a problem of git-for-windows:
https://github.com/cbucher/console/issues/340

update to latest 2.20.x will fix the issure (https://gitforwindows.org/)

**Comment by Eugeny** [comment]
Thanks! Direct issue link: https://github.com/git-for-windows/git/pull/205
