### ISSUE TITLE
Ability to pass parameter when adding SSH connections

### ISSUE THREAD

**Issue by vnikitov** [Eugeny/terminus#600]
It would be good to add a field for passing parameters to ssh command when we adding SSH connections.
As an example, I use PKCS11 and Yubikey in order to log in, but even if I have PKCSProvider in my ssh config it won't work with terminus and will ask me for a password instead pin for the key. Will be possible to implement this feature?

**Comment by Eugeny** [comment]
This is unfortunately not possible since Terminus isn't using OpenSSH for its SSH connections. 
You can create your own `ssh` commandlines however and store them as Profiles
