### ISSUE TITLE
Wide Unicode characters are displayed wrong

### ISSUE THREAD

**Issue by wookayin** [Eugeny/terminus#602]
Maybe related to #149.

When I type non-English unicode characters (Korean, Chinese, Japanse, etc.) that are as wide as 2 English letters, they show up at weird locations.

![image](https://user-images.githubusercontent.com/1009873/50729217-0c92cf00-1104-11e9-88c5-7a5a0c414516.png)

Version: 1.0.68 Alpha
OS: macOS mojave 10.14

**Comment by Eugeny** [comment]
Could you please compare behaviour with hterm and xterm frontends?

**Comment by yzlnew** [comment]
Confirm this on Windows 1809.
![snipaste_2019-02-11_14-00-52](https://user-images.githubusercontent.com/4904877/52547884-683c3080-2e05-11e9-9624-1b6c1ade4673.png)

**Comment by wookayin** [comment]
As of 1.0.73, it has fixed and now works as expected.

![image](https://user-images.githubusercontent.com/1009873/56052489-8b109580-5d1f-11e9-867c-0b614a48002e.png)

**Comment by IgnusG** [comment]
This can be closed then
