### ISSUE TITLE
support ssh privatre key with passphrase

### ISSUE THREAD

**Issue by wanghaiwei** [Eugeny/terminus#605]
Version: 1.0.67-c10-gccc34ae
Platform: win32 10.0.17763
Plugins: clickable-links, quick-cmds, shell-selector, theme-windows10

**Comment by Eugeny** [comment]
In which format is your key?

**Comment by wanghaiwei** [comment]
my private key was created by ssh-keygen
format rsa

**Comment by bes-internal** [comment]
ssh keyfile without passphase dont work too

**Comment by bes-internal** [comment]
After delete config.yaml and window.json all keyfiles (new openssh format, with and witjout passphase, ed25519) started working. Magick

**Comment by enif-lee** [comment]
@Eugeny  maybe this is problem

![image](https://user-images.githubusercontent.com/9916002/51993551-6a8fb800-24f2-11e9-9f17-5d24ce42efcd.png)

https://github.com/mscdex/ssh2-streams/issues/100

**Comment by enif-lee** [comment]
maybe this is problem

![image](https://user-images.githubusercontent.com/9916002/51993842-fc97c080-24f2-11e9-89e7-688544e67b54.png)

https://github.com/mscdex/ssh2-streams/issues/100

As above link, the new open ssh private key format(`-----BEGIN OPENSSH PRIVATE KEY-----`) didn't supported before `ssh2-streams@0.3.0`.

The temporary solution is create private key as older format.

`ssh-keygen -m PEM -t rsa -b 4096 -C "enif.lee@gmail.com"`
