### ISSUE TITLE
Installer graphic is odd

### ISSUE THREAD

**Issue by mikemaccana** [Eugeny/terminus#606]
Currently the installer uses a generic animated image of a text editor - it doesn't really look like terminus:

![image](https://user-images.githubusercontent.com/172594/50764565-053a0580-126b-11e9-8929-b1e755e0d3be.png)

Let's replace this with the pretty new icon, and the word ''installing....'. I can make a graphic (source in SVG) if you tell me where to put it!

![image](https://user-images.githubusercontent.com/172594/50764635-3fa3a280-126b-11e9-8e98-e444dcd61506.png)

**Comment by Eugeny** [comment]
That was the stock Squirrel installer animation - replaced it with just the icon. Normally it should just take a few seconds to install - so hopefully complex graphics are not required :)
