### ISSUE TITLE
ConPTY: process not exist  after I close tab or terminus

### ISSUE THREAD

**Issue by chrislearn** [Eugeny/terminus#609]
I use windows 10,
When I close tab or terminus, many process is not exist, they still running in background.
![image](https://user-images.githubusercontent.com/5874864/50885918-01081680-142a-11e9-8336-3cd1f0387dab.png)
![image](https://user-images.githubusercontent.com/5874864/50885946-14b37d00-142a-11e9-8b0a-b9ed95c9828c.png)

**Comment by Munkkeli** [comment]
I have the same issue.
Windows 10 version 1809 build 17763.253

**Comment by Eugeny** [comment]
Please retest with the latest nightly.

**Comment by Munkkeli** [comment]
Still leaves them running in the background with latest nightly (1.0.68-c24-g78f8f40)

**Comment by Schlaefer** [comment]
I had the same issue in 1.0.68 but it seems to be fixed in 1.0.69.

Windows 17763.288

**Comment by Munkkeli** [comment]
1.0.69 did not seem to fix it for me, still leaves both CMD and Bash instances running after closing Terminus or individual terminals.

**Comment by Schlaefer** [comment]
Checked on1.0.69 again: Closing a tab does end the process now, but closing the app still leaves it behind.

**Comment by Eugeny** [comment]
Apparently ConPTY is still not stable enough in Windows builds before 18309, so I'll be adding a corresponding warning to the settings UI.
