### ISSUE TITLE
A light text on a light background

### ISSUE THREAD

**Issue by unnamedguy** [Eugeny/terminus#610]
I have this issue (while using nano) in almost all color schemes

Version: 1.0.68
Platform: win32 10.0.17763
Plugins: none
![image](https://user-images.githubusercontent.com/26875843/50893131-3bb18500-1411-11e9-8c7b-8fc97e8408af.png)

**Comment by Eugeny** [comment]
xterm solution coming up in https://github.com/xtermjs/xterm.js/issues/1898

**Comment by Scarsz** [comment]
So what's the temp fix for this, if any? This is a pretty big usability issue for me.
