### ISSUE TITLE
Paste outputs more than I copied

### ISSUE THREAD

**Issue by Bnjmn83** [Eugeny/terminus#615]
Same issue as #153.

Not sure why it was closed.  Happens with ctrl+shift+c/v as well as when using right mouse button.

The problem can be seen when copying from a formatted output like from _ls_.  

> Mode                LastWriteTime         Length Name
> ----                -------------         ------ ----
> d-----       31.10.2018     11:33                certs

When selecting the word _certs_ the pasted output is:

> 10.2018     11:33                certs

Anyway, it works properly when copying text from a _cat_ output.

Please fix this since it is super annoying.

v1.0.68

**Comment by Eugeny** [comment]
Could you please compare behaviour with xterm and hterm frontends (Settings -> Appearance)?

**Comment by Bnjmn83** [comment]
holy shit this solved it! you're the man!

**Comment by Eugeny** [comment]
Thanks for checking!
