### ISSUE TITLE
Crash at launch and freeze the system. 

### ISSUE THREAD

**Issue by LifeIsStrange** [Eugeny/terminus#616]
Hi!
I've installed on Fedora + XFCE terminus (the 68, with rpm).

At first it was great, I was on the launch page of terminus, I clicked on settings.
I played with some, and it worked live, but when I changed the default window position to left, it appeared twice (the current position) + a black rect at top left of the screen. (that is the background without the UX).
Then, each time I launch terminus it only show the background without the UX and make my OS freeze to the point I must restart the computer.
I've uninstalled it many times, but it seems to keep remembering the custom buggy setting.
I even removed the whole /opt/terminus folder but nothing seems to make him reset to his default.
Now when I launch it, it take all the screen space (exept the OS bar), the startup animation run (but freeze)then only the background, then the OS freeze.

**Comment by Eugeny** [comment]
You could try to reset the app by removing the `~/.config/terminus` directory.

**Comment by stpham-net** [comment]
How can I remove config of terminus on Windows 10? I try change setting name "Dock..." to "Right" and now can't see terminus any more
