### ISSUE TITLE
Ctrl + Key shortcuts not working

### ISSUE THREAD

**Issue by webmin88** [Eugeny/terminus#617]
Version: 1.0.68
Platform: win32 10.0.17134
Plugins: altair, clickable-links, quick-cmds, scrollbar, shell-selector, theme-gruvbox, theme-hype, theme-windows10, title-control

Key combos like Ctrl + Backspace to delete the previous word or Ctrl + Left Arrow to go back to the previous word are not working and instead print things like ^H. So far I have only replicated this issue when PowerShell is my active shell.

Thanks

**Comment by Eugeny** [comment]
Duplicate of #507
