### ISSUE TITLE
Appearance - Font size

### ISSUE THREAD

**Issue by TheAndrey** [Eugeny/terminus#618]
Version: 1.0.69
Platform: win32 6.1.7601
Plugins: none

I use a fractional font size value. It's working just fine for me. But after restart, the dot is replaced with a comma making the value incorrect.
![default](https://user-images.githubusercontent.com/6772452/51443589-aad18800-1cf3-11e9-87ea-a499a8265e19.png)

It wouldn't hurt to limit the maximum font size or set `overflow` for the preview area yet.
![default](https://user-images.githubusercontent.com/6772452/51443618-1e739500-1cf4-11e9-9eff-0bdaafaca9ed.png)

**Comment by TheAndrey** [comment]
@Eugeny what about fractional numbers?

**Comment by Eugeny** [comment]
They work for me, but I suspect your locale might be affecting this - so I forced it to English.
