### ISSUE TITLE
Cannot Toggle terminal window by Ctrl+Space 

### ISSUE THREAD

**Issue by zhuoshuai** [Eugeny/terminus#619]
> Two windows[1st, 2st] are opened  

 when I close the 2st, the shortcut `Ctrl+Space` for `Toggle the terminal window` is  Invalid.
> OS: win10_64_Ver1809

**Comment by sampaiodiego** [comment]
any way to bring it back? 😬

**Comment by NJAldwin** [comment]
I'm having a similar issue,.  From #2422:

> Machine:
> Windows 10 version 2004 19041.207
> WSL 2 Ubuntu
> Terminus 1.0.106
> 
> ---
> 
> Steps to reproduce:
> 
> 1. Open Terminus.
> 2. Press the `toggle-window` keybind (default `Ctrl+Space`) to hide the window.
> 3. Note that the window has completely disappeared, including the task bar icon.
> 4. Open a new instance of Terminus.
> 5. Press `toggle-window`.  This hides the _new_ instance.
> 6. Press `toggle-window` to show the window.  Only the _new_ instance shows up.
> 7. Close (X) the terminus window.
> 8. Press `toggle-window` again.
> 9. Notice that terminus does _not_ reopen
> 10. Open task manager.  Note that there is a terminus instance running in the background that cannot be accessed.  It must be closed with End Task.
> 
> ---
> 
> What is expected:
> 
> Any of the following:
> - `toggle-window` shows/hides _all_ terminus windows
> - trying to open a new terminus window when one is hidden via `toggle-window` just reopens the hidden window
> - there is a status bar icon or something in order to be able to get a hidden terminus window back without ending its task
> - (this is not preferred, but it would be better than current behavior) `toggle-window` only operates on the _newest_ terminus window, except once that one is closed, it works on the next newest, and so on.
> 
> ---
> 
> I've lost several windows with assorted tabs this way (mostly by accidentally pressing ctrl-space and not realizing it until later).  Hoping one of the proposed expectations is acceptable!
