### ISSUE TITLE
Default padding/margin cuts tmux panel on the bottom

### ISSUE THREAD

**Issue by pwittchen** [Eugeny/terminus#62]
Hi,

Thanks for the nice project (I forgot to thank in my previous issue :)).

I have the following problem:

I'm using Zsh & Tmux on Ubuntu 16.04 LTS.
My Tmux panel on the bottom of the terminal is cut by default padding/margin.

It looks as follows:

![tmux-cut](https://user-images.githubusercontent.com/695319/27839654-38d2f968-60f3-11e7-9367-46e3490537e4.png)

You can also see a comparison with default terminal application.

My settings are as follows:

![settings](https://user-images.githubusercontent.com/695319/27839659-4bd9a99e-60f3-11e7-8fcf-ef96a51bf1b5.png)

My `.tmux.conf` file can be found at https://github.com/pwittchen/dotfiles/blob/master/.tmux.conf

Regards,
Piotr

**Comment by pwittchen** [comment]
Right now, I don't see Tmux bottom panel at all. I can see it in Tilix, so it's Terminux issue.

**Comment by Chr1s-T** [comment]
> Right now, I don't see Tmux bottom panel at all. I can see it in Tilix, so it's Terminus issue.

As you can see, when I use tmux, there are some useless paddings remaining in the terminus, how to fix this problem? I want to use it without any margin.
![TIM截图20190705124153](https://user-images.githubusercontent.com/23159278/60698560-80caf580-9f22-11e9-9463-2ce37762c50d.png)
