### ISSUE TITLE
Trying saved password. All configured authentication methods failed

### ISSUE THREAD

**Issue by sherlockwhite** [Eugeny/terminus#622]
This ssh connect needs vpn.If i closed the connect,the saved password is not effective.But when i use the xshell,the saved password is effective,what happened？

**Comment by gt50** [comment]
I am experiencing the same issue on Windows 10, version 1.0.73. The first time I connect, I am prompted for a password. If I try connecting a second time I get the following:

Trying saved password...
All configured authentication methods failed

**Comment by jocarren** [comment]
Same here. 

Version: 1.0.73
Platform: win32 10.0.17134
Plugins: none

**Comment by Eugeny** [comment]
Please test with the latest release, thanks.

**Comment by 50l3r** [comment]
I have the same problem. I try with multiple ppk's
