### ISSUE TITLE
Can't issue bash commands on Cygwin

### ISSUE THREAD

**Issue by jorgesouzadxc** [Eugeny/terminus#624]
I can't issue bash commands like "ls" on cygwin. The problem is the PATH environment variable. This is my PATH variable: 

/cygdrive/d/Downloads/Chrome/WINDOWS.X64_180000_db_home/bin:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS:/cygdrive/c/Program Files/Intel/Intel(R) Management En
gine Components/iCLS:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Windows/System32/OpenSSH:/c
ygdrive/c/Program Files/Java/jdk1.8.0_181/bin:/cygdrive/c/Program Files/Java/jre1.8.0_181/bin:/cygdrive/c/Program Files/Java/jre1.8.0_181/lib:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Manage
ment Engine Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Pr
ogram Files/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files/MATLAB/R2017b/runtime/win64:/cygdrive/c/Program Files/MATLAB/R2017b/bin:/cygdrive/c/Program Files/MySQL/MySQL
 Utilities 1.6:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/cygwin:/cygdrive/c/cygwin/bin:/cygdrive/c/bin:/cygdrive/c/Users/Jorge/scoop/shims:/cygdrive/c/Users/Jorge/AppData/Local/Microsoft/Wind
owsApps:/cygdrive/c/Program Files/Microsoft VS Code/bin

The commands works properly if I use the "inject environment variable" option of the Settings menu to add PATH to "/bin", but it overwrites my existing PATH variable. Is there a way to solve this issue? I think that appending "/bin" to PATH without overwriting it could solve this issue.

Version: 1.0.69
Platform: win32 10.0.17134
Plugins: none

**Comment by tiguchi** [comment]
Related problem: .bash_profile / .profile / .bashrc are not picked up, which could be used to correct the PATH variable.

The home directory is incorrect. We end up in the Windows user home directory `C:\Users\<username>` instead of Cygwin's `/home/<username>`, where bash profile files would be stored.

**Comment by Peter-Optiway** [comment]
I'm having the same issues, not even windows commands work like `dir`.

But i managed to solve it by adding a `environment` variable.
`path`=`%path%;C:\cygwin64\bin`.

**Comment by LouWii** [comment]
Commenting because this is still an issue. Installed alpha 81 yesterday and I had the exact same issue.
