### ISSUE TITLE
Minor taskbar icon regression in 1.0.69

### ISSUE THREAD

**Issue by mikemaccana** [Eugeny/terminus#627]
The taskbar icon in 1.0.69 now has a jagged edge - 10..68 had it right, so probably just an easy revert.

The new installer image is jagged too:

![image](https://user-images.githubusercontent.com/172594/51750925-6d7e4900-20ab-11e9-808f-a9e165455fdf.png)

**Comment by mikemaccana** [comment]
PS @Eugeny just wanted to say how slick Terminus is looking/feeling lately. I spend my whole day in Terminus and Chrome and you're so far ahead of any other terminal app on Windows it's insane!

**Comment by Eugeny** [comment]
Thanks @mikemaccana! I haven't changed the icon since .68 though
