### ISSUE TITLE
ctrl + mouse up/down not working

### ISSUE THREAD

**Issue by lubinson** [Eugeny/terminus#628]
I was trying to use ctrl + mouse up/down to scaling the font size, but not working. Ctrl + [-] and Ctrl + [=] are working, but not so cool. I was trying to modify the hot key by using mouse event, but can't input mouse event in the hot key box. There has one issue https://github.com/Eugeny/terminus/issues/184
similar, but looks not work for me. 

I am using windows 10. 

Many Thanks.

**Comment by lubinson** [comment]
Oh, I just found the xterm front end supports this. I will close this issue.

**Comment by jaques-sam** [comment]
Why closing this? This needs to be fixed. I was trying to give a live demo and people couldn't read the font 😟 

For me it's also not working at all on Windows 10.
Also CTRL+scrolling doesn't work, I tried hterm as well.

**Comment by deragon** [comment]
@lubinson, can you please share with us your solution?
