### ISSUE TITLE
Add x11 forwarding

### ISSUE THREAD

**Issue by lubinson** [Eugeny/terminus#630]
As title, Thanks.

**Comment by Eugeny** [comment]
It doesn't

**Comment by marcinbojko** [comment]
Do you have any plans to add it in the future?

**Comment by Eugeny** [comment]
Why not :)

**Comment by lubinson** [comment]
@Eugeny cool, thanks.

**Comment by fleischern** [comment]
Is this fixed?  Any plans to fix it in the near future?

**Comment by ShawnRahlTR** [comment]
This would be a great enhancement, and it's quite standard functionality for modern terminals.
