### ISSUE TITLE
Possible regression about closing tabs/sessions.

### ISSUE THREAD

**Issue by marcinbojko** [Eugeny/terminus#631]
System: Linux Mint 19.1 Cinnamon x64
Terminus: 1.0.69
Shell: /bin/bash, no persistence.
Frontend: hterm.

Behaviour:
Having few tabs open, when I'll do 'reboot' or 'shutdown -h now' on mentioned hosts, in some cases Terminus freezes completly. No tabs, no acces, no dev console, the only succesful option is to kill a process.
Expected behaviour:
Not to hang on session/tab closing.

**Comment by marcinbojko** [comment]
Ping

**Comment by marcinbojko** [comment]
ping

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by marcinbojko** [comment]
Will do

**Comment by marcinbojko** [comment]
Version 1.0.88, when doing 'shutdown' on remote host, all tabs are gone, devtools:

![image](https://user-images.githubusercontent.com/4726723/62942325-54837e00-bdd8-11e9-92a9-b0a676342819.png)

**Comment by ihenry42** [comment]
This happens to me frequently when closing tabs, usually by exiting the shell with "exit"

System: Windows 10 Pro Version 10.0.18980 Build 18980
Terminus: 1.0.91
Shell: CMD (clink) and ssh sessions
Use ConPTY: Yes or No (does not matter)

I get a out of memory crash and then I have to terminate the process manually.

[log.txt](https://github.com/Eugeny/terminus/files/3610900/log.txt)
![Screenshot](https://user-images.githubusercontent.com/9661582/64878265-f977bd80-d607-11e9-96ae-4230b29fac1a.png)

**Comment by Eugeny** [comment]
@ihenry42 various memory related issues are possible with hterm - it's deprecated in favor of xterm

**Comment by lgpaulsen** [comment]
That seems to work for me as well, multiple hangs when exiting a shell (especially ssh connections)
Change the config file
From
```
terminal:
  frontend: hterm
```
To
```
terminal:
  frontend: xterm
```
