### ISSUE TITLE
Titlebar not set for WSL shell

### ISSUE THREAD

**Issue by Sureiya** [Eugeny/terminus#634]
Is there any way to get the WSL shell's title bar set correctly?

![terminus_2019-01-29_14-58-51](https://user-images.githubusercontent.com/241411/51939105-ab95a880-23dc-11e9-8a8e-6f99e839b5e5.png)

For comparison, from top left to bottom right,

-  Windows cmd
-  WSL terminal
-  Git Bash
-  wsltty window (expected behaviour)

**Comment by Sureiya** [comment]
I've done some further investigating and I now think this is an upstream bug. It only seems to affect non-bash command processors (I'm using zsh).

**Comment by CoskunSunali** [comment]
@Sureiya Have you found any workarounds?
