### ISSUE TITLE
Coloured characters are disappearing from the terminal

### ISSUE THREAD

**Issue by NatoBoram** [Eugeny/terminus#635]
In the following GIF, I used the command `neofetch`, which displays a few coloured characters, then I moved the terminal around a bit. The coloured characters disappeared.

![s7a5va1jox](https://user-images.githubusercontent.com/10495562/51956195-c5eb7880-2414-11e9-9a91-3504e6e22bfe.gif)

**Comment by Eugeny** [comment]
Could you please compare the behaviour with hterm and xterm frontends?

**Comment by NatoBoram** [comment]
Oh, that's interesting. The bug only appears on `hterm`!

**Comment by Eugeny** [comment]
xterm will be the default frontend in the next release, so I'll be closing this for now
