### ISSUE TITLE
[Feature Request] Password field in SSH Connection Manager

### ISSUE THREAD

**Issue by x1nas** [Eugeny/terminus#637]
Please add password field in SSH Connection Manager

**Comment by lubinson** [comment]
+1

**Comment by serafeimgr** [comment]
+1 this is the only feature missing for me in order to do the switch.

**Comment by lazb** [comment]
For me it's not saving passwords, but with this option maybe it would work.

**Comment by coffmant** [comment]
+1

**Comment by 1212gmartinez** [comment]
+1
