### ISSUE TITLE
tabsLocation

### ISSUE THREAD

**Issue by haitaohua** [Eugeny/terminus#641]
Version: 1.0.69
Platform: darwin 18.2.0
Plugins: none

appearance tabsLocation: left,  will make window crash

**Comment by Eugeny** [comment]
Only allowed values are `top` and `bottom` (as in the UI settings). Feel free to add a ticket for sideways tabs though.

**Comment by ImMrMa** [comment]
left tab is very useful for me!!!  like this!
![微信截图_20190902205041](https://user-images.githubusercontent.com/24520617/64115876-5af78b00-cdc3-11e9-9ef7-b82c97b3b67c.png)
