### ISSUE TITLE
Choosing WSL-Ubuntu 18.04 for my shell tabs close immediately

### ISSUE THREAD

**Issue by superm1** [Eugeny/terminus#642]
I'm currently on Windows 1803.  Terminus 1.0.69

When I try to set my shell as WSL- Ubuntu 18.04 my tab closes immediately after opening.  I managed to screenshot the error below:

![image](https://user-images.githubusercontent.com/494526/52135029-89816d80-260a-11e9-8b87-6a882eded1d6.png)

**Comment by superm1** [comment]
It seems to be related to having legacy WSL installed previously.  After removing legacy WSL it seems to work as expected.  So feel free to close this if you think it should be.

```
Z:\>lxrun /remove
Warning: lxrun.exe is only used to configure the legacy Windows Subsystem for Linux distribution.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

Usage:
    /install - Installs the subsystem
        Optional arguments:
            /y - Do not prompt user to accept or create a subsystem user
    /uninstall - Uninstalls the subsystem
        Optional arguments:
            /full - Perform a full uninstall
            /y - Do not prompt user to confirm
    /setdefaultuser - Sets the default subsystem user. If the user account does not exist it will be created.
        Optional arguments:
            username - Supply the username
            /y - If username is supplied, do not prompt to create a password

Z:\>lxrun /uninstall
Warning: lxrun.exe is only used to configure the legacy Windows Subsystem for Linux distribution.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

This will uninstall Ubuntu on Windows.
This will remove the Ubuntu environment as well as any modifications and new applications with the exception of:

C:\Users\user\AppData\Local\lxss\home
C:\Users\user\AppData\Local\lxss\root

Type "y" to continue: y
Uninstalling...
```

**Comment by superm1** [comment]
It looks like it's a mistake to me trying to use `-d` to launch a particular distro.  Proper way is to launch `distro.exe`.

https://docs.microsoft.com/en-us/windows/wsl/wsl-config

**Comment by Eugeny** [comment]
`wsl.exe -d <distro>` is the default way to launch a specific distro on more recent Insider builds. Do you have multiple WSL distros installed? 

Could you please post the list of subkeys under `HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Lxss`?

**Comment by superm1** [comment]
All I have is Ubuntu 18.04 from the store.  My company's I/T setup doesn't yet allow upgrades beyond Windows 10 1803, so I can't go up to 1809 or later.

Here is everything under that key.
![image](https://user-images.githubusercontent.com/494526/52567964-1d092a00-2dd3-11e9-913f-0f57a591f5a7.png)

![image](https://user-images.githubusercontent.com/494526/52567974-26929200-2dd3-11e9-9fa7-38324f99e5fd.png)

**Comment by xXBeekeyXx** [comment]
> All I have is Ubuntu 18.04 from the store.

Does the shell work if you select **WSL/Defaul**?

**Comment by superm1** [comment]
Yes it does.

**Comment by superm1** [comment]
As a layman from the outside comparing my personal machine running 1809 to my work machine running 1803 it seems like Microsoft just added support for the `-d` argument to launch distros in 1809.

For me i'm unblocked with Terminus just using `WSL/default distro` on my work machine.
So I think it's probably a good idea from Terminus side to just only offer "WSL/default distro" when detected to be running on 1803 or less and show a little warning that choosing your shell is only available on 1809+ or something.
