### ISSUE TITLE
Copy on select doesn't work

### ISSUE THREAD

**Issue by superm1** [Eugeny/terminus#643]
Windows 10 1803
Terminus 1.0.69

I notice turning on "Copy on select" doesn't work.  I need to use my hotkey to copy text.

**Comment by therealjuanmartinez** [comment]
Same issue on Linux:
Ubuntu 18.10
Terminus 1.0.69

**Comment by RReverser** [comment]
Confirmed on a freshly installed Terminus; the issue appears to be with `xterm` backend; switching ConPTY on/off doesn't help, but switching to `hterm` does fix the issue.

**Comment by Eugeny** [comment]
So selecting text and pressing Ctrl-Shift-V right after doesnt paste the previously selected text? I'm struggling to reproduce this.

**Comment by superm1** [comment]
Hmm, now after switching to `hterm` and back to xterm it's working again in `xterm` for me too...
