### ISSUE TITLE
[Feature request] New editbox in SSH connections to force connection options and enable legacy algorithms and ciphers

### ISSUE THREAD

**Issue by sectorogo** [Eugeny/terminus#645]
I cannot connect to some of my Cisco switches. This is the error i got:

**Handshake failed: no matching key exchange algorithm**

I don't have any problems to connect to them with PuTTY or any other ssh client.

**Comment by sectorogo** [comment]
Btw i have tried with the latest stable and the latest nightly builds. The result is the same.

**Comment by sectorogo** [comment]
It happens on switches with older version of IOS. This switch is running 12.2(55)SE12 and the latest version available is SE13. This is one version before the last.
On these switches there is no configuration for SSH ciphers.

**Comment by x1nas** [comment]
Try the following command:
`ssh <user>@<host> -oKexAlgorithms=+diffie-hellman-group1-sha1`

**Comment by sectorogo** [comment]
Where to use this command?

**Comment by x1nas** [comment]
> Unable to negotiate with X.X.X.X port 22: no matching cipher found. Their offer: aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc

`ssh <user>@<host> -oKexAlgorithms=+diffie-hellman-group1-sha1 -c aes256-cbc`

**Comment by sectorogo** [comment]
This is the output from ssh -G hostname :

**ciphers** chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
**hostkeyalgorithms** ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa
-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
**hostbasedkeytypes** ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa
-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
**kexalgorithms** curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha
1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1

**Comment by x1nas** [comment]
Windows version?

**Comment by sectorogo** [comment]
> `ssh <user>@<host> -oKexAlgorithms=+diffie-hellman-group1-sha1 -c aes256-cbc`

This works great! Thank you. Is there any way to enable this globally?

Maybe it's a good thing to add custom options in ssh connection manager in Terminus to enable these legacy ciphers when needed.

**Comment by sectorogo** [comment]
I think this should be feature request to parse custom options to SSH connections for legacy algorithms and ciphers.

**Comment by Eugeny** [comment]
Terminus doesn't use OpenSSH internally, so its options would not make sense. I've added UI to select allowed ciphers though: 
![image](https://user-images.githubusercontent.com/161476/52524322-0a400980-2c9c-11e9-954c-93febcd72997.png)
