### ISSUE TITLE
terminal title

### ISSUE THREAD

**Issue by csrgxtu** [Eugeny/terminus#65]
when i open a new terminal, tab title is bash,

when i ssh login to host1, title changed to username@host1

when i exit the ssh, still username@host1

**Comment by csrgxtu** [comment]
is this a bug?

**Comment by Eugeny** [comment]
Please include OS info

**Comment by csrgxtu** [comment]
![image](https://user-images.githubusercontent.com/5053620/27901864-3b5479f4-6266-11e7-9ae6-26ba8b72f028.png)

DISTRIB_ID=Ubuntu  
DISTRIB_RELEASE=14.04  
DISTRIB_CODENAME=trusty  
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"  
NAME="Ubuntu"  
VERSION="14.04.5 LTS, Trusty Tahr"  
ID=ubuntu  
ID_LIKE=debian  
PRETTY_NAME="Ubuntu 14.04.5 LTS"  
VERSION_ID="14.04"  
HOME_URL="http://www.ubuntu.com/"  
SUPPORT_URL="http://help.ubuntu.com/"  
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by jmdf** [comment]
I'm also experiencing this on Windows 10, with Bash on Windows and Terminus 1.0.0-alpha.23.
Sometimes it doesn't even change the title when I ssh login to a host. Do you experience that as well?

**Comment by cdockter** [comment]
Was this issue resolved? is there some way for me to update the title after i create a new tab?
