### ISSUE TITLE
Adding path variables

### ISSUE THREAD

**Issue by h-hub** [Eugeny/terminus#651]
I have a question. In settings -> shell : We can add variables. Is there a feature where we can path varibales like this ? If not can it be a feature in the coming releases. Please ignore if my questions is out of scope.

![image](https://user-images.githubusercontent.com/6287819/52431637-968ae900-2b43-11e9-967f-b1aeb1c8ea79.png)

**Comment by Eugeny** [comment]
You can override `%PATH%` from this settings page, but simply adding new items to it is better done via your PowerShell profile file: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-6

**Comment by h-hub** [comment]
Thanks for the info
