### ISSUE TITLE
Terminus attempts to use ConPTY even if not supported

### ISSUE THREAD

**Issue by xXBeekeyXx** [Eugeny/terminus#653]
Version: 1.0.70
Platform: win32 10.0.17134
Plugins: none

No shell is loading when creating a new terminal.

![image](https://user-images.githubusercontent.com/45722052/52535743-5057a480-2d52-11e9-9ed9-ea765f4d78f1.png)

**Comment by source2git** [comment]
same issue here

**Comment by saulhudson** [comment]
I'm also getting the same issue since upgrading from 69 to 70. Tried using various different shells (Git bash, PS etc). Reverted back to 69 until a fix is in place.

**Comment by dietervanhoof** [comment]
It looks like the detection(?) of when to use ConPTY is wrong (I have no clue what this all means but at least I managed to fix it on my system). I added `useConPTY: false` to the terminal element in my config file.

So my config looks like:
```yml
hotkeys:
  shell: {}
ssh: {}
terminal:
  environment: {}
  useConPTY: false
```

Could you try this and let me know if that works for you?

**Comment by xXBeekeyXx** [comment]
> Could you try this and let me know if that works for you?

Thank you! Every shell works, except **WSL/Ubuntu**. But interestingly **WSL/Default Distro** does work, although I am pretty sure that i only have one WSL-distro installed on my laptop.

**Comment by saulhudson** [comment]
> Could you try this and let me know if that works for you?

Thank you, that's worked for me as well.

**Comment by dietervanhoof** [comment]
> Keep up the good work, this is easily the best terminal on Windows right now.

Sadly I'm not affiliated with this project whatsoever other than being a user ;) I'm glad I was able to help out though. This is indeed easily the best terminal around.

**Comment by niktekusho** [comment]
@dietervanhoof 's solution worked for me too.
