### ISSUE TITLE
Garbled Chinese text using cmd as shell.

### ISSUE THREAD

**Issue by yzlnew** [Eugeny/terminus#654]
Windows 1809. Using stock cmd as shell.
The font is Sarasa Term SC.
xterm and hterm both produce the same result.
![snipaste_2019-02-11_14-00-52](https://user-images.githubusercontent.com/4904877/52547884-683c3080-2e05-11e9-9624-1b6c1ade4673.png)

**Comment by yuguorui** [comment]
The same OS and the same font, no problem here.

**Comment by Eugeny** [comment]
Does enabling/disabling ConPTY affect this in any way?

**Comment by yuguorui** [comment]
> Does enabling/disabling ConPTY affect this in any way?

Not related in my PC.

**Comment by yzlnew** [comment]
@Eugeny Nope. Still showing the wrong text.

**Comment by yzlnew** [comment]
@Eugeny @yuguorui It only occurs when using cmd as admin.

**Comment by Eugeny** [comment]
@yzlnew are you using "Run as admin" from the context menu, or do you mean it only happend when the Windows user is an admin?

**Comment by yzlnew** [comment]
@Eugeny I'm using "Run as admin".

**Comment by yuguorui** [comment]
Yes, I can also reproduce this bug when I use the `New as admin` from the context menu.

**Comment by YangHanlin** [comment]
I can also reproduce this bug when I use any of the options in `New as admin`, including `CMD (Clink)`, `CMD (Stock)` and `Powershell`.

I am using Terminus on Windows 1903 (OS Version 18343.1) and my font used is `Consolas`.

**Comment by KsRyY** [comment]
I have the same problem here. 
OS: Windows 1903m Build 18362
Font: Fira Code

**Comment by KsRyY** [comment]
There is a solution. If you launch with administer outside (right-click the terminus shortcut/program and select `Run as administer`) there is no garbled Chinese font. Don't know why this work

**Comment by Eugeny** [comment]
Could you please upgrade to the latest nightly and provide a dump of your terminal state as described here? https://github.com/Eugeny/terminus/wiki/Posting-terminal-state
