### ISSUE TITLE
Extremely slow performance in Mac OS X Mojave (10.14).

### ISSUE THREAD

**Issue by jrgilman** [Eugeny/terminus#655]
Terminus Version: **1.0.7.0**
System Specs:
```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	149.0.0.0.0
```

As the title says:

1. Opening the application takes about one to two minutes for it to open at all.
2. Takes another minute to go from a gray screen.
3. Resizing, scrolling, etc. on the terminal screen is extremely laggy (but okay on the Settings page).

Let me know what other information you need from me to help out. I'm not sure where the location of the log files are...

**Comment by Eugeny** [comment]
You can open the debug console with `Alt-Cmd-I` - see if there are any messages on the Console tab, and if not, you can capture a performance trace from the Performance tab.
