### ISSUE TITLE
cwd-detection banner URL is not correct

### ISSUE THREAD

**Issue by piersandro** [Eugeny/terminus#6563]
**Describe the problem**:
In SFTP Window the `cwd-detection` banner points to a the Tabby home page not the instruction to configure cwd-detection.

**To Reproduce**:
Use SFTP connection and click on the `cwd-detection` banner. The URL is `https://tabby.sh/go/cwd-detection` but it redirect to the tabby.sh home page and not on the a documentation page to configure cwd-detection.

**Comment by SevDaisy** [comment]
`https://tabby.sh/go/cwd-detection` is expected to redirect to `https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting`.

**Comment by Eugeny** [comment]
Fixed, thanks!
