### ISSUE TITLE
Terminus uses dGPU by default

### ISSUE THREAD

**Issue by benvddriessche** [Eugeny/terminus#657]
On a Surface Book 2, which has an integrated Intel GPU and a discrete Nvidia GPU, terminus uses the dGPU by default which seems unnecessary. It is possible to manually override this but it shouldn't be the default behavior.

**Comment by Eugeny** [comment]
I've added the Chrome option to force the app onto the integrated GPU (related: https://github.com/electron/electron/issues/9842)

I won't be able to test it though as I haven't got any dual-GPU hardware, but you should be able to grab the build here shortly: https://ci.appveyor.com/project/Eugeny/terminus/build/artifacts

**Comment by artsilenkov** [comment]
> I've added the Chrome option to force the app onto the integrated GPU (related: [electron/electron#9842](https://github.com/electron/electron/issues/9842))
> 
> I won't be able to test it though as I haven't got any dual-GPU hardware, but you should be able to grab the build here shortly: https://ci.appveyor.com/project/Eugeny/terminus/build/artifacts

This build works for me, no discrete GPU triggering.

**Comment by Eugeny** [comment]
Thanks for confirming @artsilenkov

**Comment by TheCompScientist** [comment]
Hello, sorry for reopening this issue. But I am experiencing similar issue OP reported, but I think I know why it defaults to dGPU (as far as nvidia drivers go):

terminus.exe is the name of the executable for PC game Ash of Gods, and nvidia drivers think its the game, and therefore, by default, enables dGPU for it instead of integrated graphics. I had to set it to use Integrated Graphics like so:

![image](https://user-images.githubusercontent.com/9343504/75661393-1047b600-5c22-11ea-97a1-73f839f3cc31.png)

**Comment by Eugeny** [comment]
Thanks - good catch. I need to look into whether changing the binary name will cause any issues with autoupdating.

**Comment by Hariama** [comment]
I noticed on two different laptops with Intel CPU's (Kaby Lake and Haswell respectively) and Nvidia dGPU's that terminus would activate the dGPU even when it is explicitly stated in the Nvidia control panel to use the integrated graphics.

If anyone encounters this issue, I fixed it on Windows 10 (ver. 20H2) by going into the graphic settings of the OS itself, and specifically setting the graphics settings performance of terminus.exe (located in %AppData%/Local/Programs/Terminus) to power saving, as denoted in the screenshot. I hope this helps.

![power_saving_terminus](https://user-images.githubusercontent.com/18269973/98927093-628ee580-24d8-11eb-8cd2-d40df6f8231d.PNG)

**Comment by PePoDev** [comment]
> I noticed on two different laptops with Intel CPU's (Kaby Lake and Haswell respectively) and Nvidia dGPU's that terminus would activate the dGPU even when it is explicitly stated in the Nvidia control panel to use the integrated graphics.
> 
> If anyone encounters this issue, I fixed it on Windows 10 (ver. 20H2) by going into the graphic settings of the OS itself, and specifically setting the graphics settings performance of terminus.exe (located in %AppData%/Local/Programs/Terminus) to power saving, as denoted in the screenshot. I hope this helps.
> 
> ![power_saving_terminus](https://user-images.githubusercontent.com/18269973/98927093-628ee580-24d8-11eb-8cd2-d40df6f8231d.PNG)

This worked for me. Thanks.

**Comment by Eugeny** [comment]
Thanks for the tip @Hariama. I'll see if I can automatically set this on first run. 

Note to self: https://stackoverflow.com/questions/59732181/programmatically-set-graphics-performance-for-an-app

**Comment by Hariama** [comment]
@Eugeny, Thanks man, glad to help out, I use your program every day! :) I was wondering if you managed to look into issue #2122 though, since it really messes up the user-experience of Weechat.

**Comment by Eugeny** [comment]
Unfortunately not. Shortcut handling in Windows terminal system is terrible and although there's a ton of workaround in Terminus not everything is covered. I'll try to check it out next week. Also, check if toggling ConPTY mode in Settings -> Shell helps.

**Comment by lindexi** [comment]
Reference : https://github.com/dotnet/wpf/issues/9286
