### ISSUE TITLE
switching tabs not working in shells

### ISSUE THREAD

**Issue by xXBeekeyXx** [Eugeny/terminus#658]
- **CTRL-Tab** and **CTRL-SHIFT-Tab** do not work from any shell.
- **CTRL-SHIFT-Arrow keys** also doesn't work from shells.
- **Alt-Number** neither.
- **CTRL-,** does work.

- This only happens when in shell-tabs. Everything works from the settings-tab

**Comment by Eugeny** [comment]
Which platform are you on and which shells have you tried?

**Comment by xXBeekeyXx** [comment]
Version: 1.0.70
Platform: win32 10.0.17134
Plugins: none

I have tried it in WSL-Ubuntu, cmd(clink), cmd(stock), Powershell and Git-Bash

**Comment by neta79** [comment]
confirmed. Came here to report the same behavior.

Version: 1.0.71
Platform: win32 10.0.17134
Plugins: none
