### ISSUE TITLE
zsh fonts not showing up

### ISSUE THREAD

**Issue by moeinrahimi** [Eugeny/terminus#66]
thanks for this great terminal app,
in terminus powerline fonts are not working but fonts are ok in default ubuntu terminal.

**Comment by Eugeny** [comment]
Could you please include a screenshot and your config file? Powerline works for me.

**Comment by dark-reiser** [comment]
yeah, I have same problem, let me help with screenshoot, 

![screenshot from 2017-07-06 07-04-49](https://user-images.githubusercontent.com/6045921/27889870-791d0604-6219-11e7-94a7-a22aaaaa6c1b.png)

**Comment by Eugeny** [comment]
Duplicate of #31
