### ISSUE TITLE
Font not respected with xterm

### ISSUE THREAD

**Issue by Astrophizz** [Eugeny/terminus#661]
Terminus with xterm ignores my configured font, InputMonoNarrow. I'm not sure but I think Terminus is falling back to the default Consolas. Does it use a different convention for font look-up?

**Comment by Eugeny** [comment]
Seems to be working for me:
![image](https://user-images.githubusercontent.com/161476/52643283-fb946500-2edc-11e9-82fd-51c8959e8d75.png)

When downloaded from their homepage, the font has spaces in the name:

```yaml
terminal:
  font: Input Mono Narrow
```

**Comment by Astrophizz** [comment]
Adding the spaces worked. hterm seems to find the font regardless of whether there are spaces or not. I just checked and I included spaces for my font config in VS Code and hyper so I don't know why I didn't in Terminus 🤷‍♂️ Anyways, thanks!

**Comment by Eugeny** [comment]
Glad it worked. The `Font` field in the Appearance settings will also autocomplete font names for you.

**Comment by Astrophizz** [comment]
Ohhh, that must have been why I got it wrong. It autocompletes the font names without spaces. It also suggests appending font weights on the end (with a space) but Terminus doesn't recognize the font with the font weight.

**Comment by Eugeny** [comment]
Which platform are you on?

**Comment by Astrophizz** [comment]
Windows 10 (1809) x64.

**Comment by ZhangBo1191** [comment]
Hello, now I have a similar question that is Terminus cannot change to a special font but Consola. The interesting thing is that I can change to any other fonts.
Version:1.0.75  (install with scoop)
Platform: Windows 10 (Version 1903 (OS Build 18362.53)
Font: Iosevka Nerd Font Mono
Terminal: WSL (Ubuntu)
I still try to repair this problem, but I think it is better to report to you first.
