### ISSUE TITLE
Not functional After Alpha 70

### ISSUE THREAD

**Issue by shaqaruden** [Eugeny/terminus#662]
I opened a new terminal and this is all i get.

![Image of Termins](https://i.imgur.com/EPipvSq.png)

Works again when reverting to Alpha 69

**Comment by shaqaruden** [comment]
I should point out this is the windows version

**Comment by niktekusho** [comment]
I think you should take a look at #653  since there you could also find a workaround until a fix is in place.

**Comment by Eugeny** [comment]
Duplicate of #653
