### ISSUE TITLE
Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR

### ISSUE THREAD

**Issue by lazb** [Eugeny/terminus#666]
Version: 1.0.71
Platform: win32 10.0.17134
Plugins: none

After updating to 1.0.71 from 1.0.69 I got this error for the connections that I've used few minutes ago on older version.

**Comment by levysaar** [comment]
Same issue here as well.
Worked great in 1.0.69 upgraded to 1.0.71 version, and now gets the error.

Windows 7, 64bit

**Comment by kabudu** [comment]
Just experienced the same issue on 1.0.71, Windows 10 64bit

**Comment by C439** [comment]
I also experience this issue.

**Comment by C439** [comment]
@Eugeny any idea?

**Comment by mocanzaki** [comment]
Load the key to puttygen then export it as an OpenSSH key

**Comment by realIronWang** [comment]
> Load the key to puttygen then export it as an OpenSSH key

it works!!

**Comment by lazb** [comment]
I have reinstalled Windows recently and I don't have this error anymore.

For others this is how you can use Windows built in ssh agent.

- When following next steps from the link make sure that you name your key id_rsa instead of id_dsa.
https://stackoverflow.com/questions/2224066/how-to-convert-ssh-keypairs-generated-using-puttygen-windows-into-key-pairs-us/2224204#2224204

Go to services (Windows key and search for "Services")
- find OpenSSH thing (just type to search)
- and make that service to start automatically, click Apply and click Start

**Comment by ajitstark** [comment]
work as a fuc***** tnk u

**Comment by tellus-git** [comment]
Worked as a charm, exporting it as an openssh key id_rsa
Thank you so much!
