### ISSUE TITLE
WSL can't exit normally

### ISSUE THREAD

**Issue by RumRaisins** [Eugeny/terminus#668]
Version: 1.0.69
Platform: win32 10.0.17763
Plugins: none
I close terminus, But WSL can't exit.
If you use Taskmgr，you will see the commonds don't exit.

**Comment by Eugeny** [comment]
Fixed in 1.0.70

**Comment by RumRaisins** [comment]
> Fixed in 1.0.70
![noexist](https://user-images.githubusercontent.com/23291220/52842513-4959d900-313a-11e9-82e6-cff910932758.gif)

**Comment by IgnusG** [comment]
Still an issue 😞

**Comment by IgnusG** [comment]
Seems to be fixed. Didn't occur since Alpha 77
