### ISSUE TITLE
Boots up a little slowly for a terminal

### ISSUE THREAD

**Issue by naclcaleb** [Eugeny/terminus#672]
I love this app, but in general when I need a terminal it's to do some quick action.

This terminal takes quite a while to boot up, making it impractical for me to use.

Is there anything I could do to speed it up?

**Comment by Eugeny** [comment]
Not much can be done here, that's the cost of using Electron

**Comment by naclcaleb** [comment]
Okay, that's what I thought.

**Comment by Calinou** [comment]
Would it be possible to have Terminus as a tray icon as an option, so that it's loaded permanently (possibly when the user logs in)? This could result in noticeably faster startup times, at the cost of some RAM always being used whenever the user is logged in.

**Comment by Eugeny** [comment]
Yes - you can show and hide the terminal using the "Toggle terminal window" hotkey (Ctrl-Space by default) and it will minimize to tray when hidden.

**Comment by naclcaleb** [comment]
That's a good idea, thanks!
