### ISSUE TITLE
Shell integration of the Windows portable build is broken

### ISSUE THREAD

**Issue by lukedan** [Eugeny/terminus#678]
In the portable build the "Open Terminus here" shell command doesn't work as the added registry key points to the temporary folder. What's worse, there's no easy way to remove the invalid entry. I suggest that either disable this option entirely for portable builds, or correct the directory (if possible) and provide options to remove the menu items.

**Comment by eromoe** [comment]
Yes, that should be removable. I found it only work on desktop, not work in driver C DEF ...

**Comment by eromoe** [comment]
Below I what I used for msys2, it actually need 3 entries.
```
[HKEY_CLASSES_ROOT\Directory\Background\shell\msys2]
@="Open MSYS2 Here"
"Icon"="D:\\msys64\\msys2.ico"
[HKEY_CLASSES_ROOT\Directory\Background\shell\msys2\command]
@="D:\\msys64\\usr\\bin\\mintty -i /msys2.ico --dir \"%V/\" /bin/env MSYSTEM=MSYS CHERE_INVOKING=1 /usr/bin/bash -l"
[HKEY_CLASSES_ROOT\Directory\shell\msys2]
@="Open MSYS2 here"
"Icon"="D:\\msys64\\msys2.ico"
[HKEY_CLASSES_ROOT\Directory\shell\msys2\command]
@="D:\\msys64\\usr\\bin\\mintty -i /msys2.ico --dir \"%V/\" /bin/env MSYSTEM=MSYS CHERE_INVOKING=1 /usr/bin/bash -l"
```

**Comment by Eugeny** [comment]
Fixed in the latest nightly
