### ISSUE TITLE
App opening but window not visible after settings change

### ISSUE THREAD

**Issue by VivekRagunathan** [Eugeny/terminus#679]
This issue might have been reported by others although a quick search did not reveal any open. But the issue still exists. I download Terminus v0.71, head to settings to change a thing or two - switch to zsh, open new tab on start up, maybe theme etc. Minor things I suppose. Quit terminus and you will never see a window again :( but the app is launched and can be quit.

System: Mac Mojave v10.14.3

**Comment by vinicius94** [comment]
I have the same problem in Windows 8.1, but I can show the window again by changing something in Windows resolution. How to change the main monitor or monitor order.
