### ISSUE TITLE
Ubuntu - procedure to set terminus as default terminal ?

### ISSUE THREAD

**Issue by ponsfrilus** [Eugeny/terminus#68]
Hi all,
   can someone help to define a procedure to set terminus as the default terminal for Ubuntu ?

I've tried stuff like :
  * `gsettings set org.gnome.desktop.default-applications.terminal exec '/usr/local/bin/terminus'`
  * `gconftool --type string --set /desktop/gnome/applications/terminal/exec /usr/local/bin/terminus`

But the command `update-alternatives --display x-terminal-emulator` does not show terminus and I can't find a way to add it here (e.g. `sudo update-alternatives --set x-terminal-emulator /usr/local/bin/terminus` does not work).

**Comment by Eugeny** [comment]
Try: `update-alternatives --install /etc/alternatives/x-terminal-emulator x-terminal-emulator /usr/local/bin/terminus 50`

**Comment by ponsfrilus** [comment]
`update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/terminus 50` makes available terminus as a new selection for `sudo update-alternatives --config x-terminal-emulator` so:
```
~/dev » sudo update-alternatives --display x-terminal-emulator
x-terminal-emulator - manual mode
  link best version is /usr/local/bin/terminus
  link currently points to /usr/local/bin/terminus
  link x-terminal-emulator is /usr/bin/x-terminal-emulator
  slave x-terminal-emulator.1.gz is /usr/share/man/man1/x-terminal-emulator.1.gz
```

Thanks a lot @Eugeny !
