### ISSUE TITLE
Cursor misalignment with WSL and Oh-My-Zsh

### ISSUE THREAD

**Issue by youssefazrak** [Eugeny/terminus#681]
Hi,

When using WSL and Oh-My-Zsh (and the powerlevel9k) the cursor is misaligned which makes it tough for correcting commands. Also when you start going into many subfolders the misalignment is getting bigger and bigger (pushing the right clock to be "cut")
Better than words here is a screenshot (cursor is in the middle of the 'L' and it's current position is end of the line)
![terminus](https://user-images.githubusercontent.com/30932864/53083296-ecc23980-34fe-11e9-8c5e-8805a7044d38.PNG)

**Comment by ZenithMeteor** [comment]
I updated to the latest version(Alpha 71) and have solved this problem.

**Comment by youssefazrak** [comment]
@ZenithMeteor Working fine now, cheers!
