### ISSUE TITLE
Need ability to remove Shell integration?

### ISSUE THREAD

**Issue by lucaseverett** [Eugeny/terminus#682]
This is regarding the setting added in #362.

Once the registry is modified, there is no option in Settings to remove the integration, and upon uninstall the integration is also not removed.

**Comment by BennyAlex** [comment]
@Eugeny still present

**Comment by dev-masih** [comment]
I can confirm with the latest update it's still happening in windows

**Comment by xaragen** [comment]
Why is this closed. This is still a problem.

**Comment by setebe** [comment]
Still a problem

**Comment by kanfo** [comment]
Still present.

**Comment by crNewton** [comment]
Problem is still present. 
(you can't turn this off when you uninstall tabby, and the context menu 'open with tabby' is still present)
