### ISSUE TITLE
Disable Ctrl-Space hotkey by default

### ISSUE THREAD

**Issue by JeroMiya** [Eugeny/terminus#683]
The Ctrl-Space hotkey is supposed to toggle the terminal from any app. Problem is, that's also a hotkey for autocomplete in some editors. I didn't know why Terminus was gaining focus whenever I did it and so I had to reluctantly uninstall Terminus thinking it was a bug.

Later I found it's just a hotkey assignment in the preferences and I could disable it, but it might be a good idea to either disable this hotkey by default or ask on install or something like that, so new users (like me) don't think it's a bug.

Related to but not the same as: https://github.com/Eugeny/terminus/issues/540
I'm suggesting a change of default settings, 540 is suggesting easier way to change settings.

**Comment by nuzar** [comment]
Please remove this hotkey.

**Comment by Hammster** [comment]
Indeed, this hotkey should be changed. Or the user should be prompted with the option to deactivate it when happens the first time. To name a editor that is widely used which has difficulties due to ctrl+space is VScode.

**Comment by TorbenJ** [comment]
Issue still exists, couldn't find any option to disable this. Everytime I activate intellisense in Visual Studio, Terminus pops up which is really annoying.

**Comment by tehbeard** [comment]
Took a while to figure out why this was happening, and then longer to fix.

> **Edit:** So in setting up on my work computer I did see there is an option on the first run welcome screen for this. 
> My bad for missing it, I rushed thru to try out the SSH and profiles to see if it cut mustard as a replacement for putty (spoiler: it does, I really like how it can handle spinning up another terminal on the same ssh connection).
> That said I still hold that it being buried in with the other keybinds with no indication it's global is still an issue.
> I've tidied up what was an comment written in anger.

Please consider making it clear in the keybinds section that **toggle-window is global**, perhaps push it to the top of the keybinds so it can be easily found.

Nothing currently indicates it's a global keybind (beyond the first run welcome screen) and it's buried deep in the keybinds.

<img width="595" height="249" alt="Image" src="https://github.com/user-attachments/assets/b89821bd-d021-4cb0-9fd8-ca5ba0cfe9a9" />

Are there any other keybinds global that I need to worry about?
