### ISSUE TITLE
Bring blur effect in terminus alpha

### ISSUE THREAD

**Issue by jithinlal** [Eugeny/terminus#684]
Can you bring blur effect as shown in the introductory image in terminus alpha

**Comment by Eugeny** [comment]
It's available from settings - application on Windows and macOS

**Comment by jithinlal** [comment]
Is it not available in linux? If so why?

**Comment by Eugeny** [comment]
It's the native effect provided by Windows and macOS window managers (fluent blur and vibrancy, respectively).

**Comment by yashank09** [comment]
Hello to the wonderful people creating this awesome terminus! Will blur be supported on Linux or any specific display manager in future? Can CSS not do this already? Would love to help if I can too!

**Comment by Eugeny** [comment]
Only Kwin supports this at the moment, and Terminus should already support it.

**Comment by yashank09** [comment]
Hmm, I do see the option in settings for 'acrylic' color and opacity, but interestingly it only seems to make the background color bit lighter when turned on. The opacity value seems to have no effect either. 
Changed from both the slider, and manually by setting a decimal value. Using KDE with Kwin blur scripts.  

On a side note I'm already loving this beautiful terminal and would definitely love to contribute once I can! Thanks to all devs.
