### ISSUE TITLE
Using PowerShell opens actual PowerShell prompt

### ISSUE THREAD

**Issue by FinlayDaG33k** [Eugeny/terminus#686]
Version: 1.0.69 + 1.0.71
Platform: win32 10.0.17763
Plugins: none

As the title already said, opening a new terminal when having `PowerShell` selected will result in an actual PowerShell prompt being opened.
I managed to "fix" this issue by turning off the `Use ConPTY` in the settings (even though I never enabled this myself).

[GIFV of the issue](https://i.imgur.com/MXbs6qV.gifv)

**Comment by Kri-Ol** [comment]
Interesting. Powershell is working just fine for me in Terminus (from1.068 upwards), but I'm using Core version (6.0 and 6.1)

**Comment by FinlayDaG33k** [comment]
Hm... Could you see what happens when you enable the `ConPTY` api in the settings?  
Just so we know that something with that optioncauses the issue

**Comment by FinlayDaG33k** [comment]
Updated to 1.0.77 today (been running on 1.0.71 ever since this issue) and it seems to be gone now :)
