### ISSUE TITLE
Occasional black out when closing a tab

### ISSUE THREAD

**Issue by princemaple** [Eugeny/terminus#687]
Version: 1.0.70
Platform: win32 10.0.17763
Plugins: scrollbar

sometimes when closing a tab, the whole terminus window blacks out and gets stuck. which also makes it impossible to open the console and see the logs. I'll take a screenshot next time it happens.

**Comment by princemaple** [comment]
![image](https://user-images.githubusercontent.com/1329716/53525668-6a58fb80-3b36-11e9-9514-936192eb2b49.png)
I had 2 tabs. Closed 1 by pressing ctrl+D. Terminus black out.
Task manager shows that there is indeed 1 tab left, so that's good news...
Just wondering what I can do to get the logs?

**Comment by princemaple** [comment]
still a thing

**Comment by swimmingchar** [comment]
Has this problem been solved?

**Comment by princemaple** [comment]
Not sure, but I haven't seen it happening lately. Did it happen to you?
