### ISSUE TITLE
Ubuntu - End and Home keys are not working with zsh

### ISSUE THREAD

**Issue by ponsfrilus** [Eugeny/terminus#69]
Both <kbd>End</kbd> and <kbd>Home</kbd> keys are not working as expected for me.

**Comment by Eugeny** [comment]
Please check whether it depends on the shell you're using

**Comment by ponsfrilus** [comment]
It's not, both <kbd>End</kbd> and <kbd>Home</kbd> are working with the same shell (zsh) in different terminal (i.e. terminator, roxterm or hyper).

**Comment by csrgxtu** [comment]
@ponsfrilus 
i use ubuntu 14.04 64 bit, and bash, Home and End works fine
![image](https://user-images.githubusercontent.com/5053620/27904077-109f00c8-626e-11e7-9521-6368d28b6c44.png)

**Comment by ponsfrilus** [comment]
@csrgxtu you are right, if I change my shell for bash instead of zsh there are no issues (so I've changed the title).

**Comment by Marahin** [comment]
:+1: this makes Terminus unusable for me. 
```
➜  ~ uname -a
Linux artsh 4.10.0-28-generic #32-Ubuntu SMP Fri Jun 30 05:32:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
➜  ~ echo $SHELL
/usr/bin/zsh
```

**Comment by Eugeny** [comment]
@all, can you please rename your `.zshrc` to something else and make a test with a "clean" ZSH?

**Comment by ponsfrilus** [comment]
@Eugeny just try to `mv ~/.zshrc ~/.zshrc_backup` and relaunch terminus, both <kbd>End</kbd> and <kbd>Home</kbd> keys still enter `~` instead of doing what's expected (Terminus alpha 14).

```
X1% uname -a
Linux X1 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
X1% echo $SHELL
/usr/bin/zsh
```

**Comment by ponsfrilus** [comment]
@ALL \o/ updating to 1.0.0-alpha.23-137 makes <kbd>Home</kbd> and <kbd>End</kbd> keys working as expected ! Thanks !

**Comment by Marahin** [comment]
@ponsfrilus please don't close issue like that; I just updated to the newest version (`1.0.0-alpha.24-144`), and in `vim` it works fine, *but when navigating just through the directories and stuff like that END key still prints `~`*.

**Comment by ponsfrilus** [comment]
re-opened for @Marahin

**Comment by ponsfrilus** [comment]
@Marahin can I close this issue now ? 28 days without news from you, so it's probably fixed by newer version... :)

**Comment by Marahin** [comment]
@ponsfrilus please do not yet. I didn't know I was the one expected to daily check if a newer build fixes it, in most projects when a collaborator fixes a bug he tags people who were experiencing it. 
I will try the newest version in a moment.

**Comment by Marahin** [comment]
@ponsfrilus I can confirm that this has been fixed, I don't know on which version, but I tested it again on the latest release available on GitHub (v1.0.0-alpha.29). Thank you :+1: for reminding me about this issue!

**Comment by ponsfrilus** [comment]
@marahin well I'm sure it's complicated to test terminus over all users setup ^^ but thanks for taking time to test with the latest on and I'm happy to hear that this issue can now be closed!

**Comment by mdoulaty** [comment]
I'm experiencing the same issue with 1.0.67 alpha
home and end keys are not working 
Running on Windows 10, tried with WSL (Bash on Ubuntu) and PowerShell
home and end keys are not doing anything
Currently as a workaround in Bash on Ubuntu, Ctrl+A and Ctrl+E works as expected - but those shortcuts don't work for PowerShell
