### ISSUE TITLE
Is it possible to launch elevated shell in the new tab?

### ISSUE THREAD

**Issue by YangHanlin** [Eugeny/terminus#690]
Currently, if I am working on an ordinary version of shell and at the same time I want to use an elevated shell, the only way is to close the Terminus currently being run and launch Terminus again under administrative privileges. This is because:

- An elevated shell is launched when and only when Terminus itself is launched under administrative privileges, and
- Two instances of Termnius cannot be run at the same time (when one instance is running, another instance cannot be launched).

So is it possible for Terminus to provide an option to launch an elevated shell in the new tab, regardless of whether Terminus itself is launched under administrative privileges?

Thanks!

PS: I am using Terminus on Windows.

**Comment by Eugeny** [comment]
Yes - you can launch an admin shell in a separate tab via terminal's context menu.

**Comment by YangHanlin** [comment]
Thanks for your comment. I'm sorry that I did not see it.

**Comment by ImportTaste** [comment]
@Eugeny I configured right click to paste so I didn't really know about this context menu option until I searched the repo. I tried right clicking the 'New terminal with profile' button to no avail, perhaps right clicking that should offer elevated versions of the profiles?

**Comment by Eugeny** [comment]
I've just added a 'duplicate as administrator' tab context menu item - should be up in the next nightly build.

**Comment by ImportTaste** [comment]
Thanks! 🎉
