### ISSUE TITLE
Windows: Some control keys echo in elevated shell launched with "New as admin"

### ISSUE THREAD

**Issue by YangHanlin** [Eugeny/terminus#691]
When an elevated shell is launched with `New as admin` in the context menu, some control keys do not work but echo some strange characters in the shell.

Steps to reproduce:

1. In a shell that is already opened in Terminus, right-click and select any of the options in `New as admin` in the context menu to open a new elevated shell;
2. Press key `Home`, and you will see the key does not work, and there appear some strange characters `[H` in the shell. Some other keys also echo strange characters, which will be listed below.

The list of the control keys that echo strange characters (which may be incomplete as there are not so many keys on my laptop):

| Key | Strange characters |
| --- | ------------------ |
| `Up Arrow` | `[A` |
| `Down Arrow` | `[B` |
| `Left Arrow` | `[D` |
| `Right Arrow` | `[C` |
| `F1` | `OP` |
| `F2` | `OQ` |
| `F3` | `OR` |
| `F4` | `OS` |
| `F5` | `[15~` |
| `F6` | `[17~` |
| `F7` | `[18~` |
| `F8` | `[19~` |
| `F9` | `[20~` |
| `F10` | `[21~` |
| `F11` | `[23~` |
| `F12` | `[24~` |
| `Insert` | `[2~` |
| `Delete` | `[3~` |
| `Home` | `[H` |
| `End` | `[F` |
| `Page Up` | `[5~` |
| `Page Down` | `[6~` |

**Note:** This bug will appear only when launching an elevated shell with `Run as admin` options in the context menu. It does not appear when Terminus itself is launched under administrative privileges to get an elevated shell.

**Comment by YangHanlin** [comment]
I have downloaded the lastest version (Alpha 75) and tried again, and unfortunately the problem still exists (an exception is `F11`, which will change Terminus to full-screen mode when pressed now). Thanks to the author anyway for providing such a beautiful and powerful terminal.

**Comment by vinguan** [comment]
This bug still exists, is there a way to fix it?

**Comment by Eugeny** [comment]
@vinguan have you retested it with the latest release?
