### ISSUE TITLE
Terminal does not gain focus when window focus returns

### ISSUE THREAD

**Issue by dsbert** [Eugeny/terminus#692]
On Windows, when changing focus to a minimized Terminus, sometimes the focus remains on the Window itself rather than the terminal input. A second click is needed before I can start typing. The expectation is that if Terminus is in the foreground and I start typing, it should always register input.

**Comment by UweKeim** [comment]
Please don't mark it a stale. Focus is a huge thing for me, having to extra click really makes this rather unreliable and unusable to me.
