### ISSUE TITLE
Zmodem support (lrzsz)

### ISSUE THREAD

**Issue by tavisdxh** [Eugeny/terminus#693]
The server support rz/sz, I can upload/download file through other terminal like xshell. 
But when I type rz or sz in terminus, it looks like supspend showing some bytes. 
I love terminus, would you tell me how to upload file from local and download file , thanks a lots!

Local PC: windows 10
Server: Centos 7
Terminus: terminus-Setup-1.0.71.exe

**Comment by garyelephant** [comment]
+1

**Comment by willxin1024** [comment]
+1 for mac。 if support, then perfect!!

**Comment by jcxwyh** [comment]
+1

**Comment by zwmmm** [comment]
+1 for windows 10

**Comment by zend** [comment]
It would be nice to have it. I found this project https://github.com/FGasper/zmodemjs may be helpful.

**Comment by ixbear** [comment]
+1

**Comment by WallE-Chang** [comment]
+1 for mac

**Comment by almas1992** [comment]
+1 for mac&windows

**Comment by huangxuanyuan8** [comment]
+1 really need it

**Comment by keosu** [comment]
+1

**Comment by MuZiRuoYi** [comment]
+1

**Comment by jk2K** [comment]
Zmodem is already supported, If not work, please check your language, `export LC_ALL='en_US.UTF-8'` may help you solve this problem

**Comment by Leon2018** [comment]
+1 for windows 10.

**Comment by willron** [comment]
+1 for linuxmint

**Comment by stdhi** [comment]
+1 for windows 10.

**Comment by lishucheng1227** [comment]
+1 for mac

**Comment by JJLAAA** [comment]
+1 for mac

**Comment by jue-jue-zi** [comment]
+1 for windows 10.

**Comment by zend** [comment]
First of all, Zmodem works perfectly now, please read the entire page.

Pay attention: LC_CTYPE on the remote machine matters, if rz/sz not working, try to set LC_CTYPE to a empty string:

`export LC_CTYPE=`

**Comment by c-jonathan** [comment]
+1 for Serial

**Comment by bbs2022** [comment]
> Guys, please read. Zmodem has already been added a long time ago.

Hi Eugeny, it seems zmodem is not supported, if the client is a Mac

**Comment by internelp** [comment]
+1 for mac

**Comment by hereTac** [comment]
> Guys, please read. Zmodem has already been added a long time ago.

Not for localhost -ssh-> host A -ssh-> host B ( rz/sz ). For my usecase the host A called JumpServer A. @Eugeny (Client is Linux
