### ISSUE TITLE
Switching tabs causes terminus not responsive

### ISSUE THREAD

**Issue by wtdcode** [Eugeny/terminus#695]
Perhaps duplicate of #464 and #687 .

When switching tabs quickly, sometimes the terminus becomes totally not responsive and only leaves its background like this:

![snipaste_2019-03-02_00-52-52](https://user-images.githubusercontent.com/30623163/53653329-080f1080-3c86-11e9-8b6f-ab2af78916fc.png)

As you can see, terminus only has its background left.

BTW, it seems that switching between ssh shells is more likely to cause this bug.

OS: Windows
Version: Alpha 71

**Comment by warthurton** [comment]
I am seeing the same issue.  If I have two tabs open and switch between them and start typing Terminus goes non-responsive.

![9w0kpnj93o](https://user-images.githubusercontent.com/202251/54046673-10de7580-41a3-11e9-88ac-dc42a6b01f43.png)

I will record a video later.

**Comment by saumyajyoti** [comment]
I am also seeing the same issue on win10 PC. After switching tabs and typing few commands , it will always hang.

**Comment by whoismy8023** [comment]
I am also seeing the same issue on win10 PC

**Comment by Anthodev** [comment]
Same issue (on both Windows 1809 and 1903) from Alpha 73 at least (got it on Alpha 79 right now).

**Comment by wtdcode** [comment]
I have moved from terminus to cygwin since this bug has a great impact on the experience of the daily use.



On 06/05/2019 13:50, Cédric Anthony<mailto:notifications@github.com> wrote:

Same issue (on both Windows 1809 and 1903) from Alpha 73 at least (got it on Alpha 79 right now).
