### ISSUE TITLE
Some hotkeys don't work with xterm

### ISSUE THREAD

**Issue by superm1** [Eugeny/terminus#696]
I've noticed that I can't seem to get my configured hotkeys for changing tabs (ctrl-tab) to work when I have xterm set as the frontend.

Switching to hterm and restarting the app they start to work.

I have 1.0.71
Ubuntu 18.04

**Comment by superm1** [comment]
Same issue exists on Windows 10 as well.

**Comment by baflo** [comment]
+1

**Comment by neta79** [comment]
+1
