### ISSUE TITLE
Can't find npm, even after I installed it

### ISSUE THREAD

**Issue by senhuiguo** [Eugeny/terminus#698]
Version: 1.0.71
Platform: darwin 18.2.0
Plugins: none

**Comment by Bevisy** [comment]
first checking npm from $PATH,is existing or not?

**Comment by Eugeny** [comment]
This has already been fixed - please try the nightly build

**Comment by sburkett** [comment]
I am getting the same issue on Win10.  Things I've tried:

- Installed the latest nightly build
- confirmed that `npm` is in my %PATH%
- Added `npm: 'C:\Program Files\nodejs\npm'` to my Terminus config file

No matter what I try, I still get the `Error: Cannot find module 'npm'` message when trying to install a plugin. Any ideas? Thanks!
