### ISSUE TITLE
[Feature-Request] Remove Ctrl-A as the default for Hotkeys

### ISSUE THREAD

**Issue by encima** [Eugeny/terminus#7]
Many tmux users [change](https://wiki.archlinux.org/index.php/tmux) the binding from Ctrl-B to Ctrl-A due to its ease.

Tmux did not work for me until I removed all the hotkey links. Could we change these to a less common default, please?

**Comment by msvana** [comment]
+1 Similar problem with "screen".

**Comment by ttamttam** [comment]
Idem. Emacs, bash (jump to the beginning of the line).

**Comment by Eugeny** [comment]
Well, the Ctrl-A bindings can be easily removed from Settings. Also, I'm planning to make it easier with #145
