### ISSUE TITLE
Opening with /bin/zsh shell not saying that im in the shell

### ISSUE THREAD

**Issue by gotama** [Eugeny/terminus#70]
So granted I am still learning zsh and only have experience with bash because that was defaulted.

I am now branching off and learning other shells.  

But now to get to the point so ive set terminus shell as zsh and when i open a tab it says zsh at the top but when i type

>echo $SHELL
the output is
> /bin/bash

**Comment by Eugeny** [comment]
Did you do any changes to your `zshrc`? Do you see `zsh` or `bash` in the process tree?

**Comment by Eugeny** [comment]
Closing due to the lack of activity. Please feel free to reopen if the issue is still relevant!
