### ISSUE TITLE
Problem with text editors

### ISSUE THREAD

**Issue by lazarossk** [Eugeny/terminus#706]
Version: 1.0.71
Platform: win32 10.0.17763
Plugins: none
I connect to a unix machine and i use nano.But when i move down the lines if i come back up the text is shuffled but only visually because when i exit and reopen i can see the text as it should be.Furthermore (^V and ^Y) dont work inside the editor so i cand move through pages.

**Comment by jordancluts** [comment]
I've had the same issue using nano where the text becomes jumbled.

**Comment by Eugeny** [comment]
Fixed in Alpha 75

**Comment by chx** [comment]
I am using Version: 1.0.77 and Ctrl+V is not working inside nano. Windows 10.
