### ISSUE TITLE
Cannot ctrl+c abort

### ISSUE THREAD

**Issue by baflo** [Eugeny/terminus#708]
I have a problem to abort a program with `ctrl+c`, namely ngrok in this case. I also turned off the _intelligent ctrl+c copy_, but that doesn't have any influence. 

- Aborting works in WSL shells
- Aborting does not work in PowerShell, cmd.exe and with cmder when ConPTY is deactivated
- Aborting works when ConPTY is activated

My current version is 1.0.71.631.

**Comment by princemaple** [comment]
Yep, same. ctrl+c just adds ^C to commandline input on powershell.

**Comment by Eugeny** [comment]
Fixed in 2227f2c

**Comment by ruslanguns** [comment]
@Eugeny I don't know if this is related to my issue, however shell takes long to cancel a program in node. I hit Ctrl+C and sometimes takes up to 4 minutes.
