### ISSUE TITLE
Cannot reliably copy (on select as well ctrl+shift+c)

### ISSUE THREAD

**Issue by baflo** [Eugeny/terminus#709]
The copy doesn't work correctly. I can't really recognize a pattern, but when I copy from the output of `ngrok`, some content is well copied while others is not. Especially when marking the URL, the whole line is copied.

**Comment by princemaple** [comment]
I've found cases where plugins affect copying. Probably clickable links.

**Comment by baflo** [comment]
I can confirm that this issue is solved when deactivating _clickable links_

**Comment by Eugeny** [comment]
Duplicate of #696
