### ISSUE TITLE
terminus vs upterm (formerly black screen)

### ISSUE THREAD

**Issue by bali182** [Eugeny/terminus#71]
Could you please add a note (maybe in the readme) about what are the advantages over the other typescript/javascript and electron based terminal emulator project?

**Comment by princemaple** [comment]
At the very least, this one is officially supporting Windows. 💟

**Comment by Eugeny** [comment]
Upterm is a combined terminal/shell project, and they are trying to redesign the shell experience to be more IDE-like, while Terminus focuses on the "classic way" of having a shell of your choice running in a terminal. The projects have different goals and you can't really compare them.
