### ISSUE TITLE
vim editor can't enter block visual mode 

### ISSUE THREAD

**Issue by zoneus** [Eugeny/terminus#713]
Version: 1.0.72
Platform: darwin 18.0.0
Plugins: none

First thank for terminus anthor, I like use terminus very much. Frequently, I use it for linux ssh. But when i want to enter block visual mode by press (Ctrl+v) in Vim editor, There is't any effect, I don't know the how to solve the problem.

above is right situation picture on the other terminal tool(iTerm2) 
![96322F70-F351-4E9F-847F-9AEC41FB4107](https://user-images.githubusercontent.com/30338668/54084036-b68e1200-4366-11e9-9166-0aded7ac099b.png)

**Comment by github-pengbin** [comment]
By the way, I use terminus on the MacOS
