### ISSUE TITLE
prompt buggy directly after clearing the screen

### ISSUE THREAD

**Issue by neodyma** [Eugeny/terminus#717]
After clearing the screen in any terminal (`ctrl+l`), the next typed command gets displayed incorrectly. The first input letter overwrites the first char of the promt, then input resumes at the bottom of the terminal, while the prompt is active in the topmost line.

![image](https://user-images.githubusercontent.com/7633051/54244632-cd329580-452d-11e9-8911-664badc7e763.png)

alpha 73 on windows 10 1809

**Comment by glen-84** [comment]
Have you tried disabling ConPTY?

**Comment by neodyma** [comment]
thanks, that did the trick
