### ISSUE TITLE
xterm swallows Ctrl-@

### ISSUE THREAD

**Issue by mskyspet** [Eugeny/terminus#718]
zssh hotkey is ctrl+@, which could not be actived in xterm. 
it works fine in hterm.

Version: 1.0.73
Platform: win32 10.0.17763
Plugins: none

**Comment by melonwool** [comment]
when i use vim, i can't use ctrl+v

**Comment by melonwool** [comment]
stop plugin **quick-cmds**,  ctrl + v can use in vim.
