### ISSUE TITLE
Input simultaneously to all panes

### ISSUE THREAD

**Issue by danielfinke** [Eugeny/terminus#722]
I can see that there is support for splitting off extra panes horizontally/vertically, but a feature I am missing from iTerm on macOS is the ability to key in input to all panes in a tab at the same time. I typically use this when working on a number of redundant remote machines over SSH that require the same work done.

**Comment by Eugeny** [comment]
Note to myself: iTerm shortcut is Cmd-Shift-I

**Comment by honza-o** [comment]
yes, please, great feature to have. one addition though: allow to exclude panes from that multi-input. e.g.: you have opened 6 ssh sessions to cluster nodes, but want to send commands just to 5 of them.

**Comment by GanapathyRaman** [comment]
Definitely a good feature to have.
