### ISSUE TITLE
Split panes, no cursor on second pane

### ISSUE THREAD

**Issue by jodaks** [Eugeny/terminus#728]
Version: 1.0.73
Platform: darwin 18.2.0
Plugins: clickable-links

The split panes feature is cool... for some reason, the cursor on the second pane is not visible. Also, is there a way to change the color of the divider or make it permanently visible instead of just showing it on mouse over or while dragging?

**Comment by RafaelGondi** [comment]
It would be very useful. It is very difficult to know where you are because there is no clear division between the panes.
