### ISSUE TITLE
Tab content disappears when switching tabs

### ISSUE THREAD

**Issue by helloxz** [Eugeny/terminus#729]
Please see the screenshot below.

![image](https://user-images.githubusercontent.com/7276531/54803861-33e14d00-4cac-11e9-9481-0f3d292577c1.png)

**Comment by jstanley23** [comment]
I have same issue using 1.0.73. Switching between Windows temporary loses content.

Switching back and forth again sometimes renders the previous content. Hitting enter will restore contents as well.

At times I have trouble duplicating the issue.

![2019-04-04_7-34-34](https://user-images.githubusercontent.com/7001549/55552730-34b2af80-56ac-11e9-9573-0cd9cf73088a.gif)


my config.yaml (minus ssh context)

hotkeys:
  shell:
    clink: []
    powershell:
      - - Ctrl-Alt-P
    cmd:
      - - Ctrl-Alt-C
  profile: {}
terminal:
  environment: {}
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  shell: wsl
  useConPTY: false
  rightClick: paste
  copyOnSelect: true
appearance: {}

**Comment by andrecavallari** [comment]
Same here

**Comment by raphaelriehl** [comment]
Same issue with Ubuntu 17.10 and 18.04.

**Comment by NDelt** [comment]
Same in Alpha 79

**Comment by thomasem** [comment]
It's interesting that this doesn't seem to happen when I have the Developer Console (DevTools) open in Windows 10.

**Comment by thomasem** [comment]
I've seen this behavior improve when I have settings tab open or developer console open and resize the window once or twice. Makes me wonder if it's something wrong with the underlying framework more-so than the Terminus app code itself. :\

**Comment by Eugeny** [comment]
Pushed a potential fix - please give it a try with a nightly build!

**Comment by thomasem** [comment]
@Eugeny still seeing issue with nightly build (`1.0.82-c27-g76b81f8`)

Few returns in tab 2 and made a new tab 3:

![Annotation 2019-06-20 061630](https://user-images.githubusercontent.com/4181816/59845545-4870c800-9323-11e9-9c38-1c403fe01a32.png)

Switched back to tab 2 via hotkey:

![Annotation 2019-06-20 061651](https://user-images.githubusercontent.com/4181816/59845543-460e6e00-9323-11e9-8227-6cbb07bc9b36.png)

**Comment by Tahmeed156** [comment]
Switching the front-end implementation from 'xterm' to 'hterm' does fix the issue. But does I don't know if it might cause problems afterwards. 
App: Terminus 1.0.82
Env: Windows 10

**Comment by thomasem** [comment]
That's interesting. I also switched to `hterm` and seem to not be having the problem anymore. Will report back. At least seems like a decent workaround! Thank you!

**Comment by NDelt** [comment]
Selecting `Settings | Appearance | xterm (WebGL)` seems to solve the issue.

**Comment by Chr1s-T** [comment]
> @Tahmeed156 That's interesting. I also switched to `hterm` and seem to not be having the problem anymore. Will report back if I notice anything odd. At least seems like a decent workaround! Thank you!

Hello, I got some trouble, would you help me? When I ssh to a server and use ctrl-r to seach the command history, it doesn't work. Do you know how to solve this problem?

**Comment by whyboris** [comment]
Confirming I had the same problem on `Mac OSX 10.13.6` and _Terminus_ `Alpha 85` 
Switching to `hterm` or `xterm (WebGL) from `xterm` (Settings | Appearance | Frontend) fixed the issue ✅

**Comment by WhiteGreeny** [comment]
save in alpha 85

**Comment by Eugeny** [comment]
Just added another potential fix - please check the nightly build once it's ready

**Comment by Jaeiya** [comment]
I just tried the latest nightly build and switching tabs seems to be fixed for me.

**Comment by thomasem** [comment]
Latest nightly does appear to work! Neat. :)

**Comment by Eugeny** [comment]
Thanks! Let me know if anyone sees this again

**Comment by ghnp5** [comment]
This happened to me now, for 2 local (not SSH) tabs I had open, where the console contents no longer appear.

Fedora 44  - this happened right after upgrading from F43 to F44.
