### ISSUE TITLE
Terminus on Windows clear the terminal window with bug

### ISSUE THREAD

**Issue by Egorvoz** [Eugeny/terminus#73]
So on Windows when i wanna clear terminal - i use `clear` or `ctrl + L`.
And as you can see in the screenshot down below - 
the command works well, but the history stay on screen.
---
![terminus_2017-07-05_16-06-38](https://user-images.githubusercontent.com/6547453/27865617-f2e12052-619b-11e7-9c7f-2da5b2ef4b68.png)

**Comment by Eugeny** [comment]
Duplicate / see #28

**Comment by Egorvoz** [comment]
@Eugeny sorry.
