### ISSUE TITLE
WARNING: terminal is not fully functional when trying to use 'less' cmd

### ISSUE THREAD

**Issue by chunwai94** [Eugeny/terminus#730]
I am using Terminus on Windows 7. When I ssh into my solaris 10 server and browse file using 'less' cmd, I always get the WARNING: terminal is not fully functional message. Ssh into solaris 11 server doesn't have this issue.

**Comment by kachunkachunk** [comment]
I think you'll get that message when you're using a TERM parameter via the SSH session which isn't well implemented in your user environment on your Solaris 10 server.

Compare the output of `echo $TERM` in both SSH and Terminus. Chances are, they are different, with xterm usually being a safe bet.

If so, in Terminus, you can try going to Settings -> Appearance -> Frontend and switch between `hterm` and `xterm`, before connecting, and seeing if it helps.

I'm not sure if you can do this on a per-connection setting, nor am I familiar with hterm all that much. So far no complaints, but I'm mostly using Manjaro and Ubuntu machines for SSH and Terminus.
