### ISSUE TITLE
Extremely blurry text, no acrylic background

### ISSUE THREAD

**Issue by iGerman00** [Eugeny/terminus#731]
Version: 1.0.73
Platform: win32 10.0.17763
Plugins: theme-hype, theme-windows10

http://igmn.tk/storage/sx/img/Terminus_e8Mo70c8fX.png
I have this issue with seemingly all Electron apps (Discord, Terminus, The new Skype), and I couldn't find a solution online. The text is just blurry and sometimes barely readable. Acrylic background is also not working unfortunately, and that's my favorite feature of Terminus on Windows 10.

I have tried renaming/deleting swiftshader in %LOCALAPPDATA%/Terminus/app-whatever, didn't fix the issue for me like for Discord

**Comment by DDoSolitary** [comment]
It seems to be an upstream issue and can be fixed by disabling FXAA in the NVIDIA Control Panel.
