### ISSUE TITLE
Command-line option to open a specific shell

### ISSUE THREAD

**Issue by sippeangelo** [Eugeny/terminus#732]
Would be nice with a command line option to select which shell to open when passing "open" to Terminus through the command line. 

Right now I'm relying on my default setting being correct, but I'd like to use Terminus in multiple places using different shells, and I can't without manually opening a shell and browsing to the paths I want to have opened in each shell window.

**Comment by bmo-at** [comment]
Definitely a worthwhile addition! I'd also like to use Terminus all over Windows, including but not limited to with WSL (already in use and the best damn Terminal of all) but also Python Windows Version, general command line usage etc.

**Comment by Eugeny** [comment]
This is now available as `terminus profile <profile-name>` for any custom profile.

**Comment by sippeangelo** [comment]
Much appreciated!
