### ISSUE TITLE
Can't split tabs

### ISSUE THREAD

**Issue by lonkaars** [Eugeny/terminus#733]
I feel incredibly stupid asking this but I'm coming from Visual Studio Code so I figured you could drag tabs to the side of a window to split screen, but that doesn't work. My question is how do you split tabs, or am I misunderstanding the feature?

**Comment by Eugeny** [comment]
No worries :) 
Terminus doesn't let you _combine_ tabs the way VSC does, but rather only split existing ones. Use the "Split to the right/bottom/left/top" hotkey for that.

**Comment by levysaar** [comment]
Is there a way to close a split after I opened it?

**Comment by Eugeny** [comment]
It closes itself as soon as you exit the shell

**Comment by levysaar** [comment]
ohh, so I guess I will have to close and open the app again.
since our server using Google Authenticator
And I just wanted to try the split feature I didn't insert the code
so I haven't really logged into the server and can't exit now ^^"

**Comment by Eugeny** [comment]
@levysaar good point, added it as https://github.com/Eugeny/terminus/issues/735
