### ISSUE TITLE
Can‘t set zsh as my shell in Terminus

### ISSUE THREAD

**Issue by Peter-Duan** [Eugeny/terminus#736]
Version: 1.0.73-c9-g9e81f0a
Platform: win32 10.0.17134
I have set zsh as my shell. But when I restart Terminus it still use bash.

**Comment by JackieJK** [comment]
It's your problem

**Comment by vadikgo** [comment]
try to add custom shell with command:
```
zsh.exe -l -i
```

**Comment by Peter-Duan** [comment]
I solved it, I just add `ash -c zsh` at bashrc

**Comment by TZTsai** [comment]
> I solved it, I just add `ash -c zsh` at bashrc

should be 'bash -c zsh'

**Comment by khairuljf** [comment]
I am using ubuntu 18.4 but it's not working for me.
