### ISSUE TITLE
Any chance of supporting SSH gateway (jump host)?

### ISSUE THREAD

**Issue by kurisu-gh** [Eugeny/terminus#737]
Would be great to have additional settings when configuring an SSH host to also specify an optional jump host (along with its own authentication settings) to connect to. From a UX point of view, you can perhaps have the jump host setting set to an already specified/configured SSH host connection to keep the SSH host configuration window clean.

**Comment by hinews** [comment]
Yes, without this feature I cannot use EC2 gateway

**Comment by dabrazhe** [comment]
Any progress on proxy command? It's essential feature and the reason I am not using Terminus

**Comment by Eugeny** [comment]
@dabrazhe it's a high priority feature, but I've got very limited time available for working on Terminus. I'm aware of this and all other requests - the best you can do is put a thumbs up on the first post - this will make your request appear higher on the sorted issue list.

**Comment by Eugeny** [comment]
A jump host connection can now be selected on the Advanced tab for each connection.

**Comment by kurisu-gh** [comment]
@Eugeny Thank you very much for all of your efforts!
