### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Sabdix** [Eugeny/terminus#739]
Version: 1.0.71
Platform: win32 10.0.17763
Plugins: altair, clickable-links, theme-gruvbox, theme-hype, theme-windows10, title-control

When Working with NANO, some of the content freezes, so it looks weird

**Comment by bes-internal** [comment]
Did you try to change terminal frontend implementation? Preferences - Apparnce - xterm/hterm

**Comment by Eugeny** [comment]
Duplicate of #706
