### ISSUE TITLE
Cant Run Terminus With Non-root User In Ubuntu

### ISSUE THREAD

**Issue by zoso65** [Eugeny/terminus#74]
Hi 
after installing deb package i cant run terminus from my apps list by clicking the terminus icon and cant run it with non root user without sudo. I even changed the owner of terminus binary to my user but nothing happens when i run it.

**Comment by dmityaev** [comment]
Faced same issue. Ubuntu 16.04.2 LTS.

**Comment by dmityaev** [comment]
bump...
does anybody know if there is workaround or proper installation steps to run terminus from any account?

**Comment by Eugeny** [comment]
So what happens if you try to run it? What happens if you start it from the Gnome terminal - do you get any logging?

**Comment by dmityaev** [comment]
It just exists silently.
Could you suggest where logs are located or how to switch logging on? I haven't found any logs related to terminus.

**Comment by Eugeny** [comment]
Try running `/opt/Terminus/terminus --debug` in another terminal an see if there is any output

**Comment by dmityaev** [comment]
Nope, there is no any output.

**Comment by Eugeny** [comment]
Also nothing in the syslog? Is your arch `x86_64`?

**Comment by dmityaev** [comment]
> Also nothing in the syslog?

Not even trace of anything was launched or crashed.

> Is your arch x86_64?

It's true. Hope this info will help:
```
~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
~$ uname -a
Linux host 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by friederbluemle** [comment]
Any updates on this? I'm still seeing this behavior more than 1 year after the issues was first opened:

1. Start `terminus` (no difference when using `terminus --debug`)
1. Output: `Host startup: 25ms`
1. Splash screen shows up (fade in animation of Terminus logo)
1. Splash screen just stays there (stuck forever)

I'm running Arch Linux with i3/awesome wm and no display manager (if that matters).

**Comment by friederbluemle** [comment]
@Eugeny Thanks for the reply. This is what I see under the directory:

```
$ ls ~/.config/terminus 
Cookies  Cookies-journal  GPUCache  Preferences  window.json
```

**Comment by friederbluemle** [comment]
@Eugeny - I still can't get past the initial splash screen. Tried i3wm, awesome, and sway - it's the same for all three window managers. Any other ideas? Thanks.

**Comment by Eugeny** [comment]
@friederbluemle does the --debug flag automatically open DevTools for you? If yes, please grab the console log from there.

**Comment by friederbluemle** [comment]
@Eugeny - No, unfortunately adding the `--debug` flag does not make any difference. Is there a log file written to disk somewhere? Or would it help if I would build the project from source with some debug flag enabled?

**Comment by friederbluemle** [comment]
Btw. should I open a separate issue for the discussion? This is not related to the topic of this issue (using sudo makes not difference either).

**Comment by Eugeny** [comment]
There is also a hotkey to open the devtools - see https://github.com/Eugeny/terminus/wiki/Debug-logs
It's weird that the log isn't being written though

**Comment by friederbluemle** [comment]
I tried the hotkeys, but it seems like the app gets stuck on the splash screen before the hotkeys are being registered. One thing I noticed is that the file `~/.config/terminus/window.json` does get updated based on where I move the window before I close it. Closing the window does _not_ end the process, it has to be killed manually. While the process is alive there are also several other temporary files/links (e.g. "SingletonCookie") visible in the `~/.config/terminus` directory. Anything there that could be of use?

**Comment by Eugeny** [comment]
Unfortunately not. Is there any chance you could try building Terminus from source as outlined in https://github.com/Eugeny/terminus/blob/master/HACKING.md? I'll understand if it's too much hassle.

**Comment by Eugeny** [comment]
Could you also try the official snap or tgz builds?

**Comment by undu** [comment]
Using AUR's package I get this stack trace when running terminus with the `--debug`:

```
entry.preload.ts:34 Error: Cannot find module 'terminus-core'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602)
    at Function.Module._resolveFilename (/opt/Terminus/resources/electron.asar/common/reset-search-paths.js:35)
    at Function.Module._load (internal/modules/cjs/loader.js:528)
    at Module.require (internal/modules/cjs/loader.js:658)
    at require (internal/modules/cjs/helpers.js:20)
    at forEach.t (plugins.ts:73)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (plugins.ts:72)
    at e (bootstrap:19)
    at Object.<anonymous> (entry.ts:16)
process.on.n @ entry.preload.ts:34
```

Also the binary in /usr/bin is not a valid executable, although the one in `/opt/Terminus/terminus` brings up the splash screen

**Comment by friederbluemle** [comment]
This is still a problem today (Feb 8, 2019).

Terminus installed through AUR on Arch Linux (i3wm, no display manager) just shows the splash screen for me, stuck indefinitely.

I noticed a few things:
- The `/usr/bin/terminus` script just calls `/opt/Terminus/terminus` (*without* passing parameters)
- When starting from command line `/opt/Terminus/terminus --debug`, I do see the chrome console windows in addition to the splash screen (which does not go away)
- The Chrome JavaScript console shows the following: `Error: Cannot find module 'terminus-core'` (and a stacktrace).

Does this help at all?

**Comment by Eugeny** [comment]
@friederbluemle please contact the package author (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=terminus-terminal-git). `/usr/bin/terminus` should be a symlink, not a wrapper script.

**Comment by Eugeny** [comment]
This has already been fixed in both Ubuntu and Arch AFAIK
