### ISSUE TITLE
xterm multiple font support

### ISSUE THREAD

**Issue by lonkaars** [Eugeny/terminus#742]
## xterm multiple font support
I cant use multiple fonts in xterm, so I have to use hterm, but that has issues too:

### fontend comparison:
<img src="https://imgur.com/E2QLW0Z.png">

As you can see, xterm doesn't support multiple fonts as it defaulted to the same as no font.
I want to use xterm because hterm doesn't render pipe characters properly with the ssh plugin...

### Example 1, `pm2 list`:
<img src="https://imgur.com/wHu22uM.png">
this renders properly over ssh with the tab launched from the ssh plugin;

### Example 2, `pm2 monit`:
<img src="https://imgur.com/11GQTMo.png">
hyper on the left, terminus on the right. Hyper and terminus both look fine when launching ssh manually, but terminus' ssh plugin doesn't render the pipes correctly in this example.
<br><br>
Is this an unsupported feature of xterm or am I doing something wrong?

**Comment by Eugeny** [comment]
xterm indeed doesn't support font fallback - opened https://github.com/xtermjs/xterm.js/issues/1983

As a workaround, here's Consolas with Powerline characters patched in: https://github.com/Znuff/consolas-powerline

The borders in `pm2` are however not related to this - it means `pm2` is not detecting Unicode support in the terminal. Compare your environment when connecting from Hyper vs when connecting from Terminus

**Comment by dgcliff** [comment]
Looks like xtermjs/xterm.js#1983 was closed because XTerm does support fallback with fontFamily. It'd be nice to have this implemented so that Segoe UI Emoji could be used in windows 10 to display emoji.

**Comment by black-desk** [comment]
I may have the same problem on win10. Using the font in the link above which name Consolas NF, my termintus look like this.  Poor English, forgive me.TAT 
![image](https://user-images.githubusercontent.com/29726878/57460882-88ff0f80-72a8-11e9-84f6-3b93132d421c.png)

**Comment by black-desk** [comment]
![image](https://user-images.githubusercontent.com/29726878/57460961-b350cd00-72a8-11e9-9489-60514c906bc4.png)

**Comment by black-desk** [comment]
![InkedTerminus_LqlGb8wTnE_LI](https://user-images.githubusercontent.com/29726878/57461196-29edca80-72a9-11e9-95b9-e26322c52bc2.jpg)

**Comment by lonkaars** [comment]
@black-desk That's not an issue with terminus itself. In a terminal, text can be black, but if the background is black it's seen as transparent. The way powerline works in your screenshot is foreground black, background blue, so you can see the black. I solved this issue with an edit of agnoster.theme, making the first portion of the line grey instead of black. If you want to change it, you can look into [this](https://github.com/agnoster/agnoster-zsh-theme/issues/30)

**Comment by black-desk** [comment]
@lonkaars It seem's the best way to solved this issue that getting my terminal's background color to black. I just want to know can this little black triangle be transparent, thank you.
