### ISSUE TITLE
Transparency settings does not work on kde

### ISSUE THREAD

**Issue by bace1996** [Eugeny/terminus#744]
Version: 1.0.73
Platform: linux 5.0.3-200.fc29.x86_64
Plugins: none
using Fedora 29 with Kde plasma
setting transparency as image but not effect

![DeepinScreenshot_select-area_20190331092914](https://user-images.githubusercontent.com/10097443/55283509-7f27e980-5397-11e9-90e1-4be0794d7437.png)

**Comment by douglasmiranda** [comment]
Are you using Nvidia? Or just Intel graphics?

**Comment by douglasmiranda** [comment]
I'm on linux too, but my setup is: https://github.com/Eugeny/terminus/issues/539#issuecomment-480537386

**Comment by bace1996** [comment]
> Are you using Nvidia? Or just Intel graphics?
using 
Nvidia-driver 418.56 
Terminus Alpha 73

Qt: 5.11.3
KDE Frameworks: 5.55.0
kf5-config: 1.0

Fedora 29

**Comment by lucawen** [comment]
not working with me too

**Comment by papodaca** [comment]
Same behavior on Gnome also with nvidia. Also tested on my laptop with Intel graphics the same behavior is present.
