### ISSUE TITLE
 Scrolling Invalid when using linux screen command

### ISSUE THREAD

**Issue by festoney8** [Eugeny/terminus#746]
When using linux `screen` command tool, the scroll bar disappeared. 
Scrolling will change the command history but not show the terminal output above.

os: win10
ssh remote system os: Debian 9
plugins: ssh, community-color-schemes, core, plugin-mananger, settings, terminal
terminus version: 1.0.73

**Comment by kankaristo** [comment]
This is a feature of `screen`, since you can have multiple "tabs" inside `screen` itself, scrolling in the terminal wouldn't really make sense (same for `tmux`):
https://unix.stackexchange.com/questions/40242/scroll-inside-screen-or-pause-output

**Comment by festoney8** [comment]
> This is a feature of `screen`, since you can have multiple "tabs" inside `screen` itself, scrolling in the terminal wouldn't really make sense (same for `tmux`):
> https://unix.stackexchange.com/questions/40242/scroll-inside-screen-or-pause-output
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/7994b6dc2a0dce415aade18fe7c66bb3a7e5a4d7/68747470733a2f2f63646e2e737374617469632e6e65742f53697465732f756e69782f696d672f6170706c652d746f7563682d69636f6e40322e706e673f763d333266623037663763653236">Unix & Linux Stack Exchange**[Scroll inside Screen, or Pause Output](https://unix.stackexchange.com/questions/40242/scroll-inside-screen-or-pause-output)**I use screen for my command-line tasks while managing the servers where I work. I usually run small commands (mostly file-system tasks) but sometimes I run more extensive tasks (like DBA).
> > The out...

oh it works, that's great! thx~
