### ISSUE TITLE
Text selection / highlighting with the mouse is barely visible in light modes / themes

### ISSUE THREAD

**Issue by dabrazhe** [Eugeny/terminus#748]
The text selected with the mouse is almost impossible to tell apart from not selected text. This appears on the light themes and color scheme. I was unable to fix this in the settings.

In the image below the last 4 lines are selected.

Version: 1.0.71
Platform: win32 10.0.17134
Plugins: none

![image](https://user-images.githubusercontent.com/24795958/55464421-63bd1880-55fb-11e9-96ea-4b0d4d3efec7.png)

**Comment by Eugeny** [comment]
Already fixed
