### ISSUE TITLE
multiline (wrapped output) inserting newlines in the paste buffer

### ISSUE THREAD

**Issue by eroper** [Eugeny/terminus#749]
If I cat a file with long lines (WSL), that are wrapped during output, then select and copy the text, it erroneously contains newlines where it was display-wrapped, despite the source not having newlines.

I don't know if this is fixable, but it's inconsistent with the behavior of linux terminals, putty, etc.

I'm currently using the hterm front-end.

**Comment by Eugeny** [comment]
Unfortunately, WSL with or without ConPTY doesn't let us distinguish between wrapped lines and true newlines yet.

**Comment by chx** [comment]
@Eugeny That's strange because conemu does it.
