### ISSUE TITLE
Can't type ~ on mac

### ISSUE THREAD

**Issue by adraax** [Eugeny/terminus#75]
On Alpha 15 and 16, we can't use `⌥ + n` to type the `~` character.

I'm using OS X 10.11.1 (15B42)

**Comment by vincenttschanz** [comment]
not sure if I need to file another issue for this, but in a similar way, the alt-arrows shortcuts (to move by one word in the command line) are also not working.

`⌥ + ←` print a `;3D` instead of moving one word left

`⌥ + →` print a `;3C` instead of moving one word right

**Comment by Eugeny** [comment]
Should be fixed in the recent alphas.

**Comment by Eugeny** [comment]
Ref #316
