### ISSUE TITLE
Feature Request: Save Tabs/Panes in profile (Session)

### ISSUE THREAD

**Issue by douglasmiranda** [Eugeny/terminus#752]
Would be nice to save tabs and panes, to make profiles more like a session.

Example: Profile My project

- Tab 1
  - Pane 1: monitoring
  - Pane 2: Logs
  - Pane 3: Shell inside the project directory
- Tab 2: Remote conection

... or am I able to achieve this already?

**Comment by mikepanayotov** [comment]
Is this possible?

**Comment by stevleibelt** [comment]
I also like this idea.

```
Title: Continue work after reboot of the host.

As a user of terminus, I want to continue my work after a reboot of my host or a restart of terminus.

Given: The users has opened multiple shells via tab like:
* tab1: local git repository
* tab2: ssh remote session for deployment
* tab3: powershell for active directory administration
And: the host system has to reboot
When: the reboot has been done and terminus is started
Then: the user wants to continue his work.
```

Either save session automatically every x seconds or manually.
Restoring a session should be either asked on startup "restart last saved session" or should be done manually by a menu dialog.

**Comment by mishoboss** [comment]
This is going to be a killer feature!

**Comment by Eugeny** [comment]
Guys, this has been a feature for a VERY long time:
![image](https://user-images.githubusercontent.com/161476/74422954-bdaf8100-4e4f-11ea-80d1-6acd88422d48.png)

Tabs are saved every 30 seconds and every time a tab is opened/closed

**Comment by stevleibelt** [comment]
@Eugeny sorry for the late reply.
So indeed, my tabs are restored (the amount and the typ of the tabs). What I wanted was that terminus also restores the current working directory of the opened tabs.
I don't know if this is possible or if my .bashrc contains a configuration that does not allows this action to take.

Is it expected and working that terminus is restoring the terminal tabs including the previous current working directory?

**Comment by Eugeny** [comment]
@stevleibelt if you're on Windows/WSL, see #1703

**Comment by Arro** [comment]
Would be cool to be able to save the exact contents of a window (say, four tabs, two in one working directory, and two in another) then open a "template" of this at will.  

Let me know if this capability already exists.  What I'm reading here is that once you close that window, that "config" (or "profile" or "session") is gone until you remake it.

**Comment by InanisOmnia** [comment]
Im having a similar issue, where saved tabs is only saving the layout and number. Information like working directory and previously run commands are not being saved

![image](https://github.com/Eugeny/tabby/assets/65400619/f0b7dcc5-d4d4-4763-b898-c8b59d9dd335)

It would be a far more useful feature if these details were restored on startup too!

**Comment by Eugeny** [comment]
Tabby doesn't manage your history, the shell does. As for the working directory, this is currently an issue with some Windows shells only: #1703

**Comment by Jomme5** [comment]
Is there an option to save session in a folder (like with vscode?) So you can save your workplace?
