### ISSUE TITLE
Tab screen is blank when switching to another tab

### ISSUE THREAD

**Issue by RobCannon** [Eugeny/terminus#755]
This is occuring in Terminus 1.0.73 running on Windows 10 1903.  When I switch back to a previously active tab, the screen is blank.  

The screen will show new content, but the older content does not display.

If I can force the screen to scroll, the previous content will display.

**Comment by PPPartric** [comment]
The same problem also happened on the macOS Mojave

**Comment by etricky** [comment]
+1 on Windows 10

**Comment by RobCannon** [comment]
I think this is related to #773.  In any event, switching from xterm to hterm does fix the issue.

You have to do this in the config file since the UI doesn't exist for that option any more:
```
terminal:
  frontend: hterm
```

**Comment by Eugeny** [comment]
Duplicate of #729
