### ISSUE TITLE
Feature suggestion:  Add custom button for quickly executing shell command.

### ISSUE THREAD

**Issue by Newamber** [Eugeny/terminus#756]
SecureCRT has a useful feature that it can create groups and buttons to access some frequently-used shell command, as an excellent terminal tool, I think terminus can consider supporting this feature~

**Comment by Eugeny** [comment]
Have you tried the terminus-quick-cmds plugin?

**Comment by Newamber** [comment]
I want to try it,  but at  `Settings | Plugins` ,  there are 2 problems:
* When I click "Plugins folder", it reminds me: Windows can not find file "C:\Users\xxx\AppData\Roaming\terminus\plugins", should I create the folder manually ?
* At "Available", it can not show any results when I try to search "terminus-quick-cmds", and  always waiting for loading (The circle on the left keeps rotating). I can access github, so maybe it has nothing to do with the Internet?

> Version: 1.0.73
> Platform: win32 6.1.7601
