### ISSUE TITLE
Doesn't show low dash '_'

### ISSUE THREAD

**Issue by GodOxidus** [Eugeny/terminus#757]
Hello,
Terminus doesn't draw low dash in windows 10. I use portable version 1.0.73.

**Comment by GodOxidus** [comment]
The problem was in Consolas font. In others, it draws low dashes.

**Comment by baflo** [comment]
When using `xterm`, the underscore seems to be printed.

**Comment by agilly** [comment]
Seeing the same issue using Source Code Pro and `hterm`, the issue disappears when using the `xterm` frontend.
