### ISSUE TITLE
"Smart copy" copy more than needed

### ISSUE THREAD

**Issue by Larandar** [Eugeny/terminus#758]
How to reproduce :
Selecting a partial line and right clicking "Copy" and then pasting it show that the selection isn't respected :
![image](https://user-images.githubusercontent.com/906021/55860649-08e46d80-5b75-11e9-9b75-50a115de7130.png) ) 
![image](https://user-images.githubusercontent.com/906021/55860776-45b06480-5b75-11e9-8d12-80058a79ea93.png)

What is expected :
Only the selected area is copied

How to fix :
- Quick : an option to disable "smart copy"
- Long term : manual selection should be prioritize over smart copying

**Comment by umstek** [comment]
This is the same for copy by both `Ctrl+Shift+c` and context menu copy.
