### ISSUE TITLE
Cannot add Hotkeys containing Spacebar

### ISSUE THREAD

**Issue by kelvins** [Eugeny/terminus#76]
I cannot add a new Hotkey that contains `Spacebar` on Windows.

If I try to add a new hotkey that contains a `Spacebar`, for example, `Ctrl+Spacebar`, each space that I press, add another control: `Ctrl-Ctrl-Ctrl-Ctrl-`. It seems to be a small bug.

Just a suggestion about `Ctrl+Spacebar`: 
The `Toggle terminal window` feature has the `Ctrl+Space` hotkey as default, right? I don't think the `Ctrl+Space` is a good choice. When using another software (e.g. Qt Creator), the `Ctrl+Space` is used for autocomplete, so when pressing it on Qt Creator the Terminus window will be shown in front of it.

**Comment by OvermindDL1** [comment]
Likewise, trying to set "Ctrl+Shift+\`" as the hotkey does not work either as \` (`~`) is not recognized.

**Comment by Eugeny** [comment]
I realize that Ctrl-Space doesn't suit _every_ occasion, but that's why it's made configurable :)

**Comment by skegel13** [comment]
It appears that the Windows key does not work. I set the toggle terminal to Win + ` and it makes so ` toggles the terminal but Win + ` does nothing.
