### ISSUE TITLE
[Feature Request] Reconnect closed SSH session

### ISSUE THREAD

**Issue by wangxin** [Eugeny/terminus#761]
When a SSH session is closed for some reason, I would like it could be re-connected. For example, right click the tab and select "Reconnect". Currently, I can only close the existing tab of closed SSH session and create a new one for reconnecting.

The most important reason for this feature:
*  I often need to check previous screen log of closed SSH session. If I have to close the existing tab and create a new one for reconnection, then I would lose the previous screen log.

**Comment by okwme** [comment]
I would love this too. I thought that was the whole point of using Mosh, so that when I’m in another app for a while and come back to terminus my session is still open...

**Comment by spanyukov** [comment]
on Windows 10 I don`t see reconnect command in right-clicked menu on a tab.
Moreover if a connection is lost in a tab, the tab will be closed automatically with an red marked error.

**Comment by gtsteffaniak** [comment]
@Eugeny Why was this closed with no fix?

**Comment by Eugeny** [comment]
This was closed with a fix. The reconnect button is available in the terminal bar if a session was disconnected.
![image](https://user-images.githubusercontent.com/161476/84438761-5c4dc200-ac37-11ea-9f29-dd3ca4d87f6a.png)

**Comment by gtsteffaniak** [comment]
> This was closed with a fix. The reconnect button is available in the terminal bar if a session was disconnected.
> ![image](https://user-images.githubusercontent.com/161476/84438761-5c4dc200-ac37-11ea-9f29-dd3ca4d87f6a.png)

I just tested this on my terminus and I do not get any reconnect button. it will give a toast ERR message and close the tab.

**Comment by Eugeny** [comment]
Can you please capture DevTools console logs at the time of the disconnection? https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by gtsteffaniak** [comment]
[ssh] [47m [49m Host key fingerprint:
log.service.ts:56 [ssh] Trying saved password
log.service.ts:56 [ssh-pig-22] Shell session ended
xtermFrontend.ts:117 Could not resize xterm Error: This API only accepts integers
    at eval (xterm.js:1)
    at Array.forEach (<anonymous>)
    at e._verifyIntegers (xterm.js:1)
    at e.resize (xterm.js:1)
    at XTermFrontend.resizeHandler (xtermFrontend.ts:113)
    at ResizeObserver.eval (xtermFrontend.ts:158)
XTermFrontend.resizeHandler @ xtermFrontend.ts:117
eval @ xtermFrontend.ts:158

**Comment by spanyukov** [comment]
@Eugeny Could you add 'reconnect' menu item on a tab? 
Sometimes I just want to have a force reconnect option

**Comment by spanyukov** [comment]
> > This was closed with a fix. The reconnect button is available in the terminal bar if a session was disconnected.
> > ![image](https://user-images.githubusercontent.com/161476/84438761-5c4dc200-ac37-11ea-9f29-dd3ca4d87f6a.png)
> 
> I just tested this on my terminus and I do not get any reconnect button. it will give a toast ERR message and close the tab.

I have the same behaviour.

**Comment by diptimanbasak** [comment]
Do we have a solution for this yet? I an using terminus and need "reconnect" option badly.

**Comment by martinzca** [comment]
This one could be really useful, as if your connection drops you will still keep your "screen" and with simple "restart" you continue where you left of. ExtraPutty got this feature, but you have to sacrifice everything else :D

**Comment by mirismaili** [comment]
@martinzca 
I installed the latest release, but I don't find `reconnect` button!

![image](https://user-images.githubusercontent.com/15800189/98296837-c2f9c080-1fc8-11eb-879a-e7199b358c41.png)

![image](https://user-images.githubusercontent.com/15800189/98296910-e1f85280-1fc8-11eb-9434-90163bc5eb34.png)

**Comment by martinzca** [comment]
@mirismaili 
Try the right corner of established SSH session.
![image](https://user-images.githubusercontent.com/21011656/98631106-4f87e400-2325-11eb-95bc-1a79ec7185b7.png)

**Comment by mirismaili** [comment]
@martinzca 
Oh! Thanks. I didn't hover on that "three dots" icon, at all!

**Comment by milindpatel63** [comment]
Have i misconfigured something, cause when i  reconnect, tabby initiates a new ssh session, and my previous session is gone.
