### ISSUE TITLE
Terminal Session Freezes with Large text output

### ISSUE THREAD

**Issue by criddell94** [Eugeny/terminus#763]
The terminal session seems to freeze with large (and sometimes quick) text output from a command or script. Running on Windows 10.

**Comment by telefax** [comment]
I have this problem frequently in Macos Catalina 10.15.2 with termius 4.9.20. I have about 7 tabs open and quite freqently termius freeze for 10s or more at a time.
Doesn't really matter if there are much output or not in the terminals.
Any way to troubleshoot this?
