### ISSUE TITLE
Add ability to pass command to shell

### ISSUE THREAD

**Issue by JacobDB** [Eugeny/terminus#77]
Just trying this out on Bash on Ubuntu on Windows, seems like a good replacement for Hyper, since I've been having problems with that.

If you run `bash` directly, you end up at your user directory (i.e. `/mnt/c/Windows/Users/Jacob`), but personally I prefer to start in `~` (`/home/jacob`). I can do this by running `bash ~`, so it'd be awesome if you just added the ability to pass parameters to the shell on launch.

**Comment by Eugeny** [comment]
Done in the latest Alpha.

**Comment by janwerner** [comment]
Just installed Terminus and like it so far. Could you elaborate on how passing a command to Terminus works?

I'd like to create shortcuts that would open a new tab in Terminus - something like

<path>\Terminus.exe powershell.exe -c ssh user@host

As it is, this just opens the default shell configured in Terminus settings and nothing else happens.

**Comment by Eugeny** [comment]
@janwerner: @JacobDB meant adding arguments to the "Custom shell", but feel free to open a separate ticket to pass commands on CLI.

**Comment by janwerner** [comment]
@Eugeny  Ah, sorry, I misunderstood that.
