### ISSUE TITLE
Can't use CTRL-h, is treated as a backspace in WSL

### ISSUE THREAD

**Issue by 0Petya** [Eugeny/terminus#770]
I use neovim in WSL, and to navigate between my split windows, I use CTRL-{h, j, k, l}.

The problem is that CTRL-h is treated as a backspace. It is not being mapped in my hotkeys. Here is a screenshot of `showkey -a` where the first line is me typing CTRL-h and the second line is me typing backspace. You can see it's being treated as the same key:

![image](https://user-images.githubusercontent.com/6667435/56315177-abc05d00-611c-11e9-9382-4b2e1d98c660.png)

**Comment by Eugeny** [comment]
This should work properly with ConPTY enabled

**Comment by 0Petya** [comment]
How do I enable ConPTY? I tried searching for that but can't find any way to do so.
Seems like it should be in the Shell settings, but here's all I see.
![image](https://user-images.githubusercontent.com/6667435/56674894-7bc70b80-6680-11e9-9480-fa8839a66bb0.png)

**Comment by Fuzzier** [comment]
Cannot remap <ctrl-h> to other commands for Vim/NeoVim in Tabby, even if ConPTY is enabled.
However, Windows Terminal works.
