### ISSUE TITLE
Copy from console in windows

### ISSUE THREAD

**Issue by jlanza** [Eugeny/terminus#78]
Right now it is possible to paste text from outside the console, but when trying to copy text (i.e. the output of a command executed) it is not possible.
I'm using window 8.1.

Thanks

**Comment by swichers** [comment]
Use `Ctrl + Shift + C` after highlighting text.

Ideally it would support the "copy on highlight" and "paste on right click" style of functionality other terminal apps do.

**Comment by Eugeny** [comment]
@swichers TBH this is quite PuTTY-specific. You're welcome to open a separate ticket to add this as an option though!

**Comment by swichers** [comment]
The default Windows command console behaves the way I mentioned. As does PowerShell. iTerm2 on macOS copies on highlight and I believe has an option for paste on right click. 

Just pointing out this isn't only a PuTTY thing. It's a somewhat common feature in shells.
