### ISSUE TITLE
Saved password not used upon disconnect

### ISSUE THREAD

**Issue by agilly** [Eugeny/terminus#783]
I have a SSH session with a saved password. When I exit the session and close Terminus cleanly, there is no issue and I can reconnect without re-entering the password.

However, when the session is interrupted (for example because the computer goes to sleep), I am asked again for the password when I reconnect the session.

This behaviour was observed in Terminus for Windows.

**Comment by Eugeny** [comment]
Please retry with the latest release, thanks.

**Comment by agilly** [comment]
Just tried with 1.0.79, the same behavior still persists:

- I connect to a server using a saved password.
- I trigger a connection error by disabling my network interface.
- The connection is lost.
- Upon reconnect, the stored password is wiped and the software asks for it again.
