### ISSUE TITLE
Failed while using ecdsa?

### ISSUE THREAD

**Issue by ghost** [Eugeny/terminus#788]
Version: Alpha 1.0.75
Platform: Windows 10.0.17763.437

When I establishing a ssh connection using ecdsa, terminus like display this:
![image](https://user-images.githubusercontent.com/46526358/56879952-79ecb600-6a8d-11e9-9289-b6a139c632bd.png)
![image](https://user-images.githubusercontent.com/46526358/56880017-aef90880-6a8d-11e9-8973-946450185ac2.png)
![image](https://user-images.githubusercontent.com/46526358/56880022-b3252600-6a8d-11e9-83d1-43f3f8f3301f.png)

This problem only happen when using ecdsa.

**Comment by Eugeny** [comment]
ecdsa support has been added a while back
