### ISSUE TITLE
Shell arguments support for Command Prompt

### ISSUE THREAD

**Issue by NDelt** [Eugeny/terminus#790]
For example, in Visual Studio Code, I can add shell arguments like `["/K", "chcp 65001"]` to start terminal with code page 65001. But I couldn't find any options like that in Terminus.
I hope Windows shell arguments option would be added.

**Comment by Eugeny** [comment]
You can use additional arguments with the "custom shell" option.

**Comment by NDelt** [comment]
"custom shell" option looks like require a full path of terminal shell. Can you explain how do I use this?
