### ISSUE TITLE
Terminus Won't Load

### ISSUE THREAD

**Issue by Xedecimal** [Eugeny/terminus#792]
(Windows here)

Just upgraded to 76 and now Terminus will show it's splash screen but won't load past that. Empty progress bar. I've terminated it and cleared out my Roaming config. Used Everything to find all references hard-drive wise to Terminus, then Geek Uninstaller'd it and cleaned the registry of anything left over. Re-installed from the exe located on releases page (not Chocolatey or the such) and it just doesn't want to load anymore in this version.

**Comment by Xedecimal** [comment]
Also to add, installing the 0.76 Portable version does not load either.

**Comment by baflo** [comment]
+1

0.75 portable loads (I just upgraded from 0.73)

![grafik](https://user-images.githubusercontent.com/834350/56941605-caa7f180-6b15-11e9-8165-841b728a6dd7.png)

**Comment by 695137400** [comment]
yes ,my window10 not run

**Comment by zuozishi** [comment]
+1 Windows10 1903 not run

**Comment by marcinkepa** [comment]
+1 Windows 10 Pro 1809

**Comment by glen-84** [comment]
The `+1`'s are not helping – please 👍 the initial comment instead.

**Comment by NDelt** [comment]
And `Open Terminus here` option is not added to Windows context menu.

**Comment by Eugeny** [comment]
Fixed in A77
