### ISSUE TITLE
How can I add "Open Terminus here" to Windows 10 context menu manually?

### ISSUE THREAD

**Issue by NDelt** [Eugeny/terminus#794]
After re-installing Terminus for upgrading to 1.0.77, `Open Terminus here` option is not added to Windows 10 context menu.
Is there any way to add it manually?

**Comment by harvardchen** [comment]
Same question

**Comment by L96Github** [comment]
You can do it using the Registry Editor. Just be extra careful.

1. open `regedit`
2. go to `HKEY_CLASSES_ROOT\Directory\Background\shell`
3. On top go to `Edit > New > Key`
4. Rename the new key to `Open Terminus here`
5. Right-click on the new key and select `New > Key` and rename to `command`
     
``` 
You should have:
> HKEY_CLASSES_ROOT
>> Directory
>>> Background
>>>> shell         
>>>>> Open Terminus Here
>>>>>> command
```
6. Now right-click on the newly created `command` and select `New > String Value`
7. set the value name to `(default)`
8. double click on it and set the value data  to the path to `"<your terminus exe path>" open "%V"`


**NOTE:** make sure to use `""` as indicated when setting the value data.
Terminus path is usually something like: `C:\Users\YourUserName\AppData\Local\terminus\app-1.0.77\Terminus.exe`


Hope it helps, cheers!

**Comment by L96Github** [comment]
**Update:** in Alpha 78 the default installation path is: `C:\Users\YourUserName\AppData\Local\Programs\Terminus\Terminus.exe`

**Comment by NDelt** [comment]
@L96Github Thanks for the detailed answer!
But my installation path is `C:\Program Files\Terminus\Terminus.exe`.

**Comment by NDelt** [comment]
Same on Alpha 82.
