### ISSUE TITLE
Quick commands Plugin not working

### ISSUE THREAD

**Issue by rsolomonjr** [Eugeny/terminus#797]
When I click one of my quick commands it won't output to bash. 

Using latest alpha. 1.0.77.

**Comment by Eugeny** [comment]
fixed in terminus-quick-cmds 2.0.0

**Comment by michabbb** [comment]
pardon, but for me, this is **not** fixed: https://youtu.be/DPLQH53GJpQ
beside that, there is a "empty screen" 🐛

**Comment by Eugeny** [comment]
@michabbb please file this to the quick-cmds repo: https://github.com/Domain/terminus-quick-cmds/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
