### ISSUE TITLE
[Win10] Terminus won't start properly

### ISSUE THREAD

**Issue by mrtzlbm** [Eugeny/terminus#798]
I tried to upgrade from 1.0.73 to 1.0.77. When I started Terminus it only showed up as process in task manager but the app window never opened up (rebooted etc.). I tried to downgrade to 1.0.73 but I still have the same issue :(

**Comment by ozligia** [comment]
Eventually it loads, but take way too much time to do it. Takes about 37 seconds to show up GUI
Win10 x64 1809 17763.437, m2 SSD, Core i5-9600, 16GB RAM

**Comment by mrtzlbm** [comment]
It never loads for me, all I see is the two processes in task mgr.

**Comment by a31amit** [comment]
I have noticed the same problem.

**Comment by AllenWilliamson** [comment]
I had the same issue on Win10. After deleting `USER\AppData\Roaming\Terminus` It started working for me again.

**Comment by mrtzlbm** [comment]
@AllenWilliamson Thanks, that fixed it. Lost all saved connections and configuration though.

**Comment by TheMinecraftExplorer** [comment]
@AllenWilliamson tysm, i was struggling :D

**Comment by Eugeny** [comment]
To expand on this, unless the config file itself is the problem, you can delete everything *but* `config.yaml` in that folder

**Comment by LoXR** [comment]
Having to re-open this, did what @AllenWilliamson but that only just removes login details it seems. I close the program and re-open and nothing opens. Im having to go into task manager to end all Termius services just to get the program to start back up again.

**Comment by Eugeny** [comment]
@LoXR fyi Termius is a different project.
