### ISSUE TITLE
Jump To Next Word

### ISSUE THREAD

**Issue by joshuahwang12** [Eugeny/terminus#802]
Version: 1.0.77
Platform: win32 10.0.17763
Plugins: relaxed-theme

The shortcut to jump to next word and jump to previous word is not working

**Comment by jordiortegon** [comment]
Hi!

I just started using Terminus and I am having a similar issue. In the Powershell terminal whenever I try to hit the hotkeys: Jump to next word, Jump to previous word, Delete previous word, etc. I just get a print in the screen (i.e: for Jump to next word I get an 'f' in the screen)
