### ISSUE TITLE
SSH Connections can't login with Google-authenticator 2FA

### ISSUE THREAD

**Issue by eallion** [Eugeny/terminus#803]
### SSH Connections can't login with Google-authenticator 2FA

When i add an SSH server in `'Setting'` - `'SSH'` - `'Connections'` - `'+ Add connection'`, 
I didn't find a place to save the 2FA verification code, or option about that.
Can you provide this feature later?

**Comment by eallion** [comment]
thank you

**Comment by TheOpenDevProject** [comment]
How would this work since 2FA codes are not static but generated?
