### ISSUE TITLE
[Bug] Start as admin auto-closes (Wrong DLL Versions included?)

### ISSUE THREAD

**Issue by jleechpe** [Eugeny/terminus#806]
Running Terminus 1.0.77 on Windows 10 (1809 build 17763.475) when trying to open Powershell as Admin from the context menu (or as a profile) it appears and then immediately closes.  Installed by downloading `terminus-Setup-1.0.77.exe` from the releases page.

I've tried both with and without ConPTY support and had no success (as well as disabling UAC prompts)

Trying to run `app-1.0.77/resources/extras/UAC.exe` gives an error saying I do not have `MSVCP140D.dll`, `ucrtbased.dll` and `VCRUNTIME140D.dll` on my machine.  Googling for those DLLs says that they are the Debug versions rather than the release version.

Was this version released off the Debug DLLs rather than the Release ones by accident?

**Comment by Eugeny** [comment]
True - good catch!
