### ISSUE TITLE
Feature request: Add an Option for a blur background image

### ISSUE THREAD

**Issue by Hobart2967** [Eugeny/terminus#814]
It's a cool thing that you can have a semi-transparent window, but it would be even cooler to have some blurred background image, (which can differ from the desktop background.

Here is how it should look (reproduced minimizing all windows, showing my desktop background):
https://i.ibb.co/HXWz661/Capture.png

**Comment by IgnusG** [comment]
Certainly an idea worth exploring

![image](https://user-images.githubusercontent.com/6438760/59555518-ed05a980-8fb3-11e9-8b00-0277e6242c41.png)

**Comment by Hobart2967** [comment]
Great! Thanks!
