### ISSUE TITLE
button unresponsive

### ISSUE THREAD

**Issue by ningnnw** [Eugeny/terminus#8167]
Version: 1.0.196
Platform: macOS arm64 21.6.0
Plugins: docker
Frontend: xterm-webgl

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/124015827/228782301-f60f5f9f-133e-4c83-87ba-1cd7795fb8e8.png">
There is no response to clicking the above buttons

**Comment by ningnw** [comment]
Sorry, it's the error caused by the docker plugin
After I disabled the docker plugin and restarted, it returned to normal
