### ISSUE TITLE
Stuck on startup when hotkey toggle-window set to nothing

### ISSUE THREAD

**Issue by scottbilas** [Eugeny/terminus#817]
I don't want a global hotkey for Terminus, so I have `toggle-window: {}` in my hotkeys section of my config.

This causes Terminus to get stuck on startup. The little loading bar goes all the way to the right, and then Terminus sits there just idle, 100% loaded. I have to kill the process.

My workaround is to temporarily remove the `toggle-window` line from config, load Terminus, then add it back.

**Comment by Eugeny** [comment]
Which version are you on? Can't reproduce with A77

**Comment by scottbilas** [comment]
Yes I'm on A77. This occurs on two separate machines for me. How else can I help diagnose?

**Comment by Eugeny** [comment]
Check if there's anything in the debug console: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by scottbilas** [comment]
It doesn't make it far enough to open the debug inspector. Freezes here:

![image](https://user-images.githubusercontent.com/964720/58026679-485c8d00-7b17-11e9-86cc-e9f612e4a14e.png)
