### ISSUE TITLE
Add shortcut to temporary maximize panel

### ISSUE THREAD

**Issue by IgnusG** [Eugeny/terminus#819]
A terminal I was using before had a cool feature which would temporary "maximize" the panel  via a shortcut so other panels aren't visible. Possible uses for this are:
- Temporary "maximizing" vim editor
- Temporary "maximizing" output of scripts

Pressing the shortcut again restored the panels so all of them were visible again.

Before Pressing anything:
![Annotation 2019-05-15 185731](https://user-images.githubusercontent.com/6438760/57794238-7cb10180-7743-11e9-9e7e-fbc63ca3a55a.png)

After pressing toggle maximize panel shortcut:
![Annotation 2019-05-15 185930](https://user-images.githubusercontent.com/6438760/57794286-96eadf80-7743-11e9-8bcd-8761f9735c9f.png)

After pressing the toggle maximize shortcut again:
![Annotation 2019-05-15 185731](https://user-images.githubusercontent.com/6438760/57794222-73c03000-7743-11e9-9115-f5b7dee8f880.png)

**Comment by TimoSta** [comment]
Might be interesting to even remove the tab bar in case a panel is maximized, to make it obvious that there's more to the tab than the one panel.

Or even go one step further and make the panel completely full-screen?

---

I believe the default shortcut for this in a few other apps is `alt + enter`.

**Comment by IgnusG** [comment]
I probably wouldn’t maximize the window since that might be confusing to the user. They can maximize it themselves independently of this feature. 

But an indicator that a panel is maximized is a good idea. I would go with something other than hiding tabs. Maybe an outline or some indicator in the tab? What do you think?

**Comment by Pauldb8** [comment]
This ! Please, it is the only feature that I miss from other terminal ! You would have the perfect terminal if you did this ! Please :). By the way thank you for the hard work, beautiful and working terminal, nothing more !
