### ISSUE TITLE
enable re-arranging tabs

### ISSUE THREAD

**Issue by tswitkowski** [Eugeny/terminus#82]
Please allow re-arranging tabs like gnome-terminal has

Gnome terminal allows dragging tabs (even to a new window, but that's another Feature Request), via the mouse or via keyboard shortcuts (ctrl-shift-pgup/dn)

**Comment by DRSDavidSoft** [comment]
@Eugeny Any updates on this one?

**Comment by dbkaplun** [comment]
This is the feature preventing me from switching to Hyper, and the reason I can't switch to Terminus. Patience is a virtue I suppose!
