### ISSUE TITLE
sz rz command cannot use while connected to host via ssh

### ISSUE THREAD

**Issue by RaphaelTFool** [Eugeny/terminus#837]
Version: 1.0.77
Platform: win32 6.1.7601
Plugins: altair, clickable-links, quick-cmds, scrollbar, shell-selector, theme-gruvbox, theme-windows10, title-control
sz command:
![image](https://user-images.githubusercontent.com/19533739/58223236-75918100-7d4b-11e9-88be-c27b02a3d5b4.png)

rz command:
![image](https://user-images.githubusercontent.com/19533739/58223304-b093b480-7d4b-11e9-8872-7fca1bff36d2.png)

and then, the window get no response......

**Comment by daya-prac** [comment]
I think this is a good suggest

**Comment by dangerose** [comment]
sz rz is commonly used and it would be perfect if terminus support it
