### ISSUE TITLE
SSH session and function/keypad keys are not working.

### ISSUE THREAD

**Issue by marcinbojko** [Eugeny/terminus#838]
Version: 1.0.77
Platform: linux 4.18.0-20-generic
Plugins: altair, clickable-links, quick-cmds, save-output, scrollbar, shell-selector, theme-gruvbox, title-control

When connected via ssh (xterm/hterm) alike, END/HOME/PageUp/PageDown seems to not working properly.

**Comment by quoidautre** [comment]
Hi,
Same issue for me, only in SSH. In "default' command line, it's working.

F.

**Comment by jbelien** [comment]
I have the same issue.
This is a duplicate of #787 though :)

**Comment by Eugeny** [comment]
Duplicate of #787
