### ISSUE TITLE
Error: Can't open display: (null)

### ISSUE THREAD

**Issue by infinitydon** [Eugeny/terminus#843]
Hi,

I am using terminus to SSH into a Linux VM, so I tried to paste some texts from my Win 10 clipboard into the SSH session using pbpaste but I got the following error:

**Error: Can't open display: (null)**

Am not sure if this has to do with some settings or should be a feature request.

Also echo $DISPLAY shows nothing:

```
$ echo $DISPLAY

```

**Comment by Eugeny** [comment]
I think the error is missing in your ticket.

**Comment by infinitydon** [comment]
I have updated the post now.

**Comment by Eugeny** [comment]
Duplicate of #630

**Comment by Eugeny** [comment]
Terminus doesn't support X11 forwarding at this moment
