### ISSUE TITLE
dont't open terminus [win10]

### ISSUE THREAD

**Issue by joseshiang** [Eugeny/terminus#844]
use terminus settings click right after win10 desktop terminus disappear and appear bottom tab click don't open ! eg:
![image](https://user-images.githubusercontent.com/19600894/58318131-c1c2eb00-7e49-11e9-8316-39869b9030b3.png)

**Comment by RunEnd** [comment]
I also encountered the same problem.

**Comment by MLefebvreICO** [comment]
Same problem here ..

**Comment by Jipem** [comment]
I had the same problem, which I managed to solve by modifying the file %APPDATA%/terminus/window.json where "x" was at -xxxxx (so very off screen). By modifying "x": 0, the problem has been fixed.

**Comment by MLefebvreICO** [comment]
> I had the same problem, which I managed to solve by modifying the file %APPDATA%/terminus/window.json where "x" was at -xxxxx (so very off screen). By modifying "x": 0, the problem has been fixed.

Thanks, here it was my `y` that was way off .. Maybe because I have a vertical screen .. who knows.

**Comment by Barokai** [comment]
had the same problem, but in combination with dock: right in config.yaml (same directory - just remove the line and edit the x value as mentioned in the comment above when terminus is closed.
