### ISSUE TITLE
Consider turning off Google Analytics by default

### ISSUE THREAD

**Issue by crispinb** [Eugeny/terminus#845]
Many people (rightfully or not) dislike Google Analytics, so it seems a bit dubious to have it switched on by default. You probably should consider turning it off, or disclosing on first run that it is initially on

**Comment by Eugeny** [comment]
Added a welcome tab that will present the analytics on/off switch on each start until the user explicitly disables the welcome tab.

Analytics won't be enabled (no matter what the setting is) until the user clicks "do not show again" on the welcome tab.
