### ISSUE TITLE
Malayalam Language support  Issue

### ISSUE THREAD

**Issue by mujeebcpy** [Eugeny/terminus#87]
The language Malayalam (ml) is not working fine in Terminal. ്+zwj  is not recognizing. 

![image](https://user-images.githubusercontent.com/24728052/27894533-521aed80-622a-11e7-8e30-b3dcc7870e33.png)

**Comment by Eugeny** [comment]
Should be fixed in the latest Alpha, please confirm

**Comment by Eugeny** [comment]
Closing due to the lack of activity. Please feel free to reopen if the issue is still relevant!
