### ISSUE TITLE
Pass an argument to start on a specific directory.

### ISSUE THREAD

**Issue by Pitu** [Eugeny/terminus#90]
Just like cmd or powershell have the possibility to open a new window on the given folder when opening from a context menu by passing the `'%V'` argument to the executable, it would be nice to have this feature and open a new tab on Terminus on the desired path.

**Comment by eelsweb** [comment]
It would be great if Terminus starts working with [this](https://packagecontrol.io/packages/Terminal).

**Comment by Pitu** [comment]
Thanks for the update on this. How exactly should I pass the directory I want the tab to open in? I tried with the following but all it did is focus on the Terminus window without opening a new tab.

```
PS C:\Users\Dev\AppData\Local\terminus> .\Terminus.exe C:/
PS C:\Users\Dev\AppData\Local\terminus> .\Terminus.exe "C:/"
PS C:\Users\Dev\AppData\Local\terminus> .\Terminus.exe -"C:/"
PS C:\Users\Dev\AppData\Local\terminus> .\Terminus.exe --"C:/"
```

**Comment by Eugeny** [comment]
`.\Terminus.exe C:\`

**Comment by Pitu** [comment]
That doesn't seem to work for me on Alpha 20 https://lolisafe.moe/vo1KIdOW.mp4

**Comment by PandawanFr** [comment]
Not working for me either. https://gyazo.com/893da6d25f19db1755cd373215a91452
(Windows 10, Alpha 20)

**Comment by GoBrianGo** [comment]
I can't open the path with the cmd '.\Terminus.exe C:\'
