### ISSUE TITLE
Cursor keys not working in Git Bash

### ISSUE THREAD

**Issue by koraktor** [Eugeny/terminus#91]
Cursor keys cannot be used for scrolling in e.g. `vi` or `less`. They work at the prompt, though.

Environment:

- Windows 7 (64 bit)
- Terminus 1.0.0-alpha.16
- Git Bash

**Comment by csrgxtu** [comment]
cursor keys means you r trying to scroll down with keyboard shortcut 'j' or some others?

**Comment by koraktor** [comment]
No, `J` and `K` are working. Arrow keys are not.
