### ISSUE TITLE
support for german language

### ISSUE THREAD

**Issue by AnotherCoolDude** [Eugeny/terminus#93]
Terminus is not able to print out letters like 'ä', 'ö' or 'ü'. I am getting this error message:

![bildschirmfoto 2017-07-06 um 11 59 39](https://user-images.githubusercontent.com/11141338/27906154-acbb97d6-6242-11e7-9210-4bf69229a99d.png)

**Comment by Eugeny** [comment]
This is an error in your Python application, not Terminus.
