### ISSUE TITLE
Ram usage

### ISSUE THREAD

**Issue by calvin-evans** [Eugeny/terminus#940]
RAM usage just creeps up and up - this is with 1 idle tab open after about 4 hours since I booted the computer:

Using: Ubuntu 19.04, version: 1.0.77

![image](https://user-images.githubusercontent.com/1681236/58350653-71a25380-7e5e-11e9-8c97-e89d998a23d8.png)

**Comment by calvin-evans** [comment]
bump

**Comment by Hammster** [comment]
Could you provide the following information? It helps to pinpoint the source of the issue:

- How many child processes are running
- Plugins
- Theme

My wild guess is that #1263 is the culprit, but it could origin from something else as well.
