### ISSUE TITLE
‘Ctrl + L’ behaves differently from 'clear' command

### ISSUE THREAD

**Issue by DalekFrog** [Eugeny/terminus#948]
Version: 1.0.77
Platform: win32 10.0.17763
Plugins: none

In Hotkeys, ‘Ctrl + L' has been set to clear terminal.

When I use ‘Ctrl + L', It will clear the screen, but once i type or input any key ,the cursor will go back to the position where I use  ‘Ctrl + L' before.

BUT, everything is fine with `clear` command

By the way, I use zsh on WSL(ubuntu)

**Comment by jackdw-concur** [comment]
Seeing this with multiple shells on Win10 as well.

**Comment by hiro-yam** [comment]
I having same issue on win10 (WSL/Ubuntu).
![output](https://user-images.githubusercontent.com/1026472/58431130-5e55e900-80e7-11e9-9938-0d7d80bca4e5.gif)

**Comment by lazb** [comment]
Same here. Good that you point out that clear is working at least. 
CTRL+L and jumping after that to the line where I was and leaving everything else blank is pretty annoying.

**Comment by kpbrown15** [comment]
Same issue. Unsetting the hotkey in settings fixes the issue though, and I'm still able to CTRL-L to clear. .

**Comment by txstan77** [comment]
Changed the CTRL-L hotkey to CTRL-SHIFT-L which resolves the problem for Linux. The local terminal can then be opened with CTRL-SHIFT-L.
