### ISSUE TITLE
HTML <input type="text">-like input

### ISSUE THREAD

**Issue by brandonros** [Eugeny/terminus#955]
I think it'd be really cool if I could use all kinds of keyboard shortcuts in a terminal for things like Ctrl+A (select all), Shift+arrow keys (to select portions), etc.

Is there a way to present a <input type="text"> (which allows modern day keyboard/mouse usage), then paste it into the terminal?

**Comment by Eugeny** [comment]
This would have to be implemented by the shell that's running inside the terminal, not the terminal itself. There were attempts to do this, e.g. at https://github.com/railsware/upterm
