### ISSUE TITLE
Text becomes invisible after a theme change

### ISSUE THREAD

**Issue by pierrenel** [Eugeny/terminus#956]
Version: 1.0.77
Platform: darwin 18.0.0

After a fresh install I can see the command line, but when I change themes/colour schemes, the text vanishes:

![image](https://user-images.githubusercontent.com/26219/58378481-eaa3c700-7f94-11e9-9d83-07585749bd42.png)

**Comment by jonorozcoc** [comment]
The same.
OS Version: Windows 10
Terminus Version: 1.0.78

**Comment by BuairtRi** [comment]
For me, I don't need a theme change. I open keep 2-3 tabs open in a second window. When I toggle between them, this happens almost all the time. When I scroll, sometimes the text flickers back into view, or if I type something new I see the next text. It's fairly frustrating.

Windows 10
Terminus 1.0.82 (but I've seen the problem for a lot longer than this)

**Comment by Eugeny** [comment]
@BuairtRi your case is #729
