### ISSUE TITLE
Windows 10 context menu broken in build 78

### ISSUE THREAD

**Issue by carlsc2** [Eugeny/terminus#959]
Running Windows 10, recently updated to Terminus 1.0.78; now when I right click a folder and select "Open Terminus here" it will kill my currently open terminus application. If I select the option again, it will restart Terminus and open a tab in the correct location.

**Comment by jwalsh2NU** [comment]
confirmed - same behavior seen.  Win 10 v 1903

**Comment by seriiix** [comment]
Same on 1809

**Comment by jinkang23** [comment]
Still broken on build 79

**Comment by jinkang23** [comment]
still broken on alpha build 81

**Comment by Eugeny** [comment]
Fixed in c180f3faff72cc697f7597935f835a8f3fdbd984
