### ISSUE TITLE
 Incomplete Display of the First Icon  on macOS

### ISSUE THREAD

**Issue by Cz200OK** [Eugeny/terminus#9599]
**Describe the problem**:
[I am currently experiencing an issue with Tabby terminal emulator where the first icon  is not fully displayed. It appears to be clipped or truncated..]

**To Reproduce**:
1. Open Tabby terminal emulator.
2. Ensure that the shell is set to Zsh.
3. Apply the Powerlevel10k theme to the Zsh configuration.
4. Observe the first icon  after the theme has been applied and the terminal has been restarted.

****
Tabby Version: 1.0.207
macOS Version: 14.4.1
powerlevel10k: stable 1.20.0 (bottled)

**Screenshots**
![screenshot-20240425-152905](https://github.com/Eugeny/tabby/assets/18591933/cbafe223-83b2-4c39-8b42-c9c58c15125a)

**Comment by piersandro** [comment]
Have you tried toe use the same font and size of the Terminal app?

**Comment by ZheCheng** [comment]
I can type font
