### ISSUE TITLE
unable to switch to root

### ISSUE THREAD

**Issue by x1nas** [Eugeny/terminus#961]
Unable to switch to root:
user@test-pc ~ $ su
Password: 
su: Authentication failure

Same command & password in simple terminal works well.

Terminus 1.0.78 clean install

**Comment by Eugeny** [comment]
Could you please compare the `env` between the two?

**Comment by jman43195** [comment]
I have the same problem, and I just wanna use the better (objectively & subjectively) terminal for my terminal stuff.

**Comment by Eugeny** [comment]
Please check again - this should be fixed in the latest release.
