### ISSUE TITLE
Color scheme selection is empty

### ISSUE THREAD

**Issue by jwalsh2NU** [Eugeny/terminus#969]
![image](https://user-images.githubusercontent.com/22819585/58486155-f0331580-812a-11e9-86fa-74648fc91dd7.png)

Upgraded to 1.0.78, and I am no longer able to change color schemes, it seems to be set to Material.  When I click in Colo Scheme is has no entries.  If I edit it tells me I am editing Material.

**Comment by IgnusG** [comment]
This is what I have in my config for a custom theme I use (works under the new version). 
<details>
<summary>Custom Color Scheme</summary>
<pre>
terminal:
  colorScheme: &ref_0
    name: Hardcore & Molokai Mix
    foreground: '#a0a0a0'
    background: '#121212'
    cursor: '#bbbbbb'
    colors:
      - '#1b1d1e'
      - '#f92672'
      - '#a6e22e'
      - '#fd971f'
      - '#66d9ef'
      - '#9e6ffe'
      - '#43a8d0'
      - '#ccccc6'
      - '#505354'
      - '#ff669d'
      - '#beed5f'
      - '#e6db74'
      - '#66d9ef'
      - '#9e6ffe'
      - '#51ceff'
      - '#f8f8f2'
</pre>
</details>  

Can you edit yours? Does editing work through the `Config File` settings option? Does this theme work for you?

**Comment by jwalsh2NU** [comment]
I can edit them, your scheme works.  It is just missing the default community-themes that used to be there.

**Comment by Eugeny** [comment]
@jwalsh2NU do you mean that you're missing the community-color-schemes plugin? Or did you just disable it?

**Comment by jwalsh2NU** [comment]
It is not disabled, just missing selections.  I tried to disable and reenable with no success.

**Comment by IgnusG** [comment]
Interesting. I'm actually missing all of them as well. Just mine is still there

**Comment by jwalsh2NU** [comment]
> It is not disabled, just missing selections. I tried to disable and re-enabled with no success.

@Eugeny Seems like it is not just me, should this be reopened?
