### ISSUE TITLE
It is recommended that you add shortcuts to each of the custom statements in Quick-cmd

### ISSUE THREAD

**Issue by iapplegenius** [Eugeny/terminus#977]
It is recommended that you add shortcuts to each of the custom statements in Quick-cmd, such as pressing "F1" and actually copying a script on the terminal that is like "sudo-i/n password***" #
https://mobaxterm.mobatek.net/features.html
https://mobaxterm.mobatek.net/img/moba/features/feature-macros.png
-----Macros support

**Comment by Eugeny** [comment]
Please submit quick-cmds issues to its repo: https://github.com/Domain/terminus-quick-cmds/issues
