### ISSUE TITLE
Ubuntu WSL Doesn't Open Proper Working Directory 1903

### ISSUE THREAD

**Issue by awincapaw** [Eugeny/terminus#978]
Since upgrading to Windows 10-1903 any new Ubuntu shell opens in the root directory, even though the working directory is set to open my home folder. When I open a new shell of any other WSL distro, it opens in my Ubuntu home directory.

Directory path:
![image](https://user-images.githubusercontent.com/38570061/58572191-d5cb6b80-8200-11e9-99d8-bcb044902352.png)
Result of opening a new Ubuntu shell:
![image](https://user-images.githubusercontent.com/38570061/58593064-95371680-822f-11e9-8480-8744c13a0d97.png)

Result of opening a new Kali shell:
![image](https://user-images.githubusercontent.com/38570061/58593049-8c464500-822f-11e9-9e59-25cd23b82a5a.png)

**Comment by IgnusG** [comment]
I was having a similar problem since the Alpha 78 update. See this issue https://github.com/Eugeny/terminus/issues/271#issuecomment-496601246. Maybe the workaround will help for now
