### ISSUE TITLE
How to get updates

### ISSUE THREAD

**Issue by jrock2004** [Eugeny/terminus#99]
Does the app itself check for newer versions and will update or do we have to reinstall to get updates? I am currently using this on Windows

**Comment by Eugeny** [comment]
Currently, there's no autoupdate feature, but it's planned.

**Comment by jrock2004** [comment]
So I just uninstall and reinstall app for now?

**Comment by Eugeny** [comment]
@jrock2004 you can just install the new versions over the old ones.
