### ISSUE TITLE
cursor blinks and cannot type commands.

### ISSUE THREAD

**Issue by Tatamethues** [Eugeny/terminus#996]
![360截图16570201479080](https://user-images.githubusercontent.com/34636866/58743189-8e8ee600-845f-11e9-8b63-9c1dbd2743d3.png)
![360截图1820042911013591](https://user-images.githubusercontent.com/34636866/58743190-8e8ee600-845f-11e9-86a0-4769ff978fef.png)

I have installed zsh and oh-my-zsh in wsl.

**Comment by LittleChengxuYuan** [comment]
I hava the same issue.

- install from scoop 
- first launch and default config
- want to open a powershell terminal
nothing show except cursor
![image](https://user-images.githubusercontent.com/17670639/58743595-3360f180-8467-11e9-9692-f449d4057a80.png)

**Comment by Eugeny** [comment]
Please open Devtools from Settings - Devtools and capture console log at the time of the issue

**Comment by LittleChengxuYuan** [comment]
> Please open Devtools from Settings - Devtools and capture console log at the time of the issue

Actually, after times restart, the termianl works well, so maybe it's down just in the first few times

**Comment by Tatamethues** [comment]
@Eugeny thanks for you help.
![360截图17571115264369](https://user-images.githubusercontent.com/34636866/58776245-2d504980-85fc-11e9-8ed3-720726ece3ce.png)

**Comment by Eugeny** [comment]
Could you please capture the log with a fresh nightly build?
