### ISSUE TITLE
Minecraft spacebar not working while running

### ISSUE THREAD

**Issue by orion-tran** [Eugeny/terminus#998]
While Terminus is running in any state (in/out session, minimized or in the taskbar) the spacebar key in Minecraft stops working all together. 

I’ve experimented a bit with this bug and it’s exclusively the space key, I’ve rebound my jump to V and it works perfectly fine, it’s only the space key (oddly enough) that stops working.

As soon as I exit Terminus (again, in any form wether it be in taskbar or minimized not in session) then my Minecraft space key works like magic once more.

I’m running Windows 10 with the latest installed release of Terminus

**Comment by Eugeny** [comment]
Deassign the default toggle-window hotkey in the settings.

**Comment by yfwz100** [comment]
`Ctrl+space` is the default binding for switching input method in some environment. Maybe a new key binding for 'toggle-window' should be used.

**Comment by orion-tran** [comment]
Thanks, as always
