### ISSUE TITLE
Ui messed up upon restarting after first launch

### ISSUE THREAD

**Issue by sachaw** [Eugeny/terminus#999]
Version: 1.0.78
Platform: win32 10.0.18908
Plugins: clickable-links

Looks normal after install, but subsequent launches looks like this:
![image](https://user-images.githubusercontent.com/11172820/58771914-e2333800-85f5-11e9-9031-a841655d9916.png)

**Comment by IgnusG** [comment]
Is the problem the white background on the title of the window?

**Comment by sachaw** [comment]
this is what it looks like after first install, and should look like: 
![image](https://user-images.githubusercontent.com/11172820/58842221-5d572580-86ac-11e9-9511-fd561758316f.png)

**Comment by IgnusG** [comment]
Have you tried toggling the different Window Frame options in the application settings?

**Comment by Eugeny** [comment]
I have a suspicion that a native window frame is not compatible with the fluent background

**Comment by sachaw** [comment]
@IgnusG Yes, I have, don't fix anything
@Eugeny It does work at first launch, and disabling it doesn't fix it.
